### ISSUE TITLE
Replies to poll appears in timeline as unsupported events during sending

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/element-android#1004]
<img width="213" alt="image" src="https://user-images.githubusercontent.com/9841565/74430502-484aad00-4e5d-11ea-9ac8-a354c19b187e.png">

<img width="214" alt="image" src="https://user-images.githubusercontent.com/9841565/74430518-500a5180-4e5d-11ea-9f0b-2b26ff01644b.png">

Event has a relates_to with the type "m.response"

**Comment by unclejay80** [comment]
Noticed the same. the more polls you have the more of these buggy lines you have in your room
![20200308_224644](https://user-images.githubusercontent.com/33184634/76171832-ddf10800-618f-11ea-86ec-97575bfc4691.jpg)
