### ISSUE TITLE
Collated notifications can't count

### ISSUE THREAD

**Issue by justdave** [vector-im/element-android#1009]
Where there are more than one notification, the collated version always says there's only one notification, no matter how many there are.
<img alt="Screenshot_20200213-151725_Discord" src="https://user-images.githubusercontent.com/307334/74477144-bbade800-4e78-11ea-860c-8d061bfabc45.jpg" width="400">

**Comment by justdave** [comment]
Interestingly, I just noticed on my tablet that I have the same three notifications, and it actually says there are three of them.  The main obvious difference is the tablet is Android 7 and the phone is Android 9.  They're both Samsung (Galaxy Tab S2 and Galaxy S8)

**Comment by bmarty** [comment]
There is no count in the notification on my device :/ running Android 10.

Can you confirm that you still have the issue? If yes, please feel free to re-open the issue.
