### ISSUE TITLE
Message sent to (encrypted) room that gets stuck gets sent to a different (unencrypted) room?

### ISSUE THREAD

**Issue by steef435** [vector-im/element-android#1034]
Reported by ecmuller:matrix.org in the Riot Web room, starting from https://matrix.to/#/!YTvKGNlinIzlkMTVRl:matrix.org/$9ra362_z1rYV-q4JTCIAZ8dOXp4LYgdgaKMBQAiTvZE?via=matrix.org&via=mozilla.org&via=privacytools.io.

IIUC a message got stuck in an e2ee roomas in #516. The message was then edited, which temporarily made it unstuck. Two days later ecmuller noticed on a different client that the original (unedited) stuck message got sent at a later time unencrypted to the riot web room (not the originally intended room).

Sounds impossible to reproduce, but thought I might create a new issue for it since it's rather unwanted behaviour.

**Comment by bmarty** [comment]
Thanks for reporting. I've read the discussion in the link you provided.
It's very strange. Let's see if it happens again.

**Comment by bmarty** [comment]
Let's consider it's fixed in Element Android 1.3.16 (see #516)
