### ISSUE TITLE
Sent message stuck at the bottom of the chat despite sending hours ago.

### ISSUE THREAD

**Issue by Flam3z** [vector-im/element-android#1055]
Version Info: 0.16.0

Device: Samsung S10
![Screenshot_20200223-182232_RiotX](https://user-images.githubusercontent.com/57234536/75122233-a0f22500-5669-11ea-8b6f-d967bfc9a290.jpg)

**Comment by aquatix** [comment]
I also have this issue, with a message that keeps getting stuck as latest sent, while it was sent in March.

**Comment by fbruetting** [comment]
Duplicate of #516 ?

**Comment by aquatix** [comment]
Looks like it, yes. Thanks for the reference!

**Comment by bmarty** [comment]
Should be fixed now (Element 1.0.10), please re-open if it's not the case
