### ISSUE TITLE
Use new ViewBinding build facility - open discussion

### ISSUE THREAD

**Issue by bmarty** [vector-im/element-android#1072]
Introduced in Android Studio 3.6

https://medium.com/androiddevelopers/use-view-binding-to-replace-findviewbyid-c83942471fc

<img width="694" alt="image" src="https://user-images.githubusercontent.com/3940906/75319356-d0bd4a80-586c-11ea-96e2-91e3c6122495.png">

There is no comparison about performance in this article, but findViewById is known to be faster than kotlin synthetics

Recipe:
- https://developer.android.com/topic/libraries/view-binding
- https://developer.android.com/topic/libraries/view-binding/migration

**Comment by aqulu** [comment]
This might be worth looking into again.

Butterknife has been deprecated for a while now (see [butterknife's README](https://github.com/JakeWharton/butterknife
)).
The `kotlin-android-extensions` plugin and Kotlin synthetics also have been deprecated recently, as stated in view-binding migration link above. From https://android-developers.googleblog.com/2020/11/the-future-of-kotlin-android-extensions.html:
> The deprecation period starts with Kotlin 1.4.20, released today. android-kotlin-extensions will be removed in a future Kotlin release during or after September 2021.
