### ISSUE TITLE
When user updates their avatar, Element tells that the user has joined the room

### ISSUE THREAD

**Issue by bmarty** [vector-im/element-android#1080]
When displaying the source of the event, the `unsigned_data` with `prev_content` are missing.

Riot-Web does it right, and `unsigned_data` is there

**Comment by bmarty** [comment]
This is old be maybe still an issue, first work will be to try to repro with the latest Element :).

**Comment by daniellekirkwood** [comment]
@ericdecanini asked "Does this effect when the user sets their avatar for the first time, or only second time"

**Comment by ericdecanini** [comment]
Tested this and it seems like the issue's already fixed. It's possible that it was fixed in https://github.com/vector-im/element-android/pull/5618 which was released in v1.4.12

![Image](https://user-images.githubusercontent.com/20701752/172153059-99806408-167f-4dfe-ad37-a9786ec61764.png)
