### ISSUE TITLE
Certain rooms still seen on the sidebar, despite not being in the room anymore.

### ISSUE THREAD

**Issue by Flam3z** [vector-im/element-android#1094]
Version: 0.17.0
Device: Samsung S10

**Comment by bmarty** [comment]
Yes, this is quite a semi-expected feature. You may want to join the room again using the side bar.
If you don't, the room will be kick out by itself after you navigate to any 20 other distinct rooms.

I think there is the same semi-issue in riot-Web as well.

You could add something to cleanup the side bar anyway, or even an option to hide left rooms...
