### ISSUE TITLE
ux is not clear when you don't have writing permissions 

### ISSUE THREAD

**Issue by Timmaks** [vector-im/element-android#1101]
On the chat.mozilla.org web instance you see in the textinput field that you can not send a message in a room but on riotx you don't see that message.
It looks like you can post a message but after sending it, it is turning red. 

I expected that there wouldn't be a inputfield in a room for  users with no rights or like on the web version a notification

**Comment by bmarty** [comment]
Yes, thanks for reporting. This is not supported yet in RiotX, but it will definitely be implemented soon™.

**Comment by arunsathiya** [comment]
I wanted to note the same behaviour. 👍🏽 Noticed on [#riot-web-announcements:matrix.org](https://matrix.to/#/!bijaLdadorKgNGtHdA:matrix.org?via=matrix.org&via=mozilla.org&via=privacytools.io).

**Comment by bmarty** [comment]
This is now implemented (since a few versions now)

Example in the room Element Web Announcements:

<img width="372" alt="image" src="https://user-images.githubusercontent.com/3940906/100633141-f90f3380-332d-11eb-9463-aa5a32945474.png">

**Comment by Timmaks** [comment]
great, thanks!
