### ISSUE TITLE
Ability to join rooms via matrix.to links

### ISSUE THREAD

**Issue by aaronraimist** [vector-im/element-android#1113]
There is some initial support for matrix.to links, https://github.com/vector-im/riotX-android/issues/57 https://github.com/vector-im/riotX-android/pull/706, but joining rooms via matrix.to links hasn't been implemented yet.

https://github.com/vector-im/riotX-android/blob/f106f92d7edb9592653e2a68c507c8cec1be4280/vector/src/main/java/im/vector/riotx/features/navigation/DefaultNavigator.kt#L110-L116

**Comment by frandavid100** [comment]
I would say this should be closed? I just opened a matrix.to link on RiotX.

**Comment by avalenn** [comment]
RiotX can open some matrix.to links but not join new rooms which is the main use of those links as if we already joined the room we don't really need the link.
![RiotX-open-matrix to_1](https://user-images.githubusercontent.com/8639290/86512136-a58cce00-bdff-11ea-87ff-9b8d84fa8125.jpg)

**Comment by onurays** [comment]
I can confirm that with the last PRs you can join rooms via matrix.to links like https://matrix.to/#/#element-android:matrix.org

![matrix_to_join](https://user-images.githubusercontent.com/1254401/92588663-06be9b00-f2a2-11ea-99f4-be5d2da53ca5.jpeg)
