### ISSUE TITLE
better visibility of text reactions in dark theme

### ISSUE THREAD

**Issue by lub** [vector-im/element-android#1118]
It seems they are currently black font on black background (the last message has a small "TM" as reaction):

![Screenshot_20200308-020111_RiotX_dbg](https://user-images.githubusercontent.com/1029578/76154723-9613a780-60e1-11ea-865d-c65be736c3a5.png)

Maybe it makes sense to add a little pill like with mentions or to change the font color? I guess the former would also make it more obvious that you can click on it.

**Comment by bmarty** [comment]
We need a design decision, because emoji are supposed to be displayed on a white background. So what can we do with a black background?

**Comment by nadonomy** [comment]
Proposal for improving this here: https://www.figma.com/file/9up0KnsGVExlFCmeEK4thT/Emojis-on-dark-backgrounds?node-id=0%3A1
