### ISSUE TITLE
freeze old message in end of dialog

### ISSUE THREAD

**Issue by progserega** [vector-im/element-android#1119]
RiotX 0.17

1. send message "Звони", when bad network at 2020.03.05
2. close chat
3. After some times - I back to chat, send and receive some messages (2020.03.07), but message "Звони" was at end of dialog. I do not remove or delete it (long tap not show menu with "delete" - only info, when message was sended).
4. Only "clear cache and restart" - help me remove this freeze message.

![Screenshot_20200307-090010 png](https://user-images.githubusercontent.com/1297163/76155515-a2771f00-6138-11ea-93ff-4ecd5c2716a7.jpeg)

**Comment by progserega** [comment]
Such situation was for not sended image (at bad network). It was show in the end of messege-list with "!" it right top. And it is do not sended automaticaly, when network became good, and was not sended if I select "send unsended" in menu of room.

**Comment by BillCarsonFr** [comment]
Now possible to remove cancel / retry with #1889
