### ISSUE TITLE
In-app browser feature 

### ISSUE THREAD

**Issue by Flam3z** [vector-im/element-android#1126]
If a linked is pressed, a prompt should appear if we could use riotx in app browser or other browser apps we have installed.

**Comment by bmarty** [comment]
Personally I hate in-app browsers such has those implement by Twitter, or any other app. If I click a link I expect it to be opened by the default browser of the system.

**Comment by bahur142** [comment]
I also think that this is not appropriate for a chat application. Lets keep the app light, without unnecessary code and functionalities.

**Comment by dacruz21** [comment]
This is what the [Chrome Custom Tabs](https://developer.chrome.com/multidevice/android/customtabs) API is for. Chrome and Firefox both implement the API, so it respects the default browser of the user. Chrome Custom Tabs usually open faster and feel more integrated with the app that opened the link. There's also a button in the dropdown menu to switch to the full version of the browser.

**Comment by TR-SLimey** [comment]
Came across this whilst looking whether there were any open issues for Chrome Custom Tabs. FWIW I think it would be great to have this feature (custom tabs)  for all links, as it's pretty convenient and fast while still technically opening the link in the user's browser so user browser preferences are honoured. The feature could even be toggle-able in settings (even though custom tabs already have the option to open the full browser). What's great about this is that this is not only supported by Chrome but most other Chromium-based browsers like Brave.
