### ISSUE TITLE
Users oftentimes cannot be found

### ISSUE THREAD

**Issue by fbruetting** [vector-im/element-android#1154]
When creating a new room, I can type a user’s name into the first search box “filter by username or ID” or into the second search box which appears when I press “search by matrix ID”. And RiotX won’t find my contact (she created her new account sometime in the past hours). Riot-Web however finds her. I recognized this a lot of times in the past when users created a new account and want to connect. They immediately get a bad impression.

What actually is the difference between both search boxes? Sometimes one works, sometimes the other – and both say that you can search by ID. A better description would really be helpful!

**Comment by bahur142** [comment]
I think it is not yet implemented to add users by Matrix ID. That stops me for now to give RiotX to my friends. That will leave bad impressions to the new users.

Otherwise it is great client!

**Comment by AndreaPravato** [comment]
I have just met the same issue; to temporarily bypass it I have found the user and sent a direct message in https://riot.im/app/ , then switched back to riotX

**Comment by bmarty** [comment]
Adding user by matrix id is supported when creating a direct chat, and also now when inviting people to a room, and should work properly. RiotX is using the same request than Riot-Web, with an extra parameter (limit=50) though.
The first filter is showing only the people you know (i.e. you share at least one room with them), that's why on new accounts it could be a bit empty...

**Comment by fbruetting** [comment]
Weeks ago, newly registered users could not be found immediately. I tried this several times with different formats of the MXID (with and without `@`, with and without the server, by name, etc.). Users who were registered long before my search could be found, though.

Have you tried finding newly registered users? Then it’s resolved. :)

**Comment by bmarty** [comment]
Those screen has been reworked, I think this issue is not true anymore. Feel free to open it again if necessary
