### ISSUE TITLE
Add option to autoplay GIF

### ISSUE THREAD

**Issue by PolynomialDivision** [vector-im/element-android#1160]
There is no option that a GIF is directly auto-played in a chat. You only have the option to play it in full-screen mode after clicking on it.

**Comment by trymeouteh** [comment]
Please add a setting to autoplay GIF files on mobile, desktop and web. Right now the desktop/web client play GIFs automatally but on mobile you need to tap on the GIF to have it play.

Please allow autoplaying GIF images be enabled by default on all clients (mobile, desktop, web)

**Comment by HammyHavoc** [comment]
I'd also like to see auto-play videos too.

**Comment by Flam3z** [comment]
Should be the added the same as web with seperate options to auto play videos & gifs.

**Comment by adamrpostjr** [comment]
Allowing automatic animations would follow the norm for a messaging application.
