### ISSUE TITLE
Option to hide joins/parts

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-android#1231]
Both to avoid them triggering the room as unread, and to avoid cluttering up the timeline.

Could also hide kicks/bans separately to this. c.f

https://twitter.com/vinzv/status/1249757375306903554

**Comment by vinzv** [comment]
To give another examples of how annoying this can get:

![image](https://user-images.githubusercontent.com/74432/79320466-27104680-7f0a-11ea-835d-7c126548f830.png)

![image](https://user-images.githubusercontent.com/74432/79320264-d862ac80-7f09-11ea-985d-4b54fc02cb38.png)

**Comment by bmarty** [comment]
Related to #1102

**Comment by MichaelKohler** [comment]
also #870

**Comment by eras** [comment]
I would find the ability to make them not trigger room as unread as a sufficient feature already. But sure, why not both :).

**Comment by rajil** [comment]
Also #1718 please.

**Comment by paboum** [comment]
A question: with Element Web, I can just add to my `config.json`:
```
"setting_defaults": {
        "hideJoinLeaves": true,
        "hideDisplaynameChanges": true,
        "hideAvatarChanges": true
}
```
to have these settings preset for inexperienced users. How can I help them make things easier with Element Android?
