### ISSUE TITLE
'unverified login. was this you?' continues to pop up every few seconds

### ISSUE THREAD

**Issue by ericmigi** [vector-im/element-android#1251]
I can't verify one of my other devices because it's not on develop yet. Every time I dismiss the top green bar by swiping away, maybe 10-20 seconds later it reappears!

**Comment by ara4n** [comment]
https://github.com/matrix-org/riot-android-rageshakes/issues/10243

**Comment by matejdro** [comment]
This link appears private (we can't see it).

**Comment by ericmigi** [comment]
@matejdro you have the same bug?

**Comment by matejdro** [comment]
Yes

**Comment by matejdro** [comment]
I'm running https://github.com/vector-im/riotX-android/commit/b36759deb41d16090c88d011dc838b7642b5b7df now and it seems to have been fixed.

**Comment by bmarty** [comment]
It has been fixed, feel free to re-open the issue if it is not the case.
