### ISSUE TITLE
"Send image with default size" box shouldn't be an option for gifs

### ISSUE THREAD

**Issue by Cadair** [vector-im/element-android#1254]
If you don't tick the box when sending a gif it gets resized and turned into a still not an animated image. Unless the resizer can handle the gif it shouldn't be an option to de-gif it :grin:

**Comment by colalord** [comment]
Any update on this?  It still seems to be an issue.

**Comment by bmarty** [comment]
I'm fixing that. The option to send with original size is still there but will be applied only to static image.
