### ISSUE TITLE
Noisy notification only behave normally if app still open

### ISSUE THREAD

**Issue by mxvin** [vector-im/element-android#1282]
Hi,
I wanna report this problem related to app notification system
How to repro with riotx - webapp :

1. Send message to riotx, while phone is locked (screen off)
2. If your phone have notif LED, it will blink shortly one time and then disappear. No notification sound
--
3. Now, open riotx, go back to homescreen then lock the phone
4. Send message again to riotx, notification behave normally (blinking LED with notif. sound)
--
5. Remove RiotX from [recent app list ](http://www.androidpolice.com/wp-content/uploads/2014/10/nexus2cee_2014-10-17-21.05.55-1.png)
5. Send message to riotx
6. Notification not behave normally (No blink LED no Sound)

I mean, notification will not behave normally if we remove RiotX from recent app list, that's it.
My OS is Android 9; LineageOS 16
RiotX v0.18.1 latest release

Thanks

**Comment by Buntbart** [comment]
I have a Galaxy S5 with LineageOS 16 (Androud 9) and Element 1.0.4 (F-Droid). The LED blinks anyway when messages arrive, but the blinking stops after about 1 minute. So this is still not very useful.
