### ISSUE TITLE
Self-hosted jitsi support

### ISSUE THREAD

**Issue by manuroe** [vector-im/element-android#1294]
RiotX should be able to:

## Join a conference from any jitsi server

This requires to support Matrix Widget API v2 (https://docs.google.com/document/d/1uPF7XWY_dXTKVKV7jZQ2KmsI19wn9-kFRgQ1tFQP7wQ/edit#):

type | Required values in data
-- | --
m.jitsi | **domain (string)** - The domain of the Jitsi server (eg: “jitsi.riot.im”) **conferenceId (string)** - The ID of the Jitsi conference **isAudioOnly (boolean)** - True if the Jitsi conference is intended to be an audio-only call

## Create a conference using the jitsi domain defined by the user's HS or by the app
There are 2 level of settings which are described at 
https://github.com/vector-im/riot-web/blob/develop/docs/jitsi.md#configuring-riot-to-use-your-self-hosted-jitsi-server

## v1 compatibility
There is no need to be compatible with Matrix Widget API v1. Riot-Android is the last Riot which does not support v2.

**Comment by tomkel** [comment]
Relevant issue in riot-android
https://github.com/vector-im/riot-android/pull/3462

**Comment by bmarty** [comment]
Hello @BillCarsonFr can you confirm that it has been implemented by #1914 ?
