### ISSUE TITLE
"Encrypted message" is displayed, but message can actually be decrypted

### ISSUE THREAD

**Issue by bmarty** [vector-im/element-android#1302]
It happens sometimes that message are not decrypted on the timeline.
Long click on the message, and we can see that the message appear in clear on the bottom sheet.
Leave the room detail screen and come back: a new message is decrypted. Repeat the operation, to see one by one all the messages being decrypted, from the newer one to the older one.

Pb of cache invalidation? Refresh of the Epoxy list?

**Comment by rugk** [comment]
Yep, totally annoying, only seems to happen sometime though and I have not discovered it with the latest version (0.2.0) yet.

**Comment by MultiCoreNop** [comment]
Happend to me again just now (0.22.0).
Force-Stopping and deleting Cache on Android does not solve it. Currently I have no idea how to view this message (except for using Riot.im on my PC).

**Comment by MultiCoreNop** [comment]
Re-reading the password/key backup on RiotX did not help either.

**Comment by Destroyer** [comment]
It's gotten a lot worse after the latest update, pretty much every other message stays encrypted till I reopen the chat window.

**Comment by bmarty** [comment]
Seems to occur less often on Element 1.0.5. I think some changes have also fixes this.

**Comment by bmarty** [comment]
Will be re-opened if it re-appears
