### ISSUE TITLE
Unable To Decrypt Message Prompt appears despite verification. 

### ISSUE THREAD

**Issue by Flam3z** [vector-im/element-android#1340]
![Screenshot_20200506-163702_RiotX](https://user-images.githubusercontent.com/57234536/81225938-0b9fd500-8fb8-11ea-9e12-a28e7f65c406.jpg)

**Comment by enzingerm** [comment]
I have the same problem once in a while. A few days ago, my brother updated his Element Android. Despite our sessions being mutually verified, I couldn't read messages sent from his phone on neither of my sessions. Clearing the cache/restarting the app didn't help. We finally solved it by enabling the option "Never send encrypted messages to unverified sessions..." on his phone and then disabling it again.
