### ISSUE TITLE
Emoji picker UI

### ISSUE THREAD

**Issue by samuel-p** [vector-im/element-android#1396]
I would love to see an emoji picker in RiotX additionally to the text based emoji search. I heard from many users, that they are missing a picker like other Messengers like WhatsApp, Telegram have them. 

I found https://github.com/vector-im/riot-web/issues/1107, but would also like this feature in RiotX.

**Comment by jwsp1** [comment]
Stickers are currently in the attachment section but if riotX implements emoji picker, it should display stickers there too.
For me, attachments are something that come from another app (Pictures, Location Maps, Audio, Contacts,...). Stickers are/will be integrated in riotX and should therefore not be listed in attachments. But for now it's ok.
I think Telegram did that pretty well. Look at the bottom picker for Emoji, (GIF) and Sticker.

![photo_2020-05-25_20-24-25](https://user-images.githubusercontent.com/24477557/82835951-c2131d80-9ec5-11ea-8317-69204392b538.jpg)

**Comment by gabmert** [comment]
It seems some people don't have a keyboard which supports emojis and the emoji picker after `:` is a bit cumbersome. All the more if the persons don't know much about their phone in the first place. 
See https://github.com/vector-im/riot-android/issues/819 for a long and partly sidetracked discussion on this topic.

Thanks for all the work that lead to this already great app!

**Comment by Yajo** [comment]
This seems fixed in current beta build from google play, 1.0.12 [40100121] (G-b965)

**Comment by SimonBrandner** [comment]
I think that is [this](https://github.com/vector-im/element-android/pull/2514) PR. I belive this can be closed.

**Comment by github-tomster** [comment]
@ the ones using the code
this mentioned PR also ruins https://github.com/vector-im/element-android/issues/2944 the userexperience 🤦‍♂️ 
what was unnecessarily done is quite straight described here https://github.com/vector-im/element-android/pull/2514#issuecomment-748616710 🥇
