### ISSUE TITLE
Errors while registering via RiotX

### ISSUE THREAD

**Issue by MamasLT** [vector-im/element-android#1403]
1) When registering, after entering email, while waiting for confirmation, if you press BACK (stop registration process - Yes) - it still shows "please check your email"... It goes back only doing same thing second time.

2) It gets you back to the email entering window, but if you re-enter email (or use the same entered already) on it and press Next there will be an error: "developer error, call createAccount() method first"
So that means i have to go back a one more step manually, which brings me back to Sign In, SIgn Up page, and re-enter username and password to continue with registration.

**Comment by bmarty** [comment]
Related (duplicate?) #1132

**Comment by bmarty** [comment]
This is fixed in #3285 (EA 1.1.7)
