### ISSUE TITLE
Registering with numeric only id will fail and error is displayed wrongly on email field

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/element-android#1410]

**Comment by BillCarsonFr** [comment]
from chat

> hxuuejjdiifjrj
 Hey guys. Thanks for your work on Matrix and RiotX. Installed RiotX today on my mobile and it took me 10 mintues to actually sign up. Tried to sign up as a new user. RiotX insisted on an email despite saying its optional. Joke is on you I guess. Anyways, entered an email address, confirmed the account only to find out then that I cannot use numbers as a username. Nice. Why not telling me this right before I start the whole registration process? Tried to start all over. Didnt work with my email address any longer. Had to use another address then. 10 minutes just for signing up. Hope you can improve that. For now it's too high of a barrier to be used by ordinary mobile phone people

**Comment by BillCarsonFr** [comment]
mobile
![image](https://user-images.githubusercontent.com/9841565/82952649-ac772400-9fa9-11ea-9622-8b2871ed58ad.png)

web:
<img width="431" alt="image" src="https://user-images.githubusercontent.com/9841565/82952656-b26d0500-9fa9-11ea-8f84-8a8bc1584373.png">

**Comment by bmarty** [comment]
Riot-Web does not (sadly) show the error at when you enter the id with only digit, but shows it after you confirm Captcha, email, etc. True it is displayed at a better place though :)

Also it make request to register in a infinite loop when this error occurs, but I should report this issue in Riot-Web project...

<img width="1484" alt="image" src="https://user-images.githubusercontent.com/3940906/82958256-4abcb700-9fb5-11ea-8149-2b4be5f3560d.png">

**Comment by bmarty** [comment]
To fix the issue, I assume we can use https://matrix.org/docs/spec/client_server/latest#get-matrix-client-r0-register-available, hoping it will return the same error.

**Comment by bmarty** [comment]
Too bad

```bash
$ curl -X GET "https://matrix-client.matrix.org/_matrix/client/r0/register/available?username=1234567890"
{
    "available": true
}
```

**Comment by BillCarsonFr** [comment]
see https://github.com/matrix-org/synapse/issues/7576

**Comment by bmarty** [comment]
Now waiting for https://github.com/matrix-org/synapse/issues/8125 to properly manage this error and removing the temporary patch
