### ISSUE TITLE
Allow user to add custom "network" in room search

### ISSUE THREAD

**Issue by valkum** [vector-im/element-android#1458]
Currently there is no way to list/search rooms of a custom server. In #55 it was mentioned to add that, but it seems it was not implemented.

Riot Desktop seems to support that with providing "Add new server" in the drop-down list.

RiotX has the menu point change network where you can select your HS, all servers and matrix.org.
It would make sense to add this here as well.

**Comment by bmarty** [comment]
I think this is covered by [this TODO](https://github.com/vector-im/riotX-android/blob/f0aa34774e0b4fa35e0949472bfd97edd0926ab2/vector/src/main/java/im/vector/riotx/features/roomdirectory/picker/RoomDirectoryPickerFragment.kt#L39), but thanks for creating the issue.

**Comment by bmarty** [comment]
Implemented in Element Android 1.1.9
