### ISSUE TITLE
Redesign room setting bottom sheet

### ISSUE THREAD

**Issue by bmarty** [vector-im/element-android#1471]
<img width="408" alt="image" src="https://user-images.githubusercontent.com/3940906/84289966-655d6700-ab43-11ea-9247-2c83628e3b6a.png">

Note: Do not remove the top right icons (access to the room setting and the favorite toggle)

https://www.figma.com/file/M15i7l4PSPY1B5M7Zhu80H/Notifications?node-id=460%3A3299

**Comment by bmarty** [comment]
Product decision: it will be done after the release.

**Comment by langleyd** [comment]
Closing as superseded by newer designs in https://github.com/vector-im/element-android/issues/3654
