### ISSUE TITLE
Room notification settings

### ISSUE THREAD

**Issue by bmarty** [vector-im/element-android#1473]
<img width="492" alt="image" src="https://user-images.githubusercontent.com/3940906/84290494-064c2200-ab44-11ea-9df0-173025414a92.png">

https://www.figma.com/file/M15i7l4PSPY1B5M7Zhu80H/Notifications?node-id=0%3A1

**Comment by PhilGPk** [comment]
Is it possible to different notification tones in this dialogue? 
Use case: to enable different audible notifications for particular contacts.

**Comment by langleyd** [comment]
Closing as superseded by newer designers in https://github.com/vector-im/element-android/issues/3654
