### ISSUE TITLE
Notifications keep reappearing every few seconds

### ISSUE THREAD

**Issue by dkter** [vector-im/element-android#1475]
When I enable the "pop on screen" option in the Android notification settings, notifications will pop up and then every five or so seconds pop up again and again until I swipe them away or tap on them. I'm on Android 10 and RiotX version 0.21.0

**Comment by Fackey** [comment]
Yeah, it's very annoying.

**Comment by jpggithub** [comment]
It's very very very annoying and it switch on the display at the same time and contribute to discharge the battery !...
Element 1.0.5 (Fdroid)
Lineageos Android 10 without Gapps (but I had the same bug with Lineageos Android 7 without Gapps)

**Comment by ouchadam** [comment]
I've been unable to reproduce this issue, going to close as this has been open for a while 

There have been many changes to the notification system in recent versions, If you're still seeing the issue in 1.3.7+ please reopen!

**Comment by dkter** [comment]
Yeah I can't reproduce this anymore either.
