### ISSUE TITLE
Font size setting has no effect

### ISSUE THREAD

**Issue by Ai-rin** [vector-im/element-android#1483]
Font size is always default, no matter what I set in the preferences.
RiotX 0.22.0-dev [205344630] (G-b2860)

Device: Redmi Note 4, MIUI 11.0.2 (Android 7.0)

**Comment by maralorn** [comment]
I have the same issue on Android 7.1.1.

Can anyone claim that font size setting is working for them? That would be good to know.

**Comment by rkfg** [comment]
Works as intended on Android 10, Moto G7 Power

**Comment by taxus-d** [comment]
The same issue on Redmi 4X, MIUI 11.0.2,  Android 7.1.2. RiotX version 0.22.0 [40022000] (F-8c981257).
Switching the font size from the largest possible to the smallest possible does not affect most of the interface.
Some labels do change, though:
<img height="200" src="https://user-images.githubusercontent.com/6074302/86170903-5b5bd200-bb0b-11ea-8983-c58b96527fee.jpg" alt="huge font: nickname and edit label are affected"/>&nbsp;<img height="200" src="https://user-images.githubusercontent.com/6074302/86170904-5c8cff00-bb0b-11ea-9ef2-444c75501c41.jpg" alt="tiny font: nickname and edit label are affected"/>

**Comment by samueljohnson** [comment]
Looks like only some of the devices are affected. The issue exists on Lenovo A6020 (Android 5.1.1) but not on LG V30 (Android 9).

Are there any fixes or workarounds for this?

**Comment by taxus-d** [comment]
The bug remains with Element 1.0.0 [40100002] (G-9b49e6a8) (on Redmi 4X, MIUI 11.0.2, Android 7.1.2)
However, all labels are now of the same size regardless of the switch in the settings.
From my experience, this bug is related not with the device model or its vendor-specific OS, but with the underlying Android version. For example it affects Highscreen phone with Android 6, but on Huawei tablet with Android 9 everything works as intended. Unfortunately, I can't upgrade the firmware right now on any of these devices to  be sure.

**Comment by Ai-rin** [comment]
As far as I remember, this setting worked for me at the beginning, then it started to forget the font size on next run, and now it does absolutely nothing.

**Comment by sindastra** [comment]
I can change the font size without issues on Element 1.0.0 [40100000] (F-fca669ff) from F-Droid on my Android 10 tablet (Samsung Galaxy Tab S5e).

**Comment by sindastra** [comment]
@Ai-rin After reading your comment I completely closed the app and opened it again and it did remember my font-size setting without issues. 🤔

###### See previous comment for version and device info.

**Comment by maralorn** [comment]
From the coments here I assume it likely that this issue only affects older android versions.
I am very sorry to ask for support for outdated software. I am really mad at Sony for not providing updates for a perfectly good and moderately old phone.

**Comment by Ai-rin** [comment]
@maralorn Probably, but this doesn't explain the fact that font setting worked previously on the same phone.
