### ISSUE TITLE
Taking photos: Image seems to get uploaded and then downloaded

### ISSUE THREAD

**Issue by fbruetting** [vector-im/element-android#1488]
v0.21

After I have taken and successfully uploaded a photo, RiotX first shows an empty placeholder for about 30…60 seconds, and then finally shows the image. So it seems to me, that not the local photo gets used, but instead a new copy gets downloaded right after the upload. That’s bad for people with limited data (especially as the image compression is currently broken).

**Comment by bmarty** [comment]
This is not true anymore, we have improved this part. See https://github.com/vector-im/element-android/blob/develop/matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/content/UploadContentWorker.kt#L206
