### ISSUE TITLE
Inconsistent read indicator position

### ISSUE THREAD

**Issue by ColonisationCaptain** [vector-im/element-android#1493]
For both text messages and media, the read indicator is displayed towards the bottom of the message in RiotX, but towards the top of the message in Riot Web or Desktop. This behaviour can be quite confusing when switching between clients. Below are examples.

**Image (RiotX)**
![1](https://user-images.githubusercontent.com/52425971/84883862-faeb8000-b088-11ea-90d4-05622671d78e.jpg)
**Image (Riot Desktop)**
![2](https://user-images.githubusercontent.com/52425971/84883906-0c348c80-b089-11ea-900d-1be57e0c5bcd.png)
**Long text message (RiotX)**
![3](https://user-images.githubusercontent.com/52425971/84883916-0dfe5000-b089-11ea-83e8-bbd37108dd68.jpg)
**Lond text message (Riot Desktop)**
![4](https://user-images.githubusercontent.com/52425971/84883924-1060aa00-b089-11ea-8e7d-fb2cb2206905.png)

**Comment by kojid0** [comment]
Personally, I prefer riotx approach. So maybe an issue to post/move to riot-desktop?

**Comment by ColonisationCaptain** [comment]
This issue has been fixed. Element now shows read indicators at the bottom of long messages on both platforms.
