### ISSUE TITLE
Cant remove messages

### ISSUE THREAD

**Issue by Wandelstock** [vector-im/element-android#1499]
I cant remove my own messages in a room when i have a  default userlevel. In a room where i have a higher userlevel i can remove messages. 

This is a bug introduced by the latest RiotX
![Screenshot_20200618-104210](https://user-images.githubusercontent.com/58773587/85007932-8255f380-b15c-11ea-850d-77dc48f3818b.png)
![Screenshot_20200618-104307](https://user-images.githubusercontent.com/58773587/85007937-83872080-b15c-11ea-8894-bcf579e685f4.png)

**Comment by bmarty** [comment]
Yes, bug confirmed, probably introduced by the power level recent implementation. @ganfra could you have a look please?

**Comment by Wandelstock** [comment]
Works now.

**Comment by bmarty** [comment]
Yes, it has been fixed by 94b5e4e2f8cbec280d39673d8b408b07fdec5226
(See #1543)
