### ISSUE TITLE
Read receipt time not respecting locale

### ISSUE THREAD

**Issue by mahdi1234** [vector-im/element-android#1517]
with 0.22 having system set to 24 hours display clicking on read receipt shows time in am/pm format.

![roitx_read_time](https://user-images.githubusercontent.com/1097047/85224982-7157ed00-b3bd-11ea-9546-737a19c8125f.png)

**Comment by bmarty** [comment]
@ganfra you wanted to work on this subject, right?

**Comment by ganfra** [comment]
Fixed by https://github.com/vector-im/element-android/pull/2040
