### ISSUE TITLE
Set presence to unavailable when app is not in foreground

### ISSUE THREAD

**Issue by lieuwex** [vector-im/element-android#1521]
Please close this if I'm mistaken, but it seems to me like RiotX does not set the user presence.

For example, if the app is in the background matrix returns me as "online" and not as "unavailable".

I get marked as such when I shut down my phone (but have Riot web open).

IIRC Riot Android seems to do this, but I'm not sure.

**Comment by bmarty** [comment]
Presence is disabled on matrix.org. Is your homeserver matrix.org?

**Comment by lieuwex** [comment]
No I'm running my own homeserver, presence is enabled.

**Comment by bmarty** [comment]
Ok, thanks, this will have to be done correctly when #70 will be implemented.

**Comment by bmarty** [comment]
Fixed by #2256
