### ISSUE TITLE
Stop the user-hostile verification nags

### ISSUE THREAD

**Issue by resynth1943** [vector-im/element-android#1548]
When I'm using RiotX, most of the time I'm having to click away that obnoxious green banner about verification. I get security but when I'm busy and know I'm the owner of the session, this is going a bit far.

I would appreciate it if you could make the verification nag less obnoxious, and so it doesn't cover the top partition of the screen.

Many thanks,
Synth

**Comment by kittykat** [comment]
Duplicate of #6460

Thank you for filing this issue. I'm going to close this one in favour of the newer issue about the banner.

**Comment by kittykat** [comment]
Duplicate of #4318
