### ISSUE TITLE
Room alias missing features

### ISSUE THREAD

**Issue by bmarty** [vector-im/element-android#1579]
#1464 starts the work on Room settings. What is missing:

- removing alias
- listing aliases
- give user a chance to set canonical alias from the list

Also we may improve the room settings view state: add a data class to hold current room state, and update it when the state is changed.
Also setting the room history visibility (without saving) and reverting the change let the save button active (when we revert the change

**Comment by deepakzero** [comment]
@bmarty  @onurays how to add voice message feature for my andriod chat app .pls help sie
