### ISSUE TITLE
My message is below unread messages line

### ISSUE THREAD

**Issue by 532910** [vector-im/element-android#1594]
![image](https://user-images.githubusercontent.com/14617699/86294267-e072e400-bbfc-11ea-87c5-94ca0b9057f2.png)

0.91.2-dev

**Comment by DoM1niC** [comment]
Yep I have the same Error

**Comment by bmarty** [comment]
It's by design. The "Unread messages" line stays displayed during the time you keep the room visible.

**Comment by 532910** [comment]
Aah, clear, nice design! (:
