### ISSUE TITLE
Bluetooth headset MUST be released on hangup

### ISSUE THREAD

**Issue by 532910** [vector-im/element-android#1595]
https://github.com/vector-im/riot-android/issues/2139

Riot doesn't release bluetooth headset after call end. So when call ends I hear a noise in headset and need to release it manually by pressing answer/hangup button on the headset.

**Comment by 532910** [comment]
It doesn't happen every time. Sometimes it releases, sometimes doesn't.

**Comment by 532910** [comment]
I believe this is a critical issue and it should take `riotx-go-live`.
If you unable to release headset manually (in car for example, that doesn't have answer button) media output will be stolen untill you'll close riot. In fact it's unobvious, and I was getting several negative feedbacks about this.

**Comment by 532910** [comment]
This drains low capacity headset battery extremely fast.

**Comment by 532910** [comment]
@bmarty, @BillCarsonFr

Benoit, Valere

This is not a feature, this is a bug.

**Comment by 532910** [comment]
I still insist that this a serious bug, that exhausts headset battery.

**Comment by kittykat** [comment]
@532910 can you reproduce this issue with v1.3.6? We can't reproduce it on 1.3.8 (coming out next week)

**Comment by 532910** [comment]
I'll take a look at it.

**Comment by jmartinesp** [comment]
We're closing this issue as it didn't have any updates in a very long time. However, if you're still experiencing the issue please feel free to re-open it and add some extra info.
