### ISSUE TITLE
Riot v0.91.3 ,don't open on Moto E5 android, 7.1.1 and others cel, android 7.*

### ISSUE THREAD

**Issue by bmarty** [vector-im/element-android#1618]
Test running the app on Android 7

Ref: https://matrix.to/#/!AZozoWghOYSIAfaZjJ:matrix.org/$RRtfxsps24lzQRbf2Yuyy7_6IMesod8gmcz0mehWuWQ?via=matrix.org&via=privacytools.io&via=1bit.se

**Comment by bmarty** [comment]
@AnonymousWebHacker how is Element Android on your Android 7 device? We have not heard about any complain about this OS version. Maybe we can close this issue now

**Comment by AnonymousWebHacker** [comment]
> AnonymousWebHacker how is Element Android on your Android 7 device? We have not heard about any complain about this OS version. Maybe we can close this issue now

Sorry for not responding in time, I had not reviewed my notifications.

It has already been solved for 2 versions ago. Thanks for asking

**Comment by bmarty** [comment]
Cool, thanks
