### ISSUE TITLE
ring goes only to bluetooth when it's connected

### ISSUE THREAD

**Issue by 532910** [vector-im/element-android#1645]
The phone should ring regardless of wether a bluetooth device is connected or not.

**Comment by progserega** [comment]
#1598

Today I test again - and I was listen ring sound, but it is play from "phone dinamic" (headset), not from "speaker dinamic". And it is was not strong.
I sink this is occur after connect, call, and disconnect bluetooth headset. May be RiotX do not set sound chanel at start for play ring sound?

**Comment by rajil** [comment]
Can confirm this issue. The only way i could get 'speakphone' to ring instead of 'headset',
- Force stop riot.
- Disable bluetooth
- Start riot
