### ISSUE TITLE
can't send messages to certain encrypted rooms

### ISSUE THREAD

**Issue by non-Jedi** [vector-im/element-android#1652]
When I try to send a message to certain encrypted rooms, the message remains red and when long pressed shows:

![Screenshot_20200708-080415_RiotimX](https://user-images.githubusercontent.com/17915621/86916561-c603a380-c0f1-11ea-9ae6-31bb06120ddf.jpg)

I've found at least one encrypted room where sending works normally.

I will send a rageshake.

**Comment by non-Jedi** [comment]
It appears to be any room with the user`@greg:thebeckmeyers.xyz` is affected.

**Comment by non-Jedi** [comment]
Clearing cache fixed this problem. I'll leave open in case the rage-shake showed anything useful, but feel free to close.

**Comment by danger89** [comment]
Was it also stuck of "sending message" for quite some time? Since that's the issue I'm facing.

**Comment by bmarty** [comment]
Feel free to open it again it it happen again...
