### ISSUE TITLE
Appearance of 'Switch Camera' in video call is random

### ISSUE THREAD

**Issue by rajil** [vector-im/element-android#1671]
The 'switch camera' option sometime does not appear at the far end. For example:
- Call from Riot Android (No switch camera) to Riot Web 
- Call from Riot-web to Riot Android (Switch camera available)

**Comment by croulibri** [comment]
I face the same situation with no switch option also when Element Android call Element Android.
Today I realize I have the option to switch when Element Android call old Riot Android (not updated to Element yet)

**Comment by kittykat** [comment]
I'm going to close this issue as it's been fixed in v1.3.8 (coming out next week) - please comment with @kittykat if you feel that there is a further improvement to be made and I'll re-open the issue
