### ISSUE TITLE
Unreadable text

### ISSUE THREAD

**Issue by Wandelstock** [vector-im/element-android#1684]
Now it works on 5.0.2 the text is in dark and black mode unreadable. 0.91.4

![Screenshot_2020-07-13-18-05-31.jpg](https://user-images.githubusercontent.com/58773587/87329065-b2fc3380-c536-11ea-9cfb-a66e198208c3.jpg)

**Comment by Saadnajmi** [comment]
I have this problem too. Is anyone looking at it?

**Comment by bmarty** [comment]
Yes, this issue is similar to (most recent) #2738, and it's fixed in the next coming release 1.1.7.
Please re-open if it's not fixed for you on 1.1.7 (release is scheduled this week)
