### ISSUE TITLE
remove RiotX from markets

### ISSUE THREAD

**Issue by 532910** [vector-im/element-android#1686]
Should im.vector.im be removed from Google Play? F-Droid?

**Comment by rakshazi** [comment]
And `riotX` and `imX`

I have another question - when new Element for Android will be available on F-Droid? Still using RiotX 0.22 :(

**Comment by novoplan** [comment]
can't find the new element app on playstore. only the old riot.im (May 22) is shown or riotx (June)

**Comment by bmarty** [comment]
Element is still in review by Google.
RiotX will then be removed from the PlayStore in a few weeks

**Comment by rakshazi** [comment]
Regarding my question about F-Droid - Element now available on F-Droid 🎉

**Comment by 532910** [comment]
looks like this should be a part of #1727
