### ISSUE TITLE
Voice & Video device settings

### ISSUE THREAD

**Issue by rajil** [vector-im/element-android#1688]
The voice and video settings should allow defining the default audio device (bluetooth/ear piece/Speaker phone).

![image](https://user-images.githubusercontent.com/379266/87429837-fe2f4880-c601-11ea-848b-16a2fa02e4be.png)

This will help in closing [#1644](https://github.com/vector-im/riotX-android/issues/1644).

**Comment by violoncelloCH** [comment]
Why is this needed? Isn't it better to have a sane default? As:
Audiocall:
- ear piece
- if bluetooth (or any other) headset connected -> headset
- or if manually switched to speakers -> speakers (including bluetooth or external ones)
Video:
Same but just never use the earpiece in this case, so speakers by default, and if connected the external one

I think having a Setting option for this is just unneeded overhead...

**Comment by rajil** [comment]
See the bug report linked above. The Bluetooth headset detection is buggy in the app. Riot thinks there is headset connected when there isn't. 
With configuration options, the user is given the opportunity to sort things out. This is also what riot-web does.

**Comment by violoncelloCH** [comment]
Well no, if this headset detection is buggy (in the alpha state of the implementation), then the fix is rather to solve this problem than to add unnecessary settings... Sorry I don't get the point here why you think a setting would be absolutely needed...

**Comment by rodolpheh** [comment]
Isn't this menu supposed to add TURN server settings and video mirroring like in Element Web/Desktop as well ?

**Comment by meyerrj** [comment]
I've noticed with video calls, it tends to default to the normal phone speakers and not as a speakerphone. This can be a bit annoying once a video chat is initiated as we have to toggle the speaker to hear each other.

**Comment by bmarty** [comment]
We agree with @violoncelloCH : default audio device should depend on the current state of the phone (including proximity sensor), and its accessories (wired headset, Bluetooth devices, etc.).
