### ISSUE TITLE
[Feature] Enrich Home tab

### ISSUE THREAD

**Issue by Jiack214** [vector-im/element-android#171]
I'm in few rooms so I often have zero unread messages. In this way the home tab is often useless because it's often show the "you're all caught up" sceeen.

So, is the home tab going to display something like "breadcrumbs" or something else to easily reach chats with no unread messages?

**Comment by bmarty** [comment]
Hi @Jiack214 ,
Yes, thanks for the suggestion, we will see what we can do to improve UX when catchup is empty.
Benoit

CC @nadonomy

**Comment by frandavid100** [comment]
Maybe a list of favorite DMs and rooms?

**Comment by Jiack214** [comment]
I would like to have something like this: (sorry for the low quality edit)

![riotx_home](https://user-images.githubusercontent.com/23478344/61563673-d0f29d80-aa74-11e9-9324-b663abdcccdf.png)

**Comment by nadonomy** [comment]
At one point we'd discussed having the list just turn into rooms by activity, like your mockup.

I like the idea of the room list just running into the list of rooms by activity, like Whatsapp et al, but need to dig into all of our use cases to see what makes the most sense.

**Comment by bmarty** [comment]
> I would like to have something like this: (sorry for the low quality edit)
> 
> ![riotx_home](https://user-images.githubusercontent.com/23478344/61563673-d0f29d80-aa74-11e9-9324-b663abdcccdf.png)

Yes this is something we want to do with #571

**Comment by akarshanbiswas** [comment]
@bmarty I really want to see favorite rooms and direct messages here in the home tab for quick access. :(

**Comment by progserega** [comment]
> Maybe a list of favorite DMs and rooms?

May be add option "On empty home tab" with variants:
1. Leave empty
1. Show recent DM and rooms
1. Show favorite DM and rooms

**Comment by kittykat** [comment]
This issue can be closed as part of the new app layout as that redesigns this area. If you feel that there are further improvements to be hand after the new app layout is on by default, please open a new issue!
