### ISSUE TITLE
Kill RiotX

### ISSUE THREAD

**Issue by bmarty** [vector-im/element-android#1727]
After the release of Element as an upgrade of Riot-Android, we should properly kiil the beta of RiotX on the PlayStore

## PlayStore

- [x] Update the PlayStore description to clearly tell that this app should not be installed. We keep it on the PlayStore for the latest update with the change below

## RiotX code

On a branch created before the re-branding is merged, and which will be of course never merged, we should:

- [x] Always display the "Welcome to the Beta" popup with new wording: title "The Beta is over", content:

> RiotX will not be updated anymore.
 Please install Element!

Description may also contain advice to properly sign out or to keep the session open to verify the new session with RiotX, but not sure it's very useful/it worth it.

2 buttons:
"Later" -> dismiss the popup
"Get Element" -> Open the PlayStore on the Element page

- [x] Prevent new login with RiotX

- [x] Publish the RiotX app on the beta channel of the PlayStore

## Finally

- [x] Say 1 month after the update: remove RiotX from the PlayStore

**Comment by pschloenzke** [comment]
I just installed the new update via Google Play Store.

-> RiotX crashes on startup

**Comment by bmarty** [comment]
Yes, thanks for reporting. It's very to say that I made a mistake. I quickly publish a v0.24.0 to the PlayStore this afternoon, that fixes the crash.

In the mean time, you should install and use Element now https://play.google.com/store/apps/details?id=im.vector.app

**Comment by bmarty** [comment]
RiotX has been removed from the PlayStore today. RIP!
