### ISSUE TITLE
Sending image failed (I assume) but message cannot be canceled/deleted

### ISSUE THREAD

**Issue by kqr** [vector-im/element-android#1732]
I sent three images to someone else. Only the first was successfully sent. The other two stick around in the bottom of the conversation and if I long press them they are described as "Sending..." However, they've been in this state for hours and I'm starting to suspect they will never be sent.

It's annoying that they're still around at the bottom of the conversation because that means they obscure new messages in that conversation, which end up above the terminally-unsent images.

Unfortunately, there doesn't seem to be an option to cancel sending those images, or deleting the messages!

**Comment by progserega** [comment]
I thin such problem in #1119 and #1706

**Comment by kqr** [comment]
Yes. This does not have the red "!" so I cannot press "send again" -- meaning this is a duplicate of #1119 but not the other one you found.

**Comment by kqr** [comment]
Would a sufficient low-cost workaround be to add the delete option also to unsent messages?

Obviously messages shouldn't get stuck in the unsent state forever, but figuring out all possible causes of that seems like it might take some time, and it would be nice to users to give them a quick manual way out of the problematic state in the meantime.

As it is, RiotX feels like a downgrade from the previous client, given all it's rough edges, so this would be very helpful from a churn point of view, I think.

**Comment by progserega** [comment]
Now workaround is "clear all cache" in settings of Element (in element settings, not in system settings->app->element->storage).

After clear cache - element init new sync data and clear unsended images. 

P.S. It bad bug for everyday use: if network is bad, if I get gsm call (internet is off at this moment) - after that chats is broken (at down of chat show unsended data - images or messages) and user must clear cache of element for return to normal work. :-(

**Comment by BillCarsonFr** [comment]
Fixed by #1889

**Comment by kqr** [comment]
Awesome. Thanks!
