### ISSUE TITLE
Can someone explain "Verify this login"?

### ISSUE THREAD

**Issue by 2011** [vector-im/element-android#1734]
Just installed (first time) from F-Droid (4010000). Under "Settings / Security & Privacy", "Active Sessions" shows "1 active session". When I select that, I see "Element Android" with an identifier beneath it. To the right sits a red badge with an exclamation mark in the center. When I select that, I see a green "Verify this login" at the bottom of the screen. When I select that, I see "Use an existing session to verify this one, granting it access to encrypted messages. Use the latest element on your other devices:" I have no other sessions, so at this point, I only have one option, "Skip", which brings up "If you cancel, you won't be able to read encrypted messages on this device, and other users won't trust it". Can someone explain what the warnings mean, if they have any importance, and how I make them go away? Thank you in advance.

**Comment by TheTimeWalker** [comment]
This is not a support forum. You should ask in the appropriate Matrix room for support.

**Comment by 2011** [comment]
Well, when I get asked in the app to verify something that I can not possibly verify (no other sessions), and I can't get rid of (meaning I see them every time I start the program) popups telling me that I can't read encrypted messages and that other users won't trust my messages, that seems like a bug to me (something specific to the implementation instead of the framework itself). Maybe someone could explain why the applicatation behaves that way.

**Comment by nakal** [comment]
I don't get this verification, either. It's a usability bug. How do I cross-verify a session, when there is only 1 session active?

**Comment by kekukui** [comment]
> **This is not a support forum.**

And this is not a support request:  I am reporting a _**user interface design flaw**_.

1.  Installed Element Android app
2.  Registered a new user account on my office private Matrix server ; works okay but found the Element app a little too resource heavy for my old phone (other clients are 1/3 the size)
3.  Installed all the alternative Matrix clients from F-droid for evaluation purposes 
(Ditto, Pattle, SchildiChat, Syphon, Fluffy) then uninstalled Element app
4.  Was disappointed with the alternative clients, Reinstalled Element app
5.  Now Element app says **"verify this login"** at launch
_"Use an existing session to verify this one, granting it access to encrypted messages.  Use the latest element on your other devices: Element Web, Element Android"_
6.  Installed desktop client, it shows the same error with a somewhat different description:
_"Confirm your identity by verifying this login from one of your other sessions, granting it access to encrypted messages."_
7.  Restart Android client, now the warning is gone - but it still appears in desktop client.

If I press "skip" , does it mean I wont be able to use encryption?  --This needs to be fixed or explained better within the app.  **TERRIBLE ONBOARDING EXPERIENCE guaranteed to cause problems for millions of users.**

**Comment by daniellekirkwood** [comment]
Have triaged and tagged, removing my assignment.

**Comment by janschejbal** [comment]
The issue being raised here is **"Non-actionable, non-dismissable verification dialog covering UI elements"**

This started popping up for me recently (I think at most a few weeks ago), likely after an automatic update or some other event not explicitly triggered by me (if this depends on contacts, it's possible that my only active contact did change something).

Current version is `1.4.20 [40104202] (G-b8965)`. My Security & Privacy menu shows "Cross-Siging is enabled. Keys are not trusted.", my "Manage Sessions" screen shows a red shield with an exclamation mark. I had one other session from a web client web  (for which I no longer have the cookie) showing with a black shield which I now terminated.

Before I terminated the session, clicking on the popup generated a "verify this login" card on the bottom of the screen telling me to verify with some other session (which I didn't have access to anymore). After I terminated the session, the only option in that menu is "skip". Pressing "skip" tells me how horrible skipping is and offers me a "continue" button leading back to the useless card. "Skip" means the popups go away until I reopen the app, then start annoying me again.

I don't know the previous verification state. I believe that in the past, web based sessions prompted me to verify with my phone, now they prompt for a reset, so it is possible that my phone session (which is the only one I had) lost verification status (or never had it but previous versions didn't care).

I now constantly get a "verify this login" pop-up on Android, covering part of the screen including the menu button. Chatting (including encrypted messages) with the one other person I know that uses Matrix works and I can see my old messages.

I have switched on cross-signing and/or key backup ("Key backup has been correctly set up for this session") relatively late.

**Comment by kittykat** [comment]
Duplicate of #3999

I'm going to close this issue as a duplicate of #3999 as the description is about having only one session and the user experience around verification not making sense with only one session.

For all other issues, please file a new issue following our current templates. I would also like to call out that we are now using [discussions in Element Meta for cross-platform improvement suggestions and feature requests](https://github.com/vector-im/element-meta/discussions) :+1:
