### ISSUE TITLE
User profile not show online status

### ISSUE THREAD

**Issue by progserega** [vector-im/element-android#1739]
Old Riot Android show user oline status like: "online", "offline", "was X minute", "was X hours". In new Element this status not show for users - not in room users list, not in user profile.

P.S.: I am use self hosted synapse server with enabled "online status" for users.

Element 1.0.0 for Android.

**Comment by progserega** [comment]
![Screenshot_20200719-155049 png](https://user-images.githubusercontent.com/1297163/87868443-e4fb1300-c9d8-11ea-8105-223f28b0450d.jpeg) ![Screenshot_20200719-155100 png](https://user-images.githubusercontent.com/1297163/87868445-e62c4000-c9d8-11ea-9cf2-bee04fa0c5c3.jpeg)

**Comment by progserega** [comment]
Most users wont this feature.

**Comment by bmarty** [comment]
Are you talking about presence management? If yes, this is a duplicate of#70.

**Comment by progserega** [comment]
> Are you talking about presence management? If yes, this is a duplicate of#70.

Yes

**Comment by ShadowJonathan** [comment]
Duplicate of #70, @BillCarsonFr
