### ISSUE TITLE
Element-android not stop ringing at incoming voip after I get call in element-desktop

### ISSUE THREAD

**Issue by progserega** [vector-im/element-android#1740]
Element android must stop play ringing and hide "incoming call" splash at full screen after user answer to call in this account in elemet-desktop.

Steps to reproduce:
1. 2 accounts: alisa and bob.
1. Bob have two device in one account: element-android and element-desktop
1. Alisa start voip-call to bob
1. Element-desktop of Bob begin play ring-sound and show splash "accept and decline incoming call"
1. Element-android of Bob begin play ring-sound and show full-screen splash "accept and decline incoming call"
1. Bob press "accept call" in element-desktop
1. Element-android of Bob still play ring-sound and still show full-screen splash "accept and decline incoming call"
1. Bob speak with Alisa some time (3-5 minutes)
1. Element-android of Bob still play ring-sound and still show full-screen splash "accept and decline incoming call (green and red buttons)"
1. Bob for test try end voip-call by press "red button" on Element-android full-screen splash - call ended on Elements-desktop, but full-screen splash of incoming voip on element-android not close. This is splash is still in full screen mode, but buttons "accepts and decline (green and red phone)" - is hided.
1. Bob press "return" on element-android and splash is hide.

I think incoming-voip-call splash must be stop showing and ring-sound must be stop playing on element-android adter user get answer for call on element-desktop.

**Comment by progserega** [comment]
stil in 1.0.6, but if I get call on desktop - pressing "hang up" on phone not end call on desktop.

**Comment by progserega** [comment]
At accept voip call on element-desktop in 1.0.7 - element-android is stop ringing, but splash incoming call still show, when I accept voip call on element-desktop.

**Comment by dbkr** [comment]
The VoIP v1 spec should help make this behaviour a bit clearer. To summarise, when a client is ringing with an incoming call:
 * If it sees an answer to the same call ID and hasn't sent an answer itself, stop ringing
 * If it sees a hangup or reject for the call ID and hasn't sent an answer, stop ringing
 * If it has sent an answer but sees a select_answer from the caller selecting a party ID other than its own, end call & notify user that the call was answered elsewhere

**Comment by progserega** [comment]
fixed
