### ISSUE TITLE
Crashing as soon as I try to open a DM/group

### ISSUE THREAD

**Issue by Torxed** [vector-im/element-android#1745]
No idea how to debug this. It's a hard crash.. sent crash debug via Goolge App Store.
I simply can't open any rooms/conversations. some times I can but when I send a message it crashes.

Self hosted matrix server, auto-updated app.

 * matrix-synapse 1.13.0-1
 * v1.0.0 [40100002] of riotX android
 * Matrix SDK Version 0.0.1  *(that seams odd)*
 
Might be related to me being in ~100+ rooms/DM's.

**Comment by Torxed** [comment]
After many hours of syncing, it seams like the crash has disappeared. Now I simply don't get mentions/notifications anymore.

**Comment by MadLittleMods** [comment]
Closing as I assume you're getting notifications again 2 years later and should be filed as a new separate issue in any case.
