### ISSUE TITLE
Rename riotX-android repository

### ISSUE THREAD

**Issue by TR-SLimey** [vector-im/element-android#1752]
GitHub has a neat feature where past names of renamed repositories redirect to their current name if the name was changed and (I assume) no new repo is created with the same name. Therefore, this repo (and all the other Riot repos) can be renamed to match the rebranding, without the need to change every single link out there.

**Comment by ZerataX** [comment]
yeah this is currently really confusing where neither the organisation name nor the repository name is correct

**Comment by TR-SLimey** [comment]
I noticed this was done now (woo-hoo!) so will close this issue @bmarty :]

**Comment by ZerataX** [comment]
still kinda sad that organisation name (and description for that matter) is wrong, but I assume that's due to github redirects
