### ISSUE TITLE
sign in with matrix id fails on chat.weho.st homeserver

### ISSUE THREAD

**Issue by Soundtoxin** [vector-im/element-android#1754]
I suspect it doesn't like the look of the url, as `@user:chat.weho.st` looks quite a bit different from the example of `@user:domain.com`. I don't know if it's choking on the subdomain or the uncommon TLD, but this works fine on most clients. In fact, it worked fine on RiotX pre-Element re-brand. I just grabbed Element off F-Droid and was unable to sign in.
The error is "Unable to find a valid homeserver. Please check your identifier". I tried removing the @ in my ID and then it just says my ID is invalid, so that wasn't the problem.
Sidenote: this homeserver has been laggy off and on lately, so there's a non-zero chance it's timing out, though it seems to reject it on the name and it happens pretty much instantly.

**Comment by mytbk** [comment]
I also have this problem for my matrixim.cc homeserver.

**Comment by bmarty** [comment]
Element Android correctly try to fetch`https://chat.weho.st/.well-known/matrix/client`, but this URL returns a 404, and should not, to be able to log in using matrix Id.

Element-Web returns the same error FWIW.

**Comment by bmarty** [comment]
Sot o conclude, please ensure that your homeserver has correctly set up the Well-known configuration
