### ISSUE TITLE
add button for direct chat to user profile

### ISSUE THREAD

**Issue by lub** [vector-im/element-android#1775]
It would be great if you could start a new or open an existing direct chat with a user when you look at its profile (where the avatar/ignore button/mention button/jump to read receipt/.. is).

Currently you have to tap on that new chat icon in the bottom right corner of the main screen and (partly because of #1774) manually enter the mxid to start a new chat or try to find it with the search.

element-web calls this button 'Direct message'

**Comment by jojoob** [comment]
It looks like it has been implemented since then.
