### ISSUE TITLE
Back camera preview is mirrored

### ISSUE THREAD

**Issue by 532910** [vector-im/element-android#1776]
Only the front camera needs to be mirrored

**Comment by 532910** [comment]
> We are now working to improve user experience with 1-1 calls.

@bmarty, is not this about ux 1:1 calls? (:

**Comment by 532910** [comment]
moreover I believe the fix is trivial

**Comment by witchent** [comment]
Then implement it yourself and do a pull request. 
They obviously looked at your issues (they gave most of them labels) so there's no reason to already push them (Especially if they're only one month old).

If you don't have time to implement it, please consider that the developers are busy as well. If you don't have the knowledge to do it then please consider that maybe things which seem trivial still take some time to figure out and fix.

**Comment by 532910** [comment]
I confirm it's fixed. Thank you.
