### ISSUE TITLE
Words containing my name should not trigger notifications

### ISSUE THREAD

**Issue by rda0** [vector-im/element-android#1781]
I receive push notifications for messages with words that are containing my user-/displayname. Opening the app does not show any highlights though.

I noticed this in multiple public rooms with notification level "mentions only".

### Expected

Only send notifications for words matching my username.

### Example

When both account username and displayname is set to `rda`, I receive notifications if a message contains the word "yesterday".

### Version

Version: Element Android 1.0.0
Android Version: 10

**Comment by bmarty** [comment]
Ok, I can reproduce the issue
