### ISSUE TITLE
Session id and session key not viewable

### ISSUE THREAD

**Issue by dominikwerder** [vector-im/element-android#1784]
The Element Android client has no possibility to show the session id and the session key.

In contrast, the https://app.element.io web client shows these under "Settings" -> "Security & Privacy".

**Comment by Fidgetcetera** [comment]
Can confirm this. There's also no way to verify by text at all. I try to keep all my Matrix client e2ee keys updated on my website for others to verify when cross signed/realtime verification isn't available, but I can't actually put up my phone's key at all (because Element desktop/web also doesn't let you view ALL your keys, only the one of the current session).

**Comment by BillCarsonFr** [comment]
You can go to Settings > Security & Privacy > Show All Sessions , you will then be able to select a session to have more information

<img width="374" alt="image" src="https://user-images.githubusercontent.com/9841565/89661465-06159c00-d8d3-11ea-8f8d-81c66cd8da2a.png">

<img width="456" alt="image" src="https://user-images.githubusercontent.com/9841565/89661828-77554f00-d8d3-11ea-8d91-b2ec994ef5b7.png">

But yes if you start from web, you can't get your current device key from element android.

-> We should add an advanced session in Security & Privacy to see your current device key

**Comment by Fidgetcetera** [comment]
> You can go to Settings > Security & Privacy > Show All Sessions , you will then be able to select a session to have more information

Only if you haven't yet verified the device. You can't un-verify a cross-signed device, either.

**Comment by BillCarsonFr** [comment]
> > You can go to Settings > Security & Privacy > Show All Sessions , you will then be able to select a session to have more information
> 
> Only if you haven't yet verified the device/session. You can't un-verify a cross-signed device, either.

Regarding un-verify, it's a known limitation tracked in web ->https://github.com/vector-im/element-web/issues/13505
Just created same issue on mobile #1904
