### ISSUE TITLE
Dark Theme has some icons with incorrect color (on stable Element Android)

### ISSUE THREAD

**Issue by unclechu** [vector-im/element-android#1786]
![Screenshot_2020-07-22-20-41-56](https://user-images.githubusercontent.com/799353/88210472-efc5da00-cc5c-11ea-92c2-6fd1a013f0bc.png)

**Comment by unclechu** [comment]
Updated to latest 1.0.1 from F-Droid, still have the same view.
![Screenshot_2020-08-02-14-48-49](https://user-images.githubusercontent.com/799353/89122720-5c00d300-d4d2-11ea-870e-1e50c79325fb.png)
![Screenshot_2020-08-02-14-48-53](https://user-images.githubusercontent.com/799353/89122734-6f13a300-d4d2-11ea-8250-3ccdf13c7426.png)

**Comment by bmarty** [comment]
It's working on our side. What is your device / OS version?

**Comment by unclechu** [comment]
@bmarty 
OS: Android 5.1.1

Kernel version:
```
3.10.65-9236909
dpi@SWDG9817 #2 
Thu Nov 9 21:04:46 KST 2017
```

Model: Samsung Galaxy J3 (2016)

**Comment by unclechu** [comment]
@bmarty I sent a rage-shake report with the issue number in the report description in case it would help.

**Comment by bmarty** [comment]
Ok, it's due to a limitation in vector drawable under API 24
