### ISSUE TITLE
Room links do not open in the app.

### ISSUE THREAD

**Issue by olymk2** [vector-im/element-android#1795]
Clicking this link on andriod results in the phone requesting if you would like to open in firefox or chrome, but not element https://app.element.io/#/room/#mhackspace-test:matrix.org

this format also fails #mhackspace-test:matrix.org  feel free to use that room to test, ie past the link in a room in element android and tap it.

**Comment by bmarty** [comment]
Shouldn't matrix.to link be used instead?

**Comment by bmarty** [comment]
Oh I see. Actually the feature is not yet implemented: See #1068
