### ISSUE TITLE
In Markdown mode, plain text mentions include URLs

### ISSUE THREAD

**Issue by heftig** [vector-im/element-android#1807]
When markdown formatting is disabled, mentions look like this in the plain text body:
```
heftig: foo
```

But when markdown formatting is enabled, mentions look like this in the plain text body:
```
"heftig" (https://matrix.to/#/@heftig:archlinux.org): foo
```

This is very verbose and distracts from the content of the message. It also unnecessarily triggers IRC bots doing URL previews.

**Comment by emorrp1** [comment]
This is https://github.com/vector-im/element-android/issues/1506

**Comment by bmarty** [comment]
It is not the case anymore in Element 1.0.6
