### ISSUE TITLE
Doubled emojis in room titles

### ISSUE THREAD

**Issue by fbruetting** [vector-im/element-android#1808]
The room icon getting to be the emoji of the title, renders the emoji itself in the title text superfluous.

### Room overview

![IMG_20200725_144854](https://user-images.githubusercontent.com/10520767/88457424-7dd0d900-ce86-11ea-9b09-f225474b014a.jpg)

### Room title bar

![IMG_20200725_144913](https://user-images.githubusercontent.com/10520767/88457426-81646000-ce86-11ea-9d90-c34da002fe12.jpg)

**Comment by TR-SLimey** [comment]
Why not just get an image of that emoji and not put it in the name?

Are you suggesting that the icon generator skip any emojis?

**Comment by fbruetting** [comment]
Picking the emoji as the room icon is a very nice feature of Element, because it makes groups vastly more distinguishable. But Element as the exact same emoji then gets placed two times next to each other, it makes the text-inline emoji superfluous.

Having to make a screenshot, cutting it and making that the group icon destroys the whole emoji-picker-like feature.

**Comment by bmarty** [comment]
We will not fix that

**Comment by fbruetting** [comment]
Are  there plans for an emoji selector for the room avatar? That would also solve the doubled-emoji issue.

**Comment by TR-SLimey** [comment]
@fbruetting I think that's just too specific of a use-case
