### ISSUE TITLE
missed call notification is awfull

### ISSUE THREAD

**Issue by 532910** [vector-im/element-android#1813]
```
X placed a voice call.
X send data to setup the call.
X send data to setup the call.
X send data to setup the call.
X send data to setup the call.
X ended the call.
```

![image](https://user-images.githubusercontent.com/14617699/88481812-46d1f480-cf66-11ea-8838-f75df9f5e814.png)

Moreover, why he placed `a call`, while send data and ended `the call`?

**Comment by BillCarsonFr** [comment]
Yes, it's a known limitation for now, it has been descoped from first release
https://www.figma.com/file/h6XHDrTXXTBHgdFl15f5pD/%5B%2378%5D-Timeline?node-id=2%3A56
Will come soon

**Comment by BillCarsonFr** [comment]
Also looks like a bug in NotificationDrawer that does not filter out some events

**Comment by kittykat** [comment]
I'm going to close this issue as the notifications are much better now. Please comment with @kittykat if you feel that it can be improved further in v1.3.8 (coming out next week) or newer
