### ISSUE TITLE
Removed function: ability to set custom sync/check frequency

### ISSUE THREAD

**Issue by AUSITStuff** [vector-im/element-android#1815]
It appears that the ability to set custom sync/refresh frequency was removed in the move from latest RiotX to Element 1.0
We operate on an offline network without access to GCM/Apple Push and as such this meant the app was always up to date. Yes it came at the expense of battery but that's a trade off it was worth being in control of.
Is this functionality likely to be restored?

**Comment by ralaud** [comment]
I was searching this feature too. Live notifications are nice especially important for voice/video calls, but to slow down battery drain on devices without FCM this feature was very useful.

**Comment by thomas31415** [comment]
For privacy reasons, no Google services are installed on my device, so I also would be very happy if this feature could be used again. 

PS: Due to heavy battery drain I had to deactivate Element and told my friends to send me an XMPP message in urgent cases...

**Comment by dkm** [comment]
That's indeed a real problem (no gapps here). I have to «force close» the app after each check. It would be nice to have at least a way to make it «offline».

**Comment by vibrys** [comment]
updated from riotx to element and stumbled upon battery drain problem. more: I have notifications off for the account and I have impression that battery gets drained - riotx didn't drain then.

**Comment by dkm** [comment]
Not sure why you closed it? Is it fixed somehow or has it been considered as wontfix ? Could not find any reference elsewhere.

**Comment by mcg-matrix** [comment]
Looks like this was resolved in version 1.0.7 which brought along #2080 for #2055. It seems to work well on my devices with all parameter value combinations I've tested – just don't set "Sync request timeout" to anything larger than 59 (see #2169).
