### ISSUE TITLE
<del> doesn't work in sent messages

### ISSUE THREAD

**Issue by Sobsz** [vector-im/element-android#1817]
In Element Android 1.0.0, sending a message such as `<del>test</del>` (which is the only way to send strike-through text as far as I'm aware) causes the HTML markup to be shown in plain text instead of striking through the message ~~like this~~. Other clients can send such messages and they'll show up in Element as crossed-out just fine, they just can't be sent from this app.

**Comment by akoyaxd** [comment]
Is this a bug or a missing feature?

I would really wish, this would get more attention. Not only does this unnecessarily decrease the feature parity between the different apps, imho strikethrough is the most powerful rethoric medium after emojis. (Tough, I do probably not represent the majority of users).

**Comment by barudaret** [comment]
Doesn't `~~tilde~~` also work for strikethrough in element-web?  That's like basic markdown syntax isn't it?  That'd be the best way for the app too.

**Comment by benparsons** [comment]
Doesn't seem to work for recieved messages either. `<del>some text</del>` just renders "some text".

**Comment by HarHarLinks** [comment]
since this is somewhat advertised as feature and really easy to send from element-web (highlight some text and click the strike through button), android **really** shouldn't leave out both the decoration _and_ the tags since that's just looking to create confusion

**Comment by bmarty** [comment]
After investigating, this is due to a bug on the Android platform, which affect devices running API 28+. I've reported it to Google, lets hope it will not be closed as for the previous bug report on the same issue...

We cannot remove the usage of _PrecomputedTextCompat_, since it will reduce the performance on the timeline.

In the mean time, feel free to star the issue: https://issuetracker.google.com/issues/188454876

**Comment by bmarty** [comment]
I implemented a workaround in Element 1.1.8 waiting for a proper fix from Google.

**Comment by vaguerant** [comment]
@bmarty I think there might be a bit of a disconnect between this issue and the one you worked around. Your fix corrects the rendering of strikethrough text, but the issue as initially filed concerns the fact that there's no way for Element Android users to *send* strikethrough text. As of v1.1.8, I can see strikethrough text just fine, but I still can't send it myself with the standard markdown \~\~strikethrough\~\~ or the HTML \<del>strikethrough\</del>. In both cases, the marked up text comes through, i.e. everybody (locally and remotely) just sees the tildes and/or HTML tags.

**Comment by HarHarLinks** [comment]
@bmarty now that 1.1.~~8~~9 has landed on F-Droid, I can report that
- [X] `<del>` are now rendered in the timeline
- [ ] `<del>` is not rendered as text decoration in the message preview, but as raw code
- [ ] you still can't send `<del>` or similar from android to generate the markdown
- [ ] nor can you send using `/html` as you can on desktop

**Comment by bmarty** [comment]
Agree, I created a new issue to track what is missing
