### ISSUE TITLE
guests have no access

### ISSUE THREAD

**Issue by sl5net** [vector-im/element-android#1848]
If I create a room with access rights for guests and visit this room via the URL offered by matrix, I get the message that guests have no access.

![7 neuer versuch - Screenshot_2020-07-30_17-04-49](https://user-images.githubusercontent.com/5634759/88944282-d3ddbc00-d28c-11ea-9730-00cc05dbcd68.png)
![8 Screenshot_2020-07-30_17-06-43](https://user-images.githubusercontent.com/5634759/88944284-d4765280-d28c-11ea-8f04-dbf450b86e4f.png)
![9 Screenshot_2020-07-30_17-08-10](https://user-images.githubusercontent.com/5634759/88944287-d50ee900-d28c-11ea-8829-7a589293d617.png)

![image](https://user-images.githubusercontent.com/5634759/88944758-6aaa7880-d28d-11ea-8460-11f29bfdf177.png)

Only offered possibilities:
https://app.element.io/#/register
https://app.element.io/#/login

**Comment by BillCarsonFr** [comment]
Is this a riot-web issue? https://github.com/vector-im/riot-web/

**Comment by sl5net** [comment]
@BillCarsonFr  Maybe. Its this room and this url: https://app.element.io/#/room/#guests2seeh:tchncs.de

**Comment by bmarty** [comment]
Please open issue about Element-Web in this repository: https://github.com/vector-im/element-web/

Element-Android does not support guest access for the moment
