### ISSUE TITLE
This translation is currently locked for updates. 

### ISSUE THREAD

**Issue by linsui** [vector-im/element-android#1850]
All components under Riot Android are locked.

**Comment by aevw** [comment]
There's only android's Riot & RiotX available for translation but it merged into Element. The only translation for Element  available is Web. Right now I'm using Element android app and it's half translated. Could be a good idea to make it available for translation.



![element1](https://user-images.githubusercontent.com/69059460/89134331-b3b33480-d4fa-11ea-9aba-326b762f4a11.jpg)


![element2](https://user-images.githubusercontent.com/69059460/89134334-bada4280-d4fa-11ea-82b4-4e99e8bcaec5.jpg)


![element3](https://user-images.githubusercontent.com/69059460/89134336-c299e700-d4fa-11ea-819f-c2ea058f7068.jpg)

**Comment by bmarty** [comment]
Yes, I'm aware of that, Weblate is broken. I will create a new project.

**Comment by aevw** [comment]
great, in no time there will be translation for that

**Comment by bmarty** [comment]
The new project is ready on Weblate: https://translate.riot.im/projects/element-android/

**Comment by 532910** [comment]
What stops it to be https://translate.element.im?

**Comment by bmarty** [comment]
Time :). It will be moved in a second time
