### ISSUE TITLE
Text disappear from input

### ISSUE THREAD

**Issue by erdnaxeli** [vector-im/element-android#1853]
Hi,

I noticed that sometimes will typing, the text still in the input suddenly disappear.

Here is a screencast where I reproduced it : <https://morignot.iiens.net/vrac/riotx.mp4>.

It seems it is related to answering a message. This is really annoying :p

**Comment by erdnaxeli** [comment]
Related to #952

**Comment by ouchadam** [comment]
I've been unable to reproduce and haven't seen any recent reports, looks like this was fixed by https://github.com/vector-im/element-android/pull/2158 

please reopen if you're still experiencing this issue on newer version of Element Android
