### ISSUE TITLE
Google Play age limit rating

### ISSUE THREAD

**Issue by daniel-lerch** [vector-im/element-android#1858]
The Element app on Google Play is rated as USK18. That means users from Germany have to be at least 18 years old in order to be able to download it.

I don't understand where this rating comes from. Other end-to-end encrypted messaging applications like WhatsApp, Wire, Signal and Threema are all rated as USK0 which means no age limit although they just have user interaction like Element.

**Comment by bmarty** [comment]
Anyone can write to public rooms (which are discoverable and can be join by anyone), and send inappropriate content/image/etc. This is why the PlayStore rates this app like that. This is not the same rating for every country though, it depends on country specific law.

**Comment by joepie91** [comment]
Isn't the same true for the other mentioned messaging apps? At least WhatsApp has groups functionality, AFAIK.

**Comment by daniel-lerch** [comment]
@bmarty is right. There is a distinction between peer to peer communication and social networks that aim to provide communication within large groups. The following screenshot is the first step for an IARC rating on Google Play:

![IARC overview](https://user-images.githubusercontent.com/36048059/89287514-6945cb00-d654-11ea-9abc-ccf34ab0dbb3.png)

Now one could argue that the Matrix network has large groups that are discoverable and public and should therefore be categorized as social network. The next step for a social network looks like this:

![IARC social network](https://user-images.githubusercontent.com/36048059/89287981-2f28f900-d655-11ea-9dea-b4cd01e9154a.png)

The problem here is that Matrix is a federated network and although the matrix community on matrix.org has [code of conduct](https://matrix.org/legal/code-of-conduct) the protocol itself does not have any content restrictions except for images of child abuse AFAIK. That would mean that sharing of nudity on your own server without violating the laws of your country would be legal. Then you will definitely end up with an USK18 rating.

---

But is Element really a social network? I would rather support the statement that Matrix is a network and Element a tool to access it like Firefox is a tool to access the WWW. If we would categorize Element as a communication tool the questions of IARC would not apply on user-generated content and Element would therefore come without age restrictions.
