### ISSUE TITLE
Attempt to upload 20 megs video to encrypted room fails with OOM

### ISSUE THREAD

**Issue by unclechu** [vector-im/element-android#1862]
![Screenshot_2020-08-02-15-31-55](https://user-images.githubusercontent.com/799353/89123180-1514dc80-d4d6-11ea-8c83-f4b36eb403d0.png)
![Screenshot_2020-08-02-15-31-59](https://user-images.githubusercontent.com/799353/89123182-15ad7300-d4d6-11ea-8d72-a055b71a9c1d.png)

**Comment by unclechu** [comment]
I can successfully upload a lot larger videos with the old legacy Riot.

**Comment by BillCarsonFr** [comment]
Hello did you submit a bug report from the app (rageshake) so i can learn more?

**Comment by BillCarsonFr** [comment]
Related to #1619 (although this video is not that big)

**Comment by unclechu** [comment]
@BillCarsonFr 
> Hello did you submit a bug report from the app (rageshake) so i can learn more?

Nope, I turned that feature off. Should I do this? In context of data privacy what data will be collected and sent if I do so?

**Comment by BillCarsonFr** [comment]
This will send us technical logs (that you could see using logcat on your device), these logs do not contains sensitive informations (access token, message content) but they contain application usage data including your username, the IDs or aliases of the rooms or groups you have visited and the usernames of other users.

**Comment by unclechu** [comment]
@BillCarsonFr I sent a rage-shake report with a mention of this issue number in the description.

**Comment by BillCarsonFr** [comment]
Can you retry with version 1.0.6 ?

**Comment by unclechu** [comment]
@BillCarsonFr 
Successfully uploaded ≈48M video file. First encryption progress bar reached 100% and then uploading bar again. This seems to be fixed now, cool.

Though I still can’t:

1. View any of the videos, both encrypted and not encrypted (but there’s a separate issue for that)
2. See thumbnails of encrypted images and videos (I see just empty space instead of them)
3. See encrypted images, I see only black screen when I open them

**Comment by unclechu** [comment]
Since it’s working on 1.0.6 I think this issue may be closed.

**Comment by unclechu** [comment]
After an update to 1.0.7 now I can see previews for both encrypted and unencrypted photos and videos. I can view images both encrypted and unencrypted. Only the videos couldn’t be played (see #1785).

@BillCarsonFr I’m closing this issue as **solved**.
