### ISSUE TITLE
Not robot checking pictures disappear after rotation

### ISSUE THREAD

**Issue by geniuslittleteddy** [vector-im/element-android#1875]
When I tap on any pictures in the not robot checking pics and rotate device, the pictures get disappear

![Screen Shot 2020-08-04 at 10 42 50 PM](https://user-images.githubusercontent.com/67744580/89307935-404d2680-d6a4-11ea-8db5-dff3a6dc3917.png)
![Screen Shot 2020-08-04 at 10 43 00 PM](https://user-images.githubusercontent.com/67744580/89307941-42af8080-d6a4-11ea-8445-4e2a1eb37ed0.png)

**Comment by bmarty** [comment]
Seems that you are still using an old app (the logo is not the last one).
Also in your case I think you just have to click on the checkbox to restart the process, I do not really see an issue here.
