### ISSUE TITLE
Element app security...sending connection data to Google?? IP connections to made to Google, why?

### ISSUE THREAD

**Issue by dimyself** [vector-im/element-android#1876]
Ok, so I recently got into Element/Riot. When I turn on my Android firewall to monitor outgoing connections, Element makes several connections to Google and a couple to Cloudflare. I'm just trying to figure out why they're going through Google? Can Google record the data going through the requests? I realize Element is encrypted, but they could possibly still record all data going through possibly? 

Why are all the Element connections/requests going to Google IP's? I switched to Riot/Element to try to avoid Google and companies like google's data collection. 

Is there a better place to ask/post this? I really would like to understand this, thank you

**Comment by ara4n** [comment]
It'll be using Google for push notifications. If you want to avoid Google, use the Fdroid build instead.

It'll be talking to Cloudflare if you're using the default matrix.org server, as that's hosted behind Cloudflare for DDoS mitigation.

**Comment by immanuelfodor** [comment]
What is the difference between the Google Play and Fdroid builds regarding push notifications? How are push notifications handled in the Fdroid one if not using Google FCM?
