### ISSUE TITLE
Uploads still don't work with room v6

### ISSUE THREAD

**Issue by tulir** [vector-im/element-android#1879]
This is a duplicate of #1558 and #363, but those are closed. The original issue is not fixed, build G-b3395 still sends floats:

```
2020-08-05 15:21:40,949 - synapse.http.server - 74 - INFO - PUT-1025098- <XForwardedForRequest at 0x7fe21aecfcc0 method='PUT' uri='/_matrix/client/r0/rooms/!EgoVrPyOnPSVXERlxj:gruenhage.xyz/send/m.room.message/$local.5c720e50-9523-4594-a666-20b063111cdb' clientproto='HTTP/1.1' site=8008> SynapseError: 400 - Bad JSON value: float
2020-08-05 15:21:40,949 - synapse.access.http.8008 - 310 - INFO - PUT-1025098- 172.19.0.1 - 8008 - {@tulir:maunium.net} Processed request: 0.011sec/0.000sec (0.004sec, 0.000sec) (0.000sec/0.005sec/2) 56B 400 "PUT /_matrix/client/r0/rooms/!EgoVrPyOnPSVXERlxj:gruenhage.xyz/send/m.room.message/$local.5c720e50-9523-4594-a666-20b063111cdb HTTP/1.1" "Element dbg/1.0.5-dev (Linux; U; Android 10; CLT-L29 Build/HUAWEICLT-L2; Flavour GooglePlay; MatrixAndroidSDK_X 0.0.1)" [0 dbevts]
```

![image](https://user-images.githubusercontent.com/4224639/89431589-d20e6f80-d748-11ea-9ccc-ffe1a8b92550.png)

**Comment by colalord** [comment]
Please fix this.  I have several Android users that have been experiencing this same issue for awhile now and are becoming reluctant to upgrade anymore at this point.

**Comment by richvdh** [comment]
oh interesting. I saw this recently and thought it was a network problem.

@BillCarsonFr : any idea why it would be sending floats?

**Comment by richvdh** [comment]
oh, I see #363 has more details.

**Comment by EchedeyLR** [comment]
So, didn't https://github.com/vector-im/element-android/pull/1766 solve the issue?

**Comment by EchedeyLR** [comment]
How is that a release made 22 days ago (https://github.com/vector-im/element-android/releases/tag/v1.0.2) solves an issue that was commited 17 days ago (https://github.com/vector-im/element-android/commit/aa5de1896fd07d89ba82cfb86b9fc0f88f6b6867)?

**Comment by resynth1943** [comment]
Hi guys,

Any updates on this?

**Comment by colalord** [comment]
I downloaded and compiled the v1.0.5 dev branch about a week and a half ago.  Image uploads seemed to work with that.  

I see that v1.0.5 was just released on 8/21/2020.  It's on F-Droid and I'm expecting it to be on the Google Play Store in the next day or so as it usually lags a couple days behind F-Droid.  I have hopes that the production release of v1.0.5 fixes this issue.  I will be testing it as soon as it drops to the Google Play Store.

**Comment by TheEvilSkeleton** [comment]
No it doesn't. My friends and I tried it and it never got fixed

**Comment by colalord** [comment]
Well that’s a bummer.

**Comment by EchedeyLR** [comment]
I reported here coming from F-Droid 1.0.5 in first place.

**Comment by colalord** [comment]
Were you and your friend uploading images to a v6 room that’s encrypted or unencrypted?

I’ve done a little more testing and the issues seems to be resolved if uploading images to an encrypted v6 room but not so much if uploading to an unencrypted v6 room.

**Comment by EchedeyLR** [comment]
In my case is unencrypted.

**Comment by TheEvilSkeleton** [comment]
Same

**Comment by tulir** [comment]
There was never any issue with encrypted rooms. The problem is that Element Android sends float values (`1234.0`) as sizes, but Matrix events are only allowed to have integers (`1234`). The server doesn't know what events in encrypted rooms contain, so it can't validate those.

**Comment by colalord** [comment]
Ah, makes sense. 

I was aware of the float values issue.  I hadn't realized it was limited only to unencrypted v6 rooms.  I had thought that would be an issue for both encrypted and unencrypted rooms, regardless.  Thanks for the info.

Sounds like this just hasn't been fixed despite the bug fix notes.
