### ISSUE TITLE
Hardware keyboard enter inserts a newline instead of sending message

### ISSUE THREAD

**Issue by vranki** [vector-im/element-android#1881]
Normally (practically in all other IM's including Element Desktop) pressing enter key sends the typed message. In Element Android hardware enter key inserts newline in the text input field. 

Tested on Gemini PDA and Cosmo Communicator.

**Comment by Funkenschuhster** [comment]
I can confirm this behaviour. I would appreciate it if the option is adjustable. The background for this is that Telegram for Android sends with CTRL&Enter.

Testet with USB keyboard attached to S10e running Samsung Dex

**Comment by vranki** [comment]
Setting and/or alternative key to insert newline could be implemented as a feature. But default behavior should clearly to be send the message. Also old Riot Android used to work this way.

**Comment by eras** [comment]
Personally I rather enjoy the current behaviour, but I can confirm that both Slack and Hangouts work as described on Android, so perhaps that is the user expectation.
