### ISSUE TITLE
FATAL EXCEPTION: main pressing the button on wired headset 

### ISSUE THREAD

**Issue by 532910** [vector-im/element-android#1885]
Steps to reproduce:

0. not sure if this step is required: make a voice call and hang up it with the button on wired headset
1. press the button on a wired headset

```
D AndroidRuntime: Shutting down VM
E AndroidRuntime: FATAL EXCEPTION: main
E AndroidRuntime: Process: im.vector.app, PID: 23749
E AndroidRuntime: android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{fe762c7 u0 im.vector.app/im.vector.riotx.core.services.CallService}   
E AndroidRuntime:       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1945)
E AndroidRuntime:       at android.os.Handler.dispatchMessage(Handler.java:107)
E AndroidRuntime:       at android.os.Looper.loop(Looper.java:214)
E AndroidRuntime:       at android.app.ActivityThread.main(ActivityThread.java:7356)
E AndroidRuntime:       at java.lang.reflect.Method.invoke(Native Method)
E AndroidRuntime:       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
E AndroidRuntime:       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
```

This is reproducable on Android 9 and 10.
The button is that one that short circuits mic to ground.
https://source.android.com/devices/accessories/headset/plug-headset-spec

**Comment by toshanmugaraj** [comment]
##Send relaunched pending events on restart
 ##Send - Recovering unsent events []
 /Tag: Starting sync thread
 /Tag: Keys already uploaded, nothing to do
/Tag: maybeUploadOneTimeKeys: waiting to know the number of OTK from the sync
/Tag: ## VOIP onServiceConnected 1 , proxy:android.bluetooth.BluetoothHeadset@d5b661e
 /Tag: ## onCreate() : im.vector.app.core.services.CallService@1ec75ef
 /Tag: ## onDestroy() : im.vector.app.core.services.CallService@1ec75ef

`Thread: main, Exception: android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2188)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8167)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)`
