### ISSUE TITLE
1-1 rooms mistakenly listed in the "Rooms" tab instead of "Direct messages" 

### ISSUE THREAD

**Issue by Ezwen** [vector-im/element-android#1887]
**Describe the bug**

On the phone of a friend, some 1-1 discussions are listed in the "Rooms" tab instead of the "Direct messages" tab.

**To Reproduce**

I am not sure how, these discussions are rather old and have been created with a much older version of Riot. 

**Expected behavior**
I would expect either:
- to be able to move 1-1 discussions from "Rooms" to "Direct messages" manually,
- or to have Element automatically put these discussions in the "Direct messages" tab. 

**Screenshots**
Sorry I don't have relevant screenshots that I can share. 

**Smartphone (please complete the following information):**
 - Device: I do not know, I will check.
 - OS: I do not know, I will check.
 - App version and store 1.0.3 - F-Droid

**Comment by BillCarsonFr** [comment]
Do you have a web session? If yes do you see those discussions as DM?
Currently Element android does not support moving a discussion from DM to Room.

Maybe you can check Settings > Advanced Settings > DevTools > Account Data
if the room is DM, it should appear under the m.direct settings

**Comment by Ezwen** [comment]
No unfortunately I do not see these discussions as DM in Element-web, but this was less a problem for my friend since both DM and Room discussions are presented in the same pane. While with Element-android these are in a separate "tab" in the UI, making things rather confusing. Also, indeed, the room is not part of `m.direct` when checking with the dev tools.

So this is not a bug specific to Element-android after all, you are right. Any idea how I could move the discussions back to DM? Is there any matrix client that is able to do such a thing?

**Comment by bmarty** [comment]
> Any idea how I could move the discussions back to DM? Is there any matrix client that is able to do such a thing?

It was possible before on Element Web, but I cannot find the option anymore.

The only way to do it, AFAIK, is to update the `m.direct` account data manually, you can do that in Element Web by typing `/devtools` in any room. But do not do it if you're not sure about what you are doing.

The other way is to create a fresh new DM with your friends.

**Comment by bmarty** [comment]
FTR the option to toggle DM/not DM has been removed on Element Web to prepare canonical DM feature.
