### ISSUE TITLE
Users often accidentally ignore other users

### ISSUE THREAD

**Issue by aaronraimist** [vector-im/element-android#1890]
**Describe the bug**
I have seen a lot of reports of users accidentally ignoring other users recently. It seems like some confimation step or something should be added. Most of the reports are from people using both Element Web and Element Android so I'm not sure which client actually did the accidental ignore but it seems likely that it could be Element Android.

Related web issue: https://github.com/vector-im/element-web/issues/14633

<img width="975" alt="screenshot" src="https://user-images.githubusercontent.com/5855073/89670025-195e4280-d8a6-11ea-97bc-dd7e5aaaf77b.png">

**Comment by aaronraimist** [comment]
Yeah it seems like if you press and hold on a message, there is no confirmation required if you tap "Block user" and there is also no indication that you blocked them. The "Block user" button doesn't even change to say "Unblock user" or anything.

This is a major issue. I have seen A LOT of people reporting this lately.

**Comment by bmarty** [comment]
I add a confirmation dialog when ignoring a user from the bottom sheet.
I created #1899 for the remaining things to do

**Comment by aaronraimist** [comment]
Is there a new version coming soon with this? Still happening to lots of users.
