### ISSUE TITLE
[Bug] App crashing by sending more files

### ISSUE THREAD

**Issue by DoM1niC** [vector-im/element-android#1891]
**Describe the bug**
App crashing by sending more files

**To Reproduce**
Sending around 10 e.g. Pictures or more...

**Expected behavior**
-

**Screenshots**
-

**Smartphone (please complete the following information):**
 - Device: Mate 20 Lite
 - OS: Android 10
 - App version: Develop / new Feature/enhance big files Pull Req don't fix it, still exist

**Additional context**
-

**Comment by BillCarsonFr** [comment]
Hello @DoM1niC , can you send a rage shake so I can have a look at the  logs?
Is it an Out of Memory error?

**Comment by DoM1niC** [comment]
> Hello @DoM1niC , can you send a rage shake so I can have a look at the logs?
> Is it an Out of Memory error?

I could log in Android Studio soo give me some Minutes.

**Comment by DoM1niC** [comment]
The problem seems meanwhile fixed now after a lot of fixes...
