### ISSUE TITLE
Share (merge) Element-Android Glossary dictionaries on translate.riot.im with Web version

### ISSUE THREAD

**Issue by MurzNN** [vector-im/element-android#1903]
Please merge (share) Weblate Glossaries (dictionaries) of Element-Android with Element-Web and Element-iOS on translate.riot.im translation server! Also maybe good to share them with Nio and other Matrix clients, managed in this server, too.

As I see here https://docs.weblate.org/en/latest/user/translating.html - Weblate support this:

> Glossaries are shared among all components of the same project and you can also choose to share them with another projects.

For example, here is Russian glossaries: https://translate.riot.im/dictionaries/element-android/ru/, https://translate.riot.im/dictionaries/riot-ios/ru/ and https://translate.riot.im/dictionaries/element-web/ru/ that must contain almost same source words, but now translators must manage them in two places and sync manually via hands.

As result, many "not easy" source words translated differently in Android, iOS and Web version, that is bad for UX.

**Comment by bmarty** [comment]
Closed in favor of https://github.com/vector-im/element-web/issues/17112
