### ISSUE TITLE
Transition to using matrix-doc for SAS Emoji translations

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-android#1909]
See https://github.com/matrix-org/matrix-doc/pull/2728

**EDIT Benoit**:
IIUC, we should, to handle this issue:
- Remove all existing SAS emoji words from our current SDK codebase (`strings.xml` files)
- Write a script to import translations from the file https://raw.githubusercontent.com/matrix-org/matrix-doc/master/data-definitions/sas-emoji.json into file (SDK) `value/strings_sas.xml` and files `value-XX/strings_sas.xml` to not interfere with existing `strings.xml` files already handled by Weblate Element Android project. _Note_: we can get inspiration from the script https://github.com/matrix-org/matrix-doc/blob/master/scripts/i18n.py which actually update the file sas-emoji.json with the exploded translations from Weblate. So we are doing the revers operation here, the advantage is that the script will download only one file.

And before each release we should:
- run the script created  above and commit changes.

**Comment by progserega** [comment]
Do this translation will be use in selection of emogi in "text-edit" window? For non-english users to hard understand how needed emoji named and how it is select by ':'...

**Comment by turt2live** [comment]
This is only for the emoji used during device verification, nothing to do with the text editing or `:` selection.

**Comment by progserega** [comment]
It's a pity!
