### ISSUE TITLE
[F-Droid] Excessive offline battery usage

### ISSUE THREAD

**Issue by fsub** [vector-im/element-android#1915]
**Description**
When running in the background with no network access (mobile data and wi-fi disabled) Element consumes unreasonable amounts of energy. If the device is mainly in standby mode, it takes up more than a third of the total battery capacity. It looks like the program tries to perform a synchronization every 10 seconds.

**To Reproduce**
1. Fully charge the device and disconnect it from the power supply.
2. Disable all network access (i.e. mobile data and wi-fi).
3. Let Element run in the background.
4. Notice that every 10 seconds an icon pops up briefly in the status bar.
5. Put the device into standby mode and leave it in this state for a few hours, at least.
6. Check the battery status and observe excessive energy consumption.

**Expected Behavior**
In the situation described, Element should not have more than one tenth of the current energy requirement.

**Smartphone / Tablet**
 - Device: Samsung Galaxy S5 / Samsung Galaxy Tab S2
 - OS: Lineage OS 14.1 (Android 7.1.2)

**Additional Context**
 - Element 1.0.4 - F-Droid

**Comment by DoM1niC** [comment]
this is currently normal, I have the same Problem and my friends so the Background Service seems to eat to much & for me the Notification loops every unread Messages after I swipe it away ....

**Comment by dontub** [comment]
I've proposed two possible solutions in #1920 to stop background sync when no network connection is available.

**Comment by BillCarsonFr** [comment]
Thx, i will look at this while doing fdroid background sync rework #2055
