### ISSUE TITLE
there's a white screen that loads briefly as the app boots, even with dark mode enabled

### ISSUE THREAD

**Issue by ericmigi** [vector-im/element-android#1917]
**Describe the bug**
Very bright when I'm trying to sneak a peek at messages at night. Wakes wife up :/

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Samsung S6]
 - OS: [e.g. Android 6.0]

**Additional context**
 - App version and store [e.g. 1.0.0 - F-Droid]
 - Homeserver: [e.g. matrix.org]

**Comment by bmarty** [comment]
Do you observe that with other app too, on your Android 6 device?

**Comment by ericmigi** [comment]
No, it only happens with riotx. Pixel 4 running latest Android beta

**Comment by ericmigi** [comment]
Oddly enough, this morning I opened riotx and there white interstitial is gone! Now it's solid green with element logo.
