### ISSUE TITLE
Display name not shown under Settings/General

### ISSUE THREAD

**Issue by srehm** [vector-im/element-android#1926]
**Describe the bug**
The display name of the user is not shown when opening the 'General' settings category.

**To Reproduce**
1. Sign in with new user
2. Go to Settings -> General
3. Edit the display name
4. Note that immediately after editing, the display name is shown as expected
5. Close the settings dialog
6. Verify that the display name was indeed stored in the homeservers database
7. Go to Settings -> General again
8. Note that the previously set display name is no longer shown

**Expected behavior**
The display name of the user should be shown in the settings once it is properly configured.

**Smartphone (please complete the following information):**
 - Device: Moto X4
 - OS: Lineage OS 17.1

**Additional context**
 - App version and store: 1.0.4 from Play store

**Comment by bmarty** [comment]
I do not reproduce the issue FTR, the new display name is correctly displayed at step 8.

**Comment by srehm** [comment]
I did some testing. The issue is reproducable in the android emulator as well. The AVD I use is a Pixel 3a with Android API 29.
When attaching the debugger, I can see that in `VectorSettingsGeneralFragment.bindPref()` the displayName property of the user returned by `session.getUser()` is always null.
Could this be a synchronization issue between the local realm db and the homeserver?
