### ISSUE TITLE
Share button in rooms gives room ID link without via parameters

### ISSUE THREAD

**Issue by tulir** [vector-im/element-android#1927]
The share button in the top right of the room info view shows a matrix.to URL with the room ID (e.g. https://matrix.to/#/!AZozoWghOYSIAfaZjJ:matrix.org). Such links are not routable, and can't be used for joining rooms*. Sharing links that can't be used is rather pointless.

Element Web solves this by including up to three servers in the `via` query parameter: https://matrix.to/#/!AZozoWghOYSIAfaZjJ:matrix.org?via=matrix.org&via=privacytools.io&via=tchncs.de

The other option is to make the share button create a link with the canonical alias of the room (e.g. https://matrix.to/#/#element-android:matrix.org), but room IDs are more permanent.

<sup>* unless your server happens to know about the room already</sup>

**Comment by bmarty** [comment]
Do the extra parameters `via=matrix.org&via=privacytools.io&via=tchncs.de` static and applicable to any rooms from any homeserver?

**Comment by tulir** [comment]
No, you need to look at the room member list to find the servers (iterate over members with `membership=join` and parse the homeserver out of the user ID). It's best to pick the servers with the most members, since those are the least likely to leave the room completely. Another good choice is the current user's server (so 2 servers with the most users + current server)

**Comment by bmarty** [comment]
Thanks @tulir for those implementation details
