### ISSUE TITLE
Save the connection information when logging out from server

### ISSUE THREAD

**Issue by damnms** [vector-im/element-android#1933]
the web version of element is easy configurable to always use matrix.mydomain.com as matrix server, but the app not

i have a homeserver running on matrix.mydomain.com
when i log out from the android app, i have to re-enter the same information again and again and again, whenever i log out.
would it be possible to save the last matrix login server(s) ?
i have 5 test accounts and 2 productive accounts, thats pretty annoying

**Comment by TR-SLimey** [comment]
As far as I know, logging out from Element is only supposed to be used when you don't intend to use that device anymore. This means that it's supposed to wipe all your account data from the client - homeserver included. I think you're really looking for multi-account support (as detailed in #[issue no. to be found]) in order to not have to log out at all.

If you want to change the default homeserver for Element Android, you'll have to re-compile it.

**Comment by bmarty** [comment]
I understand the use case.

The app could remember the previously used homeservers URL and propose them for completion when typing the homeserver url. Also it should be possible to wipe out the history.

**Comment by damnms** [comment]
> As far as I know, logging out from Element is only supposed to be used when you don't intend to use that device anymore.
Well.. i would understand this behaviour when i do a factory reset of that device or delete the app.
But just logging out... means deleting all account data? Really?

**Comment by bmarty** [comment]
To clarify, logging out clear all data on the Android device, but does not clear anything server side, except the Access Token of course.

**Comment by TR-SLimey** [comment]
> > As far as I know, logging out from Element is only supposed to be used when you don't intend to use that device anymore.
> 
> Well.. i would understand this behaviour when i do a factory reset of that device or delete the app.
> But just logging out... means deleting all account data? Really?

From the device - yes. You wouldn't want to log in on a friend's device, then log out, and have some of your information left on their device. You certainly wouldn't make them factory-reset their phone after that.

An alternative to logging out is coming in the next update I believe - app locking.
