### ISSUE TITLE
Suggestion: Fall back to long polling if setting up push gateway fails

### ISSUE THREAD

**Issue by timokoesters** [vector-im/element-android#1936]
I want people to start using the Conduit homeserver, but it doesn't support push gateways yet. I think currently the google play build just doesn't receive messages if the app is closed while the fdroid build works (with some huge delay though for some reason).

I'd like Element Android to fall back to long polling if it figures out the homeserver does not support push gateways (404 on the CS endpoints or maybe a new `capability` in the spec?)

**Comment by timokoesters** [comment]
After some investigation it seems like it does work, but android's "optimize battery usage" feature makes it very unreliable.

**Comment by immanuelfodor** [comment]
The Gotify app uses websockets instead of FCM, and it's very reliable after removing the default battery optimization under app settings. Maybe it's worth a look.

**Comment by timokoesters** [comment]
My main reason for opening this issue was that conduit did not support pushers. Now it does, so I will close this issue. If someone else is interested they can reopen.
