### ISSUE TITLE
Editing a message (multiple) before it got eventually send breaks the sending process completely

### ISSUE THREAD

**Issue by lockejan** [vector-im/element-android#1938]
**Describe the bug**
I tried to send a reply to a message in a chat room.
The rendered result after sending wasn't properly formatted so I edited it again to fix it and send it again.
It took me two more times to get a message formatting which was okayish.
However the message wasn't successfully send to all recipients in the chat room in the first place and now blocks my client of sending anymore messages to the chat-room, because I can't delete the pending message.
Any new message now gets a pending status by default.
The message queue is in a broken state for outgoing messages.
I still receive messages from other participants in the chat-room though.

**To Reproduce**
1. Go to 'your-chatroom'
2. Prepare a message reply
3. Send it
4. Edit it immediately after hitting send
5. Change the content a little
6. Try sending the updated message
7. Get stuck with a light-grey message body on your client indicating that the message is still pending and has not yet been sent.

**Expected behavior**
An updated message in the chat-room

**Screenshots**
![Sending Issue](https://user-images.githubusercontent.com/25434434/90377733-b2e0dd80-e078-11ea-82a4-ed8f107f0086.jpg)

**Smartphone (please complete the following information):**
 - Device: Samsung S8
 - OS: Android 9

**Additional context**
 - App version and store beta-Program in Android App Store
 - Homeserver: private home-server running `synapse:v1.17.0-py3`

**Comment by faaaaabi** [comment]
I get into to a similar problem if I post a very large message >> 4000 characters. In my case copied from a webpage. Element desktop warns me, that the message is to big and gives me the chance to cancle sending, Element Android does not.

**Comment by faaaaabi** [comment]
So until I'm not able to cancle the sending process, I'm not able to send messages to the group anymore via Element for Android.
