### ISSUE TITLE
Editing message forgets line breaks and markdown

### ISSUE THREAD

**Issue by Porrumentzio** [vector-im/element-android#1939]
**Describe the bug**
When sending a message with line breaks and/or markdown markup and taping the *edit* option, those line breaks and markdown markups disappear, resulting in very odd messages.

**To Reproduce**
1. Go to a sent message
2. Click on "edit"
3. The line breaks and markdown have disappeared

**Expected behavior**
When editing a message, all of its line breaks and markdown should stay in a editing mode (should appear the *, _, ` and so on).
The line breaks should also stay.

**Screenshots**
Here can be seen the message with markdown (also line breaks, but that's not so evident)
![IMG_20200817_154412](https://user-images.githubusercontent.com/61913683/90403009-9c4e7c80-e0a0-11ea-96ab-a34e03194891.jpg)

Here can be seen how, when editing, the line breaks and markdown is lost.
![IMG_20200817_154436](https://user-images.githubusercontent.com/61913683/90403186-de77be00-e0a0-11ea-89ee-9baaae2d884a.jpg)

**Smartphone (please complete the following information):**
 - Device: Xiaomi Redmi Note 4 X
 - OS: /e/OS Android 7 Nougat

**Additional context**
 - 1.0.4 F-Droid
 - matrix.org

**Comment by absorber** [comment]
Seems to be related to https://github.com/vector-im/element-android/issues/853 and https://github.com/vector-im/element-android/issues/1982

**Comment by Porrumentzio** [comment]
Will this also correct the line breaks issue?

**Comment by bmarty** [comment]
This one could actually be closed by #2002, please reopen it if it is not the case (to check on Element Android v1.0.6)

**Comment by Porrumentzio** [comment]
Hi! I'm on Element Android 1.0.7 and line breaks still get forgotten after editing.
