### ISSUE TITLE
I can't see total votes, also no secret voting

### ISSUE THREAD

**Issue by V3YNjKbFGLSQ0FzpOu1s** [vector-im/element-android#1942]
I post polls in groups via the /poll function but only my votes get counted. I asked other users to post their own polls and they observed the same behavior. In addition, when a user votes a poll, a message that reads { "type": m.room.message } appears and lets you know who voted what when you push on the message. Wouldn't it be better if the votes were secret or if there was an option to make the votes secret?

**Comment by bmarty** [comment]
Obsolete now with the new poll implementation (#4360 and #4624).
Votes cannot be secret, since you cannot hide Event to other user in a timeline. But vote events will be hidden by default on Matrix client supporting correctly the feature.
