### ISSUE TITLE
java.lang.RuntimeException: Canvas: trying to draw too large bitmap.

### ISSUE THREAD

**Issue by onurays** [vector-im/element-android#1951]
Crashes while trying to show large images in attachment preview.

**Comment by allendema** [comment]
@onurays This has been happening in Version 1.1.6 from F-Droid too.

All media can be viewed from Room > Uploads > Media but one particular image causes the app to crash.
Which reopens the app or just leaves the Upload Menu and goes back to the Room. 

Can you check on that?


[Gist of the log](https://gist.github.com/allendema/8d7aa6d1e4d1df0be4947ca883b9be5d)

**Comment by bmarty** [comment]
The crash could also occurs when the image is displayed in the timeline.
The app has to be more robust when handling such big images
