### ISSUE TITLE
[SSO] Sign out of session -> Error

### ISSUE THREAD

**Issue by hex-m** [vector-im/element-android#1953]
**Describe the bug**
I try to log out of an unverified session but get an error. My setup uses SAML based SSO.

**To Reproduce**
1. Set up a server and configure SAML SSO
2. Log into your account with different clients
3. Log into your account on Element-Android 
4. Open the "Security & Privacy" settings and choose "Show All Sessions"
5. Select on of the "Other sessions" and choose "Sign out of this session"

I get the following Error:
`java.lang.RuntimeException: RegistrationFlowResponse(flows=[InteractiveAuthenticationFlow(type=null, stages=[m.login.sso])],completeStages=null, session=clCyz[...]vuH,params={})`

**Expected behavior**
It should work analogous to Element-Web. There I get asked to re-authenticate and afterwards the Session is removed.

**Smartphone (please complete the following information):**
 - Device: Fairphone 3 (FP3)
 - OS: Android 9

**Additional context**
 - Version 1.0.4 from f-droid
 - Homeserver: internal, but I can offer an account to reproduce if necessary

**Comment by bmarty** [comment]
Yes, thanks for reporting, we are aware that it is not yet supported (see #1264)

**Comment by hex-m** [comment]
Thanks for the reply and sorry for not finding the other report. I consider this a duplicate and close it.
