### ISSUE TITLE
A Kick appears has "someone has made no change"

### ISSUE THREAD

**Issue by erdnaxeli** [vector-im/element-android#1959]
**Describe the bug**
Someone kicked someone else. On element android I see (in french) "Someone n'a effectué aucun changement" (which could be translated to "Someone has made no change") while on element web I see "Someone has kicked someone else".

**To Reproduce**
I am not sure, when I try to reproduce it the event is shown correctly.

**Expected behavior**
I expect element android to show me "Someone has kickes someone else".

**Screenshots**
![2020-08-19-101831_603x92_scrot](https://user-images.githubusercontent.com/479441/90610246-71316d80-e205-11ea-8833-e84aa0eb33a5.png)
![Screenshot_20200819-101738](https://user-images.githubusercontent.com/479441/90610317-8a3a1e80-e205-11ea-9ade-de39df175068.png)

**Smartphone (please complete the following information):**
 - Device: Moto G4 Plus
 - OS: Android 8.1.0

**Additional context**
 - App version and store 1.0.4 on Playstore
 - Homeserver: cervoi.se

The user doing the kick is a bridged one from IRC, but I don't see why it would change anything.

**Comment by bmarty** [comment]
Can you send the content of the Event please?

**Comment by erdnaxeli** [comment]
Sure:
```
{
  "content": {
    "membership": "leave",
    "reason": "attention derrière toi ! "
  },
  "event_id": "$159782383733024WwvKp:iiens.net",
  "origin_server_ts": 1597823837042,
  "sender": "@irc_PrinceCaramel:iiens.net",
  "state_key": "@irc_Tuareg:iiens.net",
  "type": "m.room.member",
  "unsigned": {
    "prev_content": {
      "membership": "leave"
    },
    "prev_sender": "@irc_Tuareg:iiens.net",
    "replaces_state": "$15729348546465XXTuX:iiens.net",
    "age": 335970
  },
  "room_id": "!XOjaoEoAmGOyLzYKMD:iiens.net"
}
```

**Comment by bmarty** [comment]
> The previous event already being a leave might explain it.

Indeed. I have no idea why Element Web is correct though

**Comment by erdnaxeli** [comment]
My guess is that the IRC bridge never make the user join, and element android and web have a different behavior with a leave -> leave event. I think I prefer the behavior of element web, but I am sur I don't like the element android one. "Nothing has changer" is really disturbing.

Btw this is not related to this issue but the IRC bridge should probbly make a user join before kicking it.
