### ISSUE TITLE
Sending a message in rare circumstances will make it get "stuck" at the bottom of the sent messages

### ISSUE THREAD

**Issue by Rares95** [vector-im/element-android#1967]
I have this happen on 2 phones, one with RiotX, another one with latest Element.

The first time happened with a text message, it would be stuck in the last sent message position no matter what. Clearing cache didn't work either, only reinstalling the app...

The second time happened with a photo. It's really annoying and i need to reinstall to fix it... Only on Android

![image](https://user-images.githubusercontent.com/2606875/90728931-114ecb80-e2c6-11ea-9677-cab6c6873247.png)

**Comment by bluecmd** [comment]
Same for me. In RiotX this felt like it happened all the time, now it happened for the first time for me in Element.

**Comment by bluecmd** [comment]
Also, probably a duplicate of https://github.com/vector-im/element-android/issues/516

**Comment by Rares95** [comment]
Duplicate of https://github.com/vector-im/element-android/issues/516
