### ISSUE TITLE
Can't login to homeserver - "homeserver outdated".

### ISSUE THREAD

**Issue by vladimir-ipatov** [vector-im/element-android#1972]
Hello! I Recently updated android element client (1.0.4).
I have account on my phone logged in before, it works good.

But after logout I can't login again.
Click "Start"
Click "Another"
typing my homeserver address and get:

"Homeserver outdated
This homeserver using too old version for connection
Ask administator to update homeserver"

And can't continue.

server version: 0.99.2-5~bpo9+1 from debian stretch backports.

Why I can't use new client with my server despite it technically works?
What the reasons for this weird step?
Why it is not documented?

It have me to remember 2008 when ICQ was changed protocols every 2-3 months and I could not able to use it :)

**Comment by violoncelloCH** [comment]
well there are security reasons to update your homeserver...
and there are other things that have been changed/added to the specification which are being used by the current element-android

**Comment by bmarty** [comment]
Just tested with your homeserver and in your case [this method](https://github.com/vector-im/element-android/blob/894f5b9ed3b2b7caafcd3af3aa75c9da97a867a9/matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/auth/version/Versions.kt#L67) will return false, so login and account creation is not possible because Element Android (sadly) only support the latest API.
We have made the choice when writing RiotX (which is now Element Android) to not waste time supporting deprecated API. Sorry for the inconvenience...

**Comment by vladimir-ipatov** [comment]
> Just tested with your homeserver and in your case [this method](https://github.com/vector-im/element-android/blob/894f5b9ed3b2b7caafcd3af3aa75c9da97a867a9/matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/auth/version/Versions.kt#L67) will return false, so login and account creation is not possible because Element Android (sadly) only support the latest API.
> We have made the choice when writing RiotX (which is now Element Android) to not waste time supporting deprecated API. Sorry for the inconvenience...


So, as I cant see in this test:

```
/**
 * Indicate if the `id_server` parameter is required when registering with an 3pid,
 * adding a 3pid or resetting password.
 */
private fun Versions.doesServerRequireIdentityServerParam(): Boolean {
    if (getMaxVersion() >= HomeServerVersion.r0_6_0) return false
    return unstableFeatures?.get(FEATURE_REQUIRE_IDENTITY_SERVER) ?: true
}

```

This test related with 3pid registering and so on.
So, may be normal login (without 3pid) will work?

So, if I understand a situation right way:
1) There is old way to login with internal ids. There is no changes in API about it.
2) There is new way to login with 3pid. Old homeservers does not support it.
3) You do the tests in client and without support NEW WAY in your homeserver you can't use OLD WAY.
So, what's the point?
You may allow to login old way without special work to implement it. Just correct tests in application. Like an iOS client.

**Comment by bmarty** [comment]
> Just correct tests in application. Like an iOS client.

I understand your frustration, but as I said, we didn't want to spend time to support old versions of the Client Server API. As you may know, Element Android is a rewrite of Riot-Android, so it has not all the history in it, in the contrary to Element iOS, which is just a renaming of Riot iOS.

Maybe we could make the blocking popup just a warning and let user try to log in, as it may work as you said.

That said, for security reason (as mentioned by @violoncelloCH), homeservers should always be up to date.

**Comment by vladimir-ipatov** [comment]
> Maybe we could make the blocking popup just a warning and let user try to log in, as it may work as you said.
Yes, thats what I talking about. Thats will be easy to do and logically correct.
And, finally, it will allow some users continue to use your application.

P.S. If you go to google play page, you will see couple comments with rating 1 from angry users (not from me :) ) faced with this issue

**Comment by vladimir-ipatov** [comment]
Yesterday my employee spent 20 minutes to compile application with that test commented out.

Everything works with old homeserver.

Here is apk, if you want to test it:

https://m.c-mit.ru/_matrix/media/r0/download/c-mit.ru/ZPnMNRHvvQPYMWUiKscdaieN

**Comment by bmarty** [comment]
Ok, we will make this popup non-bloquing. However some features may not work properly when using an outdated homeserver.
