### ISSUE TITLE
Markdown Not Rendering

### ISSUE THREAD

**Issue by dwmunster** [vector-im/element-android#1982]
**Describe the bug**
Markdown content is not rendering correctly on the Android version.

**To Reproduce**
1. Enable markdown formatting.
2. Send a markdown formatted message, e.g. 

> \```
> testing
> \```

3. Message does not appear correctly on Element for Android but does appear correctly on web/desktop.

**Expected behavior**
The testing block above should be rendered correctly,

**Screenshots**
Android:
![Android](https://user-images.githubusercontent.com/3619157/90925971-27d94d80-e3c0-11ea-991e-65e5795c32db.png)

Desktop:
![Desktop](https://user-images.githubusercontent.com/3619157/90926000-36c00000-e3c0-11ea-80b7-a824ae6444fc.png)

**Smartphone (please complete the following information):**
 - Device: Pixel 3A
 - OS: Android 11 Beta

**Additional context**
 - v1.0.4 from F-Droid
 - Homeserver: munster.dev

I submitted a rageshake shortly before starting this issue.

**Comment by MexHigh** [comment]
Me and a friend of mine are currently working on it. Should be fixed by tomorrow.

**Comment by bmarty** [comment]
I reopen the issue, we will close it once when we can confirm that we do not reproduce it

**Comment by kittykat** [comment]
I'm going to close this issue as there don't appear to have been any new occurrences in over a year.
