### ISSUE TITLE
PIN Code Improvements

### ISSUE THREAD

**Issue by TR-SLimey** [vector-im/element-android#1985]
**Is your feature request related to a problem? Please describe.**

I have noticed that the PIN code system has some frustrating flaws. 

- First of all, it only allows exactly 4 characters, which is just begging for years of births to be used. I think the length should be virtually unlimited for greater security.
- Biometrics seem to be enabled by default if they are available which may not be desirable. For example, if someone has access to your phone via biometrics but you want to keep Element private even from them. I believe there should be a separate option to enable each type of biometric auth.
- The time before Element locks is not configurable. For example, to lock Element instantly, I have to clear it from the open apps menu, otherwise it locks automatically after an unknown (to me) amount of time. I think that should also be configurable with the option to lock as soon as the user leaves the app, after the device locks, or after a certain amount of not using the app.
- In order to include all the above options, I believe PIN should have it's own submenu within Settings > Security & Privacy

**Describe the solution you'd like**

See above

**Describe alternatives you've considered**

None

**Additional context**

None

**Comment by bmarty** [comment]
Yes, those are all good ideas.
The grace period is 2 minutes IIRC.

**Comment by bmarty** [comment]
So we will add a dedicated setting screen to handle:
- Activate or deactivate the feature (= the current setting)
- Disabling possibility to use Biometrics
- Enable or disable the grace period. On this point, without grace period, I think we could have trouble when switching between Element Activities. So "No grace period" will probably be a 2 seconds of grace period to avoid that.

Also opening the External camera for instance without grace period may lead to the possibility to re-enter pin code when the photo is taken. This use case should be correctly tested.

We won't change the size of PIN code (4) it seems a bit complicated with the lib we use to have a random number of digits. It's up to the user to choose a robust PIN code, and after 3 wrong code, the session will be logged out.

**Comment by TR-SLimey** [comment]
Alright. That's great to hear! :D

**Comment by TR-SLimey** [comment]
Oops, didn't mean to close that. I'll re-open so you can close when ready
