### ISSUE TITLE
Clarify which information should not be shared (settings)

### ISSUE THREAD

**Issue by TR-SLimey** [vector-im/element-android#1986]
**Is your feature request related to a problem? Please describe.**

In `Settings` > `Security & Privacy`, there are a few boxes which seem to display something which should be kept private, but there is no indication of that. Those things are `Session Key` and `Cross Signing > *`.  

**Describe the solution you'd like**

Assuming that those boxes indeed contain private information, their value should probably be "Click to reveal" instead, and upon clicking, they should show an alert telling the user that this information is private and should not be shared, with options to reveal the value (and copy it to clipboard) or to cancel.

**Describe alternatives you've considered**

None

**Additional context**

The suggestion is based on Element Web's `Access Token` box with the addition of an alert warning the user. Speaking of which, the option to view the token should probably be added to Element Android, and follow the above.

**Comment by TR-SLimey** [comment]
> Hello, those information are public (public keys).
> They are published, no need to keep them secret

Thanks for the reply. I'm glad to hear that. What about my last question though? Can we also add an "Access Token" field for consistency with Element Web/Desktop or should that go in a separate issue?

**Comment by correabuscar** [comment]
> > Hello, those information are public (public keys).
> > They are published, no need to keep them secret
> 
> Thanks for the reply. I'm glad to hear that. What about my last question though? Can we also add an "Access Token" field for consistency with Element Web/Desktop or should that go in a separate issue?

on Element on android, in `Settings` -> `Advanced settings` then at the very bottom is `Access Token` with its description `Your access token gives full access to your account. Do not share it with anyone.`
But what happens if you tap it? it gets `Copied to clipboard` (toast) which is rather unexpected to happen for a tap on it, so then any apps monitoring clipboard in the background, could've snatched it, sent to back to their hq, even if they don't know what it is.

<details>

> Whether other apps can be notified and access the clipboard contents depends on the operating system and specific app behavior:

>Android:

>    Prior to Android 10: Apps could freely access the clipboard content, even in the background. This raised privacy concerns.
>    Android 10 and above: Only the following apps can access the clipboard:
>        The app currently in focus: This is the app you're actively using when copying something.
>        The input method editor (IME): This is the keyboard app you use for typing.
>    Android 12 and above (optional): Users can enable a feature that notifies them whenever an app accesses the clipboard.

( I can't find it on my xiaomi android 13 - and 
> "The feature to enable clipboard access notification is not currently available on Xiaomi devices running Android 13.0.4."

)

>iOS:

>    Before iOS 14: Apps could access the clipboard content while they were in the foreground.
>    iOS 14 and above: Apps can still access the clipboard content, but:
>        They can only do so while they are in the foreground.
>        New in iOS 15: Users can enable a feature that shows a notification whenever an app accesses the clipboard.

from Gemini (LLM)

</details>
