### ISSUE TITLE
12 hour time not being detected correctly

### ISSUE THREAD

**Issue by 132ikl** [vector-im/element-android#1998]
**Describe the bug**
Whether to use 24 or 12 hour time should be detected automatically. However when the system is set to 12 hour, Element still shows 24 hour time.

**To Reproduce**
1. Enable 12 hour time
2. All times in Element will be in 24 hour time

**Expected behavior**
Times are shown in 12 hour time when 12 hour time is enabled and 24 hour time when 24 hour time is enabled

**Screenshots**
![](https://fs.ikl.sh/selif/qn3khenc.jpg)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy J3 V (SM-J337V) 
 - OS: Android 9

**Additional context**
 - App version and store: 1.0.4, Play Store
 - Homeserver: is.nota.live

**Comment by ganfra** [comment]
So should be ok now. Please reopen if it's not good on your device.
