### ISSUE TITLE
Allow running Jitsi in the background

### ISSUE THREAD

**Issue by mrjohnson22** [vector-im/element-android#2011]
**Is your feature request related to a problem? Please describe.**
After joining a Jitsi call, there seems to be no (stable) way to view any other page/activity of the app without dropping from the call.

Some situations where this is frustrating include:
* Wanting to view messages sent in the room that the Jitsi call was joined from. (The text chat in Jitsi rooms is not a viable substitute, as its history is independent from Matrix rooms.)
* Getting a notification for a message sent in another room, and tapping the notification to view it. This actually does allow the call to continue running in the background, but then there is no way of stopping the call other than force-killing the app.

**Describe the solution you'd like**
After joining a call, pressing Back (or doing anything that would view another page/activity) should keep the call active, with a persistent notification / in-app "bar" for returning to / dropping from the call. This is the behaviour for 1:1 VoIP calls.

**Describe alternatives you've considered**
A workaround is for users to simply choose to join a call from the standalone Jitsi app, which has robust options for running in the background.

Unfortunately, doing this can be difficult in practice. Element Android's embedded Jitsi seems to hide all means of copying/sharing the URL of a call, so if a call is prepared by Scalar (which creates a long, non-memorizable string for the call URL), the only way to find the URL is to use Element Web, which uses the "regular" Jitsi Meet web interface that exposes the URL.

What would also be nice is if Element Android could detect if the Jitsi app is installed, and offer to join a call using that app instead, since it already handles background calls perfectly well.

**Additional context**
This issue was present in the old Riot Android app too, so maybe these issues stem from the Jitsi Meet SDK.

* https://github.com/vector-im/riot-android/issues/3303
* https://github.com/vector-im/riot-android/issues/3304
* https://github.com/vector-im/riot-android/issues/3433

**Comment by chagai95** [comment]
Is this still an issue?

**Comment by mrjohnson22** [comment]
This does seem to be fixed since https://github.com/vector-im/element-android/pull/2908. I tried a multitude of different ways to reproduce the issue, but was foiled at every turn :)
