### ISSUE TITLE
Use twemoji for verification emoji

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-android#2023]
Let's include graphics for the 64 emoji we use for verification so that visually they are consistent cross-platform for verification and avoid confusion with what "compare the emoji" means.

See also https://github.com/vector-im/element-ios/issues/3589

**Comment by ara4n** [comment]
See also https://twitter.com/helveticade/status/1299690550719918081

**Comment by bmarty** [comment]
We already include graphics to avoid this. We will double check.

**Comment by BillCarsonFr** [comment]
I check and we are using the same. 

<img width="1027" alt="image" src="https://user-images.githubusercontent.com/9841565/93177139-a2348d80-f732-11ea-8f94-e2261017b831.png">
