### ISSUE TITLE
passwordless login with phone nr to mobile apps

### ISSUE THREAD

**Issue by Rik44444** [vector-im/element-android#2026]
Hi,
I love Matrix, esp the focus on bridges. I would like to start recommending it to friends and family, but the Element app is really only acceptable to them if it is possible to register and login automatically with their phone number, without a password, and with sms id confirmation. So like with WhatsApp and Signal. This is a feature request to make this possible on Matrix as well, perhaps add it as an option in the login screen. I think it should be feasible (but I'm no expert), to assign randomly generated new user names and passwords to new phone numbers, and allow users to register and login without ever having to see either, so that they can just login with their phone number.

see also here: matrix-org/synapse#8099 and here https://github.com/matrix-org/matrix-doc/issues/2740

**Comment by bmarty** [comment]
See my comment in https://github.com/matrix-org/matrix-doc/issues/2740

**Comment by Rik44444** [comment]
Hi, i'd like to re-open this thread, after consulting with the devs on the Matrix documentation Github project. Please see the discussion there for what they think are the changes that are needed to make this feature of logging in with your phone nr, like possible with Signal, Telegram and Whatsapp, possible. https://github.com/matrix-org/matrix-doc/issues/2740 
Most important quotes from there:
"The spec supports this sort of approach through guest accounts, user-interactive auth, and some clientside trickery."
and
"m.login.password with a 3pid type to identify the user?"
and 
"Oh; you're right. I now remember that's even how something similar used to work in the early days of Matrix. Agree that a combination of guest accounts, UIA and arranging the process on the client-side should do the job - not sure any server-side changes are even necessary."
and
"it mostly needs changes on the client side (in Element), and (probably but not necessarily) on the server side (in Synapse). Sorry for pushing you around so many times. I think your original ticket (vector-im/element-android#2026) is actually the right place for that"

**Comment by Rik44444** [comment]
ps I cannot seem to find the option to re-open this issue, i think that's only something the admins can do, correct?
