### ISSUE TITLE
Login with mxid | Autodiscovery fails if identity server is invalid and Homeserver ok

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/element-android#2027]
If the well-known/client contains a valid HomeServer but an invalid Identity server the app won't let you login
<img width="348" alt="image" src="https://user-images.githubusercontent.com/9841565/91707240-cebba780-eb7f-11ea-99dd-554eca5e004f.png">

for privacy tools config
````
{
    "m.homeserver": {
        "base_url": "https://chat.privacytools.io"
    },
    "m.identity_server": {
        "base_url": "https://chat.privacytools.io"
    }
}
````

As per spec, if m.identity_server is present it should be valid.
But it looks like web as relaxed that rule:
https://github.com/matrix-org/matrix-js-sdk/pull/1062

see https://github.com/vector-im/element-web/issues/11508
see https://github.com/vector-im/element-web/issues/11102

**Comment by bmarty** [comment]
I do not like to not follow specs with the reason the Element Web does not follow them

**Comment by bmarty** [comment]
But https://github.com/matrix-org/matrix-doc/pull/2284 is merge now so I think this is OK. Will review it
