### ISSUE TITLE
Contact renaming

### ISSUE THREAD

**Issue by totikom** [vector-im/element-android#2031]
# The Problem
In messengers based on phone numbers like Telegram, Signal, WhatsApp users can assign names to their contacts. It allows to use easy and understandable aliases (like "Mom" instead of the full name of your mother).
More over, Matrix promotes itself as a _secure_ way of communication, and therefore using random strings as nicknames can be common (as a countermeasure against OSINT). It is hard to remember, which of random strings is your friend's nick, but it will become trivial, if you can locally change his/her nickname to real name or smth else memorable.

# Proposed solution
Add a way to locally (only in one session) assign names to your contacts.

# Alternative solutions
This information _can_ be synced across different sessions, but it will require additions to the Matrix Protocol, which sounds like an overkill.

**Comment by witchent** [comment]
This is at least related (if not a duplicate) of https://github.com/vector-im/element-android/issues/1908.

Also the spec change would probably be this one https://github.com/matrix-org/matrix-doc/issues/690.

**Comment by totikom** [comment]
Yes, #1908 sounds quite close.
I think my issue can be closed.

**Comment by witchent** [comment]
You can do this yourself so the devs don't need to spend time doing it :)
