### ISSUE TITLE
When sharing an image from external app, element prompts for storage permission

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/element-android#2048]
Open photo app, choose select then element:
<img width="339" alt="image" src="https://user-images.githubusercontent.com/9841565/92011956-1727c080-ed4c-11ea-926c-816aaa9c023c.png">

**Comment by dznsm** [comment]
Appears to be the same for other files shared to element from other apps.
Also, maybe should be another issue, but possibly could be related, using the + button next to text input box in an element room, then files or gallery asks for storage permission and does nothing if denied (Android 10 AOSP)
