### ISSUE TITLE
change audio device during the calling phase

### ISSUE THREAD

**Issue by 532910** [vector-im/element-android#2050]
Please add support to swtich between audio devices ( earpiece, loudspeaker, headset) during the calling phase.

![Screenshot_20200902-222547_Element_(Riot im)](https://user-images.githubusercontent.com/14617699/92027747-a6909c00-ed6b-11ea-9548-d552d8845bd1.png)
'

**Comment by kittykat** [comment]
I'm going to close this issue for now as the issue has been resolved (testing on v1.3.8)
