### ISSUE TITLE
Request: Move shields to the left side of room icons

### ISSUE THREAD

**Issue by ShadowJonathan** [vector-im/element-android#2051]
**Is your feature request related to a problem? Please describe.**
Partly due to a confusion in design language, and partly to prepare for the upcoming #70 issue (presence management), I think the current position of the encryption shield on the right sides of avatars could be conflicting with common design language of the "online/offline indicator" in the rest of the industry, and even within element itself (see Element Web)

**Describe the solution you'd like**
Move the encryption shield to the left side of avatar/room icons, this is a "new spot" to put design elements in, it explicitly disassociates itself then with the "user status indicator" used in other applications, subtly signalling it's not a user status indicator, but something else just as important.

**Describe alternatives you've considered**
I previously considered removing the shield entirely in room lists (in anticipation of #70, to put the user presence indicator there), but I saw that moving it was a better alternative.

**Additional context**
I think clarifying the design language of the app in a way that doesn't conflict with other apps of its type (discord, telegram, itself (web), etc.) would be beneficial to better adoption and recognition of elements presented in the UI, such as the encryption shield representing the out-of-band user verification mechanism status, while 'excommunicating' it from user presence.

**Comment by Rares95** [comment]
Yes please!

Could we also add another shield to also show if some room has E2E encryption enabled?

**Comment by ShadowJonathan** [comment]
> Could we also add another shield to also show if some room has E2E encryption enabled?

I think the existence/non-existence of the shield badge in room lists/details already takes care of that

**Comment by Rares95** [comment]
> > Could we also add another shield to also show if some room has E2E encryption enabled?
> 
> I think the existence/non-existence of the shield badge in room lists/details already takes care of that

Ah right, found it. Nvm then

**Comment by ShadowJonathan** [comment]
Closed per review in #2060
