### ISSUE TITLE
Stickers in sticker picker aren't cached

### ISSUE THREAD

**Issue by Bubu** [vector-im/element-android#2066]
**Describe the bug**
The stickers (well, I guess images) displayed in the sticker picker aren't cached. Which leads to element android not shwoing any stickers on bad/missing internet connection. And I guess it's redownloading about 10MB of sticker data whenever I want to sent a sticker.

This is using https://github.com/maunium/stickerpicker as a stickerpicker

**To Reproduce**
1. Have https://github.com/maunium/stickerpicker as a stickerpicker
2. Open the stickerpicker, wait for all previews to be downloaded
3. close element android
4. open stickerpicker again and wait for everything to download again

**Expected behavior**
I expected that the stickerpicker widget itself and the sticker preview data is cached

**Smartphone (please complete the following information):**
 - Device: Nexus 5X
 - OS: Android 8.1

**Additional context**
 - App version 1.0.5-F-Droid
 - Homeserver: bubu1.eu

**Comment by Bubu** [comment]
Mmmh, maybe there is some caching. Stickers load faster *sometimes*. But they definitely don't load at all when you are offline.

**Comment by dkanada** [comment]
I can confirm there is zero caching. I found the code that disables all caching for widgets and removed it for my personal builds to make stickers viable. Hopefully I'll have a PR to fix that along with a few more sticker issues soon.

**Comment by kojid0** [comment]
> I can confirm there is zero caching. I found the code that disables all caching for widgets and removed it for my personal builds to make stickers viable. Hopefully I'll have a PR to fix that along with a few more sticker issues soon.

Thank you!

**Comment by bmarty** [comment]
Done in #2648 (Element Android 1.2.1)
