### ISSUE TITLE
proximity sensor must not be used with loudspeaker and video

### ISSUE THREAD

**Issue by 532910** [vector-im/element-android#2087]
please disable proximity sensor when loudspeaker is used or it's a video call

**Comment by bmarty** [comment]
With loudspeaker the proximity is disabled.
I can reproduce a small bug for video call, if I switch the audio to phone ear set, the proximity sensor is enabled. But is it really a bug, even for a video call?

**Comment by 532910** [comment]
The proximity sensor is always enabled for me (possibly due to #1685)
OP3T LineageOS 17.1 on Android 10, Element 1.0.6

**Comment by 532910** [comment]
it should distinguish when the phone is by the ear and
1. accidental closing proximity sensor with a hand for example
2. when the phone is face down

**Comment by DoM1niC** [comment]
is it normal I can't switch back to Ear Speakers and @532910 is right, I have the same problem like him :(

**Comment by bmarty** [comment]
@onurays could you double check please? Also please double check #1685 . Thanks!

**Comment by mweinelt** [comment]
Tested video call today with Element 1.0.11 on a Pixel 3a and the proximity sensor was enabled, which was a tad bit annoying.

**Comment by kittykat** [comment]
I'm going to close this issue for now as it's been fixed in 1.3.8
