### ISSUE TITLE
[BUG] Auto scrolling to the latest message

### ISSUE THREAD

**Issue by bahur142** [vector-im/element-android#2094]
Element Android did not scroll automatically to the latest message when you are the sender.

1. Go to Settings --> Preferences
2. Disable "Show removed messages"
3. Send some messages to someone.
4. Screen did not move to the latest message. Instead the button with the arrow appears to go to the latest message.
5. Enable "Show removed messages".
6. Everything is fine again, when you send messages.

App versions: 1.0.6 & 1.0.7
Homeserver: my own (v.1.19.1)
Devices: Android 6.0.1; Android 9.0

**Comment by scottwallacesh** [comment]
I also see this behaviour.

**Comment by bmarty** [comment]
Fixed by #2144
