### ISSUE TITLE
Font size settings option doesn't change the font size

### ISSUE THREAD

**Issue by sim6** [vector-im/element-android#2095]
Thanks for your work.

I'm using the f-droid version 1.0.5 [40100050] (F-19f9c94d)  and when I change the font size option from settings the font size doesn't change.

**Comment by DoM1niC** [comment]
I solve the Problem by Close the App fully and reopen it

**Comment by sim6** [comment]
With 1.0.6 [40100060] (F-0da106ba) it works. Thanks!

**Comment by sim6** [comment]
See also #1483
