### ISSUE TITLE
Some images are not shown.

### ISSUE THREAD

**Issue by 532910** [vector-im/element-android#2097]
Web:
![image](https://user-images.githubusercontent.com/14617699/93003876-07c62580-f54b-11ea-8b5e-5c6224f3a542.png)

Android:
![image](https://user-images.githubusercontent.com/14617699/93003909-304e1f80-f54b-11ea-9dac-2a5383098253.png)

Image (md5 `eca44c8be8b11a66127fe67dae9684c7`):
![image](https://user-images.githubusercontent.com/14617699/93003858-ea915700-f54a-11ea-93fe-8ef5880d08c7.png)

**Comment by 532910** [comment]
It's not transparent.

**Comment by becausewat** [comment]
I'm encountering this as well. The latest version that it works on is 1.0.5 on fdroid.

1.0.6 and later does not display some images when they are sent from the web client, but I can see them when they are sent from another device using the Android app.

**Comment by arthurlutz** [comment]
I'm having something similar on a new install of 1.0.6. Has anyone tried downgrading to fix this ?

**Comment by bmarty** [comment]
It should be fixed on 1.0.7, this is similar to #2121

**Comment by 532910** [comment]
Indeed, I confirm this is fixed in 1.0.7!
