### ISSUE TITLE
no audible ring from incoming call

### ISSUE THREAD

**Issue by laicon188** [vector-im/element-android#2100]
Hello.

No audible ring from incoming call
Element on android updated to the latest version.
Own synapse server version 1.13.0

Have anyone the same issue?

**Comment by lomion0815** [comment]
Element Android is not using the ringtone volume system setting but the media volume. Try to increase the media volume and verify this issue. If my observation is correct please update this ticket because I consider this to be a bug.

**Comment by BillCarsonFr** [comment]
Update

> I just found that Element Android is using the Media volume setting for ringing voice and video calls. I would expect the ringtone volume setting to be used ...

**Comment by bmarty** [comment]
Should be fixed by #2174

**Comment by bmarty** [comment]
(So in Element 1.0.10)
