### ISSUE TITLE
Various report of people that cannot play video

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/element-android#2107]
> I can play it under iOS as said above. My Android devices are connected to my homeserver.
So i can‘t test it here. But reproducable i have problems like other users with sending - playing - and replaying videos under 1.0.6
FDroid 1.0.5 is still ok

> And i created an unencrypted room and send the video a second time. Same here, iOS, Windows Linux all good,
Android struggles again with the file.
Thought the encryption could cause this behaviour , but seems not to be the root of the prob.
And what is more important: existing videofiles that have been send by elderly versions in the past, can‘t now be played any longer too.

![image](https://user-images.githubusercontent.com/9841565/93182657-40782180-f73a-11ea-838a-7bafbb9e389c.png)

**Comment by BillCarsonFr** [comment]
I have been able to reproduce when sending video from iphone.
Originally i thought it was a codec issue, but looks like the decrypted file is truncated (missing a fex kb)

**Comment by 532910** [comment]
I've created two screen records with org.lineageos.recorder. Both are playable in Element web, but only one in Element Android. The first one gives `Can't play this video`. Trying to clean all cache doesn't help. I can share this video personaly with Element team, but wouldn't like to make it public.
