### ISSUE TITLE
Search messages in a room - phase 1

### ISSUE THREAD

**Issue by onurays** [vector-im/element-android#2110]
### Description
This feature aims to provide a reliable way to search for messages in the clear (unencrypted) rooms. When the user enters a search term with at least 2 characters the result should be shown as a list or with an indicator if no result was found. The result list contains the whole message and sender name separated by date. Clicking one of the search results should navigate to the timeline that contains the message and navigation back to the search screen should be possible.

For clear rooms, the search should be done through the search API. Searching in encrypted rooms will be supported in the next phases.

### [Search API](https://matrix.org/docs/spec/client_server/latest#module-search)
Path: `/_matrix/client/r0/search`
Method: `POST`
Requires auth: yes

**Request:**
```
{
    "search_categories": {
        "room_events": {
            "search_term": "bug",
            "filter": {
                "limit": 10,
                "rooms": [
                    "!SoEEvuKACYFCbTgBmy:matrix.org"
                ]
            },
            "order_by": "recent",
            "event_context": {
                "before_limit":1,
                "after_limit":1,
                "include_profile":true
            }
        }
    }
}
```

**Response:**
```
{
    "search_categories": {
        "room_events": {
            "results": [
                {
                    "rank": 0.1,
                    "result": {
                        "content": {
                            "body": "Is it a bug or feature?",
                            "msgtype": "m.text"
                        },
                        "event_id": "$1599563884108596qwer:matrix.org",
                        "origin_server_ts": 1599563884260,
                        "room_id": "!GOBljmIYwQ:matrix.org",
                        "sender": "@onurays:matrix.org",
                        "type": "m.room.message",
                        "unsigned": {
                            "age": 604850010
                        },
                        "user_id": "@onurays:matrix.org",
                        "age": 604850010
                    }
                }
            ],
            "count": 201,
            "highlights": [
                "bugs",
                "bug"
            ],
            "next_batch": "YWxsCgoxNTU3Mxxxk0Mjk3MzA4MA"
        }
    }
}
```

**We should paginate the search results if the previous response contains `next_batch` parameter:**
https://matrix-client.matrix.org/_matrix/client/r0/search?next_batch=YWxsCgoxNTU3Mxxxk0Mjk3MzA4MA

### Checklist

- [x] **Add search action as the menu item inside the timeline**

![Screen Shot 2020-09-15 at 12 48 59](https://user-images.githubusercontent.com/1254401/93195357-d5d2e000-f751-11ea-9785-dae0b34cb166.png)

- [x] **Show search screen when the search action is clicked in a clear room**

- [x] **Show a dialog that indicates the search feature will be available later for encrypted rooms**

![Screen Shot 2020-09-15 at 12 53 35](https://user-images.githubusercontent.com/1254401/93195953-7aedb880-f752-11ea-9068-e02ebf4fc881.png)

- [x] **Search should be triggered by the search button on the keyboard**

- [x] **Implement the search API for clear rooms according to the document: https://matrix.org/docs/spec/client_server/latest#module-search**

- [x] **Show the no message found indicator if no result found**
 
![Screen Shot 2020-09-15 at 13 05 28](https://user-images.githubusercontent.com/1254401/93197314-24817980-f754-11ea-9742-c52fe21c6a7d.png)

- [x] **Map the API response to a domain object and serve from both session and room**

- [x] **Separate results by date**

![Screen Shot 2020-09-15 at 13 11 20](https://user-images.githubusercontent.com/1254401/93197927-f51f3c80-f754-11ea-971b-4d345c3d4d51.png)

- [x] **Automatically scroll to the end of the list. If the user scrolls to the top and the previous response contains `next_batch` field, make another request with this information. (See Search API section)**

- [x] **Clicking on a result should navigate to the timeline positioned at the message. Pagination should be available in both way**

- [x] **Make sure that clicking back from the timeline is returning back to the search screen which preserves the previous search term and the result list**

## Limitation for phase 1

- [x] Only search for messages, and not for files, so not tab for the moment (blocked by https://github.com/matrix-org/synapse/issues/1851)
- [x] Only search in public rooms. We will handled encrypted room later, either by searching in the cache (not ideal), or by using [seshat](https://github.com/matrix-org/seshat). for the moment, display a dialog if user want to search in a e2e rooms.

**Comment by 4ley** [comment]
Is this feature already implemented? From the chat room context menu (burger bar) I see "Settings, Invite Add Matrix apps" only. No Search option. I run version 1.5.30

**Comment by lindhe** [comment]
@4ley It exists for non-encrypted rooms only. The option is not there for encrypted rooms.

**Comment by lindhe** [comment]
I'm on 1.5.30 from Google Play, and I have the feature. You sure you don't? This was merged years ago.

**Comment by 4ley** [comment]
I have the same version. You said non-encrypted rooms only. I tested only encrypted rooms.

**Comment by lindhe** [comment]
Search  in e2e rooms is a requested feature, not sure it's about to happen anytime soon though. :/

#2208
