### ISSUE TITLE
Calling is possible even if power level is not sufficient

### ISSUE THREAD

**Issue by enzingerm** [vector-im/element-android#2112]
**Describe the bug**
In a (modified) direct chat, a member who doesn't have the power level to be able to send `m.call.invite` events, is still able to start a call. In encrypted rooms, the callee's devices even start to ring.
**To Reproduce**
1. Lower the power level for member `A` in a direct chat to `n (< 100)`
2. Set `content['events']['m.call.invite'] = n + 1` in the state event `m.room.power_levels`.
3. Try to start a call from `A`'s device.
4. In encrypted rooms, `B`'s devices start ringing, in unencrypted rooms, I assume the event gets denied by the server, but still, Element Android shows the calling screen.

**Expected behavior**
The buttons for audio and video calls should be disabled as soon as the power level is not anymore sufficient to start calls. Also, incoming calls from users not allowed to start them, should be swallowed.

**Additional context**
 - App version 1.0.6 from Google Play
 - Homeserver: Synapse 1.18

**Comment by bmarty** [comment]
Ok, thanks for reporting. This is not handled yet. The recipe is a bit hacky (who will make it?) but conform to what we can do at the spec level.

**Comment by TR-SLimey** [comment]
Just for clarity, the client on the receiving end should be responsible for dropping a call which is not allowed to be made by room permissions to prevent users from bypassing this room permission using a modified client. However, the sending client can still grey out the buttons for clarity and convenience.

**Comment by bmarty** [comment]
Yes, that makes sense, but let me ask what is the point to prevent someone you share a room with to call you?

**Comment by enzingerm** [comment]
The main use case in my opinion is Matrix being used in kind of a "non symmetrical" relationship where for example a teacher wants to give his students the possibility to contact him but only in form of text messages, or a custodian offering his clients a "restricted" communication channel.

**Comment by TR-SLimey** [comment]
Or just to prevent people from constantly calling and bothering others by making group calls in large groups.

**Comment by bmarty** [comment]
Group call (so call in a room with more than 2 members) are not managed using WebRTC (and so does not send m.call.invite), but using Jitsi widget.

But I get the point of asymmetrical relation.

**Comment by TR-SLimey** [comment]
I know Jitsi was used, but an event is still sent to indicate the start of a group call, right? Is it just the fact that it's a different event then?

**Comment by bmarty** [comment]
No, no event are sent when starting a group call, just the widget added event. We have in mind to improve that.

**Comment by TR-SLimey** [comment]
Right, I see. Thanks!

**Comment by bmarty** [comment]
Fixed by #2139 , thanks @enzingerm !

> Just for clarity, the client on the receiving end should be responsible for dropping a call which is not allowed to be made by room permissions to prevent users from bypassing this room permission using a modified client. However, the sending client can still grey out the buttons for clarity and convenience.

@TR-SLimey Feel free to open a dedicated issue to manage this case ^^
