### ISSUE TITLE
Support authed Jitsi widgets

### ISSUE THREAD

**Issue by jaywink** [vector-im/element-android#2116]
Authed Jitsi widgets were introduced to Element Web [here](https://github.com/vector-im/element-web/pull/15114). For more details see https://github.com/matrix-org/prosody-mod-auth-matrix-user-verification

Requires #2115

**Comment by mm28ajos** [comment]
Would love to see that feature.

**Comment by amelentjev** [comment]
It was done here : #https://github.com/vector-im/element-android/pull/3383
