### ISSUE TITLE
element android does not playback videofiles in chatrooms since update to 1.0.6

### ISSUE THREAD

**Issue by chrissi55** [vector-im/element-android#2121]
Updated from 1.0.5 element android to version 1.0.6
Have an own homeserver under matrix-synapse (ubuntu-server) 1.19.2

clients with element iOS 1.0.10  and desktop clients with element (windows, linux) 1.7.7 can take videos, send videos and playback videos on my homeserver.

Have a second test account on matrix.org to test federation effects and different behaviour between reference server matrix.org and my own homeserver.yaml.

I am not able to play videos from element nor can i download them and play them as offline file by e.g. VLC Player.

![Screenshot_20200914-212755](https://user-images.githubusercontent.com/22561479/93458947-48be9100-f8e1-11ea-8d62-7f5a7197af12.png)

![Screenshot_20200914-215017_1](https://user-images.githubusercontent.com/22561479/93458991-5aa03400-f8e1-11ea-8013-e40c96a6ceb8.png)

There are other users who confirmed that behaviour in matrix chat for element android.

With a 1.0.5 android version playback is possible. In the meantime my only tablet client with FDroid version got the latest update too to 1.0.6. Now he is no longer able to play videos sended by element either.

The video files were taken by my users and we tested with mp4 youtube files too. All the same failure

**Comment by bmarty** [comment]
Yes, thanks, this is fixed in Element 1.0.7. You will have to do a clear cache ( in the application to fix the problem once you get Element 1.0.7

**Comment by BillCarsonFr** [comment]
A 'clear media cache' should be enough

**Comment by unclechu** [comment]
Maybe it relates to #1785.
