### ISSUE TITLE
Stuck in loading stage after Pin set up

### ISSUE THREAD

**Issue by ralaud** [vector-im/element-android#2136]
**Describe the bug**
Hi, I did set up Pin (for the App), after that I did restart Element and when I type in the Pin, it is loading and looking like it stuck there. I also did restart my smartphone and got the same behavior. When I was writing this issue, I did go back and Element Chat was opening. Then I tried second time and now I am waiting more than 10 minutes, it is loading and not opening the chat, so it is stuck at loading stage. 

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Security & Privacy'
3. Activate Pin
4. Restart Element and type in Pin
5. Loading and stuck in loading stage

**Expected behavior**
Accept Pin and open Element chat 😊

**Screenshots**
Added one to my rageshake

**Smartphone:**
 - Device: [Xiaomi Redmi Note 5 Pro] 
 - OS: [Android 10] 

**Additional context**
 - App version and store [1.0.6 - F-Droid]
 - Homeserver: [matrix.org]

I had to select 'I forgot my (four-digit) Pin' 😁 and login again to fix it. I tried again and could reproduce the same behavior. I did send a rageshake today.

With best regards!

**Comment by bmarty** [comment]
Yes, thanks, it's fixed in Element Android 1.0.7
