### ISSUE TITLE
direct conversation error

### ISSUE THREAD

**Issue by ramtinsafadoust** [vector-im/element-android#2142]
my server address is :
matrix.farmehr.com

when i download app from google play there is no problem

but when i clone android project there is problem

client cant start direct conversation and screen go white

and in android studio debugger can see nginx 404 error

if my server has problem => why google play version is ok

if server is ok  => why this error happen 

and if my server has problem => why i can start direct chat by google play version with clone version

im so tired and confuse 

any body can help me

i have no problem if you want my server login user and password

but just please try to solve my issue

**Comment by BillCarsonFr** [comment]
Hello @ramtinsafadoust 
Are you running the develop branch?
If so it may be unstable, the released version is based on master.
