### ISSUE TITLE
Sound device selection overlaps hangup button

### ISSUE THREAD

**Issue by 532910** [vector-im/element-android#2148]
It's imposible just end the call after switching sound device:
![image](https://user-images.githubusercontent.com/14617699/93814073-b7db1300-fc5c-11ea-93f7-75cb9d66d814.png)

**Comment by bmarty** [comment]
You have to close the bottomsheet by clicking on the screen. But yes, maybe it should closed by itself when selecting an audio device.

**Comment by 532910** [comment]
> You have to close the bottomsheet by clicking on the screen

This is a one more action, that costs

> But yes, maybe it should closed by itself when selecting an audio device.

Yep, see native android dialer for example.

**Comment by kittykat** [comment]
I'm going to close this issue for now as it's been fixed in 1.3.8 :+1:
