### ISSUE TITLE
`Sign in with Matrix ID` does not work for custom homeserver

### ISSUE THREAD

**Issue by a000a** [vector-im/element-android#2149]
When entering `Sign in with Matrix ID` (under ` Select a server`), it is shown:
`Unable to find a valid homeserver. Please check your identifier`.
In my case the homeserver is different from the id (both have a subdomain).

When selecting `Other` (login_server_other_title) it works fine with both subdomains

**Comment by bmarty** [comment]
Your well-known file should be correctly located at the same domain than the one used in the userId. Please check again https://matrix.org/docs/spec/client_server/r0.6.1#server-discovery

**Comment by a000a** [comment]
It worked!
Thank you.
