### ISSUE TITLE
 Don't set presence when handling a push notification or polling

### ISSUE THREAD

**Issue by jcgruenhage** [vector-im/element-android#2156]
**Describe the bug**
Element is setting the client as online on each notification when using GCM, or always when polling in the F-Droid flavour. This sort of defeats the purpose of the presence feature.

**To Reproduce**
1. Have Element Android on one account, close the app.
2. Send them a message from some client
3. See them coming online immediately, without opening the app.

**Expected behavior**
1. Have Element Android on one account, close the app.
2. Send them a message from some client
3. See them coming online only when they actually open the app

In the case of the F-Droid flavour, as long as the app is syncing in the background, the account is just never, ever displayed as offline.

**Additional context**
The solution is to use the `set_presence` parameter on the `/sync` request *unless* the app is open.

**Comment by violoncelloCH** [comment]
related to #70 and #1521

**Comment by bmarty** [comment]
Yes, presence is still not implemented. I'm thinking about working on it :)

**Comment by jcgruenhage** [comment]
There's two parts to presence here: Showing presence of others, as well as actively setting presence to online when using the app. That'dbe a feature request. The other part, setting presence to online du to sync request when the app is not open is a bug IMO, and should have a higher priority than presence as a feature.

Very nice to hear that you intend to implement presence as a feature too though
