### ISSUE TITLE
Endless loading screen for self hosted Jitsi

### ISSUE THREAD

**Issue by faaaaabi** [vector-im/element-android#2168]
**Describe the bug**
I've integrated a self hosted Jitsi aession into a room, via a self hosted dimension integration server. On element Web the Integration works flawlessly, on Element Android a never ending loading screen is all I get 

**To Reproduce**
1. Setup a dimension Integration Server
2. Setup a Jitsi Server
3. Configure Element web to use this self hosted integration server. 
4. Add a self hosted Jitsi session to a room via Element Web via the self hosted integration server.
5. Try to enter the Jitsi session in Element Android Voice/Video

**Expected behavior**
Element should open the jitsi session in the jitsi app installed on my android device

**Screenshots**

![Screenshot_20200925-091300](https://user-images.githubusercontent.com/12394037/94238846-36f87180-ff11-11ea-8be8-09b9493428c1.jpg)

**Smartphone (please complete the following information):**
 - Device: One+ 8 pro
 - OS: Android 10

**Additional context**
 - App version and store: Play store 1.0.7
 - Homeserver:  synapse:v1.17.0-py3

**Comment by marcquark** [comment]
@faaaaabi Could you try this out again and report whether the problem persists?
I'm hosting my own Matrix and Jitsi server using the wonderful https://github.com/spantaleev/matrix-docker-ansible-deploy

I have my own account and two test dummies. Both Test dummies are connected via Element Web (also self-hosted). My own account is connecting via Android (Samsung Galaxy, Android 11, Element 1.0.17 from F-Droid). All 3 accounts are joined into a testing room. No matter from where i initiate a call, all participants can join the call using my self-hosted Jitsi server. No issues on Android here. It also works using Schildichat (version 1.0.14.SC27 F-Droid).

**Comment by marcquark** [comment]
Could it be an app permissions problem?

**Comment by faaaaabi** [comment]
This issue actually no longer exists for me. Thanks for remembering me of this stale issue :)
