### ISSUE TITLE
[Discoverability] Settings are hard to find 

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/element-android#2171]
After several support sessions with users, we can safely say that the application settings are hard to find.

- Some user do not find the left drawer (as the usual hamburger icon is replaced by the user icon in element)
- After that the settings icon is a small gear icon
- /!\ Some users even think that there is no logout option ( as its deep down left drawer > gear > General > scroll to bottom), found in review in playstore

<img width="306" alt="image" src="https://user-images.githubusercontent.com/9841565/94272609-8d7ea380-ff43-11ea-8f6e-60ae229acfec.png">
<img width="302" alt="image" src="https://user-images.githubusercontent.com/9841565/94272627-92dbee00-ff43-11ea-8dfe-243ce43e8d22.png">

**Comment by bmarty** [comment]
We will implement 

<img width="376" alt="image" src="https://user-images.githubusercontent.com/3940906/94971478-660d7500-0507-11eb-9009-c321463705ee.png">

https://www.figma.com/file/JhtklNBnHNz45QWmFh1aKh/Make-user-settings-more-discoverable?node-id=2%3A539 (
