### ISSUE TITLE
Unable to create Direct Message on a server which didn't implement /.well-known/matrix/client

### ISSUE THREAD

**Issue by samueljohnson** [vector-im/element-android#2173]
**Describe the bug**
On version 1.0.7 of the Android client, creation of new Direct Message fails on server which didn't implement /.well-known/matrix/client. Except for 404 on the well-known, no other error appears in access.log.

**To Reproduce**
1. Install version 1.0.7 of Android client
2. GET on /.well-known/matrix/client returns 404
3. Create a new DM
4. DM creation fails

**Expected behavior**
New DM creation succeeds

**Smartphone (please complete the following information):**
 - Device: Reproducible on multiple Android devices [e.g. LG V30]
 - OS: Android 9

**Additional context**
 - App version and store [e.g. 1.0.7 - Google Play Store]
 - Homeserver: custom homeserver

Adding support for /.well-known/matrix/client in webserver instantly resolved the issue.

**Comment by bmarty** [comment]
Thanks for reporting. This should be fixed in 1.0.8, which will be available on the PlayStore in the coming hours.
Please re-open it if it's not the case
