### ISSUE TITLE
I cannot find Config file like for element web

### ISSUE THREAD

**Issue by xavierle** [vector-im/element-android#2179]
while studying the android project structure
I was looking for the equivalent file to  Config.md for element web.
( i know better element web code)

to understand the structure of the android project
where are those parameters for element-web located in element-android ?

are there located in different places or a different filename ?

will there be a general config file for android also ?

**Comment by bmarty** [comment]
You can look at https://github.com/vector-im/element-android/blob/develop/vector/src/main/res/values/config.xml

**Comment by xavierle** [comment]
thank you for the hint. i will keep studying the project to see if i can help
