### ISSUE TITLE
Can't create room and verify users

### ISSUE THREAD

**Issue by laicon188** [vector-im/element-android#2185]
Hello.

Have problems with version 1.0.7. (latest)
1. When create room with someone application immediatly close. But on iPhone I can do this.
2. When try to verify user in chat another user don't receive verify question. But it's working on iPhone.

Own homeserver version "1.19.1"

**Comment by bmarty** [comment]
Yes, thanks for reporting. Broken verification is a known bug, fixed in the latest version 1.0.8 which is now available on the PlayStore.

**Comment by laicon188** [comment]
Yes, updated in the morning.
Now all working. 
Thanks
