### ISSUE TITLE
"No known servers" when joining rooms via federation

### ISSUE THREAD

**Issue by ajayyy** [vector-im/element-android#2194]
When trying to join a room with an address, such as #gitter:matrix.org, it fails with the error "No known servers".

Joining rooms from the discovery list on other instances also fails.

![image](https://user-images.githubusercontent.com/12688112/94759076-f3689200-036c-11eb-93cc-6c525a3259ba.png)

**Smartphone (please complete the following information):**
 - Device: OnePlus 7t
 - OS: Android 10

**Additional context**
 - App version and store 1.0.8 - Google Play
 - Homeserver: self-hosted

Related: https://github.com/vector-im/element-android/issues/808

**Comment by bmarty** [comment]
Fixed by #2526
