### ISSUE TITLE
Sending messages is slow

### ISSUE THREAD

**Issue by mawalu** [vector-im/element-android#2197]
**Describe the bug**
Sending messages sometimes takes ten seconds or more.

**To Reproduce**
1. Send a message
2. Wait for the message to be send

**Expected behavior**
Sending messages should feel snappy like in other messengers.

**Screenshots**
I recoded a [video](https://martinwagner.co/stuff/ScreenRecord-2020-10-01-12-07-38.mp4)

**Smartphone (please complete the following information):**
 - Device: Oneplus One
 - OS: Lineage OS 16 with microg

**Additional context**
 - App version and store 1.0.8 Fdroid
 - Homeserver: matrix.mawalabs.de

I had htop open on my server while sending and synapse did not take up an unusual amount or resources.

**Comment by bmarty** [comment]
Yes, we are working to improve that. Thanks for opening the ticket

**Comment by cloudrac3r** [comment]
I found that the more you use the app it gradually gets more and more slow. You can make it fast again by going into settings, general, and clicking clear cache.

**Comment by cloudrac3r** [comment]
Related: #1057, and the comments on #1476

**Comment by Mannshoch** [comment]
Since I Installed Element I never was able to send a Message.
I'm Only able to read Messages. I had to change the Messanger.
I do not have got any error messages.

**Comment by github-tomster** [comment]
@mannshoch
maybe: https://github.com/vector-im/element-android/issues/1798

**Comment by TheFrenchGhosty** [comment]
I also had this problem with messages taking 15-30 seconds to send when it's instantaneous on desktop.



> I found that the more you use the app it gradually gets more and more slow. You can make it fast again by going into settings, general, and clicking clear cache.

Doing this indeed solved the problem... but for how long.

**Comment by bmarty** [comment]
This is now far better if you install the version 1.0.10.

**Comment by cloudrac3r** [comment]
Thanks! Looks like SchildiChat, the fork I use, has updated to use 1.0.10 as a base. If I have any more problems I'll report back here, otherwise, please assume everything is good!

**Comment by EchedeyLR** [comment]
@cloudrac3r 
> I found that the more you use the app it gradually gets more and more slow. You can make it fast again by going into settings, general, and clicking clear cache.

This doesn't work for me as well as https://github.com/vector-im/element-android/issues/1476#issuecomment-646923269. It doesn't improve in any sense the performance again.

**Comment by EchedeyLR** [comment]
@bmarty I am an user of 1.0.10 version in Android 7.1.2 over armeabi-v7a.

**Comment by vacuumbeef** [comment]
I'm on 1.0.12 from F-Droid, same happened, messages was sending with big delay, and after cleaning cache everything was fine again.
Same thing happened with my friend, also on 1.0.12 from F-Droid.

**Comment by zincurat** [comment]
I use 1.0.12 F-Droid version. After a month of active usage delay of sending is up to 11 seconds. I haven't this problem on desktop version. Solution: to clear cache (inside app).

**Comment by TheFrenchGhosty** [comment]
Can confirm, this bug is still a thing, it also affect rooms loading time.

**Comment by PLAYERUNKNOWNHatsune01** [comment]
I can confirm that this issue still a thing both on Gplay version and F-droid version and on their latest version

**Comment by superboum** [comment]
I also have the issue on my Android phone (Element from F-Droid, up to date, on a Moto G5 with Android 8.1.0): messages take up to 10 seconds to send.
And similarly, sending messages from Element Web is instantaneously, it takes less than a second.

**Comment by vacuumbeef** [comment]
I am still experiencing this problem too. Clearing cache helps, but it is not a solution, really.

**Comment by TheFrenchGhosty** [comment]
@bmarty This is still a thing.

**Comment by danger89** [comment]
I still have the feeling it's slow. If I compare it with telegram for example.

Maybe use a seperate thread to dispatch the api calls or something. Since the gui feels slow..!

**Comment by PLAYERUNKNOWNHatsune01** [comment]
> I still have the feeling it's slow (Android). If I compare it with telegram for example.
> 
> Maybe use a seperate thread to dispatch the api calls or something. Since the gui feels slow..!

First of all telegram doesn't encrypt messages specially on large groups that's why it's fast than Matrix is terms of sending messages on large group since Telegram doesn't do some extra work to send a message. Second Element Devs are still working on gui make it smooth, look nice and easy to for normal people and it's nothing to do with gui why element are slow on sending messages.

**Comment by danger89** [comment]
> > I still have the feeling it's slow (Android). If I compare it with telegram for example.
> > Maybe use a seperate thread to dispatch the api calls or something. Since the gui feels slow..!
> 
> First of all telegram doesn't encrypt messages specially on large groups that's why it's fast than Matrix is terms of sending messages on large group since Telegram doesn't do some extra work to send a message. Second Element Devs are still working on gui make it smooth, look nice and easy to for normal people and it's nothing to do with gui why element are slow on sending messages.

It's actually even slow with private one-on-one conversations. 

Ok in that case, why not dispatch the encryption task to a seperate thread. So it feels more snappy.

I just try to think along and help. Just all others before me. I think it's an important issue.

I would like to see Element/matrix succeed. Performance and user experience can't be underestimated!!
