### ISSUE TITLE
Location

### ISSUE THREAD

**Issue by bmarty** [vector-im/element-android#2210]
Handle `m.location` events:
- [x] Send it
- [x] Render it

Ref: https://matrix.org/docs/spec/client_server/r0.6.1#m-location

**Comment by omichalek** [comment]
also
- [ ] Request location from your contact.
- [ ] Give location sharing permission for a period of choice.
eg.: I allow sharing my location within a conversation for next 12 hours. If my GPS is running already, location is shared continuously. If my GPS was not enabled in past eg. 5 minutes, a contact in the conversation can issue a location retrieval request and Element tries to fulfil it.

**Comment by anaqreon** [comment]
Has anyone started working on this feature? Is there an existing feature branch we can follow and help develop?
