### ISSUE TITLE
send message fail under lineageos 16 ( android 9 )

### ISSUE THREAD

**Issue by BuddhaLotus** [vector-im/element-android#2216]
**Describe the bug**
send message fail under lineageos 16 ( android 9 )

Thanks for the great work on element!

i have a mobile phone with  lineageos(android 9) flashed, and lastest version element installed, when i send message to other client ( huawei , oppo , my pc ) , the message seems not normal white , and the other ends cant receive the message . 

other direction , other clients send message to it all ok.  and the message between other clients work well.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [Redmi Note 7]
 - OS: [Lineageos 16 (android 9) ]

**Additional context**
 - App version and store [1.0.8 - F-Droid]
 - Homeserver: [my home server run synapse]

**Comment by BuddhaLotus** [comment]
![Screenshot_Element](https://user-images.githubusercontent.com/3349452/95184578-2215bb00-07fa-11eb-9806-f83a49f767a9.jpg)

**Comment by ralaud** [comment]
Did you flash microg or opengapps? So do you have Google Services on your LineageOS device?

**Comment by BuddhaLotus** [comment]
> 
> 
> Do you use an application Firewall (like Afwall+ or Netguard)?
> 
> Because your captive portal service can not connect to google server to check internet access. It is maybe the same problem like in issue #1798

thanks for your reply. i use afwall. you're right! i disable the  captive portal service, then all ok!
but i allow captive portal service access local net work only, element work fine now.
