### ISSUE TITLE
PIN Code to destroy data

### ISSUE THREAD

**Issue by 532910** [vector-im/element-android#2218]
Please add support for an additional PIN code to destroy all data once entered instead of the unlock PIN.

**Comment by TR-SLimey** [comment]
This is what logging out does. That's why logging back in re-downloads user data

**Comment by 532910** [comment]
Exactly.

**Comment by TR-SLimey** [comment]
Are you suggesting a PIN code for logging out then?

**Comment by 532910** [comment]
You can take it like this, but I meant to clear the app storage.

**Comment by 532910** [comment]
In fact it's doesn't matter how it will be achieved, but the result should be a wiped app data on device.

**Comment by TR-SLimey** [comment]
![Screenshot_20201013-212302.png](https://user-images.githubusercontent.com/37966924/95912187-65dc6780-0d9a-11eb-8538-173b3363646a.png)

Here. Just "implemented" that for you. If you want it PIN protected, get an app locker and lock settings.

**Comment by 532910** [comment]
Nope. It must work as an alternate PIN.

**Comment by TR-SLimey** [comment]
What's your usecase anyway?

**Comment by 532910** [comment]
What's the main PIN usecase?

**Comment by bmarty** [comment]
I think the use case is to wipe data in an emergency situation, when the enter PIN code screen is displayed.

**Comment by TR-SLimey** [comment]
But doesn't "Forgot PIN" wipe data anyway? And putting another PIN on that kind of defeats the purpose.

**Comment by violoncelloCH** [comment]
not a pin that protects from wiping the data, but one that triggers wiping of data... so in case anyone forces you to tell them the pin you can just tell them the pin which actually wipes the data instead of telling them the true pin needed for unlocking
... (at least as far as I understand it^)

**Comment by TR-SLimey** [comment]
@violoncelloCH That seems very specific. I mean, I don't see why it can't be implemented, but I feel like it's not that useful. If someone can force you to give them your PIN they can likely force you to give them your password to log back in too, when they realise you've tricked them.

**Comment by 532910** [comment]
> force you to give them your password

I don't know it at all, not just don't remember.

> another layer of protection

The same way erase PIN add one more layer of protection. For the situations when you are forced to unlock it or reveal a pin.

We know how to erase all data for some android application, but do you know how to do it on ios? And the behaviour must be the same, regardless of platform.

**Comment by EdGeraghty** [comment]
Just to throw in my twopenn'orth here - there **absolutely is** a use case for something like this, however when you're at the point of being forced to enter a PIN in an app it's far too late. Regardless of who's asking you to enter said PIN, if they do it and "*whoops all my data has suddenly vanished from the app lol* 😇" I struggle to foresee a situation in which this could end particularly well.

I was actually planning to open a ticket floating the idea of adding the function of disguising Element by "turning it into" something simple like an embedded webpage, or calculator, or even a 2048 game(?!) or... or... or... on a "rage shake", or a series of power button presses or similar. One could then further then functionality by forcing log out if Element is in its disguised state and (for instance) a USB cable is plugged in.

There's a very real chicken-and-egg problem for those needing to keep in real-time comms in situations where your device is likely to be seized - this is particularly exacerbated by Element's not supporting "disappearing messages" (although I don't wish to rehash that conversation here!).

The ability to disguise this app on the receipt of something like a series of power button presses or [...] would obscure the app from the real threat - the person forcing you to unlock your phone in the first place.

I will help in at least getting a skeleton implementation in place in the client, if you'll accept the PR.

**Comment by CJFWeatherhead** [comment]
![](https://imgs.xkcd.com/comics/security.png)

https://wiki.openrightsgroup.org/wiki/Regulation_of_Investigatory_Powers_Act_2000/Part_III

https://wiki.openrightsgroup.org/wiki/Terrorism_Act_2000/Schedule_7

But I feel this is moving towards a [plausable deniability](https://en.wikipedia.org/wiki/Plausible_deniability) debate.

Ultimately this always comes back to threat modelling

**Comment by bmarty** [comment]
We won't implement this feature for the various reasons described above. Thanks for this interesting discussion!
