### ISSUE TITLE
add feature-graphic-google-play

### ISSUE THREAD

**Issue by 532910** [vector-im/element-android#2220]
Please add Google Play Feature Graphic `assets/feature-graphic-google-play.svg`

![image](https://user-images.githubusercontent.com/14617699/95226470-a588d980-0805-11eb-8727-02640040787f.png)
![image](https://user-images.githubusercontent.com/14617699/95226476-a7529d00-0805-11eb-9601-df657f72caab.png)

**Comment by bmarty** [comment]
@Bubu can you help here please? I can provide the needed feature graphic for F-Droid if necessary. This is what we have so far for Gplay:

<img width="935" alt="image" src="https://user-images.githubusercontent.com/3940906/95761729-06ecf480-0cad-11eb-84cc-0ae23afdf184.png">

**Comment by Bubu** [comment]
You can find how the featuregraphic needs to be added to the fastlane folderstrcuture here: https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/

**Comment by 532910** [comment]
It looks better now, thank you.

**Comment by bmarty** [comment]
Yes, indeed! Thanks @Bubu for the support!
