### ISSUE TITLE
Cannot log in to homeserver using @name:server format

### ISSUE THREAD

**Issue by kjekac** [vector-im/element-android#2223]
**Describe the bug**
When I try to log in to my homeserver using the normal login dialogue, I get the error message "Unable to find a valid homeserver. Please check your identifier". If I login using the advanced method instead, it works. If I login using my matrix.org-account instead of my own homeserver-account, it also works. 

**To Reproduce**
Steps to reproduce the behavior: (some translatio
1. Click on "Get started"
1. Click on "Sign in with Matrix-ID"
2. Fill in the details of an account `@name:server` where `server`≠`matrix.org`
3. Click on "Sign in"
3. See error.

**Expected behavior**
I should be logged in.

**To circumvent**
Steps that do work:
* **Either** set `server` to `matrix.org` and repeat steps above
* **Or** perform the following
  1. Click on "Get started"
  2. Click on "Other"
  3. Enter the address of the `server` from above
  4. Click on "Sign in"
  5. Enter the `name` from above and the password
  6. Click on "Sign in"
  7. Be signed in.

**Smartphone (please complete the following information):**
 - Device: Google Pixel 3a
 - OS: GrapheneOS RP1A.201005.004 (Android 11)

**Additional context**
 - App version and store: 1.0.8, from F-Droid

**Comment by bmarty** [comment]
Is the well-known configuration correctly set up on your server? This is required to log in using matrix Id.

See more deatil here: https://matrix.org/docs/spec/client_server/r0.6.1#get-well-known-matrix-client

**Comment by kjekac** [comment]
This solved it, thank you! :)
