### ISSUE TITLE
Rows are hidden in Textinput

### ISSUE THREAD

**Issue by DoM1niC** [vector-im/element-android#2234]
**Describe the bug**
Textinput Box in UI don't update/scrollable the Rows since the current Develop commits, if I reopen it sometimes there is possible to show the hidden Text (Rows), so the previous Rows would be hidden and not scrollable.

**To Reproduce**
Create a chat and write some Text more then 3-4 Rows 

**Expected behavior**

**Screenshots**
![Screenshot_20201014_051242.jpg](https://user-images.githubusercontent.com/1436958/95939248-ea9ba580-0ddb-11eb-8ebf-e6808f758a5e.jpg)

**Smartphone (please complete the following information):**
 - Device: Huawei Mate 20 Lite, tested on another Devices too! 
 - OS: Android 10

**Additional context**
 - App version : Develop 
 - Homeserver: Master 

Testet daily with blanked and cleaned Source without success, only early Versions of the Code are ok.

**Comment by DoM1niC** [comment]
- I reset to previous commits so the issue is not there
- the developed without my fork give me the same issue like my picture 🖼

**Comment by DoM1niC** [comment]
THX PR #2263 fixed my Issue THX @ganfra

**Comment by bmarty** [comment]
Thanks for confirming!
