### ISSUE TITLE
Ringtone volume can not be changed while ringing

### ISSUE THREAD

**Issue by lomion0815** [vector-im/element-android#2246]
**Describe the bug**
For outgoing calls the volume of the ringtone can not be controlled by using the buttons on the phone. Reason is that in this state of the call (callState.Dialing) the buttons already control the conversation volume while the ringtone is played in the "media" context. When you open the volume dialog and change the media volume it affects the ringtone volume

**To Reproduce**
1. Initiate call (e.g. video call in a DM chat)
2. Press the volume button on the side of the smartphone

**Expected behavior**
Ringtone volume changes

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy A8
 - OS: Android 9

**Additional context**
 - App version and store G-Play 1.0.8
 - Homeserver: selfhosted

**Comment by bmarty** [comment]
Should be fixed by #2174 (Element 1.0.10)
