### ISSUE TITLE
Element repeatadly triggers notifications on smart watch, although there are none on the phone

### ISSUE THREAD

**Issue by MikkCZ** [vector-im/element-android#2270]
**Describe the bug**
For all other apps, new notification vibrate my Xiaomi Mi Band 4 only once. But for Element client, it vibrates about three times with interval of about one minute, even though there is a single new message only, and there were no edits from its author. Also the band lists the notification multiple times when you open the list of notifications there, however the phone shows only one.

I assume this could be caused by some interval, when the Element app checks for new messages and fires a new notification (or updates the old one), even though the notification has already been displayed on the phone for the very same message.

**Expected behavior**
Notification about new message should be pushed only once.

**Smartphone (please complete the following information):**
 - Device: Sony Xperia XZ1 compact + Xiaomi Mi Band 4
 - OS: Android 9.0

**Additional context**
 - App version and store: latest from Google Play
 - Homeserver: chat.mozilla.org

**Comment by LinAGKar** [comment]
I have the same thing with a Mi Band 3 and a Oneplus 8T with Android 11, and Element 1.1.11 from Google Play. When a message is received, the band vibrates repeatedly until you dismiss the notification. It also happens when you start a voice call, the band vibrates every few seconds for the duration of the call.

**Comment by LinAGKar** [comment]
I think this is the same as #1673

**Comment by ouchadam** [comment]
Fixed in Element 1.3.2 (see details in #3657)
