### ISSUE TITLE
two gear buttons

### ISSUE THREAD

**Issue by 532910** [vector-im/element-android#2271]
There are two settings buttons, and the green one just opens a white screen.

![image](https://user-images.githubusercontent.com/14617699/96512126-af302980-1268-11eb-925a-b75bd79eec5e.png)

**Comment by AnonymousWebHacker** [comment]
In Element 1.0.9 both the play store and the dbg, I do not get those 2 options that you speak

**Comment by 532910** [comment]
It's 1.0.9 from gplay.

**Comment by bmarty** [comment]
This is a mistake on my side, the green icon will appear if you enable the developer mode and restart the app. It's already fixed for the next release (1.0.10)

**Comment by 532910** [comment]
ack
