### ISSUE TITLE
Text disapear from input when switching between app

### ISSUE THREAD

**Issue by erdnaxeli** [vector-im/element-android#2278]
**Describe the bug**
When switching between apps, the text disappears from the text input, then appears again, then do strange things.

**To Reproduce**
1. Go to a room
2. Send a first message
3. While the message is sending, type a new one (don't send it)
4. Switch to another app
5. Go back to Element => the message is gone, then comes backe a little after

**Expected behavior**
The message stay here.

**Screenshots**
https://cloud.cervoi.se/_matrix/media/r0/download/cervoi.se/VSikgEIdMIFScJrEQQIYhXVW

**Smartphone (please complete the following information):**
 - Device: Moto G4 Plus
 - OS: Android 8.1.0

**Additional context**
 - App version and store : PlayStore 1.0.8
 - Homeserver: cervoi.se

It may be solved already by https://github.com/vector-im/element-android/pull/2158?

**Comment by bmarty** [comment]
Yes, probably fixed by #2158. Please check on 1.0.9, which should be soon available

**Comment by erdnaxeli** [comment]
It seems to be fixed.
