### ISSUE TITLE
Input field doesn't clear after send, if text came from another app

### ISSUE THREAD

**Issue by matrixes** [vector-im/element-android#2287]
**Describe the bug**

When sharing text from another app, the input field in Element is prepopulated correctly, but when you tap send, the input field isn't emptied.

**To reproduce**

1. Open e.g. Chrome browser
1. Go to a page
1. Tap Share in Chrome browser to share the link
1. Select Element
1. Review the information and note that the link is prepopulated in the input field
1. Tap send
1. Notice that the text in the input field is still there

**Expected behavior**

The input field should be emptied

**Smartphone (please complete the following information):**

 - Device: Google Pixel 3 XL
 - OS: Android 11

**Additional context**

 - App version and store 1.0.9 Google Play Store
 - Homeserver: selfhosted home server

**Comment by T-bond** [comment]
Also, if you remove the text after that manually, and you send a new one, that one won't get deleted either. Nor the following ones, until you kill the app.

**Comment by virtualdreams** [comment]
Same problem!

**Comment by benparsons** [comment]
Getting a few independent reports of this issue

**Comment by Dominaezzz** [comment]
I'm looking into this! I think I've found the bit of code. PR in a bit.
