### ISSUE TITLE
Synchronization is much slower since 1.0.9

### ISSUE THREAD

**Issue by thomassross** [vector-im/element-android#2297]
**Describe the bug**
Since v1.0.9, operations like sending and receiving messages while the app is in the foreground takes upwards of 30 seconds.

**To Reproduce**
1. Open a channel
2. Send a message
3. Observe that it takes 30+ seconds for the message to turn white from grey, and for the message to show up on other devices

**Expected behavior**
Sending and receiving messages should take a reasonable amount of time.

**Smartphone:**
 - Device: Samsung S9+ (SM-G965W)
 - OS: Android 10

**Additional context**
 - App version and store: v1.0.9 from F-Droid
 - Homeserver: matrix.org

Sending messages takes less than 2 seconds using the Element Desktop app (v1.7.10) on Linux, using the same account/homeserver, channel, and network connection.

**Comment by akallabeth** [comment]
Same issue, started happening with 1.0.9, 1.0.8 did not have that issue (also, maybe unrelated, #2298 or #1721 did start to affect my setup with this version)

**Comment by BillCarsonFr** [comment]
Hello 1.0.10 (beeing released) has some changes on crypto module performances changes, let me know if it's better after update.
Do you you have some contacts that are using fluffy-chat? There has been an issue with key-request spamming, and the current element android does not react well to this jamming, and it may impact further sync executions due to crypto database beeing to big. Maybe you can rageshake and give reference here?

**Comment by akallabeth** [comment]
@BillCarsonFr Looking forward to that release.
As far as contacts, the only ones not using element are in a few public chat rooms I am following. (they are not encrypted anyway)

**Comment by thomassross** [comment]
Clearing Element's cache (which was 400MB!) in Android's App Info page seems to have helped a little bit, but it is still very slow.

**Comment by thomassross** [comment]
@BillCarsonFr I got the 1.0.10 upgrade through F-Droid today. Sending messages is indeed much faster than before the update, but it's still very slow (10ish seconds on average for the message to send). Receiving messages still takes about 7-8 seconds longer than the desktop app. I have no contacts using FluffyChat.

Is it possible to see the logs that will be sent with the rageshake report before sending them?

**Comment by thomassross** [comment]
This problem has pretty much disappeared for me. I think that DNS was part of the problem --- switching DNS servers to 1.1.1.1 (Cloudflare) using Blokada 4 made message sending much faster.
