### ISSUE TITLE
Message decryption is taking a long time when opening a room

### ISSUE THREAD

**Issue by Half-Shot** [vector-im/element-android#2298]
Messages are taking a long time (+30m) to decrypt in rooms, presumably this is database slowness but could it really be this slow. Other devices/clients aren't showing any unable to decrypt errors.

Related issue: https://github.com/matrix-org/element-android-rageshakes/issues/16156

**Comment by MrCustomizer** [comment]
Is this by any chance related to https://github.com/vector-im/element-android/issues/1721?

**Comment by Half-Shot** [comment]
Yeah it could well be the same issue.

**Comment by BillCarsonFr** [comment]
Hello, it looks like the crypto module has been jammed by fluffy chat key request spamming that leads to a crash in sync and a desync of olm sessions
1.0.10 (currently in process of beeing released) added mitigation to prevent key request jamming.
In parallel we started an effort to ensure atomicity of syncs to avoid such desync
