### ISSUE TITLE
Two elements in the task switcher

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-android#2299]
**Describe the bug**
![image](https://user-images.githubusercontent.com/1190097/97225268-0e75c880-1798-11eb-9f07-62ee7a3ce873.png)

**To Reproduce**
Unclear - I opened the app to log in and noticed there were two elements in the task/app switcher. The green one (left) just redirects me to the second (right).

**Expected behavior**
Only one element.

**Screenshots**
See above.

**Smartphone (please complete the following information):**
 - Device: Pixel 2
 - OS: Android 11

**Additional context**
 - App version and store: 1.0.9 playstore
 - Homeserver: t2l.io

**Comment by T-bond** [comment]
I can create new instances of the application, if I have one already running, and after that I share something from another app.
The sharing will create a new instance, and will leave it in the recents.

**Comment by BloodyIron** [comment]
I can easily get multiple instances of Element running, but neither of them ask me to login, so I don't think it's tied to logins. I'm on android 7.0.1 by the way. And I think this is also really messing up alerts for Element on my phone too.

**Comment by notramo** [comment]
Calling, or using PIN code will also create new instance.

**Comment by Bubu** [comment]
This doesn't seem quite fixed yet. I still get multiple elements in recents when sharing things to element and others have reported the same happens when opening it from a notification.

**Comment by BloodyIron** [comment]
Yeah I still get multiple instances of Element on Android too. Please re-open @bmarty

**Comment by anoadragon453** [comment]
Note that this still seems to be a problem: https://github.com/vector-im/element-android/issues/2569
