### ISSUE TITLE
Multiple instances of Element on Android?

### ISSUE THREAD

**Issue by BloodyIron** [vector-im/element-android#2312]
I'm on the latest version of Element served by Google Play as of this writing. I've noticed that when I go to the screen where I switch between apps by scrolling, that Element often appears to have two instances of itself running. And this seems to possibly be causing issues with clearing/counting notifications on my Android device for Element.

I'm on Android 7.0.1

Not sure what more to add, but this is a curious situation, likely worth adding to the roadmap at some point.

**Comment by T-bond** [comment]
I think this is duplicate of: #2299

**Comment by BloodyIron** [comment]
@T-bond I think you're right, my mistake! <3
