### ISSUE TITLE
Add quick action to invite friends on empty screens

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-android#2321]
... & add in the FAB.

**Effort + Impact**

Low + High

<br> 

**Problem**

Encourage people to start conversations, by easily inviting people.  Simple version will use share sheet with no auto-accept yet.

<br>

**Solved looks like**

% of users with no DMS decrease

**Comment by BillCarsonFr** [comment]
Closed in favor of https://github.com/vector-im/element-android/issues/2348
