### ISSUE TITLE
3 quick actions on a room members profile

### ISSUE THREAD

**Issue by bmarty** [vector-im/element-android#2338]
"Direct message" action has been recently added, but not following the design with the 3 icons here:

https://www.figma.com/file/Jt7bfX8pFugq46GFoDhCn8/Profiles?viewport=-27%2C0%2C0.5280778408050537

<img width="274" alt="image" src="https://user-images.githubusercontent.com/3940906/98008521-e1a75e00-1df4-11eb-8821-d59840de2118.png">

The 2 other actions (call and video call) have to be added in the same time that this is implemented (by opening/create a DM and perform the call action immediately?)

**Comment by notramo** [comment]
How to create a DM then perform a call immediately? The other has to accept the invitation first.

**Comment by bmarty** [comment]
@gaelledel do we still want to implement this?

**Comment by gaelledel** [comment]
@bmarty I doubt that we want to implement this. Let's double-check with @nadonomy

**Comment by gaelledel** [comment]
@bmarty Sorry for the delay on this one. Let's keep the implementation the way it is currently. We'll revise the wider room settings view at later stage.
