### ISSUE TITLE
[Quick Invite Android] Add `Invite friend` action in DM tab

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/element-android#2348]
Requirement:

> “I want to generically share a link to talk to me”
[Invite friends] in empty states/invite lists etc
Trigger native OS share sheet— send a message, or an email, or whatever
https://matrix.to/#/@nadonomy:matrix.org
“Talk to me on Element… http…”

Invite friends, will trigger ACTION_SEND with short text and matrix.to:

`Talk to me on Element https://matrix.to/#/@nadonomy:matrix.org`

<img width="331" alt="image" src="https://user-images.githubusercontent.com/9841565/98346747-b0a67380-2016-11eb-9ead-e5e66deb5e04.png">

Benchmark text on other Apps
TG:  Action is Named `Invite Friend` located in left pannel, msg is:
>"Hey let's switch to Telegram, https://tele..org/Rekrj"

WA: Action is named `❤️ tell a friend` located in settings and msg is:
 > ‎Hey,
WA Messenger is a fast, simple and secure app that I use to message and call the people I care about.
‎Get it for free at https://www.whatsapp.com/download/

Several Options available to add the 'Invite friend action`

1) Put it in the FAB button for DM
<img width="489" alt="image" src="https://user-images.githubusercontent.com/9841565/98346457-47266500-2016-11eb-8f63-3f10478f0ca7.png">

2) Put it as an option in the Create DM screen
<img width="333" alt="image" src="https://user-images.githubusercontent.com/9841565/98346626-88b71000-2016-11eb-9818-c7ad03e9a2bd.png">

**IMPORTANT** In this screen the option should disapear as soon as one member is selected (eg group DM flow)

**Comment by BillCarsonFr** [comment]
Note: This task depends on https://github.com/matrix-org/matrix.to/issues/165 to work properly

**Comment by BillCarsonFr** [comment]
@niquewoodhouse i added some benchmark of invite friend copy, if have some inputs for what we should to for element (short like tg or full description like WA)

TG: Action is Named Invite Friend located in left pannel, msg is:

    "Hey let's switch to Telegram, https://tele..org/Rekrj"

WA: Action is named ❤️ tell a friend located in settings and msg is:

    ‎Hey,
    WA Messenger is a fast, simple and secure app that I use to message and call the people I care about.
    ‎Get it for free at https://www.whatsapp.com/download/

**Comment by niquewoodhouse** [comment]
@BillCarsonFr imo the shorter the better: `Let's chat in Element, ....` or `Let's switch to Element, ....` and let people say more if they want to.

Longer ones risk putting a lot of words into people's mouths that don't sounds authentic.  We also possibly can't see we're _that_ fast or _that_ simple, yet, or that calling works in the expected way, so feels wrong to make it into a longer advert.
