### ISSUE TITLE
Allow aspect ratio free cropping of uploaded images

### ISSUE THREAD

**Issue by benparsons** [vector-im/element-android#2356]
**Is your feature request related to a problem? Please describe.**
You want to share only part of an image, would like to crop it immediately before uploading.

**Describe the solution you'd like**
Tiny editor similar to WhatsApp

**Describe alternatives you've considered**
None, idea stolen from WhatsApp.

**Comment by T-bond** [comment]
There is already cropping functionality. Just the buttons invisible/black on black. In the current release they are fixed.
![Screenshot_20201106-205532_Element (Riotim)](https://user-images.githubusercontent.com/3778556/98409027-723ea200-2072-11eb-831e-b0ae0e3e81a7.jpg)

**Comment by SeerLite** [comment]
Isn't that only aspect ratio cropping though? I couldn't figure out how to crop freely like on other apps.
I think aspect ratio cropping is really unintuitive, it has been a common complaint from my friends

**Comment by SeerLite** [comment]
I'd also like to suggest adding some basic editing functionality like the ability to add text or draw on top of images. They're not as important as cropping but still missed a lot from other IMs, in case you wanna consider them.

**Comment by thefeiter** [comment]
> Isn't that only aspect ratio cropping though? I couldn't figure out how to crop freely like on other apps. I think aspect ratio cropping is really unintuitive, it has been a common complaint from my friends

Every time I want to send only part of a screenshot, I have to use my phones built in image editor to be able to crop with a free aspect ratio. I would really love to see free cropping as well.
I think those are things making it hard for people to transfer to matrix since all other messenger apps have this as a basic feature.

**Comment by thefeiter** [comment]
Maybe the issue can be renamed to "Allow aspect ratio free cropping of images"

**Comment by mxvin** [comment]
This feature is available from upstream libs. See https://github.com/Yalantis/uCrop/issues/801#issuecomment-1018245678
Just add some line on [GalleryOrCameraDialogHelper.kt](https://github.com/vector-im/element-android/blob/050c23b578f2f16893587fb919b6e55688b6653b/vector/src/main/java/im/vector/app/core/dialogs/GalleryOrCameraDialogHelper.kt) and that's it.
This is a very basic feature, important and must be available ASAP :smile:
