### ISSUE TITLE
Always seeing 2 old messages from 2 Sep in the end of the chat

### ISSUE THREAD

**Issue by xor512** [vector-im/element-android#2358]
### Description

No matter what a person I talk with write, his/her message is always before two messages rom 2 Sep (old ones). They never dissappear and are always there.

### Steps to reproduce

Don't remember what I did to make this happens. Please see screenshot: https://imgur.com/a/YZe31Q2

![Screenshot_2020-11-06-22-25-11-495_im vector app](https://user-images.githubusercontent.com/29346009/98417059-8ab5b900-2080-11eb-9fcc-2f812decbf24.jpg)

I expect new messages from November to appear at the bottom. But they appear before "sticky" messages from 2 Sep. Is it possible to unstick them? Ans what is so special about 2 Sep anyway?

### Version information

- **Platform**: web, android app, doesn't matter

For the web app:

- **Browser**: Firefox
- **OS**: Windows, Limix
- **URL**: app.element.io

For the desktop app:

- **OS**:Windows

**Comment by WGH-** [comment]
Looks like a dup of #1119 which was probably incorrectly closed.

A friend of mine had this bug multiple times.

Interestingly, Russian translation of the app seems to be common in all instances. Accident or not?

**Comment by xor512** [comment]
> Interestingly, Russian translation of the app seems to be common in all instances. Accident or not? EDIT: I'm wrong, in this particular case only the messages itself are in Russian.

Yes, exactly, the localization in some kind of English, it's just messages are in Russian.

**Comment by fluboi** [comment]
Same issue here. 
In the android app only, in a specific conversation, an old message I sent more than 10 days ago, is wrongly shown as the last one. 
(And I don't speak russian !)

**Comment by Krzmbrzl** [comment]
I also have this issue.

To me it seems that the issue is that messages are being kept at the bottom until they are fully sent. My guess is that this status might not get updated in some circumstances causing the messages to keep sticking to the bottom.

I did verify however that these messages indeed got sent. So it really only seems to be an issue with updating the status and not with sendingt the message.

The stuck messaged have a consistent ordering between them though. The one that hot stuck first (older) is above the one that got stuck some time later.

**Comment by xor512** [comment]
I've created this issue and I'm constantly getting this spam "Me to. Jak was here". Do you guys have nothing to do?

**Comment by Krzmbrzl** [comment]
If you don't want updates on the issue, just unsubscribe from it.

Besides: Making clear that this affects more than a hand full of people tends to be useful information for developers. Especially if every report contains a few more details on the issue...

**Comment by Krzmbrzl** [comment]
Notw that I have found a workaround for this issue (I now had 5 messages sticking to the bottom):
Go into settings and under general select "clear cache".
This removed all sticky messages for me.

**Comment by bjonnh** [comment]
If I do that nobody receives my messages anymore and I have to reverify everybody (and yes I do clear cache in the app not in android), and that's a temporary workaround that is painful to do 2-3 times a day…

**Comment by reivilibre** [comment]
I noticed this issue back in the RiotX days.

Recently I have begun to experience this issue again with version `1.0.10 [40100101] (G-b652)`.
