### ISSUE TITLE
Input field is not cleared after sharing

### ISSUE THREAD

**Issue by 532910** [vector-im/element-android#2374]
1. share
2. send
3. the message leaves in the input field

every send button press produces the same message

![Screenshot_20201110-204636_Element_(Riot im)](https://user-images.githubusercontent.com/14617699/98711327-e7bdb180-2395-11eb-8c64-3eb166706832.png)

lineageos 17.1
version 1.0.10 from gplay

**Comment by violoncelloCH** [comment]
duplicate of #2287 , right @532910 ?

**Comment by 532910** [comment]
yep, thank you

**Comment by Ezwen** [comment]
Hi there, this is still hapenning to me with 1.0.10, I suppose this is not normal?
