### ISSUE TITLE
Install APKs from chats

### ISSUE THREAD

**Issue by RocketJannis** [vector-im/element-android#2381]
**Is your feature request related to a problem? Please describe.**
Sometimes I want to send an APK file to a friend so he can install it. If I click on the file to open it, it just does nothing.
In the system log I can see the message: `5470-5470/com.android.packageinstaller E/InstallStart: Requesting uid 10106 needs to declare permission android.permission.REQUEST_INSTALL_PACKAGES`

**Describe the solution you'd like**
Add the permission `android.permission.REQUEST_INSTALL_PACKAGES` to manifest. If you want, I could create a pull request for that. Tested this already, it would work. No more work is needed.

**Describe alternatives you've considered**
Don't know any alternatives as the permission is required since Android 7.1.

**Additional context**
The screenshot shows the package installer asking the user to grant the permission. (after adding the permission to manifest):

![Screenshot_1605205738](https://user-images.githubusercontent.com/38166566/98980776-5aa56480-251d-11eb-96b2-da0dcb844577.png)

**Comment by bmarty** [comment]
Implemented in Element 1.1.7
