### ISSUE TITLE
Follow the system setting for dark/light mode

### ISSUE THREAD

**Issue by iiitomo** [vector-im/element-android#2387]
This feature has been nicely implemented by SchildiChat (a fork of element-android). https://github.com/SpiritCroc/SchildiChat-android

Would be nice to add it to Element.

**Comment by kylrth** [comment]
Why was this closed? I think this is common practice for a lot of apps, so I'm surprised at the close without comment.

**Comment by bmarty** [comment]
This issue has been closed automatically by Github because a PR containing a commit which fixes this issue has been merged: #2597.
The feature is available in Element Android 1.0.14

**Comment by kylrth** [comment]
Thanks! Sorry, I forgot to update the app before complaining. :P

**Comment by bmarty** [comment]
No problemo :)
