### ISSUE TITLE
Optional message bubbles

### ISSUE THREAD

**Issue by iiitomo** [vector-im/element-android#2388]
This feature has been nicely implemented by SchildiChat (a fork of element-android). https://github.com/SpiritCroc/SchildiChat-android

Would be nice to add it to Element.

**Comment by witchent** [comment]
Duplicate of https://github.com/vector-im/element-android/issues/1805 and https://github.com/vector-im/element-android/issues/979
(Maybe the newer one of them should be closed as well)

**Comment by kittykat** [comment]
Thank you for requesting this feature. I am going to close this issue as this is a duplicate of #979
