### ISSUE TITLE
Remove the pre-login greeting screen.

### ISSUE THREAD

**Issue by notramo** [vector-im/element-android#2390]
![image](https://user-images.githubusercontent.com/26059643/99189379-d17a7180-2758-11eb-8722-f71cb5607d0f.png)
(screenshot of SchildiChat as I have that installed, but it's the same on Element except the logo)
User's attention is limited. We can't make them read arbitrary amount of text. They have to process and understand the information, and they get tired.
So if we make them read more text in one screen, they will read less on the next.
The greeting screen is nonsense. It provides information the user already know. By reading it and realising they already knew it, they won't pay much attention on the next screen (server selection).

The screen tells the user that there are DMs and group chats in Matrix, and they can talk to others. Are you serious? This is an expectation to every IM platform novadays. If a platform doesn't have it, people don't use it. Please don't waste their attention on telling them that Matrix have this too...
They will notice it from the UI after logging in even if you don't tell them here. (It is also in the Play Store description if it wouldn't be enough...)

It tells the user that they can chat in security, thanks to E2EE. They will notice it too when a chat is created, and an **Encryption enabled** banner is shown (or the **Enable encryption** toggle when creating a room, then the banner if it was on). By the way, if someone knows about Element by somebody telling them, they always bring security and E2EE as the most significant reason to switch.

It is the most horrible idea to present them information they already know (or will learn while using the app).
**They are busy finding the _Register_ or _Login_ button, we make this harder with that greeting screen.**
(I know it from vast experience of recommending the app to non-techie users.)

**Comment by daniellekirkwood** [comment]
Thanks for raising this issue! We appreciate your feedback.

The team are currently re-designing the sign-up & sign-in flow and as part of that work we will be repurposing this screen, which makes this issue obsolete and therefore I will close it.
