### ISSUE TITLE
Annoying error message scares every new user

### ISSUE THREAD

**Issue by notramo** [vector-im/element-android#2391]
**Describe the bug**
When registering (tested on grin.hu HS, but probably it happens on others too), Element shows an error message dialog between the reCAPTCHA, and the e-mail confirmation step (while waiting for e-mail).
> Error:
M_UNAUTHORIZED

**It is shown for _every_ new user, so it's very annoying.** It makes guiding a non-techie user through registration even harder. I am saying it after guiding 5 non-techie through the registration.
It **can't be dismissed**. After clicking OK, it **appears again** after few seconds (no matter how many times you dismiss it).
The most annoying thing is that the error message is **nonsense**. Nothing is wrong, and the registration succeeds after confirming the e-mail in **every case**. There is no reason to show it.

It doesn't happen on Element Web.

**To Reproduce**
1. Start registration on grin.hu HS (probably others too), and fill the forms
2. Complete the "I'm not a robot" challenge
3. Wait for the registration e-mail to arrive (**error is shown here**)
4. Confirm the link in the mail.
5. Registration finished successfully, and logged in to new account.

**Expected behavior**
Not seeing an error message
Especially when nothing causes it, and registration succeeds.

**Smartphone:**
 - Device: Happens with every manufacturer.
 - OS: Various versions.

**Additional context**
 - App version and store: 1.0.9 Play (in every case)
 - Homeserver: grin.hu

**Comment by bmarty** [comment]
Ah, this is a regression, let me have on look on that.

**Comment by notramo** [comment]
Good job! This was fast! I'm waiting for the release to be able to recommend Element to more new users.
