### ISSUE TITLE
Enable Encryption from room properties screen

### ISSUE THREAD

**Issue by notramo** [vector-im/element-android#2394]
![element_room_settings](https://user-images.githubusercontent.com/26059643/99190638-8a43af00-275f-11eb-99ea-ca5b82daa807.png)

**Is your feature request related to a problem? Please describe.**
Finding way to enable encryption in an already existing room is difficult.
Especially when the room properties screen has a Security section but the button isn't there.

**Describe the solution you'd like**
Move the **Enable Encryption** button out from **Room Settings** into the **Security** section (it should have a shield icon too, but I was too lazy to mock it up):
![kép](https://user-images.githubusercontent.com/26059643/99191119-7f3e4e00-2762-11eb-8ac0-016e5c109b86.png)

**Comment by bmarty** [comment]
Thanks for feedback, I think it makes sense!
