### ISSUE TITLE
Sharing text to Element makes message writing impossible

### ISSUE THREAD

**Issue by notramo** [vector-im/element-android#2399]
**Describe the bug**
Shared text remains in composer after sending it.

**To Reproduce**
1. Share text from anywhere to Element
2. Send shared text
3. Text remains in composer after sending
4. Delete text from composer
5. Compose another message
6. Send it
7. I'm not sure if the shared text or the newly composed message remains in composer
8. This happens with every new message after that.

The only workaround is to close the app.

**Expected behavior**
Share text and be able to message normally after that.

**Smartphone (please complete the following information):**
 - Device: tested on multiple devices
 - OS: tested on multiple versions

**Additional context**
 - App version and store: 1.0.10 both F-Droid and Play

**Comment by T-bond** [comment]
Already fixed: #2364

**Comment by notramo** [comment]
Cool!
