### ISSUE TITLE
Android Auto integration

### ISSUE THREAD

**Issue by bbigras** [vector-im/element-android#240]
It would be great to support Android Auto. Especially for notifications.

I tried declaring android auto support in the manifest  https://developer.android.com/training/cars/messaging#manifest-messaging but it didn't seem to work. I thought that with the notifications now using MessagingStyle we would get Android Auto support for free.

Maybe someone else could test.

was previously requested for riot-android as:
https://github.com/vector-im/riot-android/issues/2811
https://github.com/vector-im/riot-android/issues/698

**Comment by bmarty** [comment]
Don't text and drive :)

**Comment by fbruetting** [comment]
> Don't text and drive :)

Serveral of the other popular messengers already provide Android Auto Support (Signal, Threema, Telegram, WhatsApp, FB Messenger, Skype, Hangouts, Kik, WeChat, ICQ and even Cisco Webex).

**Comment by bessw** [comment]
> 
> Don't text and drive :)

Interaction happons through speechassistant.

Also this could give the app a little publicity, when searching in the android auto app for supported "Hands Free Communication" apps, there are at the moment only eight apps listed.

**Comment by bbigras** [comment]
Any interest in this? It's really really useful.

and all the cools kids at school (FB Messenger...) do it.

**Comment by thomcatdotrocks** [comment]
For reference, [Here is Signal's implementation](https://github.com/signalapp/Signal-Android/commit/9148b7da5f4604dae1106d3932bfa7d3bfa63ad4) of Android Auto integration.  [Here's](https://github.com/iNPUTmice/Conversations/pull/2441/files/403eff3d19df8111b73e6edfce91c2f95ee4d785) another implementation from an XMPP client called "Conversations"

**Comment by foux** [comment]
Any news on this one? It's a huge missing point compared to the others, and the reason why my wife doesn't want to switch from WhatsApp to Matrix ;)

**Comment by bbigras** [comment]
I wonder if the new jetpack library could help with this:

https://android-developers.googleblog.com/2020/10/introducing-android-for-cars-app-library.html
https://developer.android.com/jetpack/androidx/releases/car-app#1.0.0-beta01

**Comment by bmarty** [comment]
Available in EA 1.3.2, see #4078 for more details

**Comment by thomcatdotrocks** [comment]
Just an FYI for anyone reading this closed issue: Here's how you can get Android Auto working on a `dbg` build:

  · Enable Developer Mode in the Android Auto app.  Settings > Tap the "Version and permission info tab" until Developer Mode is enabled.
  · Allow Unknown sources.  Setings > 3 button menu > Developer settings > Check "Unknown sources".

![image](https://user-images.githubusercontent.com/37344783/136050286-014df5d4-7b5b-4c27-928d-f55590e236ee.png)

Very excited to have this working!

**Comment by JacobKochems** [comment]
> Just an FYI for anyone reading this closed issue: Here's how you can get Android Auto working on a `dbg` build:
> 
> · Enable Developer Mode in the Android Auto app. Settings > Tap the "Version and permission info tab" until Developer Mode is enabled. · Allow Unknown sources. Setings > 3 button menu > Developer settings > Check "Unknown sources".
> 
> ![image](https://user-images.githubusercontent.com/37344783/136050286-014df5d4-7b5b-4c27-928d-f55590e236ee.png)
> 
> Very excited to have this working!

Hi @th0mcat,
since you spoke about the debug build and it has been quite some time I was wondering if one still needs a debug build for this to work or if it's a released feature now. 
I'm asking because I tried it as you described with release version 1.6.3 and wasn't able to get a notification by Android Auto.
When I google this feature the only meaningful result I get is this thread.

**Comment by BloodyIron** [comment]
@bmarty can we get this re-opened please? I can't really see evidence this is mainlined.

**Comment by th0mcat** [comment]
@JacobKochems @BloodyIron I've had Android Auto notifications working no problem in my CR-V for the past 2 years on various Google Pixels.  If you are using a dbg build of Element/SchildiChat, you have to go into your Android Auto settings, Enable Developer options (scroll to the bottom and tap on "Version and permission info" until you get the toast that Developer mode has been enabled), and enable Unknown sources (tap the three dot menu, Developer Settings, scroll down).

**Comment by BloodyIron** [comment]
@th0mcat thanks for the insights! :)

**Comment by bessw** [comment]
I think only receiving messages and answering to them via speech assistant works.
Sending messages via speech assistant doesn't.
