### ISSUE TITLE
Can't minimise jitsi call in Android 10?

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-android#2418]
Apparently in Android 10 nothing is shown in the upper left corner to minimise a Jitsi call

**Comment by faaaaabi** [comment]
I don't know if this is related, but if I am in an active jitsi group call, leaving the app keeps audio active as expected. But reentering from the group chat apparently opens a new instance of the call besides the already active call. The only way to kill an active call in background, is to hard stop the element-android via the Android app settings.

**Comment by mrjohnson22** [comment]
This happens in Android 9 as well.
See also: https://github.com/vector-im/element-android/issues/2011

**Comment by IdmFoundInHim** [comment]
Actually, an icon is shown but does nothing

**Comment by IdmFoundInHim** [comment]
This desperately needs fixed, as it impacts tightly integrated functionality in a noticable and inconvenient way. I can reproduce on a OnePlus 7 Pro running LineageOS for microG 17.1 (Android 10) and have a report of the same issue on a Google Pixel 4a running Android 11.

**Comment by bmarty** [comment]
Still a pb on EA 1.1.0 after upgrade of Jitsi.
