### ISSUE TITLE
Update of room alias management

### ISSUE THREAD

**Issue by bmarty** [vector-im/element-android#2428]
- [x] Do not render `m.room.aliases` event anymore in the timeline
- [x] Update rendering of `m.room.canonical_alias` event, since it now has an `alt_aliases` field
- [x] Add server API to add and delete local alias
- [x] Do not use aliases from m.room.alias as the room name fallback
- [x] UI: Add section in the room setting, to open a dedicated screen to manage the room aliases

### Element Web

<img width="618" alt="image" src="https://user-images.githubusercontent.com/3940906/99795703-82ec1f00-2b2c-11eb-81ca-3c289854e953.png">

### MSC

https://github.com/matrix-org/matrix-doc/pull/2432

**Comment by manuroe** [comment]
Kamino cloned this issue to [vector-im/riot-ios](https://github.com/vector-im/element-ios/issues/3822)
