### ISSUE TITLE
Not a fan of the new 'user is typing' indicator location

### ISSUE THREAD

**Issue by benqrn** [vector-im/element-android#2430]
The 'user is typing' indicator appears to have recently moved from right above the text input area to the top of the screen.  There's not much space at the top so the text is also cut off when it appears.

I can see how this would be an improved design for large group chats, however for the way I use it on my personal server, usually only chatting 1:1 or several people in a small group, I much prefer the indicator to be near the text input box.

Would be great if there was a user option to have it in either the new location or the old one.

**Comment by bmarty** [comment]
The old location was taking to much space, and reduced the height of the timeline, especially on devices with small screen.
But I agree that now that we have call button, the space in the top bar is too small for the typing notification, room name and topic. I think we will fix that by iterating on the call buttons.

**Comment by benqrn** [comment]
Maybe the 'seen by' icon could indicate that particular user is typing.  It is too small to display useful text, but it could blink, flash, or have some sort of animation, like fluctuating in size by 20% while typing.  Then the focus can stay at the bottom by the text input but not take up additional space in the window.

**Comment by thefirstofthe300** [comment]
I too am very off-put by the location of the current typing indicator. It makes very little sense for me to have to divert my attention away from the focus of the conversation at the bottom of the text box to see if someone is actively continuing that same conversation.

I am of the opinion that the indicator should exist near the text box. Maybe it should use a combination of the Google Messages three dot typing indicator and the user avatar to indicate that person is typing? @benqrn's suggestion is also good: being able to see who is typing based on the size of the avatar indicating the read receipts.

Ultimately, I just want _some_ kind of indicator at the bottom of the text box that someone is typing.

**Comment by bmarty** [comment]
The typing indicator is now near the message composer
