### ISSUE TITLE
Selecting all input text and pressing backspace only deletes first word

### ISSUE THREAD

**Issue by Bubu** [vector-im/element-android#2437]
**Describe the bug**
Since v1.0.10 when I want to delete a composed message and I select the whole message and tap backspace it only deletes the first word of the message.

**To Reproduce**
1. Type new message, don't send it
2. Long press somewhere in the composer field
3. tap 'select-all'
4. tap backspace

**Expected behavior**
Delete all of the selected messsage

**Smartphone (please complete the following information):**
 - Device: Nexus 5x
 - OS: 8.1/LOS 15.1

**Additional context**
 - v1.0.10 FDroid

**Comment by T-bond** [comment]
It works correctly for me.
Samsung Galaxy S10+
1.0.10 [40100100] (F-bba167d4)
Android 10 (with OneUI 2.5)
Using Gboard

**Comment by Bubu** [comment]
Yeah, I cannot reproduce this with an emulator (which uses gboard) either. This happens with LOS and AOSP keyboard for me. :(

**Comment by Bubu** [comment]
Seems fixed here!
