### ISSUE TITLE
Canceled messages sent after reconnection

### ISSUE THREAD

**Issue by T-bond** [vector-im/element-android#2438]
**Describe the bug**
When I send a message without connection to the home server, and I cancel the sending of the message, it gets delivered after connection to the homeserver established.

**To Reproduce**
1. Disconnect from your homeserver (e.g. killing your connections)
2. Send a message (tested on encrypted DM, and  encrypted room with only me in it)
3. Cancel the sending of the message.
4. Restore your connection to the homeserver.
5. Wait, a little while. The message should appear, and the other party (if any) will get the message.

**Expected behavior**
The message not getting delivered.

**Screenshots**
https://youtu.be/M1Xc2cRbpVg

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S10+
 - OS: Android 10 (OneUI 2.5)

**Additional context**
 - App version and store: 1.0.10 [40100100] (F-bba167d4)
 - Homeserver: Custom, using Synapse 1.23

**Comment by bmarty** [comment]
I can confirm the bug by reproducing it :/
