### ISSUE TITLE
Add a confirmation before sending GIFs from the GIF keyboard

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-android#2440]
**Is your feature request related to a problem? Please describe.**
It was unexpected that a GIF was sent immediately when tapping on it. The user could have been scrolling through the list and accidentally tapped, or the user expected to see a larger format of the GIF and tapped on it to see.

**Describe the solution you'd like**
A confirmation before sending the selected GIF.

**Describe alternatives you've considered**
N/A

**Additional context**
This time it worked out in that the GIF sent was relevant to the conversation, but it equally could have been something less appropriate.

**Comment by bmarty** [comment]
I agree, it should open the attachment pre-viewer in this case, as if you have selected an image from your gallery.
This is what WhatsApp does for the record.

**Comment by bmarty** [comment]
Strangely the current behavior has been explicitly implemented by my past me here: a3b205b310fa10c8a82b22c2bd3cbdd348ce92f3
