### ISSUE TITLE
Support creation of Jitsi widgets with "openidtoken-jwt" auth

### ISSUE THREAD

**Issue by jamescl** [vector-im/element-android#2441]
**Is your feature request related to a problem? Please describe.**
Curerntly, element android does not support [prosody-mod-auth-matrix-user-verification](https://github.com/matrix-org/prosody-mod-auth-matrix-user-verification), instead asks for a username and password, which is very confusing for users as they will never know the username and password. 

**Describe the solution you'd like**
In short, deliver [this](https://github.com/vector-im/element-web/pull/15114) for android.

**Describe alternatives you've considered**
Nobody uses an android device, ever. We throw them in the sea. 

i.e. there are no other options.

**Additional context**

From the [element- web PR](https://github.com/vector-im/element-web/pull/15114):

This PR adds the Element Web parts for supporting Synapse OpenID token based auth for Jitsi widgets. This auth enables locking Jitsi widgets to particular homeserver users and rooms. The whole flow is described here: https://github.com/matrix-org/prosody-mod-auth-matrix-user-verification

The auth flow is only used when the Jitsi server has a well-known file indicating the requirement of auth.

**Comment by cubed-it** [comment]
Is this not a duplicate of https://github.com/vector-im/element-android/issues/2116 ?

**Comment by jamescl** [comment]
yes - missed that, so will close in favor of that.

**Comment by mm28ajos** [comment]
Would love to see that feature.
