### ISSUE TITLE
Quoting code messes with formating. Interpretes it as Markdown

### ISSUE THREAD

**Issue by akoyaxd** [vector-im/element-android#2443]
If someone sends a message with code and someone else replies to it, the code in the quote from the response gets wrong formatted. It seems like it gets interpreted as Markdown.
The Desktop App ist not affected.

**Screenshot from the Desktop:**
![image](https://user-images.githubusercontent.com/22196236/100237960-e8c31700-2f2f-11eb-8e2c-8a0005508a12.png)

**Screenshot form Android**
![image](https://user-images.githubusercontent.com/22196236/100238051-0abc9980-2f30-11eb-8a34-f962a7ec3983.png)

### Android Version:
Lineage4MicroG 17.1 - oneplus3 (Android 10)

### Element Version:
1.0.10 [40100100] (F-bba167d4)

**Comment by HarHarLinks** [comment]
I can confirm this on 1.1.9 F-Droid

**Comment by cloudrac3r** [comment]
This is fixed by my https://github.com/vector-im/element-android/pull/6357 which is in release 1.4.26. Try updating.
