### ISSUE TITLE
[Android] Social login

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/element-android#2452]
Implement https://github.com/matrix-org/matrix-doc/pull/2858

#see https://github.com/matrix-org/matrix-react-sdk/pull/5426

<img width="445" alt="image" src="https://user-images.githubusercontent.com/9841565/100357520-145c0500-2ff5-11eb-896a-40ec29773f25.png">

**Comment by niquewoodhouse** [comment]
@BillCarsonFr I think this [layout](https://www.figma.com/file/TMZYcx1hMx4HyZixpxRYRa/Simplify-reg?node-id=274%3A8266) might be better - as we could have an unknown number of them.  Something to discuss with @nadonomy probably.


<img width="289" alt="Screenshot 2020-11-27 at 10 54 31" src="https://user-images.githubusercontent.com/1587166/100441798-f054fe00-309e-11eb-9d7f-aef086a1cd5d.png">

**Comment by BillCarsonFr** [comment]
Just a remark that the buttons do not follow strict branding guidelines.
<img width="822" alt="image" src="https://user-images.githubusercontent.com/9841565/100618748-877ab980-331c-11eb-971f-6f91575dd312.png">

vs

<img width="274" alt="image" src="https://user-images.githubusercontent.com/9841565/100618790-93667b80-331c-11eb-8dcc-caa91c1d5c3d.png">

Not sure how much of that is mandatory ...
