### ISSUE TITLE
Bugreporter uses riot-android

### ISSUE THREAD

**Issue by twouters** [vector-im/element-android#2454]
Found this by coincidence, not sure if this is worth any effort.

https://github.com/vector-im/element-android/blob/4c599d3d4021ead4c96a020d88d20c7cd67f0431/vector/src/main/java/im/vector/app/features/rageshake/BugReporter.kt#L252

**Comment by bmarty** [comment]
Yes, thanks.
"riot-android" is the app name used by the rageshake service, to create a Github issue in the correct Github repository (see https://github.com/matrix-org/rageshake#post-apisubmit).
We use the same Github repository for Riot-Android (now deprecated) and Element Android (formerly RiotX). So this is not a problem.
Maybe one day we will change the configuration of the matrix.org rageshake instance and then we could change this value, but it is clearly not a priority :)
