### ISSUE TITLE
Don't use photos for empty room list placeholder

### ISSUE THREAD

**Issue by notramo** [vector-im/element-android#2477]
**Describe the bug**
The new empty room list design is confusing to new users because of photos of real people. They think they are already in a chat with them and scared because they don't know who they are.

**To Reproduce**
1. Open Element with an account that is not in any DMs.

**Expected behavior**
- No placeholder, instead the "Invite friends", and "Show my QR code" button
- If there is placeholder, don't use photos, instead use avatar placeholders, like this:
![avatar placeholder](https://upload.wikimedia.org/wikipedia/commons/7/7c/Profile_avatar_placeholder_large.png)

**Comment by bmarty** [comment]
(Some screenshots are in the description of https://github.com/vector-im/element-android/pull/2450)

Scared? Isn't it a bit exaggerating?

This is just some placeholders without any click action.

"Invite friends" acrtion is just behind the FloatingActionButton, and in the left drawer. Maybe a good idea to add it here, I do not know.

**Comment by notramo** [comment]
They often think about Matrix as a "hacker stuff" and which is only used by hackers. It can make them feel their account is compromised.

Two questions:
**What's the point of using real photos instead of placeholders?**
**Do any commercial platform use photos of real people for this purpose?**

**Comment by bmarty** [comment]
Design decision can be endless and should rather be discussed here: https://matrix.to/#/#element-design:matrix.org?via=matrix.org&via=feneas.org&via=mozilla.org
