### ISSUE TITLE
Visual notification on the mobile application icon

### ISSUE THREAD

**Issue by user67x** [vector-im/element-android#2493]
Hello,

I use Element on PC and mobile. But in mobile application, it lacks a visual notification in the form of a number, or something else, a bit like on Whatsapp, Google Play (and other Google application), Instagram, Twitter, and almost all mobile applications on Android.

Can we expect this feature in a future version?

Thanks!

**Comment by bmarty** [comment]
Hello, can you be more specific? We already have badge in the icon on the application:
<img width="70" alt="image" src="https://user-images.githubusercontent.com/3940906/101344987-ad590e80-3886-11eb-9bb3-945c78e71691.png">
Or inside the app:
<img width="342" alt="image" src="https://user-images.githubusercontent.com/3940906/101345023-bba72a80-3886-11eb-9280-080abe5cbed5.png">

<img width="352" alt="image" src="https://user-images.githubusercontent.com/3940906/101345068-ca8ddd00-3886-11eb-95c4-4ac3092ad9d4.png">

**Comment by KardinalReusen** [comment]
I don't have any badge on my icon in the element android app. The telegram icon on the other hand shows the numbers of unread messages. So does the element desktop client (arch linux). Can anyone please show me how to turn on the feature in the element android app?

**Comment by SimonBrandner** [comment]
I am on Android 10 and I don't have a number there as well. But I do have a notification dot there. That seems to be the case for all the apps.

![Screenshot_20210124-154430](https://user-images.githubusercontent.com/25768714/105633838-4524b300-5e5b-11eb-89b8-0904983f8056.png)

**Comment by KardinalReusen** [comment]
Thanks for the quick reply. I am on Android 8. I do not have a notification dot for Element. But I do have notification numbers for the other apps. 

![photo_2021-01-24_15-58-02](https://user-images.githubusercontent.com/46031579/105634150-fe37bd00-5e5c-11eb-88f2-cd038375c46d.jpg)

**Comment by SimonBrandner** [comment]
Hmmm, on Android 10 in notification settings you can enable and disable the notification dot per-app. Maybe there is something similar for Android 8. If not this may be a bug but that's up to the devs to figure out.

**Comment by KardinalReusen** [comment]
I looked in the "Notifications management" of my Android 8 Phone. In case of the telegram app or e.g. the mail app there is an option "Badges"  witch is turned on in both cases. In the notifications dialog of the element app this option is not existing.

![image](https://user-images.githubusercontent.com/46031579/105634882-7784df00-5e60-11eb-876e-9e34566dbeeb.png)

**Comment by user67x** [comment]
Hello. The problem is solved: works as design. I have turn the badge for notifications. I don't know why it wasn't activated by default.
