### ISSUE TITLE
[Spaces] / Read Only MVP Phase 1

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/element-android#2495]
See https://github.com/matrix-org/matrix-doc/pull/1772
and room types https://github.com/matrix-org/matrix-doc/pull/1840

-> Basic support for spaces. As a user I should be able to receive an invite, preview the space content and join (or discard invite). Support leave.

## SDK

- [x] Database
  - [x] persist room type
  - [x] New SpaceSummaryEntity
  - [x] Database migration  
- [ ] Create Space Service 
  - [x] Create Space
  - [x] Get Space from Id
  - [x] Peek Space from id or alias
  ~~- [ ] Detect/Protect from space subspace cycle~~
  - [x] Get space summary (detached + live)
  - [x] Join Space (and default rooms of that space)
- [x] Space Model
  - [x] Add room to space
  - [x] Remove room
  - [x] Add subspace
  - [x] Set child as default / add order
- [x] Support room type (messaging / space)

## UI

- [x] Debug commands to create space / add child
- [x] Add Lab flag in settings to enable space feature
- [x] Show user spaces in left drawer (invites + member)
- [ ] Click on invite to open space preview
  - [x] Add Space Preview Activity / fragments / model
  - [x] 0 depth support
  - [x] subspace display  support (simple max depth)
  - [x] Join Space
  ~~- [ ] Discard Invite~~
  ~~- [ ] Manage edge cases (failed to peek?)~~
 ~~ - [ ] Integrate new Space API for preview~~
- [ ] Handle current space selection 
  - [x] filter visible rooms 
  - [x] filter visible DM
  - [x] Update home toolbar
  - ~~[ ] Notification badge~~
  - ~~[ ] Handle All spaces case~~
 - ~~[ ] New FAB buttons behaviour~~
   - ~~[ ] In room tab should open explore space rooms screen~~
   - [ ]~~ In DM tab, modify a bit existing screen to display footer 'Looking for someone outside of <Space>? Switch space or Invite them'~~

## Issues

 - ~~[ ] Only show root spaces on left drawer (avoid to have both parent and child at same level)~~

**Comment by progserega** [comment]
Hello!
Standart use case for users: create group of his contacts. It is create personal group, with not show anybody. But...
But I try create private space on https://riots.im/adhoc/spaces3 and can not simply add my private chats to this space... I can add only room or invite users. After invate users - they must join to my PRIVATE space. What is this?! What changes from community?! 
Why you do not create simply grouping of private chats and rooms. I want simply have private "groups": 
1. work
1. home
1. friends
Why my friends need join to my private spaces?! I do not understand...

**Comment by t3chguy** [comment]
> can not simply add my private chats to this space

This is a feature which simply has not had UX designed for it but is planned.

**Comment by progserega** [comment]
> This is a feature which simply has not had UX designed for it but is planned.

I hope this is will be accepted. :+1:

**Comment by heyakyra** [comment]
:information_source: All existing communities will die instead of be migrated:

>>    Which phase one covers migration of existing groups/communities to spaces?
>
> None.

https://github.com/vector-im/element-web/issues/15930#issuecomment-768715792

**Comment by t3chguy** [comment]
They won't die, the newer clients will just lose the ability to access them
