### ISSUE TITLE
Send image dimensions in integer

### ISSUE THREAD

**Issue by tomkwok** [vector-im/element-android#2502]
**Describe the bug**
When attempting to send an image to a room, the client sends image dimensions `w` and `h` and also file `size` in floating point instead of integer required in Matrix spec. An example is as follows.

`'{"msgtype":"m.image","body":"20201207_210205.jpg","info":"mimetype":"image/jpeg","w":1328.0,"h":747.0,"size":79478.0},"url":"[deleted]"}'`

**To Reproduce**
Send an image in a room using Element Android. The images would not send to a Conduit server implemented in Rust (strongly typed)

**Additional context**
 - App version and store: `Element (Riot.im)/1.0.4 (Linux; U; Android 6.0.1; Flavour FDroid; MatrixAndroidSDK_X 0.0.1)`
 - Homeserver: Conduit

**Comment by Dominaezzz** [comment]
Same as https://github.com/vector-im/element-android/issues/363 .

This is quite the persistent issue isn't it.
