### ISSUE TITLE
Ability to disguise Element

### ISSUE THREAD

**Issue by EdGeraghty** [vector-im/element-android#2507]
One of the biggest threats activists face is seizure of their devices, as this gives full access to e.g. the messages stored on it.

It would be great if there was a way to send some sort of series of power button presses or similar, which would disguise the app in the launcher, remove the app from the recents bar, & disguise it as something like a calculator which can be unlocked by pressing the corners anti-clockwise or similar.

This would remove the immediate threat: a fairly disinterested adversary scrolling through your apps to find something.

This would also ensure that those relying on the app to keep in secure contact in hostile situations would be able to stay in communication, rather than having to uninstall the app and go radio silent until the next check in.

**Comment by penn5** [comment]
Better - a calculator where you do a certain sum to unlock it

**Comment by bmarty** [comment]
I do not think this will be implemented by the core team. Feel free to make a fork and implement it!
