### ISSUE TITLE
Encrypted reactions are not managed

### ISSUE THREAD

**Issue by jtrees** [vector-im/element-android#2509]
**Describe the bug**
Some emoji reactions in the timeline don't get interpreted properly. Instead they show up as `{ "type": m.reaction }`

**To Reproduce**
1. Send an emoji reaction in an encrypted room from FluffyChat.
2. Check the room from a different FluffyChat device: The reaction is rendered correctly.
3. Check the room from Element Web: The reaction is rendered correctly.
4. Check the room from Element Android.

**Expected behavior**
The reaction is rendered correctly.

**Screenshots**
![Screenshot_20201209-094024_Bliss_Launcher](https://user-images.githubusercontent.com/5802758/101606002-28dfca80-3a03-11eb-93f3-22c4efe0c2a1.png)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S7 Edge
 - OS: /e/ 0.12 (based on Android 8.1.0)

**Additional context**
 - Element Android 1.0.11 from F-Droid
 - FluffyChat 0.23.0 from F-Droid
 - Homeserver: matrix.org

It's hard to tell whether the underlying bug is on the FluffyChat or Element Android end. The former seems likely but since Element Web renders the reaction correctly, I am not entirely sure.

The corresponding FluffyChat issue is here: https://gitlab.com/ChristianPauly/fluffychat/-/issues/178

**Comment by bmarty** [comment]
The message `{"type": m.reaction}` appears only if you have enabled the developer mode and enabled "Show hidden events in timeline". But even with this configuration, the reaction should be displayed properly under the related event.

<img width="348" alt="image" src="https://user-images.githubusercontent.com/3940906/101908677-b87ca900-3bbc-11eb-9328-7c415318a67e.png">

Ex:

<img width="345" alt="image" src="https://user-images.githubusercontent.com/3940906/101908728-cd593c80-3bbc-11eb-97fa-7aeec7bf2696.png">

So not a bug?

**Comment by jtrees** [comment]
> the reaction should be displayed properly under the related event.

This part is not the case for me.

I also just turned off developer mode and was able to reproduce the problem: I am still missing the emoji and I still see the `{"type": m.reaction}`.

**Comment by bmarty** [comment]
Could you paste here the source of the reaction event?

**Comment by bmarty** [comment]
Also are you sure that the reaction refers to the event you think it is? It can be a reaction for any events in the past.

**Comment by jtrees** [comment]
A FluffyChat maintainer responded (in another, duplicate issue) that the bug is on Element's end:

https://gitlab.com/ChristianPauly/fluffychat-flutter/-/issues/217#note_469010030

**Comment by jtrees** [comment]
> Also are you sure that the reaction refers to the event you think it is? It can be a reaction for any events in the past.

I am certain. I have reproduced it in rooms created solely for the purpose of reproducing the behaviour with only myself as a member.

**Comment by jtrees** [comment]
> Could you paste here the source of the reaction event?

This turns out to be trickier than I thought. On mobile I can view the encrypted and decrypted source but I cannot copy it. On desktop I don't know how to view the source of an emoji reaction.

How can I access the data you need?

**Comment by huguesdk** [comment]
i have the same problem. a reaction added from fluffychat is not visible in element android and the message `Debug: event type "m.reaction"` is displayed instead in the timeline (and “display hidden events” is disabled). i was able to add the same reaction in element android and it shows up under the message as being alone, but in fluffychat and element web the message has 2 reactions. removing the reaction from fluffy chat displays a “deleted message” in the timeline.

the source of the reaction refers to the correct `event_id` of the message.

i was also not able to copy the source of the message, so here are screenshots.

encrypted source:
![fluffychat_reaction_encrypted](https://user-images.githubusercontent.com/1168359/105376583-31ced900-5c0a-11eb-9dbd-775ddbf9216a.png)

decrypted source:
![fluffychat_reaction_decrypted](https://user-images.githubusercontent.com/1168359/105376615-385d5080-5c0a-11eb-96cf-dcc640108645.png)

**Comment by jtrees** [comment]
> A FluffyChat maintainer responded (in another, duplicate issue) that the bug is on Element's end:
> 
> https://gitlab.com/ChristianPauly/fluffychat-flutter/-/issues/217#note_469010030

Here is the reply, by the way:

> This is an element-android bug of not handling m.room.encrypted messages correctly. Please open a bug report with them, that they don't handle m.room.encrypted that are, after decrypting, m.reaction

**Comment by faaaaabi** [comment]
I can confirm that reactions send from a fluffy client are displayed as described. Element Desktop however seems to handle this message type correctly. See the Screenshots attached

![Screenshot_20210127-091904](https://user-images.githubusercontent.com/12394037/105963402-3fa8b200-6081-11eb-9fad-090811856b33.png)
![Bildschirmfoto 2021-01-27 um 09 19 26](https://user-images.githubusercontent.com/12394037/105963422-46372980-6081-11eb-82d8-0b802edf6d76.png)

**Comment by bmarty** [comment]
I see.
I would argue that it is absolutely useless to encrypt reaction, since all the interesting content (the reaction key (generally an emoji) and the eventId it applies to) is visible in the encrypted message.

**Comment by jtrees** [comment]
@bmarty Thanks for fixing this. I look forward to the next release!

**Comment by bmarty** [comment]
Fixed in EA 1.1.4
