### ISSUE TITLE
No known servers error is given when joining rooms on new Gitter bridge

### ISSUE THREAD

**Issue by iinuwa** [vector-im/element-android#2516]
**Describe the bug**
Bridged rooms on the `gitter.im` server cannot be joined from Element Android.

An error is given:

> No known servers
> [Retry]

**To Reproduce**
1. Click on the join room button.
2. Type the room alias (`#<owner>_<repo>:gitter.im`) (because gitter.im doesn't show up as a Matrix network)
3. Click on the entry in the list
4. Click "Join" under "Room cannot be previewed" message.
5. See the error message above

OR

1. Click on a link to a room alias for a Gitter bridge room from another room.
2. Click "Join" under "Room cannot be previewed" message.
3. See the error message above

I believe that I also got the same error when using a matrix.to link, but don't remember at the moment.

**Expected behavior**
The room can be joined from Element Android as they are able to be joined on Element Web.

**Smartphone (please complete the following information):**
 - Device: Moto g5 play
 - OS: Android 9.0[e.g. Android 6.0]

**Additional context**
 - App version and store: 1.0.11 - Google Play
 - Homeserver: matrix.org

I am able to re-join the bridged scala/scala room (`#scala_scala:gitter.im`) after joining and leaving on Element Web.

**Comment by MadLittleMods** [comment]
I can also reproduce with upper and lowercase aliases: `#Microsoft_TypeScript:gitter.im`, `#microsoft_typescript:gitter.im`

 - Google Pixel 4A
 - Android 11
 - Element Android v 1.0.11



---

Reference where we first discussed this: https://matrix.to/#/!OvgDmYaPOFRRWnIdQe:half-shot.uk/$ja4DojqSwjcF_F2E4dvFOMpm9jKqc8t_VInYPvpaDUo?via=half-shot.uk&via=matrix.org&via=gitter.im

**Comment by MadLittleMods** [comment]
@BillCarsonFr pointed out trying `/join` which does seem to work. `/join #Microsoft_TypeScript:gitter.im`, etc

**Comment by iinuwa** [comment]
Confirmed that works for me.

**Comment by MadLittleMods** [comment]
Related to https://github.com/vector-im/element-android/issues/2194
