### ISSUE TITLE
Wait for all room members to be known before sending a message to a e2e room

### ISSUE THREAD

**Issue by bmarty** [vector-im/element-android#2518]
Due to lazy-loading of room members, all the room members are not known after an initial sync.
The other members are loaded when the user load the timeline of the room.
If the user send a message in this room before all the members are known, the message will be encrypted only for known users, and not for every one in the room. Other users will not be able to decrypt the message.

The SDK has to wait for all the members to be known before sending a message to a e2e room

**Comment by uhoreg** [comment]
Looks similar to this Element iOS issue: https://github.com/vector-im/element-ios/issues/3807

**Comment by bmarty** [comment]
Fixed in Element Android 1.0.14
