### ISSUE TITLE
Latest update breaks RTL layout

### ISSUE THREAD

**Issue by barudaret** [vector-im/element-android#2523]
**Describe the bug**
The text entry field is squeezed thin

**To Reproduce**
1. Put app in farsi or arabic
2. Go to a room
3. Look at text box
4. Observe problem

**Expected behavior**
Normal sized text field

**Screenshots**
If applicable, add screenshots to help explain your problem.  >  Ok, I will
![Screenshot_20201211-000759_Element dbg](https://user-images.githubusercontent.com/32847759/101873860-f76f1800-3b44-11eb-8695-0e7bc7997512.jpg)

**Smartphone (please complete the following information):**
 - Device: [e.g. Samsung S6]  Samsung GS20
 - OS: [e.g. Android 6.0] Android 10

**Additional context**
 - App version and store [e.g. 1.0.0 - F-Droid]  1.0.12-dev [206909200] (G-b922) develop F-Droid
 - Homeserver: [e.g. matrix.org] ostavrosnika.com

**Comment by bmarty** [comment]
Thanks for reporting, I will fix it right now
