### ISSUE TITLE
v2 identity service API: Hash details not requested before sending pepper

### ISSUE THREAD

**Issue by mrjohnson22** [vector-im/element-android#2531]
When using a self-hosted ma1sd as my identity server, I noted that Element Android never requests `GET /_matrix/identity/v2/hash_details` and thus sends an invalid pepper with `POST /_matrix/identity/v2/lookup` that always gets rejected by the identity server.

This prevents the Discovery page from working, which shows error dialogs instead of telling me which of my emails have been / can be made discoverable.

A possibly related issue is that Element Android attempts to use an old token in the "Authenication: Bearer" header before requesting a new one via `POST /_matrix/identity/v2/account/register`.

Meanwhile, Element Web doesn't have any of these problems: it requests `POST /_matrix/identity/v2/account/register` to get a token, then `GET /_matrix/identity/v2/hash_details` with that token to get a pepper, and finally `POST /_matrix/identity/v2/lookup` with that pepper to successfully get lookup results.

**To Reproduce**
1. Connect to an identity server and bind at least one email to your Matrix account, such as with Element Web->Settings->Email addresses->Add.
2. Sign in to Element Android with the same Matrix account, and go to Settings->General->Discovery.
3. Wait a moment for the page to load information on your email accounts.
4. If using ma1sd as your identity server, get an error message of `M_INVALID_PEPPER`. Emails are listed, but not information about their discoverability is shown.
5. If not using ma1sd, just track HTTP request logs and see that no request to `hash_details` is made. (I assume this remains a problem even when using other identity servers.)

**Expected behavior**
Element Android should be requesting `hash_details` before sending a pepper & deciding on a hash algorithm.

**Screenshots**
This is the error I get from ma1sd:
![Screenshot_20201212-185802_Element (Riotim)](https://user-images.githubusercontent.com/8988672/101999548-39ff3480-3cac-11eb-93be-c21e7e33bd78.jpg)

**Smartphone (please complete the following information):**
 - Device: Samsung S8
 - OS: Android 9

**Additional context**
 - v1.0.11 Google Play & v1.0.12-dev F-Droid
 - Homeserver: custom homeserver

This doesn't happen to me for my matrix.org account, and some of the errors I'm hitting may be due to ma1sd. Nonetheless, Element Android appears to be deviating from the IS spec, so I'll file this just in case.

I also filed this as an ma1sd bug: https://github.com/ma1uta/ma1sd/issues/76

**Comment by bmarty** [comment]
Element Android follows the IS spec and if it is not the case this is a bug. I add this issue to the current sprint to investigate it.

Initial request of hash details:
- https://github.com/vector-im/element-android/blob/develop/matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/identity/IdentityBulkLookupTask.kt#L54)
Hash detail rotation:
- https://github.com/vector-im/element-android/blob/develop/matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/identity/IdentityBulkLookupTask.kt#L104

Is `ma1sd` idebntity server running Sydent?

**Comment by bmarty** [comment]
I just check and Android Element request what you expect it to request:

> POST https://vector.im/_matrix/identity/v2/account/register
GET https://vector.im/_matrix/identity/v2/account
GET https://vector.im/_matrix/identity/v2/hash_details
POST https://vector.im/_matrix/identity/v2/lookup

May I have access to `ma1sd` identity server to perform some test?

**Comment by mrjohnson22** [comment]
Thank you, but for the time being I'd like to keep my homeserver+IS private since I have friends' & family's info on there.

But it looks like ma1sd is not the culprit. As a test, **I replaced my ma1sd with a fresh install of sydent**, and even then, **Element Android never requests `hash_details` when viewing the Discovery page**. Neither sydent nor nginx logs show `hash_details` being requested by Element Android, but it does show it being requested by Element Web.

The only difference is that sydent doesn't hit any errors. **It must be that sydent accepts arbitrary, client-chosen peppers**, and thus doesn't need a client to request `hash_details`. However, the IS spec says that the IS must choose which pepper a client must use, which a client obtains via a response to [`hash_details`](https://matrix.org/docs/spec/identity_service/latest#get-matrix-identity-v2-hash-details). Then the IS must respond to a [`lookup`](https://matrix.org/docs/spec/identity_service/latest#post-matrix-identity-v2-lookup) request using any other pepper with status 400 and `M_INVALID_PEPPER`. This is what ma1sd does, so its error is actually spec-compliant.

So unless I misconfigured my sydent somehow, it looks like both Element Android and sydent are deviating from the IS spec a little bit, while ma1sd follows it strictly.

**Comment by bmarty** [comment]
That's very weird... On my side, it works. I assume you will have to debug the Element Android application by yourself to check what's wrong in your specific private configuration.

**Comment by mrjohnson22** [comment]
Interestingly, if I sign out & sign back in, `hash_details` gets requested and everything works properly. It stops working as soon as my identity server rotates its pepper, like when I restart it. The same occurs with the latest version of Element Android built from source.

It must be that Element Android only requests `hash_details` on its first-ever request to the identity server, and saves the returned pepper & hash algorithm permanently. That leads to a `M_INVALID_PEPPER` error once the pepper has been rotated, and instead of requesting `hash_details` again to get the new pepper, it just gives up and displays an error.

I'll look through the code to confirm if this is what's really happening, and if so, to find what it would take to request `hash_details` in response to a `M_INVALID_PEPPER` error.

**Comment by mrjohnson22** [comment]
Here's the problem: Element Android _does_ try to refresh the pepper, but only when it receives an error response whose body contains both `"errcode": M_INVALID_PEPPER"` and `"error": "<some message>"`. If the `"error"` field is missing, the response is treated as a generic error instead of a well-known Matrix error, and Element Android falls back to displaying an error dialog instead of trying to recover from the error by asking for `hash_details`.

And it just so happens that ma1sd's error response doesn't specify `"error"` in its body, which is [against the spec](https://matrix.org/docs/spec/identity_service/latest#api-standards). That means this should be fixable by updating ma1sd to add an error message in its invalid-pepper response.

Closing this since Element Android is behaving according to the spec. Thanks for your help!
