### ISSUE TITLE
Decide between JPG and PNG (or use WEBP) on paste

### ISSUE THREAD

**Issue by Pwuts** [vector-im/element-android#2534]
**Is your feature request related to a problem? Please describe.**
When pasting a photo, it is always uploaded as a PNG, which uses up a lot of bandwidth and is suboptimal for photo type images.

**Describe the solution you'd like**
Either use WEBP, which is suitable for illustrations as well as photos, or encode the pasted image as PNG _and_ JPG, and use the smallest of the two results.

**Comment by bmarty** [comment]
I think this issue should be open on [element web](https://github.com/vector-im/element-web/issues), if it does not exist yet. This GitHub repository is for the Android applicaiton. Please re-open if you do not agree.

**Comment by Pwuts** [comment]
Sorry, my bad, will do!
