### ISSUE TITLE
Room Topic not displayed correctly after visiting a link

### ISSUE THREAD

**Issue by allendema** [vector-im/element-android#2551]
**Describe the bug**
Sometime the room Topic is not displayed correctly, in esence the upper body part of the text field  there is "cut" in half.

**To Reproduce**
1. Go to a desired room and look for "Topic"
2. Open the Link if there is any
3. Go back to the app

**Expected behavior**

The text or URL to be displayed correctly.

**Smartphone (please complete the following information):**
 - Device: [Pixel 3a]
 - OS: [Android 11]

**Additional context**
 - App version and store: [1.0.11 / F-Droid]
 - Homeserver: [matrix.org]
 - No fonts changed

**Comment by onurays** [comment]
I couldn't reproduce it on the emulator of Pixel3a, Android 11. Could you please provide some screenshots?

**Comment by allendema** [comment]
Uploaded it here as I could not do it on GH from the phone.

[Screenshot](https://bin.snopyta.org/?3f25b2835b782d3f#3gQpqrE3oHK6L5zq1ct8vCdBwzHsoo1rsPupPXcqkDwT)
