### ISSUE TITLE
Filter NSFW rooms and icons on search

### ISSUE THREAD

**Issue by j-james** [vector-im/element-android#2559]
**Describe the bug**
Searching for public rooms to join brings up a wide variety of workspace-explicit rooms, many with NSFW icons.

**To Reproduce**
1. Go to the "Rooms" tab.
2. Click on the `#+` new room icon in the bottom right.
3. Type "nim" (what I happened to be looking for) into the searchbar.
4. Observe the results.

**Expected behavior**
NSFW images (room icons) should not pop up with no warning, and NSFW channels should not pop up without explicitly allowing them to. As this appears to happen with many / almost all search terms, I'd also suggest that searching for rooms should be disabled or seriously rethinked.

Perhaps the search dialog that pops up after clicking the `#+` button should be replaced with a snazzy way to join a room / instance without providing room suggestions.

(apologies if this is the wrong place to open an issue. although this likely affects all element clients, it doesn't really seem to be a problem with the spec. if there's a better place for these kinds of issues, i'll move this there.)

**Comment by uhoreg** [comment]
see also https://github.com/vector-im/element-web/issues/4683

**Comment by ara4n** [comment]
basic solution in place at https://github.com/vector-im/element-android/pull/2975

**Comment by bmarty** [comment]
(Available since Element Android 1.1.3)

**Comment by j-james** [comment]
Fantastic, thank you! I'll give it a whirl when the F-Droid package updates.

**Comment by j-james** [comment]
Works great!
