### ISSUE TITLE
Option to disable emoji keyboard

### ISSUE THREAD

**Issue by tulir** [vector-im/element-android#2563]
The button to open Element's new emoji keyboard takes a lot of space from an already small input field. My keyboard has a perfectly good built-in emoji input option that doesn't take space from the input field, so I'd like to hide the one in Element.

An alternative would be to make the input field buttons more compact and reduce horizontal padding in the input field. Telegram at least seems to do it much better.

**Comment by ManDay** [comment]
I'm in no position to decide what's good or bad for element-android, but I cast my vote that #2514 as a whole should be reverted. It goes against any rationale for good software design.

**Comment by 6543** [comment]
@ManDay each has it's own arguments ... I think it should at leas be a **Option** to remove it completely, since there is a demand for that ...

**Comment by ElegyD** [comment]
Are there really that many keyboard apps that don't ship with Emojis? I always use the built-in one like @tulir. It's in my muscle memory and I don't have to remember for each messenger app where the emoji button is located.
I also have to agree with @ManDay that an app shouldn't deal with another dependency that needs to be updated every time Unicode adds new Emojis/Glyphs for example.
Also, the Emoji library adds around 2.4 MB in APK size according to [here](https://mvnrepository.com/artifact/com.vanniktech/emoji-google/0.7.0).
If we leave the emoji picker in, should it per default be disabled?

**Comment by bmarty** [comment]
We will add a setting "Show Emoji keyboard", set to **true** by default, in `Settings/Preferences/Message Editor` section.
