### ISSUE TITLE
A "service" message stay permanently at the bottom of the messages in a direct room

### ISSUE THREAD

**Issue by jpggithub** [vector-im/element-android#2566]
**Describe the bug**
A "Vous avez passé un appel" (You made a call) message stay permanently at the bottom of the messages in a direct room.
There are 3 weeks between the real last message and this annoying message.
I had other calls with the same person in this direct room. The other messages are in the right order.
I can't delete this annoying message.

When I use https://app.element.io/ this annoying message is not at the bottom of the list.
It happens only on my smartphone.

**To Reproduce**

The message stay without doing anything special.
I don't know how to reproduce the bug.

**Expected behavior**
The message at the bottom should be the last.

**Smartphone (please complete the following information):**
 
    Samsung S4
    OS: Lineage 17.1. Android 10.0
    Element 1.0.11 (fdroid, without gapps)
    on matrix.org

![Screenshot_pb_Element_(Riot im)](https://user-images.githubusercontent.com/6158790/102751691-86abd500-4368-11eb-963e-76ef091012e0.png)

**Comment by hko-s** [comment]
See https://github.com/vector-im/element-android/issues/516#issuecomment-683901599 for a workaround

**Comment by bmarty** [comment]
Let's consider it's fixed in Element Android 1.3.16 (see #516)
