### ISSUE TITLE
Duplicate entry in recent apps

### ISSUE THREAD

**Issue by LinAGKar** [vector-im/element-android#2569]
**Describe the bug**
When launch the app, I get two entries for it in the recent list. The first entry seems to be the splash screen, and removing it doesn't seem to do anything. Removing the second entry and then selecting the first one will restart the app.

**To Reproduce**
1. Launch the app
2. View the recently used apps

**Expected behavior**
The app should only be listed once

**Screenshots**
![Screenshot_20201221-155911](https://user-images.githubusercontent.com/3390621/102790626-00ae7f00-43a6-11eb-82b2-e75957f6c4ab.jpg)

**Smartphone (please complete the following information):**
 - Device: OnePlus 8t
 - OS: Android 11

**Additional context**
 - App version and store: 1.0.11 - Play Store
 - Homeserver: Self hosted

**Comment by anoadragon453** [comment]
I've only started seeing this on Android 11.

**Comment by anoadragon453** [comment]
This is still a problem on v1.0.12 from F-droid.

**Comment by anoadragon453** [comment]
This does not seem to be a problem on v1.0.14 \o/

**Comment by LinAGKar** [comment]
This is longer happening for me either, with Element 1.0.17

**Comment by DanielGibson** [comment]
I'm observing the same issue with Element 1.4.20 on Android **12** (it's a Samsung Galaxy A33, "One UI" version 4.1, in case that's relevant)

**Comment by DanielGibson** [comment]
OK, maybe not exactly the same: I'm not seeing the splash screen, but actual conversations, sometimes the same conversation is shown multiple times.
It *might* be cause by opening the app with the icon on the start screen when it's already running in background (visible in the recent apps menu), *however* this doesn't always happen, often (but not always) starting it with the icon just brings the existing window into foreground.
