### ISSUE TITLE
Unspecced msgType field in m.sticker

### ISSUE THREAD

**Issue by auscompgeek** [vector-im/element-android#2580]
**Describe the bug**
Element Android sends an unspecced `"msgType": "org.matrix.android.sdk.sticker"` field in the content of `m.sticker` events.

**To Reproduce**
1. Open the sticker picker.
2. Send a sticker.

**Expected behavior**
No unspecced unnamespaced fields should appear in the content of the resulting event.

**Smartphone:**
 - Device: Samsung Galaxy A20
 - OS: Android 10

**Additional context**
 - App version and store: 1.0.13 - Play Store
 - Homeserver: vovo.id.au

**Comment by bmarty** [comment]
You are right. This field is used internally, but should not be sent. Will fix.

**Comment by bmarty** [comment]
Fixed in 1.0.14
