### ISSUE TITLE
Unsent message stuck at the bottom of the conversation forever

### ISSUE THREAD

**Issue by Totogro** [vector-im/element-android#2582]
**Describe the bug**
For some reason one message in a long conversation could not get through 1h30 ago (as the conversation continued) and is stuck at the bottom of the conversation forever. We are unable to remove it. (Very annoying to the point Element seems not a viable solution for regular people who expect a smooth experience.)

**To Reproduce**
1. Have an unsent message (cannot be reproduced on purpose, i'm afraid...)
2. Try to remove it from a contextual (long press) menu : impossible, no option given
3. Try to restart the app : annoying message still there
4. Try to quit the room and come back with invitation : annoying message still there

**Expected behavior**
We expected to be able to remove this message after a long click on it to get a contextual menu with an option "delete this unsent message"

**Screenshots**
![Screenshot_20201226-163304_Element (Riotim)](https://user-images.githubusercontent.com/33231858/103155411-f6262800-479f-11eb-9460-233d73bf2ac8.jpg)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy A8 (2018)
 - OS: Android 8.0

**Additional context**
 - store : from the link on Element.io website to the Android App in Google Play
 - App Version 1.0.11 [40100112] (G-b847)
 - Matrix SDK version : 0.0.1 (dffdcfe1)
 - olm version : 3.1.2
 - Homeserver: matrix.org

(Thank you for your work)

**Comment by bjonnh** [comment]
I also confirm that I'm hit by the same bug on a Moto G6. It has been like that for months and the only way to remove them is to clear the cache. It happens in at least 10 different rooms. What seem to happen is I try to send a message, connection cut or I switch app for too long, and when I come back  the message sometimes sent, sometimes not appears at the bottom of the screen like that and can't be removed. It also happens on element web, but in that case at least I can edit it and make it empty. It is still there but at least it is not as disturbing.

**Comment by bmarty** [comment]
See #2494
