### ISSUE TITLE
New call timeline is redundant

### ISSUE THREAD

**Issue by notramo** [vector-im/element-android#2586]
Screenshot in #2517
Why is the profile picture and name needed in **each tile**? It's a DM after all.
It should simply display:
- incoming/outgoing
- duration
- call state

**Comment by violoncelloCH** [comment]
I think it'd make sense for groups to see who initiated andmparticipated in a call (once this will be possible in matrix natively) but it's indeed redundant information for 1-1 / DM chats

**Comment by notramo** [comment]
And groups don't have calls yet, only Jitsi widgets.
And it's certainly about DMs.

**Comment by ariskotsomitopoulos** [comment]
I will close this issue, duplicate of https://github.com/vector-im/element-android/issues/2955
