### ISSUE TITLE
"Backup Encryption Key" dont show up on first run

### ISSUE THREAD

**Issue by 6543** [vector-im/element-android#2589]
**Describe the bug**
When you install element & create a account, the "Bachup Encryption" does not schow up.

If you close and open it display it correctly.

I **expect** to see this directly after creating the account.

**Smartphone:**
 - Device: Huawei Nova
 - OS: Android 7.0

**Additional context**
 - App version and store: 1.0.11 - F-Droid
 - Homeserver: obermui.de

**Comment by bmarty** [comment]
The banner will appears once you have some keys to backup, i.e. after sending or receiving a message in an encrypted room.
