### ISSUE TITLE
One-to-one rooms (direct chats) listed under rooms

### ISSUE THREAD

**Issue by jojoob** [vector-im/element-android#2593]
Element android shows some one-to-one chat rooms under rooms instead of direct chats for me. This happens mainly with rooms created by the [mautrx-telegram](https://github.com/tulir/mautrix-telegram) bridge. But since element desktop sorts them correctly I assume it's a problem with element android.

I double checked, the one-to-one rooms only have two members each including me. I did not found a pattern. Around half of the one-to-one rooms are listed under rooms, the other half under direct chats.

**Smartphone**
 - Device: Samsung Galaxy S10e
 - OS: Android 10

**Additional context**
 - App version and store 1.0.13 Play Store
 - Homeserver: own, private homeserver with synapse

**Comment by bmarty** [comment]
A room is considered direct (so appear in the "direct chat" section) if its id is listed in the account data with key `m.direct`.

You can check that in Element Web by typing `/devtools` in any room or in Element Android Settings/Advanced settings/Account data/m.direct.

There is no UI way (any more) to move a room from direct to rooms and vice versa. You can try to edit the m.direct account data from Element Web at your own risk.

However, this is strange that Element Web and Element Android do not have the same algorithm to sort rooms. Maybe something has changed on Element Web and I'm not aware of.

**Comment by Robbi-Blechdose** [comment]
I also have this problem.
When creating a 1-1 conversation, it's listed as a direct chat for me, but as a room for the other person.
It'd be nice if this could be fixed, seeing as it greatly hinders usability.
