### ISSUE TITLE
Opening of large image is broken.

### ISSUE THREAD

**Issue by afranke** [vector-im/element-android#2595]
I sent a large image (20MB file, 25k px wide stiched panorama) from another client to a direct conversation. Clicking on that image to open it on my sides of the conversation loads for a few seconds, then the client just seems to restart. On the other side they just get a black screen. Opening the same image in Fractal works fine.

Element 1.0.11 from F-Droid and LineageOS 17.1 (Android 10) on a Samsung Galaxy S4 on my side.
Element 1.0.13 from the Play store on regular Android 11 on the other side.

Both accounts are on matrix.org.

**Comment by ouchadam** [comment]
fixed with https://github.com/vector-im/element-android/pull/6290 1.4.24
