### ISSUE TITLE
Tapping drawer having more than 1 room in notifications gives "malformed link" error

### ISSUE THREAD

**Issue by olmari** [vector-im/element-android#2605]
**Describe the bug**
When there is multiple notifications for matrix-rooms, when I tap the Element notifications in Android drawer I do get into Element main screen but it always also gives error "Your matrix.to link was malformed".

**To Reproduce**
1. Have notification in 2 or more rooms
2. Click on Element notifications in Android drawer
3. See error

**Expected behavior**
To get into Element main screen without error popping up.

**Screenshots**
![Element_error](https://user-images.githubusercontent.com/5422161/103342030-21a35e00-4a91-11eb-9492-d93a8cb5a4d9.png)

**Smartphone (please complete the following information):**
 - Device: Cosmo Communicator + Samsung Note 8 w/ LineageOS 17.1
 - OS: Android 9 + Android 10

**Additional context**
 - 1.0.13 GPlay
 - Homeserver: hacklab.fi

**Comment by janilahti** [comment]
I can confirm this behavior. OnePlus 7 Pro / Android 10.

**Comment by WarpedOne** [comment]
Confirmed on Samsung Note 8 / Android 9. Single notification goes to that room, Multiple notices gets the 'malformed link' message.

**Comment by WarpedOne** [comment]
Mentioned in https://github.com/vector-im/element-android/pull/2047#issuecomment-688380382
