### ISSUE TITLE
Option to toggle sending read receipts

### ISSUE THREAD

**Issue by integratedfactor8** [vector-im/element-android#2609]
**Is your feature request related to a problem? Please describe.**
There is an option to show read receipts, which can be located by entering the settings menu, then the preferences menu, looking under the timeline subheading. However, I don't think disabling this option disables read receipts being sent. In my opinion, read receipts should be optional for privacy as users may not wish for this information to be revealed to others.

**Describe the solution you'd like**
I would like there to be an option that stops read receipts being sent to other users for everything. Such an option could be combined with the existing option to show read receipts, or it could be a distinct option. This option could function similarly to the send typing notifications option, but instead it would toggle the sending of read receipts to others. This option could also be located in the preferences menu.

**Comment by SimonBrandner** [comment]
This is a long term problem. There is an [issue](https://github.com/vector-im/element-web/issues/2527) on element-web and even an [MSC2285](https://github.com/matrix-org/matrix-doc/pull/2285). I think this is currently waiting for a notification rework as  @turt2live said [here](https://github.com/vector-im/element-web/issues/2527#issuecomment-749102327).

**Comment by turt2live** [comment]
(closing in favour of the element-web issue)

**Comment by xelayz** [comment]
Can't use Element, because they implemented the read receipts feature. For me it make no sense to see if someone read my message and it is a part of the fast pace of the digital age. I really want to use Element, because I like all the other stuff very much. But atm everyone can see when I read a message, this is a huge dealbreaker.
