### ISSUE TITLE
New buttons keep light colors with dark theme

### ISSUE THREAD

**Issue by dalz** [vector-im/element-android#2628]
**Describe the bug**
The buttons to add an attachment, insert an emoji and send the message don't fit with the dark theme anymore.

**To Reproduce**
1. Open a chat
2. Notice the color of the buttons

**Expected behavior**
Buttons have a dark gray/black/green style.

**Screenshots**
![image](https://user-images.githubusercontent.com/25228125/103882866-54260a00-50d4-11eb-9be2-3857244eaeb0.png)

Expected something like:
![image](https://user-images.githubusercontent.com/25228125/103882919-656f1680-50d4-11eb-94c7-ee62b7f307ab.png)

**Additional context**
 - App version and store: 1.0.12 - F-Droid

I don't know if this is intentional; if it is, my humble opinion is that the change should be reverted as I think the old style looks better, especially with the dark theme.

**Comment by gaelledel** [comment]
@bmarty @onurays There's some design changes in the composer coming with the larger voice message project. I have examples for colours on the Dark themes in Figma as part of this project. I suggest we look at this when you @onurays start to work on the new composer?

**Comment by bmarty** [comment]
Fixed in the recent version of the app (at least in 1.1.11)
