### ISSUE TITLE
If you hit the 'home' button during login, login forgets where it is.

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-android#266]
I started to log in, and then hit the home button whilst trying to take a screenshot. On going back into the app, it forgot i was trying to log in (and coughed up a network authentication error) and made me re-enter my login details.

**Comment by bmarty** [comment]
I try to reproduce the pb sevderal times today with the latest version 1.1.3, but without success. Now UIA session is persisted in DB so the app is more robust on this point
