### ISSUE TITLE
UrlPreview doesn't work

### ISSUE THREAD

**Issue by aedis** [vector-im/element-android#2667]
**Describe the bug**
Url preview is not generated after sending the URL (page contains proper tags) in private and room windows.

**To Reproduce**
1. Go to the conversation activity being connected to the server.
2. Paste the url (the fully qualified one).
3. Send the message.

**Expected behavior**
Url preview should be generated.

**Screenshots**
Not needed

**Smartphone (please complete the following information):**
 - Device: Samsung S7
 - OS: Android 8.0

**Additional context**
 - App version and store: Google Play, 1.0.13
 - Homeserver: matrix-synapse-1.25.0 with properly configured url_preview and blocklist options, all deps are installed for url preview support on the server-side.

I can support here with additional logs, analysis - I'm able to build the app from the source. Just I need the info on what I should look for. The issue is visible in the app built from the source also.

It worked only once - I do not why.

**Comment by laszlovl** [comment]
Are these rooms using encryption? If so, this is a dupe of #2555

**Comment by aedis** [comment]
Yep, this is the case. I'm closing this as a dup of #2555.
