### ISSUE TITLE
Play animated Stickers (gif)

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-android#2668]
**Problem**
Stickers may be animated files, e.g. gif files, apng files, etc.
Animated images like these can usually (only) be played, by tapping to "open" them, presumably in a webview.
In case of a sticker with MIME type image/gif, the app recognizes the animated nature of the file and shows a play button overlaid on the sticker. However this isn't clickable, nor does the animation play.

**Proposed Solution**
Animated stickers should be supported. The support should at least match the regular file sending of the same file type. Inline playback would be preferable, perhaps similar to Element Web/Desktop, which can play on mouse hover, which could translate to tap to play the longer of one loop, loop for a minimum amount of time, or similar. See also #1160.

**Comment by binarydad** [comment]
I would love this as well. Rocket.Chat has this and it's nice, especially for my kids.

**Comment by kojid0** [comment]
I think this is not supported serverside, so the android dev can't fix it. I guess it's rather an issue for https://github.com/matrix-org/matrix-doc/issues, but I'm not 100% sure.

**Comment by HarHarLinks** [comment]
> I think this is not supported serverside

This is currently working on element-web/desktop, so I don't see how it could be a server/protocol issue. I think this would be working on android, if either stickers could be tapped for fullscreen viewing as normal pictures are, or just play gifs inline.

**Comment by HarHarLinks** [comment]
Most gif stickers now autoplay indefinitely in 1.1.11
- there is no download confirmation for what might be a huge gif
- cant pause gif stickers
- no (downloading) animation, just a black space and eventually the sticker appears and starts playing
- I have at least 1 gif sticker that only plays once and does not loop on android, but does loop on desktop (i use the hover-to-play-gifs setting on desktop)

**Comment by HarHarLinks** [comment]
You are correct, I can confirm that. I am no longer certain if my assessment for 1.1.11 was correct, however I can say that animated stickers work very nicely in the SchildiChat fork of Element Android.

**Comment by binarydad** [comment]
I checked out Shildichat. It does seem nice, in terms of the GIFs and overall layout compared to Element. That name and icon for Shildichat is just... yeah.

Really wish Element would support at least the option for enabling animated GIFs by default.

**Comment by kreaninw** [comment]
GIF images/stickers should be automatically played by default as:

1. It's the default behavior on the desktop app. Changing this won't benefit mobile users in any way, so it should stay the same across all the platforms.
2. It's the default behavior on other popular messenger apps including, Whatsapp, LINE, Facebook Messenger, and even Discord. Therefore, it should or better be automatically played in loops by default. This would help a lot for people to migrate to Element as this is the expected behavior across most if not all messenger apps.

**Comment by HarHarLinks** [comment]
> Changing this won't benefit mobile users in any way

downloading gifs can be fairly costly since they're quick to be a couple MB large. :shrug: clearly there should be an option to disable autoplay (and thus autodownload), plus another option to switch behaviour based on cell or wifi connectivity.

**Comment by binarydad** [comment]
I send my kids GIFs all the time. It's annoying for them (and me) to have to play each one. 

Would LOVE an option for toggling this.

**Comment by HarHarLinks** [comment]
> I send my kids GIFs all the time.

Please note that this issue is about **animated Stickers** (e.g. like [this](https://github.com/maunium/stickerpicker)) in particular, not general GIF playback (automatic or otherwise).

**Comment by DUCKCHI** [comment]
Animation stickers can be played on element-android. If you modify the source of maunium-stickerpicker a little, you can upload webp, gif, and use animation stickers (checked on element-web).

https://duckchi.github.io/stickerpicker/web/
example

Considering that gif automatic playback is possible in schildichat, animation sticker playback is also possible on element-android by simply reflecting the automatic playback code on the sticker.
