### ISSUE TITLE
Publish new versions to f-droid

### ISSUE THREAD

**Issue by rakshazi** [vector-im/element-android#2698]
Hello,
F-Droid contains only *.12 version for now.

Could you publish new versions, please?

**Comment by Bubu** [comment]
I submitted .14 there a few days ago. I don't know when it'll be published though.

**Comment by rakshazi** [comment]
Seems something wrong with f-droid repo, because 1.0.14 was built on 21 Jan O_o

Created a topic on f-droid forum: https://forum.f-droid.org/t/element-new-version-not-available-on-f-droid/12430

**Comment by dessalines** [comment]
Posted this elsewhere, but like a lot of other android apps like newpipe, it'd be a good idea to host your own f-droid repo, then you won't have to wait days for f-droid to do their releases, it'll be on your own schedule.

**Comment by MPeti1** [comment]
That would probably be the best, but do we know why is it taking so long for F-droid (for every app)?

**Comment by dessalines** [comment]
They build all their apps from source on a schedule, and it takes a long time. 

When you host your own repo, you can throw whatever APKs you like in a directory.

**Comment by rakshazi** [comment]
@bmarty could you think about the idea of your own f-droid repo, please? NewPipe example is a good one - they still post updates to main f-droid repo, but have their own repo with very fast releases of new  versions

**Comment by rakshazi** [comment]
F-droid repo now has 1.0.14 :tada:
