### ISSUE TITLE
"Discovery" screen doesn't always show shared emails

### ISSUE THREAD

**Issue by AndrewFerr** [vector-im/element-android#2708]
**Describe the bug**
When viewing Settings->General->Discovery after not having viewed it for a while, shared emails will appear as unshared. Exiting the page and immediately re-entering it fixes the problem.

This happens is because of mishandling of expired peppers for the identity server. When a lookup request to an identity server responds with `M_INVALID_PEPPER`, Element Android correctly asks the server for a new pepper, and retries the lookup. However, the retry uses the original, invalid pepper instead of the newly-retrieved one.

**To Reproduce**
1. With any client, add some email addresses to your Matrix account, connect to an identity server, and mark some of those email addresses as shared
2. Wait a few hours
3. In Element Android, view Settings->General->Discovery
4. Notice that "Discoverable email addresses" shows none of your email addresses as shared
5. Exit and re-enter the Discovery page
6. Notice that your shared email addresses now properly appear as shared

**Expected behavior**
Shared emails (and any other 3PIDs) should appear as shared without having to exit and re-enter the Discovery page.

**Additional context**
 - 1.0.13 - F-Droid and 1.0.15 from develop branch
 - Homeserver: self-hosted homeserver
 - Identity server: self-hosted ma1sd

**Comment by bmarty** [comment]
You open an issue, then you fix it in a PR, wonderful! Thanks a lot!

I'm glad I set up a `canRetry: Boolean` parameter to avoid infinite loop due to this bug!

**Comment by bmarty** [comment]
Fixed in #2709 so in Element Android 1.0.15
