### ISSUE TITLE
Jitsi widget: can't join calls (invalid token error?)

### ISSUE THREAD

**Issue by Moto-John** [vector-im/element-android#2729]
**Describe the bug**
Trying to join calls from element android open doesn't work. It opens an overlay from jitsi for a fraction of a second saying disconnected and it them immediately returns back to the room

**To Reproduce**
1. Start a call on a group or add the jitsi widget.
2. Try to join from the audio or video options

**Expected behavior**
Join the meeting

 - Device: Mi 9T Pro (also tested on a Mi 10 with MiUI 12)
 - OS: Android 11
 - App version and store [e.g. 1.0.14 - Play store]
 - Homeserver:  [matrix.org plus my own homeserver]

I can apparently join calls just fine from element-web so the homeserver or my internet isn't the problem. Also, I tried to run a catlog on my device and found these error that may be (probably are) related to the error. 
![Screenshot_20210127-101936](https://user-images.githubusercontent.com/25955098/106023124-30e8ec00-60cf-11eb-9378-9d58fddcdea8.png)
![Screenshot_20210127-103335](https://user-images.githubusercontent.com/25955098/106023134-321a1900-60cf-11eb-9348-ac70c8e353b3.png)

**Comment by IdmFoundInHim** [comment]
It has happened for users joining Element (my homeserver) from 26 Jan 2021 on. The last person to join Element that can get on the call joined 5 Jan 2021. It appears to be a regression in that range, but my sample size is very small. The twist is that it happens on iOS as well

**Comment by root562** [comment]
In my case I am using version 1.0.14 and on Matrix.org accounts. I tested three participants. Two on android phone(Android version 10) and one on web. On android phone when I try Jitsi call, another white screen displays "Connecting you to your meeting". Then the screen close, nothing happen. This feature was working well before on Riot. Integration enabled on both phones.

**Comment by mahmoudajawad** [comment]
I was just testing Jitsi integration and got the same issue reported by OP. I can start and join Jitsi calls from web, but can't start or join Jitsi calls from either my Android or iOS devices. 

This is what I get before the screen becomes white and unresponsive:
![image](https://user-images.githubusercontent.com/316734/106888613-40d08380-6700-11eb-9da2-616a107f34b8.png)

**Comment by bmarty** [comment]
Hello, thanks for reporting!
This is fixed now, we have made some changes server side.
Please feel free to re-open the issue if you still have the problem.

**Comment by mahmoudajawad** [comment]
I can confirm this issue is resolved on Android but not iOS. Do I need to open a separate issue for this in iOS repo or that we can track the same here?

**Comment by mahmoudajawad** [comment]
@bmarty, just in case you weren't notified earlier.

**Comment by bmarty** [comment]
Yes, thanks, we will fix that in the coming days

**Comment by mahmoudajawad** [comment]
@bmarty i just tested Jitsi again on iOS and I was able to start and join Jitsi calls from my iOS device as well.
