### ISSUE TITLE
Calls don't work from Smartphone to Linux (Flatpak)

### ISSUE THREAD

**Issue by MarkSmz** [vector-im/element-android#2730]
#### General information

- **Version (Flatpak on OpenSuse Leap 15.2)**: 1.7.17
- **Version (Android 10)**: 1.0.12 - F-Droid
- **Version (iOS 14.4)**: 1.1.3
- **Homeserver**: matrix.org

**Describe the bug**

Hello,

I have the problem that audio/video calls don't work from smartphone (Android and iOS) to desktop (Flatpak Linux), but from smartphone to Web browser and Windows desktop. When you answer the call, the smartphone tries to connect all the time, but the connection is never established.

I hope you can solve the problem.
Thanks.

**Screenshots**
![Screenshot_20210127-190836](https://user-images.githubusercontent.com/49169537/106034825-ae166000-60d3-11eb-9baf-2aad994f6a2a.png)

**Comment by SimonBrandner** [comment]
@MarkSmz If you upgrade to 1.7.18 on desktop, everything should work.
