### ISSUE TITLE
Add new android notification features (Chat bubbles, priority conversations)

### ISSUE THREAD

**Issue by 33Fraise33** [vector-im/element-android#2734]
**Is your feature request related to a problem? Please describe.**
When opening the android notification settings it gives a headsup about missing features:

> "Element (Riot.im) doesn't support most conversation features. You can't set a conversation as priority, and conversations won't appear as floating bubbles"

This is a native android feature described working here: https://www.androidcentral.com/how-use-chat-bubbles-android-11

**Describe the solution you'd like**
I'd like this native feature to be implemented so chat bubbles can be used. This is not to be confused with #2388 , #1805 and #979. They are talking about the chat view in app, this is a bubble overlay showing over all apps like Facebook messenger did first. 

**Describe alternatives you've considered**
None existant. This makes quickly looking something up and copying it much easier. Also quickly jumping to a chat while doing something else. 

**Additional context**
/

**Comment by AquaWolf** [comment]
I also want this feature. I looked a bit in the code perhaps I can program this but still need some more orientation in the code.

**Comment by AquaWolf** [comment]
Added some lines to enable shortcuts and therefore priority conversation but not sure if I missed something:
https://github.com/vector-im/element-android/commit/dd7c264483bfd8ff4dba81343b167d267957826a

**Comment by hanthor** [comment]
I wonder why the bubbles don't work. I have noticed not many Android apps implement the bubbles feature.

**Comment by Peterkmoss** [comment]
Any news on this? I would really like to see chat bubbles :)

**Comment by ShadowJonathan** [comment]
Element-web recently got chat bubbles, so i expect Design to pick up on it and give it to Mobile apps soon

**Comment by kevincox** [comment]
@ShadowJonathan I think you are confusing two different issues. This is talking about Android Chat Bubbles which is about using the system chat-app overlay feature so that Element is always on-screen. The [feature recently added to Element Web](https://github.com/matrix-org/matrix-react-sdk/pull/6291) is about changing the look of the messages inside of Element.

**Comment by ShadowJonathan** [comment]
Oh whoops, yeah, i dun goofed for a second 😅

**Comment by AquaWolf** [comment]
Sorry for this long time not working on this issue actually, I will give this a next try because I really want this feature. I will clean up my PR and try to get these chat bubbles working. I cannot give any timeline for this does anybody know how to ping to review my PR after my clean up? I tried to contact @bmarty in matrix.org but I didn't get any response from him :(

**Comment by AquaWolf** [comment]
Because of native Android 11 chat bubbles I need to implement some kind of view for the chat window in the system overlay any advise for a ui for that?

**Comment by AquaWolf** [comment]
Thank you @bmarty for reviewing and merging happy to see this feature in the App 👍

**Comment by Peterkmoss** [comment]
Does this mean that bubbles are still missing?

**Comment by Peterkmoss** [comment]
No, this is not internal to the app. This is an android feature - just as @kevincox mentioned [here](https://github.com/vector-im/element-android/issues/2734#issuecomment-895144745)

**Comment by SimonBrandner** [comment]
Ah, you're right I got confused and thought the PR added the Android chat bubbles and I thought you were asking about the bubble-themed chat, sorry! :sweat_smile: In that case, yes, this should be re-opened/new issue should be opened. I prefer the latter, personally

**Comment by AquaWolf** [comment]
Yep you're right there must be implemented some special Activity UI for Android chat bubbles. Would be nice to reopen or split this issue just to keep in mind that the chat bubbles are requested.

**Comment by abmantis** [comment]
@AquaWolf there's already an issue for chat bubbles: https://github.com/vector-im/element-android/issues/1124 and also https://github.com/vector-im/element-android/issues/1722
