### ISSUE TITLE
404 on play store

### ISSUE THREAD

**Issue by remygrandin** [vector-im/element-android#2737]
Hi,

It seem the elemnt app is not available via https://play.google.com/store/apps/details?id=im.vector.app
It return a 404

Best regards,

**Comment by Siruux** [comment]
Element has been suspended from the Google Play Store

**Comment by ShadowJonathan** [comment]
Tweet here: https://twitter.com/element_hq/status/1355290296947499013

**Comment by dessalines** [comment]
It would be a *really* good idea to host your own f-droid repo. Then everyone could get fast updates on your own schedule.

**Comment by je-vv** [comment]
But if using a custom f-droid repo, please offer at least one apk under the same official f-droid policies, no closed source components, no google push stuff, and so on...  Thanks !

**Comment by bmarty** [comment]
It's back now
