### ISSUE TITLE
Invisible or almost-invisible text with system theme

### ISSUE THREAD

**Issue by lnicola** [vector-im/element-android#2738]
**Describe the bug**
I use the system theme and an app to automatically switch it (Auto Dark Theme). After a system theme switch, the text in Element is invisible, but toggling the Element theme between system and dark/light and back fixes it. I think Element doesn't notice that the text foreground color has changed.

I also noticed this with the bottom notification in the final step of the cross-signing flow. There's a "Finish >" step at the end and if you go back (cancel), the new session will remain inconsistent.

**Screenshots**

White on white text:
![image](https://user-images.githubusercontent.com/308347/106353251-d380b500-62f1-11eb-86e4-8c1c7fbac094.png)

Gray on gray text:
![image](https://user-images.githubusercontent.com/308347/106353597-64f12680-62f4-11eb-9f08-85be820ecb05.png)

**Smartphone (please complete the following information):**
 - Device: OnePlus 6T
 - OS: Android 10

**Additional context**
 - App version and store: 1.0.14 - Play Store
 - Homeserver: N/A

**Comment by parsifallo** [comment]
I have the same problem. Need to close the application every day twice (day to night, night to day) :(

**Comment by lnicola** [comment]
@parsifallo wait, does closing the app actually fix it for you?

**Comment by parsifallo** [comment]
Sure. If light/dark mode switched, I swipe to close in Android to close the application. After opening Element again, the font color ist correct

**Comment by lnicola** [comment]
Ah, that's great. I'm sure I tried it, but I think my phone only closes the apps if I wait a couple of seconds before restarting them.

**Comment by bmarty** [comment]
Fixed in next release 1.1.7
