### ISSUE TITLE
Use UnifiedPush for push notifications

### ISSUE THREAD

**Issue by vurpo** [vector-im/element-android#2743]
Opening an issue about this here for good measure. The recently started UnifiedPush project (#unifiedpush:matrix.org) is an Android protocol and library for apps to be able to receive distributor-agnostic push notifications. Element Android could use the UnifiedPush library to still receive push notifications from FCM, but also alternatively from other non-Google distributor systems that the user can have installed on their device (currently available are Gotify, a server and app that receives push notifications via a websocket, and NoProvider2Push, a peer-to-peer system). This would make it possible to have push notifications without depending on Google services or libraries.

The UnifiedPush library comes in two variations: the FCM-added version of the library, which basically comes with the FCM distributor built into the library (so a user doesn't need to do anything other than install the app to get FCM notifications), and the main version of the library, which doesn't come with FCM embedded (so a user has to separately install the FCM, Gotify, or other distributor as an app on their phone to get push notifications).

These two versions of the library could be used in the Google Play version and F-Droid version of the app respectively, to be able to publish an easy-to-use no-setup-needed version of the app to Google Play, and a version that doesn't depend on any Google code to F-Droid.

**Comment by p1gp1g** [comment]
https://github.com/vector-im/element-android/pull/3448

**Comment by bmarty** [comment]
@vurpo your issue description is super clear. I will get inspired from it to write a documentation about UnifiedPush and it's configuration in the Element Android project. Thanks!

**Comment by MayeulC** [comment]
For discoverability (and perhaps search engine referencing), the link to the current doc is: https://github.com/vector-im/element-android/blob/develop/docs/unifiedpush.md

**Comment by ildar** [comment]
Anyone seen a descent guide how to set it up?

**Comment by vurpo** [comment]
To set it up, install one of the UnifiedPush distributors (see unifiedpush.org) and go into Element's settings to choose the distributor you have installed. I'm not sure if F-Droid has updated to this version yet though.

This setup process is extremely easy, but since people keep asking about it should probably have some user facing instruction somewhere?

**Comment by djmaze** [comment]
Yes, F-Droid already has this version. I had ntfy already installed and upon restarting Element, I was asked how I wanted to be notified in the future. Really easy.

![](https://user-images.githubusercontent.com/3940906/172798568-a18c2de8-bcdf-49d9-a7ee-8d53335353ec.png) 

(image from the pr at #6228)
