### ISSUE TITLE
Links to communities don't work

### ISSUE THREAD

**Issue by mahmoudajawad** [vector-im/element-android#2744]
**Describe the bug**
Links to communities do not work on Android app.

**To Reproduce**
1. Find a community like such as "+talkingnews:matrix.org" (within the app) or "https://matrix.to/#/+talkingnews:matrix.org".
2. Nothing happens.

**Expected behavior**
To redirect user to the community page.

**Smartphone (please complete the following information):**
 - Device: oneplusone 3t
 - OS: e.foundation Rom

**Additional context**
 - App version: 1.0.12 (from their degoogled native app store)
 - Homeserver: ems.host

**Comment by mahmoudajawad** [comment]
Closing as communities are taking a flight from Matrix, Element.

**Comment by bmarty** [comment]
Thanks for the follow up!
