### ISSUE TITLE
Latest Element not installed using F-Droid

### ISSUE THREAD

**Issue by aplatypus** [vector-im/element-android#2764]
**Describe the bug**
When I click install on F-Droid for "riot.im" on Android v10 nothing installs.  Riot.im is the only software that comes back for "Element".  However the F-Droid packags says v0.9.9.

While the F-Droid web site cites v1.0.14, 31 Jan 2021 as the current version.

**To Reproduce**
1. Open F-Droid on an Android phone
2. Click on 'Search'
3. Enter either "Element", "Matrix" or "Riot"
4. Click on the matrix client app
5. Click on Install
6. Someting happens and ...
7. MEssage "not installed" comes back.
8. Click on Version
9. Shows 0.9.9

**Expected behavior**

1. Find "Element" in the F-Droid catalogue, not out-of-date names
2. Find latest version per release notes on element.io web site and F-Droid on-line catalogue
3. Some kind of reason or error message if there was an install problem

**Smartphone (please complete the following information):**
 - Device:  Samsung A70
 - OS: Android 10

**Additional context**
 - F-Droid: v1.10

**Comment by violoncelloCH** [comment]
did you update the local f-droid repository (by pulling down to refresh in the app list)?

**Comment by aplatypus** [comment]
@violoncelloCH ... Thanks.  No the refresh failed with some error about too many mirrors.  ???

So I fixed everything by uninstalling F-Droid and Reinstalling it.  Element is now installed  :-)
