### ISSUE TITLE
Join room by alias other federation error

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/element-android#2778]
Step to reproduce:

From a matrix.org account try to join this room #cloud-devroom_testing4:fosdem.org

=> android displays a "This room is not accessible at this time", and doesn't give you an option to try and join?

**Comment by BillCarsonFr** [comment]
It is due to an uncaught exception in the get directory visibity task -> causing the all task to fail instead of returning a cannot preview room error

**Comment by bmarty** [comment]
Fixed in 1.0.17
