### ISSUE TITLE
Collapse ACL change Events

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-android#2782]
Server ACLs can make for unpleasant reading. Like web, we should hide the details by default.  Users can go into View Source if they really want to see the gory details

**Comment by bmarty** [comment]
This should only be the case if you enable the developer mode.

**Comment by bmarty** [comment]
Ok, now I understand that several ACL events are in the timeline and this is ugly. We have the same pb on Element Web:

<img width="277" alt="image" src="https://user-images.githubusercontent.com/3940906/107046888-71c7bb80-67c7-11eb-97ef-b8173b9ebafa.png">

**Comment by anoadragon453** [comment]
Collapsing into `moderator changed the server ACLs for this room 13 times`, analogous to how Element clients handle displayname changes, sounds like a plausible route.

**Comment by SimonBrandner** [comment]
I am not sure how much effort this requires but it might be worth doing this now because of the recent spam attacks. Element Web did this recently

**Comment by bmarty** [comment]
This is clearly something to do one day, and this should not be too hard to do it, but the priority is not high enough to do it now.

**Comment by bmarty** [comment]
On Element Web we can see this:

<img width="572" alt="image" src="https://user-images.githubusercontent.com/3940906/152601741-7d4a06df-423a-4067-a9f4-212e114a1bb7.png">

We already have the mechanism to collapse similar Events, it's should not take long to do it for ACL Events

**Comment by mnaturel** [comment]
Hi @bmarty , do you know how server ACLs changes events can be generated in a room for testing purpose ?

**Comment by mnaturel** [comment]
Hi @amshakal , my PR is now ready for design review. You can see how it renders in #5249 .
