### ISSUE TITLE
Support UnifiedPush for google-free push notifications

### ISSUE THREAD

**Issue by uumas** [vector-im/element-android#2784]
Having Element sync in the background isn't very efficient but it's currently the only way to get push notifications without google play services. [UnifiedPush](https://unifiedpush.org/) is an open implementation for push notifications which isn't dependent on google. Documentation is available [here](https://unifiedpush.org/developers/android/)

**Comment by SimonBrandner** [comment]
Seems like a duplicate of [#2743](https://github.com/vector-im/element-android/issues/2743)

**Comment by uumas** [comment]
Huh, i tried searching for unified and push but didn't find that for some reason. Thanks!
