### ISSUE TITLE
Audio messages

### ISSUE THREAD

**Issue by Gushtera** [vector-im/element-android#2795]
Hello guys,
do you plan to implement audio messages?

**Comment by SimonBrandner** [comment]
Duplicate of [#29](https://github.com/vector-im/element-android/issues/29)

@Gushtera Yep, I believe this is planned

**Comment by SimonBrandner** [comment]
@Gushtera Yep, I believe this is planned

**Comment by bmarty** [comment]
Yes, dup of #29, it's coming soon(tm)
