### ISSUE TITLE
light UX version of RiotX dedicated to androidTV?

### ISSUE THREAD

**Issue by Thatoo** [vector-im/element-android#28]
Hello,

If possible, it would be nice to have a light UX version of RiotX dedicated to androidTV.

It is possible today to install and use Riot for android with a mouse and keyboard on androidTV (thanks to AptoideTV). I know receiving voice and video work. I couldn't try if others can hear/see me because I don't have webcam for my TV but I read that Android has some webcam's drivers pre-installed. I'll try when I can. Did someone try?

However, I think it's not handy to do so. What I have in mind is a simpler version of it. It is mostly a question of hiding options of the android app.

It would only allow to make and answer calls in direct chat. Salon would not be listed (hidden, not accessible inside RiotX-androidTV), only direct chat would appear! And when we enter one of them, only the two buttons of voice and video call would be there (no chat room, no keyboard needed).

Only notification of calls would be needed and would appear on top of screen while TV is on (used) with two options answer/not answer.

If it's possible, it could even ring and switch on the screen of TV when a call is incoming but would need to switch off again the screen if the call is not picked (to avoid consuming electricity).

What do you think?

**Comment by jmartinesp** [comment]
I'm sorry, but there are no plans to officially support Android TV in the near future, and making those modifications probably requires a lot of work that we can't approach at the moment. I'll close the issue for now, but we can always re-visit if the situation changes.

**Comment by Thatoo** [comment]
I guess, @jmartinesp, that it is more a client like "Element Call" that would be good on android TV.
