### ISSUE TITLE
Publish new versions on F-droid or provide own f-droid repo

### ISSUE THREAD

**Issue by rakshazi** [vector-im/element-android#2802]
**Describe the bug**
F-droid has 1.0.14 as latest version

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Samsung S6]
 - OS: [e.g. Android 6.0]

**Additional context**
 - App version and store [e.g. 1.0.0 - F-Droid]
 - Homeserver: [e.g. matrix.org]

**Comment by rakshazi** [comment]
Related: https://github.com/vector-im/element-android/issues/2747

**Comment by emorrp1** [comment]
1.0.17 has now built (skipping 15,16), should be published shortly https://f-droid.org/wiki/page/im.vector.app/lastbuild_40100170
