### ISSUE TITLE
Improve the status of send messages (sending, sent, received, failed)

### ISSUE THREAD

**Issue by giomfo** [vector-im/element-android#2804]
When sending a message in Element, it’s possible for the sent message to be in several states such as sending, sent, received, failed to send. Today, we have different implementations across web, iOS & Android and we’d like to make them consistent across all platforms.

We present here the new design to expose progress states on Android:
   - When sending or encrypting a message: Display a hollow tick at the bottom right of the message (In case of a multi-line message, the tick is aligned with the last line)
   - **The text color is always black (we remove the light grey color (and other colors) for local echos)**
   - When a message is sent: Display a filled tick
   - When a message has been read: Overlay the read receipt, also ‘clearing’ the tick states. In effect, this means that once a message has been sent & read, it doesn’t need to be decorated any more
![image](https://user-images.githubusercontent.com/8969772/107432778-bab1a400-6b28-11eb-88ae-43fcc0af5cc9.png)

   - When a message failed to sent: Display an exclamation mark (on a red background) where the tick lived. (see #2803 to handle the failed messages)
![image](https://user-images.githubusercontent.com/8969772/107432819-c8ffc000-6b28-11eb-9d49-8747e75ae388.png)

   - In case of an attachment (image/video/file...), display a loading wheel at the bottom right during the media encryption and its upload (the media is slightly gray):
![image](https://user-images.githubusercontent.com/8969772/107432904-e59bf800-6b28-11eb-8ef4-551c60c3ad05.png)
On long Press the spinner icon > show dialog to cancel the upload
![image](https://user-images.githubusercontent.com/8969772/107433074-272ca300-6b29-11eb-982a-c7c74e260a0a.png)

When this attachment is actually sending display a hollow tick, replaced by a filled tick when this is done:
![image](https://user-images.githubusercontent.com/8969772/107432963-f9475e80-6b28-11eb-9904-2faed3e100f0.png)

**Comment by duncanturk** [comment]
I think showing a tick while it is sending may be confusing.
The currently used clock symbol (or anything that indicates that it is not done sending) may be better and more intuitive.

**Comment by mullenkamp** [comment]
What about when a message has been received but not read yet?
This is the only status functionality that seems to be missing from Element.
For example, Signal (and WhatsApp) has one empty check mark if the message has been successfully sent to the server, a second empty check is added when the recipient has received the message, and both checks become bold once the recipient has read the message.
Or am I missing something in the GUI?

**Comment by ericdecanini** [comment]
It looks like this has already been done. I can see that this issue is from February 2021 so my current understanding is that the work is done and this issue just hasn't been closed. Please correct me if I'm wrong though.

A little investigation would be great for us to do to check that this is really the case and that we have parity with the other platforms

**Comment by bmarty** [comment]
Yes, this is fine to close it I think.

**Comment by jyotprajapati** [comment]
@bmarty  @ericdecanini 
I can't find the implementation for the received part as pointed out by @mullenkamp.

**Comment by mullenkamp** [comment]
I think they simply ignored my comment...

**Comment by ShadowJonathan** [comment]
Currently there is no possible mechanism in matrix to determine if a person has received but not read a message yet.

**Comment by mullenkamp** [comment]
> Currently there is no possible mechanism in matrix to determine if a person has received but not read a message yet, only that it has been sent and acknowledged by your homeserver, after which it will queue it for sending to another homeserver (like an email server).

Thanks for the response. I thought that might be the case, but I originally wanted to ask the question to clarify this.
