### ISSUE TITLE
How to listen to a special event such as m.presence? [SDK] 

### ISSUE THREAD

**Issue by SAEEDHONARI** [vector-im/element-android#2812]
How to listen to a special event such as m.presence in element-android

**Comment by bmarty** [comment]
"m.presence" events are not yet handled by the Matrix SDK, it's still on the TODO list.

**Comment by SAEEDHONARI** [comment]
> 
> 
> "m.presence" events are not yet handled by the Matrix SDK, it's still on the TODO list.

My problem was solved, I called the relevant API directly

**Comment by bmarty** [comment]
Ok, thanks for feedback. Let's close this issue and keep only #70
