### ISSUE TITLE
Voice calls and Element 1.0.18

### ISSUE THREAD

**Issue by bahur142** [vector-im/element-android#2818]
**Describe the bug**
Small problem with voice calls when caller uses Element 1.0.18 and receiver uses older version of Element, eg. 1.0.16

**To Reproduce**
1. User A installs Element 1.0.18
2. User A calls user B with Element 1.0.16, 17
3. Call is successful
4. User A ends the call
5. User B receives message like in the screenshot

**Expected behavior**
When user A ends the call and returns to the chat window, user's B device should also returns to the chat window.  

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/30805725/107758966-4a756f00-6d30-11eb-9758-eaa4d8aec08e.jpg)

**Smartphone (please complete the following information):**
 - Device: User A - Xiaomi Mi4
                User B - Xiaomi Mi6
 - OS: User A - Android 6.01
          User B - Android 9

**Additional context**
 - App version and store: 
 User A - Element 1.0.18 from BuildKite
 User B - Element 1.0.16 from Play Store
 - Homeserver: my own 1.26.0

I suppose this happens because of the new Jitsi library in version 1.0.18
If the two users are with version 1.0.18 the problem does not exists.

**Comment by bmarty** [comment]
Thanks for reporting. I assume we will fix issues only if all devices use the latest version of app.

**Comment by bahur142** [comment]
Yes, this is important all devices to be the same version for the sake of the overall user experience with the app. 
I reported this only so you can be aware. And thanks for your efforts too!

**Comment by karolyi** [comment]
So with 1.1.0 out, according to my tests it still doesn't support TURN servers and relay candidates.

I could only make calls with STUN servers and UDP hole punching: tracked calls from mobile to browser with `about:webrtc` in Firefox/Librewolf, no relay offers from the mobile side, while I had them on the browser side.

Is this intentional?
