### ISSUE TITLE
Use a ktlint Gradle plugin to automate ktlint use instead of requiring manual downloading of the ktlint binary

### ISSUE THREAD

**Issue by erikhuizinga** [vector-im/element-android#2820]
**Is your feature request related to a problem? Please describe.**

The contributing guidelines could be simpler by not requiring manual downloads and runs of the ktlint binary. This can be cumbersome for new and existing contributors. Automating this removes the need for manual downloads and runs of binaries.

Specifically here: https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#ktlint

**Describe the solution you'd like**

Use a Gradle plugin to run ktlint, e.g.

- https://github.com/JLLeitschuh/ktlint-gradle/ - just for ktlint, easy to configure
- https://github.com/diffplug/spotless - for ktlint and many more
- There may be other solutions: https://github.com/search?q=ktlint+gradle

This has the added benefit that it can be easily run on CI by simply running a Gradle task, which is likely what already happens for other build steps like Android lint. The two suggested Gradle plugins have the added benefit that it puts the ktlint version used under version control: various versions of ktlint have proven to behave differently, so making the correct and desired ktlint version in VCS has the benefit of knowing that every machine runs the same version.

Also, currently ktlint is in .gitignore, but it could be removed there if integrated from Gradle.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by bmarty** [comment]
Started working on that in #3957 , but still have some trouble to understand why the result are not the same between 2 consecutive run.
