### ISSUE TITLE
Log-in syncing never completes.

### ISSUE THREAD

**Issue by amos3vt** [vector-im/element-android#2822]
I initially made an account through the Android application. When I try to log into the same account through the desktop app, it never gets past the "syncing" screen. (I let it run for a few hours).

I then made a new account through the desktop application then tried logging in through the Android application. Again, it remains stuck at the "syncing" screen.

Device: OnePlus 5t
OS: OxygenOS

**Comment by Glotzon** [comment]
I can confirm the same issue on Android 10, as well as Android 8, both running version 1.0.14 from droid.
Interestingly enough, the same issue occurs on version 1.7.20 on Linux, hence I am unsure this being a purely client issue, or rather an issue with the verification process through the server,
My observation:
- On a newly installed synapse system (yes, I killed my trusted synapse server as I anticipated me having a DB issue), the first client connects, in my case running on Linux.
- Any subsequent connection is seen by the running client, the connection appears with its ID on the already connected system, but the login process never completes on the new client. There is no verification notification on the connected client.

The server is good, connecting to my homeserver using Ditto Client works as expected, a verification process on the originally connected client appears.

Devices: Sony XA2 Ultra, Sony X10Plus, Linux Desktop/Laptop PCs
Versions: Android 10, Android 8, Linux 5.10.14

**Comment by KnightWhoSaysNeeeowWumPing** [comment]
With one of my Android devices I am experiencing the same issue - the desktop clients run just fine.

*Device that does **not** work:*

Device: Moto G9 Play (XT2083-3)
Version OS: Android 10 (Stock)
Version Clients: 1.0.12 (F-Droid), 1.0.14 (F-Droid), 1.0.15 (Google Play)

*Works well with the following devices:*

Device: Samsung Galaxy A3 2017 (SM-A320FL)
Version OS: Android 9 (LineageOS)
Version Clients: 1.0.14 (F-Droid)

Device: Samsung Galaxy A3 2017 (SM-A320FL)
Version OS: Android 8 (Stock)
Version Clients: 1.0.16 (Google Play)

**Comment by binaryfever** [comment]
Experiencing same issue both in the android app and linux desktop client.  element web works fine.

Device: Samsung Note 20 Ultra
Version OS: Android 11 (stock)
Version Client: 1.0.15 (Google Play)

Device: Linux PC
Version OS: Fedora 33
Version Client: 1.7.20

**Comment by penn5** [comment]
> With one of my Android devices I am experiencing the same issue - the desktop clients run just fine.
> 
> _Device that does **not** work:_
> 
> Device: Moto G9 Play (XT2083-3)
> Version OS: Android 10 (Stock)
> Version Clients: 1.0.12 (F-Droid), 1.0.14 (F-Droid), 1.0.15 (Google Play)
> 
> _Works well with the following devices:_
> 
> Device: Samsung Galaxy A3 2017 (SM-A320FL)
> Version OS: Android 9 (LineageOS)
> Version Clients: 1.0.14 (F-Droid)
> 
> Device: Samsung Galaxy A3 2017 (SM-A320FL)
> Version OS: Android 8 (Stock)
> Version Clients: 1.0.16 (Google Play)

Did you actually clear data on all of them, so that you are *certain* that it's caused by the firmware rather than just a random condition at first start?

**Comment by KnightWhoSaysNeeeowWumPing** [comment]
I'm not quite sure what you mean by 'clear data'. Do you mean clearing cache and data for the element app from the system settings menu?
I tried it multiple times - always uninstalling the app and reinstalling again (different versions from different app stores) - shouldn't that clear all remaining data anyway?

**Comment by penn5** [comment]
> I'm not quite sure what you mean by 'clear data'. Do you mean clearing cache and data for the element app from the system settings menu?
> I tried it multiple times - always uninstalling the app and reinstalling again (different versions from different app stores) - shouldn't that clear all remaining data anyway?

Yes, but on at least one affected device you should also do a factory reset to be sure

**Comment by bmarty** [comment]
It can be due to a bad configuration server side. When sign in or sign up, the credentials can also contain URL of the client-server API and if this URL is not correct, the app will fail to perform any other requests and so will never sync.

I will add some robustness on this point.

What is your homeserver URL?

**Comment by Glotzon** [comment]
I am running version 1.1.0 of Element-Android, I am unable to confirm this bug being closed.
Could please somebody check if above fix applied to the problem described above?
