### ISSUE TITLE
Sends login requests to https://matrix.org/ rather than honouring .well-known

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-android#2843]
By default, clients should check https://matrix.org/.well-known/matrix/client before logon to see that they should send login/registration requests to https://matrix-client.matrix.org.

It seems that currently element-android defaults to https://matrix.org.

**Comment by bmarty** [comment]
Just a small feedback, I do not say that this should not be fixed, but Element Android does that because https://matrix.org/_matrix/client/r0/login actually return something, so Element Android does not see the point to try to retrieve the client-server API using well-known.

**Comment by bmarty** [comment]
In EA 1.1.13
