### ISSUE TITLE
Redacting an event should redact all of the reactions

### ISSUE THREAD

**Issue by manuroe** [vector-im/element-android#286]
From riot-web created by [turt2live](https://github.com/turt2live): vector-im/riot-web#9843  

This probably needs server-side support to avoid making potentially thousands of calls to /redact

**Comment by manuroe** [comment]
Is it right that redacting an event should redact all of the reactions?

If I say something inflamatory and everybody boos, is it right that I can rewrite history by redacting the inflamatory statement?

I think I would prefer that the record at least show that `@bob:example.com` said _something_ and got 9000 👎s (of course all of the booers would be welcome to redact their boos if they chose)

**Comment by tulir** [comment]
Duplicate of #176?

**Comment by kittykat** [comment]
Duplicate of #176
