### ISSUE TITLE
Include UnifiedPush lib

### ISSUE THREAD

**Issue by iiitomo** [vector-im/element-android#2898]
I wish Element-Android allows me choose my distributor for Push Notifications. (e.g. so that I can use Gotify instead of FCM / Google services)

UnifiedPush is a recent FOSS library that allows this, I suggest to include it in Element-Android.
See #unifiedpush:matrix.org  and https://unifiedpush.org

**Comment by emorrp1** [comment]
Duplicate of #2743

**Comment by iiitomo** [comment]
Closing because duplicate of #2743
