### ISSUE TITLE
Send and play voice messages

### ISSUE THREAD

**Issue by Luraktinus** [vector-im/element-android#29]
Add the abillity to record and send voice messages inside the App and also play them.
(without the need of 3rd party apps)

EDIT by @bmarty:
Additional requirements:
- Users hold a button to record a voice message and release to review then send (or delete).
- The voice message is recorded as an audio file and uploaded to the media repository.
- A special event is written to the timeline and renders on clients as a playable voice message.
- Recording and playing audio files must be integrated into the app that no external other app is required for both functions.

**Comment by soonzhi** [comment]
any plan of doing this?

**Comment by bpcurse** [comment]
We have many requests for this feature as people are used to it from whatsapp and other messengers. The usability for illiterate people is another important factor.
The legacy riot-android even has a pull request open for this that hasn't been merged yet.

**Comment by bmarty** [comment]
(FTR: https://github.com/vector-im/riot-android/issues/1237)

**Comment by tuxayo** [comment]
> The usability for illiterate people is another important factor.

> EDIT: Except for illiterate people, it is probably an important feature for the visually impaired, too. I cannot tell but I expect it to be a better UX than using a screen reader.

Another use case: I have a relative with [arthritis](https://en.wikipedia.org/wiki/Arthritis) or [osteoarthritis](https://en.wikipedia.org/wiki/Osteoarthritis) and it's getting harder and harder to reliably use a touch keyboard.

**Comment by tuxayo** [comment]
@bpcurse 
>  The legacy riot-android even has a pull request open for this that hasn't been merged yet.

Is that these two?

https://github.com/vector-im/riot-android/pull/3314

https://github.com/vector-im/riot-android/pull/3207

**Comment by tuxayo** [comment]
Additional info: the same workaround[1] as in Riot legacy doesn't work as the file attachment menu doesn't offer the possibility to invoke a recorder app.

[1] this comment and the next one: https://github.com/vector-im/riot-android/issues/1237#issuecomment-600982782

**Comment by 532910** [comment]
Is any update there? This is a high-priority-must-have feature for any 21th century IM!

**Comment by bmarty** [comment]
Interesting library to consider (found by @onurays )
- https://github.com/varunjohn/Audio-Recording-Animation
- https://github.com/Armen101/AudioRecordView

**Comment by tuxayo** [comment]
@532910 
> Is any update there? This is a high-priority-must-have feature for any 21th century IM!

No need to word it like that. It seems (from a user POV) that RiotX is still very early in development. So yes, many stuff is missing.

**Comment by tuxayo** [comment]
I wish we users could fund well the project. That would help a lot for the development.
https://liberapay.com/matrixdotorg/

**Comment by 532910** [comment]
It will be nice to have ability to change a playback speed (with pitch correction of course).

**Comment by progserega** [comment]
May be do this as next iteration:
Add options for room "play new voice-messages in background" - even if screen is off.

And riotX will be able to work as a "radio".

**Comment by hieronymousch** [comment]
Bit of a shame that this lost the riotx-go-live push...

**Comment by fti7** [comment]
I think they will focus on this as soon RiotX can replace/is feature complete of the old Android App.
I switched to RiotX as the new Cross signing Feature came up and they did a good job for the current "Alpha/Beta" Stage :-)

**Comment by michaelblyons** [comment]
I would really like the same for video messages, too. A friend uses this all the time in a different application.

**Comment by ralaud** [comment]
> I would really like the same for video messages, too. A friend uses this all the time in a different application.

That feature would be nice, but I think it would be huge amount of data for a server.

**Comment by michaelblyons** [comment]
> > I would really like the same for video messages, too. A friend uses this all the time in a different application.
> 
> This feature would be nice, but I think it would be huge amount of data for a server.

It's reputedly in Riot Android already: "Record and send"

**Comment by ralaud** [comment]
> > > I would really like the same for video messages, too. A friend uses this all the time in a different application.
> > 
> > This feature would be nice, but I think it would be huge amount of data for a server.
> 
> It's reputedly in Riot Android already: "Record and send"

Oh, you are right, I forgot about this feature because it isn't so handy.

**Comment by TR-SLimey** [comment]
Maybe, just maybe, voice changer effects could also be added like Wire has? Mostly for fun but also to hide what your voice actually sounds like for privacy reasons.

**Comment by DoM1niC** [comment]
Currently I use the new RiotX instead of Riot with the VoiceMessage Forks, I hope some will implemented :( 

**THX anyway the new RiotX will bash all known Open Source Messenger alternatives!!!!!!!**

**Comment by progserega** [comment]
It is nice feature in Telegram: app will begin auto record voice-message when user place phone (with opened Telegram) to head.

Steps of this feature:
1. Unlock screen of phone 
1. Open Element app
1. Open needed room
1. place phone to head (use proximity sensor)
1. Element will hide screen (for prevent press some buttons by head) and begin record voice message
1. When user remove phone from head - Element will stop recording voce-message
1. Element wait 3-5 seconds for get users chance cancel sending this voce-message (by press showed "cancel sending" button)
1. If user not press this button - Element will send voice message to this room.

**Comment by hoergen** [comment]
I wonder what is the reason, why it is implemented in the Web App, but was never implemented in Riot, RiotX or Element?

I want to push this issue a little more, because it is open for now 2 years ?

**Comment by torbendoellmann** [comment]
There should also be a possibility to prevent other people from sending me voice messages (they would still be able to send audio files, but it takes an extra step, since you need to switch to a recording app to do so).

Sending voice messages is one of the worst things you can do to another person. Often it's not possibel to listen to them because you might be in a crowded place and most of the time people waste more than a minute to give you information that would fit in a sentence or two.

**Comment by progserega** [comment]
> There should also be a possibility to prevent other people from sending me voice messages (they would still be able to send audio files, but it takes an extra step, since you need to switch to a recording app to do so).
> 
> Sending voice messages is one of the worst things you can do to another person. Often it's not possibel to listen to them because you might be in a crowded place and most of the time people waste more than a minute to give you information that would fit in a sentence or two.

I am use https://github.com/progserega/voice2textMatrix bot for convert voice messages to text. It is not secure, but enough for most dialogs with voice-messages (at now this is mostly whatsapp bridged dialogs).

**Comment by jtagcat** [comment]
"Please don't send me voice messages." can be communicated between users themselves. Technology strongarming is not always the solution.

Transcriptions (also possible to do locally, on mobile devices) would be the next step, after implementing voice messages.

**Comment by wilhelmhagg** [comment]
I currently see all my friends migrating to telegram which I don't like. The voice recording feature is the only one missing to recommend them matrix/element. I would really love to see that.

**Comment by Atalonica** [comment]
The major missing feature as an user point of view, in my opinion.

**Comment by nithwith** [comment]
This feature will be really great and I hope it will be quickly integrated; it can really make a difference in attracting mass users from other online messaging platforms! I'm following the evolution of the issue carefully and will be available for the testing phase!

**Comment by alijafari96** [comment]
It's really surprising that a feature of this importance hasn't been implemented. Although there aren't many developers working on the project, the priority of voice messaging isn't that much low that after a year it hasn't been taken into account yet!

**Comment by gabmert** [comment]
Cross referencing: 
this feature is also wished for in web/desktop: <https://github.com/vector-im/element-web/issues/1358>
and it seems both are waiting for a update of the Matrix protocol <https://github.com/matrix-org/matrix-doc/pull/2516>

**Comment by jtrees** [comment]
FluffyChat already has this feature, by the way. An implementation should be possible with the existing protocol.

**Comment by fbruetting** [comment]
@bmarty Are there any plans for this feature ? I searched for this issue and found out – quite unsurprisingly – that I’m by far not the only one having problems getting quite some friends to use Matrix because of this sole and incredible useful feature. My friends are really interested, but it’s a major blocker for a lot of people. :/

**Comment by Yajo** [comment]
> An implementation should be possible with the existing protocol.

I guess that it's not possible for bridges to properly bridge a voice message and look native on both ends of the bridge unless it can differentiate that it actually *is* a voice message, and not just one attached sound file.

Example, this is how a native whatsapp message looks like:
![imagen](https://user-images.githubusercontent.com/973709/100771138-f6781100-33f5-11eb-9a82-19ac8d6b5898.png)

Now, when bridged from matrix using fluffychat voice message:
![imagen](https://user-images.githubusercontent.com/973709/100771229-160f3980-33f6-11eb-8321-66e5a4623c31.png)

I see similar things in other bridges.

**Comment by sim6** [comment]
Yes, it's not perfect for bridges but I prefer this behaviour that the current one. Always can be improved in a future.

**Comment by hex-m** [comment]
The audio player part got it's own issue: https://github.com/vector-im/element-android/issues/2525

**Comment by hoergen** [comment]
> The audio player part got it's own issue: #2525

hehe .... no!

This thread is meanwhile about that an essential function is not implemented because of other networks that are reachable via bridges. Looks like the development lost the direction on that topic.

**Comment by DanHakimi** [comment]
> This thread is meanwhile about that an essential function is not implemented because of other networks that are reachable via bridges. Looks like the development lost the direction on that topic.

To be fair, the audio player thread got derailed with features that would be good for audiobooks or music players but just not make sense for an inline messaging app audio player. It's github, threads get derailed.

**Comment by hoergen** [comment]
> > This thread is meanwhile about that an essential function is not implemented because of other networks that are reachable via bridges. Looks like the development lost the direction on that topic.
> 
> To be fair, the audio player thread got derailed with features that would be good for audiobooks or music players but just not make sense for an inline messaging app audio player. It's github, threads get derailed.

Please stick to this thread topic "Send and play voice messages" and don't do what you explained for completely other threads. Thank you.

The topic of this thread is still: **Send and play voice messages**

**Comment by hoergen** [comment]
https://github.com/vector-im/element-android/issues/2525

**Comment by TheTrainor** [comment]
Every single person I've tried to convince to use Matrix/Element has said no as soon as they found out it didn't have an easy to use audio message feature.

**Comment by trymeouteh** [comment]
Signal, Jami and other apps do this. Would be nice to see Element support this.

**Comment by TR-SLimey** [comment]
I think we've established now that this is an important feature, and as far as I know, it is planned, so maybe let's limit comments to suggestions only, and if you want to express your support for the feature, just give a +1.

**Comment by pwFoo** [comment]
Send / play voice messages would be nice, because many contacts love that feature...

**Comment by a000a** [comment]
Maybe this helps:
https://www.techotopia.com/index.php/Kotlin_-_Android_Audio_Recording_and_Playback_using_MediaPlayer_and_MediaRecorder

`android.media.MediaPlayer` is already used in vector/src/main/java/im/vector/app/core/services/CallRingPlayer.kt

**Comment by undrivendev** [comment]
+1

**Comment by TR-SLimey** [comment]
> +1

Not what I meant
.___.

**Comment by jphuart** [comment]
For the ones that cannot wait, there is fluffychat that propose the functionality, and it works fine: see https://fluffychat.im

**Comment by tredondo** [comment]
> I think we've established now that this is an important feature, and as far as I know, it is planned

Can someone point out to where exactly [on the roadmap](https://github.com/vector-im/roadmap/projects/1) audio/voice messages are planned? I couldn't find it by searching that page for these keywords, and the roadmap itself is pretty opaque - for example issue numbers instead of descriptions, or vague descriptions like "Improve X" (how?).

The corresponding [element-web issue](https://github.com/vector-im/element-web/issues/1358#issuecomment-758040145) was locked without linking to the roadmap either.

**Comment by paddycarver** [comment]
It's mentioned here: https://matrix.org/blog/2020/12/25/the-matrix-holiday-special-2020#2021

**Comment by Nesaijn** [comment]
When this is done on Android, will it also be done on iOS simultaneously?

**Comment by SimonBrandner** [comment]
@Nesaijn Probably yes

**Comment by AnonymousWebHacker** [comment]
Heeyy Sorry for being late for the party ;) @bmarty , what is Element waiting for audio? come on cheer up , That triangle of sending text, without hardly writing, is already left over 

![photo_2021-02-07_17-12-06](https://user-images.githubusercontent.com/43164089/107171772-92437180-6991-11eb-93c6-8b19cfa378bd.jpg)

**Comment by johansmitsnl** [comment]
@paddycarver it is indeed in the blogpost but not in the roadmap?

**Comment by SimonBrandner** [comment]
@johansmitsnl Hmmm, seems to be the case. Maybe the roadmap is outdated a bit. I am pretty certain this is coming since Matthew has mentioned this in the blog post as well as at FOSDEM

**Comment by nadonomy** [comment]
@johansmitsnl @SimonBrandner @moshpirit it's on the roadmap but unfortunately it's a private issue as it contains some private details due to the feature being sponsored. I'll go through all the private issues in the roadmap and break them out public counterparts so they're publicly visible in the near future.

**Comment by nadonomy** [comment]
From scanning the other comments— yep development is underway! In order to execute properly we've needed to re-lay out the composer and room header to scale better and present a more understandable hierarchy.

iOS & Android development are closely in sync so will release together, and @turt2live what's the latest on web support? I know you've been working on this while also focusing on other things but will web at least have playback support when mobile is ready?

**Comment by turt2live** [comment]
Web probably won't have support when mobile is ready. Other priorities got in the way and pushed web's implementation by a few weeks.

**Comment by hoergen** [comment]
Maybe you talking about some internal details, but "Web" in the browser Firefox and Chromium and the Desktop App are working like charme since minimum over a year with playing sound files. Or are you talking about recording inside the app ?

**Comment by n137** [comment]
I am for the idea of a voice bot that translates text into voice. I do not have enough time and energy to look at the phone and read messages (my eyes get tired, my posture deteriorates, my hands are busy). Voice messages would be very convenient. It might be able to work as a player, so as not to load the phone's memory.

**Comment by ArneNostitz** [comment]
hi and sorry if this is covered in another thread, but how is playback of bridged whatsapp audio coming along on mobile (iphone). works on desktop, but on mobile i just get "audio" file links and it always wants to open in an external app ... did i misconfigure something here?

**Comment by a000a** [comment]
> hi and sorry if this is covered in another thread, but how is playback of bridged whatsapp audio coming along on mobile (iphone). works on desktop, but on mobile i just get "audio" file links and it always wants to open in an external app ... did i misconfigure something here?

element android does not have an implemented player yeat, afaik. hope this feature is coming soon

**Comment by dylanmorroll** [comment]
+1 for this, with voice messages Element could be used for almost all communication, rather than having to switch to yet another app for this feature. This and location are the two things holding me back from shifting away reliance on other messaging apps!

**Comment by IJustDev** [comment]
Hey guys, read through some of the messages, is this planned for some upcoming version? Would love to work on this

**Comment by SimonBrandner** [comment]
You can follow the development here: https://github.com/vector-im/element-android/pull/3598
