### ISSUE TITLE
Regression: Video will not play upon tap, but only after swipe

### ISSUE THREAD

**Issue by ManDay** [vector-im/element-android#2928]
Tap on a video will spawn the video player (controls visible at bottom edge), but the video doesn't play and the screen remains black (even after tapping on the play button). The video *will* start playing if (from the video player screen) you swipe through the room's media.

**Comment by TheDiscordian** [comment]
Can confirm on Google Play v1.0.13 I did not have this bug, upgrading to v1.0.16 now I have this bug.

**Comment by ottersarecool** [comment]
I confirm this for the latest f-droid build aswell
Version 1.1.0

**Comment by ripper81** [comment]
I can confirm this bug on my Android phone. Videoplayback works in the desktop client. In my case only one of my chatrooms is affected. In the other rooms and direct conversations it works like intended.

**Comment by schopenhauer** [comment]
I have the same issue on my Android phone (Samsung S10, Android 11) running Element 1.1.0 [40101002] (G-b1380). The workaround works as explained by @ManDay above.

This seems to be the same problem as already described in issue [#1919](https://github.com/vector-im/element-android/issues/1919).

**Comment by wincak** [comment]
Reproducible with a clean install with a new account on current F-Droid version 1.1.0 [40101000] (F-bb33a92d).
Video plays OK on Element desktop on Linux. The video was a webm.
Does this really mean nobody can play any video on all Android clients since at least August or is there more to it?

**Comment by ManDay** [comment]
@wincak
> Does this really mean nobody can play any video on all Android clients since at least August or is there more to it?

"nobody": No, some people have reported they have no problems with F-bb33a92d. It seems to depend on further circumstances; development for Android is a PITA...
"play any video": Swiping left-right is good for a work-around which makes it work

**Comment by msaeedm** [comment]
I have the same issue

**Comment by G2G2G2G** [comment]
It's been like this for a few months, you just click the side of the video and it'll request you to open the video in your video player app instead of within element, then works fine.

Seems to be because it opens videos as an image when you click the center. 

@wincak

see above, anyone can play the vids.

**Comment by btouchard** [comment]
I've a same issue.
And when I use slide right/left work around, the video start, and stop after a minute with single message "can play video".
If I save video (download from app), she work well

best regard & good job ;)

**Comment by olymk2** [comment]
just had the same happen works for no one in the room, using element web how ever is fine the swipe hack does indeed start the video playing.
