### ISSUE TITLE
Copy message Snackbar blocking text input

### ISSUE THREAD

**Issue by chagai95** [vector-im/element-android#2929]
**Describe the bug**
When copying a message the Snackbar that pops up blocks the input text

**To Reproduce**
1. Go to a chat
2. Long click on a message
3. Try pasting it into the text input

**Expected behavior**
being able to copy and paste into Text input

**Screenshots**
https://nextcloud.chagai.website/s/KeLF75egBXwDCqC

**Smartphone (please complete the following information):**
 - Device: Xiaomi redmi 8
 - OS: MIUI 12

**Additional context**
 - developer branch
 - Homeserver: chagai.website

it'll be nice to be able to just paste straight away, maybe make it a toast instead or at least a short Snackbar duration. Perhaps add a button to the Snackbar to hide be able to just dismiss (hide) it or perhaps make the Snackbar not cover the text input field at all (maybe have it undernieth it or even above) last possibility is to add an option - resend message then you could do that and edit that message

**Comment by bmarty** [comment]
Snackbar is alrady displayed with a Short duration, but I agree it is displayed during a too long duration. I will reduce this duration.

Also you can already dismiss the Snackbar with a swipe on it (from left to right, does not work from right to left on my phone)
