### ISSUE TITLE
Direct Messages doesn't match "People" on Element Web

### ISSUE THREAD

**Issue by freaktechnik** [vector-im/element-android#2934]
**Describe the bug**
A couple of "people" rooms on Element Web show up under the normal rooms tab in Element for Android. The hallmark for those rooms is that they were created by a bridge and as such, have three accounts in their history, because the bridge copied in some message history. As a side effect of being classified as room and not direct message (I assume) the rooms don't get an icon on Android.

**To Reproduce**

1. Create new DM room with whatsapp bridge (mautrix-whatsapp, in my case I created them with the pm command to the bridge bot in element web)
2. Wait for the bridge to backfill history
3. Room shows up under "People" on Element Web

**Expected behavior**
Room shows up under "Direct Messages" in Element for Android, since Element Web sees it as "People" room. Essentially, I'd expect both clients to classify the rooms the same.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Fairphone 3
 - OS: /e/ OS 0.14 (based on Android 9)

**Additional context**
 - App version and store 1.1.0 Fdroid
 - Homeserver: humanoids.be
 - mautrix-whatsapp: mautrix-whatsapp v0.1.5+dev.464a7ee7 (Feb 26 2021, 14:12:33) (docker :latest)

I have double-puppeting in the bridge enabled/authenticated. I'll happily dig into the roomstate etc. with guidance.

**Comment by freaktechnik** [comment]
It turns out doing `/converttodm` in Element Web moves the room to the appropriate section on Android without any change to the room's location in Element Web.

**Comment by SimonBrandner** [comment]
@freaktechnik, for the change caused by `/converttodm` to be visible in Element Web you might need to refresh the page... It should work then, is that the case for you?

**Comment by freaktechnik** [comment]
I'm fine with what element web is displaying, since this is an android issue where my goal was to have a room shown under "people" to be shown under DMs on android.

**Comment by SimonBrandner** [comment]
Oh, I see, sorry I got a little confused

**Comment by marcquark** [comment]
i just ran into the same issue. `/converttodm` fixes the problem, but where does this inconsistency come from? it's confusing as a user to see something different on mobile than on desktop or vice versa

**Comment by pvagner** [comment]
It would be nice if /converttodm was available on android as well. I have created a portal to private chat using mautrix-facebook. On both element-web and element-android that room has been displayed under rooms executing /converttodm it moved to the expected spot on both - Direct messages on android and People on element-web.
If only /converttodm command was available on element-android as well so I can fix it from within element-android in the future.

**Comment by subiol** [comment]
@pvagner I have opened a feature request exactly for that: https://github.com/vector-im/element-android/issues/3533

**Comment by abmantis** [comment]
I can confirm this issue (I'm also using the mautrix-whatsapp bridge). Some rooms show up in the "rooms" in the Android app, but show on "People" in the web app.

**Comment by bmarty** [comment]
(related: #3533)
