### ISSUE TITLE
New event mark not disappears from launcher icon after read

### ISSUE THREAD

**Issue by iav** [vector-im/element-android#294]
New event mark not disappears from launcher icon after read on Samsing Galaxy Note 4, android 6.0.1

**Comment by iav** [comment]
What can I do to help solve a bug?

**Comment by iav** [comment]
I not see this bug anymore on my Samsung Galaxy Note 4, Android 6.0.1 with 1.0.3 [40100031] (G-b3369)

**Comment by bmarty** [comment]
Cool, let's close it then.
