### ISSUE TITLE
[Spaces] Using Spaces | Suggested Rooms

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/element-android#2971]
As an alterntive to auto-join, we introduce the suggested field in child content
=> UX wise these rooms should be proposed to the user

Will appear as a new section in room list at the bottom, listing the suggested rooms (once joined they are removed)

<img width="417" alt="image" src="https://user-images.githubusercontent.com/9841565/110294750-90041f80-7ff0-11eb-9cb2-26bb9fe3f0c3.png">

Est: 2ID

**Comment by niquewoodhouse** [comment]
@BillCarsonFr There's a couple of options in the Figma if you want to discuss them for feasibility as a first iteration.
