### ISSUE TITLE
Update Message Composer design

### ISSUE THREAD

**Issue by giomfo** [vector-im/element-android#2974]
The following changes must be applied on the existing message composer in element-android:
- Add a border to the text view
- Remove the separator between the room history and the message composer
- Remove the send button when the text input is empty
- Remove the security shield

Here is the targeted design:
![image](https://user-images.githubusercontent.com/8969772/110311469-1bd37700-8004-11eb-9abc-b5164f0faaa0.png)

**Comment by kojid0** [comment]
What is the role/function of the plus-button when text is entered?
Personally, I would switch emoji and plus so that the plus can be hidden once text is entered in the field. 
Then there is more space for text and illogical combination (plus visible when text is entered) would be removed.
Referring #2646

**Comment by beercanchicken** [comment]
Opinion here on the topic of conversation scrolling alignment and multi-line input: I've used both types and when the bottom of the conversation sticks to the top of the multi-line input, it feels more natural.  This is currently the behavior of Element and QKSMS.  Progressively covering the bottom of the last reply with the multi-line input as per your third screenshot seems to imply this behavior would change.

While I see the purpose of not showing a send button for a blank message, adjusting the spacing to add it back to the UI adds movement to the UI that can be avoided simply by disabling the button.

**Comment by giomfo** [comment]
> What is the motivation for removing the security shield?

It will be displayed into the header

**Comment by gaelledel** [comment]
> Opinion here on the topic of conversation scrolling alignment and multi-line input: I've used both types and when the bottom of the conversation sticks to the top of the multi-line input, it feels more natural. This is currently the behavior of Element and QKSMS. Progressively covering the bottom of the last reply with the multi-line input as per your third screenshot seems to imply this behavior would change.
> 
> While I see the purpose of not showing a send button for a blank message, adjusting the spacing to add it back to the UI adds movement to the UI that can be avoided simply by disabling the button.

Hi @beercanchicken Thanks for the feedback. I can confirm that this is not the intended behaviour. the composer will not cover content in the timeline.
