### ISSUE TITLE
Remove shields from the room list

### ISSUE THREAD

**Issue by bmarty** [vector-im/element-android#2991]
Remove shields from the room list.

It should allow to greatly improve the performance, especially after login to a big account with lots of e2e rooms, because computing the room shield require to load all the room members and their device, download their keys, etc.

Shields will stay visible when in the room detail screen (timeline), and on all its sub-screens.

EW does not display shield on the room list as well.

**Comment by manuroe** [comment]
Kamino cloned this issue to [vector-im/riot-ios](https://github.com/vector-im/element-ios/issues/4115)
