### ISSUE TITLE
Disable URL previews for matrix.to links

### ISSUE THREAD

**Issue by reivilibre** [vector-im/element-android#2995]
**Describe the bug**
URL previews are generated for matrix.to links, including those used for username mentions/pills.

![Screenshot_20210314-115907](https://user-images.githubusercontent.com/38398653/111067566-cfcd7a00-84bc-11eb-8703-eca6ed5cd6cf.png)

**To Reproduce**
Steps to reproduce the behaviour:
0. Have URL previews enabled on your server
1. Send a mention from another client
2. See in room.

**Expected behaviour**
I would expect these URL previews to not be shown for matrix.to links.

**Smartphone (please complete the following information):**
 - Device: Nokia N5
 - OS: Android 8

**Additional context**
 - App version and store: 1.1.0 [40101002] G-b1380 (Google Play)
 - Homeserver: [e.g. matrix.org] librepush.net with config modified to enable URL previews (this issue was spotted by someone else on another homeserver)

N.B. this does not occur on Element Desktop

**Comment by bmarty** [comment]
I've updated the title to point what we should do.
I'm not sure we can filter out a list of domains which generated useless URL preview, but as matrix.to is sort of thing strongly related to Element, we could deal with it.

**Comment by bmarty** [comment]
"https://*.element.io/" links could also be excluded.

**Comment by bmarty** [comment]
(I do not reproduce the issue with pills FWIW)
