### ISSUE TITLE
Voice Messages - Locked Mode

### ISSUE THREAD

**Issue by giomfo** [vector-im/element-android#3010]
We consider here the locked mode of the voice messages. This mode is associated with a playback mode available before sending the message.

- [ ] Locked Mode
   - The user has just activated the Voice recording mode. This opens the locking system.
   - The user drags up the Mic icon
   - Locking is activated once the Mic is fully dragged onto the padlock
   - The padlock then disappear by shrinking down in size
   - Once the Locked mode is fully active, A toast is diplayed indicated users that tapping on the wavelenghth stops the recording and enters playback mode
   - Voice messages last up to 2min. On the last 10s a toast notification is displayed warning users of time left. In the Locked mode, if the user goes over the limit, the recordings stops and goes into Playback mode
- [ ] Playback mode
   - If the user taps the audio bar visualiser, or the recording goes off the limit of time, or if the recording is interrupted by an external event (phone call), the recordings stops and goes into Playback mode
   - In playback mode, the users can listen to the recordings, send the recordings or delete the recordings

**Comment by DoM1niC** [comment]
Pretty Awesome and looks fine for the Element Design Sheet 🥇 

Element is the new Era of Messenging 💯

**Comment by bahur142** [comment]
Could you please add an option in the Preferences menu to disable/enable this feature? The same as Emojis.

**Comment by koalp** [comment]
> 
> 
> Could you please add an option in the Preferences menu to disable/enable Voice Messages feature? The same as Emojis.

I often accidentally hit the voice message button and never use the feature. I would really like this button to be optional.

**Comment by RayBB** [comment]
I think this issue is done too. Maybe we can close it?  @giomfo

**Comment by giomfo** [comment]
yes, thank you
