### ISSUE TITLE
If there are only emojis and whitespace in a t.text, make them larger

### ISSUE THREAD

**Issue by benparsons** [vector-im/element-android#3017]

**Comment by bmarty** [comment]
(this is already the case by the detection is broken for some (composed?) emojis)

**Comment by benparsons** [comment]
![Screenshot_20210318-152043.png](https://user-images.githubusercontent.com/1197991/111650925-b0f11f80-87fd-11eb-958e-7d74c89cdc41.png)

**Comment by bmarty** [comment]
Fixed in 1.1.4
