### ISSUE TITLE
[Bug] Files does not notify

### ISSUE THREAD

**Issue by DoM1niC** [vector-im/element-android#3027]
#### Describe the bug
Files only does not notify / create a Push 

#### To Reproduce
1. Send some Files
2. Wait if Push Notification appears

Sometimes works but often not in my Case 

#### Expected behavior
After send a file or files so Element does not push the Message correctly, in Web all is ok so far... Text Messages works instantly without problems.

#### Smartphone (please complete the following information):
 - Device: Huawei Mate 20 lite
 - OS: Android 10

#### Additional context
 - App version: Develop (GPlay) with own Sygnal Push Service
 - Homeserver: Synapse (Master) 

Is this a issue @Sygnal or specific of Client side ?

**Comment by bmarty** [comment]
(I do not reproduce the issue on my side, with a mtrix.org account. I get a push then a notification for image and file sent to a e2e or clear room)

**Comment by DoM1niC** [comment]
Mhhh... Strange yeah the Room is e2e too but Text is always working, but if I send a image or files, often the Push will not recognize 😐 I will test something later...

**Comment by DoM1niC** [comment]
so the Problem still exists with the latest Android Dev Code / Synapse / Sygnal... Messages are ok but Attachments no create a push notification, after I send a small Emoji or so this will works anyway.

**Comment by DoM1niC** [comment]
After some Merges from Synapse / Sygnal my problem is gone, I use the current PR from Android Client too, so any changes fixed this issue from either client or server side, I dunno ....
