### ISSUE TITLE
On-click behavior of call button

### ISSUE THREAD

**Issue by sl5net** [vector-im/element-android#3040]
#### problem

The connection from my android to android (she) takes> 4 minutes (she then stopped). so when I have element on on linux and on android. if android is off it goes faster, using only linux, almost without delay. 

if connection not work (takes> 4 minutes all the last WEEKS!! BTW that was terrible. thans for understanding)

she is changing her press behavior.

she presses more long, may too long, then it doesn't work either. 

do not know exactly what the effect. with Threema the button sems more flexibel, reacts better to your clicking habit. 

# Describe alternatives you've considered.

don't wait for release key

**Comment by bmarty** [comment]
Sorry, we do not understand anything. Feel free to open another issue and follow the template issue
