### ISSUE TITLE
Bug in /read_markers

### ISSUE THREAD

**Issue by timokoesters** [vector-im/element-android#3065]
https://github.com/vector-im/element-android/blob/c80564e1b14067287e463374ab71b9ad8c6cd0d4/matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/read/SetReadMarkersTask.kt#L45

The m.fully_read field is handled as optional, but the spec says it is required: https://matrix.org/docs/spec/client_server/r0.6.1#post-matrix-client-r0-rooms-roomid-read-markers

**Comment by bmarty** [comment]
Thanks, let me check

**Comment by bmarty** [comment]
Fixed in Element 1.1.4
