### ISSUE TITLE
Cannot sign out when server is unreachable

### ISSUE THREAD

**Issue by ykktrcb7** [vector-im/element-android#3099]
#### Describe the bug
Cannot sign out when server is not reachable. App stays in loop.

#### To Reproduce
1. Login to your server
2. Make your homeserver unreachable
3. Sign out
4. Cannot sign out and stays in loop

#### Expected behavior
Sign out or delete session

#### Smartphone:
 - Device: Huawei Mate 20 x
 - OS: Android 10

- element 1.1.0 from f-droid

**Comment by bmarty** [comment]
Do should see a dialog with cancel/retry in this case, don't you?

**Comment by bmarty** [comment]
Improved in Element 1.1.4
