### ISSUE TITLE
Hide send button when no text is entered (UX)

### ISSUE THREAD

**Issue by nourkagha** [vector-im/element-android#3114]
#### Is your feature request related to a problem? Please describe.
Currently if no text is entered in the message field, you can press the send button which does nothing. This adds some unnecessary clutter, doesn't feel very intuitive and makes the message field appear smaller.

#### Describe the solution you'd like.
Hide the send button unless text is entered in the message field.

Behaviour:

* No text entered: Emoji button alone on the right side of the message field.
* Text entered: Send button smoothly animates into view and appears to the right of the emoji button.

#### Describe alternatives you've considered.
You can desaturate (grey) the send button when no text is entered. However, simply hiding it reduces unnecessary clutter.

#### Additional context
This is used as a standard in other popular messaging applications and makes the messenger feel more responsive, adaptive and intuitive in terms of UX.

**Comment by violoncelloCH** [comment]
AFAIK the plan is to have a mic button for voice messages at that place once that feature is implemented
when a text is entered the mic button is replaced by the send button

**Comment by nourkagha** [comment]
That would make sense. I was wondering whether they plan on adding a mic feature or not (like Discord).

**Comment by violoncelloCH** [comment]
first steps are discussed/described here: #2974 #3009 #3010

**Comment by nourkagha** [comment]
Thank you! Closing this.
