### ISSUE TITLE
GMS in F-Droid build

### ISSUE THREAD

**Issue by linsui** [vector-im/element-android#3116]
See https://gitlab.com/fdroid/fdroiddata/-/merge_requests/8731

F-Droid enabled binary scanner recently and it found that in element apks there are gms classes. I guess gms is pulled by `react-native-device-info` though it doesn't require gms to work. Anyway we just need to exclude gms from jitsi-meet-sdk.

**Comment by bmarty** [comment]
Fixed in Element Android 1.1.4
