### ISSUE TITLE
Bug? @user:server.tld is already in the room when creating a new direct message with the user themselves/himself/herself/self/oneself

### ISSUE THREAD

**Issue by erikhuizinga** [vector-im/element-android#3123]
#### Describe the bug

Not sure if a bug or a feature... 😅 

#### To Reproduce

1. Open authenticated and unlocked Element Android
2. Click on new direct message FAB
3. Select the current user, i.e. oneself
4. Click CREATE
5. Creating room...
6. Observe warning/info/error dialog: `@user:matrix.tld is already in the room.`

#### Expected behavior

The same behaviour as on the Element web client, or the other way around: the web should show the same behaviour as in the Element Android client. On the web an 'Empty room' with just the user is created when trying to create a direct message with oneself.

#### Smartphone (please complete the following information):
 - Device: Google Pixel 3a
 - OS: Android 11

#### Additional context
 - App version and store: 1.1.3 [40101032] (G-b1729)
 - Homeserver: matrix.org

**Comment by erikhuizinga** [comment]
I haven't tested this myself, but another person on Element iOS (IDK the version) reports that it behaves like the web client: it creates an 'Empty room' with the user themselves.

**Comment by bmarty** [comment]
Let's do like Web or iOS for now :)

**Comment by bmarty** [comment]
I will also filter out the current user from the list of invitable users, on the app side, it makes sense.
