### ISSUE TITLE
Repeatedly clicking Third party notices preference may open dialog more than once

### ISSUE THREAD

**Issue by erikhuizinga** [vector-im/element-android#3127]
#### Describe the bug

Because the webview used to render the third party notices is slow to show, it is possible to open multiple webviews when clicking in quick succession on the 'Third party notices' preference in Settings -> Help & About.

#### To Reproduce
1. Go to Settings -> Help & About
2. Click on Third party notices repeatedly, one click quickly after another
3. See the slow loading of the dialog and notice that it may open multiple times, depending on the webview being in memory or not. It tends to be slower if not yet loaded.

#### Expected behavior

The dialog opens once.
The dialog opens quickly.

#### Smartphone (please complete the following information):
 - Device: Pixel 3a | emulator
 - OS: Android 11 | Android 6

#### Additional context
 - App version and store: 1.1.3 [40101032] (G-b1729)
 - Homeserver: matrix.org

**Comment by bmarty** [comment]
Fixed in 1.1.6
