### ISSUE TITLE
Order of the "j" lists is not stable in the import emoji script

### ISSUE THREAD

**Issue by bmarty** [vector-im/element-android#3134]
Each time I run the script `import_emojis.py`, I got different generated file, which is not ideal to see the diff.

Maybe a problem here: https://github.com/vector-im/element-android/blob/develop/tools/import_emojis.py#L117

Any idea @oogm ?

**Comment by oogm** [comment]
Hey, thanks for the heads up!
Almost, the problem is on the next line.
Turns out, OrderedDicts/Keys do not retain their order when using the "-" (setminus) operator.
Replacing these with ordinary delete operations should do the job, see PR #3147.

**Comment by bmarty** [comment]
Fixed by #3147 , thanks @oogm !
I will update the generated file today.
