### ISSUE TITLE
F-Droid Version Out of Date

### ISSUE THREAD

**Issue by Glitchy-Tozier** [vector-im/element-android#3141]
#### Describe the bug
For a month it has now been stuck on 1.1.0 and isn't updating.

#### Expected behavior
Update Element on F-Droid

#### Screenshots
![Screenshot_20210408-122819_F-Droid.jpg](https://user-images.githubusercontent.com/59611881/114011787-eb326780-9865-11eb-9513-62fb6c67fd3c.jpg)

#### Smartphone
 - Device: Samsung Galaxy S9
 - OS: Android 10

#### Additional context
 - App version and store: 1.1.0 - F-Droid

**Comment by T-bond** [comment]
It will he fixed with 1.1.4.

**Comment by Glitchy-Tozier** [comment]
Great!  :)
