### ISSUE TITLE
Typing notifications in the latest Buildkite build

### ISSUE THREAD

**Issue by bahur142** [vector-im/element-android#3146]
Hi 
I just tested the latest build from Buildkite 1975 to see whats new for the next version.
Typing notifications switch in Preferences is ON for both of my devices that are the same version from above. However typing notifications did not appear. I tried switching it off & on, clear cache.
Could you check it, please?
Thank you all for your efforts!

Devices: Xiaomi Mi4 (Android 6.01), Mi6 (Android 9)
Syanpse version: 1.31.0

**Comment by bmarty** [comment]
Typing notification are working fine here. Just to be sure: you will not see your own typing notification between your devices.

**Comment by bahur142** [comment]
Actually the accounts are two. The older device (Mi4) is just for tests and I have a test account there, so I simulate real chatting between 2 users :) 
I just downloaded the latest Buildkite from today and no change, still no typing notifications. But could be something specific just for these brand/devices.

**Comment by bmarty** [comment]
Typing notifications should also appear in the room list. Can you check that please?

**Comment by bahur142** [comment]
Hi, typing notifications are OK no with the latest build.
