### ISSUE TITLE
[SDK] Referenced OLM repository cannot be found

### ISSUE THREAD

**Issue by tladesignz** [vector-im/element-android#3150]
This line:

https://github.com/matrix-org/matrix-android-sdk2/blob/v1.1.1/matrix-sdk-android/build.gradle#L158

Leads to this output:

```
Execution failed for task ':app:dataBindingMergeDependencyArtifactsDebug'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find org.matrix.gitlab.matrix-org:olm:3.2.2.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/matrix/gitlab/matrix-org/olm/3.2.2/olm-3.2.2.pom
       - https://jcenter.bintray.com/org/matrix/gitlab/matrix-org/olm/3.2.2/olm-3.2.2.pom
       - https://jitpack.io/org/matrix/gitlab/matrix-org/olm/3.2.2/olm-3.2.2.pom
       - https://github.com/vector-im/jitsi_libre_maven/raw/master/android-sdk-2.9.3/org/matrix/gitlab/matrix-org/olm/3.2.2/olm-3.2.2.pom
     Required by:
         project :app > com.github.matrix-org:matrix-android-sdk2:v1.1.1

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```

JitPack doesn't know about anything:

<img width="1465" alt="Jitpack-olm" src="https://user-images.githubusercontent.com/117089/114207570-ce2c9000-995c-11eb-9150-851a460ab998.png">

**Comment by bmarty** [comment]
Yes, this is a recurring problem (see https://github.com/jitpack/jitpack.io/issues/3908). We are currently working to find another solution.

**Comment by tladesignz** [comment]
Urgh. Ok, thanks for letting me know and sorry for the disturbance.

Sometimes it works sometimes not? Looks like an issue with differing mirror configurations. Also never experienced that with github.com and gitlab.com sources. Maybe you want to move the OLM stuff to Github, too?
