### ISSUE TITLE
Show decrypted source doesn't show the latest message

### ISSUE THREAD

**Issue by MightyCreak** [vector-im/element-android#3155]
#### Describe the bug
With dev mode enabled, looking at the decrypted source of an edited message only shows the first message source.

#### To Reproduce
1. In Element-Android, enable dev mode
2. In a room, send the message "Test without modification"
3. Click on 'Edit' on this message and change the text to "Text with modification"
4. Show the (decrypted) source
5. See that it shows the source of the first message (i.e. "Test without modification")

#### Expected behavior
Show the latest message source.

#### Screenshots
Text rendered in Element-Android:
![image](https://user-images.githubusercontent.com/6382548/114310008-2bd4ef80-9ab7-11eb-8197-ffc1da66c282.png)

Decrypted source:
![image](https://user-images.githubusercontent.com/6382548/114310247-3ba10380-9ab8-11eb-9de9-ab96bcafb657.png)

#### Smartphone:
 - Device: OnePlus 6T
 - OS: Android 10

#### Additional context
 - App version and store: 1.1.3 PlayStore
 - Homeserver: matrix.org

**Comment by bmarty** [comment]
This is by design. If in the Advanced settings you enable "Show hidden events in the timeline", you will be able to see the Event which edits the first message and to see its source (with "Test with modification").

**Comment by MightyCreak** [comment]
Which will be the default behavior between Element Desktop and Android? (Element Desktop displays the last edited message by default)
