### ISSUE TITLE
Holding link to copy shouldn't open the message menu

### ISSUE THREAD

**Issue by SeerLite** [vector-im/element-android#3158]
#### Describe the bug
Pressing and holding a link in a message causes both the link to be copied and the message menu to show up.

#### To Reproduce
1. Send a message with any link e.g. https://matrix.org/
2. Press and hold the link

#### Expected behavior
The link should be copied and the message menu shouldn't open up.

#### Smartphone (please complete the following information):
 - Device: Xiaomi Redmi Note 8
 - OS: Android 10, LineageOS 17.1

#### Additional context
 - App version and store: 1.1.3 - F-Droid
 - Homeserver: matrix.org

**Comment by ouchadam** [comment]
fixed in 1.3.10 by https://github.com/vector-im/element-android/pull/4620
