### ISSUE TITLE
"In reply to" has no translation

### ISSUE THREAD

**Issue by waclaw66** [vector-im/element-android#3163]
#### Describe the bug
"In reply to" string has no translation. Please add the string to Weblate.

#### Screenshots
![obrazek](https://user-images.githubusercontent.com/15554561/114374102-93f10780-9b83-11eb-9178-68cef58d3b88.png)

**Comment by bmarty** [comment]
"In reply to" was in Weblate, but has been removed, because it was against the Matrix spec to translate this.

Also there was to other problem that it leaked the user's locale.

Anyway this will probably not visible in a near future when rich reply will be implemented on mobile.

**Comment by waclaw66** [comment]
Thanks for explanation.
