### ISSUE TITLE
[Bug] Mixed media sending will stuck

### ISSUE THREAD

**Issue by DoM1niC** [vector-im/element-android#3177]
#### Describe the bug
Mixed media contents will not send and give back a error with shows continuously resending

#### To Reproduce
1. Select some mixed Videos and Images and try to send

#### Smartphone (please complete the following information):
 - Device: Huawei Mate 20 lite
 - OS: Android 10

#### Additional context
 - App version: develop
 - Homeserver: master

**Comment by DoM1niC** [comment]
Will fixed with PR #3264

**Comment by bmarty** [comment]
In Element Android 1.1.7

**Comment by DoM1niC** [comment]
I have to reopen this because often on much media sending Element will show a retry error but ony abort and resend will help.... often the Problem appears with mixed Content like Video's and Pictures but not at all.

On Element Web @Desktop so far all seems be fine with much files-

**Comment by DoM1niC** [comment]
Issue seems fixed for me... Mixed sending works fine now...
