### ISSUE TITLE
Cross signing unreliable on Conduit (but works with Fluffychat)

### ISSUE THREAD

**Issue by timokoesters** [vector-im/element-android#3183]
On Conduit:

Element Web to Element Android cross signing is very hit or miss, a few weeks ago it instantly came up with the QR code and everything worked, but now even the emoji verification is stuck loading. Can I debug this somehow? I don't think the Conduit code for this changed.

When I start the cross signing from Element Web, I see the emojis on Element Android, but Element Web has a spinning loading icon

This is a new Element Android session trying to cross sign to an existing session in Element Web

It's weird, Element Android sometimes offers me a button with "scan their code" when I try to start verification from its settings, but I don't have any QR code it could scan (nothing shows up on Element Web)?

Element Web + Fluffychat emoji verification seems to work great

**Comment by bmarty** [comment]
As commented in #3589, it should be fixed on develop and in Element Android 1.1.14.

@timokoesters should be nice if you can confirm that! Thanks

**Comment by bmarty** [comment]
Please re-open if the issue can be reproduced.
