### ISSUE TITLE
Missing sender information after edited message of same sender since v1.1.4

### ISSUE THREAD

**Issue by SpiritCroc** [vector-im/element-android#3184]
#### Describe the bug

Consider following scenario:
- Person A sends msg1
- Person B sends msg2
- Person A edits msg1
- Person A sends msg3

Since v1.1.4, msg3 will no more contain the sender's name and avatar, and thus look like as if it was sent by person B.

#### To Reproduce

Join a room that contains messages of above order, for example in #element-dev:matrix.org: https://app.element.io/#/room/!bEWtlqtDwCLFIAKAcv:matrix.org/$-l1w_lEgvUpo5LQFZCLKZocvOeSB-3KLepmf3uH6ATs?via=matrix.org&via=t2l.io&via=riot.ovh

#### Expected behavior

msg3 in above scenario should show the sender's name and avatar.

#### Screenshots

In following screenshots, the picture was sent by Matthew, but looks like sent by Jonathan:

![device-2021-04-15-110324](https://user-images.githubusercontent.com/12481742/114843637-50440b00-9dda-11eb-907d-bf9edf19d22e.png)
![device-2021-04-15-110335](https://user-images.githubusercontent.com/12481742/114843656-533efb80-9dda-11eb-9148-6ab74c018266.png)

#### Smartphone (please complete the following information):
 - Device: OnePlus 5
 - OS: Android 11.0

#### Additional context
 - App version: F-Droid variant built from source (tag v1.1.4)
 - Homeserver: matrix.org and others

**Comment by bmarty** [comment]
Fixed in 1.1.7
