### ISSUE TITLE
Cannot open encrypted file after restarting the app

### ISSUE THREAD

**Issue by warwicklol14** [vector-im/element-android#3186]
#### Describe the bug
Whenever the app is started all the cached decrypted files are deleted. Due to this we cannot open files in an encrypted room.

#### To Reproduce
1. Upload a file in an encrypted room.
2. Close the app and remove it from the recent apps.
3. Open the app again and click on the uploaded file.
4. Expected UX is that the file opens but nothing happens.

#### Expected behavior
My expected behavior is that file opens in the desired app when you click on it.

#### Smartphone (please complete the following information):
 - Device: Samsung M31
 - OS: Android 11

#### Additional context
 - App version and store: 1.1.3 - F-Droid
 - Homeserver: matrix.org

I tried to find the cause of the bug and saw that to open the file we needed to get a temporaryShareableURI
https://github.com/vector-im/element-android/blob/9565e8975e31f8b873369e22e29d51824f8b20ca/vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailViewModel.kt#L1154

But when I tried to debug the app, this URI always was null so the event would never get posted causing nothing to happen when the file is clicked.

The reason the URI was always null is that
https://github.com/vector-im/element-android/blob/9565e8975e31f8b873369e22e29d51824f8b20ca/matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/DefaultFileService.kt#L279

The reason targetFile doesn't exist is that the following file is assigned to it which doesn't exist when you restart the app.
https://github.com/vector-im/element-android/blob/9565e8975e31f8b873369e22e29d51824f8b20ca/matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/DefaultFileService.kt#L244

The cached decrypted file is deleted whenever the app is started
https://github.com/vector-im/element-android/blob/9565e8975e31f8b873369e22e29d51824f8b20ca/vector/src/main/java/im/vector/app/features/home/HomeActivityViewModel.kt#L84

The getClearFile() method just returns the decryptedFile but it doesn't exist
https://github.com/vector-im/element-android/blob/9565e8975e31f8b873369e22e29d51824f8b20ca/matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/DefaultFileService.kt#L231

So the desired behavior is that `getTemporarySharableURI()` should instead of returning null, decrypt the file and send it.

#### Screenshots
![image](https://user-images.githubusercontent.com/45288858/114873070-8f914c80-9e18-11eb-8ef2-cfc8c6ca06de.png)

This is the way element-desktop handles it.

**Comment by warwicklol14** [comment]
I stumbled upon this bug while investigating #3067. Kindly look into it too.

**Comment by bmarty** [comment]
I see, thanks for reporting this annoying bug. I'm currently investigating it.

**Comment by bmarty** [comment]
Fixed in Element 1.1.7
