### ISSUE TITLE
App crashes on "troubleshoot notifications" button

### ISSUE THREAD

**Issue by bahur142** [vector-im/element-android#3187]
#### Describe the bug
When doing troubleshoot notifications, the app crashes.

#### To Reproduce

1. Go to Settings --> Notifications 
2. Click on "Troubleshoot Notifications"
3. App crashes on the last step when the notification should be displayed

#### Smartphone (please complete the following information):
 - Devices: Xiaomi Mi4; Xiaomi Mi6
 - OS: Android 6.0.1; Android 9.0

App Versions: 1.1.4; 1.1.5
Synapse: 1.31.0

**Comment by bmarty** [comment]
Thanks for reporting, I will have a quick look

**Comment by eliecharra** [comment]
Same behavior there

**Device** Xiaomi Mi8
**ROM** lineage os 18.1
**Android** 11
**App version** 1.1.5

App crash when reaching the last step and return to conversation list


https://user-images.githubusercontent.com/6154987/115004621-45a37780-9ea7-11eb-8e93-d50a8947f70e.mp4

**Comment by bahur142** [comment]
> Same behavior there
...

Hi, just a little diff question, because I see you are also using Mi device. Do you have sound notifications in one-to-one chats? Mine are gone since 1.1.4.

**Comment by eliecharra** [comment]
> > Same behavior there
> > ...
> 
> Hi, just a little diff question, because I see you are also using Mi device. Do you have sound notifications in one-to-one chats? Mine are gone since 1.1.4.

Yeah it seems that it's working for me.

**Comment by bmarty** [comment]
Fixed in EA 1.1.6, to be published today
