### ISSUE TITLE
Add Gitter.im as a default in the Change Network menu

### ISSUE THREAD

**Issue by AP2008** [vector-im/element-android#3196]
#### Is your feature request related to a problem? Please describe.
There is no way to browse the Gitter.im room directory. 

#### Describe the solution you'd like.
Gitter.im should be added as one of the defaults in the `Change Network` menu. 

#### Additional context

Gitter.im should be added here

<img src="https://user-images.githubusercontent.com/558581/115270322-d07fae80-a101-11eb-83e7-14f7f25f27af.png" width="400">

---

Related issue in the iOS app: https://github.com/vector-im/element-ios/issues/4233

Related issue https://github.com/vector-im/element-android/issues/1141

`gitter.im` was added one of the defaults to Element web via https://github.com/vector-im/element-web/pull/15894

**Comment by bmarty** [comment]
Element Android displays what is return by https://matrix.org/docs/spec/client_server/r0.6.1#get-matrix-client-r0-thirdparty-protocols

**Comment by MadLittleMods** [comment]
Thanks @bmarty!

Does the app only support looking that endpoint up from the `matrix.org` homeserver?

Can we specify `gitter.im` as a location under the `matrix.org` homeserver?

Do we have to wait for https://github.com/vector-im/element-android/issues/1141 in order to support multiple homservers?

**Comment by Half-Shot** [comment]
Protocols/third party endpoints only works for local bridges at the moment, not over federation so it's not terribly useful for `gitter.im`. However, usually it's up to the client to specify a set of default *homeservers* to show up in that list.

Element Web has gitter.im listed as an option in [it's config](https://develop.element.io/config.json)

**Comment by bmarty** [comment]
We will add it to the config file, as other Element clients, and deduplicate if `gitter` is returned by protocols/third party endpoints

**Comment by bmarty** [comment]
Implemented in Element Android 1.1.9

**Comment by AP2008** [comment]
@bmarty Thanks for taking the time to implement this! I'll try it out when 1.9.9 is released.

**Comment by bmarty** [comment]
You're welcome, but don't wait so long, it will be available in 1.1.9 :)
