### ISSUE TITLE
[SDK] Dummy stage doesn't send password but Synapse requires it

### ISSUE THREAD

**Issue by tladesignz** [vector-im/element-android#3217]
Using the latest SDK 1.1.1, we can't register new users with our own Synapse server.

It seems, Synapse requires the dummy stage, when nothing else is required (like Recaptcha) and it also needs to have the password set when trying to fulfill that stage.

But the SDK2 doesn't set it here:

https://github.com/matrix-org/matrix-android-sdk2/blob/develop/matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/auth/registration/DefaultRegistrationWizard.kt#L182-L188

Server to test against: `neo.keanu.im`.

**Comment by bmarty** [comment]
Hello,
I managed to register a new account on `neo.keanu.im` using Element Android.

When the dummy stage is mandatory, this is handled by the application, and not by the Matrix SDK. See https://github.com/vector-im/element-android/blob/057295c155b206ff6b0498c081707a7c1b5268ba/vector/src/main/java/im/vector/app/features/login/LoginViewModel.kt#L693

So in your case, you should do the same call when using the SDK.

Maybe mandatory `dummy` stage could be handled by the SDK without bothering the application, I'm not sure...

**Comment by tladesignz** [comment]
@bmarty, thank you very much for your help!

I got this implemented: So the deal is, if there is only one stage which is a dummy stage, then `#createAccount` first and **then** do the dummy call.

I wouldn't have figured that out on my own.

That logic is so messed up. There should be a better solution than this. I guess that "design" happened by mistake?

**Comment by bmarty** [comment]
If you call `dummy()` without first call `createAccount()` you should get `IllegalStateException("developer error, call createAccount() method first")` which is quite explicit :). See it in the link you've actually sent: https://github.com/matrix-org/matrix-android-sdk2/blob/develop/matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/auth/registration/DefaultRegistrationWizard.kt#L182-L188

But it also true that `RegistrationWizard` is not documented at all. I will add some comments.

Registration is documented here https://matrix.org/docs/spec/client_server/r0.6.1#post-matrix-client-r0-register

**Comment by tladesignz** [comment]
D'oh. Must admit that I didn't noticed that piece. Probably, because it's not explained a lot and is totally unexpected.

On the other hand, this exception didn't throw for me. I could execute the dummy call just fine, but the server answered with something along the lines of "missing username and password".

The REST API spec is there, yes. I implemented this already on iOS. The iOS SDK is not as detailed regarding authentication, but on the other hand, by looking at the less-confusing code from the MatrixKit, it was no problem at all.

**Comment by bmarty** [comment]
Doc has been improved in #3303
