### ISSUE TITLE
Spaces | Space landing enhancement add people you know

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/element-android#3233]
<img width="304" alt="image" src="https://user-images.githubusercontent.com/9841565/116237568-af056f00-a760-11eb-9e8a-5fa8629a7b20.png">

**Comment by kittykat** [comment]
@BillCarsonFr what changes do you feel need to happen compared to the current landing space?

**Comment by kittykat** [comment]
I'm going to close as the space join flow and space creation flow are different now, and that screen looks different too
