### ISSUE TITLE
favorites are shown twice

### ISSUE THREAD

**Issue by 532910** [vector-im/element-android#3240]
With the one of the recent updates favorites are shown twice.

![image](https://user-images.githubusercontent.com/14617699/116448872-3e467b80-a862-11eb-94bd-7d2266dcdaad.png)

**Comment by BillCarsonFr** [comment]
Can't reproduce on develop

**Comment by 532910** [comment]
Is develop available for verify?

**Comment by 532910** [comment]
1.1.7 looks fine
