### ISSUE TITLE
Unified Home View

### ISSUE THREAD

**Issue by ShadowJonathan** [vector-im/element-android#3241]
Basically a copy of what [schildichat](https://github.com/SchildiChat/schildichat-android) is doing, allow a single view for all chats.

Someone in `#element-android` wanted this, and i'm almost sure it's easy to implement.

<details>
<summary>Schildichat Preview</summary>

![](https://raw.githubusercontent.com/SchildiChat/SchildiChat-android/sc/fastlane/metadata/android/en-US/images/phoneScreenshots/2_en-US.png)

</details>

**Comment by ShadowJonathan** [comment]
(I'm also 99% sure this is a duplicate, but trying a few keywords didn't turn up with anything)

**Comment by kojid0** [comment]
It's a duplicate of #650 and much wanted, indeed. It seems that they are still waiting for design since 9 months... As @BillCarsonFr is assigned, maybe he knows more about the current state?

**Comment by ShadowJonathan** [comment]
If it's a duplicate, I'll close it right now.

Duplicate of #650
