### ISSUE TITLE
Change matrix.org wording on landing screen

### ISSUE THREAD

**Issue by ShadowJonathan** [vector-im/element-android#3242]
Currently it says;

> Join millions free on the largest public server

But shouldn't it be;

> Join millions, for free, on matrix's largest public server

?

**Comment by nadonomy** [comment]
@ShadowJonathan thanks for flagging!

@bmarty it looks like on web we use:

> Join millions for free on the largest public server

If we're actioning this as a quick fix— I would prefer to match web for cross-platform parity (and to avoid bikeshedding on grammar!).

**Comment by bmarty** [comment]
Thanks. Wording updated in next version 1.1.7
