### ISSUE TITLE
No sound notifications (noisy) when using Wi-Fi

### ISSUE THREAD

**Issue by bahur142** [vector-im/element-android#3243]
#### Describe the bug
Since version 1.1.6 there is a strange bug, that I can reproduce in 4 different devices. There are no sound notifications (noisy notifications) when you are using Wi-Fi. But when you are using mobile data sound notifications are fine. 
**This is valid only for devices with Android 8 and above. Devices with Android 5,6,7 are not affected.**

#### To Reproduce

1. Install the latest version no matter how - Play Store, Fdroid, Buldkite
2. Switch on Wi-Fi data and ask someone to message you in one-to-one chat with noisy notifications.
3. You receive a message notification (led, vibration, pop-up), **but no sound**.
4. Now switch on mobile data and ask again someone to message you in one-to-one chat.
5. You receive a message notification, but this time with sound. As it should be in one-to-one.

Expected behavior:
Sounds should work no matter WiFi or mobile data when noisy notifications are enabled.

 - Devices: all devices using Android 8 and above.

 - App version and store: all versions since 1.1.6
 - Homeserver: Synapse 1.31

**Comment by hifi** [comment]
I was just about to post this as well. Also reproduced on a Samsung XCover Pro and Huawei P30 Pro where both are on a recent enough Android. 

Though sometimes in addition to vibration I get partial sound like it's cut off. Most of the time nothing. I didn't notice using Wi-Fi was the common denominator so good catch! 

I'm on the current Play Store version of 1.1.6.

**Comment by pilpo** [comment]
Yep, same here. On one-to-one, I have no sound notification. But in room with multiple person, it's ok.

**Comment by funkesoftware** [comment]
I can confirm that. I've got the same behavior on my Motorola Moto G6 and my wifes HTC.
I hope this gets fixed soon.

**Comment by LinAGKar** [comment]
Still there in 1.1.7 [40101072] (G-b2298)

**Comment by matrixes** [comment]
I'm the author of #3537 and I have now been able to reproduce _this_ issue's... issue. I can get my notification audibly playing while on mobile data but not when using WiFi. It took me to go to the android web app and put all notification settings to Noisy to get to this point. I had done this exact same setting change in the Android app multiple times but that didn't affect anything. It was only when I just recently made the Noisy settings change on the web that audio started playing on my Android devices (I tested multiple).

It's _super weird_ that WiFi on/off has any affect on this..... And also, I'm more than a little bit confused about the web vs Android when it comes to the application of Notification settings....

**Comment by Nixon-Joseph** [comment]
I'm still seeing this constantly. I never noticed the connection to wifi, but have noticed that I often miss notifications because not even my android wear watch seems to do anything. The notification comes in (in the bar the next time I look at my phone), but I don't get a vibration or anything. 

When my notification volume is up, still get the notification on my phone, but it never vibrates or makes sound like it does for every other app I have.

**Phone:** OnePlus 7 pro (GM1917)
**OS:** Oxygen OS 11.0.6.1 (Android 11)

**Comment by OptimusGREEN** [comment]
Yeah my element Android app isn't giving me audible notifications. Not convinced this should be closed.
