### ISSUE TITLE
No "Upload Error" message when filesize upload exceeds server limit

### ISSUE THREAD

**Issue by dykstranet** [vector-im/element-android#3245]
#### Describe the bug
Large files appear to upload, but fail at the end if they are too large. 

#### To Reproduce
1. Upload file that exceeds server limit
2. Observe error message with no details

#### Expected behavior
Display an error with details, similar to what happens in the Element web client, 
![Upload_error_2021-04-29_12-37](https://user-images.githubusercontent.com/4895224/116503515-e4d55f80-a8e8-11eb-8955-0f47a624631a.png)

#### Smartphone (please complete the following information):
 - Device: Samsung S9+
 - OS: Android 10

#### Additional context
 - App version and store 1.1.6 from Google Play Store
 - Homeserver: Matrix Synapse 1.31.0 (private)

**Comment by bmarty** [comment]
After a quick look, it appears that the code does not check for attachment size when you share a file from a third party app to Element. Is it your use case?

From a timeline, if you click on the plus button, then select a big file to share, a check is done on the size.

Anyway I will imporve that code and let the MatrixSDK check for file size, which can also change if file is encrypted and/or reduces (image/video compression)

**Comment by bmarty** [comment]
Fixed in 1.1.7 (#3264)
