### ISSUE TITLE
Improve display of dates and times

### ISSUE THREAD

**Issue by bmarty** [vector-im/element-android#326]
Date separator on the timeline: we should display nice date format, like today/yesterday/name or day/day-month/day-month-year

for time (event, list of reaction, ...), same strategy: time, time-day, ... We can also consider using wording like "2 minutes ago" but it will force a more regular refresh of the timeline

**Comment by kojid0** [comment]
A floating date right below the header would be nice (similar to Telegram), indeed

**Comment by non-Jedi** [comment]
For date separators, it's particularly important that the year is shown (currently it's just `DayOfWeek DayOfMonth Month`) for dates that are not during current year. In scrollback, a date-separator from May 15 currently looks identical for 2019 and 2020 other than the day of week. Riot web handles this correctly.

**Comment by bmarty** [comment]
Added to the current sprint to decide if we can close it

**Comment by ganfra** [comment]
It should be ok now, but I've seen some people complaining about it not using the right locale. Maybe check on that?
