### ISSUE TITLE
Tapping on notification shows a blank screen

### ISSUE THREAD

**Issue by warwicklol14** [vector-im/element-android#3260]
#### Describe the bug
Whenever you tap on a notification for a message, it takes you to a blank screen. 

#### To Reproduce
1. Send a message to yourself from another account.
2. Tap on the notification.

#### Screen recording

https://user-images.githubusercontent.com/45288858/116685535-212fbb00-a9d0-11eb-8ac8-c20c41e0e599.mp4

#### Expected behavior
My expected behavior is that it goes to the respective chat when clicked on the notification.

#### Smartphone (please complete the following information):
 - Device: Samsung M31
 - OS: Android 11

#### Additional context
 - App version and store: 1.1.6 - F-Droid
 - Homeserver: matrix.org

#### Self investigation

I tried replicating this bug on Emulators with Android 11,8,7 but they seem to work perfectly fine. Searching for the same problem on https://matrix.to/#/#element-android:matrix.org and others also seem to have this problem.

I looked at the code and the following line seems to be the reason behind the blank screen.

https://github.com/vector-im/element-android/blob/38e83e1f3569ce5667ce782b1c4e2bf9b48474f8/vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailActivity.kt#L86

Upon debugging it is evident that getParcelable on the following line returns null.

https://github.com/vector-im/element-android/blob/38e83e1f3569ce5667ce782b1c4e2bf9b48474f8/vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailActivity.kt#L84

Finding where the intent for the notification is created, I stumbled upon this comment

https://github.com/vector-im/element-android/blob/38e83e1f3569ce5667ce782b1c4e2bf9b48474f8/vector/src/main/java/im/vector/app/features/notifications/NotificationUtils.kt#L691

This might be what is causing the bug. The pending intent doesn't seem to have any extra args.
But the intent is created with the roomId as it's data just in case.

https://github.com/vector-im/element-android/blob/38e83e1f3569ce5667ce782b1c4e2bf9b48474f8/vector/src/main/java/im/vector/app/features/notifications/NotificationUtils.kt#L692

So to have a temporary fix, I changed the getParcelable line as follows:

```kotlin
intent?.extras?.getParcelable(EXTRA_ROOM_DETAIL_ARGS) ?: intent?.dataString?.split("?")?.let { RoomDetailArgs(roomId = it[1]) }
```
Getting the roomId from the Intent's data fixed it temporarily. But I will await for a better solution to this bug from the element android team.

**Comment by peterx1024** [comment]
Same issue with notification:
Device: Samsung M11
OS: Android 10

Additional context
App version and store: 1.1.6 - F-Droid
Homeserver: matrix.org

**Comment by tlpbu** [comment]
Same issue with notification:
Device: Samsung Galaxy S20
OS: Android 11

Additional context
App version and store: 1.1.9
Homeserver: selfhosted private

**Comment by tlpbu** [comment]
Any chance this irritating issue will be fixed some time soon? 
In daily use I have to constantly close mobile app process and reopen app to be able to read/reply to messages once I happen to to click on notification.

**Comment by vyashole** [comment]
Same issue with notification:
Device: Samsung Galaxy A70 
OS: Android 11

Additional context
App version and store: 1.3.3 [40103030] (F-651e3478)
Homeserver: Matrix.org

**Comment by tlpbu** [comment]
Finally just noticed that issue has been resolved.
App version. 1.3.9
