### ISSUE TITLE
Chat showing as if from other person

### ISSUE THREAD

**Issue by chagai95** [vector-im/element-android#3275]
#### Describe the bug
Showing my messages as if they are from someone else

#### To Reproduce
Don't know

#### Screenshots
https://photos.app.goo.gl/Dp6guG3JwFBGuZNg8

#### Smartphone (please complete the following information):
 - Device: Galaxy A51
 - OS: 11

#### Additional context
 - App version and store: 1.1.6
 - Homeserver: chagai.website

**Comment by expipiplus1** [comment]
I have experienced this too. Long pressing on the offending message does show the correct attribution.

**Comment by bmarty** [comment]
Hello, thanks for reporting.
I think it is a duplicated of #3184 (I can see that there is a message edition), fixed in release 1.1.7
