### ISSUE TITLE
Add isPublic field to RoomSummary

### ISSUE THREAD

**Issue by elghrabi** [vector-im/element-android#3292]
Field needs to be added in RoomSummary so we can know if a room is public or not

**EDIT**

We will take the opportunity to display this information in the timeline, as per Element Web:

<img width="184" alt="image" src="https://user-images.githubusercontent.com/3940906/117433647-00b1b480-af2c-11eb-9dd0-6b3da4ef7da5.png">

The picto "world" is displayed if and and only if the join rule is equal to "public". Ref: https://github.com/matrix-org/matrix-react-sdk/blob/develop/src/components/views/avatars/DecoratedRoomAvatar.tsx#L93-L97

**Comment by bmarty** [comment]
We will add a field
```kotlin
val joinRules: RoomJoinRules
```
 to the room summary.

For reference: https://github.com/vector-im/element-android/blob/develop/matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/state/StateServiceExtension.kt#L28

**Comment by bmarty** [comment]
Implemented in Element Android and it's SDK 1.1.7
