### ISSUE TITLE
'add reaction' interaction on the row of reactions to encourage more (web parity)

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/element-android#3344]
### First point

Actual 
<img width="158" alt="image" src="https://user-images.githubusercontent.com/9841565/118264605-36b8e080-b4b8-11eb-9ee8-f9fcb266a412.png">

After
<img width="274" alt="image" src="https://user-images.githubusercontent.com/9841565/118264673-53551880-b4b8-11eb-8b6d-ef7a419cc6b8.png">

### Second point

Take the opportunity to think again on the bottom sheet of a message?

Currently we have 

<img width="287" alt="image" src="https://user-images.githubusercontent.com/3940906/140287251-2109a6d1-112a-45e0-a34b-f3a8cfda4773.png">

"Add Reaction" action is far from the quick reactions row, especially when this is a message sent by the user (since they can also edit and remove)

**Comment by daniellekirkwood** [comment]
Tagging Message Bubbles as we will implement this as a part of Bubbles project

**Comment by ganfra** [comment]
Done on #5204
