### ISSUE TITLE
Notification does not vanish if the message is read on another session

### ISSUE THREAD

**Issue by bmarty** [vector-im/element-android#3347]
- Bob has 2 sessions: one on Element Android, one on Element Web, and share a room with Alice.
- Bob is viewing the room list on Element Android
- Alice sends a message to Bob in room A
- The notification appears on Bob's Android device.
- Bob read the room in his Element Web session
- The notification is still visible to Bob's Android device -> KO

The notification should be cancel on Bob's Android device.

It used to work, so this is regression.

During the while process Element Android is in foreground (so is syncing permanently). If Element Android app goes to background, I'm not sure we will receive a Push to update the read marker of Bob, but it is acceptable in this case.

**Comment by bmarty** [comment]
I've noticed that the notification of one room is not dismissed when we open the room on the same device, which is probably a related issue.

**Comment by ouchadam** [comment]
I've been unable to reproduce, using a Google Play variant with the latest from develop cfd37bb5287f123886914f06e7c0348c64e80a94 and testing on a Pocofone f1 (API 29) and Samsung Fold (API 30) the notification correctly dismisses when focusing on the web client.

The notification also dismisses whilst in the app is in the background and the web client gains focus.

**Comment by ouchadam** [comment]
I think I've found the cause, other than having an invalid session or removing the room this is the only way I've been able to reproduce :crossed_fingers: 

the current logic relies on all the notification events existing within the same `last chunk` which means if a user gets enough messages in their timeline to start a new chunk it's now impossible for the app to match against the older events (the notification is cleared when all events for a roomId have been filter by `isMessageOutdated` which solely relies on the last chunk)

- [filtering events if they're outdated](https://github.com/vector-im/element-android/blob/develop/vector/src/main/java/im/vector/app/features/notifications/NotificationDrawerManager.kt#L252)

- [notification is removed when all events for the room have been filtered](https://github.com/vector-im/element-android/blob/develop/vector/src/main/java/im/vector/app/features/notifications/NotificationDrawerManager.kt#L289)

- [expecting the event to be in the last chunk](https://github.com/vector-im/element-android/blob/develop/matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/query/ReadQueries.kt#L39) 

- [creating a new chunk doesn't have the previous events](https://github.com/vector-im/element-android/blob/develop/matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/RoomSyncHandler.kt#L347)
