### ISSUE TITLE
Reduce the Space between each messages  

### ISSUE THREAD

**Issue by Sesmicwastaken** [vector-im/element-android#3351]
Pls reducse the spaces between the each induvidual message it looks very weird and takes up unecessary space on screen 

 Reference pic:

![Screenshot_20210517-100940.jpg](https://user-images.githubusercontent.com/78996543/118434368-f1a8d000-b6aa-11eb-8b86-13234659339a.jpg)

This is how it would roughly look like without so much space in between

![PicsArt_05-17-10.23.42.jpg](https://user-images.githubusercontent.com/78996543/118434041-5ca5d700-b6aa-11eb-83c9-56e2ff4c94a5.jpg)

This is just rough cropping so it wouldnt ofc look that good

Alternatively you guys can add background for the messages like whatsapp , signal etc 

:)

Sorry for so many edits just noticed many typos 😅

**Comment by bmarty** [comment]
It looks like you have enable the option to show timestamp for every message from Settings/Preferences/Timeline:

<img width="369" alt="image" src="https://user-images.githubusercontent.com/3940906/118483578-75e46d00-b716-11eb-88da-0ded729a0fd8.png">

**Comment by SimonBrandner** [comment]
Yep, disabling this solves the problem for me

**Comment by Sesmicwastaken** [comment]
Thanks!
Silly me lol xd
