### ISSUE TITLE
It sorts photos from old to new...

### ISSUE THREAD

**Issue by bienfp** [vector-im/element-android#3354]
Hi 

#### Describe the bug
When trying to add a photo, I choose the Galery (not the camera), and it sorts everything from A to Z, instead of Z to A, which means photos are sorted from the oldest first to the newest. Which has no interest when you want to share something as old photos could be years old.
So I have to sort them from Z to A using the filter.

#### Expected behavior
Either it remembers the previous setting, or we can change the default setting to "sort from Z to A"

#### Screenshots
![1 0](https://user-images.githubusercontent.com/84315960/118465467-33b13080-b702-11eb-9875-78116272330e.png)
![1 1](https://user-images.githubusercontent.com/84315960/118465500-3a3fa800-b702-11eb-9c7a-080f466528f7.png)

#### Smartphone (please complete the following information):
 - Device: Huawei P30, lastest version available, EMUI 11
 - OS: Android 10

#### Additional context
 - Lastest Element from Playstore
 - Homeserver: matrix.org

Many thanks in advance

**Comment by bmarty** [comment]
Element Android is opening a third party app to let you pick up photos from your system. I'm not sure we can customize the sorting here, but I will check.

Do you have the same issue on your device when you use another application, for instance an Email app, and you try to attach a photo to an email?

**Comment by bienfp** [comment]
Hello Benoit, 

(French ?)
I tried with Bluemail. I did "add file" then it gives me a lot of choices, but when i click on "image" then "camera" as a source, it all comes with the newest photos first...

Pierre

**Comment by bmarty** [comment]
(oui, français, mais continuons en anglais sur ce repo public :) )

Did you get to the same image picker using Bluemail? Some applications may have their own image picker.

I've checked if we could tell the system an ordering option, but I've not found anything so far. On my device, using Element or any other app I see the latest photos first, which as you say is the more logical thing to do.

**Comment by bienfp** [comment]
No, the image picker from Bluemail is like this :
![image](https://user-images.githubusercontent.com/84315960/118480251-47649300-b712-11eb-9c27-2f7d049ec8ce.png)

Then I click :
![image](https://user-images.githubusercontent.com/84315960/118480389-77ac3180-b712-11eb-826b-5c246d623778.png)

Then "image", "camera", and that gives me the liste starting with latest pic.

When you say you tested on your device, does it run Android ?

...
...
So I gave it a second try, from Element....
   - add "photo" from the choice "gallerie" : it comes wrong way round
   - add a "file", then choose "image" and folder "camera" and it comes with lastest photo first... Weird ! and it looks like the Bluemail file browser, which in Bluemail was a file browser as it didn't give me the choice to add an image directly...

**Comment by bmarty** [comment]
OK, thanks. Please let me know if it's better on Element 1.1.7, the picker will look like Bluemail image (and video) picker.

**Comment by bmarty** [comment]
> When you say you tested on your device, does it run Android ?

Yes, Android 10

**Comment by bienfp** [comment]
Hourra !
it seem to be working ! Did you do something special ?

**Comment by bmarty** [comment]
We are now allowing photos and videos to be selected... but it looks like the original pb is only on your phone :)

Happy to hear that it's fixed (as a side effect) in 1.1.7
