### ISSUE TITLE
Spaces | Improve 'Leave Space' UX/UI

### ISSUE THREAD

**Issue by erikhuizinga** [vector-im/element-android#3359]
See https://github.com/vector-im/element-android/issues/3359#issuecomment-843873136 for the current issue description.

<details>
<summary>
Previous, outdated issue description
</summary>

#### Is your feature request related to a problem? Please describe.

As a user I want to remove a Space, so that I can organise Spaces properly.

#### Describe the solution you'd like.

As a user I want to remove a Space (if I have rights), or leave a Space (if I was added/invited+accepted and have rights to leave).

An option to remove a Space forever in the Space's overflow (three dots) menu in the drawer or in its settings will likely do.

#### Describe alternatives you've considered.

There currently seems no way to leave a space.

#### Additional context

N/A

</details>

**Comment by BillCarsonFr** [comment]
Hello @erikhuizinga 
The option is there, but you might have to scroll the bottomsheet a bit

<img width="405" alt="image" src="https://user-images.githubusercontent.com/9841565/118779481-5de22a00-b88b-11eb-8b1f-5f126dec6776.png">

![reveal_leave](https://user-images.githubusercontent.com/9841565/118779725-a3065c00-b88b-11eb-9055-d2b34c93070e.gif)

Will look at a way to make this option more visible.

**Comment by erikhuizinga** [comment]
Wow, that's some extremely difficult to discover UI! Thanks for your reply.

Consider this issue to be about the UX/UI of the feature.

- It should be visible. The bottom sheet clearly isn't fit for this menu, because there might be more menu items than what fits on screen. Consider less menu items, e.g. move the Leave Space option to Settings, or join Invite people and List members in one item e.g. called Manage members, etc.
- What happens to the Space when leaving? Is it deleted if the last member leaves? Or if the last admin leaves? The impact on members when leaving (as admin or moderator) should be clear, if there is any.

**Comment by erikhuizinga** [comment]
I've updates the issue description and title.

**Comment by bmarty** [comment]
In EA 1.1.8
