### ISSUE TITLE
Spaces | Explore room list: the RoomId is displayed instead of name

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/element-android#3371]
In #community:matrix.org 

<img width="307" alt="image" src="https://user-images.githubusercontent.com/9841565/118814768-c7c0fa80-b8b0-11eb-8f19-f6ce1f73e2f3.png">

**Comment by BillCarsonFr** [comment]
Ok, so this room does not have a name. But in this case we should use an alias if any

**Comment by bmarty** [comment]
Fix in EA 1.1.8
