### ISSUE TITLE
Spaces | Add Rooms, should use better room name resolver

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/element-android#3376]
Empty Dms without names appears with roomId

=> Try to use roomNameResolver

<img width="419" alt="image" src="https://user-images.githubusercontent.com/9841565/118840858-0f9f4c00-b8c8-11eb-83db-ccb48835c880.png">

Probably should Adapt it also in Discover rooms controller

**Comment by HarHarLinks** [comment]
seems to be same problem as in vector-im/element-web#17336

**Comment by kittykat** [comment]
Closing as it now shows a more detailed description:

![Screenshot_20220107-115133](https://user-images.githubusercontent.com/51663/148540587-ba437bee-dd8c-48cd-b74b-e837b51b5a9f.png)
