### ISSUE TITLE
Android: Jitsi auth

### ISSUE THREAD

**Issue by ganfra** [vector-im/element-android#3379]
Support Jitsi Auth as per https://github.com/matrix-org/prosody-mod-auth-matrix-user-verification#widget-initialization

**Comment by bmarty** [comment]
Done in #3383 in EA 1.1.8

**Comment by amelentjev** [comment]
Unfortunately it doesn't work out of the box on latest jitsi meet (2.0.7830-1).
1. It awaits "JWT" string in "typ" header field.
2. It checks jwt signature against "notused" key.

To make it work I have to comment pair of checks in verify method of luajwtjitsi.lib.lua
