### ISSUE TITLE
[spaces-feedback] please show me if I have unread messages in a space that I currently don't have open

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/element-android#3381]
Currently android space pannel only show badges for notifications, but not for unread messages

ACTUAL:
<img width="357" alt="image" src="https://user-images.githubusercontent.com/9841565/118985005-5ea7b880-b97e-11eb-9743-d9d80db66b13.png">

EXPECTED?
<img width="359" alt="image" src="https://user-images.githubusercontent.com/9841565/118985034-64050300-b97e-11eb-9f72-a69e8cdb0927.png">

**Comment by BillCarsonFr** [comment]
@niquewoodhouse wdyt?

**Comment by niquewoodhouse** [comment]
Sounds good, would match web then, right?

**Comment by BillCarsonFr** [comment]
> Sounds good, would match web then, right?

For consistency do we update the room list too?
Currently there is a vertical green bar at the begining of entry with unread messages
<img width="193" alt="image" src="https://user-images.githubusercontent.com/9841565/119136890-7a739300-ba40-11eb-86c4-439a42715b57.png">

**Comment by niquewoodhouse** [comment]
So on android you get the green bar on the side when a room has an unread message?  there's no dots?

I'd like to change that, I think it's a good idea, but it's not really part of the spaces beta, feels like it needs to be considered more as an app-wide task. wdyt?

**Comment by kittykat** [comment]
This is implemented now :+1:
