### ISSUE TITLE
Element crashes opening any rooms

### ISSUE THREAD

**Issue by c-x-berger** [vector-im/element-android#3393]
#### Describe the bug
The title says most of it. Opening any room - E2EE or not, DM or normal channel - causes the application to crash. I've attempted to sign out and back in, but to no avail.

Re-installing the app from F-Droid seems to have fixed the issue. I've submitted crashlogs via the app prior to reinstalling.

#### To Reproduce
1. Open app
2. Attempt to open any room or DM
3. Observe crash or boot to main screen

#### Expected behavior
I'd like to be able to open rooms...

#### Smartphone (please complete the following information):
 - Device: Pixel 3a
 - OS: Android 12 Beta

#### Additional context
 - App version and store: 1.1.7 - F-Droid
 - Homeserver: boiler.social

**Comment by BillCarsonFr** [comment]
https://github.com/matrix-org/element-android-rageshakes/issues/23071

**Comment by bmarty** [comment]
Thanks for reporting @c-x-berger. If you create a new room, can you open it?

**Comment by c-x-berger** [comment]
Unfortunately, I'm not entirely clear on how I got in the crashing state anymore. Reinstalling the app fixed it, and I don't know how to get back. I didn't think to try creating a room while it was still going.

**Comment by c-x-berger** [comment]
And it's mysteriously started happening again.

I can create a room, and even send messages in it. I can freely navigate to and from that room starting from the room list. Other rooms still cause the issue. It may have something to do with multiple users being in the room?

**Comment by bmarty** [comment]
Some item in the timeline can cause this problem. It's weird that only you have this issue as far as I know.
Do you observe the crash on a room that I could join? Or feel free to invite me (@benoit.marty:matrix.org) in one of the rooms which causes crashes (using another client of course...)

**Comment by c-x-berger** [comment]
> Do you observe the crash on a room that I could join?

Yep. Synapse Announcements is a well know one, or try `#liminal-space:boiler.social` for a smaller room. Both are public.

**Comment by hashworks** [comment]
I have the same issue. Reseting the app (deleting the storage and signing in again) didn't solve the issue. I was able to create a direct chat with another user which seemed to work fine, but crashes now as well.

**Comment by bmarty** [comment]
Here is the crash log

```
Thread: Timeline_Building_Thread, Exception: com.airbnb.epoxy.IllegalEpoxyUsage: You must set an id on a model before adding it. Use the @AutoModel annotation if you want an id to be automatically generated for you.
at com.airbnb.epoxy.EpoxyController.addInternal(EpoxyController.java:8)
at com.airbnb.epoxy.EpoxyModel.addTo(EpoxyModel.java:1)
at com.airbnb.epoxy.EpoxyController.add(EpoxyController.java:1)
at com.airbnb.epoxy.EpoxyController.add(EpoxyController.java:7)
at im.vector.app.features.home.room.detail.timeline.TimelineEventController.buildModels(TimelineEventController.kt:7)
at com.airbnb.epoxy.EpoxyController$1.run(EpoxyController.java:6)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.os.HandlerThread.run(HandlerThread.java:67)
```

This is really strange that this issue does not occur for every one.

**Comment by c-x-berger** [comment]
Hmm. 1.1.8 made its way on to F-Droid today, and the issue seems to have vanished itself?

I'm closing this issue, but if stuff breaks again (like it has after a re-install) I'll reopen it.

**Comment by hashworks** [comment]
I've updated to 1.1.8 which seemed to fix the issue, yes. After updating to the latest Android 12 beta yesterday the bug re-appeared – but I don't know if it is caused by the update or by anything else happening in that time period.

I've submitted a bug report again with `GitHub Issue 3393` as the problem description.

**Comment by hashworks** [comment]
Looks like this is still an issue with the new Android 12 Beta 4. Note that I also recently reinstalled my phone completely.

**Comment by bmarty** [comment]
Todo: test ono Android 12 emulator if we can repro and fix

**Comment by bmarty** [comment]
Tested today using an emulator running Android 12 and no crash has been observed

**Comment by hashworks** [comment]
Seems like it has been resolved on my end as well.

**Comment by bmarty** [comment]
Ok, thanks for the feedback, let's conclude that it was due to the beta version of the system...
