### ISSUE TITLE
Thumbnail not being compressed

### ISSUE THREAD

**Issue by MainTobias** [vector-im/element-android#3396]
#### Describe the bug
When sharing a Video picked from Gallery the video is being compressed but the Thumbnail not.

**Comment by bmarty** [comment]
Do you suggest to extract the thumbnail from the compressed video? The quality will be reduced, I'm not sure this is a good idea.

**Comment by MainTobias** [comment]
No, but the thumbnail should at least be compressed a little. F.e. when I am sharing a short 4k video the video size after compression is 5mb and the thumbnail size is 1.5mb, which is kinda big.

**Comment by bmarty** [comment]
In EA 1.1.9
