### ISSUE TITLE
Clarify the difference between Direct Messages/Chats/DM and Rooms

### ISSUE THREAD

**Issue by opusforlife2** [vector-im/element-android#3409]
#### Is your feature request related to a problem? Please describe.

I do not understand the difference between a DM and a Room. When I'm creating a new DM, I can add multiple people to create a Group DM instead of a 1:1 DM, so it's not single user vs group, clearly.

So the problem is, I do not know when I am supposed to create a Group DM and when I should create a Room.

In fact, I can't seem to find the answer across the entire Matrix project's communications, anywhere.

#### Describe the solution you'd like.

I would like the app (and other Matrix IM apps) to clarify what each category is for in the UI, preferably in the onboarding process, but also visually in the app itself. A Group DM should look visually different from a Room.

#### Describe alternatives you've considered.

The Element and Matrix websites should mention:
- That you can create a 1:1 DM, a Group DM, and a Room.
- The difference between a Group DM and a Room.

**Comment by opusforlife2** [comment]
Can someone at least informally state here what the difference is? I still cannot find it anywhere.

**Comment by BillCarsonFr** [comment]
Hello @opusforlife2 ,

I can quickly explain the technical part: 

Technically there is no difference between a 1:1DM, group DM, or room. They are all just rooms. 
It's just a local setting client side, were a room can be marked as a DM. On web you can use the slash command /converttodm or /converttoroom

On creation though, DMs or grouped DMs have a specific preset, like for example making all participant admins of the chat (would not be the case if you first create a room then add people).

Other than that, you are right the UX should be improved

**Comment by opusforlife2** [comment]
Thanks, @BillCarsonFr! So basically it's about what presets are used when creating a Room. Got it.

**Comment by bmarty** [comment]
I think we can close this issue now. You got a clarification from BillCarsonFR and there are other issues to deal with moving a room between Direct Message and Rooms (#3533)

**Comment by opusforlife2** [comment]
@bmarty This issue has nothing to do with conversion between types of rooms.

There is still no UI element or behaviour that shows the difference between the three. If I ask a layperson to install Element, they get misled by the two bottom tabs.

Usually, people assume that the DM tab is for 1:1 chats, and the Rooms tab is for group chats. I have to prevent them from creating Rooms when they're supposed to create Group DMs. Actually, I mostly do everything myself each time.

---

One line pitch: A layperson using Element just sees a DM and a Rooms tab. They have no idea that there are 1:1 DMs, Group DMs, and Rooms, or what the difference between them is.
