### ISSUE TITLE
Spaces name shows after logging out and into other account

### ISSUE THREAD

**Issue by timokoesters** [vector-im/element-android#3415]
#### Describe the bug
I logged out of my account and into another account. In the top bar under "Direct Messages" I see a space I joined in the old account.

#### To Reproduce
1. Log in to main account
2. Open a space so the top bar says the space name
3. Log out and into the other account

#### Expected behavior
The space name should not show as I am not part of it in the other account.

#### Additional context
 - App version and store 1.1.8 play store

**Comment by bmarty** [comment]
@BillCarsonFr can you investigate please?

**Comment by kittykat** [comment]
@timokoesters can you still reproduce the issue? I haven't been able to over here so wanted to check with you before closing

**Comment by kittykat** [comment]
I'm going to close this issue for now as we cannot reproduce it. If anyone can, please comment with @kittykat and I will re-open it.
