### ISSUE TITLE
Cant connect to .onion domain

### ISSUE THREAD

**Issue by MainTobias** [vector-im/element-android#3418]
#### Describe the bug
I cant connect to my onion service hosting synapse.

#### To Reproduce
1. Open Orbot
2. Select a browser and the Eelement app. Enable VPN Mode. Press start.
3. Click on the browser icon to verify you are indeed connected. Open element and try to add http://exampleV3.onion or http://exampleV3.onion:80. Wont work.

 open element and try to directly(without orbot) connect to your .onion service and it wont work too.

#### Expected behavior
You should be able to connect to a .onion service just like you can connect to a normal synpase server. (Also my .onion service shows the everythings working page when visiting it through the tor browser)

#### Smartphone (please complete the following information):
 - Device: Oneplus 8T
 - OS: Android 11

#### Additional context
 - App version and store 1.1.7 -- Google Play Store
 - Homeserver: http://testzb2rccudyyibsvsjprglksfpoyctejreket6mayaqpkfnzrbp5id.onion/

**Comment by ChuckNorrison** [comment]
Same behaviour here, you already tried to disable "Private DNS" in Android settings?

**Comment by MainTobias** [comment]
Thank you I just needed to turn Private DNS from Automatically to Off. However I think there should be some kind of reference either in the form of an error when it element detects a onion address or as a note in the documentation.

**Comment by ChuckNorrison** [comment]
Its more a onion routing problem on android devices with this hidden Private DNS backdoor. Orbot is just an issue which makes this crime obviously, its not even an optional setting while setup your android. Nobody knows whats happening with your nameresolution requests... for sure its all logged in a database and ready to manipulate your data
