### ISSUE TITLE
Design kit update

### ISSUE THREAD

**Issue by gaelledel** [vector-im/element-android#3426]
Design is currently cleaning up the Element UI components and basic styles such as colours and text styles.
The ultimate goal is to accomplish the same in the SDK and aim to create consistency and harmony between design and development.
We're starting the cleaning work with basic styles first (colours and text styles)

COLOURS
To start with, I have drastically reduced the colour palette to 25 colours in total. These colours account for both Light and Dark themes and are referenced as Global colours here: https://www.figma.com/file/X4XTH9iS2KGJ2wFKDqkyed/Compound?node-id=1338%3A17947

I have also created a Mobile specific colour guide with appropriate variable namings here: https://www.figma.com/file/X4XTH9iS2KGJ2wFKDqkyed/Compound?node-id=1521%3A23026 and this is what should be implemented in Android Studio.
As discussed it'll be preferable to save these styles in the style.xml file for better development practices and to facilitate the work around consistency.
You can see these colours being applied on the Android UI here https://www.figma.com/file/X4XTH9iS2KGJ2wFKDqkyed/?node-id=1937%3A102

TEXT STYLES
A list of text styles is defined here https://www.figma.com/file/X4XTH9iS2KGJ2wFKDqkyed/Compound?node-id=1336%3A17796
This aims to follow the Google Material design default typography style as much as possible with one exception or two for font size. 
It would be ideal to use the variable naming convention proposed in the "font in Figma" column. Again this will ease communication between design and development if the need of text referencing occurs.

Any question let me know :)

**Comment by bmarty** [comment]
Implemented in Element Android 1.1.10, mainly in #3459, #3486 and #3511

@gaelledel feel free to create issues in this repo for any mistakes on color or text, even the smallest one :). As you can see in the 3 PRs above, a lot of files has been impacted, so I cannot guarantee that everything is fine. Thanks!
