### ISSUE TITLE
"Error decrypting attachment" for a video sent in an encrypted room

### ISSUE THREAD

**Issue by dkasak** [vector-im/element-android#3428]
### Description

A video that was sent to an encrypted room is unplayable. I can see the initial frame, but hitting all other buttons are disabled except the play button. However, hitting the play button does nothing.

Pressing the `Decrypt *.mp4 (XX.YY MB)` button below the video show the following:
![image](https://user-images.githubusercontent.com/463342/120065391-9db1ca00-c060-11eb-83c4-461f23a9b6de.png)

I'll rageshake.

Logs being sent: yes

### Version information

- **Platform**: desktop
- **OS**: Arch Linux
- **Version**: 1.7.29

**Comment by bmarty** [comment]
It working fine today (using the same problematic video, without uploading it again). I do not know what happened...
