### ISSUE TITLE
im.vector.app is outdated in F-Droid

### ISSUE THREAD

**Issue by Kreyren** [vector-im/element-android#3434]
#### Expected behavior
Expecting version 1.1.8, got 1.1.7

#### Smartphone (please complete the following information):
 - Device: OnePlus2
 - OS: DivestOS 17.1
 
 Build for 1.1.8 doesn't seem to be pushed in f-droid based on `F-Droid Build Status` app

**Comment by bmarty** [comment]
Yes, please be patient.

**Comment by 6543** [comment]
https://gitlab.com/fdroid/fdroiddata/-/issues/2396
