### ISSUE TITLE
Push notifications are repeated if the sync takes too long

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-android#3437]
#### Describe the bug
I get too push notifications for the same message if I dismiss the notification before the sync happens.

#### To Reproduce
1. Be on a slow network/server/account
2. Receive a push notification
3. Dismiss it
4. A couple seconds later when the sync completes, get a second notification for the same message

#### Expected behavior
I should not have my phone vibrating twice as often.

#### Screenshots
N/A

#### Smartphone (please complete the following information):
 - Device: Pixel 5
 - OS: Android 11

#### Additional context
 - App version and store: 1.1.8 playstore
 - Homeserver: irrelevant

**Comment by tulir** [comment]
I think I get this for pretty much all messages. Element Android is really slow to sync for some reason (much slower than other clients), so all notifications are pushed twice.

**Comment by johansmitsnl** [comment]
For me I get them sometimes 8 times in a row when you think what is exploding in this chat. Just one message...

**Comment by ouchadam** [comment]
unfortunately this isn't in the 1.3.4 release as #4238 was merged into a feature branch #4274

will temporarily reopen until we merge the feature PR
