### ISSUE TITLE
[SDK] Does a Java example project exist?

### ISSUE THREAD

**Issue by tobymurray** [vector-im/element-android#3440]
I've been following along with the Kotlin example project: https://github.com/matrix-org/matrix-android-sdk2-sample

Is there a Java equivalent?

**Comment by bmarty** [comment]
Not as far as I know. But the Android Matrix SDK2 should be compatible with any Android projects written in Java.

**Comment by tobymurray** [comment]
I was trying out a Java Android project and the interoperability provides some interesting challenges. E.g. handling `Result` seems to be not-completely-trivial in Java code. I was hoping a Java sample project would help guide through some of the trickier bits (so I didn't have to learn Kotlin)

Maybe giving Kotlin a go is the path of least resistance though.
