### ISSUE TITLE
Update Audio, docs attachments visual appearances

### ISSUE THREAD

**Issue by gaelledel** [vector-im/element-android#3444]
As part of the voice message work, we need to clearly differentiate attachment types in the timeline.
Types:

1/Voice message
2/Audio files
3/Files such as .docx, .pdf .excel etc
4/images such as .jpg .png etc

https://www.figma.com/file/X4XTH9iS2KGJ2wFKDqkyed/Compound?node-id=2039%3A26421

**Comment by HarHarLinks** [comment]
related: https://github.com/matrix-org/matrix-doc/issues/1938
