### ISSUE TITLE
Rooms are never displayed as unread

### ISSUE THREAD

**Issue by vberger** [vector-im/element-android#345]
The Home screen is always empty saying "You're all caught up", and in the room lists there is never any visual indication that a room contains unread messages, even though if I open the "old" android app or riot-web, they both display several rooms as containing unread messages.

My understanding from the reading the rest of the repository is that it should work... ?

Using the Beta app from GPlay, on Android 8.0.0, with my personal HS running synapse 1.1.0

**Comment by evoL** [comment]
Also, the reading indicator is not synced, which sounds related. I can read the new messages (which are not marked as unread or otherwise indicated as new) on RiotX, but when I go back to Riot/Web, the "Jump to unread" button jumps back before the messages I've read on the phone.

**Comment by vberger** [comment]
Actually it appears the Home screen only shows rooms with "noisy" notifications, and only these rooms have any visual indication of having unread content in the UI.

It would be nice to add such visual indication (like in riot-web & riot-android), and make it possible (configurable?) for the Home screen to also display rooms with non-noisy unread messages.

**Comment by BillCarsonFr** [comment]
Related to #485
