### ISSUE TITLE
Matrix ID is shown sometimes instead of a display name

### ISSUE THREAD

**Issue by chagai95** [vector-im/element-android#3454]
#### Describe the bug
Matrix ID is shown sometimes instead of a display name when replying to a message.

#### To Reproduce

1. reply to some messages.

#### Screenshots
<img src="https://user-images.githubusercontent.com/31655082/120598350-75521300-c446-11eb-8020-10b681c95da3.png" width="50%">

#### Smartphone (please complete the following information):
 - Device: Redmi Note 8 Pro
 - OS: MIUI Global 12.0.4 (Android Version 10)

<img src="https://user-images.githubusercontent.com/31655082/120597982-02e13300-c446-11eb-8436-f774c37faa96.png" width="50%">
https://matrix.chagai.website/_matrix/media/r0/download/chagai.website/woUtcyYvoBzqEXMbOzIMvMNP

#### Additional context
 - App version and store: develop build, apk gplay
 - Homeserver: anconnect-server.aarenet.com

**Comment by MadLittleMods** [comment]
Closing as https://github.com/vector-im/element-android/pull/3735 was merged and this looks like disambiguation
