### ISSUE TITLE
PLEASE make F-droid Repo

### ISSUE THREAD

**Issue by PLAYERUNKNOWNHatsune01** [vector-im/element-android#3458]
Element yesterday released version 1.1.9 and we still stuck on 1.1.7 on fdroid and kinda outdated version and those two update have new features and fix bugs. This problem was discussed on [#3343](https://github.com/vector-im/element-android/issues/3343) [#2727](https://github.com/vector-im/element-android/issues/2747)  [#2698](https://github.com/vector-im/element-android/issues/2698) [2567](https://github.com/vector-im/element-android/issues/2567) and we still hoping we can get repo for fast update because what if there's huge big security hole on the app and needs ta fix fast! The update will arrived but on us that installed the app on fdroid need to wait days or weeks! Hope devs I guess? Will create repo for us we can have fast updates!

**Comment by bmarty** [comment]
As usual, please be patient.
