### ISSUE TITLE
Low priority does nothing for DMs

### ISSUE THREAD

**Issue by LinAGKar** [vector-im/element-android#3463]
#### Describe the bug
If you mark a room as low priority, it's moved into under the low priority header at the bottom, separate from the non-low priority rooms. In Element-web, low-priority DMs are also moved to the same place. In Element-Android however, marking a DM as low priority doesn't do anything; low priority DMs are still mixed in with the regular priority DMs.

#### Smartphone (please complete the following information):
 - Device: Oneplus 8T
 - OS: Android 11

#### Additional context
 - App version and store: 1.1.8 - Google Play
 - Homeserver: Self hosted

**Comment by bmarty** [comment]
Implemented in EA 1.1.14
