### ISSUE TITLE
Restart notification service after closing the app

### ISSUE THREAD

**Issue by ghost** [vector-im/element-android#3495]
#### Describe the bug
After closing the app directly (or using task killer) on smartphones without Google Play Services the notification service doesn't restart and as a result there are no notifications.

#### To Reproduce
1. Open the Element app.
2. Close the Element app.
3. Write a message to that app using another device.
4. See no notifications.

#### Expected behavior
Receive push notifications.

#### Screenshots
After opening the app we can see running Element process.
![1](https://user-images.githubusercontent.com/83540496/121775196-d092ac80-cb8e-11eb-9c1b-9fc831cd15e0.jpg)
But after closing the app there is no process and that's why there are no notifications
![2](https://user-images.githubusercontent.com/83540496/121775199-d4263380-cb8e-11eb-9da9-932a9cd32ec8.jpg)

#### Smartphone (please complete the following information):
 - Device: Meizu M3 Note
 - OS: Android 7.0, Flyme 6.3.5.0A

#### Additional context
 - App version and store 1.1.8 - F-Droid
 - Homeserver: matrix.org
 - No Google Play Services

**Comment by ouchadam** [comment]
Fixed by https://github.com/vector-im/element-android/issues/4298 in 1.3.7
