### ISSUE TITLE
Google Services Gradle plugin is not always applied to build

### ISSUE THREAD

**Issue by erikhuizinga** [vector-im/element-android#3527]
#### Describe the bug

https://github.com/vector-im/element-android/blob/5325c761f4bce9edaf77239f84a3553a0cb135c3/vector/build.gradle#L510-L512

The Google Services Gradle plugin is applied if and only if the Gradle task name being run from CLI contains the substring `"Gplay"`. This is not always the case, even when building a `Gplay` flavor build. For example, `./gradlew` can be run with task `asGD`, which is an unambiguous abbreviation of `assembleGplayDebug`, so Gradle runs that task. However, the logical branch that applies the Google Services Gradle plugin would not be triggered, because `"asGD"` does not contain the `"Gplay"` substring! This can lead to serious issues in production if a release would accidentally be built with a task that doesn't contain the `"Gplay"` substring.

#### To Reproduce
1. Checkout branch `develop`
2. Build using `./gradlew asGD`
3. Install the built APK, run the app.
4. Note the logcat: 

```
            FirebaseApp  W  Default FirebaseApp failed to initialize because no default options were found. This usually means that com.google.gms:google-services was not applied to your gradle project.
   FirebaseInitProvider  I  FirebaseApp initialization unsuccessful
```

This proves that the Google Services Gradle plugin wasn't installed successfully, with consequences like FCM not working like expected.

#### Expected behavior

The build script applies the plugin regardless of the task name specified through the Gradle CLI.

#### Screenshots

N/A

#### Smartphone (please complete the following information):

N/A

#### Additional context

tag `v1.1.9` (and branch develop between that version and the next future version)

---

I'm opening a PR that fixes this issue.

**Comment by bmarty** [comment]
I agree it was a bit ugly to test `contains("Gplay")`, also it was causing problem when building both Gplay and F-Droid APK in the same gradle command... I will review your PR with interest.
