### ISSUE TITLE
Do NOT lie to users about the status of their message

### ISSUE THREAD

**Issue by colemickens** [vector-im/element-android#3532]
#### Describe the bug

Woo, I can not properly express the feelings caused by sending a message from Element Android, getting home, opening Element and realizing that in fact, no, my gd message did not send and instead I'm just ignoring my student.

**Scenario:**
1. Open Element Android (god knows its not synced)
2. I search from my student's name.
3. I tap the conversation.
4. I tap out my message, hit send, looks like my message sent.
5. I hit "home" on Android.

Then, later:
6. I arrive home.
7. I open Element-Web and see my reply is not there.
8. I get my phone out and screenshot it, and see this:
<img src="https://user-images.githubusercontent.com/327028/122604452-d2df8580-d02a-11eb-8c69-9e3efc1c4e93.png" width=200>
LIES! It _is not sent_.

Then, after some time, it **actually sends** and then the truth is revealed:
<img src="https://user-images.githubusercontent.com/327028/122604499-e38ffb80-d02a-11eb-9c65-8ef9fda0009f.png" width=200>

#### To Reproduce
1. Use Element-Android
2. Send messages

#### Expected behavior
The messages send...

#### Screenshots
See above.

#### Smartphone (please complete the following information):
 - Device: Google Pixel 3
 - OS: stock Android 11 (all up to date)

#### Additional context
 - App version and store: 1.1.19 from Google Play Store
 - Homeserver: **matrix.org**

**Comment by subiol** [comment]
Empty circle next to the message means the message has not yet been received by the server, so Element is not lying but telling you the truth.

**Comment by colemickens** [comment]
I thought that was the greyed-out text?

So is the point that Element stops trying to send in the background? I have to wait for the circle to fill before I can switch apps? etc? that doesn't clear a minimum bar for usability, imo.

**Comment by subiol** [comment]
@colemickens that is a legit complain but it is a different issue than the one described in the title. You should close this issue and open a new one (or at least edit the title and the text of this one if you think that is better).

**Comment by ouchadam** [comment]
Element will automatically attempt to resend messages in some error cases, such as regaining network connectivity. I would have thought slow connectivity would have the same behaviour... 

| OFFLINE MESSAGE |
| --- | 
|![offline-message](https://user-images.githubusercontent.com/1848238/143458021-ef05cce8-2ca6-4b28-85c6-8e094c4e3dc0.gif)

we're planning to improve the UX unsent messages scenario with https://github.com/vector-im/element-android/issues/4164, I'm going to close this issue in favour of #4164, feel free to reopen another issue if you think there's a separate use case here!
