### ISSUE TITLE
Audible notifications are broken

### ISSUE THREAD

**Issue by matrixes** [vector-im/element-android#3537]
#### Describe the bug
Audible notifications fail to fire so intermittently that they should be considered to be in a broken state.

##### Preface
You will have to do your own extensive testing on this. As mentioned, the issue is intermittent and there are way too many settings that affect the behaviour of notifications that it's futile to provide all possible combinations as tests.

##### Prerequisites

* Have 2 devices ready
  * Device 1: Any Element client, doesn't really matter
  * Device 2: I have a (freshly factory reset) Google Pixel 3 XL with Android 11 and Element 1.1.9 (40101092) (G-b2485)
* One-on-one chatroom
  * Device 2: Verify that the chatroom notification settings are set to at least "All messages"
* Element
  * Device 2: Verify that the global notification settings are _all_ set to "Noisy"
* Android
  * Device 2: Verify that the notification settings are set to be visible, vibrating and audible

##### Steps to reproduce the behavior:

1. On device 2, verify that you have a one-on-one chatroom with device 1, but don't be in it for the test. E.g. go to Element's chat room overview screen, then close Element (swipe away, or what have you)
2. On device 1, go to the same one-on-one chatroom as mentioned in step 1, type and send a message to the chatroom

#### Expected behavior
At least I expect device 2 to _concistently_ receive a visible, vibrating and audible notification.

#### Experienced behaviour
In all cases, the notification received is visible and vibrating. However, there is no pattern as to when it fails playing a sound.

#### Smartphone (please complete the following information):
 - Device: Google Pixel 3 XL
 - OS: Android 11

#### Additional context
 - App version and store Element 1.1.9 (40101092) (G-b2485) - Google Play
 - Homeserver: self hosted
 - The notification tester in Element work as expected. Every single time I run the test (even repeatedly) I get visible, vibrating and audible notifications.
 - Element is so far the only app I experience these issues with. GMail work as expected, Calendar work as expected, Syncthing work as expected. Element does not.
 - I will be willing to gather more extensive data upon request. I don't know what's relevant to test/send in at this point.

**Comment by matrixes** [comment]
I _may_ have some more information with regards to this issue, but it's still not concistent enough to conclude the issue is clearly related to this situation;

* If I keep Element running in the foreground, I get visible, vibrating and audible notifications.
* If I leave Element, be it either through swiping away the app, or locking my phone, I only get visible and vibrating notifications.

I believe there's something to this, as it would explain why the notification test works; the app is in the foreground, which is a way I've found to be much more consistent in firing off the audio when a notification is received.

**Comment by matrixes** [comment]
I have now reverified that this is a repeatable issue, by installing Element on a Google Pixel 2 with the same OS and app conditions as the example for the Pixel 3 XL above. I used the same account for testing this, and the issue is as previously described;

Have the app open, get visible, vibrating and audible notifications. Leave the app in whichever capacity; Only visible and vibrating notifications get fired, no audio.

**Comment by bahur142** [comment]
This problem is described here:
https://github.com/vector-im/element-android/issues/3243

It happens on Android 8.1+ and when using Wi-Fi. On mobile data there is sound.
It persist since version 1.1.6. Still no fix.

**Comment by matrixes** [comment]
Yeah, I saw that. My issues were even more extreme, though; I didn't get _any_ notification sound no matter WiFi or mobile data. However, I went on a notification crusade just now and enabled _everything under and above the sun_ as Noisy on all my devices, and here's where I think I found something, including the web settings. Lo' and behold, I _now have_ the same experience as in #3243 , which I didn't before.
So at least it looks like now that I get notifications when on data, but not on WiFi. I'll keep testing a bit more and close this if I can consistently get this behaviour to not get to such extremes as the one I registered here.

**Comment by matrixes** [comment]
I'm getting enough indications that this issue has turned into #3243 and will close this, in favour of that.

**Comment by Samonitari** [comment]
Same issue here!

As you @matrixes said in his issue, I consider the notification function as broken (I started out as @matrixes, not getting any notification sound in the background, now, it is just on wifi...)
And for a chat app to have its notifications broken, - sorry dev collegues - I consider the whole app fundamentally broken!

I'd re-open this issue.
It happens to me on wifi too. I the reasonable notifications noisy, but not all. It should work like this (as noisy room messages are generally unwanted) way on mobile data too!
As this is the more general issue out of the two, this should be left open not the other!

**Comment by matrixes** [comment]
@Samonitari If nothing else, there's _two_ of us now that find this bug crippling enough to warrant a "broken" tag. :)
That said, since I at least got to a point where I could reproduce #3243 more consistently, there's been _some_ "improvements" to this issue, as this one states that pretty much any and all notifications are missing sounds.
But yeah, the notifications are still, in my opinion, broken. It's just not in the way that I first reported it. And I'd be a happy camper if they would try and fix it for good.
