### ISSUE TITLE
Sending files doesn't work at all

### ISSUE THREAD

**Issue by dkasak** [vector-im/element-android#3570]
#### Describe the bug

Recently (since a few versions ago, not sure exactly when) file upload completely stopped working for me on Element Android. I discovered this while trying to send photos using EA. 

#### To Reproduce
1. Click `+` in order to attempt to send a file.
2. Click `Camera` (or `Gallery`, or `File`, etc).
3. Select a file to send.
4. The spinner spins forever with the message "Waiting...". The file never gets uploaded.

#### Expected behavior
The file should get uploaded and sent to the room.

#### Smartphone (please complete the following information):
 - Device: Xiaomi Mi A3
 - OS: Android 11

#### Additional context
 - App version: Versions >= 1.1.9 (including the latest beta) from the Play Store
 - Homeserver: termina.org.uk

Here's a [rageshake](https://github.com/matrix-org/element-android-rageshakes/issues/23877) I sent earlier which shows the problem while trying to send a photo.

**Comment by ouchadam** [comment]
I can't say I've noticed this, @dkasak are you still having issues?
