### ISSUE TITLE
code formatting and linebreak rendering is broken (1.1.9)

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-android#3576]
#### Describe the bug

I use [this](https://github.com/anoadragon453/matrix-reminder-bot) beautiful bot by anoa, which posts its manpage as a nicely formatted m.notice with code highlighting when asked.

Instead, everything is just in italics? That does not seem to make much sense.

perhaps related to #3575

#### To Reproduce
1. try a nicely formatted msg

#### Expected behavior
as a mobile app, it can be beneficial to format some things such that they fit the viewport better. however the general markup should still be respected. in this case it is becoming almost illegible.

#### Screenshots
![Screenshot_20210628-150444434](https://user-images.githubusercontent.com/2803622/123641264-5ca90300-d822-11eb-970e-3428948e8bca.jpg)

On desktop (i.e. expected):

![image](https://user-images.githubusercontent.com/2803622/123641293-66326b00-d822-11eb-94c9-051f0271e97e.png)

#### Smartphone (please complete the following information):
 - Device: moto g5s+
 - OS: android 10

#### Additional context 1.1.9 F-Droid
 - Homeserver: private

**Comment by HarHarLinks** [comment]
For reference, this is still in 1.1.12

**Comment by G2G2G2G** [comment]
It's because of the `m.notice` I see when it's `m.message` the <code> blocks aren't ignored anymore. Inconsistent. This is only an issue on phones.

**Comment by HarHarLinks** [comment]
I tried to repro the issue in OP, it appears fixed :tada:

**Comment by th0mcat** [comment]
> I tried to repro the issue in OP, it appears fixed 🎉

This still looks really bad on `develop` for me:

![image](https://user-images.githubusercontent.com/37344783/157521755-835c6948-fd3f-4e35-aee4-40cd2d1f060d.png)

On element-web:

![image](https://user-images.githubusercontent.com/37344783/157521818-5508a2a8-936b-48d7-8f85-1aca894cf2c8.png)

**Comment by HarHarLinks** [comment]
While I agree it isn't great, that's not what I intended with the original issue which as G2G2G2G pointed out had to do with m.notice. This appears fixed (m.text and m.notice look the same now). Perhaps you want to open a new "Enhancement" issue for syntax highlighting?

I can't repro your linebreak issue either:
![image](https://user-images.githubusercontent.com/2803622/157542203-e8352613-60eb-4011-85aa-a3f5577ee135.png)
Though admittedly the *slanting* isn't great, at least it works at all.

**Comment by th0mcat** [comment]
My apologies, I should have been clearer.  For now, disregard the syntax highlighting as that's a different feature request.  In my example, when I put code inside a code block, none of the formatting is preserved on Element Android.  The line after `def file_add():` is not indented like it is in my Element Web example.

**Comment by HarHarLinks** [comment]
indeed I noticed in your example a lot of whitespace is missing. however the json I tried is ok. might you post your code here for me to try?

did you use a simple codeblock without language hint, or did you give a language hint? in my case both look the same.

**Comment by th0mcat** [comment]
I tried with/without a language hint in different rooms, same result.  It's just a simple python script.

```
#123
import csv

def file_add():
    file = open("salaries.csv","a")
    name = input("Enter a name: ")
    pay = input("Enter salary: ")
    print()
    record = name + "," + pay + "\n"
    file.write(str(record))
    file.close()

def file_read():
    file = open("salaries.csv","r")
    print("\n" + file.read())

def rec_del():
    file = list(csv.reader(open("salaries.csv")))
    tmp = []
    for row in file:
        tmp.append(row)

    rn = 0
    for row in tmp:
        print(rn, row)
        rn+=1
    select = int(input("Which user would you like to delete? "))
    del tmp[select]
    print()

    file = open("salaries.csv","w")
    x = 0
    for row in tmp:
        newAppend = tmp[x][0] + "," + tmp[x][1] + "\n"
        file.write(newAppend)
        x = x + 1
    file.close()

    file = open("salaries.csv","r")
    print(file.read())
    file.close()

def main():
    choice = 0
    while choice != 4:
        print("\n1) Add to file\n2) View all records\n3) Delete a record\n4) Quit program\n")
        choice = int(input("Enter the number of your selection: "))
        if choice == 1:
            file_add()
        if choice == 2:
            file_read()
        if choice == 3:
            rec_del()
        if choice < 1 or choice > 4:
            print("\n\nWRONG\n")

main()
```

**Comment by HarHarLinks** [comment]
![image](https://user-images.githubusercontent.com/2803622/157579248-b50a2b40-99c2-48f1-9313-e6165f8b376e.png)
however if you I include non-code block text:
![image](https://user-images.githubusercontent.com/2803622/157579473-65f4bca3-2bfc-436b-92ce-e8c96598616e.png)

I would say we (you?) should open 2 issues:
1. code highlighting
2. broken code blocks when there is text alongside them
