### ISSUE TITLE
Element Android reuses txnId for to-device events in the verification process

### ISSUE THREAD

**Issue by timokoesters** [vector-im/element-android#3589]
There are two types of transaction ids in the to-device verification process:
The txnId, which is a path parameter for the /sendToDevice request. As far as I understand, this should never be reused unless the previous try failed (https://spec.matrix.org/unstable/client-server-api/#put_matrixclientr0sendtodeviceeventtypetxnid).
Then there is a transaction_id field that is shared by the other messages of the verification session (https://spec.matrix.org/unstable/client-server-api/#key-verification-framework).

Element Android uses the same id for both txnId and transaction_id, so on Conduit most sendToDevice requests are dropped because the txnId was already used before. This is probably the reason for https://github.com/vector-im/element-android/issues/3183

How to fix:
Only use the session's transaction_id for the transaction_id field of verification message contents. Generate a new id for the txnId of /sendToDevice requests.

**Comment by bmarty** [comment]
That's very good catch. We will have a look

**Comment by bmarty** [comment]
Should be fixed on develop and in Element Android 1.1.14.

@timokoesters should be nice if you can confirm that! Thanks
