### ISSUE TITLE
New call designs

### ISSUE THREAD

**Issue by ganfra** [vector-im/element-android#3599]
Implement new designs: 

- [x]  In call controls
- [x] Timeline tiles
- [x] Draggable PiP 
- [ ] Jitsi notification
- [x] Jitsi close conf
- [x] Jitsi join conf

Figma link: https://www.figma.com/file/V6m2z0oAtUV1l8MdyIrAep/VoIP?node-id=4254%3A25767&viewport=241%2C48%2C0.07

**Comment by ariskotsomitopoulos** [comment]
Closing this issue it seems fixed in **v1.3.8**
