### ISSUE TITLE
Automatically resend message

### ISSUE THREAD

**Issue by jtagcat** [vector-im/element-android#361]
Few weeks I was on a very bad connection (no service, like 10/5 Wifi for 50 people). When I tried to send a message it would fail due to no connection. I had brief 'network spikes', where I would get ok connection, but hitting the resend all button in time was a problem.

Some way to implement auto-resend. The best way to implement it in my opinion would be to replace the resend all button with nothing and keep the cancel all button (for occurrences, where users intentionally turn off networking in order to quickly abort sending sensitive information.

**Comment by bmarty** [comment]
With the current implementation, messages are queued up and stored if the network is not  available. When the network is back, the messages should be automatically sent

**Comment by fbruetting** [comment]
In the last weeks, this has been a major recurring problem, so it seems that this store-and-retry function doesn’t work reliably (or just for connection-less cases, but not for server-overload cases).

Additionally, it would be cool if unsent messages after some time (~10 seconds?) would produce a notification with the option to resend – and if these unsent messages could be shown as unsent in the home screen, for making sure that users recognize.

**Comment by bmarty** [comment]
Please re-open if you observe again the problem with Element 1.0.6 (not yet released)
