### ISSUE TITLE
How many days is the Crash Reporting data kept?

### ISSUE THREAD

**Issue by konomikitten** [vector-im/element-android#3628]
I asked in the Element Android room and got not response, my question is how long are our crash reports kept before being deleted? I found this passage in the privacy policy:

> When reporting errors we might collect some information to help us find a solution. This may include your IP address, hostname, full name and e-mail address. This information is collated in the application monitoring platform Sentry and is subject to strict retention policies.

But it doesn't offer any clarity on what "strict retention polices" are.

**Comment by bmarty** [comment]
Crash report data are never deleted AFAIK.

> "strict retention polices"

Those data are not public. They are stored in a private GitHub repository and the logs and screenshot are store on a private server administrated by New Vector Ltd.

**Comment by konomikitten** [comment]
@bmarty that doesn't seem very privacy focused or much of a strict retention policy to me. As a user who values privacy having my device data and sometimes even screenshots of my chat windows in these "error reports" being retained indefinitely is extremely disturbing.

I would like to see the privacy policy updated to reflect this policy if true and not vague lines such as "subject to strict retention policies" that tells users nothing about the actual data retention.

**Comment by ara4n** [comment]
we deliberately don't delete bug report data, given it gets turned into bug tickets which we then regularly refer to as we go through fixing bugs (which unfortunately can take years).  The logs themselves deliberately contain minimal sensitive data (no keys or secrets or message contents are logged).  Room IDs and user IDs are logged however (as otherwise it's almost impossible to debug meaningfully).  If the user chooses to include a screencap then obviously that's logged too.

If this is a problem for you, you can always GDPR erase your data from our systems as per the privacy policy for Element by mailing gdpr@matrix.org.

**Comment by konomikitten** [comment]
> we deliberately don't delete bug report data, given it gets turned into bug tickets which we then regularly refer to as we go through fixing bugs (which unfortunately can take years).

I don't see why you'd need to keep the report data indefinitely, it would be pretty easy to say "well this bug has either been fixed or hasn't been touched for say 100 days so we can just get rid of it".

> The logs themselves deliberately contain minimal sensitive data (no keys or secrets or message contents are logged). Room IDs and user IDs are logged however (as otherwise it's almost impossible to debug meaningfully).

That's good to know.


> If this is a problem for you, you can always GDPR erase your data from our systems as per the privacy policy for Element by mailing [gdpr@matrix.org](mailto:gdpr@matrix.org).

Only people in the EU can exercise the rights granted by the GDPR, so that's not really an option for all of us?

Making a few small changes and clarifying how crash report data is kept in the privacy policy would definitely reassure myself and probably others that Element and by extension Matrix care about user privacy.

**Comment by ara4n** [comment]
> I don't see why you'd need to keep the report data indefinitely, it would be pretty easy to say "well this bug has either been fixed or hasn't been touched for say 100 days so we can just get rid of it".

We could delete the logs if we've fixed the bug.  If we haven't, then we need to keep the logs around so we can check things like how frequently a given problem is coming up, or go and spot patterns across logs of the same issue filed by different people etc.  Unfortunately it can take us over 100 days to get to lower priority issues, and meanwhile some of the harder ones (e.g. E2EE issues) have remained unsolved for over 100 days despite us working on them.

> Only people in the EU can exercise the rights granted by the GDPR, so that's not really an option for all of us?

Anyone in the world is welcome to use the data protection mechanisms which we're obligated to provide to EU citizens for GDPR (for precisely this reason, if you have changed your mind on sending us some data and want us to erase it).

> Making a few small changes and clarifying how crash report data is kept in the privacy policy would definitely reassure myself and probably others that Element and by extension Matrix care about user privacy.

Noted. cc @deniseal with her DPO hat on to ensure we spell this out correctly.

**Comment by konomikitten** [comment]
> We could delete the logs if we've fixed the bug. If we haven't, then we need to keep the logs around so we can check things like how frequently a given problem is coming up, or go and spot patterns across logs of the same issue filed by different people etc. Unfortunately it can take us over 100 days to get to lower priority issues, and meanwhile some of the harder ones (e.g. E2EE issues) have remained unsolved for over 100 days despite us working on them.

That's fair and I understand it to a degree, I just wish that it wasn't necessary to keep the data forever, surely bugs become stale eventually.

> Anyone in the world is welcome to use the data protection mechanisms which we're obligated to provide to EU citizens for GDPR (for precisely this reason, if you have changed your mind on sending us some data and want us to erase it).

That's reassuring to know.

> Noted. cc @deniseal with her DPO hat on to ensure we spell this out correctly.

That would be a welcome change, could there also be a warning when sending a bug with a screenshot that users should make sure that no private information is displayed in their screenshot before sending the report?

Thank you for addressing my concerns, I really appreciate it.

**Comment by beercanchicken** [comment]
> > I don't see why you'd need to keep the report data indefinitely, it would be pretty easy to say "well this bug has either been fixed or hasn't been touched for say 100 days so we can just get rid of it".
> 
> We could delete the logs if we've fixed the bug. If we haven't, then we need to keep the logs around so we can check things like how frequently a given problem is coming up, or go and spot patterns across logs of the same issue filed by different people etc. Unfortunately it can take us over 100 days to get to lower priority issues, and meanwhile some of the harder ones (e.g. E2EE issues) have remained unsolved for over 100 days despite us working on them.
> 
> > Only people in the EU can exercise the rights granted by the GDPR, so that's not really an option for all of us?
> 
> Anyone in the world is welcome to use the data protection mechanisms which we're obligated to provide to EU citizens for GDPR (for precisely this reason, if you have changed your mind on sending us some data and want us to erase it).
> 
> > Making a few small changes and clarifying how crash report data is kept in the privacy policy would definitely reassure myself and probably others that Element and by extension Matrix care about user privacy.
> 
> Noted. cc @deniseal with her DPO hat on to ensure we spell this out correctly.

First off, thank you to you and your team for the hard work making a great first generation Matrix app.  It has a few bugs but the Hydrogen project looks promising.  My friends, family and teammates using it are generally satisfied with it overall.

Future feature idea: track bug report submission IDs (first, as local client data; later, on the home server) and have an option to send a deletion request to the bug report server mechanism.  This would require development investment but would fall in line with the privacy goals of the ecosystem.  Hope the F-Droid repository happens soon--that may cut down on duplicate bug reports, given that the current F-Droid version of Element is just over a month old.

**Comment by deniseal** [comment]
> Making a few small changes and clarifying how crash report data is kept in the privacy policy would definitely reassure myself and probably others that Element and by extension Matrix care about user privacy.

I am taking it as an action to discuss with the teams how we store (and dispose of) crash report data and will be making changes to our privacy policy based on the outcome of that discussion.

Thank you for your feedback - if you see any other problems with our existing policies please feel free to open an issue in [this repository ](https://github.com/vector-im/policies) or email us at dpo@matrix.org.

**Comment by konomikitten** [comment]
> I am taking it as an action to discuss with the teams how we store (and dispose of) crash report data and will be making changes to our privacy policy based on the outcome of that discussion.

Thank you for looking into this I really appreciate it and thanks to the entire team while I'm at it, I use Element and Matrix on a regular basis so thank you for all the hard work.

**Comment by konomikitten** [comment]
I think this issue has been addressed, closing this now.
