### ISSUE TITLE
Ringback tone does not sound on silent

### ISSUE THREAD

**Issue by giannissc** [vector-im/element-android#3642]
#### Describe the bug
Ringback (dialing feedback) tone does not sound if phone is silent

#### To Reproduce
1. Put phone on silent
2. Call someone
3. Notice ring tone not sounding

#### Expected behavior
If i ring someone i expect a confirmation ringing tone to sound regardless of the state of the phone. This has been the expected behaviour when calling someone since phones were created.

**Comment by bmarty** [comment]
If the user puts their phone on silent, I guess it's to avoid to be annoyed by a ringing call.

**Comment by giannissc** [comment]
Yeah but you are initiating the call and you want some feedback that you call went through and it is ringing on the other end. I cant can't count the time where i had to get my phone of my ear ti make sure that i am actually calling the other person. It is just bad user experience. That's why every phone and calling app on the planet follows the same approach.. It just work and if it's not broken dont fix it!

**Comment by giannissc** [comment]
Another thing is that if i get a feedback ringing sound when i am calling sound then that sound can be changed to different sounds depending if the user rejected the call or if it has timed out

**Comment by giannissc** [comment]
The iOS version of the app seems to be doing this right. Even when the phone is on silent there is a ringing confirmation tone to let you know that the all is currently in progress. @bmarty

**Comment by giannissc** [comment]
Closing this as it seems to be a duplicate of #3221
