### ISSUE TITLE
Give us one tab for all chat like telegram

### ISSUE THREAD

**Issue by AnisTaluqdar** [vector-im/element-android#3645]
I like all chat in one tab or page. As like telegram. I like to see the option to marge direct chat and room together in one tab.
There have a option for unread massage we can spare it or marge it like wise give a option to marge direct chat and room together.

Thanks

**Comment by HarHarLinks** [comment]
If I understand you correctly, https://schildi.chat/android/ does what you want.

**Comment by aniseeo** [comment]
I know that but schildichat have some bug.

**Comment by kojid0** [comment]
This is a duplicate of #650 
Please upvote that issue in order to give it more attention

**Comment by kojid0** [comment]
This is a duplicate of #650 which has a lot more upvotes. This issue can be closed.
Also @BillCarsonFr seems to work on tabs currently.

**Comment by bmarty** [comment]
Closed in favor of #650
