### ISSUE TITLE
unnamed rooms show roomid in space room management screen

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-android#3647]
#### Describe the bug
unnamed rooms show roomid in space room management screen
especially DMs

#### To Reproduce
1. Go to Space -> Manage rooms and spaces

#### Expected behavior
human readable names

#### Smartphone (please complete the following information):
 - Device: [e.g. Samsung S6]
 - OS: Android 10

#### Additional context
 - App version and store 1.1.11
 - Homeserver: [e.g. matrix.org]

**Comment by kittykat** [comment]
Duplicate of #3376
