### ISSUE TITLE
Add translation for american / united states english

### ISSUE THREAD

**Issue by benwaffle** [vector-im/element-android#3677]
#### Is your feature request related to a problem? Please describe.
I see text like "Favourites" in the app, but in the US it should be spelled "Favorites"

#### Describe the solution you'd like.
A new locale in weblate, en-US, should allow people to add spelling different from en-GB.

**Comment by bmarty** [comment]
Hello, en-US is the default value on Android platform, but anyone can create a new language for en-GB in Weblate. I will try to make it clear that all the translations will not have to be put in this language, but only the one which differ from the original one.

So to change the default value to proper US values, we have to edit this [source file](https://github.com/vector-im/element-android/blob/develop/vector/src/main/res/values/strings.xml). A PR will be appreciated!

Detected mistake:
- `favourites`
- `unrecognised`
- TBC...

**Comment by bmarty** [comment]
I've done the Weblate part:

<img width="1089" alt="image" src="https://user-images.githubusercontent.com/3940906/125769854-e83a0cd2-b1b7-4f9c-9c33-cfbc21dc234c.png">
