### ISSUE TITLE
Missing `device_one_time_keys_count` in sync response causes no keys to be uploaded

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-android#3725]
https://github.com/matrix-org/synapse/pull/10214 was recently merged to synapse which caused it to omit the `device_one_time_keys_count` section if no OTKs of any type were present. Element android only calls `updateOneTimeKeyCount` if the section is present (https://github.com/vector-im/element-android/blob/2864101e2aa2368ceac89e7532b6944530a8bdb4/matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/DefaultCryptoService.kt#L417) so this caused a new session to never upload any OTKs, meaning all messages would be undecryptable.

**Comment by bmarty** [comment]
Currently handled in #3724 (in progress)

**Comment by deepbluev7** [comment]
This issue may be one of the reasons, why E2EE doesn't work properly on Conduit.

**Comment by bmarty** [comment]
Fixed in #3724 
Element Android 1.1.14
