### ISSUE TITLE
Add a fallback for user displayName when this one is null or empty

### ISSUE THREAD

**Issue by yostyle** [vector-im/element-android#3732]
Actually if user displayName is null or empty the function `getBestName()` return the matrixId.
It should be better to have a fallback as for the room name :`RoomDisplayNameFallbackProvider`

For example we have this fallback on Tchap : https://github.com/tchapgouv/tchap-android-v2/blob/27fd9730546e7f51734868e61433cb5a4bf4cafd/vector/src/main/java/fr/gouv/tchap/core/utils/TchapUtils.kt#L89

**Comment by bmarty** [comment]
The current plan is:
- delete all existing `getBestName()` method
- SDK side, create a `DisplayNameService`, with one method `getBestName(matrixItem)`
- On `MatrixConfiguration`, add an interface to let the app provide an optional `userDisplayNameFallbackProvider`. If null, default fallback will still be the matrixId
- The SDK implement `DisplayNameService` in `DefaultDisplayNameService`, injecting the `MatrixConfiguration`.
- `DisplayNameService` is available from the session

**Comment by bmarty** [comment]
In EA 1.3.2
