### ISSUE TITLE
Entering back ticks doesn't format text as a code block

### ISSUE THREAD

**Issue by hwittenborn** [vector-im/element-android#3733]
This only happens on messages I _send_. Any messages sent by other people appear as normal code blocks. Messages I send on the other hand appear as literal tick marks when sent (haven't confirmed if it also appears as such on things like Desktop when sending from mobile).

**Version:** 1.1.12 [40101121] (G-b2723)

**Comment by hwittenborn** [comment]
This is what it normally looks like:

![Capture+_2021-07-23-12-15-56(1).png](https://user-images.githubusercontent.com/74838472/126818237-47b1a5ed-fc6e-431e-91fb-78535f7c2fbd.png)

**Comment by pythonInRelay** [comment]
Have you tried 3 backticks?

**Comment by hwittenborn** [comment]
Doesn't appear to be working with that either:

![Capture+_2021-07-23-21-26-06(1).png](https://user-images.githubusercontent.com/74838472/126854957-ce9d0447-3827-4e44-9c2b-015505957722.png)

**Comment by hwittenborn** [comment]
This variation also isn't working any different than the above ones:


```
\`\`\`
hi
\`\`\`
```

**Comment by Y0ngg4n** [comment]
Same here

**Comment by T-bond** [comment]
For me it works.
1.1.12 [40101120] (F-2da03795)
Do you have Markdown support enabled in the settings?

**Comment by hwittenborn** [comment]
Strangely the issue fixed itself the other day, and I didn't have markdown support enabled at the time. I've went ahead an enabled it though, and it's all working regardless.

**Comment by Y0ngg4n** [comment]
@T-bond where is the option for markdown support? I cant find it.

**Comment by T-bond** [comment]
@Y0ngg4n Settings (global, not room) > Preferences
It is the first option in the ,,Message editor" section.
![SmartSelect_20210726-175213_Element](https://user-images.githubusercontent.com/3778556/127019787-c84ef4c9-2eda-4d94-8d6f-98a79a22c43a.jpg)

**Comment by Y0ngg4n** [comment]
@T-bond Thanks
