### ISSUE TITLE
Infinite number of same chats can be created.

### ISSUE THREAD

**Issue by ghost** [vector-im/element-android#3746]
#### The bug
We can create two or more valid Direct Messages with the same person.

#### To Reproduce
Steps to reproduce the behavior in Element Android:
1. Add new chat with person X.
2. Again, add new chat with person X.

#### Expected behavior
There should be only one chat - the same way as Web/iOS Element client handling it.

#### Screenshots
![Two conversation with the same person.](https://user-images.githubusercontent.com/87245511/127372210-2cb8a934-b124-4939-81a0-6e7b096baf32.png)

#### Additional context
 - Only Element Android. Probably missed validation in https://github.com/vector-im/element-android/blob/00911a7f7ef8d398c0af4f3b31384fa95c8dcbc7/vector/src/main/java/im/vector/app/features/createdirect/CreateDirectRoomViewModel.kt#L85

**Comment by MadLittleMods** [comment]
Closing in favor of https://github.com/vector-im/element-android/issues/2893
