### ISSUE TITLE
M11.11 Spaces | Expose legacy Communities -> Space migrator 

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-android#3753]
* Somewhere sensible, we should let people know a migrator exists on Element Web
* Related issue: https://github.com/vector-im/element-web/issues/18092

**Comment by niquewoodhouse** [comment]
@BillCarsonFr 

fwiw this is what we have in design

<img src="https://user-images.githubusercontent.com/1587166/135426775-ced39197-fd7f-44db-b051-eb5588b56ec8.png" width="360">

**Comment by kittykat** [comment]
Since communities are being removed on Web, I don't think we need the migrator on Android any more
