### ISSUE TITLE
Going back and I'm still in the same room

### ISSUE THREAD

**Issue by chagai95** [vector-im/element-android#3769]
#### Describe the bug
When clicking on the back button in the top right I stay in the same room.

#### To Reproduce

1. Not sure but it happens a lot

I sent the logs mentioning this GitHub ticket

#### Screen recording
https://photos.app.goo.gl/SQDJk7sWz6AuHmhj6

#### Smartphone (please complete the following information):
 - Device: Redmi Note 8 Pro
 - OS: MIUI Global 12.0.4 (Android Version 10)

![image](https://user-images.githubusercontent.com/31655082/120597982-02e13300-c446-11eb-8436-f774c37faa96.png)

#### Additional context
 - App version and store: Google Play Beta Tester 1.1.14
 - Homeserver: https://matrix.chagai.website

**Comment by daniellekirkwood** [comment]
@chagai95 👋  Could you confirm that this is still an issue?

**Comment by chagai95** [comment]
Haven't seen this for quite some time so no, I can't confirm... 😉

**Comment by daniellekirkwood** [comment]
Awesome - I'm going to go ahead and close this out but let us know if you run into it again and we'll take a look!
