### ISSUE TITLE
When accepting an invite, expecting to see the room

### ISSUE THREAD

**Issue by jaywink** [vector-im/element-android#3771]
When I accept an invitation to a room, after the invite is processed I would expect to see the room. Instead it is hidden somewhere in my room list, forcing me to use search to find it, to find out if there are any messages there for me to react to.

**Comment by bmarty** [comment]
It's done like that to be able to accept multiple invitations in a row. If you want to enter the room, first click on the invite item (not the button), and then accept the invitation in the next screen.

**Comment by bmarty** [comment]
In EA 1.4.2

> Also room can be joined from the invite notification, I'm not sure we open the room in this case.

This use case may be handled later.
