### ISSUE TITLE
Call tile layout changes

### ISSUE THREAD

**Issue by gaelledel** [vector-im/element-android#3775]
In order to respond to internationalization issues on mobile call tiles, some layout changes were required
Please see the specs in Figma below in the Android columns
Please also note that colours were also simplified. E.g: icons were tertiary, they are now all secondary
I have also updated the video icon

https://www.figma.com/file/V6m2z0oAtUV1l8MdyIrAep/VoIP?node-id=2863%3A45199

**Comment by kittykat** [comment]
@gaelledel can this issue be closed now?

**Comment by gaelledel** [comment]
@kittykat If the work was done yes. I haven't seen any of the work done on Android.

**Comment by kittykat** [comment]
Yes, the designs match in 1.3.8
