### ISSUE TITLE
Element Android doesn't send a JSON body for POST `/rooms/{roomId}/receipt/{receiptType}/{eventId}`

### ISSUE THREAD

**Issue by reivilibre** [vector-im/element-android#3789]
Element Android currently doesn't send a JSON body for POST `/rooms/{roomId}/receipt/{receiptType}/{eventId}`.

It should send a request body, even if that would be the empty body `{}`.

This was noticed as part of recent changes in Synapse v1.40.0rc1; a workaround (https://github.com/matrix-org/synapse/pull/10531) will be put into Synapse v1.40.0rc2:

The spec is, at the time of writing, wrong (see https://github.com/matrix-org/matrix-doc/issues/3237) but is being fixed by https://github.com/matrix-org/matrix-doc/pull/3238.

**Comment by bmarty** [comment]
Fixed in EA 1.2.1
