### ISSUE TITLE
Error when sending encrypted message

### ISSUE THREAD

**Issue by MaxPower654** [vector-im/element-android#3792]
#### Describe the bug
After upgrading to 1.1.15,  some android users are unable to send encrypted messages to a room with multiple members.
There is a error message like "Did not sent message, retry?"
Some 1:1 chats were also affected. 
After rolling back to v.1.1.12 or using schildi.chat the issue was gone.

#### To Reproduce
1. Send encrypted message to room
2. See error

#### Expected behavior
I would expect the message to be encrypted and sent.

#### Screenshots
![sendfail](https://user-images.githubusercontent.com/88454888/128234826-b68c9d96-df93-47e1-b7d9-756f7eb07de6.jpg)

#### Smartphone (please complete the following information):
 - Device: at least Pixel 4a
 - OS: Android 11

#### Additional context
 - 1.1.15 F-Droid and Google Play
 - Private Homeserver, v.1.37

From the behaviour, I would expect this issue to be a duplicate from https://github.com/vector-im/element-web/issues/17195, but on android. 
I already checked if the encryption event was redacted, but it seems to be fine.

**Comment by voice06** [comment]
I can confirm I am seeing this issue as well with 1.1.15, I am not longer able to send encrypted messages, but I can from Web or Desktop.

**Comment by william-caylent** [comment]
I had two users report this issue to me. they both reinstalled the application from scratch and it resolved the issue. I also have an android device and have not had this issue.

**Comment by williamkray** [comment]
I had two users report this issue to me. they both reinstalled the application from scratch and it resolved the issue. I also have an android device and have not had this issue.

**Comment by MaxPower654** [comment]
I can confirm that the issue was resolved after clearing cache and storage from Android settings, but it came back shortly after that.

-------- Original-Nachricht --------

**Comment by delroth** [comment]
I've hit the same issue today and have heard reports from at least two other people on two different encrypted rooms.

**Comment by miniature-igloo** [comment]
Many people on my server are having this issue. It's happening across many different encrypted rooms. 

I've had them uninstall/reinstall & log out and log back in. Both of these work for a while, but the issue comes back. 

It's limited to Android 1.1.15. Not happening for any of the people using iOS app, desktop app, or a release before 1.1.15.

**Comment by miniature-igloo** [comment]
I just checked to see if in the rooms that it is happening in had their 'm.room.encryption' events redacted. None of them did. None of the rooms on the server have had the 'm.room.encryption' event redacted.

**Comment by manuroe** [comment]
The bug happens once you logged out from a device:

To reproduce it:
- User A has 2 devices: A1 and A2
- User B has B1 (having User B is probably not mandatory
- A sends messages to a room with B
- A logs out from A2

-> A cannot send messages from A1 anymore

**Comment by pkern** [comment]
For what it's worth, I did not log out anywhere and still got that persistent error on Android. It just suddenly started yesterday, not even directly connected with an app update.

**Comment by manuroe** [comment]
> For what it's worth, I did not log out anywhere and still got that persistent error on Android. It just suddenly started yesterday, not even directly connected with an app update.

thanks @pkern. There might be another issue. Can you rageshake mentioning this issue (3792), please?

**Comment by onurays** [comment]
> For what it's worth, I did not log out anywhere and still got that persistent error on Android. It just suddenly started yesterday, not even directly connected with an app update.

It is happening even if other users log out. I am preparing a release including the fix.

**Comment by miniature-igloo** [comment]
What is the expected timeline to get this fix onto Google Play? This has crippled my server.

**Comment by MaxPower654** [comment]
> What is the expected timeline to get this fix onto Google Play? This has crippled my server.

This is an excellent question. Any information @onurays ?
My users are unable to write messages on a messaging platform...
