### ISSUE TITLE
Minimum Android version? 

### ISSUE THREAD

**Issue by LinAGKar** [vector-im/element-android#3807]
What's the minimum Android version required for this? I don't see this indicated anywhere, it would be nice if it was included in the README like it was for old Riot-android.

**Comment by RocketJannis** [comment]
According to this line it's API 21: https://github.com/vector-im/element-android/blob/develop/vector/build.gradle#L114

This would mean Android 5.0 (see https://en.wikipedia.org/wiki/Android_version_history)
