### ISSUE TITLE
Error Sending Messages to one person

### ISSUE THREAD

**Issue by zethra** [vector-im/element-android#3809]
#### Describe the bug
When I attempt to send a message to one specific person it always fails with the "Messages failed to send" message, and reties all fail. I'm able to send message to other people with no issue. I can still receive message from that room and send them from the desktop. I changed my display name from element desktop right before this started, idk if that's related. This is an encrypted room. I've tried running "clear cache" in the setting and that didn't fix it.

#### To Reproduce
I try to send a message to this one user. idk how ya'll could reproduce it but I'll supply anything I can.

#### Expected behavior
Messages send with no issue.

#### Smartphone (please complete the following information):
 - Device: Pixel 2 XL
 - OS: Android 11

#### Additional context
 - App version and store: 1.1.15 [40101152] (G-b2969_ from the Play Store
 - Homeserver: matrix.org, the other user is on the-apothecary.club

**Comment by benneti** [comment]
do you know whether you or the other person logged out of a session recently?

**Comment by zethra** [comment]
The other person said they were trying a new client recently

**Comment by benneti** [comment]
Then I guess it could be the same problems me and two of my contacts have, you can also try schildichat as it seems to work for me.

**Comment by zethra** [comment]
Thanks for the suggestion, but I'll probably just wait until they push out a patch

**Comment by DoM1niC** [comment]
I had the same issue and this was fixing my Problem https://github.com/vector-im/element-android/pull/3804 but the Release is not out official so wait some days or use the Nightly APK https://github.com/vector-im/element-android/actions/runs/1105196833

**Comment by zethra** [comment]
Latest update fix the problem
