### ISSUE TITLE
Messages fail to send

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-android#3813]
#### Describe the bug
Messages fail to send. Has been happening over the last week, becoming more prevalent over time. Present both in rooms and direct messages. I've submitted two rageshakes: one last week, one today. Resending message doesn't work.

Clearing cache didn't fix the issue, but logging out and back in again appears to have done it.

#### To Reproduce
Steps to reproduce the behaviour:
1. Go to a room
2. Type and send a message
3. See error

#### Expected behaviour
Message sends

#### Screenshots

![Screenshot_20210809-232919.png](https://user-images.githubusercontent.com/51663/128782391-15b549cb-5e49-4bc2-b021-a58b6d50468b.png)

#### Smartphone (please complete the following information):
 - Device: Google Pixel 2
 - OS: Android 11

#### Additional context
 - App store, version 1.1.15 [40101152] (G-b2969)
 - Homeserver: matrix.org

**Comment by callahad** [comment]
This is a known issue (#3792) which is fixed in 1.1.16 -- you should be able to manually check for updates in the Play store to resolve.
