### ISSUE TITLE
Support for hidden read receipts (MSC2285)

### ISSUE THREAD

**Issue by SimonBrandner** [vector-im/element-android#3831]
[MSC2285](https://github.com/matrix-org/matrix-doc/pull/2285) is now supported by Synapse and Element Web, it would be super nice, to get support on Android too

**Comment by vaguerant** [comment]
Tagging a couple of relevant issues.

Previous request for this feature, seems to be more active: #2436
PR which merged this feature into spec: matrix-org/matrix-spec#1216

**Comment by SimonBrandner** [comment]
Closing in favour of https://github.com/vector-im/element-android/issues/2436
