### ISSUE TITLE
Enhancement: Share multiple files

### ISSUE THREAD

**Issue by brandsimon** [vector-im/element-android#3846]
If I want to send multiple files to someone, I am used to select all files in a folder and share it. This is not possible with element currently, It is only possible to send one file, then the next, and so on, what is annoying for many files.

**Comment by bmarty** [comment]
Selecting multiple files to send them in a row is possible with Element Android, either coming from an external app (ex Google Photo, select multiple element then share to Element Android) or by clicking on "+" next to the composer in a room and then select multiple items.

Maybe it's a limitation on your device?

**Comment by brandsimon** [comment]
@bmarty 
This did not work on 1.1.4 for me on two devices, but with 1.2.0 it works fine.
Thank you very much.
