### ISSUE TITLE
Focus search bar when opening Reactions view

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-android#3869]
#### To Reproduce
1. Press and hold on a message to pop up menu
2. Click on 'Add Reaction' (why is "Add Reaction" capitalised like that, while "Report content" is the other way?)

#### Expected behaviour
Search is focused (like on other apps)

#### Actual behaviour
Search is not focused and clicking in the "top bar" area doesn't bring it up, only the search icon does

#### Smartphone (please complete the following information):
 - Device: Pixel 2
 - OS: Android 11

#### Additional context
 - App store, version 1.1.15 [40101152] (G-b2969)
 - Homeserver: matrix.org

**Comment by ryg-git** [comment]
If it is okay I would like to work on this issue.

**Comment by bmarty** [comment]
@ryg-git sure, thanks for letting us know!

**Comment by bmarty** [comment]
> why is "Add Reaction" capitalised like that, while "Report content" is the other way?

@kittykat I would be happy to harmonize the capitalization. This is what we have now:

<img width="194" alt="image" src="https://user-images.githubusercontent.com/3940906/135102631-221a5ccb-d54d-4c9e-9827-77fdb31473a9.png">

So maybe change "Add Reaction" to "Add reaction" and "View Source" to "View source" (only visible in developer mode) would be OK. Do you confirm?
