### ISSUE TITLE
Voice message lock mechanism is incompatible with gesture navigation

### ISSUE THREAD

**Issue by robintown** [vector-im/element-android#3878]
#### Describe the bug

If your phone uses gesture navigation, it is impossible to use the voice message slide-to-lock feature, since sliding upwards from the voice message button is interpreted as trying to close the app.

#### To Reproduce

1. Enable gesture navigation on your phone
2. Press and hold the voice message button
3. Attempt to slide upwards to lock the recording

#### Expected behavior

An upwards swipe should lock the recording instead of trying to close the app

#### Screenshots

https://user-images.githubusercontent.com/48614497/130335718-ac906310-2be0-4a5e-ae9a-64f3babebd85.mp4

#### Smartphone (please complete the following information):

 - Device: Google Pixel 3a
 - OS: LineageOS 15.1

#### Additional context
 - App version and store: 1.2.0 - F-Droid

**Comment by dipeve** [comment]
Maybe Lineage use another kind of gesture navigation, in my S21 and Pixel 3, both with stock roms, I can use the lock voice without issues.

**Comment by robintown** [comment]
Maybe, I also need to upgrade to LineageOS 16.1 so perhaps it's no longer a problem in recent versions

**Comment by robintown** [comment]
Still occurs with LineageOS 18.1

**Comment by robintown** [comment]
I finally determined that turning off 'Swipe to invoke assistant' in gesture navigation settings fixes this issue. Since I don't care about assistants, I don't think it's necessary to leave this open.
