### ISSUE TITLE
mic is overlaps send button on reply

### ISSUE THREAD

**Issue by 532910** [vector-im/element-android#3906]
### Steps to reproduce

I dunno how to reproduce this, sometimes it happens, sometimes not.
1. Swipe a message left to reply

### What did you expect?

If fact I expect a mic button to reply with a voice message.

### What happened?

![image](https://user-images.githubusercontent.com/14617699/130971809-1152aec0-08b3-44b2-9485-e3a2ac462708.png)

### Your phone model

OP3T

### Operating system version

11

### Application version and app store

1.2.0 from GPlay, beta channel

### Have you submitted a rageshake?

No

**Comment by bmarty** [comment]
Should be fixed in Element Android 1.3.2
