### ISSUE TITLE
Textviews with a medium style don't apply sans-serif-medium font

### ISSUE THREAD

**Issue by yostyle** [vector-im/element-android#3907]
### Steps to reproduce

1. In debug enable developer mode
2. Restart the app
3. Go to Debug view from home drawer
4. Click on "TEXT VIEWS LIGHT" button 

### What did you expect?

All texts in textviews with a medium style should have the sans-serif-medium font.

### What happened?

We have a text with sans-serif font if the style is medium type.

### Your phone model

Samsung Galaxy A50

### Operating system version

Android 10

### Have you submitted a rageshake?

No

**Comment by bmarty** [comment]
Fixed in 1.3.18
