### ISSUE TITLE
Enable scrubbing on received voice messages

### ISSUE THREAD

**Issue by jakewb-b** [vector-im/element-android#3924]
As a user who has received a voice message
I want to be able to scrub the waveform 
So that I can start playback from any point in the audio file

- Currently all voice messages play from the start, and there is no way to play them from a mid-point. This makes implementing longer messages a user-experience risk as it is too easy for users to lose their place in a file and not be able to easily regain it.
- There are two interactions:
  - Click on the waveform - move the playhead to that point
  - Click, drag, and release on the waveform - while dragging, the timecode should increase/decrease according to where the mouse is positioned, and on release the playhead moves to that point

**Comment by Johennes** [comment]
Closing this in favor of the duplicating #5426 which is linked to the PR.

**Comment by Johennes** [comment]
Or actually, let's keep it open since it's part of the  Voice Messages Post-Launch project which I can't currently edit. Should be closed together with https://github.com/vector-im/element-android/issues/5426 then.

**Comment by Johennes** [comment]
Closing in favor of https://github.com/vector-im/element-android/issues/5426 after confirming with @jakewb-b
