### ISSUE TITLE
Capitalise first letter of the first word in a text entry

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-android#3930]
#### What would you like to do?
Have the first letter of the text entry capitalised by default

#### Why would you like to do it?
It looks semantically better

#### How would you like to achieve it?
Have the text entry do it automatically like in other apps

### Have you considered any alternatives?

n/a

**Comment by bmarty** [comment]
It is [already the case in the composer](https://github.com/vector-im/element-android/blob/develop/library/ui-styles/src/main/res/values/styles_edit_text.xml#L14) (below the room timelime), or you are talking of something else?

**Comment by kittykat** [comment]
I'm not sure why I was seeing this issue last month. I can't reproduce it now so closing this issue.
