### ISSUE TITLE
Cannot preview space

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-android#3931]
### Steps to reproduce

1. Be invited to a public or private space that you are not a member of
-> See invitation appear in the left menu
2. Select invitation
-> See bottom sheet pop up with the invitation

### What did you expect?

To be able to preview the space by clicking on the space name or have a preview button.

This was a M1 requirement for spaces.

### What happened?

I can navigate away from the bottom sheet or ACCEPT the invite or DECLINE the invite

### Your phone model

n/a

### Operating system version

n/a

### Application version and app store

https://buildkite.com/organizations/matrix-dot-org/pipelines/element-android/builds/3224/jobs/a1fe572d-8a7b-4406-8a0f-37f4c9ff4787/artifacts/30990f61-8f7d-4dc6-af1e-340765110cc6

### Homeserver

matrix.org

### Have you submitted a rageshake?

No

**Comment by BillCarsonFr** [comment]
Hello,
This is what you see on mobile
![image](https://user-images.githubusercontent.com/9841565/131700388-74c1796b-9700-47ae-b96b-9610b937e2d9.png)

THis what you have on web
![image](https://user-images.githubusercontent.com/9841565/131700402-98918211-68a1-4b29-8272-ca112a9bdb5e.png)


I believe that after internal discussion, it was decided that having:
 - The inviter name
 - Space name 
 - People you know who already joined

would be enough to decide to join or not a space

The initial requierement of previewing a space hierarchy, was discarded as bringing too much complexcity (if a user need that level of auditing before joining he should probably not joined).
Also as auto-joined was descoped it is less a problem

**Comment by BillCarsonFr** [comment]
Yes the right panel does not exist on mobile.
Notice that it will always show the inviter and you as invited for private space (you can't know about other members as you are not joined)
