### ISSUE TITLE
Validate public space address length when user clicks away from 

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-android#3934]
### Steps to reproduce

1. Left menu -> "Add Space"
2. "Public"
3. Name -> thisisanamespacewithareallylongnamefornoreasonotherthantotesttheerrorthrownforrisiculouslylongnamespacesbecasuesoempeoplewilltrytonamethingsreallyobscurenamesbecausetheycanbefunsometimesbutapparentlyelementdoesntreallysupportthemorsoiwillfindoutsoooooooooooooooooooooooon
-> Space address is auto-filled
4. Click on "NEXT"

### What did you expect?

Space address is validated for length

### What happened?

Space address length is not validated until "CREATE SPACE" is clicked on the next screen

![Screenshot_20210901-113952.png](https://user-images.githubusercontent.com/51663/131661059-fccae427-ca6c-4801-a4c5-791c22526874.png)

### Your phone model

n/a

### Operating system version

n/a

### Application version and app store

https://buildkite.com/organizations/matrix-dot-org/pipelines/element-android/builds/3224/jobs/a1fe572d-8a7b-4406-8a0f-37f4c9ff4787/artifacts/30990f61-8f7d-4dc6-af1e-340765110cc6

### Homeserver

n/a

### Have you submitted a rageshake?

No

**Comment by daniellekirkwood** [comment]
![Screenshot_20210901-105752_Element dbg](https://user-images.githubusercontent.com/89144281/134189693-c696fe48-0454-41c0-b4e8-1dfb4bbd0d18.jpg)
![Screenshot_20210901-105817_Element dbg](https://user-images.githubusercontent.com/89144281/134189705-11d0ef05-c4bd-4943-b297-a9f9a099782c.jpg)
