### ISSUE TITLE
Membership setting on creating new room doesn't work

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-android#3938]
### Steps to reproduce

1. Left menu -> ☰ next to a private space -> Add Rooms
2. CREATE NEW ROOM
3.  Room access -> Space members only
4.  Create
5. ☰ in the top right corner -> Settings
6. Room settings
7. Look at "Room access"

### What did you expect?

Other space members can see the room.

### What happened?

Other space members can't see the room.

Room shows as "Space members only" but is (probably) "private"

Settings from Android:
![Screenshot_20210901-121521.png](https://user-images.githubusercontent.com/51663/131662455-2a5fba49-ad16-4902-838b-5cb21b52e46d.png)

Settings from web:
![Screenshot from 2021-09-01 12-14-45](https://user-images.githubusercontent.com/51663/131662313-21de3879-fb95-43c0-b42a-a7e97306d962.png)

### Application version and app store

https://buildkite.com/organizations/matrix-dot-org/pipelines/element-android/builds/3224/jobs/a1fe572d-8a7b-4406-8a0f-37f4c9ff4787/artifacts/30990f61-8f7d-4dc6-af1e-340765110cc6

**Comment by BillCarsonFr** [comment]
I think this probably due to this #3950
Could you retry with this build https://buildkite.com/organizations/matrix-dot-org/pipelines/element-android/builds/3239/jobs/473a0c3b-c914-408c-a5b9-b54425628648/artifacts/13269b0f-d6f1-460e-a9cd-3be0a27905dc

**Comment by BillCarsonFr** [comment]
Fixed by #3950
