### ISSUE TITLE
Room name should show display name, not matrix ID when trying to preview

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-android#3940]
### Steps to reproduce

1. In a space at the Rooms screen
2. Select to preview a Room 
3. Bottom sheet appears with error [MatrixID] This room can't be previewed <Join anyway>

### What did you expect?

This error message should show the name of the room, not the Matrix ID 

### What happened?

Showed the Matrix ID (see image)

![spaces preview matrix id](https://user-images.githubusercontent.com/89144281/131681795-2e15ea40-59df-4c4c-b128-d8e05540ceb4.jpg)

### Application version and app store

https://buildkite.com/organizations/matrix-dot-org/pipelines/element-android/builds/3224/jobs/a1fe572d-8a7b-4406-8a0f-37f4c9ff4787/artifacts/30990f61-8f7d-4dc6-af1e-340765110cc6

### Have you submitted a rageshake?

No

**Comment by BillCarsonFr** [comment]
Fixed by https://github.com/vector-im/element-android/pull/3986
