### ISSUE TITLE
View of Self in Spaces member list

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-android#3941]
#### What would you like to do?
Consider the appearance or ordering of Space members in app to lower down the list.

#### Why would you like to do it?
So your own name doesn't take up so much real estate on screen.

#### How would you like to achieve it?
Remove or lower priority of self in list.

### Have you considered any alternatives?

N/A

**Comment by kittykat** [comment]
The flow to trigger this is Space -> DMs -> New DM and see self in the list:

https://user-images.githubusercontent.com/51663/131830017-22a88a27-8f1a-4916-b342-ee7d6f298495.mp4

**Comment by niquewoodhouse** [comment]
> ordering of Space members in app to lower down the list

@BillCarsonFr what defines the ordering of these lists?

> While the member list should have self in it, I feel that the list of people you can DM shouldn't because clicking on yourself doesn't do anything (and probably shouldn't apart from showing a message to say that you can't start a DM with yourself).

I think that's interestingly enough a popular feature of Slack -being able to DM yourself

**Comment by kittykat** [comment]
@niquewoodhouse I currently feel like I should be able to DM myself - I actually have one set up, but I don't think that in itself is a spaces issue.

The ordering seems sane to me now (I'm only at the top if I'm admin and alphabetical otherwise). I think we can close this issue for now, what do you think @daniellekirkwood ?

**Comment by daniellekirkwood** [comment]
So the logic is that Admins appear at the top alphabetically, and then the rest of the list is alphabetical. 

The user sees themselves in that list wherever they fit with the above logic?

**Comment by kittykat** [comment]
> The user sees themselves in that list wherever they fit with the above logic?

Yes, that's right

**Comment by daniellekirkwood** [comment]
Ok. Let's go with that then. 

Happy to close this issue.
