### ISSUE TITLE
Whitespace when creating Space

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-android#3942]
#### What would you like to do?
Discuss the amount of whitespace in the centre of the screen when creating spaces

#### Why would you like to do it?
Consistent whitespace throughout the Create Space flow
|Create space|Create private space|
|-|-|
|![whitespace1](https://user-images.githubusercontent.com/89144281/131685477-5607b5e4-af9b-461e-b5ab-21012fe467c5.jpg)|![whitespace2](https://user-images.githubusercontent.com/89144281/131685474-a36ef643-bdc9-4e84-9214-9ac961789e23.jpg)|

**Comment by BillCarsonFr** [comment]
It was a design decision to make this buttons more reachable

**Comment by niquewoodhouse** [comment]
@BillCarsonFr I think we should keep the whitespace so the buttons are easier to reach but change some of the other details around the screen so it feels more consistent:

<img width="360" alt="android-create-space-public-11@2x" src="https://user-images.githubusercontent.com/1587166/135434246-485dcda8-c5a9-4d8d-9ce9-2e0e47d70a66.png">

- Remove the 'spaces are a new...' copy from the Space type step (as its now a part of the sidebar, its not needed here).
- That makes space to put the question at the top.
- Use same size title as on other question pages
- In the designs, the "your space" title in the header is centered.  If we can't do that, fair enough, but we might need to update the visuals a bit to make things balance up.

<img width="360" alt="android-create-space-public-12@2x" src="https://user-images.githubusercontent.com/1587166/135439094-4e880ff3-d51d-4f6a-87e0-454406260cf2.png">

**Comment by bmarty** [comment]
In EA 1.4.2
