### ISSUE TITLE
Restricted Room previews aren't working

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-android#3946]
### Steps to reproduce

1. In Rooms list in Space
2. Select Room that am not a member of (appears in Suggested list)
3. Bottom sheet appears "This room can't be previewed" 

### What did you expect?

To see a preview of the room

### What happened?

Bottom sheet appears "This room can't be previewed" 
(Also, content should display room name, not Matrix ID; [https://github.com/vector-im/element-android/issues/3940](url) )

### Application version and app store

https://buildkite.com/organizations/matrix-dot-org/pipelines/element-android/builds/3224/jobs/a1fe572d-8a7b-4406-8a0f-37f4c9ff4787/artifacts/30990f61-8f7d-4dc6-af1e-340765110cc6

### Have you submitted a rageshake?

No

**Comment by BillCarsonFr** [comment]
I think this probably due to this https://github.com/vector-im/element-android/pull/3950
Could you retry with this build https://buildkite.com/organizations/matrix-dot-org/pipelines/element-android/builds/3239/jobs/473a0c3b-c914-408c-a5b9-b54425628648/artifacts/13269b0f-d6f1-460e-a9cd-3be0a27905dc

**Comment by BillCarsonFr** [comment]
It looks like I need to use https://github.com/deepbluev7/matrix-doc/blob/room-summaries/proposals/3266-room-summary.md in order to get a proper preview of the room
