### ISSUE TITLE
Kick user dialog for spaces talks about rooms

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-android#3956]
### Steps to reproduce

1. Left panel -> ☰ -> List members
2. Select a member
3. "Kick" under "Admin Actions"

### What did you expect?

"kicking user will remove them from this room."

- [ ] "kicking" is capitalised
- [ ] Ends in "from this space."

### What happened?
![Screenshot_20210902-101819.png](https://user-images.githubusercontent.com/51663/131823331-4ab54f95-4476-434e-b082-3e439e42b89a.png)

### Application version and app store

https://buildkite.com/organizations/matrix-dot-org/pipelines/element-android/builds/3224/jobs/a1fe572d-8a7b-4406-8a0f-37f4c9ff4787/artifacts/30990f61-8f7d-4dc6-af1e-340765110cc6

**Comment by BillCarsonFr** [comment]
To be complete, same applies to BAN option
<img width="329" alt="image" src="https://user-images.githubusercontent.com/9841565/131826229-763ecb39-bb3a-4585-9bcf-4d9fe5a06e54.png">

And security section 
<img width="369" alt="image" src="https://user-images.githubusercontent.com/9841565/131826203-4d4ab2fd-e7ae-4a5d-ac63-09ef1acf30a9.png">


And 2 useless options are shown (jump to read receipt + mention)

<img width="402" alt="image" src="https://user-images.githubusercontent.com/9841565/131826098-3e7d1d5f-6013-4d88-970f-3f6e7fffebd4.png">
