### ISSUE TITLE
Improve interaction for switching spaces

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-android#3958]
#### What would you like to do?
Navigate more intuitively and quickly between spaces

#### Why would you like to do it?
Because when I am looking at a space (room or member list), I find myself automatically hitting that button expecting to back out of the space into the list of spaces so I can chose the next one to look at

#### How would you like to achieve it?
The Android back button ( < ) to bring up the left panel when in the room or DM view
The flow of "DM/room -> (back button) -> all DMs/rooms -> (back button) -> all spaces" makes hierarchical sense

### Have you considered any alternatives?

Current interaction for back and swipe doesn't feel as good to get to the list of spaces, especially when switching spaces regularly. Two taps on the back button is much quicker and is less of a context switch/needs less thinking.

**Comment by kittykat** [comment]
This is ready for implementation, Nique has approved from Design pov

**Comment by ericdecanini** [comment]
@niquewoodhouse @kittykat how should the navigation flow be when you go from:
all chats -> subspace (of another space) -> back button

**Comment by ericdecanini** [comment]
^ the pr is up and on the same topic as my previous comment, a design review would be great!

**Comment by niquewoodhouse** [comment]
> @niquewoodhouse @kittykat how should the navigation flow be when you go from: all chats -> subspace (of another space) -> back button
> 
> Should we make it so you navigate to the direct parent of that subspace even if you didn't switch to that parent space beforehand?

Hey, not sure if I understand the question completely, but I think the idea should be the user goes back to what they navigated to, not necessarily the parent if they didn't switch to it.  Does that make sense?

**Comment by ericdecanini** [comment]
> 

This would actually require quite a large scale change. The app was built in a way that we aren't able to remember what the last navigated space was

**Comment by ericdecanini** [comment]
> > @niquewoodhouse @kittykat how should the navigation flow be when you go from: all chats -> subspace (of another space) -> back button
> > Should we make it so you navigate to the direct parent of that subspace even if you didn't switch to that parent space beforehand?
> 
> Hey, not sure if I understand the question completely, but I think the idea should be the user goes back to what they navigated to, not necessarily the parent if they didn't switch to it. Does that make sense?

If this is the case, I have some follow up questions:
1) On every new app session, should the app still remember the space it was in (like it currently does)?
2) And if so, should the app also remember what spaces were navigated to before in the previous app session?

**Comment by kittykat** [comment]
@ericdecanini I think on a new session we can assume (and as a fallback in all cases where we don't have navigation data) that the user was in the parent space previously so go back up the hierarchy.

**Comment by ericdecanini** [comment]
Okay so within the same session, goes back the way the user navigated. On a new session (aka when navigation data isn't available), simply go up right?
