### ISSUE TITLE
Encryption in Direct Message and Rooms

### ISSUE THREAD

**Issue by hilmanfitriana19** [vector-im/element-android#3997]
hello I want to ask where is the location for encrypting messages in rooms to occur?

I found that the encryption method for direct messages (peer-to-peer) is different from the encryption method for rooms(multichat). I added a log to the `encryptGroupMessage` module located at `MxOlmDevice.kt`, and it appears when direct-message(peer-to-peer) communication occurs, but not when rooms(multichat) communication occurs.

**Comment by bmarty** [comment]
I think this is the same encryption flow for DM and for group rooms. Can you double check please?

**Comment by hilmanfitriana19** [comment]
Thank for the answer, it turned out that it was indeed encrypted, my fault for using a public group and not realizing that the group was created with a disabled end-to-end encryption status.
