### ISSUE TITLE
Adapt the session verification banner to handle correctly the case where there is only one session

### ISSUE THREAD

**Issue by giomfo** [vector-im/element-android#3999]
### Your use case

- [ ] If the client is aware that there is no other session for the current user the message of the following banner should not talk about "session"
![image](https://user-images.githubusercontent.com/8969772/131110547-7abd7299-cedf-4c52-b615-d3d1ded2cd1b.png)

I suggest limiting the message of this dialog to "Confirm your identity to unlock your history".
The Element dev team decided to display this banner (even if there is no session) to let the user provide the secret phrase or the recovery key (if any). Talking about other sessions here is strange for the user point of view.

The wording of this banner should be simplified to avoid the inconsistency in this case and maybe others. I suggest keeping it as much short as possible to let the details come in the second screen.

- [ ] The verification banner must not be displayed if the client is aware there is no secure storage (backup) available for the current user, and no other session too

**Comment by giomfo** [comment]
@BillCarsonFr Hi do you think this point is still a pending issue?
Can you please provide an update on it?

**Comment by BillCarsonFr** [comment]
Fixed by https://github.com/vector-im/element-android/pull/6475
