### ISSUE TITLE
Sent message have grayed duplicate in bottom

### ISSUE THREAD

**Issue by MurzNN** [vector-im/element-android#400]
I send message to room, it sends succesfully, but RiotX keep showing grayed-out duplicate of it in bottom of timeline, even after killing app and open again.

I use RiotX debug, updated yesterday.

Here is screenshot with message on bottom:
![Screenshot_20190719-085203_RiotX dbg](https://user-images.githubusercontent.com/336662/61512741-87b63580-aa03-11e9-8ada-aee9b7d4f5c8.jpg)

Here is after long tap
![Screenshot_20190719-085210_RiotX dbg](https://user-images.githubusercontent.com/336662/61512787-acaaa880-aa03-11e9-937d-e74260ec0224.jpg)

Here is it sent in room timeline (at top):
![Screenshot_20190719-085156_RiotX dbg](https://user-images.githubusercontent.com/336662/61512832-d06dee80-aa03-11e9-806c-fe9c71309a40.jpg)

Here is it source
![Screenshot_20190719-085222_RiotX dbg](https://user-images.githubusercontent.com/336662/61512854-dbc11a00-aa03-11e9-80c2-59af8d0ba0e9.jpg)

**Comment by MurzNN** [comment]
Message clone in this room is still visible in bottom of timeline (grayed-out as unsent) after active talking in other rooms.

**Comment by MurzNN** [comment]
After clearing cache - I got other issue https://github.com/vector-im/riotX-android/issues/408

**Comment by TheCycoONE** [comment]
Seeing this as well on a zenpad 300m running Android 7.0

**Comment by kittykat** [comment]
@MurzNN I'm going to close this as I believe it's fixed. Let me know if you've seen it more recently!
