### ISSUE TITLE
The color of this arrow is the Element theme, could this be added to the color config? 

### ISSUE THREAD

**Issue by chagai95** [vector-im/element-android#4003]
### Steps to reproduce

Have a lot of unread messages, then go to the chat

![image](https://user-images.githubusercontent.com/31655082/132890898-bbea7e32-756a-45e5-b23b-42e6bbad6e19.png)

### What happened?
color is not per theme config

### Have you submitted a rageshake?

No

**Comment by bmarty** [comment]
Yes, we should use `?colorPrimary` instead of hard coded value `#0DBD8B` in all the vector drawables.

We will update this

TODO: check that there is no issue on API 21.

**Comment by bmarty** [comment]
Fixed in EA 1.3.1 (or 1.3.2)
