### ISSUE TITLE
RageShake | Messages are displayed as unabled to decrypt then decrypted a few seconds later

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/element-android#4011]
https://github.com/matrix-org/element-android-rageshakes/issues/26594

**Comment by BillCarsonFr** [comment]
By looking at the logs, the session key was received correctly, but the subsequent call to getInbound group session returns null and is marking the message as failed to decrypt

So it looks like there is a delay before the session is actually stored in DataBase and can be fetched succesfully.

We already have an in memory cache to make it faster when updating the ratchet index, we could use it on when the session is first added

**Comment by bmarty** [comment]
In EA 1.2.3
