### ISSUE TITLE
voice message fail after phone lock

### ISSUE THREAD

**Issue by progserega** [vector-im/element-android#4022]
### Steps to reproduce

1. I move up voice button
2. I see, that voice record begin
3. Wait ~15 seconds and my phone was lock screen and off screen
4. Wait ~5 seconds 
5. Unlock screen
6. Unlock phone by gesture
7. I see, that voce recording is abort without any messages

Situation 2:
1. I still press on voice button and 
2. I see, that voice record begin
1. I still pressing on voice button
3. Wait ~15 seconds and my phone was lock screen and off screen
4. Wait ~5 seconds 
5. Unlock screen
6. Unlock phone by gesture
7. I see, that voce recording is abort without any messages

### What did you expect?
1. I expect, that when I start voice recording (by still pressing on button or move record icon to up for lock record) - phone will not lock screen.
2. If user lock voice record and lock phone screen manually - voice record must be continue at background.
### What happened?
1. If phone lock quickly - voice recording not usable - it break record.

### Your phone model

Yotaphone 2

### Operating system version

android 6.0.1

### Application version and app store

Element android gplay 1.2.2

### Homeserver

rsprim.ru

### Have you submitted a rageshake?

Yes

**Comment by 532910** [comment]
Can confirm this issue.
