### ISSUE TITLE
Voice message limit

### ISSUE THREAD

**Issue by 532910** [vector-im/element-android#4024]
#### What would you like to do?

I'd like to record voice messages longer than the current 2 min limit.

#### How would you like to achieve it?

Just remove the limit or add a control.

### Have you considered any alternatives?

No.

**Comment by DoM1niC** [comment]
its currently hardcoded in Source

**Comment by Beiri22** [comment]
So it could easily be changed into a user-defined property, right? So there are no serverside constraints?

**Comment by DoM1niC** [comment]
Nope is fully Client side, Server are only keep the filesize limit not more, you have edit the vector gradle like todo a own Fork...

**Comment by ouchadam** [comment]
going to close this in favour of https://github.com/vector-im/element-android/issues/4160
