### ISSUE TITLE
Call screen stuck with some hanging up scenarios

### ISSUE THREAD

**Issue by ganfra** [vector-im/element-android#4026]
### Steps to reproduce

1. Have Element Web open with Account A and Account B. Have Element Android open with Account A.
2. Start a call from Account B to Account A.
3. Open the call screen on Element Android by clicking on the notification
4. Pick up on Element Web.

### What did you expect?
The call screen should be dismissed
### What happened?
It's not dismissed.

### Have you submitted a rageshake?

No

**Comment by bmarty** [comment]
Done in #4029
