### ISSUE TITLE
[Voip] : Other call not always refreshed when ended

### ISSUE THREAD

**Issue by ganfra** [vector-im/element-android#4028]
### Steps to reproduce

1. Launch 2 different calls in 2 rooms.
2. Let the opponent of the held call hangups

### What did you expect?
The held call should disappear completely from UI (Active call views, InCall screen)
### What happened?
The held call is still shown in Active call views and InCall screen. It disappears when you close the screens.

### Have you submitted a rageshake?

No

**Comment by kittykat** [comment]
I'm going to close this issue for now as we were unable to reproduce it in a community testing session. Please re-open if it's still valid.
