### ISSUE TITLE
incorrect time display.

### ISSUE THREAD

**Issue by nik2323** [vector-im/element-android#4036]
### Steps to reproduce

1. Where are you starting? What can you see?
2. What do you click?
3. More steps…

### What happened?

I cannot synchronize the time of mobile applications: Element 1.2.2, Schildichat 1.2.2.sc44. Samsung Note 9 device, Android 10, security patch level version from 01/08/2021. The only problem is with these two apps, the other several dozen apps display the correct time. When setting up in the device here: Settings - General settings - Date and time, there is no difference between the Autodetect time settings or manual selection: Select time zone, Set date, Set time. Whatever settings I use, the time in the Element and SchildiChat applications is 1 hour longer than in the device or in other applications.

### Your phone model

Samsung note 9

### Operating system version

Android 10

### Application version and app store

Element 1.2.2

### Homeserver

matrix.org

### Have you submitted a rageshake?

No

**Comment by ouchadam** [comment]
@nik2323 would you be able to provide some screenshots showing where the wrong times are in element?

**Comment by ouchadam** [comment]
going to close due to inactivity
