### ISSUE TITLE
Prevent other participants from viewing the Private Room members.

### ISSUE THREAD

**Issue by nik2323** [vector-im/element-android#4037]
### Your use case

Prevent other participants except the administrator from viewing the members of the Private Room.
The invited members should not be allowed to view the details of other invited members.

### Have you considered any alternatives?

In the Telegram application in the Private Channel, it is impossible for the invited members of the Private Channel to view other members of the Private Channel.
This is implemented by default.

**Comment by bmarty** [comment]
This idea requires change in the spec, and is not directly related to Element Android. Feel free to submit it here https://github.com/matrix-org/matrix-doc/
