### ISSUE TITLE
The ability to hide the sender and the sent message text in the notification line in the notification text.

### ISSUE THREAD

**Issue by nik2323** [vector-im/element-android#4040]
### Your use case

Make it possible to hide the sender and the sent message text in the notification text in the notification line.

There should be information only with text - a new message has been sent to you, or something like that.

### Have you considered any alternatives?

Half of messengers have such an option.

**Comment by BillCarsonFr** [comment]
There is a system setting that allows to do that. Settings > Apps & Notifications > Notifications > Notification On Lock Screen and uncheck Sensitive Notification.
Isn't that enough?

**Comment by bmarty** [comment]
It is already possible to hide notification content if you configure a PIN code to protect access to the application, in Settings, Security & Privacy, Protect access. Then you can disable "Show content in notifications"
