### ISSUE TITLE
Spaces invitation system notifications don't take me to the join space toast

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-android#4043]
### Steps to reproduce

1. Be logged into your account on your Android phone
2. Receive system notification (e.g. from email invite to your registered address)
 -> See the notification pop-up
3. Click the notification
 -> App opens on previous view, not showing notification

### What did you expect?
Join space toast

### What happened?
Previous view of the app

https://photos.app.goo.gl/KNbAKmPJZiCAvrhKA

### Application version and app store

Spaces release test version

### Have you submitted a rageshake?

No

**Comment by BillCarsonFr** [comment]
Additional context.
The invitee must have an identity server setup, and the given email must shared in the discovery settings

**Comment by bmarty** [comment]
Fixed in EA 1.2.3

**Comment by kittykat** [comment]
@bmarty @BillCarsonFr would this have fixed the same issue with room invites not taking the user to the invite?
