### ISSUE TITLE
[VoIP] Ring tone plays only once

### ISSUE THREAD

**Issue by opusforlife2** [vector-im/element-android#4047]
### Steps to reproduce

Called a phone with Element Android v1.2.2 installed. This phone has the default OS ring tone.

### What did you expect?

The ring tone should have played the entire time the call was being made.

### What happened?

The ring tone played once fully, and then went silent. The call banner stayed, though.

### Your phone model

Nokia 6.1

### Operating system version

Android 10

### Application version and app store

Element Android 1.2.2, Play Store

### Homeserver

matrix.org

### Have you submitted a rageshake?

No

**Comment by opusforlife2** [comment]
Your bug report template seems a little off ^. "What happened" appears twice, once as a label and once as a subheading.

**Comment by ouchadam** [comment]
for android 9.0 and above we can [set ringtones to loop](https://developer.android.com/reference/android/media/Ringtone#setLooping(boolean)), for versions below, users will unfortunately need to either select longer ringtones or manually [add extra metadata to the file](https://forums.oneplus.com/threads/ringtone-rings-once-and-stops.74397/#post-3917347)
