### ISSUE TITLE
Reply/Edit mode animation is broken when sending.

### ISSUE THREAD

**Issue by ganfra** [vector-im/element-android#4077]
### Steps to reproduce

1. Swipe on an event in the timeline to open the reply mode
2. Type your reply message
3. Click on sent button

### What did you expect?
Animation runs smoothly
### What happened?
Animation is kind of broken and can lead to weird state

### Have you submitted a rageshake?

No

**Comment by bmarty** [comment]
Fixed in EA 1.3.2
