### ISSUE TITLE
Is this a place to ask for Element Android help? 

### ISSUE THREAD

**Issue by GhostOfJimmyHoffa** [vector-im/element-android#4079]
The feed in a room frequently gets out of order after I post. Only logging out and logging back in fixes this. 

Should my room members be verified by me? 

Is there a way to easily see a rooms history? 

Sorry in advance if I'm in the wrong place.

**Comment by BillCarsonFr** [comment]
Hello @GhostOfJimmyHoffa the best place to get community support would be in the dedicated rooms
For android it's here => https://www.matrix.to/#/#element-android:matrix.org
