### ISSUE TITLE
Exporting E2E keys in RiotX not working

### ISSUE THREAD

**Issue by bergmannf** [vector-im/element-android#4082]
When I export the E2E keys from the RiotX App it creates a new file in the downloads folder, but when I try to import the keys (either in RiotX or the desktop app) it fails with the message `Trailer line not found`.

When I check the generated file it looks like this:

```
-----BEGIN MEGOLM SESSION DATA-----
<about 28000 lines of base64 data with newline every second line>
```

It seems there is not corresponding `-----END MEGOLM SESSION DATA-----`.

I tried the workaround to add the `-----BEGIN MEGOLM SESSION DATA-----` line by hand, but that did not fix it and only changed the error to `Authentication check failed: incorrect password?`

The `RiotX` app is version `0.20.0 [40020002] (G-b2640)`

**Comment by bmarty** [comment]
Ok, please ignore, I've transferred the issue to the correct project.
@ouchadam can you have a look on it please? Thanks

**Comment by bmarty** [comment]
Element Android 1.3.1 include PR #4091, which should show more error during key export if any.
