### ISSUE TITLE
community not show conversations

### ISSUE THREAD

**Issue by progserega** [vector-im/element-android#411]
1. I add rooms and conversations (by internal room address) to my private community (where join only me).
2. When I select my community in riot-web - I see rooms and conversations which I added at step 1
3. When I select my community in RiotX  - I do not see conversations, but see rooms.

I think that community will be more usable if user will can create private community with own grouping of his conversations.

**Comment by progserega** [comment]
For example:

I have some contacts in matrix, in whatsapp (by bridge), in telegram (by bridge). And I want create community, for example "Mounting Bike Community" and add all bikers to this community. This allow me see all my bikers friends, chats with it and not see other rooms and conversations.

But at current situations - all this bikers must join to my private community. But part of them can not do this (they are bridge-users), part of they - maybe do not want join to my community, and in some cases I do not want that they see users in my community - because this is my private community with my private contacts.

So we need instrument to usable grouping our private contacts. Do the "community" can do that, must do that? Do the matrix users will have some instruments?

**Comment by progserega** [comment]
Riot-web with selected "matrix" community:
![riot-web](https://user-images.githubusercontent.com/1297163/61589272-07522900-abeb-11e9-9529-d33546e281ad.png)
RiotX with such community:
![Screenshot_20190721-190536](https://user-images.githubusercontent.com/1297163/61589281-2781e800-abeb-11e9-878f-cc6be7188e15.png)
![Screenshot_20190721-190528](https://user-images.githubusercontent.com/1297163/61589282-2781e800-abeb-11e9-9381-30c5beb56b80.png)

**Comment by progserega** [comment]
I think RiotX show only rooms with alias. And only private chats with users, which join to community. But not show rooms (and private chats), which added by internal room id such: `!sdfsdfsdf:server.net`

**Comment by kittykat** [comment]
I'm going to close this issue as we no longer support communities. See [this task](https://github.com/vector-im/element-android/issues/5733) for communities being removed from the app.
