### ISSUE TITLE
Major issue with DST Root CA X3 Expiration using Let's Encrypt

### ISSUE THREAD

**Issue by ggogel** [vector-im/element-android#4122]
### Steps to reproduce

1. Have a Let's Encrypt certificate on your homeserver or a reverse proxy using Let's Encrypt in front of it

### What did you expect?
Android clients should still be able to connect. The app should give an error about the certificate and ask if it can be trusted.

### What happened?
See: https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/

The Android app wasn't able to connect to the server anymore. I couldn't send nor receive any messages. There was no error message given, which was really confusing. When I log out and back in again i get a certificate error. As long as the certificate doesn't change it works but for instance when I pull a new one from Let's Encrypt it's broken again. 

I don't get the certificate error using Element Web with Firefox on the same device. Though, I get the error using Chrome. So I would conclude from that, that Element is accessing the system certificate store. Still, Element should give a warning and ask for confirmation even if the user is already logged in.

### Your phone model

OnePlus 8T

### Operating system version

Android 11

### Application version and app store

1.2.2, olm version 3.2.4 from Google Play

### Homeserver

matrix.gogel.me

### Have you submitted a rageshake?

No

**Comment by ggogel** [comment]
Just wanted to report back that my Chrome on Android now trusts the certificate by default. I've completely redone the setup of LE. I still got the issue with Element on Android though....

**Comment by tulir** [comment]
Looks like your cert is just set up wrong, probably not related to the LE root cert stuff. https://whatsmychaincert.com/?matrix.gogel.me

**Comment by ggogel** [comment]
But why does it work on every device, every app and browser, except Element Android? When I look at the certificate it responds with the full certificate chain, including the two CA certs. I don't understand why the website claims that the chain is wrong.

**Comment by tulir** [comment]
Browsers have intermediate certs in their trust stores, so they don't care if it's missing from what the webserver responds. `curl https://matrix.gogel.me` and https://federationtester.matrix.org/api/report?server_name=gogel.me are also saying the returned certs are wrong (and also that your SRV record points at a CNAME, which is not allowed, but synapse doesn't care about that)

**Comment by ggogel** [comment]
Do you by any chance know how to include the intermediate certs with LE and haproxy running on a pfsense?

**Comment by ggogel** [comment]
As a workaround I imported the chained certificate from the website and made haproxy use it. This is by no means a solid solution, since the cert will expire in three months, where I would need to repeat that process again.

I'd really appreciate a guide on how to get the chained certificate from LE on a pfsense firewall.
