### ISSUE TITLE
Can't Send Anyway in an encrypted room

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element-android#413]
![](https://i.imgur.com/k96UZ1x.png)
![](https://i.imgur.com/o3cQZhu.png)

When sending a message in a room where a new device has been added, the message turns red, and can no longer be interacted with.

Sending a new message will also be red.

Long-pressing on the message just pops up a context menu with no controls, just the message content.

This seems to happen about once a day and is kind of sucky.

**Comment by Valodim** [comment]
It seems that this is also not fixed by clear cache, at least clearing cache did not fix this issue for me twice now.

**Comment by anoadragon453** [comment]
I realized this is probably the new devices behaviour without a popup allows you to Send Anyways.

**Comment by bmarty** [comment]
Please re-open if this is still an issue on the latest version of Element
