### ISSUE TITLE
Cannot join spaces on element for Android 1.2.2

### ISSUE THREAD

**Issue by paboum** [vector-im/element-android#4130]
### Steps to reproduce

1. Go to room list
2. Touch the join/create button (#+)
3. Type a space name, e.g. #ManjaroLinux:matrix.org
4. Touch the space on the space list that appears

### What did you expect?
A popup describing the space in detail, allowing to join it.

### What happened?
The popup only flashes and then I get pushed back to the room list from step 1. The only way I can join the space is via web/desktop app, after I join there, it is correctly usable from Android app.

### Your phone model

Oneplus Nord 2 5G

### Operating system version

Android 11 / OxygenOS V11.3

### Application version and app store

Element version 1.2.2 from Play Store

### Have you submitted a rageshake?

No

**Comment by BillCarsonFr** [comment]
Please upgrade to element 1.3.1 (space release) and retry
