### ISSUE TITLE
Better handle room upgrades within Spaces 

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/element-android#4133]
### Steps to reproduce

Reflect web changes https://github.com/vector-im/element-web/issues/19246

### Your use case

The client should resolve upgrades locally where possible to deduplicate space listings

**Comment by ericdecanini** [comment]
@BillCarsonFr I've done some investigating and testing on this issue and my question is do we still need to action this?

On testing, there's no situation where a listing is duplicated. When a room is upgraded and an old member is not invited to the upgraded room, they may see the old room in their room list that they can go into and see that it is upgraded. This seems to be normal behaviour. This happens thanks to receiving a tombstone state event from the server on upgrade.

The moment they get an invite to the new room, the old room's listing disappears and gets replaced by the invite.

**Comment by ericdecanini** [comment]
https://user-images.githubusercontent.com/20701752/170678438-5baac528-c21d-4e46-afe4-9654c4724d69.mp4

The above shows me being in a room, then another user upgrading the room, looking for any duplicates in room list and explore rooms, then being invited into the room and looking for any duplicates.

Fortunately we don't have any situations where there are duplicates, but there are situations where the same room is either in Home or in the Space but never both. I'll investigate this
