### ISSUE TITLE
Hiring a development team to speed up the normal feature development process

### ISSUE THREAD

**Issue by xb3b6** [vector-im/element-android#4140]
### Your use case

Shocked by how bad the interface is, many of the obvious things are simply not there.  After looking at the issues I can see that the community offers improvement and help, but this is moving at a kotlin-brake speed. More than 1000 requests.  Why, for example, is there still no selection function in a screenshot or a photo with a brush of the desired place ???  How can I send a screen, cropping to the desired size, not 16: 9 and highlighting specific pixels?  Please learn from the experience of messengers who are working on improving the interface, so that users are satisfied.  

Otherwise, the matrix will have no one to communicate with, because he will be unsuitable for comfortable communication.

### Have you considered any alternatives?

Telegram GUI

### Additional context

Support with likes to convey meaning to developers.

**Comment by bmarty** [comment]
The team is growing on we are working to improve the application. Thanks!

> Why, for example, is there still no selection function in a screenshot or a photo with a brush of the desired place ??? How can I send a screen, cropping to the desired size, not 16: 9 and highlighting specific pixels?

This is already supported. When sending an image, you have the possibility to edit it before sending.
