### ISSUE TITLE
Mic is shown on text message notification during a call

### ISSUE THREAD

**Issue by 532910** [vector-im/element-android#4142]
### Steps to reproduce

1. Make a voice call
2. Send a message

![image](https://user-images.githubusercontent.com/14617699/135715963-8c845d8b-7e0d-4294-ace7-b543d73df15e.png)

### Operating system version

Android 11

### Application version and app store

The latest beta from GPlay

### Have you submitted a rageshake?

No

**Comment by kittykat** [comment]
I'm going to close this issue for now as we can't reproduce it in a community testing session. Please comment with @kittykat and more info if it's still valid for you

**Comment by 532910** [comment]
Not fixed, reopen please!

**Comment by 532910** [comment]
Not fixed, reopen please!
