### ISSUE TITLE
Notifications only firing when app is in foreground 

### ISSUE THREAD

**Issue by matrixes** [vector-im/element-android#4143]
### Steps to reproduce

1. Be at phone home screen, in another app or screen shut off
2. Ask anyone to send a message, tagging you
3. Wait

### What did you expect?
1. A notification without extra interaction. This worked in the 10th of September release (the one prior to this).

### What happened?
1. No notification until I open the app

### Your phone model

Google Pixel 5

### Operating system version

Android 11

### Application version and app store

Element 1.3.1 [40103012] (G-b3666), Matrix SDK version 1.3.1 (8937a0f5)

### Homeserver

selfhosted, 1.41.1

### Have you submitted a rageshake?

No

**Comment by bmarty** [comment]
Hello @matrixes, can you run the notification troubleshoot please?
In the app, go to the settings, then "Notifications", then at the bottom, "Troubleshoot Notifications". Please let us now if everything is fine here. Thanks!

**Comment by bmarty** [comment]
Also you can check the specific notification setting of the room the message is sent, either by long clicking on the room in the room list of from the settings of the room. Please also let us know what is this setting.

**Comment by JonLiuFYI** [comment]
I'm experiencing the same problem and can provide some of the info from my situation. My setup:

* Android 11
* Google Pixel 3a
* Identical app and SDK version as @matrixes
* Homeserver is self-hosted version 0.34.1.1 

The notification troubleshooting in the app doesn't indicate any problems. It's all green checkmarks.

I have a chat room set to "silent" for "all messages" and direct message chats set to "noisy" and "all messages." I'm not getting notifications from any of them unless I have the app in the foreground.

Others I know are experiencing the same issue with 1.3.1 with these phones:

* OnePlus 6T, Android 11
* Samsung Galaxy S8, Android 9

**Comment by matrixes** [comment]
This took me for a loop because on the day after our Synapse upgrade, Let's Encrypt's SSL root certificate expired on our Synapse server which made the issue symptoms that extra bit difficult to troubleshoot. After having managed to update the root certificate on the server, everything is now back in order over here!

Thanks for your engagement @bmarty !
