### ISSUE TITLE
Sometimes call stuck with no buttons or a way to hang up

### ISSUE THREAD

**Issue by 532910** [vector-im/element-android#4144]
### Steps to reproduce

I'm not sure this is always-reproducible.

1. Start a voice call (to ios, but not sure)
2. Answer a call on ios
3. Hangup a call on ios -- android will show the call is ended
4. Start a new call:
![image](https://user-images.githubusercontent.com/14617699/135716632-11c6ce2b-71cd-4613-b5fe-f92ef3deacf7.png)
![image](https://user-images.githubusercontent.com/14617699/135716673-a465c0f8-47c6-4791-a1c5-2c5ee624f82b.png)

### Operating system version

Android 11

### Application version and app store

The latest beta from GPlay

### Have you submitted a rageshake?

Yes

**Comment by 532910** [comment]
This is a very annoying issue, as it's not trivial how to kill this activity, and phone reboot is the only way for most people.

**Comment by kittykat** [comment]
@532910 which version of Element are you using?

**Comment by 532910** [comment]
Sorry for forgetting to specify it, I'm on GPlay Beta channel, thus it was the latest at the time the issue was opened.
I'll try to reproduce it as soon as v1.3.8 becomes available.

**Comment by kittykat** [comment]
I got it on 1.3.8: 
![Screenshot_20211121-221120.png](https://user-images.githubusercontent.com/51663/143217876-40ae4658-3cd0-4440-b93f-b748c9fae7a9.png)

**Comment by ouchadam** [comment]
I'm not entirely sure why this happens yet but the screenshots are showing the call stuck in the `Idle` state. Element isn't actually ringing at this point. 

I can add UI to hang up but will investigate a little more to try and understand why we're getting stuck

**Comment by ouchadam** [comment]
(symptoms) fixed in 1.3.9
