### ISSUE TITLE
Voice message recording ends after two minutes 

### ISSUE THREAD

**Issue by AnID-Aux** [vector-im/element-android#4159]
### Steps to reproduce

1. Record a voice message
2. Speak
3. after 1:57 or 1:59 the recording will stop
4. then the message will be sent automatically

### What happened?

I would have expected that you can record a voice message of unlimited length. At least more than two minutes. 

### Your phone model

Samsung Galaxy Note20 Ultra 5g

### Operating system version

Android 11

### Application version and app store

Element 1.3.1 Playstore OLM 3.2.4

### Homeserver

private Homeserver

### Have you submitted a rageshake?

No

**Comment by toshanmugaraj** [comment]
It looks like the screen saver is stopping the recording.

**Comment by ouchadam** [comment]
closing in favour of #4160
