### ISSUE TITLE
Cannot resend failed attachments

### ISSUE THREAD

**Issue by onurays** [vector-im/element-android#4224]
### Steps to reproduce

- Send a file/image in flight mode
- Close and open the application
- Turn off the flight mode, let the app try to send it again
- Click on the unsent pdf file in timeline -> Crash
- Click on the unsent image in timeline -> Black screen
- Click on the resend button -> Will fail and produce below log:
`java.lang.SecurityException: Permission Denial: opening provider com.android.providers.downloads.DownloadStorageProvider from ProcessRecord{14e0097 27573:im.vector.app.debug/u0a531} (pid=27573, uid=10531) requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs`

#### What did you expect?
To be able to resend failed attachments

#### What happened instead?
Cannot resend attachments

### Have you submitted a rageshake?

No

**Comment by bmarty** [comment]
I think we store the file locally before trying to send it, which is not possible if there is no network, but when the network is back, we try to send the original file, whose access is revoked, and not the local copy

**Comment by bmarty** [comment]
Similar to #3616
