### ISSUE TITLE
Room upgrade support

### ISSUE THREAD

**Issue by manuroe** [vector-im/element-android#424]
This is a meta issue for the support of room upgrade. It lists all we need to do.

The UX and the design can be the same as Riot-Android. That may worth to check if the new icons used by Riot-web in the banners can fit on a mobile app.

The implementation must support upgrade through federation. That has been implemented lately on Riot-Android (see https://github.com/vector-im/riot-android/issues/3204 and corresponding PRs).

Check list:
- [x] display a banner in the old room
- [x] automatically join the new room when the user taps on this banner
- [x] use the sender server name in the `/join` request (existing issue #303)
- [x] display a banner to the new room that links to the old room
- [x] show only the new room in rooms lists (existing issue #246)
- [ ] check if we can use new icons from riot-web

**Comment by ganfra** [comment]
Handled by https://github.com/vector-im/riotX-android/pull/449
We should ask Nad for design

**Comment by bmarty** [comment]
design will be updated in next sprint

**Comment by nadonomy** [comment]
@bmarty I added skinnier designs for the notices here:

https://zpl.io/bl6Kkpe

**Comment by bmarty** [comment]
Let's iterate on design later, this is a bit outdated
