### ISSUE TITLE
Make Element Android Thread aware

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-android#4246]
#### What would you like to do?

To take a few steps towards understanding Threads in Android before a full implementation

#### Why would you like to do it?

To ensure maximum backwards compatibility and continuity in conversations when threads will be available to the masses.

#### How would you like to achieve it?

[MSC3440](https://github.com/matrix-org/matrix-doc/pull/3440) recommends two things for clients that do not fully support threads yet

- [x] To treat `m.thread` the same way that they treat `m.in_reply_to`
- [x] To change the event references from `m.in_reply_to` to `m.thread` when replying to an event that has an `m.thread` relation (to ensure that the message will be displayed correctly in the thread when viewed on thread's ready clients)

### Additional context

Threads might be using a `m.thread` relation over `m.in_reply_to`

**Comment by bmarty** [comment]
In EA 1.3.9
