### ISSUE TITLE
Remove the home menu drawer sign out functionality

### ISSUE THREAD

**Issue by ouchadam** [vector-im/element-android#4265]
#### What would you like to do?
Remove the sign out option from the Home menu drawer

#### Why would you like to do it?
- The ability to sign out is already available in the settings -> general page  
- Help reduce some of the UI noise

#### How would you like to achieve it?
By removing the button and putting something more valuable in its place

### Additional context

| BUTTON | 
| --- |
|![2021-10-18T16:27:39,190931706+01:00](https://user-images.githubusercontent.com/1848238/137762342-7d8ae7e4-f3e9-4bad-87b0-a5302ce6f3ab.png)

**Comment by bmarty** [comment]
Some context about why this "Sign out" action has been added here can be found at #2171.

Also, as a side remark (or a joke?):

> Are people signing out so often that it needs to be a 2 click journey?

Depending on the account configuration, after 2 clicks, the journey is not over :/

**Comment by bmarty** [comment]
Opening the settings is also very rare on a daily usage of a messaging app. Maybe useful at the beginning, but after?
Also sign out is also well promoted on Element Web.
We will know more about the usage when we will have some analytics, I guess.
This will be to the product team to decide what is best here, I would be happy to change things to improve that.

**Comment by bmarty** [comment]
FTR we have an issue on small devices, see screenshots in https://github.com/tchapgouv/tchap-android-v2/issues/453

**Comment by Florian14** [comment]
> FTR we have an issue on small devices, see screenshots in [tchapgouv/tchap-android-v2#453](https://github.com/tchapgouv/tchap-android-v2/issues/453)

I don't know if the issue can be reproduced on small devices with normal font size, but it can be reproduced on any device by selecting largest or huge font size (and also with longer texts than the english ones)

**Comment by daniellekirkwood** [comment]
This will be solved with the App Layout work - closing this issue.

**Comment by daniellekirkwood** [comment]
@BillCarsonFr Your feedback is valid but I worry it will get lost in this closed issue. 

https://github.com/vector-im/element-android/issues/7056
