### ISSUE TITLE
Iterate on UrlPreview design

### ISSUE THREAD

**Issue by bmarty** [vector-im/element-android#4278]
Element iOS now supports URL previews, and their rendering is nicer than on Element Android, this is not acceptable (just kidding!)

**Comment by daniellekirkwood** [comment]
![urlpreviewsios](https://user-images.githubusercontent.com/89144281/139714030-977ff74e-fd03-4ee3-a7a1-00b88c4fa598.jpeg)

Is this an example of the url preview you're referencing? 

They are only available on unencrypted rooms in iOS...

**Comment by amshakal** [comment]
I followed the product thinking in iOS and created designs for android.

Here are the proposed designs to show URL with images:
![Frame 3694](https://user-images.githubusercontent.com/85162587/139941021-8cfbaeaa-0c75-4e6e-b13c-77f00d26d777.png)
![Frame 3695](https://user-images.githubusercontent.com/85162587/139941022-d44fd856-5302-4208-ae5c-a69f4efccb7e.png)


Here are the proposed designs to show URL without images:
![Frame 3696](https://user-images.githubusercontent.com/85162587/139941143-20de7cbf-3b42-440b-9dcc-5cd65efd1805.png)
![Frame 3697](https://user-images.githubusercontent.com/85162587/139941145-0960a363-a0bd-483d-8113-7dcec35ae5fd.png)

Settings tab to turn preview on and off:
![Frame 3693](https://user-images.githubusercontent.com/85162587/139941215-1c3807dd-68ba-48fc-828b-7b4698114231.png)

And finally, here is a link to the figma file:
https://www.figma.com/file/U7Pyaa5Y7V7a1QTcjJyb3k/UrlPreview-design?node-id=1%3A41
