### ISSUE TITLE
3pid provider logos look odd on the login page

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-android#4285]
## Action needed
- [ ] Update the icons on the buttons to have the correct padding, all the icons should be aligned in light and dark mode
- [ ] Dark mode: Google icon padding "The padding to the left (and right) of the text should be 8dp. The logo should be 18dp, and there should be 24dp between the logo and the button text." [link here](https://developers.google.com/identity/branding-guidelines)

### Acceptance Criteria
When updated, please add a screenshot to this issue and tag @daniellekirkwood & @amshakal for 👍 👍 👍 
Thanks!

### Steps to reproduce

Start in a logged out

1. "Get started"
2. "[matrix.org]"
3. Look at 3pid login options

#### What did you expect?
Slick and classy experience

#### What happened instead?
A rainbow calamity with a square google icon in the dark theme:
![Screenshot_20211020-135530.png](https://user-images.githubusercontent.com/51663/138256155-19e33f28-b74c-43a7-9187-fe3ff5726162.png)

Apple being the only dark 3pid provider in the light theme:
<img width="286" alt="image" src="https://user-images.githubusercontent.com/3940906/138094125-2f9b1885-f6e3-447f-9b2e-21cdb01d7b37.png">

**Comment by kittykat** [comment]
If those are the guidelines, then it makes sense to follow them. Is it worth double checking that Google is supposed to be grey on a light background? And the Google icon or background with a dark theme should still need fixing, I think

**Comment by bmarty** [comment]
Just adding some padding to the start icon, here are the previews:

### Light

<img width="660" alt="image" src="https://user-images.githubusercontent.com/3940906/142006321-0944c9c7-6acc-402a-bcb2-1922c54e079e.png">

### Dark

<img width="655" alt="image" src="https://user-images.githubusercontent.com/3940906/142006387-3ae08ea0-2581-4bbd-b801-e7b8c65bbcc4.png">


Is it OK for you @daniellekirkwood @amshakal ?

**Comment by daniellekirkwood** [comment]
Looks great! 👍

**Comment by bmarty** [comment]
PR to be approved: #4522 @amshakal @daniellekirkwood

**Comment by amshakal** [comment]
For dark mode, can we switch the background of the button to white? The white on blue looks a bit odd. 

Just read through google's guidelines shared above and it suggests that: 'The button background can be either blue or white, but the button must always include the standard color Google "G" on a white tile.'
