### ISSUE TITLE
Invite to space workflow is not logical

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-android#4295]
### Steps to reproduce

1. In the left panel, ⋮ -> Invite people
2. By username or email
3. Select a person -> Invite

#### What did you expect?
Going back to left panel view

#### What happened instead?
Sent back to the "Invite to `<space>`" toast

### Application version and app store

Element 1.3.4 (RC)

### Will you send logs?

No

**Comment by niquewoodhouse** [comment]
Going back to left panel view 👍

**Comment by fedrunov** [comment]
Done in Element 1.3.18
