### ISSUE TITLE
Invite by email doesn't work

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-android#4297]
### Steps to reproduce

1. In the left panel, ⋮ -> Invite people
2. By username or email
3. Enter valid email

#### What did you expect?
Be able to invite by email

#### What happened instead?
Cannot proceed

See also #3820

### Application version and app store

Element 1.3.4 (RC)

### Will you send logs?

No

**Comment by bmarty** [comment]
Fixed in EA 1.3.8
