### ISSUE TITLE
Conference with Jitsi support

### ISSUE THREAD

**Issue by bmarty** [vector-im/element-android#43]
- [ ] import last Jitsi lib

**Comment by rajil** [comment]
It would be great if we have the ability to use our own self hosted Jitsi server instead of hardcoded https://meet.jit.si/. This feature exists in Rocket Chat, and would be awesome to see in Riot.

**Comment by bpcurse** [comment]
From a privacy view it is essential to use a self-hosted server. If a third party controls the server, communication can be monitored and recorded.

**Comment by almereyda** [comment]
`config.json` from custom Riot instances will contain hints about where to find and how to integrate a self hosted Jitsi. Additionally self-hosted integration servers like Dimension also integrate with custom Jitsi instances.

These configurations might eventually be reused, if present.

**Comment by DJCrashdummy** [comment]
@bmarty i guess this also needs a ~"riotx-go-live" tag, considering #611 is just about the 1:1 resp. p2p-feature and the announcement in [TWIM 2020-05-01](https://www.matrix.org/blog/2020/05/01/this-week-in-matrix-2020-05-01#riotx), that *WebRTC audio and video calls* **and** *Jitsi conference integration* will be implemented.

**Comment by dhrunia** [comment]
Would it be possible to have all members of the room (where conference call is made) get a call notification similar to one-one calls so they can accept or reject? Currently one has to create a conference call and then message members to join which is okay for tech savy users but average users just say they didn't get a call notification.

**Comment by mpfaff** [comment]
@dhrunia that would need to be off by default, because for rooms with >20 members, it would be insane for everyone to be notified just because one user decided to go on voice chat.

**Comment by sruggier** [comment]
Rather than a per-room setting, that sounds like something that the user should have to select each time they initiate a call.

As long as the hypothetical interface for that has a dynamic filter, along with select all and invert selection commands, it should be reasonable for most use cases.

**Comment by MurzNN** [comment]
On recent Skype we can initiate group call as Loud and as Silent - https://support.skype.com/en/faq/FA10613/how-do-i-make-a-call-in-skype#

> when you start a video call , you can choose whether you want the call to ring everyone in the group or be ringless
