### ISSUE TITLE
Spinner has no text next to it

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-android#4305]
### Steps to reproduce

1. Browse users in a space
2. Click on user
3. See spinner in a wide dialog without any text

#### What did you expect?
Some text telling me what is going on

#### What happened instead?
![Screenshot_20211020-154708.png](https://user-images.githubusercontent.com/51663/138318706-e0daae76-a4a7-4ea0-9842-8b207b7017aa.png)

### Application version and app store

Element 1.3.4 (RC)

### Will you send logs?

No

**Comment by fedrunov** [comment]
@niquewoodhouse which text should we show here? Just some generic "loading..." (we have already this copy) or something more specific to an action?
