### ISSUE TITLE
Spaces: "New: Let people in spaces find and join private room" doesn't seem relevant

### ISSUE THREAD

**Issue by novocaine** [vector-im/element-android#4315]
## Action needed
- [ ] Remove 

## Description

This popped up the first time I went to access spaces after logging in on Android.

It's nice that we're trying to give our users updates on new functionality, but I don't think this is is quite right - 

* It's interrupting what I'm doing at a moment not really related to the functionality
* It's very wordy and I'm not sure many people would really take in what it means, especially not new users
* It doesn't actually guide users into the flow directly (a button that takes them somewhere)

![Screenshot_20211020-145449_Element](https://user-images.githubusercontent.com/57377/138459552-7e7e9ca2-0895-4ee3-9a41-7a7a2027f926.jpg)

![Screenshot_20211020-145510_Element](https://user-images.githubusercontent.com/57377/138459568-cb084539-e3da-4545-9fee-049bdd91f58e.jpg)

**Comment by bmarty** [comment]
In Element 1.3.18
