### ISSUE TITLE
Direct message not initiated after telling the app to do so via the space member list 

### ISSUE THREAD

**Issue by aWeinzierl** [vector-im/element-android#4319]
### Steps to reproduce

1. open a space 
2. use context menu of different space (not sure if the Space must be different)
3. list members 
4. tap on a member (you don't have a chat with <- maybe not required either) 
5. tap direct message 
6. see Space menu

#### What did you expect?

See DM opening

#### What happened instead?

See Space menu

https://user-images.githubusercontent.com/20560137/138476277-40a1cd59-bf91-439d-86ea-a3c3816f414e.mp4

### Your phone model

Fairphone 3+

### Operating system version

Android 10

### Application version and app store

Element version 1.3.4 [40103042] (G-b4036) from GitHub

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by kittykat** [comment]
> has `needs-product` been added because we're unsure about opening a dm?

I'm not sure why I added Needs-Product. I think this should just be fixed, it can get very frustrating!

**Comment by daniellekirkwood** [comment]
Agreed. Although @kittykat Kat speaks for the Needs-Product label.

I will remove the tag and mark this issue as "Ready". The issue should be fixed and the Direct Message button should take users to create a DM

**Comment by mnaturel** [comment]
Hello @daniellekirkwood, as suggested by @bmarty in [this comment](https://github.com/vector-im/element-android/pull/5292#pullrequestreview-889772403), I wanted to confirm the changes I have done in the navigation behavior. In the following GIFs you can see the before/after. The difference is we do not close the member profile screen anymore which has impact on back navigation.

### Before (From room timeline)
<img src="https://user-images.githubusercontent.com/46314705/155166314-97876fb3-330b-4f12-9b12-7d0aa636013d.gif" width="600" />

### After (From room timeline)
<img src="https://user-images.githubusercontent.com/46314705/155166312-ef82a940-0431-4c16-a5ad-792f4a0c1437.gif" width="300" />

### After (From list members)
<img src="https://user-images.githubusercontent.com/46314705/155166304-70da7119-4bef-46be-a3ef-8b9c44f2a70c.gif" width="300" />

**Comment by bmarty** [comment]
Fixed in 1.4.4
