### ISSUE TITLE
Don't open menu when long clicking a link

### ISSUE THREAD

**Issue by chagai95** [vector-im/element-android#4324]
### Steps to reproduce

1. long clicking a link to copy it opens the menu  meant for the long click on a message

#### What did you expect?
The menu should not open
#### What happened instead?
The menu opened

### Your phone model

Galaxy A51

### Operating system version

One UI 3.1, Android 11

### Application version and app store

1.3.3 [40103032] (G-b3874)

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by bmarty** [comment]
In EA 1.3.10
