### ISSUE TITLE
Recently-made rooms disappear from a private space after triggering rageshake by accident while creating the private space

### ISSUE THREAD

**Issue by Linerly** [vector-im/element-android#4327]
### Steps to reproduce

1. Create a private space
2. Trigger rageshake by shaking the phone (though in my case, the phone's screen went off, then turned my phone's screen on and unlock the phone)

#### What did you expect?
Private space to be successfully created with the rooms in the private space as well

#### What happened instead?
Private space got created, but the rooms in the private space disappears (eventually having to add them to the private space manually, but that didn't work as well)

### Your phone model

Mito W1

### Operating system version

Android 9

### Application version and app store

Element version 1.3.4, olm version 3.2.4 from GitHub

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by kittykat** [comment]
@Linerly is this reliable reproducible for you?

**Comment by Linerly** [comment]
Hmm, I don't think so anymore

**Comment by kittykat** [comment]
I'm going to close this for now, please re-open or @kittykat if you experience the problem again
