### ISSUE TITLE
Start a new Thread by replying to a message in Timeline

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-android#4328]
As a user I want to start a new Thread from a message in the Timeline.

Long press on message to open options > start Thread is an option > 
- Design is here: https://www.figma.com/file/T309ztx0sNyOOK6NKVLHsK/Threads?node-id=1304%3A244131

[Short press](https://docs.google.com/document/d/1pmB_tvslngZssWgHuuGtNZ0G6UBrGv9Rb3zu4cFJvCs/edit?usp=sharing) is not included in the MVP/P0 version of Threads. 

Following https://github.com/matrix-org/matrix-doc/pull/3440

- [x] Add **Reply In Thread** option on long click
- [x] Display threads in the appropriate thread timeline
- [x] Send a **regular** message from threads
- [x] Send a **Reply** message from threads
- [x] Send a **Quote** message from threads
- [x] Send an **Edit** event from within threads
- [x] Indicate a message is a root thread _(with a temp UI)_
- [x] Use relation type m.thread to start Threads
- [x] Make sure that m.thread can be combined with m.in_reply_to to allow quote relies in threads

Added:
- [ ] When user clicks "Reply in Thread" the message bar gets the focus so user can type reply immediately without the need for extra click

**Comment by daniellekirkwood** [comment]
Needs-Product is a label on this issue because we need to reach a conclusion on the Short Press discussion.

**Comment by daniellekirkwood** [comment]
Removing the Needs-Product label as short press has been delayed to V2 of Threads and is not included in the MVP

**Comment by daniellekirkwood** [comment]
Removing Jano's assignment as Designs have been added to the issue

**Comment by janogarcia** [comment]
@ariskotsomitopoulos We need to make sure that when the "Reply in thread" action is used the message composer input gets the focus automatically in the thread view, without requiring the user to manually tap on it to actually initiate the reply.

https://www.figma.com/file/T309ztx0sNyOOK6NKVLHsK/Threads?node-id=1304%3A244131

@daniellekirkwood Could you please add it as a task/acceptance criteria to the issue description? Thanks!
