### ISSUE TITLE
When changing the message to be replied from image message to text/audio message the old image belonging to previously selected message should go away 

### ISSUE THREAD

**Issue by ryg-git** [vector-im/element-android#4343]
### Steps to reproduce

1. Open a room screen or DM screen.
2. Select a image message to reply either by swiping or from long press menu 
![IMG_20211026_195908](https://user-images.githubusercontent.com/69393483/138902183-ee5b74a6-5b4b-4248-9956-117fe35b1354.jpg)

3. Then while the image message is selected for the reply select another message  (text or audio)
4. Now you will see that only text is replaced i.e image name is changed to selected message or file but the previously selected image doesn't go away. 
![IMG_20211026_200610](https://user-images.githubusercontent.com/69393483/138902361-634f4d94-0b02-4671-ae21-385aa2260ead.jpg)

5. Also if you select text message first and then you change message to be replied to image the selected image is not displayed only image file name is displayed.
![IMG_20211026_200651](https://user-images.githubusercontent.com/69393483/138902671-faac2365-445a-4442-bc8a-5cf1aea4d87a.jpg)
![IMG_20211026_200712](https://user-images.githubusercontent.com/69393483/138902789-c2607968-c425-493d-86df-e6f6bd15c4fd.jpg)

#### What did you expect?
When changing the message to be replied from image to text the old image should go away and only text belonging to newly selected message should be displayed,
Also if you select text message first to reply and then select image the image should also be displayed not only file name.
#### What happened instead?

If you select image first to reply and then change the message to be replied to text the image doesn't go away.
If you select text message first to reply and then select image the image is not displayed only file name is displayed.

### Your phone model

Xiaomi redmi note 8 pro

### Operating system version

Android 11

### Application version and app store

Element android app version 1.3.3

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by bmarty** [comment]
Fixed in #4490 and Element 1.3.9
