### ISSUE TITLE
Tapping notifications gives a "the link was malformed" error

### ISSUE THREAD

**Issue by francois-pasquier** [vector-im/element-android#4374]
### Steps to reproduce

1. On app closed 
2. I tap a notification 
3. The app opens and I get a "the link was malformed" error

#### What did you expect?
Having no error 

#### What happened instead?
The error

### Your phone model

Samsung s21 ultra 5g

### Operating system version

Android 11

### Application version and app store

App: 1.3.3 [40103032] (G-b3874), olm 3.2.4

### Will you send logs?

Yes

**Comment by SimonBrandner** [comment]
This should be fixed in the next release :)

**Comment by ouchadam** [comment]
it'll be part of 1.3.5 once google finish reviewing :crossed_fingers:  #4267
