### ISSUE TITLE
Notifications disappearing 

### ISSUE THREAD

**Issue by CubicrootXYZ** [vector-im/element-android#4375]
# Short description

Notifications disappear minutes to hours after they came up. 

# Step by step 

1. No client open 
2. Send message to me
3. Notification pops up
4. Wait a few dozens of minutes up to 2, 3 hours 
5. Notification is no longer there
6. Open the app - messages are still unread 

# App version 

1.3.3 [40103032] (G-b3874)

# Hardware

OnePlus 6T with OxygenOS 11.1.1.1

Accu optimization deactivated

# Additional info

Executed the built in notification Test without any findings.

**Comment by ouchadam** [comment]
a lot of notification issues were fixed in https://github.com/vector-im/element-android/pull/4274 

hopefully 1.3.7 resolves this

**Comment by CubicrootXYZ** [comment]
Got the update for 1.3.6 and the issues disappeard.

**Comment by Locne55** [comment]
This issue is back

**Comment by lindhe** [comment]
I believe that was reported in #7643 and fixed in [release v1.5.12](https://github.com/vector-im/element-android/releases/tag/v1.5.12).
