### ISSUE TITLE
Encryption works on Windows but not on Android

### ISSUE THREAD

**Issue by CorentinQuique** [vector-im/element-android#4376]
### Steps to reproduce

When i talk with the same people in another matrix instance :

- Encryption on Windows works fine
- Encryption on Android doesn't work.

I tried to reinitialised my encryptions keys : reinitialisation works but doesn't fix the problem.

Uninstall and reinstall android app : it works. Problem solved.

### Intended result and actual result

I expected the encryption on windows and on android works together.

It don't understand why one works fine and the other not.

### Your phone model

Samsung Galaxy S20 FE 5G

### Operating system version

Android 11.0

### Application version and app store

Element version 1.3.3 from F-Droid

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by darnir** [comment]
Could this be similar to #3429 ?

**Comment by meyerrj** [comment]
This is also likely related to #1721

**Comment by CorentinQuique** [comment]
> 
> 
> Could this be similar to #3429 ?

Yes it more looks like #3429 than #1721

**Comment by ouchadam** [comment]
thanks for raising the issue, I'm going to close this in favour of #3429 (which the crypto team are looking into)

If I've misunderstood and you believe this could be a separate dedicated issue, please reopen!
