### ISSUE TITLE
Wrong cursor position when entering new room name

### ISSUE THREAD

**Issue by bosskopp** [vector-im/element-android#4377]
### Steps to reproduce

When the "Create New Room" dialog is open
And I click on the input field "Name"
And I enter a character
Then the cursor position moves to the beginning of the string

#### What did you expect?

Given the room name "room"
When I enter the characters r, o, o, m
Then the input should read "room"

#### What happened instead?

The input reads "moor"

### Your phone model

Pixel 6

### Operating system version

Android 12.0

### Application version and app store

Element Version 1.3.3 from Play Store

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by ouchadam** [comment]
this has been fixed in 1.3.5 but we're waiting for google to finish reviewing the release #4276
