### ISSUE TITLE
Add "Sign in" to Splash screen

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-android#4382]
### Your use case

When a user opens the app they see a splash screen. Right now the only option is to "Get Started". 
We want to add the ability to Sign in, as well as Create an account.

_This is the Basic Splash screen and is a small change to the existing flow so that we might learn from users_

**Comment by amshakal** [comment]
In the proposed solution I have added both the buttons to the splash screen - Get started and I already have an account. Both the CTAs would lead to the same page as before i.e. server selection, and would make the screen below obsolete. 
<img width="275" alt="Screenshot 2021-11-02 at 21 12 31" src="https://user-images.githubusercontent.com/85162587/139952544-e13b6c07-fd40-4e95-aa78-4503fc73dd34.png">

If this is hard to implement at the moment, consider keeping this screen for now, as we are going to be redoing this flow with the new authentication flow anyway.

Here is the proposed solution:
![register](https://user-images.githubusercontent.com/85162587/139951879-a32fe31b-7635-4afb-a11c-9216aec999ea.png)

**Comment by daniellekirkwood** [comment]
Removing the X-Needs-Design label as we have had a response from design

**Comment by amshakal** [comment]
Just a quick note. We are planning to change the tag line from 'It's your conversation. Own it' to 'Own your conversations.'

**Comment by daniellekirkwood** [comment]
![Screenshot 2021-11-30 at 13 29 04](https://user-images.githubusercontent.com/89144281/144058631-83a02e64-7228-45d5-89b7-6c1bfadacd3d.png)


Discussed on Element today
