### ISSUE TITLE
Make the placement and size of "Next" buttons in FTUE consistent

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-android#4383]
### Your use case

Today our buttons during sign-up, sign-in or general onboarding are not consistent

**Comment by amshakal** [comment]
Consider using full length primary buttons. Here are a few examples:

![register](https://user-images.githubusercontent.com/85162587/139952855-57ba5ffb-daec-4d06-8374-796bea08852f.png)
![Sign up](https://user-images.githubusercontent.com/85162587/139952857-0ed79aec-ee1a-440a-9163-2389c9cab709.png)
![T+C](https://user-images.githubusercontent.com/85162587/139952858-fce3a5b6-2310-48d9-9415-2ed95b63eed4.png)
![Email Verification](https://user-images.githubusercontent.com/85162587/139952853-95ceee9e-01a5-4dbb-ac4d-c976a48f8926.png)

**Comment by daniellekirkwood** [comment]
Removing the X-Needs-Design label as we have a response from Design.

**Comment by daniellekirkwood** [comment]
I think we can close this issue with "no action" as we've decided to build the new experience instead. WDYT @amshakal

**Comment by amshakal** [comment]
Works for me :)
