### ISSUE TITLE
Search results from Threads

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-android#4387]
- When I search for a message, return results from a Thread
  - Design (pending)
  - Unencrypted Rooms & ~~Encrypted Rooms~~

Designs are here: https://www.figma.com/file/T309ztx0sNyOOK6NKVLHsK/Threads?node-id=2858%3A290566

EDIT: In testing on January 20 we found that tapping on the Thread root from a search result causes the app to crash.

**Comment by daniellekirkwood** [comment]
@janogarcia are we expecting any changes to the way that threaded messages show up when a user searches for them? Is today's behaviour acceptable?

**Comment by janogarcia** [comment]
@daniellekirkwood Thanks for flagging this one. It seems I couldn't update the issue description, so that it points to the proper Figma frame, and forgot to ping you on that.

https://www.figma.com/file/T309ztx0sNyOOK6NKVLHsK/Threads?node-id=2858%3A290566

**Comment by daniellekirkwood** [comment]
Thanks, @janogarcia ! I have added the link to the description and removed your assignment :)

**Comment by daniellekirkwood** [comment]
We discussed this issue in standup today and have updated the issue description to remove encrypted rooms as this is not possible.
