### ISSUE TITLE
Find a Thread through mentions - Notifications & Badges

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-android#4388]
### Your use case

WIP: Danielle will update with more info soon!

  - [Android Design: Unread Threads, no mentions](https://www.figma.com/file/T309ztx0sNyOOK6NKVLHsK/Threads?node-id=1587%3A244184)
  - [Android Design: Unread Threads, with mentions](https://www.figma.com/file/T309ztx0sNyOOK6NKVLHsK/Threads?node-id=1587%3A244197)
  - [Android Design: & unreads more than 99](https://www.figma.com/file/T309ztx0sNyOOK6NKVLHsK/Threads?node-id=1587%3A244731)

We also need to discuss Push notifications 

### Additional context

[Notification documentation and notes](https://docs.google.com/document/d/1V5G1WbvBwvqt3t0XCMfIt39Eu-veoN-4Ca7Z5VGE_A8/edit?usp=sharing)

For the MVP release Thread panel badges should be dots, without numbers.

A limitation of the MVP release is that clearing notifications on one platform will not clear them on other platforms.

**Comment by daniellekirkwood** [comment]
@ariskotsomitopoulos it was identified in testing on January 20, 2022 that only the grey dot appears, never a red dot...

**Comment by daniellekirkwood** [comment]
@janogarcia updated issue to be clear that these should be dots, not numbers.

**Comment by ariskotsomitopoulos** [comment]
> @ariskotsomitopoulos can you confirm that this issue has been completed?
> It's marked as Shipped on our project board but may have been re-opened or not completed...?

Yes, it's completed maybe, have been reopened to remove the number from the notifications that have been also done

**Comment by daniellekirkwood** [comment]
Great, thank you. I will close this
