### ISSUE TITLE
Notification ring for every line in a private conversation

### ISSUE THREAD

**Issue by gcp** [vector-im/element-android#4398]
### Steps to reproduce

1. Have Element installed on an Android Phone (Pixel 2 XL on Android 11)
2. User starts a private conversation with me
3. Phone notifies on every single line the person types.

#### What did you expect?

Single notification no more frequent than once every 1-5 minutes. Maybe I'm mistaken but I think this is how it used to work before? The current behavior is extremely disruptive and I don't remember Element being this annoying, and surely people have talked to me before.

There's no point in notifying on every line. If there was a long pause and they start again, fine, maybe that's a new conversation.

#### What happened instead?

DINGDING DINGDING DINGDING DINGDING DINGDING DINGDING DINGDING DINGDING DINGDING DINGDING DINGDING DINGDING DINGDING DINGDING DINGDING DINGDING DINGDING DINGDING DINGDING DINGDING DINGDING DINGDING DINGDING DINGDING DINGDING DINGDING DINGDING DINGDING DINGDING 

(now imagine a Smartwatch doubling the notifications and you can understand that I pretty much want to uninstall Element permanently)

### Your phone model

Pixel 2 XL

### Operating system version

Android 11

### Application version and app store

1.3.3 olm 3.2.4

### Homeserver

chat.mozilla.org

### Will you send logs?

No

**Comment by gcp** [comment]
The phone dings and the watch vibrates :)

**Comment by ouchadam** [comment]
perfect, in that case this has been fixed! 

thanks for raising the issue, for now I'm going to close it as we have a fix in the process of being released
