### ISSUE TITLE
Right-to-left typing instead of left-to-right

### ISSUE THREAD

**Issue by porcospino44** [vector-im/element-android#4406]
### Steps to reproduce

1. Go to the room explorer to add a new server to search rooms in, or to create a new room in your homeserver.
2. Type a server name (for the room explorer) or a room name (for the new room creation dialogue).

#### What did you expect?

Left-to-right typing, as happens elsewhere in the app.

#### What happened instead?

The characters of the server/room name are typed right-to-left.

### Your phone model

Samsung Galaxy A32

### Operating system version

Android 11

### Application version and app store

1.3.3 [40103030] (F-651e3478)

### Homeserver

mozilla.org

### Will you send logs?

Yes

**Comment by testuser002148953** [comment]
Confirmed for me too. Element Android, Lineage OS 18.1 (Android 11), OnePlus 8 Pro

**Comment by TheEagleByte** [comment]
Happening for a user of mine.

> Phone: moto g stylus (XT2115DL)
> App: Latest version of the app
> Android 11 is new it just installed the other day

**Comment by AdamTomaja** [comment]
@damtux:matrix.org:

Hello everyone! :)
I think I've just found a new bug on Element Android (1.3.3 Fdroid): when I'm typing the title of a new room I'm creating, the characters are written backward. E.g. to write NEW I have to type WEN

**Comment by daniellekirkwood** [comment]
Fixed in EA 1.3.5 FTR
