### ISSUE TITLE
Unable to receive a call on f-droid version using ungoogled Android

### ISSUE THREAD

**Issue by Kreyren** [vector-im/element-android#4407]
### Steps to reproduce

0. Install the app from F-Droid and log in
1. Call that account while the app is in the background and expect to not get any notification about the call which is unexpected

#### What did you expect?

Being able to use the app instead of the caller app

#### What happened instead?

Having to text people message to call me and wait for them to read it and call me

### Your phone model

OnePlus2 (hardware modded)

### Operating system version

Android 10 (QQ3A.200805.0010) from DivestOS

### Application version and app store

Element version 1.3.3 [40103030] (F-651e3478), olm version 3.2.4 from F-Droid

### Homeserver

irelevant

### Will you send logs?

No

**Comment by ouchadam** [comment]
You may be experiencing https://github.com/vector-im/element-android/issues/4298 

For some quick context

The F-Droid variant uses set interval polling for background messages and calls, the default is set to every 60 seconds, which means in the best case scenario the caller may have to ring for up to 60 seconds (until the next poll event) before the call is received.  

_however_, we're at the mercy of the system as to whether that rate is actually respected, due to background restrictions imposed by the system https://github.com/vector-im/element-android/issues/4298 

------

https://github.com/vector-im/element-android/pull/4314 should improve the situation in combination with setting a shorter polling window (at the cost of battery)

**Comment by ouchadam** [comment]
going to close this issue due to inactivity, please reopen if 1.3.7+ doesn't fix the issue

**Comment by Kreyren** [comment]
@ouchadam Same issue on 1.3.7

**Comment by ouchadam** [comment]
to confirm, does this apply to all notifications whilst the app is in the background (messages, invites etc)?

**Comment by Kreyren** [comment]
> to confirm, does this apply to all notifications whilst the app is in the background (messages, invites etc) or only calls? -- @ouchadam (https://github.com/vector-im/element-android/issues/4407#issuecomment-984558500)

Seems to be all notifications

**Comment by ouchadam** [comment]
all notifications failing to come through suggests this is the background sync issue #4298 

- does DivestOS have battery saving options (is it possible to disable them for element?)
- is the _Listening for notifications_ notification displaying but no notifications are coming through?

**Comment by Kreyren** [comment]
> Seems to be all notifications -- @Kreyren (https://github.com/vector-im/element-android/issues/4407#issuecomment-985065696)

Sorry i had the device in do not disturb without realizing it, reclarifying: I can see `Listening for notifications` and i get message notifications, but no call and invite notifications.

> does DivestOS have battery saving options (is it possible to disable them for element?) -- @ouchadam (https://github.com/vector-im/element-android/issues/4407#issuecomment-985336147)

Seems that I already have those disabled.

> is the Listening for notifications notification displaying but no notifications are coming through? -- @ouchadam (https://github.com/vector-im/element-android/issues/4407#issuecomment-985336147)

It's displaying but no calls and invite notifications are forwarded through only new messages that I am aware of.

**Comment by ouchadam** [comment]
interesting that messages are coming through but not calls, I've reopened the issue

something else to check is whether the call channel notifications are enabled (Settings -> Notifications -> Configure Call Notifications) and if the web call notification settings are also enabled. Might also be worth setting the web call notifications to off and noisy again as we've seen issues where the behind the scenes rules become out of sync. 

| CALL CHANNEL | WEB NOTIFICATIONS |
| --- | --- |
|![Screenshot_20211203_140342](https://user-images.githubusercontent.com/1848238/144615309-98474b21-3afe-49d7-8879-785c1816f7d2.png)|![2021-12-03T14:01:00,236421310+00:00](https://user-images.githubusercontent.com/1848238/144615328-321f5b7f-c738-43d1-b488-2dccb06e5154.png)

**Comment by Kreyren** [comment]
Figured it out i didn't have a verified session with security set to only encrypt in verified session so it was just giving me a message notification instead of call. Works now with the session verified.

**Comment by ouchadam** [comment]
great to hear! going to close this issue off

cc @daniellekirkwood this scenario could be catching out others, do you think dedicated messaging could help? "Incoming call ignored due to non verified caller"~
