### ISSUE TITLE
Conversation-style icons are cropped incorrectly

### ISSUE THREAD

**Issue by dkter** [vector-im/element-android#4417]
### Steps to reproduce

Receive a notification

#### What did you expect?
A correct icon crop (this is taken from #1809)
![image](https://user-images.githubusercontent.com/34610081/140436608-2e369a62-7a15-45d9-9956-07ec2ae70d94.png)

#### What happened instead?
The icon is not cropped into a square shape and has parts of the image cut off.
![image](https://user-images.githubusercontent.com/34610081/140436717-f77e52aa-0c0c-4561-bb7f-6b6ffa7df828.png)

This was a bug I explicitly fixed in #1809 (see 5df0bd69c7e7331474c4876fc8d20a963b57f1ca) but it was reverted in 1.3.4, probably when this PR was merged: #3313 
#3313 seems to add the exact same feature #1809 already added, and #1809 was merged before #3313. So merging #3313 didn't change much -- the only thing it changes (aside from changing `removeAllDynamicShortcuts` to `removeLongLivedShortcuts`) is duplicating some of the [code that's already in ShortcutCreator](https://github.com/vector-im/element-android/blob/f135fbea351cd3c1db15d804b320b9c7ac9f75db/vector/src/main/java/im/vector/app/features/home/ShortcutCreator.kt#L74) in NotificationDrawerManager (albeit not using `Bitmap.toProfileImageIcon`, which should be used to render the room icons correctly).

Now every time a notification is received, the shortcut for that room is recreated using the notification code, which renders the icon incorrectly. Sometimes the shortcut will be recreated again with the original ShortcutCreator, which renders the icon correctly.

It looks like there's been a major refactoring of the notification code since #3313, but the redundant code [still exists](https://github.com/vector-im/element-android/blob/fe9dde5a14fd0f91d9cc11d8c6a4dd01f32db1bb/vector/src/main/java/im/vector/app/features/notifications/RoomGroupMessageCreator.kt#L66). I don't see a reason to keep it -- it hasn't changed anything behaviour-wise, at least for me, other than introducing this bug. If there's any reason this should be kept, it should use ShortcutCreator instead.

### Your phone model

Pixel 3a

### Operating system version

Android 12

### Application version and app store

Tested on both Element 1.3.5 and 1.3.8-dev, GPlay variants

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by ouchadam** [comment]
Added in 1.3.8
