### ISSUE TITLE
Threads P0 half way smoke testing

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-android#4448]
Run an initial testing session to check that we're on the right track at the 50% completion mark.

#### What we need going into the session
- [x] List of completed and partially completed tasks based on [must haves](https://github.com/vector-im/element-meta/issues/3) for P0
- [x] Pick a time when most of the team can attend (Product, Design and lead developer for the platform must attend)

#### During the session
- Lay out standard paths to follow to achieve tasks (test cases with steps)
- Run through some exploratory test cases (tasks to achieve without steps)
- Collect defects and enhancements which are found, and  make sure to collect accurate reproductions steps with screenshots and screen recordings as needed
- Compare against designs

#### Outputs from the session
- [ ] Product processes and files found issues
- [ ] Design reviews any designs to update for findings from session
- [ ] Acceptance criteria on issues updated as needed (by design, product or development)

**Comment by daniellekirkwood** [comment]
We expect to hit half-way towards the end of this sprint (started today).
This would make a testing session viable from the 29 November(ish).

@kittykat, could we organise an Android smoke testing session for the end of the 6th December week? Maybe the 9th or 10th?

**Comment by kittykat** [comment]
Booked in for Friday 10th December
