### ISSUE TITLE
Threads P0 second smoke testing

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-android#4449]
Run a follow up testing session to check that we're on the right track at the ~85% completion mark.

#### What we need going into the session
- [ ] List of completed and partially completed tasks based on [must haves](https://github.com/vector-im/element-meta/issues/3) for P0
- [ ] Pick a time when most of the team can attend (Product, Design and lead developer for the platform must attend)
- [ ] [First round of smoke testing is complete](https://github.com/vector-im/element-android/issues/4448) and majority of issues found have been resolved

#### During the session
- Lay out standard paths to follow to achieve tasks (test cases with steps)
- Run through some exploratory test cases (tasks to achieve without steps)
- Collect defects and enhancements which are found, and  make sure to collect accurate reproductions steps with screenshots and screen recordings as needed
- Compare against designs

#### Outputs from the session
- [ ] Product processes and files found issues
- [ ] Design reviews any designs to update for findings from session
- [ ] Acceptance criteria on issues updated as needed (by design, product or development)

**Comment by frakic** [comment]
I've gone through all of test cases before running the Community session yesterday so this issue can be closed.
