### ISSUE TITLE
Use the stable hierarchy endpoint from MSC2946

### ISSUE THREAD

**Issue by clokep** [vector-im/element-android#4462]
### Description

[MSC2946](https://github.com/matrix-org/matrix-doc/pull/2946) has completed FCP and Synapse is implementing the stable endpoint (see matrix-org/synapse#11329). It would be nice for Element Android to implement the following so that the unstable endpoints can be deprecated:

* Start using the stable `/_matrix/client/v1/rooms/{roomID}/hierarchy` endpoint.
* Ensure that the `room_id` is not accessed via the list of `children_state` (this is nested under the room information and should be unnecesary).

This should most likely be implemented to attempt using the stable endpoint before falling back to the unstable endpoint. Please let me know if you have any questions.

**Comment by clokep** [comment]
> Matrix SDK2 does not support yet the `/v1` API. Is it available in the `/r0` path?

No, it will not be available at the `/r0` path due to the new spec versioning of endpoints.

**Comment by bmarty** [comment]
information about v1 can be found here #4245 (follow the links from there)

Let's discuss this together.

**Comment by clokep** [comment]
The other thing to check is if the `join_rules` field (plural version) is being used instead of the proper `join_rule` field.
