### ISSUE TITLE
Searching for rooms is case sensitive with special characters

### ISSUE THREAD

**Issue by chagai95** [vector-im/element-android#4465]
### Steps to reproduce

1. Search for a room which starts with Ú for example using a ú in the search query.

#### What did you expect?
To find everything
#### What happened instead?
I didn't

### Your phone model

Xiaomi Pro 8

### Operating system version

Android 12

### Application version and app store

1.3.7 [40103072] (G-b4267)

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by chagai95** [comment]
This is probably a duplicate: 
https://github.com/vector-im/element-android/issues/3317

**Comment by ouchadam** [comment]
should be fixed with https://github.com/vector-im/element-android/pull/4352 (1.3.7)

**Comment by ouchadam** [comment]
@chagai95 I've just noticed the version you've raised this issue for is 1.3.7 which would mean #4352 didn't fix the issue, I'm hoping you meant a different version :sweat_smile: 

I'm trying to reproduce the issue but it seems to work~ does this example cover the problematic scenario?

| UPPER | LOWER |
| --- | --- | 
![Screenshot_20211116_110649](https://user-images.githubusercontent.com/1848238/141974505-7d3bdca8-576a-419f-a7b0-5057e094ba02.png)|![Screenshot_20211116_110634](https://user-images.githubusercontent.com/1848238/141974511-d7359098-f628-4f67-b222-f837f31c152a.png)

**Comment by chagai95** [comment]
Just tested, it works, sorry my mistake, I don't know how I got the wrong version.

**Comment by ouchadam** [comment]
no problem, thanks for confirming!
