### ISSUE TITLE
Battery Drain On call & Overheating

### ISSUE THREAD

**Issue by Flam3z** [vector-im/element-android#4473]
### Steps to reproduce

Just start a call with any user.

### Outcome

I expected for my phone to be very hot & drain my batter within mere minutes.

What actually happened was that  The back of my phone would heat up quick and drain my battery really fast to where I have to always keep it on the charger while I am on the phone.

### Your phone model

Samsung S10

### Operating system version

Android 11

### Application version and app store

1.3.6 [40103062] (G-b4127) olm version: 3.2.4

### Homeserver

Matrix.org

### Will you send logs?

Yes

**Comment by ouchadam** [comment]
This is a tricky one as it's occurring within the calls, which we unfortunately don't have much control over, the calls are using Jitsi which in turn uses react-native to bind to the javascript webrtc implementation (lots of battery/cpu heavy steps)

we have recently upgraded the library https://github.com/vector-im/element-android/pull/4504 and it'll be available in 1.3.9, this might help :crossed_fingers:

**Comment by Flam3z** [comment]
I'll reply here if theres a positive change 🤞

**Comment by WNYprideprep** [comment]
Having this same issue with a Moto G Stylus running Android 11
