### ISSUE TITLE
Review list of commands to display in the Thread's composer

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-android#4474]
There are items in the **/command** list that are only applicable to the room and so it does not make sense to have them appear in the Thread.

[Here is a list of commands and the proposal for which to remove from the Threads composer](https://docs.google.com/spreadsheets/d/16BTyouFCqqBYhA1rnDPOvRb7wlJACcmeqaq0td8Mehc/edit?usp=sharing)

- [ ] Remove the commands from the list (When a user types "/" a list appears, this should only contain the actions that the user can take)
- [ ] When a user tries to use a command that is not available in the Thread, show an error message that says: 

> **Command error**
> This command is not permitted in a thread
> OK

**Comment by daniellekirkwood** [comment]
@janogarcia I've added a solution into the issue info here, please let us know if there's anything that should change

**Comment by janogarcia** [comment]
I'd suggest tweaking the copy to make it a bit more helpful, by telling the users how to move forward.

```
**Unavailable command**
This command is not available in threads. Try running it in the room instead.
OK
```

...or something along the lines. What do you think, @daniellekirkwood?
