### ISSUE TITLE
Fix crash when staring a jitsi call on Android versions 7.x and below.

### ISSUE THREAD

**Issue by langleyd** [vector-im/element-android#4489]
Since app version 1.2.1 jitsi calls have crashes on android api 25(OS 7.x) and below due this bug in a library we have a transitive dependency on from the jitsi sdk.

**Comment by langleyd** [comment]
Closing as duplicate of https://github.com/vector-im/element-android/issues/4509

**Comment by bmarty** [comment]
ah sorry @langleyd I did not see this issue when I created #4509
