### ISSUE TITLE
Render markdown in chat previews

### ISSUE THREAD

**Issue by ghost** [vector-im/element-android#452]
When previewing the previous message from the direct messages tab, markdown is not rendered, resulting in previews such as:

```
Hello **there**
```

**Comment by bmarty** [comment]
There is a PR about it, thanks @onurays, the plan is to double check that it does not impact performance and merge the PR. On the PR, the changelog will have to follow new towncrier requirement

**Comment by bmarty** [comment]
Fixed in #4483
