### ISSUE TITLE
f-droid builds

### ISSUE THREAD

**Issue by bingoxo** [vector-im/element-android#4531]
### Your use case

As many have complained about before the f-droid version lacks a lot behind the google play one , the solution suggested has been making custom f-droid repo , but what about you guys build  the fdroid apk alongside the gplay one and put it in releases as well? so that even if it gets delayed in main fdroid repo , at least we have some way to get itt on time

**Comment by bmarty** [comment]
The core team does not own the signature to build the F-Droid APK

**Comment by bingoxo** [comment]
> The core team does not own the signature to build the F-Droid APK

when i said fdroid build i meant a foss build with no google services dependencies

**Comment by bingoxo** [comment]
@licaon-kter maybe you can help them get this sorted out :) ?

**Comment by licaon-kter** [comment]
@bingoxo "the core team" decides what versions and when is F-Droid allowed to build and publish.

Read the F-Droid Element .yml file notes and search the F-Droid forum.


/close this
