### ISSUE TITLE
Clicking beside a photo opens gallery.

### ISSUE THREAD

**Issue by Flam3z** [vector-im/element-android#4544]
### Steps to reproduce

1. Start in any room with photos sent
2. Press beside the sent photo

#### What did you expect?
Either for nothing to happen or for the image to open within element

#### What happened instead?
My 3rd party gallery app opened to view the photo

### Your phone model

Samsung S10

### Operating system version

Android 11

### Application version and app store

Element Version 1.3.8 Gplay

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by ouchadam** [comment]
thanks for raising! going to close in favour of this generic version https://github.com/vector-im/element-android/issues/4551
