### ISSUE TITLE
redundant events on smart watch

### ISSUE THREAD

**Issue by progserega** [vector-im/element-android#455]
RiotX show additional info in message-list: {NUM} notify.

I think RiotX change notify text for this. But this changing will come to smart watch as extra events such: "2 notify", "text of notify", "3 notify", "text of notify", "4 notify" and etc. 

This "{NUM} notify" is extra double info on smart watches. Old Riot was not show this additional info - he show only text of message and author of message - this was nice.

Images for example:
![Screenshot_20190731-221657](https://user-images.githubusercontent.com/1297163/62212310-cd033b80-b3e3-11e9-944e-c1a12465d731.png)
![IMG_20190731_222908](https://user-images.githubusercontent.com/1297163/62212355-e2786580-b3e3-11e9-94bf-75c486d46117.jpg)
![IMG_20190731_222902](https://user-images.githubusercontent.com/1297163/62212357-e310fc00-b3e3-11e9-91f1-18e3e9804d69.jpg)

**Comment by ouchadam** [comment]
this was fixed in https://github.com/vector-im/element-android/issues/1673 (1.3.2)
