### ISSUE TITLE
Message Bubbles - Layout for media - Android

### ISSUE THREAD

**Issue by jakewb-b** [vector-im/element-android#4575]
- As a user with message bubbles enabled
- I see media messages (images, video, audio files, voice messages) with no bubble, but with my messages right aligned and other people’s messages left aligned
- So that I have a more familiar interface and can easily differentiate my messages from other peoples

https://www.figma.com/file/zVtAKK0hzKu5JkpbzlE1pG/Message-Bubbles?node-id=1%3A29

NB - to aid in identifying the major tasks, issues have been created for specific items but this should not be taken to mean that is the only functionality to be implemented. The intent is that users with message bubbles enabled will have all the same Element functionality as users without message bubbles enabled.

**Update**
Media includes:
- [ ] Images (need timestamp updates)
- [ ] Files
- [ ] Audio
- [ ] Location
- [ ] Video (need timestamp updates)

**Comment by daniellekirkwood** [comment]
Today in testing we found a bug where audio messages send empty bubbles @ganfra 
![audiobubbles](https://user-images.githubusercontent.com/89144281/149386993-3cf34f47-0e1e-4661-be54-62fb746b1e75.jpg)

**Comment by daniellekirkwood** [comment]
This issue is complete. Closing
