### ISSUE TITLE
Message Bubbles - Polls - Android

### ISSUE THREAD

**Issue by jakewb-b** [vector-im/element-android#4576]
- As a user with message bubbles enabled
- I see polls display with no bubble around them, but my polls are right aligned and other people’s polls are left-aligned
- So that I can easily differentiate between my messages and other people’s, and the polls line up consistently with messages that appear in bubbles.

**Comment by daniellekirkwood** [comment]
![Polls Android Bubbles](https://user-images.githubusercontent.com/89144281/148814571-3dcfb22f-9026-44ba-9692-f5e8f653ba84.png)

Polls are centred on Mobile. @amshakal Can you confirm that we don't need to put a Poll on a side? 

@ganfra to confirm that polls are still centred when in landscape

**Comment by daniellekirkwood** [comment]
![Screenshot_20220113-181600_Element dbg](https://user-images.githubusercontent.com/89144281/149386388-1396ef08-1bbc-404d-b529-8c8803235d52.jpg)

Bug found in testing today: The sender of the second poll is the owner of the account (me) and so we need to make some changes to reflect the bubbles layout... Maybe remove the name & avatar (and find another way to distinguish that this is your poll...)

@amshakal could you advise?

**Comment by ganfra** [comment]
![Screen poll bubble](https://user-images.githubusercontent.com/8754928/149565799-31a43320-5286-401d-93ec-13d43326e0d7.png)
I tried putting them inside Bubble and find it ok. Only colors are a bit weird when it's outgoing message (with greenish background).

**Comment by daniellekirkwood** [comment]
The user in your screenshot is receiving the Polls?

**Comment by amshakal** [comment]
Hi, I agree. Polls inside bubble looks better in this case, and timestamp has a a home as well. I would be interested in seeing what it looks like from the sender's side, since that was the issue. Just an FYI, we are in the process to change the green colour of bubble to a more saturated colour, will be confirmed by tomorrow, so I can share how it will affect this component once a decision is made.

**Comment by ganfra** [comment]
![poll sender](https://user-images.githubusercontent.com/8754928/149746112-fcf4b529-d866-4148-8391-2763ad3a51b9.png)
 It looks like this ^ Like I said, colors are not that great, but if you are changing them, might be better!

**Comment by amshakal** [comment]
Yeah! I should have an update by Wednesday morning on that. Otherwise polls are looking good to me :)
