### ISSUE TITLE
Iterate on the user consent dialog about identity server look up

### ISSUE THREAD

**Issue by bmarty** [vector-im/element-android#4577]
### What we have now

<img width="332" alt="image" src="https://user-images.githubusercontent.com/3940906/144019952-ba612b79-07c0-47b4-9779-1a8f2ea74476.png">

### Changes

- [x] Wording:

>To discover existing contacts, you need to send contact info **(emails and phone numbers)** to your identity server.*(new lines removed)* We hash your data before sending for privacy.
>*(new lines added)*
>Do you <del>consent</del> **agree** to send this info?

- [x] "POLICY" action is removed, and the policy link(s) are added to the dialog itself, above the question "Do you agree...":

>Privacy policy
>
> - *link*

- [x] "NO" action is replaced by "Not now"
- [x] "YES" action is replaced by "Agree"

### Ref

https://support.google.com/googleplay/android-developer/answer/11150561 - section **User interface (UI)** and **Content**

**Comment by deniseal** [comment]
lgtm @bmarty. Updates to the privacy policy to clarify this are with Design to get added to the website, this is what will be included in clause 1.2:

> Your relationship with identity servers: you might chose to use an identity server, to allow other Matrix users to discover you via the Element app. This is optional and requires your explicit consent to discover users from your personal contacts. For the identity server made available by us, please see the Identity Server Privacy Notice.

@AmandineLP since this technically a policy update, can I get your approval please?

**Comment by bmarty** [comment]
First proposal:

<img width="335" alt="image" src="https://user-images.githubusercontent.com/3940906/144068041-86a0701d-76bd-4dfb-9283-28c0f9201a34.png">

**Comment by bmarty** [comment]
In EA 1.3.9
