### ISSUE TITLE
Message Bubbles - Quote - Android

### ISSUE THREAD

**Issue by jakewb-b** [vector-im/element-android#4580]
- As a user with message bubbles enabled
- I can quote a message and see the quoted text within the bubble of my message, differentiated by lighter grey text and a light grey vertical line
- So that I have a more familiar interface and can easily differentiate my messages from other peoples
<img width="227" alt="Screenshot 2021-11-25 at 16 04 46" src="https://user-images.githubusercontent.com/87766619/144020585-93ce1ee6-2b67-41c3-a1ce-80b7a0601139.png">

**Comment by daniellekirkwood** [comment]
![Screenshot_20220113-132744_Element dbg](https://user-images.githubusercontent.com/89144281/149386032-1b91b2e1-4bfd-4655-8d28-40fb4e3ca782.jpg)

@ganfra there was a bug raised today that the spacing on the Quote is incorrect - there needs to be more padding between the quote and the text (just like there is in the reply) 

I'm sure @amshakal will be able to provide more details if you need
