### ISSUE TITLE
Message Bubbles - React - Android

### ISSUE THREAD

**Issue by jakewb-b** [vector-im/element-android#4582]
- As a user with message bubbles enabled
- I can react to a message and see my reaction in a small bubble underneath the original message, with a counter of how many people have reacted with the same emoji
- So that I have a more familiar interface and can easily differentiate my messages from other peoples
<img width="180" alt="Screenshot 2021-11-25 at 16 02 37" src="https://user-images.githubusercontent.com/87766619/144020408-138353b3-12d5-4165-abcd-665d29825216.png">

**Comment by daniellekirkwood** [comment]
@ganfra you raised in the kick off whether we want to add "add reaction" and how we show more than 8 reactions as these are not currently supported on Android. I believe we still need a decision on that from @amshakal 

I think there's already issues for these items too, let me grab those.
