### ISSUE TITLE
Messages/Notifications only populate when app is in the foreground

### ISSUE THREAD

**Issue by Autre31415** [vector-im/element-android#4589]
### Steps to reproduce

1. Open the app.
2. Navigate away from the app and/or close it in recent apps.
3. Receive messages at some point while it's in the background.

#### What did you expect?
Notifications and messages should load up while the app is in the background.

#### What happened instead?
When opening up the app after having it in the background for a while and viewing a DM/chat, a loading bar will appear at the top and the chat will update and notifications will be sent at the same time.

Notably, I will always receive instant notifications and not see loading bars in chats while I keep the app open in the foreground, but as soon as it's in the background the app essentially shuts off until I bring it back to the front and then it loads and catches back up again.

#### Notes:
- This bugged behavior began on a fresh install of element on a brand new phone, and notably did not occur on the old one. I have not changed any notification related settings from their defaults on this new installation, and I successfully validated this new device using cross-signing.

- I ran the notification troubleshooter and the result included the following issues:
  - Firebase Token (!)
    ```
    Failed to retrieved FCM token:
    java.util.concurrent.ExecutionException:
    java.io.IOException: SERVICE_NOT_AVAILABLE
    ```
  - Token Registration (!) (probably a cascade from previous failure)
  - Text Push (!) (probably a cascade from previous failure)
  - Notification Display step does work
  
- Possibly relevant? In Advanced -> Notification Targets there are "No registered push gateways"

- Data/Battery saver features in Android are at their defaults (off)

### Your phone model

Pixel 6

### Operating system version

Android 12

### Application version and app store

1.3.7 [40103072] (G-b4267) Installed fresh off the Play Store, olm 3.2.4

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by ouchadam** [comment]
@Autre31415 thanks for raising, normally we would expect to see `java.io.IOException: SERVICE_NOT_AVAILABLE` when attempting to run the google play variant on a device without google play services 

we register the push gateways on each fresh application launch, eg force stopping or rebooting your device and launching element for the first time.

could I ask for you to try rebooting and running the notification troubleshooter again?

**Comment by Autre31415** [comment]
I've rebooted the device and ran the troubleshooter and I'm seeing the same result.

I also uninstalled the app, reinstalled it, verified the fresh session, removed the old stale session, and the troubleshooter and no gateways situation has remained the same.

**Comment by bmarty** [comment]
> Notably, I will always receive instant notifications and not see loading bars in chats while I keep the app open in the foreground, but as soon as it's in the background the app essentially shuts off until I bring it back to the front and then it loads and catches back up again.

This is expected, there is a continuous sync request when the app is in foreground. When in background, a Push from FCM trigger a sync request.

It seems that you have a problem with your phone, are the Google Play Services up to date?

This is what I have here FWIW:
<img width="390" alt="image" src="https://user-images.githubusercontent.com/3940906/144120925-4210b21d-2081-4d27-bc63-3952ddb88b8a.png">
<img width="275" alt="image" src="https://user-images.githubusercontent.com/3940906/144120870-28b35437-f7d1-42a8-8ffc-a8d5a78e4504.png">

**Comment by bmarty** [comment]
- Diagnostic OK on an Emulator with Android 12:
<img width="373" alt="image" src="https://user-images.githubusercontent.com/3940906/144124644-7a45aab7-a6fe-4fed-881d-5cc23157e872.png">

- Similar issue (without any answer yet): https://askandroidquestions.com/2021/06/23/how-to-fix-service_not_available-error-in-firebase-cloud-messaging-while-getting-token/

- Code that shows your error: https://github.com/vector-im/element-android/blob/main/vector/src/gplay/java/im/vector/app/gplay/features/settings/troubleshoot/TestFirebaseToken.kt#L75

**Comment by ouchadam** [comment]
out of interest, are you using a VPN or adblocker, if so could you try temporarily disabling them? they could be interrupting the connection to Google Play Services/Firebase cloud messaging

something else to check is if mobile data reacts differently to WiFi in case there's a network configuration  

and finally... have you noticed any other apps skipping notifications (gmail/other messengers etc), or is it only element?

**Comment by Autre31415** [comment]
I was able to get notifications working!

I performed a whole flurry of steps and I'm not exactly sure which one did it, but I'll list them all here in case others run into something like this:

- I wiped all networks by going into System -> Reset Options -> Reset Wi-Fi, mobile, & Bluetooth.
- I rebooted the phone in and out of safe mode (this seems to have reset some settings in various apps).
- I disconnected from Wi-Fi for an extended period of time and ran the troubleshooter while on a mobile data network and it succeeded.

After that I checked and saw the push gateway in the list and from then on notifications worked both in and out of Wi-Fi.

**Comment by ouchadam** [comment]
:tada: great to hear, thanks for letting us know!

**Comment by Dual-0** [comment]
I have the same issue with another error at the Firebase-Token step in the notification troubleshooter
```
java.util.concurrent.Execution.Exception
java.io.IOException: FIS_AUTH_ERROR
```
Phone is a Pixel too ... Pixel 6 Pro
Matrix Server 1.51
Element-Android via Playstore 1.3.15
Have already tested 1.3.16
