### ISSUE TITLE
Improve the display of privacy policy and T&C

### ISSUE THREAD

**Issue by bmarty** [vector-im/element-android#4594]
Policy and T&C are a bit specific on a Matrix client. We have the policies of the client itself, the policies of the homeserver and the policy of the identity server, if there is one configured.

Desired changes:

- [x] Replace the actions `Settings/Help & About/Copyright`, `Settings/Help & About/Terms & conditions` and `Settings/Help & About/Privacy policy` to a single items `Legals` which will open a new screen to group all the policies from Element, the policies from the homeserver and the policies from the identity server if there is one configured.

<img width="384" alt="image" src="https://user-images.githubusercontent.com/3940906/144104232-3dbd12ad-9ce4-4d5b-b8f4-f7323b4255fc.png">

- [ ] Improve the way we display identity server policy. Remove the expandability of the section.

<img width="389" alt="image" src="https://user-images.githubusercontent.com/3940906/144104303-94ee5b94-71f6-496b-998e-d19c53f4ec0f.png">

- [ ] Add the homeserver policies to the homeserver setting page `Settings/General/Homeserver`. Currently those policies are only visible when the user create an account.

<img width="390" alt="image" src="https://user-images.githubusercontent.com/3940906/144104345-6da9e905-43b3-41d4-bfcd-a3a678b46fb0.png">

**Comment by bmarty** [comment]
@deniseal I have assigned this to you, please let me know what you think about this plan ^. Thanks!

**Comment by deniseal** [comment]
@bmarty this is a great idea. Should we also involve other teams to ensure consistency across all products?

**Comment by deniseal** [comment]
@nadonomy I think it would be good to have product involved in this.

**Comment by nadonomy** [comment]
Thx for flagging. @daniellekirkwood (product) & @amshakal (design) are best positioned for this via the mobile app teams.

**Comment by bmarty** [comment]
Done

**Comment by bmarty** [comment]
(at least the first point)

**Comment by bmarty** [comment]
Will open other issues for the remaining parts
