### ISSUE TITLE
Layout View Ids: use `@id` instead of `@+id` for referenced ids

### ISSUE THREAD

**Issue by bmarty** [vector-im/element-android#4604]
Using `@id` instead of `@+id` for referenced ids is better since there will be only one declaration for each id, so code navigation will be simplified. For instance the dialogs:

<img width="998" alt="image" src="https://user-images.githubusercontent.com/3940906/144244195-fd16a329-8880-4969-8c53-09762fa3e2f3.png">

and in the code

<img width="1042" alt="image" src="https://user-images.githubusercontent.com/3940906/144244749-02aeff0b-f908-4a00-aa72-684fafefcd58.png">

will disappear and the navigation will directly goes to the view which has the searched id.

Initially reported by @Florian14 , but I do not think he has created an issue about it.

A global replacement could be done, also some rules could be added to this file: https://github.com/vector-im/element-android/blob/main/tools/check/forbidden_strings_in_layout.txt to avoid the issue to come back

**Comment by Florian14** [comment]
@bmarty Note that the `+id` should be kept at the declaration level, it should be removed only in the references (in the constraints of another view for example)

**Comment by bmarty** [comment]
Of course, I'm talking about "referenced ids" here :)

**Comment by bmarty** [comment]
In EA 1.3.10
