### ISSUE TITLE
Complete the app content / data safety form on Google Play

### ISSUE THREAD

**Issue by bmarty** [vector-im/element-android#4609]
More info can be found at https://android-developers.googleblog.com/2021/10/launching-data-safety-in-play-console.html

**Comment by vaibhavantil1** [comment]
@bmarty @deniseal 

Saw this issue while researching on Play Store Data Safety Section. I maintain a few projects that can help you:

- [Free Data Safety Generator](https://github.com/Privado-Inc/privado): CLI tool that scans your android app code to automatically detect data collected & shared
- [SDK Privacy Reports](https://github.com/Privado-Inc/SDK-Privacy-Report): OSS documentation of what data your SDK collects automatically used for filling the data safety form

I did a scan(~takes 10 mins) on this repository using [my tool](https://github.com/Privado-Inc/privado) and here are the results(images): 
- 13 Data Types
- 1 SDKs

Feel free to use the tool and give us some feedback: https://github.com/Privado-Inc/privado

Hope this was of help!
![image](https://user-images.githubusercontent.com/87804852/157166082-7d9781bb-07e6-42a5-bef6-d486c2932b82.png)
![image](https://user-images.githubusercontent.com/87804852/157166283-06e1d5f0-4db9-4fb5-9a9d-ce892311e109.png)

**Comment by bmarty** [comment]
@deniseal and I have filled the form on the PlayStore today.

Here is the exported CSV from the PlayStore: [data_safety_export.csv](https://github.com/vector-im/element-android/files/8370635/data_safety_export.csv)

Let's hope that the PlayStore will be happy with that, else it's still possible to update some answers.
