### ISSUE TITLE
Download media

### ISSUE THREAD

**Issue by Ezwen** [vector-im/element-android#461]
When clicking on a media (eg. photo), a view opens to look at it closely. However I don't see any way to download the media on the device?

**Comment by bmarty** [comment]
Work is started here: https://github.com/vector-im/riotX-android/tree/feature/download_image_video

**Comment by ofelt** [comment]
Hi there, any news on this issue ? The last (and only) commit is 4 month old.
IMHO this is a must have feature, more than emoji.
Thanks for your work !

**Comment by bmarty** [comment]
You can now save the media by long clicking on it from the timeline
