### ISSUE TITLE
Crashed every time when i try to get backup

### ISSUE THREAD

**Issue by Ranbeer600** [vector-im/element-android#4630]
### Steps to reproduce

1. When i click set to secure backup
2. Screen got black
3. After that app closed

### Outcome

I think it will make backup but i get https://paste.crdroid.net/T8ZlTB

### Your phone model

Redmi note 7 pro

### Operating system version

Android 11

### Application version and app store

1.3.7.

### Homeserver

Matrix.org

### Will you send logs?

Yes

**Comment by ouchadam** [comment]
thanks for raising! this crash has been fixed by https://github.com/vector-im/element-android/issues/4520 and the release containing the fix is currently in review by google
