### ISSUE TITLE
Change Green bar to Grey on Room list

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-android#4639]
## Problem
There's a lot of green in our app, it's startling to new users as its not always clear what green means. This is especially prevalent in the Room and DMs list when the left hand side could be straight green... 

## Solution
Change the green bar to grey

For light mode: #737D8C
For dark mode: #A9B2BC

See screenshot below

**Note** there are 2 different shades of grey on iOS. A dark one for general unread messages and a light one for notifications. Do we want to keep the grey this way around and do we want to replicate the same on Android that we have on iOS?

**Comment by amshakal** [comment]
Here is what we have on iOS currently:
![IMG_6B8FB0212B7F-1](https://user-images.githubusercontent.com/85162587/146268887-cc94f1dc-9515-46cc-8c0d-6ca769b2d392.jpeg)

Here is what we have on android currently:
![Screenshot_20211126-155450](https://user-images.githubusercontent.com/85162587/146268914-a407efd7-cdf3-4b68-8f2f-2f20f663d01a.jpeg)


Can we change the left bar colour to that on iOS?
For light mode: #737D8C
For dark mode: #A9B2BC

Note: the icon representing the number of notifications should be of the same colour as above. If it's not, I think we should change it for consistency.

**Comment by amshakal** [comment]
We have an issue for that already :)  https://github.com/vector-im/element-android/issues/4640

**Comment by daniellekirkwood** [comment]
@amshakal  there are 2 different shades of grey on iOS. A dark one for general unread messages and a light one for notifications. Do we want to keep the grey this way around and do we want to replicate the same on Android that we have on iOS?

**Comment by daniellekirkwood** [comment]
Let's keep the gray as is for now, we can re-assess in time.

**Comment by bmarty** [comment]
Fixed in 1.4.2
