### ISSUE TITLE
The notification badge jumps around

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-android#4640]
## Problem
The notification badge is not in a consistent spot in the room list, and so as rooms move around (due to activity) the badges can be disorienting too.

## Solution
Right align the notifications badge in the rooms list (and DMs) so that it's always in a consistent place on the screen. 

Here is a mockup: 

The notification badge to the right next to timestamp (8px between them). Also changed it's colour to match iOS: #737D8C on light and #A9B2BC on dark.

<img width="487" alt="Screenshot 2021-12-15 at 22 01 31" src="https://user-images.githubusercontent.com/85162587/146271892-0d2428c7-ba6c-4c1d-b908-4d4825e24c95.png">

**Comment by amshakal** [comment]
Here is a mockup. Changes:

I have moved the notification badge to the right next to timestamp (8px between them), I also changed it's colour to match iOS: #737D8C on light and #A9B2BC on dark.

<img width="487" alt="Screenshot 2021-12-15 at 22 01 31" src="https://user-images.githubusercontent.com/85162587/146271892-0d2428c7-ba6c-4c1d-b908-4d4825e24c95.png">

**Comment by daniellekirkwood** [comment]
Removed Needs Design label and Amsha assignment as questions answered and this issue is now ready to be built

**Comment by manuroe** [comment]
PR merged
