### ISSUE TITLE
Update the top bar in a room

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-android#4642]
## Problem
Rooms feel cluttered and messy and there's no 'breathing' space at the top of the screen. 

## Solution
Update the bar at the top of the room to match iOS 

<img width="539" alt="Screenshot 2021-12-15 at 21 32 16" src="https://user-images.githubusercontent.com/85162587/146268176-672dfe86-5aa1-4ac8-ad60-ff86a9970663.png">

Figma file: https://www.figma.com/file/8gIgD79bQoWdtfK3MtX59G/WTF-Moments?node-id=1%3A7117

PR should require a review from @amshakal 

Related: #3296 PR should probably fixes the 2 issues at the same time

**Comment by daniellekirkwood** [comment]
@amshakal Can you draw us a quick mockup of what the top bar should look like? I think G may already have mockups that we could attach here... It will also have to consider Threads panel access :)

**Comment by amshakal** [comment]
Consider removing room description from the header and moving it to room settings, similar to how iOS handles it. Here is a mockup for both light and dark screens. 

<img width="539" alt="Screenshot 2021-12-15 at 21 32 16" src="https://user-images.githubusercontent.com/85162587/146268176-672dfe86-5aa1-4ac8-ad60-ff86a9970663.png">

Figma file: https://www.figma.com/file/8gIgD79bQoWdtfK3MtX59G/WTF-Moments?node-id=1%3A7117

Pending/to dicuss: 
- If typing should stay up where the header is or should we move it down like iOS.

**Comment by daniellekirkwood** [comment]
Thanks, Amsha! This looks great. 

As for the typing notification, there's another issue tracking that: https://github.com/vector-im/element-android/issues/3296

**Comment by daniellekirkwood** [comment]
Have removed the Needs Design label and added Amsha's screenshots to the description. This issue is now ready to be built

**Comment by ahmed-radhouane** [comment]
Hello @daniellekirkwood  
I have some questions about this issue from what I found in the implementation. 

1 - I found multi badges that are overlapped,  related to the room image, one on top of the other 
 - An item that indicate presence state (Green / gray circle) which I think it is deprecated ? I do not see it in the application. Can you confirm this 
 
>
<img width="339" alt="Capture d’écran 2022-02-11 à 16 02 38" src="https://user-images.githubusercontent.com/73594434/153615584-3cc67cf6-53b4-4bdd-971d-4f8f601989dd.png">
 
- Second one : an icon that represent the public state, 

>
<img width="348" alt="Capture d’écran 2022-02-11 à 16 04 54" src="https://user-images.githubusercontent.com/73594434/153615930-363c259a-5ebf-4d4d-b02e-312f8013f806.png">
 
If I set the verification shield like described in the Figma file it will overlap the previous two cases, or functionally I'm not sure if different cases could coexiste at the same. 

2 - For the toolbar actions , in android we have a menu that enable users to access more actions 

>
<img width="398" alt="Capture d’écran 2022-02-11 à 16 12 36" src="https://user-images.githubusercontent.com/73594434/153617079-0d5bddfe-2a59-475b-ae02-42173f5cefaa.png">

technically I'd like to be sure that we keep this icon, (3 dots) and we reduce size between the other icons ?

**Comment by daniellekirkwood** [comment]
Thanks, @ahmed-radhouane. Great call outs. 

@gaelledel Did we run in to either of these while in the design phase?

1 - What should we do with that extra icon? Ideally, if it's available, we show it. Can you provide direction for how we do that. 

2 - We need to articulate the strategy for icons on this top bar. We will have Threads, Widgets, Audio Call, Video Call, and the "3 dots". To me, that feels like it won't fit. @gaelledel I know you did a lot of work on this, please advise us on the decision you made and the actions we should take here. 

CC: @amshakal & @janogarcia

**Comment by daniellekirkwood** [comment]
Hi @ahmed-radhouane Could you confirm the status of this issue please? It's closed on the WTF board but Open as an issue... Thanks!

**Comment by ouchadam** [comment]
this done (and merged!) as part of https://github.com/vector-im/element-android/pull/5213, will be included in the 1.4.4 release

**Comment by daniellekirkwood** [comment]
Amazing, thanks!
