### ISSUE TITLE
Add filter to room lists Android

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-android#4643]
### Problem 
Users cannot filter the People or Rooms list. This is frustrating if they're trying to find something in the list quickly.

### Solution
Add a filter input field to the top of each list view. Similar to iOS, it is only visible when the user starts scrolling down. This means that it doesn't take up any unnecessary real estate but is there if the user starts to look for something (by scrolling down)

![Screenshot 2021-12-13 12 43 47](https://user-images.githubusercontent.com/89144281/145816031-c634d5fd-3663-4678-8727-9d96420eb827.png)

### Requested reviewers
@amshakal

**Comment by bmarty** [comment]
Have you seen the magnifier icon at top right?

**Comment by daniellekirkwood** [comment]
Yes, this is supposed to be a "search" capability but is currently acting like a filter...

@bmarty Do we have a "Search" function on Android (like in iOS)?

**Comment by daniellekirkwood** [comment]
![Screenshot 2021-12-13 12 43 47](https://user-images.githubusercontent.com/89144281/145816031-c634d5fd-3663-4678-8727-9d96420eb827.png)

**Comment by bmarty** [comment]
@daniellekirkwood do you want us to add the same filter UX than on the room member list?

See below:

![room_member_filtering](https://user-images.githubusercontent.com/3940906/151875922-19e7d3bb-4e0f-4117-ae89-16dc59775ece.gif)

**Comment by daniellekirkwood** [comment]
@bmarty This is the search functionality that exists today?

I think it will act similarly to this - @amshakal will be able to confirm the behaviour. Previously we'd chatted about it acting the same as iOS

**Comment by daniellekirkwood** [comment]
On iOS we're adding the Filter icon: https://github.com/vector-im/element-ios/issues/5250

**Comment by mnaturel** [comment]
Hi @daniellekirkwood , I am currently implementing this issue and I am wondering if the search icon should remain in the app. In fact, the search screen provides the same functionalities of filtering except we are able to filter rooms and messages at the same time.

**Comment by daniellekirkwood** [comment]
Great question @mnaturel 

@amshakal as the Android search feature is a filter, do we want to remove the need for the input field and instead update the search icon to a filter icon? WDYT?

**Comment by amshakal** [comment]
Hey! Yeah, I think we should change it to filter icon so we are not confusing the user. This is a quick fix for now as the team works on improving search and IA on Android in the coming weeks/months.

**Comment by mnaturel** [comment]
@daniellekirkwood @amshakal  Thanks for your replies! I have already done the moving of the filter bar into the rooms/messages tabs. 😄  But right now, what I did is not related to scrolling behavior (it is always displayed and sticky) since it is a bit more complicated to implement. So the answer to my question might be different. What UX is best for user?

1. Having possibility to filter directly when seeing lists. So in this case we remove the search icon from top right menu.
2. Click on a button to go in a dedicated filter screen. In this case, we simply replace the search icon by a filter icon. There are no changes to the existing UX.

**Comment by mnaturel** [comment]
After more discussion, we will go the low effort changes: replacement of the search icon by a filter icon.

**Comment by amshakal** [comment]
Hey! Sorry for the back and forth. I think let's gow with replacing the search icon with filter icon to avoid confusion. This will be a low effort, high impact solution given that in user testing sessions, almost every android user tapped on the search icon to look for someone to start a chat with.

**Comment by bmarty** [comment]
https://github.com/vector-im/element-android/issues/1384 was the reason we change the icon from filter to magnifier FTR

**Comment by amshakal** [comment]
I see, I think it's misleading to have search icon when they can't technically search. :/ 
Will make sure to pass on these insights to Nique for upcoming Search + IA work.
