### ISSUE TITLE
Cannot exit scan QR code without scanning a QR code

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-android#4644]
### Problem
When a user wants to add another user by scanning the QR code, the full screen camera takeover appears. This view cannot be closed - the user _must_ scan a QR code which can be annoying if they clicked there by accident. 
The only way I found to close this view was to force quit the app.

| Current | Screens |
| --- | --- |
| ![DM](https://user-images.githubusercontent.com/89144281/145019978-9439c544-7fe0-4ec4-81aa-c3fdcdcf39ee.jpg) | ![QR code](https://user-images.githubusercontent.com/89144281/145019993-69036296-b33a-4d33-bcd5-335562f46e07.jpg) |

### Solution
Add a material.io top bar (contextual action bar) with a title and close button that takes the user back to the previous screen.

Something like this:
![Screenshot 2021-12-07 at 11 19 59](https://user-images.githubusercontent.com/89144281/145020126-cb1218f0-a9f2-4793-b97d-012677ee2495.png)

---
*Edit bmarty* TODO:
For all the titles to add you can reuse an existing string
- [ ] Add a title to the screen `CreateDirectRoomByQrCodeFragment` (see above)
- [ ] Add a title "Scan a QR code" to the screen `ScanUserCodeFragment`
- [ ] Add a title "Scan their code" to the screen `QrCodeScannerFragment`

**Comment by bmarty** [comment]
Using the regular back button should work, but it,s maybe a bit hidden on new Android system.

Can you add a screenshot please?

**Comment by daniellekirkwood** [comment]
Confirmed, the "back swipe" gesture works on Android but this action can be disabled so its best not to rely on it

**Comment by bmarty** [comment]
Thanks for the screenshots by the way, here they helped me to understand that you were not talking about QR code scanning for user verification :)

**Comment by bmarty** [comment]
In EA 1.3.13
