### ISSUE TITLE
Permanently unresponsive (no sync) after returning from background

### ISSUE THREAD

**Issue by ManDay** [vector-im/element-android#4669]
### Illustration

https://user-images.githubusercontent.com/1059827/147871105-a504390d-1365-43a0-aa2b-6ddb0953959e.mp4

### Steps to reproduce

Open a room and let the phone go to standby/display off after delay. Then unlock the phone again, thus returning to the room.

### Outcome

The "sync" spinner at the top border will appear and start spinning indefinitely.

From that point on

* no synchronisation will ever succeed
* "Clear cache" hangs indefinitely on the initial splash screen, too
* Closing Element Android has no effect

The only solution that I've found so far is using "Force Stop" on Element Android in the device settings.

### Your phone model

Cubot J5

### Operating system version

Android 9

### Application version and app store

Element 1.3.7 F-8b98c8fe

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by ManDay** [comment]
About reproducability: It happens occasionally with a high probability. I have not been able to reproduce it in small rooms, although once the problem occurs, sync fails for all rooms. On larger rooms like #matrix I would say it happens in 8 out of 10 trials.

**Comment by ManDay** [comment]
If it is of any significance: When this happens (I've joined more than 3 rooms as of recently and now it happens with a probability of >60%, even in the overview of rooms and when returning to the app - this has now forced me to use *Element Web* because *Element Android* is basically unusable), cutting the network -- which normally causes a warning about *Airplane Mode* -- does not have any effect, either: The loading indicator just keeps spinning.

**Comment by ManDay** [comment]
@SpiritCroc from Schildi (which has the same problem from the Element Codebase) has told me that a video might clarify the problem, I've added it to the opening post. You can see how after several tabbing back-and-forth Element bricks in the indefinite sync. I suspect that the stochastic doesn't follow the number of switches, because it happens with a 80% probability when I come back to Element after it has been in the background for several minutes.

**Comment by amas0** [comment]
Just wanted to jump in and say that I'm also experiencing this issue with high probability upon returning to Element from it being in the background. I've found I can fix it temporarily by closing the app completely (removing it from my background apps) and reopening it. 

I am running 1.3.12 (G-b5040) on a Galaxy S21.

**Comment by ManDay** [comment]
Occasionally, this situation occurs "invisibly", meaning there is no indication of the problem such as an infinitely spinning "loading bar". The other systems are there, such as messages being marked "delivered" (and actually delivered) but disappearing when leaving the room and no sync. The unmistakable indicator for me is that when I do "clear cache", Element hangs on the initial ("green") screen indefinitely.

Upstream, if you're just going to ignroe this bug then please close it so users don't waste effort commenting on it. Thanks.

**Comment by bmarty** [comment]
Should be fixed in Element 1.3.16 by #5162. Feel free to re-open if this is not the case.
