### ISSUE TITLE
Reactions on a message are limited to 8 distinct reactions.

### ISSUE THREAD

**Issue by bmarty** [vector-im/element-android#4674]
We apply a maximum of 8 different displayed reactions on the timeline, with no clue that more reactions have been added to the message. This is here: https://github.com/vector-im/element-android/blob/main/vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/AbsBaseMessageItem.kt#L75

All the reactions are visible in the bottom sheet after long click on the message and "View Reactions" though.

|Timeline|BottomSheet|
|-|-|
|<img width="292" alt="image" src="https://user-images.githubusercontent.com/3940906/145490684-de9cd808-a76d-49b6-b1c7-3cf35d204e3e.png">|<img width="292" alt="image" src="https://user-images.githubusercontent.com/3940906/145490715-d60e376b-113a-4538-a3c6-1f071c701ca9.png">|

Element Web has a "show all" action, which displays all the reactions on the timeline.

|Limited|Expanded|
|-|-|
|<img width="486" alt="image" src="https://user-images.githubusercontent.com/3940906/145490796-e9d2feb3-3ccc-41e4-bb10-95b6d2dd2ff9.png">|<img width="567" alt="image" src="https://user-images.githubusercontent.com/3940906/145490776-f81d331b-0fb8-4b01-b7a8-124c81141c58.png">|

On mobile we could add the "show all" action and maybe just open the bottom sheet with all the reactions.

**Comment by ganfra** [comment]
We are also supposed to add a quick action to add more reactions : https://github.com/vector-im/element-android/issues/3344

**Comment by daniellekirkwood** [comment]
Tagging Message Bubbles as we will implement this as a part of that initiative

**Comment by ganfra** [comment]
Waiting for @amshakal inputs

**Comment by daniellekirkwood** [comment]
Tagging as Needs-Design and awaiting for Figma link/direction from @amshakal  :)

**Comment by amshakal** [comment]
Hi great suggestion. I think we should add the capability for a user to expand and see all reactions by both methods - show all as well as the bottom sheet on long press, giving people the capability to go deeper into 'who-sent-what-reaction' as they wish to. 

I also think we should also as a button to add reaction as suggested in https://github.com/vector-im/element-android/issues/3344.
<img width="309" alt="Screenshot 2022-02-08 at 7 22 18 pm" src="https://user-images.githubusercontent.com/85162587/153060459-1d9fd3e1-d637-44e1-990a-e23cb1abff29.png">

<img width="426" alt="Screenshot 2022-02-08 at 7 22 39 pm" src="https://user-images.githubusercontent.com/85162587/153060484-7df325e5-3769-48e3-a273-1b4bdcc05774.png">

<img width="495" alt="Screenshot 2022-02-08 at 7 22 59 pm" src="https://user-images.githubusercontent.com/85162587/153060504-c07e2453-5b94-45cc-9c48-7eddfe844a84.png">

And lastly, we have reordered the long press quick actions to have 'add reaction' right under quick reactions. https://github.com/vector-im/element-android/issues/5005

Find attached link to [Figma](https://www.figma.com/file/zVtAKK0hzKu5JkpbzlE1pG/Message-Bubbles?node-id=2477%3A47481)

**Comment by ganfra** [comment]
Done in #5204
