### ISSUE TITLE
Element Android 1.3.9+ crashes a lot (on Android 5.1.1)

### ISSUE THREAD

**Issue by Linerly** [vector-im/element-android#4675]
### Steps to reproduce

1. Install Element Android 1.3.9+ (on Android 5.1.1, at least in my case)
2. Log in
3. Open a room with emojis, an encrypted room, or any room that has stuff loading, or make Element Android laggy somehow, or whatever

#### What did you expect?
It shouldn't crash a lot

#### What happened instead?
Crashes a lot, I submitted a few rageshakes about this a while ago

### Your phone model

Samsung Galaxy J1 ace

### Operating system version

Android 5.1.1

### Application version and app store

1.3.9 [40103091] (G-b4722)

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by bmarty** [comment]
Typing "🪱🦗🪳" in a room make the app crash on API 21.

Stack trace from rageshakes:
```
Thread: main, Exception: java.lang.IllegalArgumentException: MetricAffectingSpan can not be set to PrecomputedText.
at androidx.core.text.PrecomputedTextCompat.setSpan(PrecomputedTextCompat.java:5)
at androidx.emoji2.text.EmojiCompat$CompatInternal19.process(EmojiCompat.java:51)
at androidx.emoji2.text.EmojiCompat.process(EmojiCompat.java:11)
at androidx.emoji2.viewsintegration.EmojiInputFilter.filter(EmojiInputFilter.java:8)
at android.widget.TextView.setText(TextView.java:4743)
at android.widget.TextView.setText(TextView.java:4709)
at android.widget.TextView.setText(TextView.java:4684)
at androidx.core.widget.TextViewCompat.setPrecomputedText(TextViewCompat.java:8)
```

It can help: https://henrysgu.medium.com/how-to-resolve-metricaffectingspan-can-not-be-set-to-precomputedtext-7897026c39f

Sadly I do not have an API 21 device and the emulator is not working anymore with this version of Android on my computer, so I cannot repro and ensure that I can fix that. Will affect to somebody else.

**Comment by heftig** [comment]
I'm getting this same crash on an Android 12 (API 31) device. It's consistently reproducible.

**Comment by heftig** [comment]
The text that causes the crash "🐭️", which is u+1f42d (🐭, mouse face emoji) followed by u+fe0f (variation selector 16).

**Comment by Linerly** [comment]
Hmm,

even with 1.3.10, it's still crashing occasionally

**Comment by Galbar** [comment]
I just received a message containig `🫔`. It crashed my app. (Android 9, element 1.3.9).

Removing the emoji from the message fixed the issue.

I don't think the app should crash when it encounters unsupported/unknown emojis.

**Comment by MazeChaZer** [comment]
I manually upgraded to 1.3.11 with the released APKs, but it's still crashing just as in 1.3.9

**Comment by superboum** [comment]
Also encountering the issue with a Galaxy S7. The app crashes with:
```
java.lang.IllegalArgumentException: MetricAffectingSpan can not be removed from PrecomputedText.
```

It does that every time I want to display a specific conversation ; this conversation does not seem to have specific emojis.

I tried to :
 - upgrade the app
 - clear all the data
 - ask for a resync

without any success

**Comment by MazeChaZer** [comment]
Oh yeah, I forgot mention this, clearing the cache didn't help for me either. Downgrading to [1.3.8](https://github.com/vector-im/element-android/releases/tag/v1.3.8) with the APK from the releases page restored functionality for me in the meantime.

**Comment by Baton34** [comment]
Crash on android 6.0 and element 1.3.9 when opening chat with received emoji 🥰. After rollback to 1.3.7 - no crash but this emoji showed as crossed box.

**Comment by MazeChaZer** [comment]
[v1.3.12](https://github.com/vector-im/element-android/releases/tag/v1.3.12) fixed the issue for me :partying_face:

**Comment by ManDay** [comment]
As the problem did occur one someone else's device, I don't know the details. But a 100% crash rate (when merely viewing a room) on an older Android (6? 8?) has apparently been fixed by updating to 1.3.12. I suspect it was this bug.

**Comment by ouchadam** [comment]
the emoji issues were a real roller coaster, @Linerly are you able to confirm if 1.3.12 fixes your original issue? :crossed_fingers:

**Comment by Linerly** [comment]
Yep, fixed the issue

**Comment by ouchadam** [comment]
perfect! in that case, going to close this issue
