### ISSUE TITLE
Threads: Alignment of Deleted Message message

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-android#4680]
### Your use case

When the root message deleted the "Deleted Message" message is indented and shouldn't be

**Comment by ariskotsomitopoulos** [comment]
Below is a screenshot from the app:
<img width="517" alt="Screenshot 2021-12-13 at 23 58 53" src="https://user-images.githubusercontent.com/60798129/145895510-9e0e59e1-8d02-44ee-b09c-27bbb5e3dedb.png">

And here is a screenshot from the design:
![Screenshot 2021-12-13 at 23 59 55](https://user-images.githubusercontent.com/60798129/145895643-adddb0a6-1f52-4ac5-b899-b6c736520faf.png)

Can you please explain further the alignment issue?

**Comment by daniellekirkwood** [comment]
So on my version the trash can icon does not appear so this looks like an indent. 

We decided (in standup today) to close this issue as it cannot be reproduced. When we do a later round of testing, and if this happens again we will re-open
