### ISSUE TITLE
Threads: Missing preview in thread summary is missing if event not decrypted (incomplete threads)

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-android#4681]
### Your use case

Missing message preview in thread summary if the event is not decrypted yet.

### Solution

- Reuse the same error messages we use for decryption errors in the main timeline
- Show the summary, show the same message in the summary if needed

Related: https://github.com/vector-im/element-web/issues/19762

**Comment by daniellekirkwood** [comment]
https://github.com/vector-im/design/issues/8

**Comment by janogarcia** [comment]
@daniellekirkwood I discussed this with Aris on the last week before Christmas, but hadn't mentioned it on any specific issue.

I think we should reuse the same error messages we use for decryption errors in the main timeline. While those are not perfect, redesigning how we handle those across the app would be a major undertaking, out of the scope for Threads P0.

**Comment by daniellekirkwood** [comment]
We discussed this issue today in standup and I have updated the issue description.

Let us know if you need anything else @ariskotsomitopoulos
