### ISSUE TITLE
Threads: My Threads filter shows thread that's not mine

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-android#4683]
### Your use case

When thread list is filtered with 'My Threads', it displays a not participated thread for a second when a new message arrives in it.

1. Go to the thread list
2. Filter list by 'My Threads'
3. Get a new message from one of the not participated threads
4. List updates for a second and that thread is displayed
5. After screen refresh, it's gone again as expected

**Comment by daniellekirkwood** [comment]
@ariskotsomitopoulos Germain identified this as still being an issue in the testing last week...

**Comment by ariskotsomitopoulos** [comment]
@daniellekirkwood I cannot replicate that issue. Every test I did work fine since my fix. Maybe Germain can test again that the issue exists? And if exists maybe some steps to reproduce it

**Comment by gsouquet** [comment]
I do not have an Android phone at hand anymore. But that happened in unencrypted room as far as I remember
