### ISSUE TITLE
Threads: Open Thread Panel from Link

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-android#4684]
### Your use case

1. In timeline, copy permalink to root message
2. Link opens timeline (not thread panel)
3. In thread timeline, copy permalink to root message 
4. Link opens timeline (not thread panel)

**Comment by daniellekirkwood** [comment]
@janogarcia If there's no way to know whether the link was copied from the Thread view or the Timeline view it might be less disorienting for the user to see the Thread Root Message in the Timeline (instead of open the Thread). 

**So... Receive link > Click link > See Timeline with Thread Summary > Click Thread Summary**

If we agree that is acceptable behaviour for launch ☝️ then we can close this issue with no action needed.

**Comment by ariskotsomitopoulos** [comment]
> @janogarcia If there's no way to know whether the link was copied from the Thread view or the Timeline view it might be less disorienting for the user to see the Thread Root Message in the Timeline (instead of open the Thread).
> 
> **So... Receive link > Click link > See Timeline with Thread Summary > Click Thread Summary**
> 
> If we agree that is acceptable behaviour for launch ☝️ then we can close this issue with no action needed.

That was exactly what I thought when I implemented it in that way

**Comment by janogarcia** [comment]
@daniellekirkwood @ariskotsomitopoulos Yeah, this was discussed before for web. There isn't any much we can do here, at least until we can add Element specific params to matrix.to links (e.g. a custom source param for Element `matrix.to/.../?element-src=thread`). Feel free to close it, Danielle.

@gsouquet Do you think such client-specific params could be added in the future (properly namespaced for a specific client, and not having a negative impact on others, as it can be safely ignored)?

**Comment by gsouquet** [comment]
I don't think it's desirable that matrix.to links have Element specific parameters
But maybe we can open a discussion with the folks that are specifying matrix.to and see whether that's something we want to aim for or not

I'm not sold on this yet, but can see where you're coming from

**Comment by daniellekirkwood** [comment]
Have created a new issue to continue the extension of this... https://github.com/vector-im/element-web/issues/20249
