### ISSUE TITLE
Threads: Thread list ordering

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-android#4685]
The Thread list does not order based on last message received but the time the root message was received. This is not as designed - **the list of threads in the thread list view should be ordered by the last message received (not the time of the root message)**

---

It's also ordered by most recent at the top which is a little jarring when the user is moving from the timelines which is most recent at the bottom... Edit: This is addressed in comments

**Comment by daniellekirkwood** [comment]
From @janogarcia:

### Guidelines for event ordering in different contexts.

> Where do new threads in the thread list go? To the top or to the bottom?

To the top.

It may seem arbitrary, or unnecessarily inconsistent, but it's not.

The reason being that we optimize for scanning the information in the most relevant way for each case.

When you scan a list of standalone items (a thread list in this case, but it could your email inbox, or even your Twitter timeline…), it’s like reading the headlines on a newspaper. Information is optimized for scanning from most relevant on the top to less relevant on the bottom.

In the Thread List, relevant equals recent (it could mean a mix of freshness and weighing other signals, like mention count, new comments count or if that thread is followed, but that doesn’t change the approach), that’s why those are moved to the top.

On the other hand, when you read a list that it’s made of parts/slices of the same item (the room or thread timeline, but it could be an email thread, or a Twitter thread), it’s like reading a specific news piece (or a book) instead of scanning the headlines. You read every line of the story in order, from top to bottom.

In the Room and Thread detail timelines, all the messages are, in some way, part of a same story, and thus needs to be read from top to bottom.

> My assumption is that we should follow the same ordering as the file panel or the notification panel

Those panels should be redesigned and reverse their ordering.

Edit: There's plenty of evidence supporting what I explained above (Slack, Discord, Mattermost, Rocket.chat, Twist, Gmail... I could go on and on).

**Comment by daniellekirkwood** [comment]
@janogarcia can you confirm the description here is accruate. Once you have, feel free to unassign yourself.

**Comment by janogarcia** [comment]
@daniellekirkwood Yeah, that's correct! The ordering for the thread list items should be by latest reply, newest on the top, as described on the notes I shared above. 👍
