### ISSUE TITLE
Messages doesn't download

### ISSUE THREAD

**Issue by asakura42** [vector-im/element-android#4692]
### Steps to reproduce

Open app and wait for messages...

#### What did you expect?
Fast message loading as it should

#### What happened instead?
No message loaded, I wait and wait but nothing. Simetimes messages update, but in 60% of times loading stucks and green bar at top moves and moves and moves.... Desktop apps works ok btw.

### Will you send logs?

Yes

**Comment by ouchadam** [comment]
thanks for raising, the more reports we get the easier it'll be to track down, this sounds a lot like https://github.com/vector-im/element-android/issues/4554 so I'm going close in favour of having 1 issue open
