### ISSUE TITLE
Logout impossible when the homeserver was shut down

### ISSUE THREAD

**Issue by forenta** [vector-im/element-android#4694]
### Steps to reproduce

1. Where are you starting? What can you see?
Element 1.3.9 from F-Droid, Nokia 7 Plus. Start the app, see the old conversations. The homeserver I used before [has been shutdown without announcement before](https://libreddit.silkky.cloud/r/PrivacyGuides/comments/qw03w8/deletion_of_privacytools_accounts_matrix_mastodon/hl1n1mv/?context=3) (privacytools.io - they really suck, please do not support them)

2. What do you click?
Burger-button > Sign out > Don't wanna backup > Signoff (confirmation)
![grafik](https://user-images.githubusercontent.com/2451238/145716821-0dfdf11c-9046-4374-b476-5dc1ac761c18.png)

3. Result
![grafik](https://user-images.githubusercontent.com/2451238/145716863-50123cc0-ca4c-4926-add4-de7aa0017ef1.png)

'Cancel' takes me back to the old conversations, 'Retry' keeps me at the error message.

#### What did you expect?
Get back to the login/sign-up screen

#### What happened instead?
Prevent from getting there ;)

### Your phone model

Nokia 7 Plus

### Operating system version

Android 10

### Application version and app store

1.39 from F-Droid

### Homeserver

chat.privacytools.io

### Will you send logs?

No

**Comment by ouchadam** [comment]
thanks for raising :+1:  I'm going to close this and centralise the issue to #4855
