### ISSUE TITLE
Search messages

### ISSUE THREAD

**Issue by bmarty** [vector-im/element-android#47]
In this room and in all rooms

**Comment by vc7ee** [comment]
I'm constantly trying to search riot like I search discord.
from:@user:server mentions:@user:server has:link has:file has: embed has: video has:image has:sound before:date after:date during:date in:#room
Search should also be searching for anything (wildtag, regex `.+`).

**Comment by progserega** [comment]
Do the search will be work in encrypted rooms?

**Comment by ildar** [comment]
Version 1.0 is out already. Will this regression be eliminated?

**Comment by niquewoodhouse** [comment]
Some quick design options [here](https://www.figma.com/file/uzGAWvJ8KyHAtILYbC8Y8o/Timeline?node-id=27%3A143)

**Comment by bmarty** [comment]
Superseed by #2110 and other related issues
