### ISSUE TITLE
Polls: Cannot end a poll in not encrypted rooms

### ISSUE THREAD

**Issue by ariskotsomitopoulos** [vector-im/element-android#4723]
### Steps to reproduce

Users can start a poll in NOT encrypted rooms, however they cannot end the poll without the appropriate power level. So we should either block user from starting a poll without the appropriate power level, or allow him to close it even with a lower one

### Outcome

Users should either not be able to start a poll without the appropriate power level, or should be allowed to close it even with a lower power level one if they have started it.

### Will you send logs?

No

**Comment by mnaturel** [comment]
Closing the issue as we implemented the second suggested solution:  

> close it even with a lower power level one if they have started it.
