### ISSUE TITLE
Element Android crashing when entering (viewing) rooms where a specific emoji was sent

### ISSUE THREAD

**Issue by DATKTV** [vector-im/element-android#4725]
### Steps to reproduce

1. send the emoji `:face_with_spiral_eyes:` from element desktop client to any room
2. try to open the same room in Element Android
3. crash

#### What did you expect?
I expected to read messages in this room
#### What happened instead?
The app crashed. Every time I tried to open the room
In some rooms, I can't even join after I deleted the emoji with the desktop client

### Your phone model

OnePlus 9

### Operating system version

Android 11 (OxygenOS 11.2.9.9.LE25BA)

### Will you send logs?

No

**Comment by bmarty** [comment]
Yes, thanks for reporting. This issue is fixed in Element Android 1.3.10 which is currently in review by Google and being built for F-Droid.
