### ISSUE TITLE
Rooms marked as semi unread when being invited to a room (and more cases)

### ISSUE THREAD

**Issue by chagai95** [vector-im/element-android#4749]
### Steps to reproduce

1.  someone invites me to a room.
2. I accept the room invite on web
3. I see this weird semi unread mark on Android:
![image](https://user-images.githubusercontent.com/31655082/146531497-3268cc08-2fd0-4a34-af48-e59af9f11afb.png)

#### What did you expect?
Not to have that.

Here is a video explaining this and showing some other weird behavior:
https://aarenet-my.sharepoint.com/:v:/p/chagai_friedlander/ETzk6F5vYYVPlcjyT10219QB9KsJzRDO-dW148wkCGa0Qw?e=I3OGKq

### Your phone model

Xiaomi Mi 11 lite

### Operating system version

![IMG_20211217_113352](https://user-images.githubusercontent.com/31655082/146531342-34e5b1a7-2c1e-40e5-a4c7-c8370b883fba.jpg)

### Application version and app store

1.3.9

### Homeserver

Matrix.org

### Will you send logs?

No

**Comment by langleyd** [comment]
Looks like we are the indicator is a bit broken in cases where there were no messages in a room. Fix incoming.

**Comment by bmarty** [comment]
Fixed in EA 1.3.13
