### ISSUE TITLE
Sidebar too large in horizontal orientation or tablets

### ISSUE THREAD

**Issue by hpdeifel** [vector-im/element-android#475]
See here:

![Screenshot_20190810-132219](https://user-images.githubusercontent.com/77743/62821331-4a147a80-bb73-11e9-9124-f9e132d579f9.png)

Especially on tablets, the sidebar can be absurdly large when fully expanded.

**Comment by sindastra** [comment]
I can confirm this also happens on my Samsung Galaxy Tab S5e (16:9 screen in landscape) with Element 1.0.0 [40100000] (F-fca669ff) from F-Droid. The Sidebar almost covers the entire screen.

Perhaps related issue #1843
