### ISSUE TITLE
Emoji inconsistencies in composer

### ISSUE THREAD

**Issue by ouchadam** [vector-im/element-android#4756]
### Steps to reproduce

1. Add a new emoji such as :face_exhaling: via the keyboard
2. Notice the unicode components are displayed
3. Submitting the message then shows the correct emoji again 

#### What did you expect?
The see the correct emoji :face_exhaling:

#### What happened instead?
Got :open_mouth: :dash: 

![Screenshot_20211217_094434](https://user-images.githubusercontent.com/1848238/146576484-b93f7c43-cd58-47e3-9a15-086ab2556a38.png)

### Your phone model

Pocofone f1

### Operating system version

android 10 (MIUI 12.0.3.0)

### Application version and app store

1.3.10

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by bmarty** [comment]
Fixed in EA 1.3.13
