### ISSUE TITLE
Voice call button disappears when there's more than 2 people in the room.

### ISSUE THREAD

**Issue by kreaninw** [vector-im/element-android#4762]
### Steps to reproduce

1. Add/invite someone into the direct message room.
2. See the right corner, the voice call button will disappear as shown in the screenshot below:

![image790](https://user-images.githubusercontent.com/1403194/146660353-ed1fa578-23cf-4b3a-8dca-1f72c42a2c34.png)

#### What did you expect?
I expect to see the **voice call button** as it's a very important feature. Most of the time, I and my friends only do voice call conferences. We're trying to migrate from Line (from Naver) but we can't as this is the only thing that prevents us from doing so.

In the same room, when I use Element on Windows 10, there's a voice call button as shown in the screenshot below:

![image8349](https://user-images.githubusercontent.com/1403194/146660565-5f32dc29-0871-4383-9820-c8c52fe3b43c.png)

I expect this to be available on Android too.

#### What happened instead?

There's no voice call button in the room with more than 2 people, thus making it impossible to do a voice call conference. The users have to make a video call conference first, then leak an unintended video of themself before they can turn off their cameras. 

### Your phone model

Lenovo Tab P11, TB-J606L

### Operating system version

Android 11

### Application version and app store

Element version: 1.3.9 [40103092] (G-b4722), olm version: 3.2.4, from Play Store.

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by ouchadam** [comment]
it looks like this was done on purpose when a room contains more than 2 people [code ref](https://github.com/vector-im/element-android/blob/develop/vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailViewState.kt#L78)https://github.com/vector-im/element-android/pull/3863

it seems that we have different behaviour across the platforms, web always shows the option, iOS doesn't show a voice call at all (haven't confirmed this) and android hides the option when more than 2 people are in a room.

cc @daniellekirkwood

**Comment by daniellekirkwood** [comment]
Thanks @ouchadam 

@gaelledel or @jakewb-b Do either of you have insight into why these decisions were made? Can you give guidance on how and why which buttons should show up so that we can make sure it's the same across platforms? Thanks!

**Comment by gaelledel** [comment]
@daniellekirkwood  this is not a normal behaviour for a DM based group chat (using native VoIP system). We should have both voice and video calls displayed. 
For "group rooms" e.g: the large Matrix community room, we currently use Jitsi and so only conference calls should be displayed with a video button. The conference calls are controlled by admins with permissions.
@ganfra FYI

**Comment by centralnui** [comment]
It's 2025 and the issue persists. We have to install Coturn, but when it's a 3+ members room, Jitsu rules the voice calls anyway, why?

**Comment by Cheu3172** [comment]
Wish we weren't forced to use conference calls, especially when voice exist and does the job perfectly fine with Coturn.
