### ISSUE TITLE
Elements crash when i use the conversation shortcuts

### ISSUE THREAD

**Issue by Arthurdevid** [vector-im/element-android#4763]
### Steps to reproduce

1. i start the app 
2. I use my 4G but not on my wifi where I have access to the server locally and when the elements app is closed on my laptop
3. I create a conversation shortcut on my homepage
4. i try to use the sortcut that i made 

#### What did you expect?
Juste use the conversation shortcut
#### What happened instead?
the app keep crashing

### Your phone model

Samsung A70

### Operating system version

Android 11 One UI 3.1

### Application version and app store

1.3.9

### Homeserver

classic installation of matrix on my home server on docker

### Will you send logs?

Yes

**Comment by ouchadam** [comment]
this sounds like it could be the emoji crashes introduced in 1.3.9, does 1.3.12 fix the issue for you?

**Comment by Arthurdevid** [comment]
Yes 1.3.12 fix the issue

**Comment by Arthurdevid** [comment]
Thanks

**Comment by ouchadam** [comment]
thanks for updating :100:
