### ISSUE TITLE
Element keeps crashing when sending emoji to a room

### ISSUE THREAD

**Issue by hwittenborn** [vector-im/element-android#4779]
Whenever I send an emoji to a room, Element keeps crashing for some reason.

It also appears to have potentially crashed in other circumstances, but Element has also crashed at least 10 times in the last day or so.

I also sent in quite a few crash reports from the app if that helps, they should be from @hunter:hunterwittenborn.com if they get tagged with a username.

### Version Info
Version: 1.3.11 [40103111] (G-b5034)
SDK: 1.3.11 (cab28ffe)

**Comment by hwittenborn** [comment]
Not sure how related it is, but the emoji pack used in Element's emoji picker appears to be different that that seen in sent messages.

**Comment by ouchadam** [comment]
thanks for reporting, from your crash reports I can confirm the issue you're seeing is fixed with 1.3.12 (which is now available on the playstore)

**Comment by hwittenborn** [comment]
Can confirm everything works now! :)
