### ISSUE TITLE
Poll system notifications on Android are not user friendly

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-android#4780]
### Steps to reproduce

1. Have a poll in a room with noisy notifications
2. Receive system notification when someone votes

#### What did you expect?
A message saying "X voted in poll Y" or something similar

#### What happened instead?

![Screenshot_20211220-171830](https://user-images.githubusercontent.com/51663/146812603-668c618a-792f-421b-b542-e7927b21520f.png)

### Application version and app store

1.3.10

### Will you send logs?

No

**Comment by ouchadam** [comment]
defect or enhancement? I'd argue for enhancement if this wasn't part of the originally spec'd work
