### ISSUE TITLE
Communities not listed

### ISSUE THREAD

**Issue by maemunman** [vector-im/element-android#479]
I'm on the current RiotX dbg (gplay build, but same problem on the fdroid build) from kr0mbel's fdroid repo.  My communities don't show up in riotx.  I was formerly a part of a community that did show up in riotx, but I've since left that community.  At least that goes to show communities are working to some extent for me, but not my own communities.  See riot and riotx screenshots.

![Screenshot_2019-08-11-13-30-06-495_im vector riotx debug](https://user-images.githubusercontent.com/32847759/62839263-bdce8a00-bc3c-11e9-861e-a3ee86bd8fab.png)
![Screenshot_2019-08-11-13-29-56-028_im vector app](https://user-images.githubusercontent.com/32847759/62839264-bdce8a00-bc3c-11e9-9426-c1e0b20a2667.png)

Fwiw I am the admin of all three of these groups, and the other group that did show up when I was a member, I was not the admin of that one.  So maybe riotx can't list communities that the user is admin over, but only ones the user is a member of.

**Comment by RodrigoTjader** [comment]
I'm on 0.6.0 and am seeing this same problem. I never saw any communites on 0.5.0 either.

I am a member of 6 communities and owner of 5 of them, but I don't see any of them in RiotX.

Are there any logs I could collect to help find the problem?

**Comment by RodrigoTjader** [comment]
Now the community which I am not the owner is appearing on the list, but the ones I own still do not appear. I had joined this community shortly before my previous message.

**Comment by barudaret** [comment]
I'd like to reaffirm that indeed, the communities which I am not owner of appear in the list and those which I am owner of are missing.

**Comment by TheDiscordian** [comment]
Was this fixed/added at some point? I'm on the Google Play build 0.21.0, and I don't have this issue. I'm the admin of 3 communities, and only a member of 2. I see all 5 communities. I didn't experience this issue on the previous 2 updates either.

**Comment by barudaret** [comment]
@TheDiscordian It's much better now, but I'm in 9 groups right now and only 6 appear in RiotX, so we're not fully there yet

**Comment by LookitheFirst** [comment]
I also have this problem. A community I created in element-web does not show up at all on RiotX/Element

**Comment by duncanturk** [comment]
Can confirm that still happens on 1.0.2 gplay version.
Did not have this issue on RiotX (same account, but communities were shown).

**Comment by barudaret** [comment]
Same.  Since the switch from RiotX to Riot.imX, not a single community is showing up.  When it was RiotX, most but not all communities were there.  Now it's none.  Idk what changed.

**Comment by heyakyra** [comment]
Joining Community #72 seems related

**Comment by duncanturk** [comment]
I can see my communities again. Don't know what changed. 1.0.4 gplay

**Comment by MexHigh** [comment]
Still have this problem (Element 1.0.8, gplay). Any progress on that? We really need this feature.

**Comment by JuniorJPDJ** [comment]
Element desktop:
![Screenshot_20201209_100013](https://user-images.githubusercontent.com/7334549/101608013-8412bc80-3a05-11eb-9f9a-aa8ff8fbd183.png)
Element Android:
![image](https://user-images.githubusercontent.com/7334549/101608081-9987e680-3a05-11eb-8b26-14e7fde9adee.png)

Latest version of both :/

**Comment by heyakyra** [comment]
Same here, there is an effort to rebuild "communities" as "spaces": #2495 

Now there's an error when loading a groups link from matrix.to, but it would be nice to fix that.

**Comment by bmarty** [comment]
Community are listed in the left drawer from the room list. Still displayed if any, even if this is currently been replaced by Spaces.
I close the issue for now, we will probably remove community in a near future.
