### ISSUE TITLE
Url preview

### ISSUE THREAD

**Issue by bmarty** [vector-im/element-android#481]
Display URL preview in the timeline, as other Riot clients does (except - sadly - Riot iOS)

Do not perform URL previewing in e2e rooms, as it leaks the URL to the HS

**EDIT**: Update of description:

We need design on how to display URL previews in the timeline.
We have several states to consider: loading/error/loaded. It should be good to avoid blink in the timeline, so all the states should take the same space.
Several preview can be displayed in a row if the message contains several URLs.
Also it is possible to close the preview. On Riot-Android, it had the effect of storing the url value, to avoid display the url preview anymore for that URL. On Element Web it seems that this is not the current behavior, it just closes the preview.

The current data we get for a preview:
- The url itself
- An image URI (optional)
- A title
- A short description

As suggested by @dhrunia, we could consider displaying URL preview in e2e room, but the decision has to be taken globally for the Element product.

Ref: https://matrix.org/docs/spec/client_server/r0.6.1#get-matrix-media-r0-preview-url

Element URL display (FTR):

<img width="848" alt="image" src="https://user-images.githubusercontent.com/3940906/90418652-afb81280-e0b5-11ea-87a5-df2561b99a0d.png">

Edit:
Design is ready: https://www.figma.com/file/tnv1s5KUVK38Byt54gs7GM/Timeline-URL-previews?node-id=0%3A1 , proposal 2 is mature (we think :) but feedback welcome via Figma comments

**Comment by KaenDagger** [comment]
I would like to work on this issue

**Comment by bmarty** [comment]
Ok, thanks

**Comment by ptman** [comment]
@KaenDagger did you get far?

**Comment by dhrunia** [comment]
> Do not perform URL previewing in e2e rooms, as it leaks the URL to the HS
Most self hosted users wouldn't mind if URL is leaked to HS. Maybe let the users decide by providing an option to enable URL previews in encrypted rooms as well?

**Comment by 532910** [comment]
It'd be nice to have a toggle for default preference for encrypted rooms.

**Comment by ptman** [comment]
is minivector from f-droid currently the only android client with url previews?

**Comment by nadonomy** [comment]
@niquewoodhouse prepped a simple proposal for visualising URL previews here: https://www.figma.com/file/tnv1s5KUVK38Byt54gs7GM/Timeline-URL-previews?node-id=8%3A122

**Comment by Alvazz** [comment]
@bmarty what is this view? it is timeline?

**Comment by Alvazz** [comment]
@bmarty Has the current timeline function been released? Where to click in

**Comment by 532910** [comment]
Doesn't work for me.

**Comment by bmarty** [comment]
Available in Element Android 1.0.12 and up

**Comment by 532910** [comment]
Yep, 1.0.12 is installed.

**Comment by bmarty** [comment]
@532910 could you open a dedicated issue to track your problem please? Thanks
