### ISSUE TITLE
Add support for Android Desktop Mode

### ISSUE THREAD

**Issue by kreaninw** [vector-im/element-android#4811]
#### What would you like to do?
I would like to use Element with Android Desktop Mode features. For instance, an ability to maximized the app's window as shown in the screen recording below:

https://user-images.githubusercontent.com/1403194/147378034-15d7783a-6f54-4a85-b0fe-e6f51be0acb1.mp4

#### Why would you like to do it?
The desktop mode on Android devices was introduced since Android 10 as a developer option. However, most, if not all, Android 11 devices now make this mode available on differences names. This mode is called Productivity Mode by Lenovo.

![147377234-d9022ace-45f2-48ba-ae33-0dfba5eb56c7](https://user-images.githubusercontent.com/1403194/147378060-dad04e7e-b57d-4e3f-af1b-4af89e08e044.jpeg)

My tablet has 11 inches display, so I prefer to use the app like I would on my laptop PC.

#### How would you like to achieve it?

I would like to have Element app works natively with Android Desktop Mode. 

### Have you considered any alternatives?

There's no alternative way.

**Comment by ouchadam** [comment]
This might be OEM specific, for example I'm able to start a samsung dex desktop session and expand the Element app.

How does the app currently behave in desktop mode?

**Comment by kreaninw** [comment]
> This might be OEM specific, for example I'm able to start a samsung dex desktop session and expand the Element app.
> 
> How does the app currently behave in desktop mode?

The maximize button of the app's window is greyed out as shown in the screenshot below:

![Screenshot_2022-01-13-14-12-07-801](https://user-images.githubusercontent.com/1403194/149377434-550b7175-5712-4ee3-ae62-8f045dc52ee1.jpeg)

I'm not sure whether this is an OEM specific issue. However, this mode works fine in many apps, both Google and non-Google apps. For example, Chrome, Facebook, Facebook Messenger, WhatsApp, LINE.

**Comment by ouchadam** [comment]
it might be a simple case of enabling https://developer.android.com/guide/topics/manifest/activity-element#resizeableActivity 

I'll raise a PR :crossed_fingers:

**Comment by ouchadam** [comment]
our CI has generated debug builds with the above flag enabled https://buildkite.com/matrix-dot-org/element-android/builds/5504#21f7023c-b978-4850-b0ad-e9783eeafc6c in case you would like to test
