### ISSUE TITLE
F-Droid build failing

### ISSUE THREAD

**Issue by programmerjake** [vector-im/element-android#4828]
The version on F-Droid is stuck at 1.3.9, apparently because the builds for later versions are failing:
https://monitor.f-droid.org/builds/log/im.vector.app/40103120#site-footer

**Comment by konomikitten** [comment]
Is this being looked at? The Element build on F-Droid hasn't been updated for a month now and is 5 versions behind. Considering the nasty emoji crashing bugs on older versions of android this is getting a bit annoying.

**Comment by konomikitten** [comment]
Builds are flowing to F-Droid again can someone close this thanks.
