### ISSUE TITLE
dev tools is blank

### ISSUE THREAD

**Issue by programmerjake** [vector-im/element-android#4829]
### Steps to reproduce

1. Where are you starting? What can you see?
in any chat room
2. What do you click?
three dots in upper right corner, then dev tools in the menu that pops down.
3. observe a blank screen

#### What did you expect?
some stuff on the screen
#### What happened instead?
it's blank

![Screenshot_20211231-120624](https://user-images.githubusercontent.com/4584340/147837828-a6ff6f64-a385-4ac1-bfbf-63a326c0dbd2.png)

### Your phone model

Pixel 4a

### Operating system version

Android 11.0

### Application version and app store

1.3.9 [40103090] (F-581c557f), olm 3.2.4 f-droid

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by bmarty** [comment]
Fixed in 1.3.12, F-Droid version is coming in a few days.
