### ISSUE TITLE
Tea emoji looks different in computer, timeline and emoji picker

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-android#4836]
I feel that emojis should be displayed the same way everywhere.

To reproduce,
1. Open emoji picker from the keyboard and see tall cup for the tea.
2. Click on the emoji so it's inserted into the composer and see short cup
3. Send the message and see tall cup in the timeline

![Screenshot_20220103-110916.png](https://user-images.githubusercontent.com/51663/147924882-1f9e89f1-819a-4f80-8ef8-14c69e0b3899.png)

**Comment by ouchadam** [comment]
this is fixed by https://github.com/vector-im/element-android/pull/4758 in 1.3.13
