### ISSUE TITLE
:face_vomiting: crashes Element but only on a specific version of Android

### ISSUE THREAD

**Issue by konomikitten** [vector-im/element-android#4845]
### Steps to reproduce

1. Send :face_vomiting: emoji to my client
2. Element crashes

Note this crash only occurs on my phone running Android 7.1.2 it does not occur on Android 10 but I can't update my phone due to end of support. Sending the same emoji on Signal on the same Android 7.1.2 phone does not cause Signal to crash so this seems to be Element specific.

### Your phone model

Asus Zenfone Selfie ZD551KL

### Operating system version

Android 7.1.2

### Application version and app store

Element version 1.3.9 olm version 3.2.4 from F-Droid

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by ouchadam** [comment]
we've unfortunately been hit by an assortment of emoji issues recently, 1.3.12 fixes 99% of them, we're in the process of releasing this version to f-droid

**Comment by Anglodel** [comment]
Can confirm it happens on a 5.1.1 device. All emoji which aren’t supported by the device, even if they were correctly displayed in precedent versions, crash the app (either completely or restart it and goes back to the home menu).

Device & app infos:

- Huawei Ascend Y5 - Y560-L01
- Android 5.1.1
- Element 1.3.9 [401003090] (F-581c557f)
- SDK Matrix Version: 1.3.9 (581c557f) via F-Droid
- olm version: 3.2.4

**Comment by ErikPrantare** [comment]
> we've unfortunately been hit by an assortment of emoji issues recently, 1.3.12 fixes 99% of them, we're in the process of releasing this version to f-droid

Any updates on this?

**Comment by konomikitten** [comment]
I can confirm that 1.3.14 just landed on F-Droid and I no longer crash when this emoji is used so closing this report, thanks for fixing this!
