### ISSUE TITLE
Can't sign out with error: This is not a valid Matrix server address

### ISSUE THREAD

**Issue by MurzNN** [vector-im/element-android#4855]
### Steps to reproduce

I can't sign out from account in Element-android with error: This is not a valid Matrix server address. 
Pressing a "Retry" button don't help, pressing "Cancel" cancels the signing out process.

I've also submitted ragshake with logs. 

So, if there is a real problem with server, why I can't simply logout from it, even with broken connection?

### Operating system version

Android 10

### Application version and app store

1.3.12 [40103122] (G-b5040)

### Homeserver

Private HS 

### Will you send logs?

Yes

**Comment by MurzNN** [comment]
![Screenshot_20220105-090156](https://user-images.githubusercontent.com/336662/148170457-12aaa889-a82f-4f8c-b9e5-93ccdf3731b3.jpg)

**Comment by HarHarLinks** [comment]
I'm running into the very same issue: the homeserver I am logged into has disappeared, now I can't log out.

**Comment by ouchadam** [comment]
this error occurs when the app receives a 404 when trying to interact with a homeserver, we could simply ignore the error on sign out but it might be worth some messaging to display that the upstream account will not be invalided.

I could imagine a dialog containing "We can't contact your homesever to sign you out" -> "cancel, retry, sign out anyway"

added _needs product_ label to decide we if need extra messaging

**Comment by HarHarLinks** [comment]
Imo as an admin/user, having your proposed extra dialogue makes sense. It should also offer to export local meg/olm keys, but not try to setup online backup.

**Comment by HarHarLinks** [comment]
### Steps to reproduce

1. shut down your server
2. try to log out

### Outcome

#### What did you expect?
log out without deleting the session from server

#### What happened instead?
can't log out.

additionally, it keeps insisting I enable my key backup, even though server isn't reachable. also, I already have a key backup set up to make it even more confusing.
