### ISSUE TITLE
Remove "X kicked X" terminology when removing people from a room

### ISSUE THREAD

**Issue by gaelledel** [vector-im/element-android#4865]
#### What would you like to do?
To remove the wording "X kicked X" when someone is removed from a room and replace with "X removed X"

#### Why would you like to do it?
Because it is more acceptable terminology

---
*EDIT bmarty*
Ok, confirmed internally:
- replace all instance of "kick" and their variations to "remove" and their variations in the English wording. Translation will updated later following the regular Weblate process. No need to create new strings.
- add the slash command `/remove` but keep the existing `/kick` for now. They will have the same effect.

**Comment by bmarty** [comment]
"removed" is a bit strange to me, maybe "excluded"?
Anyway we will need a confirmation from the product team (@daniellekirkwood ) to do this change, also it will have to be done on all the Element apps.

**Comment by daniellekirkwood** [comment]
I agree. Is this message specifically for the event in the timeline? Could you provide a screenshot, @gaelledel?

Also note that "kicked" is the terminology we use across the product for this action. It would be strange to kick a user from a room and then not see that confirmation in the timeline...

Benoit, "Excluded" has different meaning in English - for example, when children are excluded from school, they are not allowed back. It's also a more emotive term - to feel excluded. When a user is Kicked from a Room, they could be invited back in?

**Comment by gaelledel** [comment]
Using the term Removed is absolutely fine and I had a discussion with Matthew about it a long time ago so please let's just go with it. No point debating on this subject any further as it was discussed again and again... This is now done on the web just waiting for this to be done on mobile.
https://github.com/matrix-org/matrix-react-sdk/pull/7469#pullrequestreview-845465212

**Comment by bmarty** [comment]
A kicked user can freely join again a public room. A banned user cannot.

**Comment by bmarty** [comment]
Will be in Element 1.3.16

**Comment by t3chguy** [comment]
I was under the impression this needed a synchronised release between all the platforms.

**Comment by t3chguy** [comment]
Well its been ready on Web pending a synced release so that users aren't confused seeing Kick on one platform and Remove on another

**Comment by bmarty** [comment]
Note that Element 1.3.16 release candidate is scheduled to be done January 25th and the next Monday on Prod

**Comment by daniellekirkwood** [comment]
> Well its been ready on Web pending a synced release so that users aren't confused seeing Kick on one platform and Remove on another

Can you send me the issue, let's go ahead and push it thru on web too

**Comment by t3chguy** [comment]
@daniellekirkwood https://github.com/matrix-org/matrix-react-sdk/pull/7469

**Comment by SPiRiT369** [comment]
I like this change and never understood why the brutal "kick" word was chosen back in the IRC days. Looking forward for replacing "ban" with "block"! 🤗
