### ISSUE TITLE
Bulk User Moderation - Ban/Uninvite

### ISSUE THREAD

**Issue by BanjoFox** [vector-im/element-android#4879]
#### What would you like to do?
One of the invite-only rooms I'm in was hit by a racist spammer.  They created several thousand invites that we now have to manually clean up.

#### Why would you like to do it?
Because the name contains offensive language, and I want to make sure that the offending bot accounts/users can't get back in easilly.

#### How would you like to achieve it?
Having a "remove all" or a way to select multiple users at once to ban/disinvite would greatly help.
Additionally it would be great to have an API call to manage users.

### Have you considered any alternatives?

I looked for an API call.  
There is also no apparent options in the Web or Desktop versions for "bulk user management".

**Comment by ouchadam** [comment]
@daniellekirkwood is this level of moderation via the mobile apps something we're looking to support? 
I have a feeling this might out of scope for the android app and better suited to a dedicated moderation tool

**Comment by BanjoFox** [comment]
I wouldn't mind it being on a separate app, desktop-only, or web-only.
Having better/more efficient moderation tools would actually alleviate issues that a lot of my friends/fellow admins would greatly appreciate.

**Comment by jmartinesp** [comment]
I'm sorry, but development of new features in Element Android has been stopped while we focus our efforts in the new version of the app.
