### ISSUE TITLE
Add a new `cryptography info` screen accessible from message context menu.

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/element-android#4891]
UISIS - milestone 1 ( Help users struck be UISIs)

See https://github.com/vector-im/element-meta/issues/76

It is yet to be defined if this screen will be accessible behind the developer mode flag or not.

The goal is to offer a way for users to recover from an unable to decrypt error, and ease investigations of errors by displaying in app the sharing status of a megolm session.

**Comment by pmaier1** [comment]
https://github.com/vector-im/element-meta/issues/249#issuecomment-1673338527
