### ISSUE TITLE
Enable Vietnamese translation

### ISSUE THREAD

**Issue by benparsons** [vector-im/element-android#4894]
### Your use case

Customer has added Vietnamese translations to weblate for element-android. I would like to enable them in the app.

#### What would you like to do?

Show Vietnamese language option in app

#### Why would you like to do it?

So Vietnamese speakers can see their language

#### How would you like to achieve it?

Enable it in the app

**Comment by ouchadam** [comment]
were pulled in by https://github.com/vector-im/element-android/pull/4843 and are available in 1.3.14
