### ISSUE TITLE
Update Files component Android

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-android#4897]
### Your use case

Update the "File" message type component to be the same as Web

related to: https://github.com/vector-im/element-ios/issues/5372

| Android today | Web today |
|----|----|
| ![Polls Android Bubbles](https://user-images.githubusercontent.com/89144281/148818463-0593ebac-189e-4916-b82d-124f966892b0.png) | <img width="292" alt="Screenshot 2022-01-10 at 18 21 42" src="https://user-images.githubusercontent.com/89144281/148818495-d9edf8a6-4653-4636-a318-2946fd2134ca.png"> |

This was raised as part of the Bubbles work, and will be completed inside of the Bubbles project but should apply to all Appearance layouts

**Comment by amshakal** [comment]
Hi yes, I think the plan is to make them look similar on all platforms. Link to figma for all media components: https://www.figma.com/file/X4XTH9iS2KGJ2wFKDqkyed/Compound?node-id=2039%3A26421

Link for how they look in bubbles layout with timestamp inside the component: https://www.figma.com/file/zVtAKK0hzKu5JkpbzlE1pG/Message-Bubbles?node-id=1919%3A41337

**Comment by ganfra** [comment]
On Android it handles the case where it's already downloaded to avoid doing it again. So there is different icons following the state. But will update so we have the pill and the rounded background.

**Comment by daniellekirkwood** [comment]
@ganfra What's the status of this issue? It's marked a couple of different ways in the different project boards and I know you're rolling off bubbles this sprint...
