### ISSUE TITLE
Standardise casing of homeserver, identity server

### ISSUE THREAD

**Issue by jryans** [vector-im/element-android#491]
Cloned from https://github.com/vector-im/riot-web/issues/10569. (I have not filed this for riot-android, as I thought it would be easier to handle this by keeping it in mind for any new strings when added to RiotX, but whatever seems best.)

These terms should be spelled "homeserver" and "identity server" in all user visible text.

Other variants such as:

* Identity Server
* ID Server
* Home Server

should all replaced.

(Of course, if it's the first word in a sentence, the first letter should be capitalised.)

**Comment by KaenDagger** [comment]
where are all variants used? If its usedin RiotX. I would like to replace it.

**Comment by bmarty** [comment]
After syncing with @nadonomy today, I heard that we now want to use "server" instead of "homeserver".
CC @ara4n
