### ISSUE TITLE
Threads: MVP behind Labs flag

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-android#4916]
### Your use case

The primary issue where we're tracking the requirements for this issue is here: vector-im/internal-planning#192

**Comment by daniellekirkwood** [comment]
@ariskotsomitopoulos Threads is behind Labs flag in prod as of this week so we can close this, right?

**Comment by ariskotsomitopoulos** [comment]
> @ariskotsomitopoulos Threads is behind Labs flag in prod as of this week so we can close this, right?

Correct !
