### ISSUE TITLE
Bug in Legals screen

### ISSUE THREAD

**Issue by bmarty** [vector-im/element-android#4919]
There is a problem on my main account, the homeserver policy cannot be retrieved.

<img width="463" alt="image" src="https://user-images.githubusercontent.com/3940906/149012015-05508e5c-48a1-4628-856f-24816a462f36.png">

There is no network issue (since the terms for the identity server can be retrieved).

This is what I see in the "Homeserver" screen if it helps:

<img width="461" alt="image" src="https://user-images.githubusercontent.com/3940906/149012172-046d9f8b-ba50-4014-adf7-a1bc06712194.png">

From the rageshake:
```
2022-01-11T19:49:42*805GMT+00:00Z 370689 E/ /Tag: Error while getting homeserver terms
NetworkConnection(ioException=java.net.UnknownHostException: Unable to resolve host "matrix.org_matrix": No address associated with hostname)
	at org.matrix.android.sdk.internal.session.terms.DefaultTermsService.getHomeserverTerms(DefaultTermsService.kt:32)
```

It seems that a `/` is missing in the URL

Element Android 1.3.13.

**Comment by lfom** [comment]
It seems that it does not work anymore, this error is displayed in red (like the previous error): "Unrecognized request", and the homeserver.log:

**synapse.http.server - 95 - INFO - GET-361 - <XForwardedForRequest at 0xffff840962b0 method='GET' uri='/_matrix/client/r0/register' clientproto='HTTP/1.0' site='8008'> SynapseError: 400 - Unrecognized request**

I have enabled "consent" in resources, and `https://<server>/_matrix/consent` displays the terms correctly.

**Comment by bmarty** [comment]
@lfom have you double checked your homeserver configuration?

Also this issue is closed, and I think your problem is not related to the fix which closed it. Could you open a dedicated new issue please?

Thanks!

**Comment by lfom** [comment]
@bmarty thank you for your reply. Yes, probably the cause of the problem is different. But I have searched for many hours in the Synapse documentation and online, and this was the only reference I found about the homeserver terms. I even looked at the code, it explicitly says it uses a hack for the registration endpoint to get the terms but I didn't find anywhere any information or example about it. If you could point me to the right direction, it'd be great. I will surely open a new issue once I'm sure it's not homeserver configuration issue. Thanks

**Comment by bmarty** [comment]
OK.

Is registration disabled on your server?

Can you post here the output of `curl -s -X POST --data $'{}' https://<replace_by_your_server>/_matrix/client/r0/register` please?

**Comment by lfom** [comment]
@bmarty I think you nailed it: registration is not enabled. I will do more tests, but probably it would be better to fetch the info some other way. Thanks a lot!

**Comment by bmarty** [comment]
Yes, this is workaround, since there is no existing API to get the terms once the account has been created.

**Comment by lfom** [comment]
Maybe using this?

https://github.com/matrix-org/synapse/blob/master/docs/consent_tracking.md
