### ISSUE TITLE
riotX not show webp images

### ISSUE THREAD

**Issue by progserega** [vector-im/element-android#492]
![Screenshot_20190817-143948](https://user-images.githubusercontent.com/1297163/63206730-582b4380-c0fd-11e9-89db-0e9b29a24c58.png)
![Screenshot_20190817-143941](https://user-images.githubusercontent.com/1297163/63206731-58c3da00-c0fd-11e9-80ce-15f98f368cdb.png)

**Comment by kevincox** [comment]
This works for me.

**Comment by progserega** [comment]
work :+1:
