### ISSUE TITLE
can't log out if server is unreachable

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-android#4920]
### Steps to reproduce

1. shut down your server
2. try to log out

#### What did you expect?
log out without deleting the session from server

#### What happened instead?
can't log out.

additionally, it keeps insisting I enable my key backup, even though server isn't reachable. also, I already have a key backup set up to make it even more confusing.

### Application version and app store

schildi 1.3.12.sc48-test11

### Will you send logs?

No

**Comment by ouchadam** [comment]
thanks for raising :+1:  going to close in favour of https://github.com/vector-im/element-android/issues/4855
