### ISSUE TITLE
message failed to send on 1.3.13

### ISSUE THREAD

**Issue by rakshazi** [vector-im/element-android#4922]
### Steps to reproduce

1. Try to send a message in any encrypted room
2. Get the error

#### What did you expect?

Message sent

#### What happened instead?

Message failed to send

### Application version and app store

1.3.16-dev [210339460] (F-b5452) develop

### Will you send logs?

No

**Comment by scottwallacesh** [comment]
Logging out and logging in again whilst on v1.3.13 got it working again.

**Comment by skdubg** [comment]
> Logging out and logging in again whilst on v1.3.13 got it working again.

it doesn't help. Error occurs again

**Comment by scottwallacesh** [comment]
> > Logging out and logging in again whilst on v1.3.13 got it working again.
> 
> it doesn't help. Error occurs again

Interesting. Still working okay for me. I did also clear my data storage and cache.

**Comment by returntrip** [comment]
> > Logging out and logging in again whilst on v1.3.13 got it working again.
> 
> it doesn't help. Error occurs again

Same here, I logged out and then back in, it worked for about 10m amd started failing again.

I know 2 more people with the same issue. Hopefully a working version will be soon available on the Play store

**Comment by scottwallacesh** [comment]
Mine worked the entire time.  I'm on v1.3.14 now.

**Comment by rakshazi** [comment]
1.3.14 works
