### ISSUE TITLE
Linking Rooms Only Searches Addresses

### ISSUE THREAD

**Issue by Fidgetcetera** [vector-im/element-android#4929]
### Steps to reproduce

1. Type # to get autocomplete suggestions for linking rooms that you're in.
2. Type the display name of a room which has an address not matching the name of the room. (IE, room address is #metadata.anthurium:nora.codes, room name is "info".)
3. The room will disappear from the autocomplete suggestions.

#### What did you expect?
Room name, as well as address, to be searched in the autocomplete (as they are on Element 
web/desktop.)
#### What happened instead?
Rooms I know exist and can link to based on their Address don't show up in the autocomplete search for the room name.

### Your phone model

Pixel 4a

### Operating system version

Android 12

### Application version and app store

Element version 1.3.9, olm version 3.2.4, from F-droid.

### Homeserver

nora.codes

### Will you send logs?

Yes

**Comment by ouchadam** [comment]
adding _needs product_ label to confirm the expected behaviour (and if it needs to be implemented across different clients),  searching both display name and address sounds very reasonable

**Comment by Fidgetcetera** [comment]
Oops! Sorry about that, misclick.
