### ISSUE TITLE
The `Help Improve` modal is shown even before I completed my device verification

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/element-android#4932]
### Steps to reproduce

Login a new session

![image](https://user-images.githubusercontent.com/9841565/149184212-02bb3f87-5186-4c7a-8998-439050cb29b9.png)

^this

#### What did you expect?

It feels a bit confusing, not sure the best way to handle that.. Probably let me finish with verification first.

### Will you send logs?

No

**Comment by ouchadam** [comment]
going to close a dupe of https://github.com/vector-im/element-android/issues/4933
