### ISSUE TITLE
Analytics modal shown at the same time as verification toast

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/element-android#4933]
### Steps to reproduce

The modal is shown and I haven't yet finished verifying my session

![image](https://user-images.githubusercontent.com/9841565/149184676-52eda810-8f2a-4c8c-945d-e6cc2ebbe741.png)

#### What did you expect?
It's a bit confusing, would maybe be preferable to let me finish with verification first?

### Will you send logs?

No

**Comment by bmarty** [comment]
In EA 1.3.16
