### ISSUE TITLE
Clarify navigation to reset password

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-android#4946]
#### How would you like to achieve it?
1. Try to sign in with Matrix ID
2. forget pw
3. it says "go back to reset it"
4. go back
5. there is no reset button

Instead it should explain that you need to select a server before you can reset your password.
There should probably also be a reset button in your face on the "Select a server screen".

- if you choose matrix.org, there is only sign up and sign in. you have to try sign in first to get the option to reset
- ems: should be reviewed, but i don't have ems
- custom: same as matrix.org

**Comment by ouchadam** [comment]
for reference

| SIGN IN WITH MATRIX ID | SIGN IN MATRIX.ORG | 
|![Screenshot_20220114_165036](https://user-images.githubusercontent.com/1848238/149553726-0df25add-b374-4a76-b5a8-84e8170b1e8a.png)|![Screenshot_20220114_165257](https://user-images.githubusercontent.com/1848238/149553897-41600fb0-fad5-44a7-a355-ff731439231f.png)

Feels like we could add a forgot password button to match the other sign in flows, adding _needs product_ label

**Comment by HarHarLinks** [comment]
> Feels like we could add a forgot password button to match the other sign in flows

Upon pressing that button, the app should find the correct homeserver from the mxid you have likely entered, and otherwise ask for the server. then it could just navigate to the existing pw reset screen of that server with the info pre-filled.

**Comment by daniellekirkwood** [comment]
I think this is part of our FTUE work. @amshakal can you confirm that the update to the forgot password flow will address all the issues here?

**Comment by daniellekirkwood** [comment]
The new auth flow addresses this issue and is in the process of being released, I'm closing this issue.
