### ISSUE TITLE
V1.3.16，fail send message. log: failed Unable to encrypt Room was previously configured to use encryption, but is no longer. Perhaps the homeserver is hiding the configuration event.

### ISSUE THREAD

**Issue by forever8361** [vector-im/element-android#4951]
### Steps to reproduce

1. Deploy your own home service.
2. Register accounts a and b on device A and device B respectively, and enter the private chat, normal
3. Log in to the a account on device C as well, and perform device verification. When chatting with b, it was found that the message could not be sent, and the message: failed Unable to encrypt Room was previously configured to use encryption, but is no longer. Perhaps the homeserver is hiding the configuration event.
4. But device A and device B are normal and can chat normally

### Outcome

Why can't the same account continue to chat or send messages after logging in and verifying on other devices?

### Will you send logs?

No

**Comment by bmarty** [comment]
Hello, which server implementation are you deploying? Synapse or another one?

**Comment by forever8361** [comment]
> Hello, which server implementation are you deploying? Synapse or another one?

hello, no Synapse. is dendrite .  

step:
1. B invites A, B to create a private chat（B must invite A and B to create a private chat）
2. A joins the room, starts a private chat, everything is normal
3. A logs out and logs in again (or A logs in with a new device)
4. A can no longer send messages to B

Note: 
1. Follow this step for 100% reproduction
2. dendrite sever   someone else suggested： https://github.com/matrix-org/dendrite/issues/2082 .

**Comment by forever8361** [comment]
> Hello, which server implementation are you deploying? Synapse or another one?

Can you locate the reason? Is the event lost in the dendrite server?

**Comment by kegsay** [comment]
I've hit something like this on matrix.org before due to Element-Web crashing out before it can persist the `m.room.encryption` event. See https://github.com/vector-im/element-web/issues/19705 - something similar could be happening here, or equally it could be a Dendrite bug. Without knowing the network responses it's hard to tell.

**Comment by ouchadam** [comment]
@forever8361 this sounds like it could also be related to https://github.com/vector-im/element-android/issues/5068

we have a fix available in 1.3.18 which might also fix this issue (if it's client side and not in dendrite)

**Comment by Florian14** [comment]
I close this issue since the mentioned PR are merged and there is no more activity here. Feel free to reopen if the issue still exists
