### ISSUE TITLE
Crash on 1.3.14 on API < 24

### ISSUE THREAD

**Issue by bmarty** [vector-im/element-android#4961]
<img width="744" alt="image" src="https://user-images.githubusercontent.com/3940906/149751362-98e87d0f-9826-47cc-982d-ddc2eadeb58a.png">

Create an extension to fix that (see the code in EmojiRecyclerAdapter)

Ideally check why the CI is not blocking issues like that.

**Comment by ouchadam** [comment]
would be great to see if we can also get lint to flag these are errors to prevent any future regressions

**Comment by bmarty** [comment]
Fixed in 1.3.15
