### ISSUE TITLE
App crashes on attempt to log in to SAML-only homeserver

### ISSUE THREAD

**Issue by AndrewFerr** [vector-im/element-android#4969]
### Steps to reproduce

1. Log out
2. On the start screen, tap "I already have an account"
3. Tap "Other"
4. In the "Address" field, type the address of a homeserver that supports only SAML/SSO logins, such as https://chat.mozilla.org

#### What did you expect?
The app should prompt to continue with a SAML/SSO login.

#### What happened instead?
The app crashes.

### Your phone model

Samsung Galaxy S8

### Operating system version

Android 9

### Application version and app store

1.3.16-dev

### Homeserver

chat.mozilla.org

### Will you send logs?

Yes

**Comment by bmarty** [comment]
Crash confirmed.
It's working correctly when reverting to the legacy auth flow.

TODO:
- [ ] Check that this issue also impact 1.3.14 - If this is not the case, no need to include the fix in #4970
- [ ] Make the flow Get Started / mozilla server / SSO page work. No we see a dialog: "the server does not accept new accounts".
- [ ] Make the flow I already have an account / mozilla server / SSO page work (it is not working on legacy, but works on login2). This is P2 regarding the crash fix
- [ ] Add the 2 flows above to the all screen sanity test.

**Comment by ouchadam** [comment]
> * [x]  Check that this issue also impact 1.3.14 - If this is not the case, no need to include the fix in [[Release] Element Android v1.3.15 - Corrective release #4970](https://github.com/vector-im/element-android/issues/4970)


Confirmed, the crash was introduce (by enabling the feature) in 1.3.13 by https://github.com/vector-im/element-android/pull/4872 

> * [x]  Make the flow Get Started / mozilla server / SSO page work. No we see a dialog: "the server does not accept new accounts".
> * [x]  Make the flow I already have an account / mozilla server / SSO page work (it is not working on legacy, but works on login2). This is P2 regarding the crash fix


Both cases are fixed by #4973 

> * [ ]  Add the 2 flows above to the all screen sanity test.

Will raise as a separate PR, also including the changes for the splash carousel #4964

**Comment by ouchadam** [comment]
Fixed in 1.3.15
