### ISSUE TITLE
Threads: Improve fallback for clients without Threads

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-android#4972]
### Your use case

Instead of including the Root Message in the Reply view for clients without Threads, show the message previous to the response.

@daniellekirkwood to add more info

We know and accept that some clients will not update their versions and therefore will not have this new and improved fallback will not be available to everyone. Those users who do not update their version from the app/play store will still have the previous fallback of seeing the Root message.

**Comment by daniellekirkwood** [comment]
I think we also need content for what to show when the message has not yet been fetched, as we're currently showing "null". This also is the case on iOS: https://github.com/vector-im/element-ios/issues/5394

@janogarcia

**Comment by ariskotsomitopoulos** [comment]
This case would be rare while now we are using as fallback the previous event. However, I implemented that. You can suggest a better text resource:
![Screenshot_20220124-140236_Element dbg](https://user-images.githubusercontent.com/60798129/151002008-bcaa5ac9-677a-49ff-a9e7-7c1f979436fb.jpg)

**Comment by daniellekirkwood** [comment]
This is great! Let's go with that - I will update the iOS issue. Thanks, @ariskotsomitopoulos

**Comment by janogarcia** [comment]
@ariskotsomitopoulos Can you please confirm if we're not showing the "In reply to `@name`" part before the "Replied within a thread" placeholder message? Unsure if we're not rendering it at all when handling this edge case or it was just cropped in the screenshot you shared.

@daniellekirkwood If we're not rendering the "In reply to `@name`" part at all, should we consider following a similar copy for the placeholder message? `In reply to a thread` instead of `Replied within a thread`.

Same for iOS.

**Comment by ariskotsomitopoulos** [comment]
@janogarcia When we don't have the parent relation or the event local in the device we removed completely the `In reply to` and it is like in the image above. In all the other cases that we have the event and the relation is like a normal `reply`. Is that clear?

**Comment by janogarcia** [comment]
@ariskotsomitopoulos Thanks for the clarification, Aris. 👍️ Then, I would suggest changing the copy to `In reply to a thread`, to keep it more consistent with similar messages, but let's give @daniellekirkwood the final word on that.

**Comment by daniellekirkwood** [comment]
OK. 

@janogarcia Can you update the necessary Figma and iOS issue [here](https://github.com/vector-im/element-ios/issues/5394). Thanks
