### ISSUE TITLE
Rooms missing from Space favourites

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-android#4986]
### Steps to reproduce

1. Look at Favourites in a Space on Element web, see 9 favourites
2. Open the same space on Android in the left panel
3. In the Rooms tab, count the favourites and see 8

I favourted the room about half a year ago, so it's not an issue with a recent update not propagating

#### What did you expect?
The Favourites list on Android should show the same rooms as the list in Element web

#### What happened instead?
The Delight room is missing from the Element space Favourites on Android

### Operating system version

Android 11

### Application version and app store

1.3.14

### Will you send logs?

No

**Comment by ericdecanini** [comment]
@kittykat I was unable to reproduce this on my side. Could you provide a screen record?

I can see on Element Windows that the Delight rooms do not belong to the Element Corp space

**Comment by kittykat** [comment]
I can't reproduce any more: Android and Web are currently showing me the same totals so I'll close this issue for now. Will reopen if I can again.
