### ISSUE TITLE
Exclude dependabot upgrade for @github-script@v3

### ISSUE THREAD

**Issue by ariskotsomitopoulos** [vector-im/element-android#4988]
Newest @github-script 5.x.x  versions removed functions for comment deletion

**Comment by bmarty** [comment]
What wrong with version 5.x.x ? I would required some code migration?

**Comment by ariskotsomitopoulos** [comment]
This issue is just for **v3**, to exclude updates. Nothing wrong with **5.x.x** just missing a function for comment deletion. Check the [PR](https://github.com/vector-im/element-android/pull/4989)

**Comment by bmarty** [comment]
I see your point now, thanks!
