### ISSUE TITLE
RSS Rate limits

### ISSUE THREAD

**Issue by xtrime-ru** [vector-im/element-android#4992]
#### What would you like to do?
Need ability to control how many requests your backend sends to different data providers. 

#### Why would you like to do it?
Some sources have rate limits. When multiple users add a lot links from same source your server will stuck in blacklist. 

Im owner of Telegram -> RSS bridge https://github.com/xtrime-ru/TelegramRSS. Public url: https://tg.i-c-a.su/. And your server constantly exceeds RPM limits. 

![telegram-cloud-photo-size-2-5417944563953285282-y](https://user-images.githubusercontent.com/34161928/150141866-0dbf8915-3113-4d61-b2e8-c2d877b4a3f4.jpg)

I increased RPM for your server as temporary fix.

#### How would you like to achieve it?

Add table with source/host -> Max RPS relation. Then control how many requests backend generates to such sources. 
Also validation would be fine: disable sources with constant errors. For example, if channel removed.

**Comment by Half-Shot** [comment]
Thanks for the report. I think I understood your request well enough and have opened an issue to track in https://github.com/matrix-org/go-neb/issues/382

**Comment by xtrime-ru** [comment]
I checked new issue - it is exactly what i meant. Thanks!
