### ISSUE TITLE
Missing plurals in localization

### ISSUE THREAD

**Issue by libexus** [vector-im/element-android#4997]
### Steps to reproduce

[poll_total_vote_count_before_ended_and_not_voted](https://translate.element.io/translate/element-android/element-app/de/?checksum=42583658a10ba344) has 3 plural forms (0, 1, >1) in the source string, but the translated strings have not. This is not exclusive to german.

![grafik](https://user-images.githubusercontent.com/67947338/150205476-95b9c6dd-9b15-4d0f-98e3-091a818058da.png)

### Outcome

-

### Will you send logs?

No

**Comment by bmarty** [comment]
This is an error, `<item quantity="zero">` should not be present in the default translation. I will fix that.
