### ISSUE TITLE
Use button states consistently throughout app

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-android#500]
(Internal) Zeplin: https://zpl.io/aBKw9Mk

<img width="381" alt="Screenshot 2019-08-20 at 16 26 54" src="https://user-images.githubusercontent.com/4626865/63391463-6381a780-c367-11e9-85c7-a3a7d728f208.png">

We should ensure we're using the correct button states consistently through the app for main call to actions. At the least, ensure this is accurate in the Sign In screen as that's the first impression of the app.

**Comment by nadonomy** [comment]
Note to self: Validate these states are 100% what we want by comping them in multiple contexts.

**Comment by bmarty** [comment]
Should iterate on it after the rebranding
