### ISSUE TITLE
Notifications are broken on 1.3.14 F-Droid

### ISSUE THREAD

**Issue by konomikitten** [vector-im/element-android#5003]
### Steps to reproduce

1. Enable Caffeine for testing purposes this prevents your phone sleeping.
2. Observe that **no notifications** come through when Element is closed and not running as a background app, even though the "Listening for notifications" persistent notification is present.
3. Launch Element and then press the home button to move it to the background (running as a background app), note that **no notifications** come through.
4. Finally bring Element to the foreground but do not have it focused on a chat that would generate a notification and you will finally have **notifications displayed**.

Summing up, currently for the F-Droid build notifications are broken in every aspect unless Element is in the foreground.

The problem was not occurring on the previous Element build from F-Droid (1.3.9).

#### What did you expect?
Notifications should be received no matter what state Element is in.

#### What happened instead?
No notifications are received unless the app is open and in the foreground.

### Your phone model

Asus Zenfone Selfie ZD551KL

### Operating system version

Android 7.1.2 (LineageOS 14.1)

### Application version and app store

Element version 1.3.14 olm version 3.2.10 from F-Droid

### Homeserver

matrix.org

### Your phone model

Motorola Moto E Dual SIM (2nd gen) XT1521

### Operating system version

Android 10 (LineageOS 17.1)

### Application version and app store

Element version 1.3.14 olm version 3.2.10 from F-Droid

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by konomikitten** [comment]
Both phones have sent rage shake reports with the heading and issue number of this bug report.

**Comment by fabienli** [comment]
same issue on my samsung galaxy s9

**Comment by ouchadam** [comment]
does this also occur when `Caffeine` is not running?

**Comment by konomikitten** [comment]
@ouchadam yes still a problem without caffeine on.

**Comment by ouchadam** [comment]
thanks for raising, it looks like there's been a regression which caused the `optimised for battery` mode to no longer schedule the next sync after completing the first one in the background, a temporary workaround is to select the `optimised for realtime` in the Settings -> Notifications -> Background sync mode

**Comment by konomikitten** [comment]
> a temporary workaround is to select the `optimised for realtime` in the Settings -> Notifications -> Background sync mode

How heavily will this drain a phones battery compared to optimised for battery?

**Comment by ouchadam** [comment]
it's hard to say as different ROMs/OEMs have unique battery optimisations, for most cases where the device is being used throughout the day there isn't too much of a difference, if a device is sat idle and not being used at all then there would be a much bigger difference in battery usage.

**Comment by konomikitten** [comment]
@ouchadam pretty sure once I changed the sync setting and leave Element open on a channel like say #matrix that it just started consuming tons of cpu and started leaking memory please advise. Screenshot of Element resource hogging on my phone via adb shell htop:

![Screenshot_2022-01-21_11-46-16](https://user-images.githubusercontent.com/12713710/150445566-5a398a72-f0df-4bfc-9b81-f7221bdb0ea2.png)

**Comment by bmarty** [comment]
This issue will be fixed in 1.3.16.
I open a dedicated issue for your latest concern @konomikitten

**Comment by Karamelmar** [comment]
Got the notifications running again after switching "Background Sync" in Settings > Notifications from "Optimized for battery" to "Optimized for real time".

**Comment by marcusmueller** [comment]
@Karamelmar this did not fix the issue for me; 1.3.15 android via fdroid.

Neither did giving unrestricted network access. This is a rather severe regression.
