### ISSUE TITLE
Unable to dowload images???

### ISSUE THREAD

**Issue by AverytheFurry** [vector-im/element-android#5005]
### Steps to reproduce

1. Click on an image
2. Try holding your finger on it, nothing happens
3. Try hitting share, no option to save
4. Cant download???

#### What did you expect?
The ability to download images
#### What happened instead?
This functionality does not seem to exist

### Your phone model

Pixel 4a5g

### Operating system version

Android 11 LineageOS 18.1

### Application version and app store

Element Version 1.3.14 Olm Version 3.2.10

### Homeserver

yiff.social

### Will you send logs?

No

**Comment by bmarty** [comment]
All is working here. Maybe only on LineageOS?

**Comment by konomikitten** [comment]
> All is working here. Maybe only on LineageOS?

Tested Element 1.3.14 here on LineageOS 14.1/17.1 on matrix.org no issues.

Friend tested 18.1, same version same instance and also had no problems.

**Comment by kittykat** [comment]
I can confirm that the gallery has only a share button

**Comment by AverytheFurry** [comment]
> > All is working here. Maybe only on LineageOS?
> 
> ~~Tested Element 1.3.14 here on LineageOS 14.1/17.1 on matrix.org no issues.~~
> 
> ~~Friend tested 18.1, same version same instance and also had no problems.~~
> 
> Edit: Seems I misread the original report, this is for an image already open not in the chat log, which definitely does not have any other option but sharing, is this a UI oversight?

Yeah, luckily found out u can hold on the message itself and hit "save" but thats hardly intuitive

**Comment by ouchadam** [comment]
:+1: I would definitely appreciate a dedicated download button/menu in the gallery view

For context

| TIMELINE | IMAGE VIEWER | LONG PRESS |
| --- | --- | --- |
|![Screenshot_20220121_172748](https://user-images.githubusercontent.com/1848238/150572660-b9000957-4d40-4c28-9798-65322fca95c0.png)|![Screenshot_20220121_172740](https://user-images.githubusercontent.com/1848238/150572666-a5b4ffbb-b45a-4c9b-8c2c-06ed3cf7296a.png)|![Screenshot_20220121_172905](https://user-images.githubusercontent.com/1848238/150572835-adfa94c5-893f-43f6-948b-fbe45a2e4ad4.png)

_looping in product_ @daniellekirkwood

**Comment by daniellekirkwood** [comment]
Thanks for bringing this to my attention @ouchadam. Yes, let's go ahead and add a Save button to the gallery view.

Tagging @amshakal for review and placement confirmation.

**Comment by amshakal** [comment]
LGTM. Can we change the ordering over here, and move add reaction, save and share above remove? (In that particular order) Seems like if someone shares an image, the user is more likely to save or share it than remove someone else's image?

I also noticed we have the option to copy images on iOS but not on Android. Something worth adding?

**Comment by amshakal** [comment]
Link to save/download icon: https://www.figma.com/file/X4XTH9iS2KGJ2wFKDqkyed/Compound?node-id=1373%3A13

**Comment by bmarty** [comment]
In Element 1.4.4
