### ISSUE TITLE
Notifications are unreliable

### ISSUE THREAD

**Issue by Destroyer** [vector-im/element-android#5016]
### Steps to reproduce

I am running a homeserver for friends. I am always getting all message notifications on my phone just fine. Friends do report however, that they sometimes miss a notification 

Pixel friend recieves about 30% of the notifications. 
Xiaomi friend recieves about 20% of notifications (he's on matrix.org though and i am sending him messages from my server).
Third friend does have to clear cache sometimes which resolves the problem fully (OnePlus)

Troubleshooting in the mobile app ends up all green
Clearing cache sometimes solves the problem for a little, then it reappears

#### What did you expect?
Notifications to be reliable
#### What happened instead?
Notifications appear 20-100% of the time

### Your phone model

Pixel 3a / Xiaomi / OnePlus

### Operating system version

Android 12 / Android 10 / Android 11

### Application version and app store

1.3.12-1.3.15

### Homeserver

matrix.vcklan.cz (synapse  v1.49.2), matrix.org 

### Will you send logs?

No

Are there any options for me to debug such issue?

**Comment by ouchadam** [comment]
I've also seen similar quirks with the notifications but then other times they would work perfectly, could I ask that your friends try going into their room settings -> notifications and selecting _none_ then back to _all messages_ 

if this solves the issue it means our push rules are falling out of sync somewhere~

**Comment by Destroyer** [comment]
Tested with Pixel friend - not sure if it 'solved' the issue, it was reliable for about 6 hours before first missed notification

also none of us uses fdroid versions, everybody got it from google play

**Comment by ouchadam** [comment]
centralising the issue to https://github.com/vector-im/element-android/issues/5038
