### ISSUE TITLE
Home feels redundant when all messages are read

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-android#502]
(May be a duplicate of other issues, but just quickly capturing things to ensure they're not lost).

Home can feel redundant when all messages are read. There's some nuance we're currently lacking which we should discuss, design and iterate on:

- Should Home not clear rooms from the view when viewing them? Either never, so the list essentially is always sorted by activity (like Whatsapp) or being reduced to a lower alpha 'read' state when viewing them, when it's later cleared between sessions or switching tabs?
- We should consider allowing the user to just simply scroll into a list of rooms by activity below the 'New messages' list

**Comment by Jiack214** [comment]
This issue is related to #171.

It would be nice to have something like this implemented in RiotX.

> We should consider allowing the user to just simply scroll into a list of rooms by activity below the 'New messages' list

This seems like my mokup in https://github.com/vector-im/riotX-android/issues/171#issuecomment-513368236

**Comment by bmarty** [comment]
Home redesign is discussed internally.
