### ISSUE TITLE
disable emoji keyboard not applied to replies

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-android#5029]
### Steps to reproduce

1. disable emoji kb in settings
2. open room
3. compose normally: no emoji kb button
4. swipe a message to start a reply
5. there is now a button to switch kb, partially in broken state

### Outcome

see above

### Application version and app store

1.3.15 F-Droid

### Will you send logs?

No

**Comment by bmarty** [comment]
Fixed in #6757
