### ISSUE TITLE
Reduce delay when re-enabling FAB

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-android#506]
When the FAB is dismissed by scrolling down, it's re-introduced by scrolling back to the top. However, it currently takes 3000-4000ms for it to appear, making the app feel broken.

In future, we'd like the FAB to automatically re-appear when scrolling up. However, as a super simple quick fix, we should simply reduce this delay to something short and immediate (100ms?).

**Comment by bmarty** [comment]
Super simple quick fix has been implemented here: 3d2d219d795ee3d3b7d1837c961999d3d9f12d0e
