### ISSUE TITLE
Location: Element doesn't look for location

### ISSUE THREAD

**Issue by kojid0** [vector-im/element-android#5061]
### Steps to reproduce

1. From attachment picker, tap Location icon
2. Grant permission to access location
3. Nothing happens:
![grafik](https://user-images.githubusercontent.com/24477557/151048606-08af851a-95c9-486d-87d7-18e1fdbca90e.png)

#### What did you expect?
Map zooms in to current location. 

#### What happened instead?
World map is shown.

#### Additional info
Device asked to grant location access for Element. Granted. Device doesn't search for location (icon is not shown in the status bar. It is usually visible when apps ask for location). Force close app and retry with permanent location access granted doesn't help. Sent a log/rageshake. 

### Your phone model

Google Pixel 5

### Operating system version

Android 11

### Application version and app store

Element 1.3.16-dev [210460560] develop

### Homeserver

tchncs.de

### Will you send logs?

Yes

**Comment by bmarty** [comment]
I had the same issue, but after about 30s, my location was correctly retrieved.

**Comment by kojid0** [comment]
Unfortunately, not for me. I'm using CalyxOS (no Google Play Services) with Mozialla Location Service / Déjà Vu Location Service (microG).
Don't understand why you didn't place this feature in "experimental settings".
Also, a FAB to force-search my location might help.
![grafik](https://user-images.githubusercontent.com/24477557/151127188-88792f0d-3f29-4536-b606-b4d7e6d4f225.png)

**Comment by bmarty** [comment]
We had a long internal discussion about the setting place.
Sharing location is off by default and you are right it is still in beta.
Anyway thanks for the feedback, we are working on this issue.

**Comment by kojid0** [comment]
Has been fixed with v1.3.17. Thanks!
