### ISSUE TITLE
Poll cannot end in some unencrypted rooms

### ISSUE THREAD

**Issue by ariskotsomitopoulos** [vector-im/element-android#5067]
### Steps to reproduce

1. Create a poll in an unencrypted room (the problem do not exist in all the unencrypted rooms) 
2. Vote
3. End the poll

I observed this issue in two rooms, but in some others works. 

#### What did you expect?
The poll to be end
#### What happened instead?
The poll did not End

### Application version and app store

1.3.16

### Will you send logs?

No

**Comment by onurays** [comment]
```
if (!powerLevelsHelper?.isUserAbleToRedact(event.senderId ?: "").orFalse()) {
            Timber.v("## Received poll.end event $pollEventId but user ${event.senderId} doesn't have enough power level in room $roomId")
            return
        }
```

Here is the reason.
