### ISSUE TITLE
Iterate on MD input

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-android#509]
Currently we don't expose MD syntax, and some users have reported errors when trying to enter calculations.

We should benchmark other Android apps for some inspiration, and then discuss possible solutions.

**Comment by bmarty** [comment]
First thing to do is #412 IMHO, to ensure users know what they are doing when playing with MD

**Comment by bmarty** [comment]
Now that #412 is done, we can maybe add inline formatting when selecting text, to teach user on how to write markdown.

We can use menu of text selection to do for instance: bold/italique/strike/etc. change on the selected text

**Comment by bmarty** [comment]
Please open such issue in the design project
