### ISSUE TITLE
Allow option to autoplay GIF images

### ISSUE THREAD

**Issue by binarydad** [vector-im/element-android#5094]
#### What would you like to do?

Similar to the web/desktop client, allow option to auto-play GIF images instead of manually pressing play button. 

#### Why would you like to do it?

We send GIFs frequently, and the experience varies between desktop and mobile. 

#### How would you like to achieve it?

Add a toggle, similar to the desktop/web version, called "Autoplay GIFs" to the android app.

**Comment by bkil** [comment]
This is a duplicate:

- https://github.com/vector-im/element-android/issues/1160

Related:

- https://github.com/vector-im/element-android/issues/2668
- https://github.com/vector-im/element-android/issues/1886

**Comment by bmarty** [comment]
dup of #1160
