### ISSUE TITLE
Configure a GitHub action to run the sonar analysis on develop every day

### ISSUE THREAD

**Issue by bmarty** [vector-im/element-android#5096]
We have a sonar cloud setup at https://sonarcloud.io/project/overview?id=im.vector.app.android

Currently I run it *regularly*.

We should set up a GitHub action, using a GitHub secret to store the token that I can provide, to let the command be run every night on the `develop` branch and so have a better usage of this tool.

The command to call is:

```sh
/gradlew sonarqube -Dsonar.login=$SONAR_LOGIN
```

Set up Jacoco and calling this command before:

```sh
./gradlew jacocoTestReport :matrix-sdk-android:jacocoTestReport :matrix-sdk-android-flow:jacocoTestReport :multipicker:jacocoTestReport :attachment-viewer:jacocoTestReport
```

will give sonar some useful code coverage by test metric, that we could then track as well.

**Comment by michaelkaye** [comment]
This is now regularly running against develop. We'll let it run (including the code coverage) for a week and then look back and see if we need to tweak it.

**Comment by michaelkaye** [comment]
There was something that needed tweaking with it but it sounds like it's doing the right things now.
