### ISSUE TITLE
Add completion for @room as per element web

### ISSUE THREAD

**Issue by bmarty** [vector-im/element-android#5123]
When typing "@r" to a room I should be proposed a completion for "@room", if my power level let me notify the room like this.

There are also sections in the completion popup that we could also introduce, see below:

<img width="1061" alt="image" src="https://user-images.githubusercontent.com/3940906/152116983-c4d9f4af-b349-496d-871b-371022c316db.png">

**Comment by mnaturel** [comment]
Hi @amshakal , can you review the design part? I have added screenshots (both in light and dark theme) in #5237 . Thank you.
