### ISSUE TITLE
Reactions appear cut off

### ISSUE THREAD

**Issue by Throlo** [vector-im/element-android#5149]
![Screenshot_20220203-161812_Element_1](https://user-images.githubusercontent.com/82319992/152414699-f968568d-270c-44a1-b2b0-da16a5b50673.jpg)

The reactions appear cut off regardless of whether it is a room or a direct chat.

**Comment by kojid0** [comment]
Cannot reproduce. Your emoji looks way bigger than mine. What font size did you select in settings?

**Comment by kojid0** [comment]
> "Largest"

Alright, can reproduce now. Looks like the button doesn't resize along with the other elements.

**Comment by ganfra** [comment]
Closed by #5204
