### ISSUE TITLE
Implement improved rendering for threads in the main timeline

### ISSUE THREAD

**Issue by janogarcia** [vector-im/element-android#5151]
**Changelog**

Root messages should form a standalone group with their respective thread summaries.

This way, we establish a clear relationship between the thread summary and the root message it belongs to. Failure to do it results in an ambiguous relationship that only gets worse when message bubbles are enabled.

**Source**

→ https://www.figma.com/file/T309ztx0sNyOOK6NKVLHsK/Threads?node-id=3085%3A305790

**Snapshot**

![Threads – Figma](https://user-images.githubusercontent.com/60790/165072410-6bd105b4-6234-43ef-b8c1-9b506d62a29d.png)

**Comment by janogarcia** [comment]
I've updated the issue description and mockup for better clarity on what the expected rendering should be. 👍

---

Current implementation is close to it but not there yet.

The thread should have been rendered in a standalone group that doesn't include the `fourth` message.

![Screenshot_20220425-123414](https://user-images.githubusercontent.com/60790/165073167-0b1ba543-3411-46a7-aaf5-785892d7d800.png)

**Comment by ariskotsomitopoulos** [comment]
Thanks for pointing this out, now its much more clear

**Comment by novocaine** [comment]
@janogarcia please review and close if you're happy

**Comment by janogarcia** [comment]
@ariskotsomitopoulos Hadn't worked for me so far. Updating to the latest Beta 1.4.16 (released yesterday) did the trick. Everything's looking fine now. Thanks! 👍
