### ISSUE TITLE
IA 1: Proposal 1

### ISSUE THREAD

**Issue by niquewoodhouse** [vector-im/element-android#5156]
**Objective**

After we've documented the current IA  #5153 and anticipated users most likely expectations #5154, we should be in a position to make a proposal for a new IA for Element Android.  The proposal should cover the majority of primary flows a user might experience on mobile TBC.

### **Primary**

**Catching up**

- [ ] Receive a notification and go to the relevant room
- [ ] Catch up on overall activity
- [ ] Catch up on activity in a specific room

**Managing a room/DM**

- [ ] Searching for specific message
- [ ] Changing avatar

**Space IA consistency**
* [x] https://github.com/vector-im/element-meta/issues/164

**Comment by kittykat** [comment]
**Starting and joining conversations** is covered by existing plans in the mobile and PS teams so we should drop that in favour of DM/room management
