### ISSUE TITLE
Bubbles: add a little extra top and bottom padding 

### ISSUE THREAD

**Issue by frandavid100** [vector-im/element-android#5159]
### Steps to reproduce

After using Chat Bubbles for some time, I feel like the bubbles should have a little extra padding at their top and bottom. That would make them look more like the ones in Element Web, and make the whole interface look a lot less busy.

Here's a screenshot and a mockup, so that you can compare.

|  |  |
|--|--|
| ![Bubbles A](https://user-images.githubusercontent.com/694794/152585190-50d3043d-8088-4faf-bf5b-b2e64f816403.png) | ![Bubbles B](https://user-images.githubusercontent.com/694794/152585205-555d15d1-48f2-4784-b613-b382639d2ab0.png) |

### Outcome

Chat bubbles have too little padding.

### Your phone model

Pixel 4a

### Operating system version

Android 12

### Application version and app store

Element 1.9.18 dbg

### Homeserver

envs.net

### Will you send logs?

No

**Comment by bmarty** [comment]
In EA 1.4.4
