### ISSUE TITLE
Bubbles: Increase font size a little

### ISSUE THREAD

**Issue by kojid0** [vector-im/element-android#5160]
### Your use case

While testing bubble layout, I think the font size is a little to small. Compared to Telegram or WhatsApp, Elements message font size is very tiny.

### Have you considered any alternatives?

There's a setting for the font size of the whole app, but then all fonts are increased - not just text inside bubbles.

**Comment by waclaw66** [comment]
Never ending story, I also agree the message font size should be the same as the rest of Element or message font size settings should be available.
All my friends who use Element have noticed that.
Dup of https://github.com/vector-im/element-android/issues/1286

**Comment by thefirstofthe300** [comment]
I too have noticed this fact.  Signal's UI makes very good use of space and text size, IMHO, giving it a very polished feel.

Comparing the size of the font in the Element message view with Signal, it's about 1sp smaller I think given that Signal uses a value of [16sp](https://github.com/signalapp/Signal-Android/blob/ea253a2e678f5247f17f2dd76da555bfeb6b9458/app/src/main/res/values/text_styles.xml#L17). I'd love to see the message view font size tweaked ever so slightly to make the app look not quite so tiny.

Right now, the text size settings almost reminds me of HiDPI support on Linux. You either wind up with text that is slightly too small and this irritating or so gigantic that it just looks wrong.

**Comment by thefirstofthe300** [comment]
As an aside, I think the padding around the text in the message bubble could be bumped a tad bit higher to make the text not feel so squished into the bubble.

**Comment by kojid0** [comment]
> As an aside, I think the padding around the text in the message bubble could be bumped a tad bit higher to make the text not feel so squished into the bubble.

Definitely agree! Can you create an extra issue for this?

**Comment by kojid0** [comment]
@daniellekirkwood @amshakal Why are there no Assignees? Can somebody of you design-review PRs #5716 and #5717? The number of open PRs is very high. Thanks in advance! :-)
