### ISSUE TITLE
Help adding support for noisy notifications for ALL DMs, not just first

### ISSUE THREAD

**Issue by binarydad** [vector-im/element-android#5161]
I really like the android client but really annoyed that a change was made to only bing a noisy alert for the first message, as a check was added to the code to NOT show another noisy notification if one already exists. 

I'm NOT an Android dev, but so far have pulled down the code and am able to generate an APK from the develop branch. 

I came across this line that was added to supposedly only send the alert once. I've experimented with removing this, but noticed random cases where, while I now receive a noisy ding/popup for every DM, sometimes it will ding (and buzz) twice instead of once. It does this across multiple devices. 

Is there something else I need to do? Is there a better way to accomplish this? I'm basically looking for help on how/where re-add noisy notifications for all DMs, but prevent the (sometimes random) double ding/buzz happening. This seems close, but seems simply removing this line isn't enough. Many thanks.

Change made in NotificationUtils.kt:

![image](https://user-images.githubusercontent.com/1760607/152598031-dd37a548-4e69-473a-b46a-f24edb4428e9.png)

**Comment by brevilo** [comment]
Context: #3786

**Comment by binarydad** [comment]
Thank you. This is what I've tried so far, but it will still ding twice. It is in fact every message two dings will occur. I tried it on a couple older/slower devices and there are 2 dings in succession. 

I'm not sure what else to try in this regard. The other file mentioned in the PR, [NotificationDrawerManager.kt](https://github.com/vector-im/element-android/pull/3786/files#diff-c1e2253b1ef80b85a77d664922bf07c861d56dc472e8fbc51b8587ec264269da), has been changed very much since then and I can't try to make a similar change indicated in the commit. 

Would anyone else have any suggestions to prevent the double ding sounds? Thanks.

![image](https://user-images.githubusercontent.com/1760607/152659880-bdba6591-1260-49c9-9e25-7fa31787d23a.png)

**Comment by ouchadam** [comment]
for some extra context the notifications are notified (pinged) via FCM pushes and by the sync service (which is also triggered on each FCM push), this means we end up with potentially duplicated notifies for each message however from a UX perspective we should only notify the first we see them, otherwise you'll be pinged when the FCM completes and again when the sync completes.

to fix the duplicate pings whilst allowing all messages to notify I suspect we still need apply the `setAlertOnce` but only when there's been no new messages (we wouldn't want updates/edits/redactions to notify). We currently diff the current and new notifications so it shouldn't be too tricky to also include a flag to indicate there are new messages

a quick fix would be to disable the FCM fast lane (although notifications may be delayed) which can be achieved by commenting out https://github.com/vector-im/element-android/blob/develop/vector/src/gplay/java/im/vector/app/gplay/push/fcm/VectorFirebaseMessagingService.kt#L170

**Comment by brevilo** [comment]
> a quick fix for the duplicated notifies would be to disable the FCM fast lane (although notifications may be delayed)

I'd call this an ugly workaround, not a quick fix ;) No effence, notification reliability (incl. swiftness) is critical for most users, I reckon. Unfortunately, this is an area where the Android client still hasn't reached (stable) maturity IMHO.

**Comment by binarydad** [comment]
Thank you both.

> We currently diff the current and new notifications so it shouldn't be too tricky to also include a flag to indicate there are new messages

@ouchadam, where is this happening in the code?


> a quick fix for the duplicated notifies would be to disable the FCM fast lane (although notifications may be delayed) which can be achieved by commenting out/deleting https://github.com/vector-im/element-android/blob/develop/vector/src/gplay/java/im/vector/app/gplay/push/fcm/VectorFirebaseMessagingService.kt#L170 and only rely on the sync

@ouchadam, that's funny because I ended up commenting out the exact same line while experimenting with how the notifications were being handled. This actually did work, but on older android devices, the first notification would ding twice, and follow-ups would ding once. I'm still digging into this one (albeit, slowly).

> > a quick fix for the duplicated notifies would be to disable the FCM fast lane (although notifications may be delayed)
> 
> I'd call this an ugly workaround, not a quick fix 😏 No offense, notification reliability (incl. swiftness) is critical for most users, I reckon. Unfortunately, this is an area where the Android client still hasn't reached (stable) maturity IMHO. Sure, some of the "blame" is surely to be taken by Android itself, e.g. apps not reliably woken up by FCM when battery optimized (despite background activity allowed).

Exactly! But, there is no point to having notification reliability of messages only ding for the first of a group. When disabling the "fast lane" line above, I still received notifications as quickly as before.

**Comment by ouchadam** [comment]
keeping the FCM fast lane is definitely preferred, but it does add complexity to the notification processing, as a quick hack :see_no_evil: removing it can remove the source of the duplicated inputs (but not completely fix android's handling of summary groups)

**Comment by ouchadam** [comment]
I'm going to close this issue in favour of an official solution as part of #4632
