### ISSUE TITLE
Leaving All Rooms in Space Leaves DMs with People in Space

### ISSUE THREAD

**Issue by Fidgetcetera** [vector-im/element-android#5163]
### Steps to reproduce

1. Join a space with multiple users you externally have DMs with.
2. Join at least one Room in that space.
3. Leave the space, with the option "leave all rooms in this space.
4. You will leave your DMs with everyone in that space.

#### What did you expect?
I expected to only leave Rooms, not DMs.

#### What happened instead?
Leaving the space and all rooms causes me to leave my DMs with people.

### Your phone model

Google Pixel 5a

### Operating system version

Android 12

### Application version and app store

Element version 1.3.15, olm version 3.2.10, Google Play Store.

### Homeserver

cybre.space, version 1.45.1

### Will you send logs?

No

**Comment by ouchadam** [comment]
looping in product in case this is intentional

**Comment by daniellekirkwood** [comment]
Do we know the behaviour on Web/iOS?

@kittykat & @nadonomy, @niquewoodhouse: you're a lot closer to Spaces and their desired behaviours than me, what is supposed to happen?

**Comment by frakic** [comment]
This issue has been resolved in a more recent version of Element so I'm going to close it.

@Fidgetcetera your DMs should go to Home when you leave a space. If that's not the case, please open another issue.
