### ISSUE TITLE
No push notifications on Conduit

### ISSUE THREAD

**Issue by timokoesters** [vector-im/element-android#5167]
### Steps to reproduce

- Set notification settings to "Optimized for battery"

### Outcome

- No push notification
- Debug "Push:" counter stays at 0

### Your phone model

-

### Operating system version

-

### Application version and app store

-

### Homeserver

conduit.rs

### Will you send logs?

No

**Comment by timokoesters** [comment]
Pushing works on other clients like element iOS or fluffychat

**Comment by ouchadam** [comment]
which version of the app is this? we've had a regression in Optimized for battery background polling in 1.3.14 #5012

**Comment by timokoesters** [comment]
I tried this with the 1.3.19-dev version of Element dbg. I was told https://github.com/vector-im/element-android/pull/5132 did not fix the issue. You can try to reproduce this by creating an account on conduit.rs (in a few hours, I'm running a migration right now)

**Comment by ouchadam** [comment]
:+1: I'll try from my side and report back later

**Comment by ouchadam** [comment]
this conversation was continued in #general:conduit.rs

It seems that setting pushers with the `event_id_only` format causes conduit to be unable to send pushes, however fluffychat uses the same flag but doesn't have the same issue. 

Setting `withEventIdOnly = false` allows the pushes to come through as expected
https://github.com/vector-im/element-android/blob/develop/vector/src/main/java/im/vector/app/core/pushers/PushersManager.kt#L67

**Comment by timokoesters** [comment]
https://github.com/matrix-org/sygnal/issues/295
