### ISSUE TITLE
Remove redundant highlight on add poll option button

### ISSUE THREAD

**Issue by onurays** [vector-im/element-android#5178]
### Steps to reproduce

Highlighting "add option" button seems weird.

### Outcome

Remove highlight of the button

### Will you send logs?

No

**Comment by bmarty** [comment]
I would not have removed the highlight, but rather limit the width of the button to avoid the effect to be full width:

<img width="476" alt="image" src="https://user-images.githubusercontent.com/3940906/153841315-5f98dc44-8360-434d-99a4-9a57b1a205c6.png">

Is it a request from the design team?
