### ISSUE TITLE
Breadcrumbs not accessible

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-android#5191]
### Your use case

Android recently introduced a swipe-right to go back gesture and this makes it extremely hard for users to access the Breadcrumbs panel in app.

We should find an alternative way to present breadcrumbs on android.

![breadcrumbs](https://user-images.githubusercontent.com/89144281/153194226-bc04639a-75c3-4614-ade1-06208f84b257.png)

cc/ @kittykat & @niquewoodhouse

**Comment by daniellekirkwood** [comment]
Assigning this to @kittykat  & @niquewoodhouse as it's directly related to the IA work y'all are looking at.

**Comment by kojid0** [comment]
Inside a chat, what about long-pressing the back-arrow to show the breadcrumb as an alternative way? Currently it only says "navigate up".

**Comment by bmarty** [comment]
Related: #3852

**Comment by nadonomy** [comment]
This breadcrumbs interaction should be abandoned/redesigned— it was hacked in and was a known risk it would clash with established interactions like swipe left to go back when it was added.

**Comment by kittykat** [comment]
@daniellekirkwood can we close this issue as won't fix? We won't be addressing it on Delight, but will consider as part of IA designs

**Comment by daniellekirkwood** [comment]
If you're handling it as part of that project then yes, absolutely. 

Closing...

**Comment by daniellekirkwood** [comment]
FYI @kittykat & @niquewoodhouse that there are 2 other issues directly relating to this behaviour: 

https://github.com/vector-im/element-android/issues/3852
https://github.com/vector-im/element-android/issues/5527

Should they also both be closed as "won't fix" as we're removing this behaviour?
