### ISSUE TITLE
Soft Logout when `LoginMode` is `SSOAndPassword` results in an empty space where a login UI component should be displayed.

### ISSUE THREAD

**Issue by langleyd** [vector-im/element-android#5192]
Soft Logout when `LoginMode` is `SSOAndPassword` results in an empty space where a login UI component should be displayed.

This is how it is displayed to the user:
<img src="https://user-images.githubusercontent.com/6135282/153198291-0de24961-911f-4e9b-9620-3b09ba80e2aa.png" width=300/>

Looks like it's [not implemented](https://github.com/vector-im/element-android/blob/develop/vector/src/main/java/im/vector/app/features/signout/soft/SoftLogoutController.kt#L125).

**Comment by ouchadam** [comment]
what should be showing in the gap? (I don't think I've seen this screen in action...)

**Comment by langleyd** [comment]
@ouchadam In some situations the server will log the user out with a 401 but will deem it not severe enough to force them to clear their data, this is called a soft logout(hard clears the data).

The gap should give user the ability re-authenticate. So if the `LoginMode.Password` it shows the `LoginPassFormItem` which displays a password and login button. If the `LoginMode.Sso` it renders a button thats starts the SSO flow.

It currently renders nothing for `LoginMode.SsoAndPassword`.

**Comment by ouchadam** [comment]
thanks for explaining :+1:

**Comment by bmarty** [comment]
Sorry, I was not aware that the issue had been created. I will close in favor of #5311 which contains more details about what we can do in this case.

Note for myself: filter using the issue label before creating a new issue
