### ISSUE TITLE
[Feature] Audioplayer

### ISSUE THREAD

**Issue by DoM1niC** [vector-im/element-android#5194]
#### What would you like to do?
A own Audioplayer to Playback Audios except Voice Messages.
#### Why would you like to do it?
- Because `.ogg` havn't Metadata from traditional Voice Messages, have to open with a external Media-player.
- MP3 / AAC based Audios could listen too.... 
- Player need a Slider to skip to part of the Track
#### How would you like to achieve it?
- I hope a Dev will see this and will implemented this because native Element-Web already have this feature.

_**btw I talked for a while with @ouchadam and he told me this needs to discuss internally with the Team**_

**Comment by kojid0** [comment]
Isn't this related to #2649?

**Comment by ouchadam** [comment]
thanks for raising! lets centralise the issue to #2525 (which has had it's priority upgraded to _wtf_)
