### ISSUE TITLE
Help! mention all in room by @?

### ISSUE THREAD

**Issue by FlyingHarman** [vector-im/element-android#5220]
### Your use case

may I using @all or ?

**Comment by DoM1niC** [comment]
> ### Your use case
> 
> may I using @ALL or ?
> ### Have you considered any alternatives?
> 
> _No response_
> ### Additional context
> 
> _No response_

@room is the correct one to announce and notice all member in the Room

**Comment by ouchadam** [comment]
We're also improving the `@room` autocomplete  https://github.com/vector-im/element-android/pull/5237 :tada:  
I'm going to close this issue in favour of https://github.com/vector-im/element-android/issues/5123
