### ISSUE TITLE
iOS created polls show, `Malformed event, cannot display` on Android.  Displays on Element Web.

### ISSUE THREAD

**Issue by scottwallacesh** [vector-im/element-android#5221]
### Steps to reproduce

1. User1 creates a poll using iOS.
2. User2 can see the poll in Element Web.
3. User2 receives, `Malformed event, cannot display` in Element Android

#### What did you expect?
I expected Element Android to render the poll correctly.

#### What happened instead?
I received, `Malformed event, cannot display` message.

### Your phone model

Google Pixel 4a

### Operating system version

Android 12 (CalyxOS v3.2.0)

### Application version and app store

Element Android 1.4.0, Matrix SDK 1.3.19, olm 3.2.10

### Homeserver

Synapse 1.52.0

### Will you send logs?

No

**Comment by scottwallacesh** [comment]
Incidentally, I just checked and I can see the old poll now in Element Android.

**Comment by Johennes** [comment]
Sounds like this issue was fixed. @scottwallacesh please reopen in case you still experience this.

**Comment by scottwallacesh** [comment]
Yes, sorry!

**Comment by Johennes** [comment]
No worries at all and thanks for reporting it in the first place. 🙂
