### ISSUE TITLE
Drop notification when messages are read on another device

### ISSUE THREAD

**Issue by jeschmidt** [vector-im/element-android#523]
I searched the database for duplicates before posting this but regardless, my apologies if it is duplicate.  I use multiple Matrix clients, one of which is Riot/Android and I just tried installing RiotX/Android.  The first thing I noticed is that Riot notifications will disappear when I read the messages on another device (like Riot/Desktop), but for RiotX they persist.  To be clear, the original Riot/Android behaviour is what I recommend.  Unread messages should trigger the notification, and when they are all marked as read (including via other devices) the notification should automatically clear itself.

**Comment by bmarty** [comment]
Yes, I agree with that.
The limit is that you can hear your phone ring for a notification and when you check it the notification is gone, which can be a bit disturbing I you don't realized it's because you've read the message on another client.

But anyway let's do this as it's done on Riot-Android

**Comment by hpdeifel** [comment]
It seems to work for some users:

![Screenshot_20200217-215301](https://user-images.githubusercontent.com/77743/74685900-3146ea80-51d0-11ea-841c-6a0c6478a76d.png)

**Comment by bmarty** [comment]
Fix by #4129 , closed manually since GitHub grammar is not clever enough to fully understand #4129 description :)

In Element Android 1.3.2
