### ISSUE TITLE
 Help! suddenly log out by administrator,and several times a day

### ISSUE THREAD

**Issue by FlyingHarman** [vector-im/element-android#5242]
### Steps to reproduce

but administrator did nothing,so help me...

### Outcome

hope it should be log in stable for a long time

### Will you send logs?

No

**Comment by ouchadam** [comment]
in order to help diagnose this we'll need some more information, sending a rageshake would be a great place to start

has the issue recently started happening, are you logged in on other clients, do they also get logged out?

**Comment by Florian14** [comment]
Closed as no more info has been given so far, do not hesitate to reopen it if it happens again
