### ISSUE TITLE
Latex broken

### ISSUE THREAD

**Issue by witchent** [vector-im/element-android#5252]
### Steps to reproduce

1. Activate latex in labs
2. Write latex code (wrapped in $ $ or $$ $$) either from Element Android or Element Web

#### What did you expect?
Element Android to render the latex code

#### What happened instead?
Observe the rendered latex code in Element Web, but the plain text (in a code block) rendered in Element Android

### Your phone model

Oneplus 6

### Operating system version

Android 11

### Application version and app store

Element Android debug latest nightly

### Homeserver

Synapse 1.52

### Will you send logs?

No

**Comment by ouchadam** [comment]
would it be possible to get screenshots of the working result in element web and broken output in element android? :pray:

**Comment by witchent** [comment]
Sure, my bad, wanted to add a picture but forgot to do so.
![Screenshot_20220217_113345](https://user-images.githubusercontent.com/13248566/154458296-2833b0e8-b26a-420d-a231-c8cac12bf46f.jpg)

The upper part is the message in Element Web, the lower part is the screenshot of Element Android.

**Comment by ouchadam** [comment]
perfect, thanks! and to clarify, what was the raw text input in this case?

**Comment by witchent** [comment]
$x^a$. The source text shows:
```
{
  "type": "m.room.message",
  "sender": "###",
  "content": {
    "org.matrix.msc1767.message": [
      {
        "body": "$x^a$",
        "mimetype": "text/plain"
      },
      {
        "body": "<span data-mx-maths=\"x^a\"><code>x^a</code></span>",
        "mimetype": "text/html"
      }
    ],
    "body": "$x^a$",
    "msgtype": "m.text",
    "format": "org.matrix.custom.html",
    "formatted_body": "<span data-mx-maths=\"x^a\"><code>x^a</code></span>"
  },
  "origin_server_ts": 1645093966879,
  "unsigned": {
    "age": 94,
    "transaction_id": "m1645093966796.114"
  },
  "event_id": "###",
  "room_id": "###"
}
```

Maybe it is also good to note that sending $x^a$ sends different events in Element Web as in Element Android, though both render fine in Web but don't render on Android

**Comment by witchent** [comment]
Oh wow, I was sure I activated threads after latex and thus even did a complete resync, but apparently killing Element and restarting it did the trick. Thanks a lot.
I will close the issue, but maybe this could be prevented somehow (indeed I am hoping that Latex support gets out of lab soon. I remember the blog post when Vector got renamed that math would be first class citizen)
