### ISSUE TITLE
Github Actions build cache usage

### ISSUE THREAD

**Issue by michaelkaye** [vector-im/element-android#5266]
The builds on GHA are fairly slow and I believe we can improve them by altering our use of the build cache. We are rebuilding the same code in a number of parallel builds, and I wonder if we could do better by having a daily run on develop to create a cache for read-only use by the PRs.

https://docs.gradle.org/current/userguide/build_cache_use_cases.html#share_results_between_ci_builds

I think it's possible that at the moment, all that happens is each JOB of each PR has their own cache (even if saved at the end of the build), is not going to be usefully completely re-used, as every related job has already started in parallel. So we would need to serialise some of the build to create a known-good cache, then have all the test jobs be dependencies from that. 

(this needs more investigation before just doing it; but it feels like it's worth an investigation, as the cache config hasn't been changed in general since the GHA were originally setup)

**Comment by michaelkaye** [comment]
I should be clear there's a separate build cache  to the cache of dependencies etc, we are re-using some of the dependency caches in a good way, so we'd need to be careful we don't affect any other benefits with it.

I was also wondering if this gradle-supplied action which offers "better" caching may also help here over and above the github-actions basic cache: 
https://github.com/gradle/gradle-build-action#caching

**Comment by michaelkaye** [comment]
Timing data for builds is now being funneled into a sqlite db on https://gha-timing.lab.element.dev/

More data can be collected by routing webhooks for workflow_job to `https://gha-timing.lab.element.dev/webhook/<repo-name>` with type application/json  - at the moment it just records run times for all jobs.

**Comment by ouchadam** [comment]
the build cache has been enabled with https://github.com/vector-im/element-android/pull/6788, we'll need to extract more cacheable modules to further reduce build times
