### ISSUE TITLE
[Spike] How simple is it to support room search

### ISSUE THREAD

**Issue by niquewoodhouse** [vector-im/element-android#5268]
At the moment, a user on iOS and web can search the content of a specific room.  It's likely to be a journey a user might look for, so is part of IA.  There doesn't seem to be a way to do that on Android. How easily can we add this?

**Comment by niquewoodhouse** [comment]
@fedrunov has investigated this and found that there is a search option in the room context menu for unencrypted rooms, but its not visible in the room details view.  

It seems on iOS the option to search a room is always visible whether its an encrypted or unencrypted room, but for encrypted rooms search doesn't work and we don't tell the user.

**Comment by Freundschaft** [comment]
So will there be room search available at some point for android or is it something thats not in scope?

**Comment by daniellekirkwood** [comment]
Yes, Search will be available. It's being tracked elsewhere on our backlog so I will be closing this issue in favour of that.
