### ISSUE TITLE
Exclude all build directories from git source control.

### ISSUE THREAD

**Issue by langleyd** [vector-im/element-android#5273]
Build artefacts like dex files can show in component directories like `matrix-sdk-android-rx/build/.transforms/`.

Can make a tweak to `.gitignore` to fix this.

**Comment by bmarty** [comment]
`matrix-sdk-android-rx` has been removed, and the .gitignore file it was containing, which ignores `/build` too This is maybe why you are seeing those files now. Can you just remove them on your clone?

**Comment by langleyd** [comment]
Yea you're dead right
