### ISSUE TITLE
Mobile FTUE: Password recovery (Android)

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-android#5284]
### Your use case

https://github.com/vector-im/element-meta/issues/135

**Comment by ouchadam** [comment]
might be worth splitting this task into two parts

- Support sign out all devices SDK + Settings flow
- FTUE forgot password flow

**Comment by ouchadam** [comment]
#6171 Allowing password supplied to reset password to be separate from the email  
#6191 Adding support for signing out all devices
