### ISSUE TITLE
Upgrade to material 1.5.0 (or 1.6.0)

### ISSUE THREAD

**Issue by bmarty** [vector-im/element-android#5291]
Dependabot does not upgrade this library, I do not know why.

If the root cause can be found it would be nice.

In the mean time we are still using `com.google.android.material:material:1.4.0`

And 1.5.0 is available (and also 1.6.0 but is it stable?) so we should upgrade manually.

Running a smoke test and the test allScreensTest is part of this work.

**Comment by ericdecanini** [comment]
1.6.0 is still in alpha02 (released Jan 2022). Upgrading to 1.5.0

**Comment by ericdecanini** [comment]
https://github.com/vector-im/element-android/pull/5392 raised to upgrade the dependency version.

I think a separate issue can be raised for the Material You upgrade itself
