### ISSUE TITLE
Add a feature flag to force usage of registration / login fallback

### ISSUE THREAD

**Issue by bmarty** [vector-im/element-android#5307]
To be able to test registration fallback and login fallback, we can introduce a feature flag `Force login fallback` in <del>`DebugFeaturesSettingsActivity`</del> `DebugPrivateSettingsFragment`, disabled by default and tested at:

- https://github.com/vector-im/element-android/blob/main/vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthVariant.kt#L127  (also can take the opportunity to replace `if` by `when`).
- https://github.com/vector-im/element-android/blob/main/vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthVariant.kt#L273

The related fun to check are `onRegistrationStageNotSupported` and `onLoginModeNotSupported`

**EDIT**: updated to point out to the correct screen. Sorry!

**Comment by ericdecanini** [comment]
@bmarty can we close this?
