### ISSUE TITLE
Update landing location after user joins a Space

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-android#5334]
At the moment, when a user joins a Space on Android, they go back to their previous view.

On iOS, users land in the home tab. This could be Explore space or room tab on Android.

**Comment by niquewoodhouse** [comment]
> On iOS, users land in the home tab. This could be Explore space or room tab on Android.

I'd vote for rooms tab on Android, explore space could work longer term but it lacks things like a search to find rooms/spaces.

At least with rooms tab we can assume with some small confidence, a space has some rooms (as the space creation flow strongly discourages people starting spaces with no rooms).

**Comment by niquewoodhouse** [comment]
Just had a look through the old designs and it turns out that was actually the intention for Android all along.

https://user-images.githubusercontent.com/1587166/155753549-aff00d7e-02e2-4ca2-b041-7d0e4dcf4685.mov

**Comment by kittykat** [comment]
Related: creating space #3948

**Comment by ericdecanini** [comment]
Fixed in 1.4.12
