### ISSUE TITLE
I would not have removed the highlight, but rather limit the width of the button to avoid the effect to be full width:

### ISSUE THREAD

**Issue by bmarty** [vector-im/element-android#5338]
I would not have removed the highlight, but rather limit the width of the button to avoid the effect to be full width:

<img width="476" alt="image" src="https://user-images.githubusercontent.com/3940906/153841315-5f98dc44-8360-434d-99a4-9a57b1a205c6.png">

Is it a request from the design team?

_Originally posted by @bmarty in https://github.com/vector-im/element-android/issues/5178#issuecomment-1038880313_

**Comment by bmarty** [comment]
I think we should revert the change from #5178 and limit the width of this button

**Comment by gaelledel** [comment]
This is a text button so no highlight is needed here

**Comment by Johennes** [comment]
Closing based on @gaelledel comment as it appears we'd like to not reconsider this for now.
