### ISSUE TITLE
Fix highlighting showing which Space is selected

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-android#5346]
On Android, the current Space is only highlighted with a green bar. Nique says that the designs show it as having a background highlighting as well.

This is done correctly on iOS.

### Tasks

- [x] @niquewoodhouse to attach link to figma/share design
- [ ] @fedrunov implement the design

**Comment by niquewoodhouse** [comment]
Here's the original design [light](https://www.figma.com/file/PhB0Bf05EdMpdI9rsSsQZ5/%5BExit-beta%5D-Spaces?node-id=129%3A48410), [dark](https://www.figma.com/file/PhB0Bf05EdMpdI9rsSsQZ5/%5BExit-beta%5D-Spaces?node-id=1628%3A128031)

**Comment by bmarty** [comment]
In EA 1.4.6
