### ISSUE TITLE
Track source of room open

### ISSUE THREAD

**Issue by fedrunov** [vector-im/element-android#5355]
Track user path to room screen with `ViewRoom` event and `trigger` field

ViewRoom map of use case to trigger

| Screen | Use case | Trigger |
| ------------- | ------------- | ------------- |
| CreateDirectRoomActivity | after user creates a DM from users list | MessageUser |
| IncomingVerificationRequestHandler | verification request | VerificationRequest |
| SearchFragment | navigate to event/message from search | MessageSearch |
| TimeLineFragmnet | handling a link in timeline | Timeline |
| PublicRoomsFragment | click on item in rooms global search | RoomDirectory |
| CreateRoomFragment | after room created | Created |
| RoomPreviewNoPreviewFragment | room preview | _RoomPreview_ (new) |
| RoomJoinRuleActivity | switch to replacement room when user change join rules | don't track |
| IncomingShareFragment | share from outside the app | _LinkShare_ |
| SpaceExploreActivity |  click on “open” button on room list item in a space explore | _ExploreRooms_ (new) |
| SpacePeopleActivity | click on a space member in space members list (from fab on space’s dm tab) | _SpaceMembers_ (new) |
| RoomListFragment | click on a room on Home screen | RoomList |

Also there is a bottom sheet with room preview from where user also can be navigated to Room, but this sheet is called in multiple places:

| Screen | Use case | Trigger |
| ------------- | ------------- | ------------- |
| HomeActivity | from parsed link  | _Permalink_ |
| SpaceExploreActivity | click on room in Space Explore |  _ExploreRooms_ |
| UserCodeActivity | on user code scanned | - |
| HomeActivity | from notification | _Notification_ |
| Timeline | click on not joined room’s link | _Timeline_ |
| RoomList | on suggested room click | - |

**Comment by kittykat** [comment]
"RoomList", is that room list from the rooms tab or from explore rooms?

**Comment by fedrunov** [comment]
RoomList is both Rooms and DMs on Home screen and also list of filtered rooms (accessed via filter button on home screen)
