### ISSUE TITLE
 Track user path to joining to room or space

### ISSUE THREAD

**Issue by fedrunov** [vector-im/element-android#5356]
Track user path to joining to room or space.

There is `JoinedRoom` event with `trigger` field

JoinedRoom map of use case to trigger

Rooms

| Screen | Use case | Trigger |
| ------------- | ------------- | ------------- |
| timeline | accept invite (DM?) + notification ? + upgrade retry  | Timeline |
| message composer | slash command  | _SlashCommand_ |
| room list | accept invite  | _Invite_ (new) |
| invite accepted | auto accept invites  | _Invite_ |
| notification | notification's accept button  | Notification |
| room preview screen | from global search  | _SearchRoomPreview_ (new) |
| room list item | by button in room item on global search  | RoomDirectory |
| space explore item | by button in room item on space explore  | _ExploreRooms_ (new) |

Spaces

| Screen | Use case | Trigger |
| ------------- | ------------- | ------------- |
| message composer | slash command  | _don't track_ |
| space directory/explore rooms | subspace | _SpaceHeirarchy_ |
| space invite item | invite item in sidebar  | _Invite_ |
| space preview screen | seems to be unused for now | don't track |

Preview Dialog issue:

for both Space and Room we have dialog with some information about it and "join button". This dialog is called from different places:

| Screen | Use case | Trigger |
| ------------- | ------------- | ------------- |
| HomeActivity | from parsed link  | _SharedLink_ (new) |
| SpaceExploreActivity | click on room in Space Explore | _ExploreRooms_ |
| UserCodeActivity | on user code scanned | - |
| HomeActivity | from notification | _Notification_ |
| Timeline | click on not joined room’s link | _Timeline_ |
| RoomList | on suggested room click | _RoomList_ |

**Comment by kittykat** [comment]
I've updated the issue above, some questions:

Can we track "room preview screen" from the point before this?

By "space directory", do you mean the Explore Rooms view?

UserCodeActivity -> is that QR code?

**Comment by fedrunov** [comment]
- What do you mean by "from the point before this"? When Preview screen is shown?
- `SpaceDirectory` is Explore Rooms, yes
- yes, UserCodeActivity is QR code
