### ISSUE TITLE
Integration test speedup: passwordConverter

### ISSUE THREAD

**Issue by michaelkaye** [vector-im/element-android#5362]
```
  passwordConverter_badIteration_ok in 705.075s
  passwordConverter_badPassword_ok in 625.808s
  passwordConverter_badSalt_ok in 698.015s
  passwordConverter_crossPlatform_ok in 356.064s
  passwordConverter_ok in 677.258s
  passwordConverter_progress_ok in 357.721s
```

Looking at these tests from the outside they seem to not be doing that much; Can we can improve the tests to not take a combined total of about an hour to execute.

**Comment by michaelkaye** [comment]
this is `matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/internal/crypto/keysbackup/KeysBackupPasswordTest.kt`, and contributes to at least 50% of the test run time.

**Comment by bmarty** [comment]
I think we can just @Ignore those tests
