### ISSUE TITLE
Threads: Update property stable values

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-android#5364]
### Your use case

[Filters property stable values are changing to “related_by_rel_type”](https://github.com/matrix-org/matrix-doc/pull/3440/commits/362e661fa69412c51a794530bb974e4efb975af6)

**Comment by ariskotsomitopoulos** [comment]
I observe that `io.element.relation_senders` and ` io.element.relation_types` will remain the same. So no action should be done. The change should be applied when the clients integrate `m.thread` instead of `io.element.thread`
