### ISSUE TITLE
Markdown should not be rendered in code snippets

### ISSUE THREAD

**Issue by benthetechguy** [vector-im/element-android#5370]
### Steps to reproduce

1. Post or view message containing potential markdown in a code snippet.
Example: \`apt purge \*nvidia*`
2. Markdown is rendered inside the code snippet when it shouldn't be.

#### What did you expect?
The markdown should not be rendered. The message should look like `apt purge *nvidia*`.

#### What happened instead?
The markdown was rendered and the message looked like this:
![Screenshot_20220227-010526](https://user-images.githubusercontent.com/29379327/155870698-8d9061d6-1d84-4fd7-b59b-bc8e0e50d91b.jpg)

### Your phone model

OnePlus Nord N100

### Operating system version

Android 11.0.4

### Application version and app store

Element version 1.4.0, olm version 3.2.10, from F-Droid

### Homeserver

fairydust.space

### Will you send logs?

No

**Comment by ouchadam** [comment]
fixed by #6357 and will be available in 1.4.26
