### ISSUE TITLE
CI build failure : could not resolve com.likethesalad.android:stem-plugin:2.0.0

### ISSUE THREAD

**Issue by michaelkaye** [vector-im/element-android#5372]
https://github.com/vector-im/element-android/runs/5352169356?check_suite_focus=true#step:4:13

Variant 'runtimeElements' capability com.likethesalad.android:stem-plugin:2.0.0 declares a runtime of a library, packaged as a jar, and its dependencies declared externally:
 - Incompatible because this component declares a component compatible with Java 11 and the consumer needed a component compatible with Java 8

The build environment has changed - we were restoring a gradle cache from linux and are now using one from macos - so it's possible that we're no-longer serving this from disk - but it feels like an issue that the build is unable to source it's dependencies from scratch.

**Comment by michaelkaye** [comment]
Currently unable to replicate this locally; looking into it further.

**Comment by ouchadam** [comment]
could this be because the action isn't including the JDK11?

**Comment by michaelkaye** [comment]
Yup, forcing java 11 seemed to work; looks like macos defaults to 8 for some reason. Weird.
