### ISSUE TITLE
Unfriendly message in display name error dialog

### ISSUE THREAD

**Issue by ouchadam** [vector-im/element-android#5418]
#### What would you like to do?
Avoid printing raw exceptions as user facing messages

#### Why would you like to do it?
To improve the message readability

#### How would you like to achieve it?

By reusing the error dialog which translates exceptions to human readable messages

### Additional context

![Screenshot_20220303_155653](https://user-images.githubusercontent.com/1848238/156604682-fa68eb86-1147-4367-8afe-8b05ff313585.png)

**Comment by bmarty** [comment]
Fixed in 1.4.4. Thanks!
