### ISSUE TITLE
QR code view broken when no display name is set

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-android#5424]
### Steps to reproduce

1. Unset your display name (in Settings -> General)
2. Left panel -> miniature QR code next to your name

#### What did you expect?
Avatar does not cover MXID
![Screenshot_20220304-131348.png](https://user-images.githubusercontent.com/51663/156773120-62d7bd64-479b-4e2b-a5cc-c14ef87b3e0a.png)

#### What happened instead?
Avatar covers MXID
![Screenshot_20220304-132618.png](https://user-images.githubusercontent.com/51663/156773147-072642f6-13f8-44c3-a0e4-184d9a8a27de.png)

### Your phone model

iPhone 11

### Operating system version

Android 11

### Application version and app store

Playstore Beta

**Comment by ouchadam** [comment]
Marked as uncommon due to needing to have no display name set, however I'm tempted to increase the severity as the invitation flow is a pretty important to us, might also fall under FTUE? cc @daniellekirkwood

**Comment by daniellekirkwood** [comment]
Thanks @ouchadam

I'm going to upgrade this to Major as it's a visual defect and severely impacts the user experience in D1 (for both the sharer of the code and the scanner). That makes it a P3 issue but maybe it's small enough that could be fixed very quickly...

**Comment by bmarty** [comment]
Fixed in #7092 (Element Android 1.4.38)
