### ISSUE TITLE
Thread list ordering, order by most recent event: Fast follow

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-android#5430]
### Your use case

For the MVP we order the thread list by the time/date the root message was received however the design is to order this list by the latest event (so the list changes it's order based on activity with most recent activity at the top).

This improvement will be made as a part of the fast follow work as to do so accurately needs server side support: https://github.com/vector-im/element-meta/issues/152

Web issue: https://github.com/vector-im/element-web/issues/20654
iOS issue: https://github.com/vector-im/element-ios/issues/5753

**Comment by novocaine** [comment]
Closing in favour of https://github.com/vector-im/element-android/issues/5819
