### ISSUE TITLE
Crashes when trying to share a screenshot to element while viewing a message context menu

### ISSUE THREAD

**Issue by BobIsMyManager** [vector-im/element-android#5444]
### Steps to reproduce

1. Open element android
2. Enter a room
3. View a message context menu by holding down on a menu
4. Take a screnshot by pressing power + volume down
5. Press "share"
6. Select elememt
7. Experience crash

#### What did you expect?
For element to show a list of rooms to share to

#### What happened instead?
The app crashed

### Your phone model

Remdi Note 9 Pro

### Operating system version

Android 11

### Application version and app store

Element version 1.4.2, olm version 3.2.10, from f-droid

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by ouchadam** [comment]
this might be device/OS specific, the app seems to work as expected for me

| GIF | 
| --- |
|![after-share-image](https://user-images.githubusercontent.com/1848238/159341399-b8e20cd7-b51a-469e-b7e3-40900e0d0a7a.gif)

**Comment by BobIsMyManager** [comment]
Yep, this seems to be patched after updating to 1.4.4

**Comment by ouchadam** [comment]
great to hear! thanks for updating the issue :raised_hands:
