### ISSUE TITLE
Messages missing/skipped when opening a room at a permalink

### ISSUE THREAD

**Issue by SpiritCroc** [vector-im/element-android#5448]
### Steps to reproduce

1. Permalink the latest message in a room
2. Go back to room list
3. Receive lots of new messages in that room (e.g. 100)
4. Open the room from the permalink

#### What did you expect?

All messages should show

#### What happened instead?

About 50 messages after/around the permalink were missing (sometimes event the permalinked message).
When opening the room at the bottom, all messages show.
Until new messages come in or you do a new initial sync, the same permalink will lead to the same messages missing.

Note: I think I'm actually close to finding a fix this issue, will hopefully create a PR later today.

Possibly related issue: https://github.com/vector-im/element-android/issues/5092
![Screenshot_20220202-115346_Element_dbg](https://user-images.githubusercontent.com/12481742/152141038-277dee43-fb75-4e36-bf44-20cf6edbba02.png)

### Operating system version

Android 11

### Application version and app store

self-compiled v1.4.2 (was happening since v1.3.16; v1.3.12 was fine)

### Homeserver

Synapse 1.53.0

### Will you send logs?

No

**Comment by bmarty** [comment]
Fixed in 1.4.6. Thanks @SpiritCroc !
