### ISSUE TITLE
Inform labs threads users that their old threads have moved to the main timeline

### ISSUE THREAD

**Issue by novocaine** [vector-im/element-android#5451]
When we update the client to consider m.thread as the threads prefix in https://github.com/vector-im/element-android/issues/5364, the user will see their old threads move into the main timeline.

We need to inform users that have labs enabled in threads that this has occurred.

**Comment by janogarcia** [comment]
@ariskotsomitopoulos I'm attaching the mockup and reassigning it to you.

**Source**
[Threads — Labs phasing out notice](https://www.figma.com/file/T309ztx0sNyOOK6NKVLHsK/Threads?node-id=3942%3A317132)
