### ISSUE TITLE
Prototype new tab layout for user testing

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-android#5460]
Prototype new layout for testing based on findings from https://github.com/vector-im/element-meta/issues/166

## Designs

https://www.figma.com/file/Hw4gjP3pknMZUir8jQqmWH/%5BMobile%5D-IA-early-proposals?node-id=348%3A33505

**Comment by fedrunov** [comment]
@niquewoodhouse should we close this, or we will use this for second iteration of prototype?

**Comment by niquewoodhouse** [comment]
@fedrunov at this stage, I'm not sure but will work out today.
