### ISSUE TITLE
Notifications don't clear on Android when read elsewhere

### ISSUE THREAD

**Issue by BloodyIron** [vector-im/element-android#5464]
### Steps to reproduce

1. Receive notification across many devices
2. Read notification (and/or reply) anywhere, be it with another android, desktop, or whatever device
3. Notification clears on desktop, but not any android device (except if it's the android device reading/replying, but other android devices still have notification)

#### What did you expect?
I expect the notifications to clear on all android devices when read

#### What happened instead?
The notifications never clear or get marked read themselves

### Your phone model

This is any android device, but LG v20 and Samsung Galaxy Tab S4

### Operating system version

Android 11 & 10

### Application version and app store

1.4.2 from Google Play

### Homeserver

Public matrix.org server

### Will you send logs?

No

**Comment by BloodyIron** [comment]
Yeah so the notifications don't clear on any of my android devices, or my GF's, or anything. I have Element installed on multiple Android devices, and they never clear in the background. However the desktop version of Android does clear notifications when they are read.

**Comment by waclaw66** [comment]
I've noticed that as well recently. I think it worked properly some time ago.
Notification should dissapear when a message is read on another device/web.

**Comment by waclaw66** [comment]
I tested all versions since 1.3.6 and they all do this. It doesn't help to do initial sync or clear cache either. The only workaround that helps (at least for a while) is to logout a login again.

**Comment by BloodyIron** [comment]
Yeah there sure have been a lot of notification regressions over the last few years :/ some getting fixed, others not...

**Comment by speatzle** [comment]
This is also affecting me, very annoying to read a message on desktop and have to manually mark it read on 2 phones.

**Comment by BloodyIron** [comment]
This seems to be happening every time, without exception, on all android devices.

**Comment by NANASHI0X74** [comment]
affects me as well

**Comment by marius** [comment]
This might be the same as https://github.com/vector-im/element-android/issues/4862

**Comment by ouchadam** [comment]
thanks for raising! going to centralise into #4862 to avoid duplicated issues

worth noting that I've also seen this and going into the room settings and toggling the notification settings from none to all messages sometimes helps (have upgraded #4862 's occurrence)
