### ISSUE TITLE
Room name is displayed above the room avatar

### ISSUE THREAD

**Issue by bmarty** [vector-im/element-android#5468]
Only on un-encreypted room.

- Open an unencrypted room
- Observe the overlap of room name above room avatar

<img width="433" alt="image" src="https://user-images.githubusercontent.com/3940906/157408331-e93ebb07-fae3-4b78-acbf-96f4215e6319.png">

There is probably a constraint which applies on a View which is displayed only for e2e room (the shield?)

This is a regression

**Comment by ouchadam** [comment]
fixed in 1.4.4
