### ISSUE TITLE
Active space changes randomly

### ISSUE THREAD

**Issue by rda0** [vector-im/element-android#5476]
### Steps to reproduce

The active space changes randomly, probably by opening the app via notifications from certain rooms. I have set my Home to show all rooms. I only want to use the Home space on my Android phone, so I need to switch the active space back to Home manually each time I open the app.

This currently makes the UX not very nice because of #3830

#### What did you expect?

Space is not changed without my request.

#### What happened instead?

Space seems to automatically change when opening a room via notification.

### Your phone model

Samsung Galaxy S9

### Operating system version

Andoid 10

### Application version and app store

1.4.2

### Homeserver

1.53.0

### Will you send logs?

No

**Comment by ASoTNetworks** [comment]
I have the same issue too. If this is by design I would like to see an option to disable this.

**Comment by ouchadam** [comment]
thanks for raising! I'm going to close in favour of using #5180 which has already been pulled into a team board (unless there's another cause for the switching :thinking: )
