### ISSUE TITLE
Drop "invite to room" option from the Space invite

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-android#5477]
### Steps to reproduce

1. In the left panel, for a Space where you are Admin
2. ⋮-> List members
3. Fab to add people

#### What did you expect?
To go straight to "Invite users" view

#### What happened instead?
See an option to invite to… "Just to this room"? Which doesn't make sense given that I'm inviting to a Space
![Screenshot_20220308-164013](https://user-images.githubusercontent.com/51663/157459400-6d7c7fc7-4a8e-4350-ae31-c8b66e18b92f.png)

### Application version and app store

Beta from Playstore

### Will you send logs?

No

**Comment by fedrunov** [comment]
can't reproduce. @kittykat could you please revalidate?

**Comment by kittykat** [comment]
Closing as I can't reproduce either any more
