### ISSUE TITLE
Presence indicator centered over profile photo

### ISSUE THREAD

**Issue by thefirstofthe300** [vector-im/element-android#5489]
### Steps to reproduce

![markup_89 (1)](https://user-images.githubusercontent.com/3161330/157545222-ca0b7339-9199-4f82-919a-d1dd7e8b7db4.png)

The presence indicator is covering up the profile photo.

#### What did you expect?
Presence indicator should be located in the bottom right.

### Your phone model

Pixel 6 Pro

### Operating system version

12

### Application version and app store

Element v1.4.4

### Homeserver

Synapse 1.53

### Will you send logs?

No

**Comment by binarydad** [comment]
Same here, multiple android versions.

**Comment by notramo** [comment]
Only in 1.4.4. In 1.4.2 it worked fine.

**Comment by notramo** [comment]
I noticed that when the presence indicator is centered, the encryption indicator shield is displayed in the bottom right corner of the avatar, where the presence dot should be.
![image](https://user-images.githubusercontent.com/26059643/159161262-882be8eb-55f8-4528-bc50-e45860af57b1.png)
However, it didn't show up immediately, only after a few minutes of using it, and cache reloads. Possibly related with #5584
