### ISSUE TITLE
Turn on Threads for all users (out of labs)

### ISSUE THREAD

**Issue by novocaine** [vector-im/element-android#5503]
Make the threads feature available for all users.

Depends on https://github.com/vector-im/element-meta/issues/187

---

We aim to release Threads on 20 December, we will do so by: 
- completing testing before the RC and during the RC period (both team, internal, and community)
- defaulting the labs flag to on for users 

Once released, we should remove the labs flag with at least one cycle between 20 December and the removal of the switch in product.

**Comment by ariskotsomitopoulos** [comment]
Automatically enabling threads in Android will require an extra implementation to invoke an initial sync after the update (with threads enabled by default)

**Comment by janogarcia** [comment]
@novocaine After internal discussion, it was decided not to provide a user setting to disable threads (it’s not entirely replacing an existing feature, it can lead to degraded experience for everyone as conversations get split between the thread and main timeline, etc.).
