### ISSUE TITLE
Formatting should not work in code blocks

### ISSUE THREAD

**Issue by timokoesters** [vector-im/element-android#5512]
### Steps to reproduce

Send this message from any client and view it with element android:
```
`aaaa*bbbb* cccc* dddd *eeee`
```

### Outcome

Instead of showing the raw characters inside the inline code block, it renders bbbb as cursive and removes the surrounding stars

### Application version and app store

1.4.2

### Homeserver

-

### Will you send logs?

No

**Comment by ouchadam** [comment]
fixed by #6357 and will be available in 1.4.26
