### ISSUE TITLE
Read receipt in wrong order

### ISSUE THREAD

**Issue by Claire1817** [vector-im/element-android#5514]
### Steps to reproduce

Open a conversation and hide states events.
The read receipt are in a wrong order.
Example found:
|Part 1|Part 2|
|-|-|
![element3](https://user-images.githubusercontent.com/15031750/157909662-43fb70bb-269f-4e8e-8f3c-39cf114e83b9.png)|![element](https://user-images.githubusercontent.com/15031750/157910384-bb4f96e6-5565-4c4b-b8cb-a654c6c39f17.png)|

 
**Edit** adding a table for readability

### Outcome

The read receipts are in a wrong order. When some states events are hidden from the timeline, read receipts of the events are aggregated with the ones of the last message in the wrong order.

### Will you send logs?

No

**Comment by bmarty** [comment]
I do not see any problem on example 1 and 2. On example 3 there is a pb for the first item.

Is it correct?

**Comment by Claire1817** [comment]
the three screens comes from the same list. 
We can see the problem on the second and third picture.

**Comment by ericdecanini** [comment]
@Claire1817 can we close this issue?
