### ISSUE TITLE
 Transition away from reply fallbacks (MSC3676)

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-android#5533]
#### What would you like to do?

Make the Android client display a reply tile for an event, even if that event does not hold the reply fallback in the `formatted_body`

#### Why would you like to do it?

[Threads backwards compatibility](https://github.com/matrix-org/matrix-spec-proposals/blob/gsouquet/threading-via-relations/proposals/3440-threading-via-relations.md#backwards-compatibility) requires it

#### How would you like to achieve it?

By supporting [MSC3676](https://github.com/matrix-org/matrix-spec-proposals/pull/3676)

**Comment by ouchadam** [comment]
@gsouquet the issue mentions iOS but I'm assuming it's for both android and iOS?

**Comment by ouchadam** [comment]
thought that might be the case :smile:  thanks for confirming!
