### ISSUE TITLE
Deactivating account not possible (loop)

### ISSUE THREAD

**Issue by robovoice1** [vector-im/element-android#5541]
### Steps to reproduce

1. Tried to deactivate my existing account on matrix.org
2. go to settings,general, deactivate account
3. result is pic1
![Screenshot_20220315-133612](https://user-images.githubusercontent.com/92784377/158380144-a1da23e6-2df4-434d-b3f1-cca3f91a9428.png)
4. After tapping deactivate
5. and entering my password
![Screenshot_20220315-133630](https://user-images.githubusercontent.com/92784377/158380587-efa0f1a5-9214-435d-9e60-e9f31cc70b8c.png)

6. user gets back to step  3 
7. On a new app login account still exists

#### What did you expect?
Deactivated account 

#### What happened instead?
A perfect loop described in reproducing this

### Your phone model

Pixel 6 pro 256 gb

### Operating system version

Android 12 GrapheneOS (latest beta channel release)

### Application version and app store

1.4.4 Fdroid

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by daniellekirkwood** [comment]
This is a defect that should be fixed, it does not fall into the definition of WTF so I'm removing it from that project board. Thanks!

**Comment by ariskotsomitopoulos** [comment]
I investigated the issue, deactivation seems to work fine.  It seems like the loader was not working, so the user couldn't understand that he had to wait a bit more to the screen. Deactivation needs a couple of seconds. [PR](https://github.com/vector-im/element-android/pull/5721) fixes that
