### ISSUE TITLE
Unable to record a voice message

### ISSUE THREAD

**Issue by ouchadam** [vector-im/element-android#5543]
Reported in #element-android

### Steps to reproduce

1. Attempt to send a voice recording
2. An error is displayed 

Logs suggest a native crash, possibly due to a format or usage incompatibility with the device

#### What did you expect?
To be able to record a voice message

#### What happened instead?
![image](https://user-images.githubusercontent.com/1848238/158388981-3aead766-3360-4c02-b9cd-f3f5e05b81d2.png)

### Your phone model

Honor 9A

### Operating system version

10

### Application version and app store

1.4.2

### Will you send logs?

Yes

**Comment by 532910** [comment]
https://github.com/vector-im/element-android/issues/3904

**Comment by ouchadam** [comment]
thanks for linking, will close this in favour of #3904
