### ISSUE TITLE
App not fully translated to german (english sentences in german app selection)

### ISSUE THREAD

**Issue by robovoice1** [vector-im/element-android#5549]
### Steps to reproduce

1. Start the element android app with german ui
2. swipe to the left 4 times
3. Result is pic1

![Screenshot_20220315-174444](https://user-images.githubusercontent.com/92784377/158430140-6f5a997e-c345-497d-84e7-3613ab6e66d7.png)

4. Some english sentences with german app settings

#### What did you expect?
Fully translated app with selected german app ui

#### What happened instead?
See pic please (mixed de and en page)

Maybe these english strings are not released to translate yet?

### Your phone model

Google Pixel 6 pro

### Operating system version

Android 12 Graphene Os (latest beta)

### Application version and app store

1.4.4 Fdroid

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by bmarty** [comment]
This string is new, and so not translated yet.

You can help translating the project into German here: https://translate.element.io/projects/element-android/element-app/de/

Please note that new strings will be available only after a sync between the project and Weblate.
