### ISSUE TITLE
Thread summary is not displayed on redacted root messages

### ISSUE THREAD

**Issue by frakic** [vector-im/element-android#5568]
### Steps to reproduce

1. Where are you starting? What can you see?
 -I'm in a room/DM with some threads
2. What do you click?
 -I delete the root message of a thread
3. More steps…
 -I can't see the thread summary

#### What did you expect?
I expected the "Message deleted" placeholder to have the thread summary underneath it
#### What happened instead?
I can only see the placeholder in the timeline and there's no thread summary

### Your phone model

Samsung Galaxy A40

### Operating system version

Android 11

### Application version and app store

1.4.6-dev [40104060] (G-b6874) feature/aris/thread_live_thread_list

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by ariskotsomitopoulos** [comment]
It is already fixed in the latest android version
