### ISSUE TITLE
[MergedRoomCreationItem] DM: RoomDescriptionText use the roomName instead of memberName

### ISSUE THREAD

**Issue by Claire1817** [vector-im/element-android#5570]
### Steps to reproduce

Create a DM with someone and update the name of the room.
The room description text will use the room name instead of the other member name.
![Screenshot_20220317-154827_Element](https://user-images.githubusercontent.com/15031750/158830694-697ead65-a69f-4616-8338-3e0c5236f9fb.jpg)

### Outcome

We should use data.memberName instead roomSummary?.displayName

### Will you send logs?

No

**Comment by giomfo** [comment]
@Claire1817 we will revert PR#5705 because of the new issue #6032 

This issue will stay open. We need design inputs to handle correctly the wording in a DM for which a name has been define
