### ISSUE TITLE
Encryption shield not visible in 1.4.4

### ISSUE THREAD

**Issue by notramo** [vector-im/element-android#5584]
### Steps to reproduce

1. Install 1.4.4
2. Open an encrypted chat
3. No shield is visible in header

#### What did you expect?
Shield shown in header, indicating verification status.

In 1.4.2 it worked fine, but 1.4.4 messed it up. Probably related #5584 

### Application version and app store

since 1.4.4

### Will you send logs?

No

**Comment by ouchadam** [comment]
thanks for raising! is there a particular case where the shield doesn't show up? I'm seeing slightly different behaviour locally where the shield shows but it never becomes trusted (with the green badge)

**Comment by notramo** [comment]
Let's see if it still exists after #5585 is fixed in the next F-Droid build.

**Comment by lindhe** [comment]
> Probably related #5584

By absolute necessity related. ;)
