### ISSUE TITLE
Notification Tab

### ISSUE THREAD

**Issue by trymeouteh** [vector-im/element-android#5590]
### Your use case

On the desktop client you can click the notification bell button in the top right and see all the notification of messages directed to you and be able to click on them and view the message in the section of the chat history. Please add this to mobile clients.

**Comment by ouchadam** [comment]
hi @trymeouteh , we have a labs option for `dedicated tab for unread notifications`, would this suit your usecase?

**Comment by trymeouteh** [comment]
How do I access this labs option on Android?

**Comment by ouchadam** [comment]
the toggle is available in `Settings -> Labs`

| GIF |
| --- |
|![labs-notification-tab](https://user-images.githubusercontent.com/1848238/159450627-de31ed97-a53b-4f11-ada3-ae485d0a71fc.gif)

**Comment by AnisTaluqdar** [comment]
#3822 this way is best for mobile client

**Comment by mcg-matrix** [comment]
> the toggle is available in `Settings -> Labs`

I don't have that switch "Add a dedicated tab for unread notifications" in Element F-Droid 1.5.7. The second item in the "Labs" list (between "Enable swipe ..." and "Enable LaTeX ...") is instead called "MSC3061: ...". Has it moved somewhere else?

**Comment by jmartinesp** [comment]
With the new app layout, there is now an 'Unread' tab that you can enable by doing:

1. On the home screen, tap on the overflow menu (the three dots).
2. Select 'Layout Preferences'.
3. Enable 'show filters'.

If you think this does not match your needs, please re-open the issue.
