### ISSUE TITLE
Calls unable to be used.

### ISSUE THREAD

**Issue by Flam3z** [vector-im/element-android#5591]
### Steps to reproduce

1. Call any user in a DM
2. Ask if they are able to see the prompt of you calling.

#### What did you expect?
To be able to call a user without any major bugs or hiccups.
#### What happened instead?
I was unable to answer the call as it would quickly close out of the window and force me back into the timeline and the other user was unable to even see me calling them all together on their pc or mobile device.

### Your phone model

Samsung S10

### Operating system version

Android 12

### Application version and app store

1.4.4 F-droid | SDK: 1.4.4 (9e8067dd) | olm: 3.2.10

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by ouchadam** [comment]
thanks for raising :+1:  have you noticed this issue on older versions? 

also, are the people you're calling also using fdroid builds or custom homeservers?

**Comment by Flam3z** [comment]
No, this is the first time I ever seen this bug, the user i tried calling uses element desktop with matrix.org homeserver.

**Comment by ouchadam** [comment]
:+1: thanks for the information, will see if I can reproduce using the desktop/android combination

**Comment by uranuspucksaxophone** [comment]
This issue seems to be very closely related (if not the same) to #1841, and yes, if you are wondering, this bug (and #1841) is reproducible by me in the latest F-Droid build. And yes, I was using the default matrix.org homeserver.

**Comment by ouchadam** [comment]
thanks for the report, to double check, does this only happen when answering calls?

if so it seems like this crash may be our cause https://github.com/vector-im/element-android/issues/5421

**Comment by uranuspucksaxophone** [comment]
> thanks for the report, to double check, does this only happen when answering calls?
> 
> if so it seems like this crash may be our cause #5421

Well, I don't know if element crashes, the only thing i observed was that in order to pick up the call the other user had to open element, go to the room, and only then would it be possible to pick up the call. And no, battery optimization or permissions were not the cause. After the F-Droid build is updated, I will try to test this again. Still though, even if this is fixed, I wouldn't use the F-Droid version, too slow updates and very unrealiable.
