### ISSUE TITLE
Users' presence indicator (green bullet) is centered on users avatar

### ISSUE THREAD

**Issue by SPiRiT369** [vector-im/element-android#5608]
### Steps to reproduce

Inside Direct Messages, the user avatar has a green/grey circle at the center, indicating whether the user is online or offline. (when presence is enabled)
Obviously, this is very ugly and should be positioned at the corner :)
I'm just guessing that it was caused by the change of moving the typing indicator to the bottom.

![image](https://user-images.githubusercontent.com/63514368/159582053-98f7cfbd-0c77-459b-a633-8738415bd350.png)

### Outcome

Improve avatar visibility.

### Application version and app store

Latest official stable version

### Will you send logs?

No

**Comment by DoM1niC** [comment]
is fixed for with the last commits from develop branch 👍🏻

**Comment by SPiRiT369** [comment]
@DoM1niC - Cool, thanks! 👏
Should I close this issue?

**Comment by DoM1niC** [comment]
> @DoM1niC - Cool, thanks! 👏
> Should I close this issue?

You could this is already fixed and since a new Release Build its solved ☺️
