### ISSUE TITLE
Element Android should emphasize a "Sign in with Matrix ID" flow over entering a HS URL manually

### ISSUE THREAD

**Issue by dkasak** [vector-im/element-android#5615]
### Your use case

The current login flow incorrectly emphasizes the `Other` option over the `Sign in with Matrix ID` option. I want to argue that login via Matrix ID (using well-known) is the correct option for an ordinary, non-power user on a homeserver other than matrix.org.

As a homeserver operator, I want to be able to give my users a username and a password and have them be able to log in without any further technical support. Users are used to usernames and passwords as the dominant login paradigm and would therefore have no problem with this.

On the other hand, the current `Other` option forces them to remember a username, a password *and* an arcane URL *in addition*. This is suboptimal, to say the least, since users have no idea what a homeserver URL is nor do they ever encounter it in normal usage... except when trying to log in from Element Android. Further aggravating the situation is the fact that the URL may change from time to time, since a server operator can move the actual homeserver to another domain via well-known delegation.

The option of manually entering the homeserver URL should also be kept, but should be treated as an advanced option to be used only for exceptional situation, such as testing and homeservers without well-known support. 

It should also be noted that Element Web properly implements the sign-in-via-MXID flow (see https://github.com/vector-im/element-web/issues/6826 for a discussion of this in the context of Element Web). So in the interest of platform uniformity, Element Android should be brought to parity.

**Comment by dkasak** [comment]
Also appending some insightful comments from Thib on the matter:

> Entering your email and leaving it up to your mail client to figure what the probably settings are is fairly common these days.
> 
> Most of the time you don't need to enter your SMTP or IMAP server (and username) manually, unless the admins set up something exotic.
> 
> A MxID is very similar to an email address :)
>
> Plus when you enter your homeserver manually you don't know if you need to prefix it with http:// or not, some people might confuse it with a website and preprend it with www.… there are many things a user can trip on

**Comment by daniellekirkwood** [comment]
Hopefully this will be solved as a part of [this](https://github.com/vector-im/element-meta/issues/134#issuecomment-1125116453) but we'll keep it open and check back in with you during testing to make sure :)

**Comment by daniellekirkwood** [comment]
The sign-in flow allows users to enter their entire MXID and updates the HS automatically. 

@dkasak Give it a try. I'm going to close this issue but feel free to reopen it if there's something we missed in your request :)
