### ISSUE TITLE
Sync request parsing takes a long time (can be more than 30s)

### ISSUE THREAD

**Issue by MadLittleMods** [vector-im/element-android#5621]
### Steps to reproduce

 1. Under **Settings** -> **Advanced Settings** -> enable **Developer Mode**
 1. And enable **Show debug info on screen**
 1. Open Element after some time has passed and activity has occurred
 1. Notice how the `/sync` network request is actually pretty fast but the parsing rooms and `toDevices` step takes a considerable amount longer

#### What did you expect?

I would expect the network to be the bigger bottleneck in seeing new messages over parsing JSON locally.

It just feels like there is some optimization to be had here. [GTA load times style](https://nee.lv/2021/02/28/How-I-cut-GTA-Online-loading-times-by-70/)

#### What happened instead?

Network `/sync` request is fast but the parsing step is slow.

![](https://user-images.githubusercontent.com/558581/159310680-c1940ef1-231e-4972-884a-4b50c4caa664.png)

### Your phone model

Pixel 4a

### Operating system version

Android 12

### Application version and app store

Element 1.4.4, olm version 3.2.10

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by bmarty** [comment]
I agree, thanks fro creating the issue.

The time for the server to build the response is long too, but the time to parse and handle the response is longer.

I guess what's taking time is to handle all the `toDevice` events (100 in your example). It should be faster when we will use the crypto rust SDK.

But we could do some measurement to confirm this.

It's more visible when disabling notification on a big account, so that no incr sync is performed in the background, which end up to big incr sync when the app is started again.

**Comment by MadLittleMods** [comment]
Thanks for checking in on this @bmarty!

I don't know what's all behind the "Parsing ..." step but it feels like *ALL* of the parsing needs to complete in order to show anything new in the app. Can we show new data as we're working through the response? It's unclear whether the "Parsing ..." step is just JSON "parsing" or is more "processing" of all of the items in the response?

From the `/sync` response, can we parse/process `room` and `to_device` in separate loops? I don't care about `to_device` when I open the app and just want to see whether a room has new messages.

What "processing" work needs to be done outside of just JSON parsing and putting the events in the local collection to display? Receiving the `/sync` response to displaying messages seems like it should be a lot quicker.

---

So I have a better understanding while discussing, what is a `to_device` message? Are these messages that should cause push notifications? Are these mainly pokes that other users added new devices to their accounts? The [spec](https://spec.matrix.org/v1.1/client-server-api/#extensions-to-sync) isn't that helpful. What's the most likely scenario when I see 67, 100, or 2 `to_device`'s every time I opened the app throughout the day?

> This module provides a means by which clients can exchange signalling messages without them being stored permanently as part of a shared communication history. A message is delivered exactly once to each client device.
> 
> The primary motivation for this API is exchanging data that is meaningless or undesirable to persist in the room DAG - for example, one-time authentication tokens or key data. It is not intended for conversational data, which should be sent using the normal [/rooms/<room_id>/send](https://spec.matrix.org/v1.1/client-server-api/#put_matrixclientv3roomsroomidsendeventtypetxnid) API for consistency throughout Matrix.
> 
> *-- https://spec.matrix.org/v1.1/client-server-api/#send-to-device-messaging*

**Comment by bmarty** [comment]
All the parsing need to be complete before refreshing the UI, since all the data, including the next sync token, are inserted into a single database transaction. In case of problem during the transaction (crash, user kills the app, etc.), we guarantee that the next sync request we re-use the previous sync token, and so the client does not get out of sync with the server. The UI is observing the database, so can be updated only once the transaction is done.

`to_device` events are related to the crypto implementation. You can get more context here: https://matrix.org/docs/guides/end-to-end-encryption-implementation-guide#handling-an-mroom_key-event. Note that a sync response cannot contain more than 100 `to_device` events.

**Comment by MadLittleMods** [comment]
> All the parsing need to be complete before refreshing the UI, since all the data, including the next sync token, are inserted into a single database transaction. 

That's how it behaves now but we could update it to work faster.

We can push messages to the database as we parse and only commit the next sync token after the whole sync response is parsed. This way, data is available immediately but in case of a crash, we just request the same `/sync` again and data is upserted no problem.

When I unlock my phone and look at Element, my first concern is whether there are new messages in the room to catch up on. My second concern is opening the room and reading them. If there is no new message indicator, I'm just going to close my phone and put it in my pocket. Currently, I have to wait for everything to parse and display before getting that first little piece of information.

We can even prioritize parsing messages from the currently open room. Parse JSON -> process `syncResponse[currentRoomId]` first. Or maybe rooms visible to me in the room list currently (I understand some sorts are determined by unread activity though), or last opened by me, whatever.

It's unclear to me how big of a role `to_device` messages play in decrypting messages. If a room is stable in the member list and device list, do these events still come through often? Or are these events sent in an encrypted room often because people need new keys for each encrypted message, idk? My first thought around `to_device` messages is do I even care about them? It's not my first concern to respond to a  `m.room_key_request` and can do it in the background. Perhaps a majority of these `m.room_key` are from a big encrypted community room I am joined to but don't really care about either and have on mute anyway. I know all of these events come over as `m.room.encrypted` so we can't detect the `type` right away but we can still see the `room_id` to see how relevant it is.


These are all just ideas though and many other ways to tackle.
