### ISSUE TITLE
Typing indicator appears cut off in bigger fonts

### ISSUE THREAD

**Issue by Throlo** [vector-im/element-android#5632]
The new typing indicator at the bottom appears cut off in larger, largest and huge fonts. "Large" font seems to be okay. 

Large
![Screenshot_20220324-204102_Element_1](https://user-images.githubusercontent.com/82319992/160028151-8cc21731-931b-442c-b124-d4459ae693e6.jpg)

Largest
![Screenshot_20220317-194328_Element_1](https://user-images.githubusercontent.com/82319992/160027978-f4cbf454-de8a-43a4-b6d7-84b84247b9ab.jpg)

Huge
![Screenshot_20220324-204255_Element_1](https://user-images.githubusercontent.com/82319992/160028019-55bd91ce-2f23-4d2e-98ba-d6f67ab90c3f.jpg)

**Comment by bmarty** [comment]
Thanks.

Developer: we should not use hard-coded height for the container.

**Comment by bmarty** [comment]
Fixed in 1.4.16
