### ISSUE TITLE
Sync is slow when device notifications are disabled

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-android#5634]
### Steps to reproduce

1. Login to Element and set device notifications on
2. Leave your phone aside for a couple of days
3. Open the app
4. Now disable device notifications
5. Leave your phone aside for a couple of days
6. Open the app

#### What did you expect?

For step 3 and step 6 to take the exact same amount of time

#### What happened instead?

- Step 3 took a matter of seconds
- Step 6 took multiple minutes

### Will you send logs?

No

### Extra context

Same issue exists for iOS too, https://github.com/vector-im/element-ios/issues/5916

**Comment by ouchadam** [comment]
for some context, the google play variant only syncs when 
- we receive a push (messages in rooms, messages being marked as read)
- whilst the app is in the foreground

the fdroid variant attempts to sync at a constant rate (defaults to 60 seconds although the system may lengthen the intervals depending on battery and device usage) 

when notifications are disabled within the app (not hidden at the system level) it means we unregister listening for push messages 

----

in your scenarios it means with notifications enabled the device is doing periodic incremental syncs whereas when they're disabled the device must catch up on all the device messages (and gappy room messages) etc

**Comment by ouchadam** [comment]
_finger in the air_ I've marked this as uncommon due to using the in app notification disabling mechanism rather than the system or individual room notifications 

there is not data however on this, happy to upgrade if others are blanket disabling all notifications in app

**Comment by gsouquet** [comment]
I don't think that setting individual room notifications would be viable as the settings is shared cross devices and I want to override the notification settings only on my personal device for my work account

**Comment by bmarty** [comment]
I agree, but I close it in favor of #5621
