### ISSUE TITLE
Location sharing does not work when sharing data with Google is disabled

### ISSUE THREAD

**Issue by mgolik** [vector-im/element-android#5650]
### Steps to reproduce

1. Open chat, try to share location
2. Allow precise location sharing

#### What did you expect?

Location sharing works without allowing sharing data with Google or at least appropriate error is displayed instead of generic one. 

#### What happened instead?

Location sharing is not working, the error appears: "Element could not access your location".

Enabling sharing data with Google fixes problem instantly, without closing the app.

#### Other info

Enabling coarse location just forces to enable precise location.

[OSMAnd](http://osmand.net/) works perfectly fine without sharing data with Google.

It would be very nice if application that supports E2E and privacy worked without depending on Google services.

### Your phone model

Samsung Galaxy S10 and Xperia 10 III

### Operating system version

Android 12 and 11

### Application version and app store

Element 1.4.2, olm 3.2.10 from F-Droid

### Homeserver

Synapse 1.55.0

### Will you send logs?

Yes

**Comment by hoka99** [comment]
This would be a major upgrade to the location tracking experience as well with #5777

**Comment by mgolik** [comment]
From what I can see it's already working, although I did not see anything mentioned in release notes.

Can someone else verify?

**Comment by torrybr** [comment]
Actually yes , I think you are correct! I just tested on 1.4.34 and looks like this is fixed. I think we can close this @mgolik

**Comment by mgolik** [comment]
Than you for fixing this!
Although you should brag about it in changelog :)
