### ISSUE TITLE
Converge on Explore rooms view for Spaces

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-android#5658]
I took a look at the original designs and couldn't see any of the Android content at the top of explore, so in Figma they were always more similar to start with.

<img width="375" alt="Explore space_ iOS@2x" src="https://user-images.githubusercontent.com/1587166/157837168-5d774b37-e055-46c8-acb6-ec68d0ecbf35.png">

<img width="408" alt="Explore space_ And@2x" src="https://user-images.githubusercontent.com/1587166/157837155-3d4ace29-f13a-4162-8a5a-bcd47b3b80cd.png">

Small notes:

- After recent discussions, its not clear what to do with subspaces, so just leave as they are on each platform for now
- Please on Android, if there's no description/topic for a room, can the `-` not be visible (see below)? It should also be a middle dot, not a dash.

<img width="234" alt="image" src="https://user-images.githubusercontent.com/1587166/157838459-5938b68c-2f9c-4247-89d1-4e444218a6c5.png">

Figma [Android](https://www.figma.com/file/PhB0Bf05EdMpdI9rsSsQZ5/%5BExit-beta%5D-Spaces?node-id=1856%3A134556)

**Comment by fedrunov** [comment]
After discussion with @niquewoodhouse and @kittykat it was decided to keep list item (room) design unchanged, since same layout is used for suggested room item in room list. Also search probably should be a part of toolbar to align with other screens with rooms filtering. 

New designs needed so reassign to @niquewoodhouse

**Comment by fedrunov** [comment]
1st option shouldn't be much harder to implement, and I also like it more than 2nd, so my voice for it

**Comment by niquewoodhouse** [comment]
> 1st shouldn't be much harder to implement, and I also like it more than 2nd, so I vote for option 1

I don't feel super strongly either way - happy to go with 1
