### ISSUE TITLE
 Letter in italics cut off slightly in message bubble

### ISSUE THREAD

**Issue by opusforlife2** [vector-im/element-android#5679]
### Steps to reproduce

1. Turn on Message Bubbles.
2. Send a word in italics.
3. Switch between bubbles and regular UI several times and observe the word.

#### What did you expect?

The full word to be displayed.

#### What happened instead?

The last letter gets cut off slightly. It's very minor, but once you see it, it's obvious.

### Application version and app store

1.4.4

### Will you send logs?

No

**Comment by opusforlife2** [comment]
Why did the bot add the `Labs` label? This feature is available generally.

**Comment by bmarty** [comment]
> Why did the bot add the `Labs` label? This feature is available generally.

Because of [this](https://github.com/vector-im/element-android/blob/main/.github/workflows/triage-labelled.yml#L17)

**Comment by opusforlife2** [comment]
Oh. I'm guessing that needs to be updated then?
