### ISSUE TITLE
Deleted messages visible with "View Source"

### ISSUE THREAD

**Issue by git-bruh** [vector-im/element-android#5730]
### Steps to reproduce

1. Open any room (encrypted/non-encrypted)
2. Send (or receive) a message
3. Delete the message
4. Long press the deleted message and tap on "View Source"

#### What did you expect?

The `content` key of the json should have an empty value.

#### What happened instead?

Original message content is visible. This happens because view source is supposed to show the original content without edits, as a consequence it shows the deleted content aswell. But I expected the deleted content to be cleaned from the database by replacing the `content` key of the relevant event with an empty json `{}`.

![Screenshot_20220411-151046_Fork_Launcher_1](https://user-images.githubusercontent.com/67585967/162711840-2343c2df-7a8f-404c-b5a9-25efcc4e7e01.png)
![Screenshot_20220411-151050_Fork_Launcher_1](https://user-images.githubusercontent.com/67585967/162711850-b54fd7fe-79ed-4f0d-81f5-7b61296cce4d.png)

### Application version and app store

1.4.11 from github releases

### Will you send logs?

No

**Comment by bmarty** [comment]
This is fixed in 1.4.12 (by #5707)
