### ISSUE TITLE
When a new user registers a new Matrix account in Element Android, the session name isn't added in the sessions list

### ISSUE THREAD

**Issue by Linerly** [vector-im/element-android#5769]
I've seen this with my friends who registers in Element Android and not having the session name (“Element Android”) in the sessions list when I look at it, not sure why

**Comment by ouchadam** [comment]
to double check, how/where are you viewing this session list / Does Element web also show the same device names? 

from the code it looks like we're still setting the initial device name to "Element Android" but it's possible a bug has crept in~

**Comment by Linerly** [comment]
Clicked on the profile picture, and I'm only seeing random letters (the account is on matrix.org)

**Comment by Linerly** [comment]
…though the next time they log in to Element Android again, the session name is “Element Android” as it should

**Comment by ouchadam** [comment]
> …though the next time they log in to Element Android again, the session name is “Element Android” as it should

very interesting! will have a deeper dive as part of the FTUE work

**Comment by ouchadam** [comment]
I'm unable to reproduce the issue, creating a new account on matrix.org and I'm able to see the session in the list 

is it possible I'm missing some steps?

| ACCOUNT CREATION | 
| --- |
![sign-up-session-name](https://user-images.githubusercontent.com/1848238/185144243-5f69fb6c-73ce-4b06-ba37-60f722fc6a4c.gif)

**Comment by Linerly** [comment]
> I've seen this with my friends who registers in Element Android and not having the session name (“Element Android”) in the sessions list when I look at it, not sure why

Keep in mind that they registered a long time ago (around early 2022), so it's possible the issue has been fixed since then...

**Comment by ouchadam** [comment]
it sounds like the session names you're seeing are the users session IDs, as it doesn't seem to be happening anymore and it's possible to manually rename the session, I'm going to close this issue :crossed_fingers: 

let's reopen if an account created with more recent versions of Element have the issue (especially now that the registration flow has undergone quite a big change) 

thanks for raising!
