### ISSUE TITLE
Voice call button removed

### ISSUE THREAD

**Issue by Wodann** [vector-im/element-android#5779]
Since the last update (current version: 1.4.11 [40104112] (G-b7382)), the voice call button has been removed from chats and groups, only allowing for video calls:

![Screenshot_20220415-114810~2.png](https://user-images.githubusercontent.com/6917585/163597659-9fff8637-0617-4d26-a3ff-0d750f37ed71.png)

I'd like to be able to still have the option to initiate either a voice or video call, even if it's under the **...** menu

**Comment by YamatoRyou** [comment]
Disable the thread to show the voice call button, it looks like this location shows up to 2 buttons.

**Comment by Wodann** [comment]
My expectation would be that if a menu item is "dropped" due to limited space, it'd move into the **...** menu, so the functionality remains accessible.

**Comment by ouchadam** [comment]
related fix in the same area https://github.com/vector-im/element-android/pull/5548

**Comment by bmarty** [comment]
Let's close this one in favor of #5840
