### ISSUE TITLE
FTUE - Link connect to server to new Server Selection

### ISSUE THREAD

**Issue by ouchadam** [vector-im/element-android#5782]
- When tapping Connect to server the user should be presented the sign up page with the Edit server screen already open

**Comment by daniellekirkwood** [comment]
We will test with this case and see if we need to change or pivot what we're doing... Assigning to the 3 of us to ensure we don't miss it.

**Comment by daniellekirkwood** [comment]
## Is this a V1 or a V2 issue? 
It's not strictly needed, it's not a blocker for the release but it would improve the user's experience. 

@ouchadam to hide the button in the meantime

**Comment by daniellekirkwood** [comment]
No longer exists
