### ISSUE TITLE
FTUE - Update sign up steps ordering

### ISSUE THREAD

**Issue by ouchadam** [vector-im/element-android#5783]
The ideal ordering is 

- Create account 
- Enter and verify email
- Privacy policy / T&Cs
- Captcha

**Comment by bmarty** [comment]
Sorry, I am late in the party, but the client should follow the order provided by the server.

So what is required to fix this issue is a server configuration change IMO

**Comment by ouchadam** [comment]
cc @daniellekirkwood  

For extra context, with this issue merged, the app will respect the server order for the legacy middle section flow and override the order for our new flow (based on the combined register feature flag)

**Comment by bmarty** [comment]
And as a user, I think the more expected order will be

- Create account 
- Captcha (to filter out bot first, and not annoy the user with this boring step just before the end)
- Privacy policy / T&Cs (because if the user does not agree, there is no need to ask for their email first. Also the T&C can explain what we will do with their email, so they have to be accepted first)
- Enter and verify email

**Comment by daniellekirkwood** [comment]
@bmarty - we put a lot of thought into the ordering of the screens and how the 'story' plays out for the user during signup. Happy to discuss further.

> For extra context, with this issue merged, the app will respect the server order for the legacy middle section flow and override the order for our new flow (based on the combined register feature flag)

Thanks, @ouchadam. Let me play this back to make sure I'm following - 
_If the user's server choice enforces an alternative ordering of these screens then the new flow will honour that? What is the ordering of matrix.org?_

**Comment by bmarty** [comment]
(OK, just cannot resist to add my 2 cents: I keep thinking that asking for Captcha at the end, user will see a WTF like: "wait, I have already provided my email and clicked on the link it contains, so of course I am not a robot!")

Current order on matrix.org is:

```json
    "flows": [
        {
            "stages": [
                "m.login.recaptcha",
                "m.login.terms",
                "m.login.email.identity"
            ]
        }
    ],
```

And the app is following this order at the moment.
