### ISSUE TITLE
Set up screenshot tests

### ISSUE THREAD

**Issue by manuroe** [vector-im/element-android#5798]
Here is the current plan:

- [ ] setup the environment, using https://github.com/cashapp/paparazzi
- [ ] explain in a doc how to test a new screen (and update existing test)
- [ ] test first screens. Maybe the FTUE screens could be a good fit, since this part is already very well covered by other test types.
- [ ] Ensure the CI runs the tests.

**Comment by ouchadam** [comment]
would be interesting to investigate using https://github.com/cashapp/paparazzi to avoid needing a real device/emulator (renders the UI via the layoutlib/design preview)

**Comment by ouchadam** [comment]
first iteration was to spike the tooling [internal doc](https://docs.google.com/document/d/14zFL0fgqFuJIc2bjKfXJOj1f-b-IUEFJkay7fmIE1wQ/edit#)

we'll need follow up tickets to fully implement the decision and write some tests

**Comment by ouchadam** [comment]
completed with https://github.com/vector-im/element-android/pull/7128 & https://github.com/vector-im/element-android/pull/7129
