### ISSUE TITLE
Set up Nightly builds

### ISSUE THREAD

**Issue by manuroe** [vector-im/element-android#5803]
We want to automate the release of develop builds so that we can have feedbacks sooner a la develop.element.io.

### Requirements

1. We want the nightly build to be as close as possible to the release version of the app
2. We want the nightly build to be installed along with the release version of the app
3. We want the nightly build to have its own signature so that we can share some secrets with GitHub, without taking the risk to compromise the signature of the main app
4. The nightly build is set up for the GPlay variant of the app (nightly builds for F-Droid users already exist at https://fdroid.krombel.de/)
5. We want the nightly builds to be built once a day, during the night, when the CI is not too busy by building PRs
6. We want the nightly build to be built and released automatically
7. Nightly build are built from the `develop` branch of the app. So it includes all merged PR since the previous build
8. We want nightly build to upgrade installed nightly build app automatically
9. We want to be able to detect nightly build and the version on rageshakes.
10. We want nightly build to be available to anyone
11. Analytics?

### Actions

- [x] Create a new `buildTypes` named `nightly`, base on `release`. Use `initWith release`
- [x] Create a new signature
- [x] add the signature to the project (we already have the debug signature to the project).
- [x] Store the secrets into Passbolt
- [x] Share the secrets to GitHub Secret
- [x] Nightly build will have `.nightly` suffix for the appId and ` nightly` suffix for the app name (**EDIT** We do not update the app name to not alter strings with template using the app name). We could also change the background of the icon to something dark (code 07007E) (**EDIT** This is done).
- [x] `versionName` will be the current version of develop with a `-nightly` suffix (for instance "1.4.28-nightly")
- [x] `versionCode` will be the versionCode from develop, i.e. based on timestamp (no change to do here)
- [x] Create a dedicated file `google-services.json` with the package name of the nightly
- [x] Configure a GitHub action to build the nightly build and publish them
- [x] Rageshake will include a new "Nightly" label
- [x] Use Firebase app distribution to release the nightly build. With gradle https://firebase.google.com/docs/app-distribution/android/distribute-gradle, with client: https://firebase.google.com/docs/app-distribution/android/distribute-cli. Not sure what is the best option so far (?).
- [x] Document how to subscribe to the nightly build

### Once complete

- [ ] Advertise that the nightly build is available, providing the documentation about it

**Comment by genofire** [comment]
An F-Droid Repo for the nighty builds would be interesting. So an F-Droid store app would manage delivering of the updates. (Like in SchildChat: https://schildi.chat/android/ )

**Comment by genofire** [comment]
No Nightly F-Droid Builds ;(

**Comment by genofire** [comment]
Another Logo for the Nightly Build would be cool, for easy find the correct installed Version of Element.

**Comment by genofire** [comment]
Put Logo Idea here:  #6742
