### ISSUE TITLE
Stuck on "Verify this login" - Never received prompt to verify device

### ISSUE THREAD

**Issue by MadLittleMods** [vector-im/element-android#5808]
### Steps to reproduce

 1. Login to the Android app (new session)
 1. Get prompted to "Verify this login"
    <img src="https://user-images.githubusercontent.com/558581/164532988-459f4811-6f9b-4b19-8a4c-5f9b798198db.png" width="270"> <img src="https://user-images.githubusercontent.com/558581/164378159-009468db-a871-4a14-868e-1a84a6a2d751.png" width="270">
 1. Go on your Element Web instance and press "Verify" on the `Element Android` item
    ![](https://user-images.githubusercontent.com/558581/164533467-e4457eb4-f535-44da-8b05-7b511272e736.png)
 1. Notice how nothing happens

#### What did you expect?

After pressing "Verify" in the Element Web instance, the Android app would move forward or prompt me to continue.

#### What happened instead?

Nothing changed. Just staring at the "Verify this login" screen.

After I exited (or was canceled) the "Verify this login" screen, it did nicely tell me I can verify at any time later. So I tried pressing "Verify" on Element Web again and this time I got the prompt.

<img src="https://user-images.githubusercontent.com/558581/164378710-3f57e9d7-278a-41e1-95d4-707fe7afeda5.png" width="270">

### Your phone model

Google Pixel 4a

### Operating system version

Android 12

### Application version and app store

Element Android version 1.4.11 [40104112] (G-b7382), olm 3.2.10

### Homeserver

matrix.org

### Will you send logs?

Yes

 - Element Android logs: https://github.com/matrix-org/element-android-rageshakes/issues/37184
 - Element Web logs: https://github.com/matrix-org/element-web-rageshakes/issues/12317

**Comment by MadLittleMods** [comment]
I think this is actually an Element Web bug where creates a new verification request instead of accepting the existing verification request from Android, https://github.com/vector-im/element-web/issues/21874

**Comment by christiansacks** [comment]
![Screenshot_20221106-011025.jpg](https://user-images.githubusercontent.com/40481087/200149366-93191ab9-8dd2-4350-ad08-26efdde802d7.jpg)

I just reinstalled because element stopped updating my chats on the android client, now when I log in it says about verifying with another session, but it never shows me the emojis on either side and doesn't offer me the password method so now kinda stuffed.

**Comment by MadLittleMods** [comment]
@christiansacks Sounds like you have a separate issue. Create a new issue with logs or find the appropriate existing issue
