### ISSUE TITLE
Signing out causes a crash

### ISSUE THREAD

**Issue by frakic** [vector-im/element-android#5821]
### Steps to reproduce

1. Where are you starting? What can you see?
 -I'm logged into the app
2. What do you click?
 -I try to sign out
3. More steps…
 -About 3 out of 10 times the app crashes when I confirm signing out
 -The next time I log in, I'm greated with the crash report screen

#### What did you expect?
I expected to be signed out and taken to the welcome screen.
#### What happened instead?
The app crashed instead.

Submitted 2 rageshakes:
https://github.com/matrix-org/element-android-rageshakes/issues/37244
https://github.com/matrix-org/element-android-rageshakes/issues/37247

### Your phone model

Samsung Galaxy A40

### Operating system version

Android 11

### Application version and app store

1.4.12

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by ouchadam** [comment]
also seeing this come through in the play store crashes https://play.google.com/console/u/0/developers/{redacted}/app/{redacted}/vitals/crashes/8618186f/details?installedFrom=PLAY_STORE&days=30


| Occurrences (30 days) | Total Occurrences | Impacted users (lifetime) |
| --- | --- | --- |
| 169 | 197 | 172 |
