### ISSUE TITLE
Update copy for "override nick colour"

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-android#5825]
### Steps to reproduce

1. Click on a user to see their profile

#### What did you expect?
"More" section of the screen in this order:
* Direct message
* Override display name colour
* Jump to read receipt
* Mention
* Ignore

And the "Override" popup title is "Override display name colour"

#### What happened instead?
"Override" is before "message" and uses "nick" instead of "display name"

### Application version and app store

1.4.12

### Will you send logs?

No

**Comment by bmarty** [comment]
(as per commented in #5831, default strings have to be US English, so we use `color` instead of `colour`)

**Comment by kittykat** [comment]
> (as per commented in #5831, default strings have to be US English, so we use `color` instead of `colour`)

We should revisit that on a product level as web has en_GB by default probably because most engineers are in Europe, and then there are en_US translations

**Comment by bmarty** [comment]
Default to `en-US` is a "limitation" of the Android platform. It's still possible to provide translations for `en-GB`, and we already have some, see https://github.com/vector-im/element-android/blob/main/vector/src/main/res/values-en-rGB/strings.xml#L3.

Note that if your phone is configured to use `en-GB`, you will see the app with `en-GB` strings. So default language for the app will be the language set in your phone.

I will update the doc to clarify this point.

**Comment by bmarty** [comment]
Clarified in https://github.com/vector-im/element-android/pull/5854/commits/506d27fa2fc4c33de533a732a34c42a70275a1c6
