### ISSUE TITLE
[Regression] The app can get very laggy 

### ISSUE THREAD

**Issue by SimonBrandner** [vector-im/element-android#5837]
Since the last release the app seems to very quickly get unusable - it lags and freezes _a lot_

Will send logs

**Comment by DoM1niC** [comment]
> Since the last release the app seems to very quickly get unusable - it lags and freezes _a lot_
> 
> Will send logs

some problem... :( here

**Comment by bmarty** [comment]
Thanks @SimonBrandner for creating the issue and for the rageshakes. Next time can you use the template please? Also using "the last release" is not ideal, better to name it. In this case this is release 1.4.12.

We have seen the problem and have investigated it. We will do a hotfix 1.4.13. Release 1.4.12 is not in production yet.

Draft PR with the fix: #5835

**Comment by SimonBrandner** [comment]
Thank you!!

(sorry for the very unideal issue report - I filled it in on a phone in a rush...)

**Comment by bmarty** [comment]
No worries :)

Fixed in Element Android 1.4.13

**Comment by SimonBrandner** [comment]
> No worries :)
> 
> Fixed in Element Android 1.4.13

Thank you!!! ❤️
