### ISSUE TITLE
Enabling threads hides the voice call button

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-android#5840]
### Steps to reproduce

1. Voice button is now hidden behind the hamburger icon
2. Except it’s not labelled “voice call” it’s “call”, which makes it even harder to find
3. Instead, perhaps we need a single call button which then gives you voice or video as a choice

#### What did you expect?

Intuitive calling

#### What happened instead?

I kept getting video calls because folks can no longer find the voice call button.

### Will you send logs?

No

**Comment by bmarty** [comment]
Thanks for creating a dedicated issue. It was part of my concern when testing release 1.4.11 (see second point of https://github.com/vector-im/element-android/issues/5699#issuecomment-1089908319).

About having a dialog to choose between voice or video call: we had complaint in the past that it adds an extra step, this is not ideal.

I would rather keep the 2 icons as before (as per other messengers like WhatsApp - which does not support thread). But I agree that it takes more space...

CC @daniellekirkwood for a product thinking about it (feel free to reassign if you're not the best person to handle it :))

**Comment by daniellekirkwood** [comment]
We also had a bug [here](https://github.com/vector-im/element-android/issues/4762#event-6327038193) where one of the buttons would disappear depending on the room (irrelevant of Threads).

We've had a couple of other issues raised around the placement of the Threads icon:
* https://github.com/vector-im/element-ios/issues/6041
* https://github.com/vector-im/element-android/issues/5779

@janogarcia & @gaelledel could you help here? How should we address this feedback?
I think Jano is the right "actioner" with input from Gaelle so will assign as such.

**Comment by janogarcia** [comment]
@daniellekirkwood 

- https://github.com/vector-im/element-ios/issues/6041 <br> Improving the spacing / tappable area between buttons is actually the first thing in the list I shared when I reviewed the implementation for the Beta app. Ref. https://github.com/vector-im/element-android/issues/5593
- https://github.com/vector-im/element-android/issues/5779 <br> I don't know why it's been removed or who removed it. The Figma mockups for Threads are showing both call icons. Probably someone worked on a redesign of the top bar on mobile?

**Comment by bmarty** [comment]
The 3 changes in here: https://github.com/vector-im/element-android/pull/5548/files#diff-a3577ed2a7330c9feb95b5567a3119ec773460f658ce931bce7679bb6550bab9R28 are making the menu items not always visible, probably because @ericdecanini wanted to fix a IDE warning. This was not good.

**Comment by bmarty** [comment]
@ericdecanini can you revert this change please (see the comment above)?
