### ISSUE TITLE
Delight: Space switching experiment [Android]

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-android#5849]
Build the Space switching experiment detailed here:
- [x] https://github.com/vector-im/element-meta/issues/219

Other things we should consider as a part of this issue:
- [ ] Ensure that the APK can be shared
- [ ] Discuss in-product event tracking and feedback collection

**Comment by daniellekirkwood** [comment]
@fedrunov, @ericdecanini Here's an issue ready for the Space switching experiment. While Amsha is out feel free to coordinate with @niquewoodhouse for any questions you have. 

The meta issue has the link to the Figma file that you'll need. 

If you'd like to create more tasks from this one, feel free to do so :)

**Comment by ericdecanini** [comment]
Functional prototype is here
https://github.com/vector-im/element-android/pull/5977

Currently awaiting design feedback. Moved to support for now

**Comment by daniellekirkwood** [comment]
Discussion from meeting, talking about PostHog: 
- First 2 asks are easy, we'll go ahead and build those
- Danielle to check number 3 and 4 if they already exist, or what we can do in PH
- Number 5 is a nice to have - we think we can use the ViewRoom event - but maybe not 
- We will only add these events to the prototype, but we may need another discussion about how to loop these into the full product
- These will only go to PostHog Dev instance

**Comment by daniellekirkwood** [comment]
I can't confirm how we view time in PostHog but Bullet 3 is a nice-to-have so it won't be a blocker. 

As for the number of Spaces, that's a userProperty that we send ✔ 

@fedrunov I think you were looking into Number 5? ViewRoom + isSpace property?

**Comment by fedrunov** [comment]
So, for 1 and 2 I've extended `Interaction` event with three new options for `name` property:

-SpaceSwitchHeader
-SpaceSwitchHeaderAdd
-SpaceSwitchHeaderCreate

and `SpaceSwitchHeader` also has propery "isSpace" (true/false) to distinct if it's pressed from home(false) or from space(true) screen

I've also added ViewRoom(isSpace = true) event tracking, when user changes space on home screen

**Comment by gsouquet** [comment]
Closing as the experiments are now finished and the results are available on figjam and airtable
