### ISSUE TITLE
Signing into homeserver fails if username exists in matrix.org main server. 

### ISSUE THREAD

**Issue by christiansacks** [vector-im/element-android#5852]
I have my own homeserver at matrix.erb.pw, the older Android client worked a treat but I had to sign out of the client today, and now I can't log back in. The reason it seems is that even though I'm telling the client to use my own homeserver and giving my username and password, it says the creds are incorrect, but if I change just the password to the password used on matrix.org with the same username, even though the homeserver is still using my own, it signs me into matrix.org.

Because of this I believe the latest versions of element android are ignoring the homeserver setting if you are wanting to use a custom homeserver. 

User on my homeserver: @meatlotion:matrix.erb.pw
User on matrix.org: @meatlotion:matrix.org

Hope someone can spot the issue and correct it quickly, I feel lost without the app working lol.

**Comment by ouchadam** [comment]
@christiansacks thanks for raising! to double check, are you signing in via the `Sign in with Matrix ID` button?

![Screenshot_20220427_121954](https://user-images.githubusercontent.com/1848238/165507172-7e069578-3c9c-4c02-be57-081bb28c6b10.png)

we're currently working on improving the sign in/up experience (FTUE project) to help make this area less confusing

**Comment by christiansacks** [comment]
yes I've tried both that and selecting "Other / Custom & advanced setting";

In "Sign in with Matrix ID", I have specified my ID as "@meatlotion:matrix.erb.pw" and the password I have tried is the one I reset on my own home server, which fails, but if I use the password for my same user but at matrix.org, i sign in ok to the matrix.org account.

In "Other / Custom & advanced setting", I have specified my username as "meatlotion" and the password I have tried is the one I reset on my own home server, which fails, but if I use the password for my same user but at matrix.org, i sign in ok to the matrix.org account.

I hope this helps. It's like whatever I put in for either my homeserver detail in the "Other / Custom & advanced setting" option, or "Sign in with Matrix ID", it's ignoring my homeserver and assuming that my username is for matrix.org only.

**Comment by christiansacks** [comment]
to clarify, lets assume my credentials are;

My homeserver creds:
Username: `@meatlotion:matrix.erb.pw`
Password: `ERB-password`

Matrix.org creds:
Username: `@meatlotion:matrix.org`
Password: `MATRIX-password`

In Matrix ID log in, if I log in like;

Username: `@meatlotion:matrix.erb.pw`
Password: `ERB-password`

This fails, but if I do

Username: `@meatlotion:matrix.erb.pw`
Password: `MATRIX-password`

This will sign me in, but as `@meatlotion:matrix.org`

Hope this helps clarify.

**Comment by ouchadam** [comment]
this sounds super strange _but_ it's actually the expected behaviour... 

it turns out your homeserver is redirecting back to matrix.org :smile:  https://matrix.erb.pw/.well-known/matrix/client

```
{
    "m.homeserver": {
        "base_url": "https://matrix-client.matrix.org"  <- should be https://matrix.erb.pw
    },
    "m.identity_server": {
        "base_url": "https://vector.im"
    }
}
```

**Comment by christiansacks** [comment]
Bugger me! That was super simple! This is why you guys are the geniuses behind the super awesome system, and I am a mere peasant using it.

I thank you, very much. I have signed in now on my android handset, to my own homeserver

**Comment by ouchadam** [comment]
no problem! glad it's sorted :100:
