### ISSUE TITLE
Add support for emoji 14.0

### ISSUE THREAD

**Issue by thanasistrisp** [vector-im/element-android#5876]
#### What would you like to do?
Support [emoji 14.0](https://emojipedia.org/emoji-14.0/)
#### Why would you like to do it?
So that people can use the latest and greatest emoji.
#### How would you like to achieve it?
By updating our Twemoji and Emojibase sources. In element web it is already implemented [here](https://github.com/vector-im/element-web/issues/21479)

**Comment by ouchadam** [comment]
it looks like the emoji-compat library we're using has included support for emoji14 in the 1.1.0 release https://developer.android.com/jetpack/androidx/releases/emoji2#1.1.0

**Comment by ouchadam** [comment]
we'll need to wait for https://github.com/vanniktech/Emoji/pull/691 to also be released

**Comment by jmartinesp** [comment]
I believe this is already done, as the referenced PR is merged and I could use some of the new emojis without issues. Please re-open it otherwise.
