### ISSUE TITLE
Rooms incorrectly marked as unread

### ISSUE THREAD

**Issue by Sorunome** [vector-im/element-android#588]
Rooms which only had a whole ton of m.room.member changes are incorrectly marked as unread

**Comment by Bubu** [comment]
Copying my comment over from #701 

Rooms are marked as highlighted (green bar at the left side) in riotX quite often which are not marked as such in riot-web (where they would be printed bold).
This seems to happen on any leave/join and also on alias changes, etc.

**Comment by onurays** [comment]
![IMG_20200831_161654](https://user-images.githubusercontent.com/1254401/91724157-8f07b680-eba5-11ea-8670-3d559deb0568.jpg)
