### ISSUE TITLE
Why are there FaceBook trackers in the app?

### ISSUE THREAD

**Issue by draxaris1010** [vector-im/element-android#5882]
### Steps to reproduce

none

#### What did you expect?
no facebook trackers

#### What happened instead?
facebook trackers are present

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by Linerly** [comment]
AFAIK, it's for the Facebook SSO option

**Comment by draxaris1010** [comment]
Can this be done without the fb SDK?

**Comment by draxaris1010** [comment]
It comes from [AppManager](https://f-droid.org/packages/io.github.muntashirakon.AppManager/), it uses ClassyShark3xodus for that and it detects it in [a "dumb" way](https://muntashirakon.github.io/AppManager/en/#sec:scanner-page).

**Comment by jmartinesp** [comment]
AppManager no longer displays the facebook tracker on the latest version, only Sentry and Posthog (and both can be disabled), so I believe this is no longer an issue? Please re-open otherwise.
