### ISSUE TITLE
After sharing data from other apps to Element, multiple instances of Element are created.

### ISSUE THREAD

**Issue by alittlebitofit** [vector-im/element-android#5937]
### Steps to reproduce

1) Open Element.
2) Minimize. Do not close. Do not clear from Recents.
3) Open camera and click a picture and share in Element. Wait for the picture to finish sending. Do not close or clear from Recents.
4) Now goto AppSwitcher/Recents.

You can see 2 instances of Element.

#### What did you expect?
Only 1 instance of Element in Recents.

#### What happened instead?
2 instances were created.
And many more are created depending on how many times you share.

It also happens when you share data from numerous other apps to Element.

Although, extra instances get destroyed when you press Back button.
And extra instances of Element don't allow you to navigate to other parts of the app.

### Your phone model

Samsung Galaxy M31s, One UI 4.0

### Operating system version

Android 12

### Application version and app store

Version: 1.4.11 [40104110] (F-aec19656); Matrix SDK version: 1.4.11 (aec19656); olm version: 3.2.10

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by konomikitten** [comment]
This is an extremely annoying issue, I'll also note that the duplicate instances also at least on my phone do not load media either and don't behave correctly.

**Comment by ouchadam** [comment]
thanks for the details :+1: I'm going to centralise the issue to #4629 (and raise the frequency)
