### ISSUE TITLE
Dependabot does not upgrade all our dependencies.

### ISSUE THREAD

**Issue by bmarty** [vector-im/element-android#5961]
According to https://github.com/vector-im/element-android/network/updates/361179500

Every dependencies are searched in https://jitpack.io/ and [https://github.com:443/vector-im/jitsi_libre_maven/raw/main/android-sdk-5.0.2](https://github.com/vector-im/jitsi_libre_maven/raw/main/android-sdk-5.0.2) on not mavencentral

For instance about `com.airbnb.android:mavericks` (extract of the link above):

> updater | INFO <job_361179500> Checking if com.airbnb.android:mavericks 2.5.0 needs updating
  proxy | 2022/05/05 23:09:41 [096] GET https://jitpack.io:443/com/airbnb/android/mavericks/maven-metadata.xml
  proxy | 2022/05/05 23:09:41 [096] 404 https://jitpack.io:443/com/airbnb/android/mavericks/maven-metadata.xml
  proxy | 2022/05/05 23:09:42 [098] GET https://github.com:443/vector-im/jitsi_libre_maven/raw/main/android-sdk-5.0.2/com/airbnb/android/mavericks/maven-metadata.xml
  proxy | 2022/05/05 23:09:42 [098] * authenticating git server request (host: github.com)
  proxy | 2022/05/05 23:09:42 [098] 404 https://github.com:443/vector-im/jitsi_libre_maven/raw/main/android-sdk-5.0.2/com/airbnb/android/mavericks/maven-metadata.xml
  proxy | 2022/05/05 23:09:42 [098] * auth'd git request returned 404, retrying without auth
updater | INFO <job_361179500> Latest version is 
updater | INFO <job_361179500> Requirements to unlock update_not_possible
updater | INFO <job_361179500> Requirements update strategy 
updater | INFO <job_361179500> No update possible for com.airbnb.android:mavericks 2.5.0

But Maverick 2.6.1 exists, see https://github.com/airbnb/mavericks/releases, and https://repo1.maven.org/maven2/com/airbnb/android/mavericks/2.6.1/

I think we have lots of outdated dependencies now.

Tentative fix from @ouchadam, by reordering our dependencies repositories : fd2aaa8c2bfa669f48309477e11f32659eb54e5d . But no effect :/

Not sure how to fix this annoying issue :/

**Comment by MarcelCoding** [comment]
I just found a workaround for this: https://github.com/dependabot/dependabot-core/issues/3901#issuecomment-1119784975

Btw. your app is really nice. I use it already for a long time :)
