### ISSUE TITLE
Wrong mic button direction (to cancel) on rtl languages

### ISSUE THREAD

**Issue by ektefa** [vector-im/element-android#5968]
### Steps to reproduce

1. Set application language to any rtl language (Like: Persian-Farsi)
2. Press and hold mic button to record voice message
3. Try to swipe to right to cancel recording

### Outcome

Expected to swipe to right to cancel recording, but its not working. Instead you have to swipe to left now.

### Your phone model

LG G8s

### Operating system version

Android 11

### Application version and app store

Element v1.4.13

### Homeserver

Synapse non-public homeserver

### Will you send logs?

No

**Comment by bmarty** [comment]
(bug confirmed)

**Comment by ByeongsuPark** [comment]
Hi, Can I take this issue?

**Comment by ektefa** [comment]
> Hi, Can I take this issue?

Of course
