### ISSUE TITLE
1.4.13 - Unable to switch to custom homeserver if homeserver has registration disabled.

### ISSUE THREAD

**Issue by dedward** [vector-im/element-android#5972]
The client is trying to validate that registration is available when accepting a new homeserver, and refuses to continue if it either can't reach the registration API endpoint (because of an ACL) or gets a response that registration is disabled on the servers.

Users who log out or have a new device are unable to reconnect.

I believe this is incorrect behaviour.

**Comment by digital-codes** [comment]
Same issue here. Can cannot with every client except element android to riotchat.de (didn't test on ios though)

**Comment by ouchadam** [comment]
thanks for raising, the issue has been fixed in 1.4.14 (which is currently in the play store beta channel) https://github.com/vector-im/element-android/issues/5874
