### ISSUE TITLE
Sync sometimes never finishes/is very slow

### ISSUE THREAD

**Issue by SimonBrandner** [vector-im/element-android#6027]
### Steps to reproduce

1. Don't use Element for a while
2. Open Element
3. Wait for it to sync
4. Wait for it to sync
5. Wait for it to sync
6. It has taken several minutes

#### What did you expect?

The sync to be very quick

#### What happened instead?

It took several minutes

### Your phone model

M2004J19C; Moto G7 plus

### Operating system version

11 (API 30) V12.5.5.0.RJCEUXM-REL; 10 (API 29) fac4a-REL

### Application version and app store

1.4.13

### Homeserver

matrix.org; element.io

### Will you send logs?

Yes

**Comment by aidaho** [comment]
In my case I've waited for 20 minutes without any progress.  
Workaround is to unsubscribe from all the channels you don't actively participate in, then kill and start the app again.  

I too believe this is probably a regression, as I'm primarily using Element from desktop and only occasionally launch it on the phone to send a pic.  
Previously the android app synced within reasonable timeframe.

**Comment by SimonBrandner** [comment]
> does the sync eventually start and complete?

It quite certainly starts but I am not sure if it ever ends - when this happens I tend to just kill the app and start it again, the sync status then shows a decreased number of rooms to process and then finishes

**Comment by SimonBrandner** [comment]
Ok, so I think it does finish but it can take up to several minutes to do that

Is there any more info I could provide?

**Comment by toshanmugaraj** [comment]
When I receive a notification, and I tap it to view, the application syncs for around 1 to 1.5 min , before I can read the message.

**Comment by manuroe** [comment]
I increased the severity to treat this issue as a P1. 
We will check the issue after the completion of https://github.com/vector-im/element-android/issues/6498 and https://github.com/vector-im/element-android/issues/5842 that will change the threading model.
ElementR-Android that will use the Rust crypto module will also have an impact in, hopefully, the good way.

**Comment by SimonBrandner** [comment]
> I increased the severity to treat this issue as a P1. We will check the issue after the completion of #6498 and #5842 that will change the threading model. ElementR-Android that will use the Rust crypto module will also have an impact in, hopefully, the good way.

Do you have a rough time estimate for that?

**Comment by mqudsi** [comment]
This is closed as fixed but it’s definitely still around in one form or the other as of mid-2024. I’m not subscribed to many channels or any large ones (just like three or four ex-gitter communities) and I still see this behavior with the latest beta versions. 

Get a notification without content. Open the app (killed or resumed doesn’t matter) and open the channel. It says “syncing” and keeps saying that for several minutes without anything happening. Give up and walk to the PC.

**Comment by stemy2** [comment]
Could you reopen the issue? It's not fixed at all. It's running since 20 minutes and the loading bar is barely filled.
