### ISSUE TITLE
[MergedRoomItemCreation] Wrong name in DM creation item

### ISSUE THREAD

**Issue by Claire1817** [vector-im/element-android#6032]
### Steps to reproduce

In DM creation item, the display name is the account name instead of the other member name.
Here we should display Claire instead of claireg16.
![wrong](https://user-images.githubusercontent.com/15031750/168030484-e62074c9-f795-4734-83c1-1aa9d599f601.png)

### Outcome

Using other member name instead of the connected account name.

### Will you send logs?

No

**Comment by giomfo** [comment]
This is a regression due to the initial fix of https://github.com/vector-im/element-android/issues/5570

**Comment by mnaturel** [comment]
@Claire1817 Just in case, I add some precisions for the bug: we displayed the name of the one that originally created the room. So if the current user were invited by someone else to chat, the member name will be correct in the message. If the current user is the one who sent the invitation, the member name will be not correct.
