### ISSUE TITLE
FTUE - MSISDN input

### ISSUE THREAD

**Issue by ouchadam** [vector-im/element-android#6043]
Add support for MSISDN registration step  

https://www.figma.com/file/xdV4PuI3DlzA1EiBvbrggz/Login-Flow-v2?node-id=2523%3A42803

![2022-05-13T09:25:20,633698968+01:00](https://user-images.githubusercontent.com/1848238/168242873-a2aa3c63-16cd-4721-ab42-af0de2241825.png)

**Comment by bmarty** [comment]
"You can't change this later" is wrong, small design issue?
