### ISSUE TITLE
Parsing Error in Element Android

### ISSUE THREAD

**Issue by dreaddr** [vector-im/element-android#6054]
### Steps to reproduce

Please check https://github.com/vector-im/element-web/issues/22198 as it relates to this issue and has the steps to reproduce.

### Outcome

Please check https://github.com/vector-im/element-web/issues/22198 as it relates to this issue and has the outcome as well (in the form of screenshots).

### Your phone model

Samsung Galaxy S6

### Operating system version

Android 7

### Application version and app store

Latest

### Homeserver

matrix.org

### Will you send logs?

No

----------

Screenshots

| WEB Markdown disabled | Android |
| --- | --- | 
|![image](https://user-images.githubusercontent.com/1848238/169869552-8452e008-23ce-4b6b-8428-d25aa2013431.png)|![image](https://user-images.githubusercontent.com/1848238/169869620-f0f58b45-dbcd-41e2-8b7c-7f329168542a.png)

**Comment by dreaddr** [comment]
> To confirm the case, raw markdown is sent from the web client and the android app is rendering with the markdown styling applied?

Yes that appears to be what is happening, if I understand correctly. It should be raw in both clients but one (Element Android) is rendering the text incorrectly.

**Comment by ouchadam** [comment]
fixed by #6357 and will be available in 1.4.26
