### ISSUE TITLE
Is there a way to FOLLOW friends rooms channels and see what channels they participate in etc?

### ISSUE THREAD

**Issue by jittygitty** [vector-im/element-android#6057]
#### What would you like to do?
Would like those I connect with in Direct Messages and possibly in some channels to be allowed (based on my settings for those rooms to share or not?) to see what rooms/channels I participate in and to be able to likewise see/follow channels/rooms my friends are on...
#### Why would you like to do it?
Just because.

#### How would you like to achieve it?
Likely by hoping some developer sees this and wants it too?

**Comment by bbhtt** [comment]
This is https://github.com/vector-im/element-android/issues/4573 I think. There is a spec proposal for this feature, tracked as MSC2666.

**Comment by turt2live** [comment]
Closing as a duplicate of https://github.com/vector-im/element-android/issues/4573
