### ISSUE TITLE
Login with MULTIPLE Profiles/Usernames simultaneously to different servers

### ISSUE THREAD

**Issue by jittygitty** [vector-im/element-android#6060]
#### What would you like to do?
What if you want to have multiple separate identities not tied to each other? (so Aliases as per #6058 won't work for this)
I'd like to be able to have some (tab?drawer?) interface supporting multiple PROFILES so you can login to different servers with different usernames at the same time.

#### Why would you like to do it?
Currently, to support joining rooms and servers as a different person/profile, I think you'd have to connect from different App instances, you'd have to install a different app apk package name for each username/server you want to login to.

#### How would you like to achieve it?
Pleading? Begging? Paying?

**Comment by bbhtt** [comment]
This is https://github.com/vector-im/element-android/issues/26

**Comment by jittygitty** [comment]
@bbhtt Thanks! Wow I didn't know so MANY people wanted the same thing for SO LONG.
