### ISSUE TITLE
Is typing UI bricked

### ISSUE THREAD

**Issue by DoM1niC** [vector-im/element-android#6063]
![Screenshot_20220514-211231.jpg](https://user-images.githubusercontent.com/1436958/168555184-8034c7ab-2a8b-49e4-8dfd-bd90eb6aef81.jpg)

Typing indicator is not fully visible after last changes on develop code

**Comment by bmarty** [comment]
Thanks for reporting. Will fix before the next release. Also the timeline is visible below the typing indicator (issue visible when scrolling). Will fix that too.

**Comment by DoM1niC** [comment]
Fixed by https://github.com/vector-im/element-android/pull/6072
