### ISSUE TITLE
Crash when opening big size picture

### ISSUE THREAD

**Issue by forkliang** [vector-im/element-android#6071]
### Steps to reproduce

I was recieving a big picture (about 15mb), and when i open it the element just crashed.

### Outcome

i want to view the picture.
crashed unexpectedly

### Your phone model

umi

### Operating system version

Android 12

### Application version and app store

Element Version 1.4.14, olm version 3.2.10 from Google Play Store

### Will you send logs?

No

**Comment by bbhtt** [comment]
This is probably related to/same as https://github.com/vector-im/element-android/issues/5867, if you can sending logs will help or you can capture it via `adb logcat`

**Comment by ouchadam** [comment]
Thanks for raising! 

Most logs will point to `out of memory` exceptions, or crashes at random points due to the system force quitting the app due to requesting too much memory too quickly. 

going to centralise the issue to https://github.com/vector-im/element-android/issues/2642
