### ISSUE TITLE
F-Droid can't build - org.maplibre.gl:android-sdk pulls in non-FOSS Google Services

### ISSUE THREAD

**Issue by licaon-kter** [vector-im/element-android#6100]
### Steps to reproduce

Try to build for fdroid... gradle dependencies for `fdroidRelease*` says:
```
+--- org.maplibre.gl:android-sdk:9.5.2
|    +--- org.maplibre.gl:android-sdk-geojson:5.9.0
|    |    \--- com.google.code.gson:gson:2.8.6
|    +--- com.mapbox.mapboxsdk:mapbox-android-gestures:0.7.0
|    |    +--- androidx.core:core:1.0.0 -> 1.7.0 (*)
|    |    \--- androidx.annotation:annotation:1.0.0 -> 1.3.0
|    +--- org.maplibre.gl:android-sdk-turf:5.9.0
|    |    \--- org.maplibre.gl:android-sdk-geojson:5.9.0 (*)
|    +--- androidx.annotation:annotation:1.0.0 -> 1.3.0
|    +--- androidx.fragment:fragment:1.0.0 -> 1.4.1 (*)
|    +--- com.squareup.okhttp3:okhttp:3.12.3 -> 4.9.3 (*)
|    \--- com.google.android.gms:play-services-location:16.0.0
```

Since: https://github.com/vector-im/element-android/commit/824e713c51c5aa5b89a85ed5e4c105f5e76a4ba8

### Outcome

Can't build from FOSS deps

### Will you send logs?

No

**Comment by licaon-kter** [comment]
Element 1.13.18 or later _(first one published by F-Droid since it skipped 1.13.16/17)_

And @SpiritCroc Schildi Chat 1.4.4.sc50 or later

**Comment by licaon-kter** [comment]
Will rebuild with this fix https://github.com/deltachat/deltachat-android/pull/2303 to test now

**Comment by bmarty** [comment]
Thanks for opening the issue.

We could try the same fix than https://github.com/deltachat/deltachat-android/pull/2303

Also we could add a check of issue like that to our CI. F-Droid team is working on a standalone version of the F-Droid scanner. So this will be for later.

Labelled as `S-Critical` as it's preventing F-Droid version from being released.

**Comment by ouchadam** [comment]
if the dependency exclusion doesn't work we may need to exclude the feature from the fdroid variant

**Comment by licaon-kter** [comment]
While DeltaChat [builds fine and clean](https://github.com/deltachat/deltachat-android/pull/2303#issuecomment-1132780477) it's not the same here. gms classes are still inside the APK.

I've [edited](https://github.com/vector-im/element-android/blob/v1.4.16/vector/build.gradle#L513) from `implementation 'org.maplibre.gl:android-sdk:9.5.2'` to `implementation ('org.maplibre.gl:android-sdk:9.5.2') { exclude group: 'com.google.android.gms' }`

Retrying now with the same version 9.4.0, maybe it matters

**Comment by licaon-kter** [comment]
Fails in a different way:
```
> Task :library:ui-styles:compileReleaseJavaWithJavac

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':vector:dataBindingMergeDependencyArtifactsFdroidRelease'.
> Could not resolve all files for configuration ':vector:fdroidReleaseCompileClasspath'.
   > Could not find com.mapbox.mapboxsdk:mapbox-android-accounts:0.7.0.
     Required by:
         project :vector > org.maplibre.gl:android-sdk:9.4.2
```

**Comment by licaon-kter** [comment]
Deps tree for DeltaChat:
```
\--- org.maplibre.gl:android-sdk:9.4.0
     +--- com.mapbox.mapboxsdk:mapbox-sdk-geojson:5.3.0
     |    \--- com.google.code.gson:gson:2.8.6
     +--- com.mapbox.mapboxsdk:mapbox-android-gestures:0.7.0
     |    +--- androidx.core:core:1.0.0 -> 1.3.2 (*)
     |    \--- androidx.annotation:annotation:1.0.0 -> 1.1.0
     +--- com.mapbox.mapboxsdk:mapbox-android-accounts:0.7.0
     |    \--- androidx.annotation:annotation:1.0.0 -> 1.1.0
     +--- com.mapbox.mapboxsdk:mapbox-sdk-turf:5.3.0
     |    \--- com.mapbox.mapboxsdk:mapbox-sdk-geojson:5.3.0 (*)
     +--- androidx.annotation:annotation:1.0.0 -> 1.1.0
     +--- androidx.fragment:fragment:1.0.0 -> 1.2.4 (*)
     \--- com.squareup.okhttp3:okhttp:3.12.3
          \--- com.squareup.okio:okio:1.15.0
```

**Comment by bmarty** [comment]
It should work fine.

It's already done here: https://github.com/vector-im/element-android/blob/main/vector/build.gradle#L489 FWIW.

OOI what is the meaning of `/LE` ?

**Comment by licaon-kter** [comment]
Later Edit :)

Not sure why you've linked to JitsiMeet... this issue is about gms brought by maplibre...as all my posts above show

:confused:

**Comment by bmarty** [comment]
Out Of Interest :)

I wanted to point out that we are already excluding the group for another of our dependency: `exclude group: 'com.google.android.gms'`. So it should work the same for MapLibre.

**Comment by licaon-kter** [comment]
Confirmed fixed in: ae9922a7319a62730fc3c25dc8bab3a8b6f8ef43

VT: https://www.virustotal.com/gui/file/1df50475eae518671fd947245f3607e09c1ad38c1e467f0d9d5bb413bb5bfc30/details

**Comment by ouchadam** [comment]
@licaon-kter thanks for confirming! :100:

**Comment by licaon-kter** [comment]
Disabled old ones: https://gitlab.com/fdroid/fdroiddata/-/commit/2113d686eb3ee4525ef141a39e095ea4e37e2653

@SpiritCroc fyi https://gitlab.com/fdroid/fdroiddata/-/commit/0507813723a4551d2eb0428b4454d7bc04e75ecc
