### ISSUE TITLE
Change of Number at the beginning of a message

### ISSUE THREAD

**Issue by Duschenkiller** [vector-im/element-android#6116]
### Steps to reproduce

Write any date in the Element desktop programm, which converts it into a list.  Following Screenshot shows the message displayed in the desktop app:
![Bug report](https://user-images.githubusercontent.com/105990583/169666087-bff6c731-35c6-456d-89dd-592b69a3a448.png)
Now look at the message in the android app.

#### What did you expect?
The same message as it is displayed in the desktop programm.
#### What happened instead?
The number got converted/rearranged. Following screenshot shows the message displayed in the android app:
![Bug Report 2](https://user-images.githubusercontent.com/105990583/169666262-899ef3e8-ee1a-42d5-8a91-8f1279261372.jpg)
The bug was found when i wrote a date and accidentally started a list (eg.: 13. May is my birthday), which was then converted and displayed as a completely diffierent date in the android app. So all of my friends now think that my birthday is at 1. May :/

### Will you send logs?

No

**Comment by ouchadam** [comment]
thanks for raising, it looks like you're encountering #4777 (initial positions in numbered lists not being taken into account) as the way you're writing the date is markdown syntax for a numbered list

Going to close this in favour of #4777
