### ISSUE TITLE
Android app does not show correct poll data

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-android#6121]
### Steps to reproduce

1. Start an open poll and vote
2. Have some other people vote as well
3. Look at the poll on Android

#### What did you expect?
I can see the poll, correct number of votes and correct results

#### What happened instead?
Sometimes the poll looks like I haven't voted.
Sometimes it looks like there have been fewer votes than in reality

### Your phone model

Pixel 2

### Operating system version

Android 11

### Application version and app store

1.4.16 [40104162] (G-b8288)

### Will you send logs?

Yes

**Comment by ouchadam** [comment]
I've noticed the update being a little slow but the counts seems correct for me, marking as uncommon for now~

**Comment by kittykat** [comment]
FYI, there's at least two of us still seeing the wrong data days later

**Comment by kavemang** [comment]
In elememt android i try voting and the selection i press blinks but the vite doesnt appear to go through, only after closng the vote does results appear but the results are incorrect with some chat members unable to vote at all, the same poll works correctly in element desktop in the same homeserver
