### ISSUE TITLE
Allow .well-known configuration to override key sharing mode

### ISSUE THREAD

**Issue by jmartinesp** [vector-im/element-android#6147]
#### What would you like to do?

The home servers can add the configuration variable `outbound_keys_pre_sharing_mode` into `io.element.e2ee` in their `/.well-known/matrix/client` url so they can override how keys are shared in a room. As an example:

```
"io.element.e2ee": {
  "outbound_keys_pre_sharing_mode": "on_typing" // (on_room_opening, on_typing, disabled)
}
```

If this variable is not added, the default value in `BuildConfig.outboundSessionKeySharingStrategy` will be used.

**Comment by bmarty** [comment]
`disabled` means that default will be used?

**Comment by bmarty** [comment]
Ah there is a `pre` in `outbound_keys_pre_sharing_mode`, so that now clear for me. Please ignore me!
