### ISSUE TITLE
App crashed

### ISSUE THREAD

**Issue by chagai95** [vector-im/element-android#6180]
### Steps to reproduce

crashed when creating a new space:
new space -> private - > me only -> loading -> crash

#### What did you expect?
Finish creating the space
#### What happened instead?
Crash

### Your phone model

Xiaomi 11

### Operating system version

Android 12

### Application version and app store

Element dbg - testing version

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by bmarty** [comment]
You are on branch `experiment/eric/space-switching-modal` and apparently the drawer has been removed there. So we get:

Exception: java.lang.IllegalArgumentException: No drawer view found with gravity LEFT

CC @ericdecanini

**Comment by fedrunov** [comment]
This was temporary  branch for App Layout experiment and it was never meant to be merged to develop, so I'll close this issue.
