### ISSUE TITLE
App will not show images with a filesize above 5 MB

### ISSUE THREAD

**Issue by Bueddl** [vector-im/element-android#6190]
### Steps to reproduce

1. Send an image with a size larger than 5 MB (5242880 Bytes) as a message in a room
2. Wait for it to be uploaded
3. Optionally tap on the image to enlarge it

#### What did you expect?

The image should be rendered.

#### What happened instead?

There is a blank space where the image should be. It does not matter whether the image is sent by someone else or on a different client. If it is uploaded from the local client then it will just be visible until the image has been sent and disappear afterwards.

The image is neither displayed in the room directly nor in the view that appears when tapping on the image.

Outcome: https://files.bueddl.de/files/Screenshot_20220530_154211_im.vector.app.jpg (above is the 5 MB image, the empty space should show the other image that is 2 bytes larger than 5 MB).

---

I have attached two test images for testing. One that is exactly 5 MB (5242880 Bytes) that is displayed in the Android app and one that is 2 Bytes larger which is not displayed in the app. We tested with a bunch images with different sizes, however these two should be enough to reproduce. Note that we only tested with png images.

[PNG-Image file with exactly 5 MB (5242880 Bytes)](https://files.bueddl.de/files/Image_5242880Bytes_5MB.png)
[PNG-Image file that is 2 Bytes larger than 5 MB (5242882 Bytes)](https://files.bueddl.de/files/Image_5242882_2BytesAbove5MB.png)

Let me know if I can help or if you need more informations!

### Your phone model

Huawei P10 Lite

### Operating system version

Android 9

### Application version and app store

Element version 1.4.14 [40104142], OLM version 3.2.10

### Will you send logs?

Yes

**Comment by ouchadam** [comment]
this may have been fixed with https://github.com/vector-im/element-android/pull/6290 (likely to be part of v1.4.22)
