### ISSUE TITLE
Remove usage of ffmpeg-kit

### ISSUE THREAD

**Issue by jmartinesp** [vector-im/element-android#6203]
#### What would you like to do?

Remove all usages of the [ffmpeg-kit library](https://github.com/tanersener/ffmpeg-kit).

#### Why would you like to do it?

Currently we use ffmpeg-kit to transcode voice recording to and from ogg files with opus codec on Android versions < 10. This is a bit of an overkill, and it's also a problem for some of our customers. It should also save us a few MBs on app size.

#### How would you like to achieve it?

We can remove ffmpeg-kit and use libopus and libopusenc instead.

### Have you considered any alternatives?

Yes, I tried several replacement libraries but in the end the simpler solution was to use the native libs for transcoding.

**Comment by bmarty** [comment]
Please double check that the license (https://github.com/xiph/libopusenc/blob/master/COPYING) is fine for our usage.

**Comment by jmartinesp** [comment]
> Please double check that the license (https://github.com/xiph/libopusenc/blob/master/COPYING) is fine for our usage.

It's BSD so it shouldn't be a problem.
