### ISSUE TITLE
After switching to a different room from shortcuts, pressing back doesn't take back to the previous room

### ISSUE THREAD

**Issue by alittlebitofit** [vector-im/element-android#6211]
### Steps to reproduce

1. Open any room (let's call this room 1)
2. Open drawer menu by swiping from left to right to find list of rooms shortcut.
3. Goto room 2.
4. Press back.

#### What did you expect?
To go back to room 1.

#### What happened instead?
Room/Chat screen is opened.

### Operating system version

Android 12

### Application version and app store

1.4.14 [40104140] (F-06830853)

### Homeserver

1.4.14 (06830853)

### Will you send logs?

No

**Comment by bmarty** [comment]
The left drawer contains the breadcrumbs, i.e. the last viewed rooms. There is no back pagination from there, to go back to the first room, you have to open again the drawer, and the room should be now at the second position from top. This is used to quickly switch between several active rooms. We cannot add back pagination here, it would be bad UX.
