### ISSUE TITLE
Wrong Voice Messages will playback in Timeline

### ISSUE THREAD

**Issue by DoM1niC** [vector-im/element-android#6213]
### Steps to reproduce

1. Record and Playback a Voice Message
2. Scroll and Playback some another Voice Messages

#### What did you expect?
Plays correct Voice Messages what I send and Playback first

#### What happened instead?
Something is not correct and plays different Voice Messages mostly with the same time what I started to listen first and Pause / Play Event is bricked too...

### Your phone model

Oneplus N10

### Operating system version

Android 11

### Application version and app store

Develop

### Homeserver

messenger.3dns.eu based on Synapse 1.60.0

### Will you send logs?

No

**Comment by KeenMaron** [comment]
I can confirm this issue. Only one friend has this problem on my matrix server with element. Hope it will be fixed soon.
