### ISSUE TITLE
[bug] not possible to verify Android Version

### ISSUE THREAD

**Issue by sl5net** [vector-im/element-android#6220]
### Steps to reproduce

1. for weeks i enabled a other Beta-Feature at Linux Client Element. works very well
2. then i enabled this other Beta-Feature at Android Client Element. not works. it waits for server response for days, and it still wait at the moment.
3. i disabled the beta at linux desktiop (no effect)
4. i reinstalled the andoid version  (no effect) it still waits for sever response
5. and at same time it tries verification (Desktop as for QR-Code or Emoji Verification) but Android is in deadLock. to problems at same times seems to be not possible to solve for it. so i stack with to problems. and i cant use Android Element not any more

BTW the german cumunity also now it. i long time user in this room:  #german:matrix.org

### Outcome

verification the android element version

its blocked (dedlock) because android could not handle this two problems as same time (see  description  above)

### Operating system

Ubuntu and Andoid

### Application version

Element newest Version at both devices
Desktop Version:
Element version: 1.10.13
Olm version: 3.2.8

### How did you install the app?

the Andoid is from Google Play Store

### Homeserver

tchncs.de

### Will you send logs?

Yes but the android is blocked, so i cant send the anroid logs.
but i have sended the linux-Desktop logs here: https://github.com/vector-im/element-web/issues/22387

#### What did you expect?
- waiting for server-antword will end a day. but it stays already for many days
- allows me to identify my desktop, but its blocked by the other message. (deadlock)

#### What happened instead?

all is blocked by the other message, waiting for server-answer (deadlock).
please read also here: https://github.com/vector-im/element-web/issues/22387
![photo_2022-06-01_12-14-43](https://user-images.githubusercontent.com/5634759/171381848-46fa55c2-716c-4710-9fdb-6d52c341db72.jpg)
![photo_2022-06-01_12-14-59](https://user-images.githubusercontent.com/5634759/171381972-e60da4c0-e577-4259-8f00-12f46fbc0cfb.jpg)

### Your phone model

Samsung S8

### Operating system version

Ubuntu and Andoid Version 9

### Application version and app store

Element newest Verson at both devices

### Homeserver

tchncs.de

### Will you send logs?

Yes

### Are you willing to provide a PR?

Yes

**Comment by sl5net** [comment]
Means i could not use Android since more then 5 days? Any idea? Do i really create a new account? Android is still waiting for server response. Sometimes i click in Deskop-Version(Ubuntu) Verifiy and it tells my then first "Verify other device ... To proceed, please accept the verification request on your other device". And then Seconds later Ubuntu says "Verification timed out. Start verification again from the notification."
no chance to do anything on the Android App. Any Idea what i could do?

**Comment by sl5net** [comment]
Still not able to login. Still this message: **first sync. waits for server response**

**Comment by sl5net** [comment]
if i use web-browser in android it looks like so:
![photo_2022-06-14_13-14-31](https://user-images.githubusercontent.com/5634759/173564880-e607dbfe-db08-484d-aa09-e7f66419d616.jpg)
anything else i could try? please help please please please please

**Comment by sl5net** [comment]
now its solved. i dont know what happens. maybe it was helpful (last step) to install fluffy. now element and fluffy working correct

**Comment by verymilan** [comment]
this is acutally related to https://github.com/matrix-org/synapse/issues/12820 – as of a few synapse releases, people sometimes get this error and can't login. as related missing event errors and resolve howtos do not apply here and i can't even see this with loglevel INFO, i've used to lookup the room that event belongs to and removed the room.
now this here was solved while i was updating synapse. i cannot tell if that's related... .

**Comment by fedrunov** [comment]
Closed as solved. Since no changes were done feel free to rise again if you face same issue again
