### ISSUE TITLE
How do I exit from Element app?

### ISSUE THREAD

**Issue by vi** [vector-im/element-android#6224]
#### What would you like to do?

Exit from Element app, so it won't consume network or show the notification.

Obviously, without any removal of any E2E keys, as done with "Sign out" item.

#### Why would you like to do it?

* Temporarily opt out of receiving any notifications and avoid being seen as online
* Save network bandwidth while being able to get back online quickly, without entering any password or restoring any keys.
* Check if logging in still works while configuring backend.

#### How would you like to achieve it?

Menu item neighbouring "Sign out".

#### Workaround

Seems like "Force close" from Android does what I want, but it is a clumsy UI and it does not feel right to use it regularly.

### Are you willing to provide a PR?

No

**Comment by ganfra** [comment]
You can just disable notification for your session and close the app so it won't consume anything in background.

**Comment by rom1v** [comment]
Same problem here, I can't "exit" and remove the Element icon from the notification bar.

"Force close" works, but it's not very user-friendly.

**Comment by rom1v** [comment]
Oh, you can disable it in Preferences → Notifications → Background Sync Mode → No background sync.
