### ISSUE TITLE
The ability to change the integration server on android

### ISSUE THREAD

**Issue by mateusfmcota** [vector-im/element-android#6235]
#### What would you like to do?
To be able to change the integration server on mobile.

#### Why would you like to do it?
The homeserver and element-web that I use has a custom integration server with custom stickers, bots and more but I can't find a way to change to it on the android version of element.

#### How would you like to achieve it?
By giving an option to change from the default one to a custom one.

### Are you willing to provide a PR?

No

**Comment by ganfra** [comment]
The integration manager is configurable from your server with wellknown. Check here: https://github.com/vector-im/element-android/issues/2717

**Comment by ata-star** [comment]
and if you dont have the resources to host a synapse server???
