### ISSUE TITLE
Mic is shown on text message notification during a call

### ISSUE THREAD

**Issue by 532910** [vector-im/element-android#6251]
A copy of https://github.com/vector-im/element-android/issues/4142 as it has been closed and ignored.

### Steps to reproduce

1. Make a voice call
2. Send a message

![image](https://user-images.githubusercontent.com/14617699/135715963-8c845d8b-7e0d-4294-ace7-b543d73df15e.png)

### Operating system version

Android 11

### Application version and app store

The latest beta from GPlay

### Have you submitted a rageshake?

No

**Comment by ganfra** [comment]
I think the icon is added by the system as we are using the microphone, so nothing we can prevent from.
