### ISSUE TITLE
Own message can't be "Unread"

### ISSUE THREAD

**Issue by 532910** [vector-im/element-android#6255]
### Steps to reproduce

I dunno how to reproduce it.
![image](https://user-images.githubusercontent.com/14617699/172506134-039d5c3b-622c-4a41-b93b-bc193d66159f.png)

### Operating system version

Lineage+microG 18.1 on Android 11

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by ganfra** [comment]
The unread marker show you what was the last message you had seen before closing the conversation. If you open it should update.
