### ISSUE TITLE
Rageshake submission dialog should default screenshots to off

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-android#6261]
#### What would you like to do?
Not send screenshots with a rageshake by default

#### Why would you like to do it?
Because it's too easy to miss that a screenshot is being attached, so too easy to send one by default and at least in my case the screenshots are rarely relevant to the rageshake or often contain private data

#### How would you like to achieve it?
By defaulting the screenshot option to off

### Are you willing to provide a PR?

No

**Comment by ouchadam** [comment]
Fixed in 1.4.24
