### ISSUE TITLE
"Show all rooms in Home" doesn't work in 1.4.19 at all

### ISSUE THREAD

**Issue by waclaw66** [vector-im/element-android#6272]
### Steps to reproduce

It was working (at least for a while... [#4131](https://github.com/vector-im/element-android/issues/4131)) in 1.4.16, but that switch has no effect in 1.4.19. All rooms are shown in Home regardless of the switch state.

#### What did you expect?
Proper rooms filtering.

#### What happened instead?
"Show all rooms in Home" switch doesn't work at all.

### Your phone model

Samsung Galaxy S20 FE

### Operating system version

Android 12

### Application version and app store

Element: 1.4.19

### Homeserver

own

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by BillCarsonFr** [comment]
Regression introduced by https://github.com/vector-im/element-android/pull/6143

Calling `roomId?.toActiveSpaceOrOrphanRooms()` instead of `roomId.toActiveSpaceOrOrphanRooms()`
as a consequences for null current space will always return null (so no filter on space) instead of Orphan filter
