### ISSUE TITLE
Crashloop after sharing a link

### ISSUE THREAD

**Issue by WRMSRwasTaken** [vector-im/element-android#6286]
### Steps to reproduce

After sharing a Link (the link in question: https://www.reddit.com/r/Ubiquiti/comments/v9gkl4/who_else_is_about_to_start_their_own_datacenter/ ) from the Discord mobile app to Element and closing it afterwards, I am no longer able to open the app. It seems to be crashlooping / freezing on the main screen. 

Unfortunately. logcat doesn't seem to be much of a help here. I enabled `SETTINGS_LABS_ALLOW_EXTENDED_LOGS` via another app because I am unable to open Element, but there are no stack traces at all. Also the homeserver does not seem to log any problems while this is happening.

I am expecting a problem with the URL preview feature, but disabling it (setting `SETTINGS_SHOW_UTL_PREVIEW_KEY` to false) does not seem to help either.

Video of the problem:
https://user-images.githubusercontent.com/4244869/173191210-c48341aa-dd00-452c-b237-43daf0ab2b59.mp4

Logs while running `adb logcat` and opening Element:
[putty.log](https://github.com/vector-im/element-android/files/8884068/putty.log)

I am out of Ideas on how to troubleshooting this further. Force-closing the app and deleting the cache does not yield and better results. And deleting application data (resetting the app) isn't really an option for me as this might let the (potential bug) vanish.

#### What did you expect?
Continued normal app behavior
#### What happened instead?
A completely unusable app due to a crash/freezeloop

### Your phone model

OnePlus 6

### Operating system version

Android 11 - Havoc OS 4.16, rooted, no google play services

### Application version and app store

1.4.14 F-Droid

### Homeserver

Synapse 1.59.1

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by ouchadam** [comment]
this may have been fixed in a newer version, 1.4.20 should be returning to fdroid soon :crossed_fingers:

**Comment by WRMSRwasTaken** [comment]
Updating to 1.4.20 made this problem disappear.
