### ISSUE TITLE
Element changing content of dates sent when sent from iOS/Desktop to Android

### ISSUE THREAD

**Issue by HonkXL** [vector-im/element-android#6310]
### Steps to reproduce

Send a message that contains this text
`23. Juni, um 17:00 Uhr`

from iOS or Windows Desktop to a receiver that uses the Android, the Android device shows this text:
`1. Juni, um 17:00 Uhr`

Problem is reproducable. See attached screenshot. Right side is screen of Sender (iOS), left side is screen of Receiver (Android).

![element-date](https://user-images.githubusercontent.com/16715040/173798183-3d98f3fb-1431-4e22-8f28-442a4990f85f.jpg)

#### What did you expect?

sent text should be shown on device of receiver

#### What happened instead?

Content of date has been changed.

### Your phone model

Samsung 21 Ultra

### Operating system version

Android 12

### Application version and app store

1.4.15 [40104162] (G-b8288)

### Homeserver

private homeserver, Synapse 1.60.0

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by ouchadam** [comment]
this is an unfortunate instance of the markdown engine acting on `21.` [as a list](https://github.com/vector-im/element-android/issues/4777), however I'm suspicious that we're applying markdown formatting to a raw text message

**Comment by ouchadam** [comment]
partially fixed by #6357 and will be available in 1.4.26 (we no longer apply markdown conversion to raw text)

The reassignment of list number values is handled by #4777
