### ISSUE TITLE
Login not possible - JsonDataException at $.m.homeserver

### ISSUE THREAD

**Issue by guedressel** [vector-im/element-android#6347]
### Steps to reproduce

On Sign-In Screen (After "I already have an account") I select "Sign in with Matrix ID" or "Other" (custom home server).

### Outcome

After entering my ID or Server name an Exception Screen is show and I can't continue.

> com.squareup.moshi.JsonDataException: Expected BEGIN_OBJECT but was STRING at path $.m.homeserver

![Screenshot_20220619-114816_Element](https://user-images.githubusercontent.com/1841616/174475930-b4fa98a3-3fa0-43ad-a626-9dc109ab66cb.png)

### Your phone model

Xiaomi Mi 8 and Samsung Tab S6 lite

### Operating system version

Lineage OS 18 and 19

### Application version and app store

Google Play Store: 1.4.20

### Homeserver

Synapse: 1.61

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by ouchadam** [comment]
thanks for raising, my suspicion is that your homeserver `.wellknown` is incorrectly configured, returning raw text instead of a json object, see https://matrix.org/.well-known/matrix/client

Notice the opening and closing braces 
```
{
    "m.homeserver": {
        "base_url": "https://matrix-client.matrix.org"
    },
    "m.identity_server": {
        "base_url": "https://vector.im"
    }
}
```

**Comment by guedressel** [comment]
Thank you @ouchadam - your suspicion was right: I used the same information in `https://{homeserver}/.well-known/matrix/client` as in `https://{homeserver}/.well-known/matrix/server`. But that's not correct.  
Here is the relevant documentation: https://spec.matrix.org/unstable/client-server-api/#well-known-uri

Thanks for all your work!
You do a great job.

**Comment by ouchadam** [comment]
glad to hear it's sorted! :100:
