### ISSUE TITLE
Some messages show punctuation in Unicode 

### ISSUE THREAD

**Issue by th0mcat** [vector-im/element-android#6388]
### Steps to reproduce

Open up a chat, write a message with punctuation, hit send.

#### What did you expect?
The message to look normal.

#### What happened instead?
Punctuation is shown in Unicode.

![Screenshot_20220627-220534~2](https://user-images.githubusercontent.com/37344783/176083456-e8a13417-3094-4e6a-af82-4a64e7dd7ea8.png)
![Screenshot_20220627-220508~2](https://user-images.githubusercontent.com/37344783/176083459-4f34a126-6f65-4743-bfcf-a9eb03654b76.png)
![Screenshot_20220627-220429~2](https://user-images.githubusercontent.com/37344783/176083460-2eb5179e-10cf-4df7-95c2-f1ea7dfa1f8d.png)

### Your phone model

Google Pixel 6

### Operating system version

GrapheneOS SQ3A.220605.009.B1.2022062200

### Application version and app store

1.4.26-dev [211782102] (F-b9268) develop

### Homeserver

thomcat.rocks

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by scottwallacesh** [comment]
I'm seeing this on: `1.4.26 [40104262] (G-b9381)`

**Comment by ouchadam** [comment]
thanks for the updates :+1:  this has been fixed by https://github.com/vector-im/element-android/pull/6447 and will be part of 1.4.28
