### ISSUE TITLE
Reproducible Builds

### ISSUE THREAD

**Issue by genofire** [vector-im/element-android#6421]
#### What would you like to do?
Reproducible Builds, to check and validated Builds

#### Why would you like to do it?
Switching between F-Droid and own Nightly Builds (like in #5803 ) without losing Data and valid signatures check.

#### How would you like to achieve it?
https://f-droid.org/docs/Reproducible_Builds/

### Are you willing to provide a PR?

No

**Comment by bmarty** [comment]
I guess the signature and appIds will be different for all those app versions, so it will not be possible to switch from one version to another. But it will be possible to install them in parallel on the same device.

**Comment by genofire** [comment]
Thats, what i do -> @vector-im does no build / publish the F-Droid Build-Flavor / AppID.

But if you build the f-droid **build-flavor** / same AppID:
- publish that build on f-droid
- here in github-releases
- on an nightly "way" (like an own f-droid repo)

it would be nice to switch between them.

As an example, the CCTG-App:
- F-Droid: https://f-droid.org/en/packages/de.corona.tracing/
  - With own signature
  - was fetched from CCTGs Server (and F-Droid just validate that Build by building it on his own) 
- Beta F-Repo Repo: https://bubu1.eu/cctg/fdroid/repo/?fingerprint=f3f30b6d212d84aea604c3df00e9e4d4a39194a33bf6ec58db53af0ac4b41bec

**Comment by fedrunov** [comment]
Hi, thank you for rising this issue, but unfortunately we are not planning to support reproducible builds for this moment. I'll close this issue
