### ISSUE TITLE
[SDK] Gradle - Could not find com.github.Zhuinden:realm-monarchy:0.7.1.

### ISSUE THREAD

**Issue by pieomy** [vector-im/element-android#6433]
### Description

Hi, 

I'm using Gradle command line tool, but I can't build 'org.matrix.android:matrix-android-sdk2:1.2.1' 
all Zhuinden repos 404. is this dependency still active? 
Thanks

> Gradle -q getDeps FAILURE: Build failed with an exception.* What went wrong:Execution failed for task ':getDeps'.> Could not resolve all files for configuration ':myConfig'.   > Could not find com.github.Zhuinden:realm-monarchy:0.7.1.     Searched in the following locations:       - https://repo.maven.apache.org/maven2/com/github/Zhuinden/realm-monarchy/0.7.1/realm-monarchy-0.7.1.pom       - https://dl.google.com/dl/android/maven2/com/github/Zhuinden/realm-monarchy/0.7.1/realm-monarchy-0.7.1.pom       - https://jcenter.bintray.com/com/github/Zhuinden/realm-monarchy/0.7.1/realm-monarchy-0.7.1.pom     Required by:         project : > org.matrix.android:matrix-android-sdk2:1.2.1   > Could not find org.matrix.gitlab.matrix-org:olm:3.2.4.     Searched in the following locations:       - https://repo.maven.apache.org/maven2/org/matrix/gitlab/matrix-org/olm/3.2.4/olm-3.2.4.pom       - https://dl.google.com/dl/android/maven2/org/matrix/gitlab/matrix-org/olm/3.2.4/olm-3.2.4.pom       - https://jcenter.bintray.com/org/matrix/gitlab/matrix-org/olm/3.2.4/olm-3.2.4.pom     Required by:         project : > org.matrix.android:matrix-android-sdk2:1.2.1* Try:> Run with --stacktrace option to get the stack trace.> Run with --info or --debug option to get more log output.> Run with --scan to get full insights.* Get more help at https://help.gradle.orgBUILD FAILED in 7s

![Zhuinden 01](https://user-images.githubusercontent.com/49295522/176782202-2cff57fd-ab06-40b3-83e9-035c3e756bf0.png)

![Zhuinden 02](https://user-images.githubusercontent.com/49295522/176782216-b6c4fe21-a1c5-411c-a779-300632ca2e31.png)

**Comment by bmarty** [comment]
Yes, Monarchy is still used.

Can you try to clone and build the sample app, to see if you have the same issue? This is this project: https://github.com/matrix-org/matrix-android-sdk2-sample

**Comment by ouchadam** [comment]
the artifact is provided by jitpack https://jitpack.io/#Zhuinden/realm-monarchy/2.0.0
