### ISSUE TITLE
[Feature request] Option to have a unified chat list for Rooms and DMs

### ISSUE THREAD

**Issue by nathanael-h** [vector-im/element-android#6442]
#### What would you like to do?
I would like to have a unified chat list for Rooms and DMs. 

#### Why would you like to do it?
I have a lot of chats that are relayed via bridges, from and to Signal and Whatsapp for example, and I found it irrelevant to have one list for Rooms and one list for DMs. Maybe I think that because on these apps (Signal, Whatspp) there is only one chat list. 

Also, some new users found that this two lists UI is strange. Moreover when we mix this with spaces, it could be sometimes long to find where is a conversation (many touch, which space, which list). 

I looked in the issues, but found nothing about this topic. Sorry if this is a duplicate. 

#### How would you like to achieve it?
This UX change cool be implemented as an opt-in option, or if UX team think this improve the overall experience as the default interface and opt-out option. I know that there is a lot of work done about first user experience, easy on-boarding, this issue could fall there I think. 
I also saw some work done on Element (X?) for iOS for custom user interface. I do not know it this is also on the roadmap for Android. 

I have another strange idea, but not sure about this... Global DMs and Rooms list could be available in the drawer-menu as "virtual" lists, or "fake-spaces"... 

### Have you considered any alternatives?

I tried the fork of element [SchildiChat](https://github.com/SchildiChat/SchildiChat-android) and had a good experience with this. I thought that maybe others could have the same opinion, and so this feature could be upstreamed. 

### Are you willing to provide a PR?

No

**Comment by bbhtt** [comment]
Duplicate of https://github.com/vector-im/element-android/issues/650

**Comment by nathanael-h** [comment]
Indeed it is a duplicate sorry I did not found #650
