### ISSUE TITLE
F-Droid build failed: Missing source code for binary files

### ISSUE THREAD

**Issue by TheLastProject** [vector-im/element-android#6444]
1.4.26 adds several .so binaries: https://github.com/vector-im/element-android/tree/v1.4.26/library/opusencoder/src/main/cpp/opus/libs

The build instructions point directly to these binary files: https://github.com/vector-im/element-android/blob/v1.4.26/library/opusencoder/src/main/cpp/CMakeLists.txt

As per F-Droid policy, everything needs to built from source. Could you please provide build instructions for these files, so that the F-Droid build can be fixed? See https://gitlab.com/fdroid/fdroiddata/-/merge_requests/11270 for the current build recipe.

**Comment by bmarty** [comment]
@jmartinesp can you help on that please?
