### ISSUE TITLE
Room overview renders code as markdown

### ISSUE THREAD

**Issue by Bueddl** [vector-im/element-android#6446]
### Steps to reproduce

1. Send a message containing a code block that contains markdown code (or something that can be interpreted as markdown).   
2. Switch to the room overview
3. The overview renders the message preview as if the code block is not there at all and just renders the markdown  

![Message containing a code block with markdown](https://i.imgur.com/kBofujP.jpg)
![Message rendered in room overview](https://i.imgur.com/zHY3c8u.jpg)

#### What did you expect?

To see a code block in the preview (as is in the message).

#### What happened instead?

The markdown within the code block got rendered instead.

### Operating system version

Android 9

### Application version and app store

Element version 1.4.25 [40104252], OLM Version 3.2.12

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by Bueddl** [comment]
I am not sure but this might be related to #2443.

**Comment by cloudrac3r** [comment]
This is fixed by my #6357 which is in release 1.4.26. Try updating.

**Comment by Bueddl** [comment]
Thanks for the reply! 1.4.25 is the most recent version I got through Google Play (maybe it has not been rolled out yet for Android 9 or sth.?).
