### ISSUE TITLE
Add custom reaction support

### ISSUE THREAD

**Issue by 10Meisterbaelle** [vector-im/element-android#6459]
#### What would you like to do?
Add support for custom reactions that show a specfic text as a reaction.

#### Why would you like to do it?
Sometimes no emoji reaction is fitting.

#### How would you like to achieve it?
When adding a reaction, you should be able to type in text to submit it as custom reaction.

### Have you considered any alternatives?

Adding the /react command to Element would also be an option

### Additional context

Other Matrix clients already have it with the /react command.
Here is how it looks:
![Screenshot_20220704-225509_Element](https://user-images.githubusercontent.com/45918080/177215747-d651f934-4e96-4b42-b0dc-8ca8b9b70eb6.png)

### Are you willing to provide a PR?

No

**Comment by bbhtt** [comment]
Duplicate of https://github.com/vector-im/element-android/issues/6028

**Comment by 10Meisterbaelle** [comment]
> Duplicate of #6028

Okay, closing issue
