### ISSUE TITLE
Can't get rid of "Verify this session"

### ISSUE THREAD

**Issue by pc00per** [vector-im/element-android#6460]
### Steps to reproduce

It always exists on the top of the screen since the time I logged in. It's frustrating. It reappears, even though I swipe it or skip it.

![Screenshot_20220705_034213](https://user-images.githubusercontent.com/83843264/177221359-7c725def-f971-4432-bdc0-e579d87654a8.png)

I don't want to have another session. Please leave me with just one good session 😐

#### What did you expect?
The popup should go away indefinitely.

#### What happened instead?
It reappears after app reopen.

### Your phone model

Doesn't matter

### Operating system version

Android 12.1

### Application version and app store

1.4.25

### Homeserver

matrix.org

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by kittykat** [comment]
Duplicate of #4318

Thank you for reporting the issue!

**Comment by pc00per** [comment]
"Duplicate of xxxx"
"Kittycat mentioned this issue"
"Kittycat assigned this to xxxx & yyyy"
"Kittycat closed this issue as not planned"

Amazing. Thank you vm for throwing the issue in the garbage completely.
