### ISSUE TITLE
App Layout: List filters

### ISSUE THREAD

**Issue by fedrunov** [vector-im/element-android#6505]
In-list buttons to select predefined filters
[figma](https://www.figma.com/file/Hw4gjP3pknMZUir8jQqmWH/%5BMobile%5D-IA-early-proposals?node-id=2597%3A139878)

![image](https://user-images.githubusercontent.com/66663241/177962055-9e97ebd7-cb12-4e9b-8949-3275512b1b69.png)

- [x] All filter
- [x] Unreads filter
- [x] Favourites filter
- [x] People filter
- [x] Tabs can be disabled, if so All filter is applied
- [x] All tabs are filtered by selected space also
- [ ] Tabs use autosize for text to fit screen
- [x] If user doesn't have any favourites or dm, corresponding tabs should be hidden

**Comment by witchent** [comment]
Can we maybe also have a room filter? I have some very inactive rooms and I'd like to only filter through them.
