### ISSUE TITLE
AppLayout: Filter by name

### ISSUE THREAD

**Issue by fedrunov** [vector-im/element-android#6507]
Widget to allow user filter room list by name

[Figma](https://www.figma.com/file/Hw4gjP3pknMZUir8jQqmWH/%5BMobile%5D-IA-early-proposals?node-id=2597%3A139878)

![image](https://user-images.githubusercontent.com/66663241/177964275-1134ccf0-bec4-415a-adc4-af4c58280210.png)

**Comment by gsouquet** [comment]
@fedrunov @amshakal does the input only filters based on the room name?
I believe we should use the same algorithm that looks at a combination of the room name and the room alias, ...

Some acceptance criteria would be very welcomed here to define a bit more clearly what we're aiming for. But if the android app carries any logic related to room filtering, I'd suggest re-using that
