### ISSUE TITLE
App Layout: Analytics 

### ISSUE THREAD

**Issue by fedrunov** [vector-im/element-android#6508]
TBD

Events gone:
MobileScreen.ScreenName.People
MobileScreen.ScreenName.Rooms

Events changed:

New trigger for opening room (ViewRoom) event from Invites
New trigger for opening room (ViewRoom) event from Unreads
New trigger for opening room (ViewRoom) event from Favourites

**Comment by daniellekirkwood** [comment]
This is related to: https://github.com/vector-im/element-meta/issues/547
