### ISSUE TITLE
"Please wait..." pop-up gets stuck when pressing "Direct Message" to a person that you are alrady on a open channel with

### ISSUE THREAD

**Issue by verycoolperson** [vector-im/element-android#6514]
**Steps to reproduce**

1. Open a chat with someone on your Direct Messages page
2. Press on the other persons profile picture
3. Press the "Direct Message" option

**Outcome**

**What did you expect?**

It should open the chat with that person

**What happened instead?**

The "Please wait..." pop-up gets stuck on screen

**Your phone model**

Samsung A30s

**Operating system version**

Android 11

**Application version and app store**

1.4.27, from GitHub

**Homeserver**

matrix.org

**Will you send logs?**

No

**Are you willing to provide a PR?**

No

**Comment by bmarty** [comment]
Thanks for reporting @verycoolperson .
S-Major since the UI is blocked after the steps.

**Comment by bmarty** [comment]
Fixed in 1.4.30
