### ISSUE TITLE
Double-quote symbols are replaced with &quot; when messages are rendered

### ISSUE THREAD

**Issue by williamkray** [vector-im/element-android#6515]
### Steps to reproduce

1. Write a message like `"hello world"` (inclusive of backticks)
2. send it

#### What did you expect?
the message would be sent, and would look like `"hello world"`
#### What happened instead?
the message is sent and looks like `&quot;hello world&quot;`

### Your phone model

Pixel 4a

### Operating system version

GrapheneOS

### Application version and app store

1.4.26

### Homeserver

mssj.me

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by tulir** [comment]
Duplicate of #6445

**Comment by williamkray** [comment]
closing as a duplicate per tulir's comment
