### ISSUE TITLE
Suggest `@room` when `@channel`, `@everyone`, or `@here` is typed in composer 

### ISSUE THREAD

**Issue by bmarty** [vector-im/element-android#6529]
Currently only `@room` get the completion.

Location of the change: https://github.com/vector-im/element-android/blob/main/vector/src/main/java/im/vector/app/features/autocomplete/member/AutocompleteMemberPresenter.kt#L148

To be iso EleWeb.

See:
- https://github.com/vector-im/element-web/issues/20972
- https://github.com/matrix-org/matrix-react-sdk/pull/7737

**Comment by pt2121** [comment]
Can I take this?
