### ISSUE TITLE
error count new messages on samsung phone desktop

### ISSUE THREAD

**Issue by progserega** [vector-im/element-android#653]
RiotX icon on desktop show new one message on samsung phone, but in app no new messages.
![Screenshot_2019-10-30-23-07-03](https://user-images.githubusercontent.com/1297163/67860770-76380a00-fb6a-11e9-9595-1c6870f8303e.png)
![Screenshot_2019-10-30-23-07-09](https://user-images.githubusercontent.com/1297163/67860788-818b3580-fb6a-11e9-901a-be87a78a6c78.png)

**Comment by bmarty** [comment]
This number is related to the number of notifications from RiotX. And it seems that you do not have any notifications from RiotX...

**Comment by progserega** [comment]
Yes, but RiotX icon have "1" label, that said, that RiotX have notification...

**Comment by progserega** [comment]
This is occur with new Element 1.0.0 on other samsung phone:

![Screenshot_20200719-154534 png](https://user-images.githubusercontent.com/1297163/87868232-47531400-c9d7-11ea-8763-464f1278e9b9.jpeg)
![Uploading Screenshot_20200719-154606.png.jpeg…]()

**Comment by bmarty** [comment]
Old. Please re-open if you still have the problem
