### ISSUE TITLE
Mobile FTUE: Copy and final check

### ISSUE THREAD

**Issue by amshakal** [vector-im/element-android#6547]
Checklist of copy changes we want to implement on both platforms:

Changes checklist:

- [ ] Splash screen https://github.com/vector-im/element-android/issues/6555

- [x] Use case screen:

- Not sure yet? Skip this question
- Remove ‘connect to server CTA’
- Remove full stop from subtitle

- [x] Create account

  - Remove subheading https://github.com/vector-im/element-android/pull/6545
  - The copy changes dynamically under username based on entry [x]  https://github.com/vector-im/element-android/pull/6545
  - Change copy for choosing server
  - Align server name to edit button

- [x] Choose server

  - Change title copy
  - Change subheading copy
  - Remove copy under server URL
  
- [x] Email

  - Change title copy
  - Change subheading copy

- [x] Phone number

  - Change title copy
  - Change subheading copy

- [x] Email confirmation

  - Change subheading

- [x] Policy/T+C

  - Change title copy
  - Change subheading copy

- [ ] Captcha

  - Change icon to robot - Amsha to provide
  - [x] Change title to - are you human?
  - [x] Remove subheading

- [x] Congratulations

  - Change subheading

- [x] Display name

  - Remove subheading
  - Show mxid as display name minus server name
  - Keep save and continue enabled

- [x] Profile picture

  - Change subheading

- [x] Personalisation complete

  - Change title
  - Change subheading

- [x] Sign in

  - Change copy for choosing server
  - Remove copy under server
  - Align server name to edit button
  - Add phone as an option

- [x] Server selection for sign in

Change server to home server

- [x] Forget password - email

  - Change title
  - Change subheading
  - Remove copy from under the text box

- [x] Verify email

  - Change title
  - Change subheading

**Comment by daniellekirkwood** [comment]
Updated copy on login screen and email verification

**Comment by daniellekirkwood** [comment]
On the login screen we need to update the server select and remove the "will" as folks' account data already lives on that server.

On the email verification screen - we updated the subhead copy to remove the excess "email"s

**Comment by ouchadam** [comment]
other copy updates included in https://github.com/vector-im/element-android/pull/6649
