### ISSUE TITLE
All images shared are stored in 'RiotX Pictures'

### ISSUE THREAD

**Issue by ordinarygulp** [vector-im/element-android#655]
Sharing an image, gif, or anything similar to RiotX, stores that image into a folder on the device, usually with multiple versions being saved. This then propagates into gallery apps, which can be unhelpful and spam-like

**Comment by bmarty** [comment]
Yes, I've noticed that too.
I assume it's due to the lib `com.kbeanie:multipicker`
I check that

**Comment by bmarty** [comment]
https://github.com/coomar2841/android-multipicker-library/issues/170 ?

**Comment by dreamerchris** [comment]
I would argue there should be a guide somewhere where people get informed about actions they have to do like in this particular situation to go to their gallery and remove the folder RiotX Pictures from the gallery

**Comment by d2dyno** [comment]
Removing items from gallery every time I share a few images on RiotX is hardly a solution

**Comment by dreamerchris** [comment]
other solution I see is to add a file that is .nomedia or something like that that prevents most galleries from inserting the images from that folder

**Comment by d2dyno** [comment]
Yes that could be a temporary solution. There's really no reason for RiotX to be storing images shared to a server channel though. Let alone storing multiple versions of it.

**Comment by dreamerchris** [comment]
> Removing items from gallery every time I share a few images on RiotX is hardly a solution

I was not refering to images but to the folder, in xiaomi as an example there is the main screen that shows the images from folders that are selected to be viewed. so if the folder RiotX Pictures is in those folders that show in the gallery app it should be excluded.

I agree that it is troublesome for the user to go to each gallery app and do that but I was argueing in a more general sense that there should be a guide that would point actions that a user should do in particular things that are by products of the app itself, but I should propably make another "issue"/proposal about that

**Comment by dreamerchris** [comment]
> Yes that could be a temporary solution. There's really no reason for RiotX to be storing images shared to a server channel though. Let alone storing multiple versions of it.

yeah I would like such functionality myself like: save all images that are shared in your rooms and 1:1 chats in the folder of your choice

**Comment by Michae94** [comment]
Hi, just wanted to say that I have the same issue. If there is a quick fix that we can do by ourselves, I'm more than interested.

**Comment by 532910** [comment]
Is this still actual? While I saw this sometime ago I can't reproduce this

**Comment by Michae94** [comment]
> Is this still actual? While I saw this sometime ago I can't reproduce this

I don't have this problem anymore thanks

**Comment by onurays** [comment]
We implemented our own multipicker library which fixes the problem.
