### ISSUE TITLE
Double quotation appears as &quot; in replies 

### ISSUE THREAD

**Issue by thstyl2000** [vector-im/element-android#6568]
### Steps to reproduce

1. Write sth with "
2. The other end replies to that message. 

#### What did you expect?
To see the replied message as entered. 
#### What happened instead?
Double quotes (") appear as `&quot;`

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by thstyl2000** [comment]
Apparently single quotes are also not rendered from html...

**Comment by bbhtt** [comment]
I think this is https://github.com/vector-im/element-android/issues/6445, it should be fixed in 1.4.28.

**Comment by thstyl2000** [comment]
Yes, looks like it, although in my case it happens also with markdown disabled.

**Comment by bbhtt** [comment]
> Yes, looks like it, although in my case it happens also with markdown disabled.

You haven't mentioned the application version, I'm guessing it's not 1.4.28. But can you please try the 1.4.28 apk from GitHub release and report back?

**Comment by thstyl2000** [comment]
Works grrreat again, thank you!
