### ISSUE TITLE
Space Switching: Toolbar

### ISSUE THREAD

**Issue by ericdecanini** [vector-im/element-android#6580]
We want to implement the new space switching toolbar as per the Figma designs

<img src="https://user-images.githubusercontent.com/20701752/179505387-75a538f1-2e8c-4121-9e42-089c6e351dc9.png" width="200" /> <img src="https://user-images.githubusercontent.com/20701752/179506990-6e41ce6b-d89e-42ec-8345-bc2aacfa4cc1.png" width="200" />

Figma link:
https://www.figma.com/file/Hw4gjP3pknMZUir8jQqmWH/%5BMobile%5D-IA-early-proposals?node-id=2584%3A140337

This should be hidden under the `New layout enabled` feature flag as described here
https://github.com/vector-im/element-android/issues/6578

**Comment by hanthor** [comment]
The back button from the Figma design is missing

![](https://user-images.githubusercontent.com/5840441/188965865-cab6e59d-1969-48f7-84b5-7a8bc43d1263.png)

Would help with the issue I described in #7071
