### ISSUE TITLE
[link text](link to room) shows as a pill

### ISSUE THREAD

**Issue by opk12** [vector-im/element-android#6581]
### Steps to reproduce

Send a Markdown-formatted room link with a caption: `[link text](https://matrix.to/#/!a room id:a homeserver)`.

#### What did you expect?
To see `link text` in blue.

#### What happened instead?
The room name shows up.

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by ganfra** [comment]
This is the expected behavior, not an issue :-)

**Comment by opk12** [comment]
I don't think so, this is non-interoperable.

- This `formatted_body` is being hidden `<a href=...>link label</a>` regardless of the sender's client.
- Writing `[link label]` shows my intention of displaying the label to the receiver.

The pill is unnecessary if a label is provided.

- The room name and icon and the pill's emphasis look out of context in the middle of my message: if there is a label, then the room's topic is not the subject of discussion, but the link is just a tool to help stay organized.
- A neat bonus of showing the label (even more when Element introduces pinned message support) is to make an index sorted by use case, which is orthogonal to and not attainable with spaces (indices sorted by topic).
