### ISSUE TITLE
Space Switching: Space Invites

### ISSUE THREAD

**Issue by ericdecanini** [vector-im/element-android#6583]
Space Invites are to live in the bottom sheet with an "invited by" subtitle. We also want to include a badge on the FAB when an invite has been received, similar to this one
https://stackoverflow.com/questions/37639698/badge-count-on-floating-action-button

Figma link:
https://www.figma.com/file/Hw4gjP3pknMZUir8jQqmWH/%5BMobile%5D-IA-early-proposals?node-id=3730%3A167388

**Comment by daniellekirkwood** [comment]
@amshakal Please link the Figma here

@fedrunov We _need_ to have Space invites solved before releasing, ideally we'd also have Room invites solved in this way also but let us know if that it not a realistic ask

**Comment by amshakal** [comment]
Link to figma : https://www.figma.com/file/Hw4gjP3pknMZUir8jQqmWH/%5BMobile%5D-IA-early-proposals?node-id=3272%3A162876
