### ISSUE TITLE
Add a more helpful error message when trying to reset password before verifying email.

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-android#6621]
### Your use case

Match [#6463](https://github.com/vector-im/element-ios/issues/6463)

The message shown is currently the response from the server that the 3PID hasn't been validated.

On the new flow choose login and forgot password.
Enter email and tap next twice.
Enter new password and tap next.
See the error message.
This should be replaced with

>Email not verified
>Check your inbox

### Are you willing to provide a PR?

No

**Comment by ouchadam** [comment]
fixed by https://github.com/vector-im/element-android/pull/6649
