### ISSUE TITLE
Composer and timeline pills for usernames with emojis are broken

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-android#6627]
### Steps to reproduce

Prerequisites:
- User with `@username🐈✨` display name
- User with `@username ❤️‍🔥` display name

1.  In the composer, type `@username🐈✨` and click to autocomplete into a pill
2. Do the same for  `@username ❤️‍🔥`

#### What did you expect?
One pill in the composer, displayed properly in the timeline

#### What happened instead?
Pills appear multiple times:

![Screenshot_20220720-193546](https://user-images.githubusercontent.com/51663/180468747-1509a20c-b5ca-44ff-aab6-626e9bf1594c.png)

When sent, they appear like this:

![Screenshot_20220722-160910](https://user-images.githubusercontent.com/51663/180469266-54e7872d-cae3-4d7c-8656-1fd230e12dd3.png)

### Operating system version

Android 11

### Application version and app store

1.4.27

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by noantiq** [comment]
Isn't this a dup of https://github.com/vector-im/element-android/issues/5017 ?

**Comment by kittykat** [comment]
Duplicate of #5017
