### ISSUE TITLE
Several rooms missing from room directory

### ISSUE THREAD

**Issue by Cknight70** [vector-im/element-android#6632]
### Steps to reproduce

On my android 12 phone
1. Select home space 
2. Click green hashtag button to open room directory
3. Click 3 dots and change server I wish to see the directory of (in my example I used midov.pl)

With my android 10 phone I was able to see all the rooms in the directory

I triggered an "initial sync" on both phones to see results with no difference.

#### What did you expect?
To see a complete list of rooms that are in the room directory
#### What happened instead?

|Android 12|Android 10|
|-|-|
|![Screenshot_20220724-090700](https://user-images.githubusercontent.com/28763729/180653376-2a0acb66-9ef9-4a59-810b-1ab6c9928a2f.png)|![Screenshot_20220724-090511_Element](https://user-images.githubusercontent.com/28763729/180653319-39a0c498-f4e6-4f2a-9ef2-97546a8467a9.jpg)|

### Operating system version

Not working: Android 12 Working: Android 10

### Application version and app store

Both running element 1.4.25 from fdroid

### Homeserver

Synapse 1.63.1

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by ouchadam** [comment]
the difference is the settings option `Settings` -> `Preferences` -> `Show rooms with explicit content`
