### ISSUE TITLE
Improve layout on the captcha screen for new registration flow

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-android#6638]
### Steps to reproduce

1. Start registration
2. See "Are you a human?" screens:
- On the "I'm not a robot" screen, the backbround of the iframe is white and the button isn't centred
- On the "Select all images with…" screen, the screen is bigger than my phone screen and is scrollable

#### What did you expect?
Better layout

#### What happened instead?
Unattractive layout

### Your phone model
Pixel 2

### Operating system version

Android 11

### Application version and app store

New user journey APK

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by daniellekirkwood** [comment]
We don't have control over the captcha iframe - including the placing, size, etc. 
We don't want to change the captcha too much as this might look ph/fishy.

**Comment by daniellekirkwood** [comment]
Scrolling to see the whole captcha may also be a problem... not sure what we could do about that...

I'm going to close this issue in place of a META issue that will include updates to this screen including a new icon and a border around the iframe for clarity.

**Comment by daniellekirkwood** [comment]
https://github.com/vector-im/element-meta/issues/524
