### ISSUE TITLE
Enable auto-capitalization for Room creation Title field

### ISSUE THREAD

**Issue by giomfo** [vector-im/element-android#6645]
### Your use case

When creating a new room, there is no auto-capitalization in the textfield for the title of the room.
I think it's better to set by default an uppercase for the first character.

### Are you willing to provide a PR?

Yes

**Comment by bmarty** [comment]
I agree, but this should still be possible to set a title starting by a lower case.
To double check: room setting (edit title) must have the same rules than room creation screen

**Comment by giomfo** [comment]
we plan to use the following option:
<img width="167" alt="image" src="https://user-images.githubusercontent.com/8969772/182418496-7a752662-a874-4995-a170-fd951cac57d2.png">

**Comment by giomfo** [comment]
Tested
