### ISSUE TITLE
empty direct message view

### ISSUE THREAD

**Issue by bbigras** [vector-im/element-android#666]
I'm not sure if it's working as intented but this view is empty while I expect it to show my DM conversations. I can find those if I use the filter icon in the upper right corner.

![image](https://user-images.githubusercontent.com/24027/68142694-f0b3b180-fefd-11e9-9f74-82c2244d52b5.png)

**Comment by BillCarsonFr** [comment]
The rooms are probably DMS; DM is just a flag, there is no technical difference between a DM and a room.
Do you also use web? do you see rooms in the DM section in web?

**Comment by bmarty** [comment]
Old issue. Feel free to re-open if you still have the problem
