### ISSUE TITLE
Threads: Thread messages disappear

### ISSUE THREAD

**Issue by ouchadam** [vector-im/element-android#6673]
### Steps to reproduce

1. Login to an account
2. Go to a room, enter a message, long press and enable threads
3. Return to message
4. Add threaded replies

#### What did you expect?
New messages to be displayed in the thread

#### What happened instead?
The messages disappear after they finish sending

![threads-losing-content](https://user-images.githubusercontent.com/1848238/181520234-aeda8d01-0183-4882-811f-ebcc4367e3ee.gif)

### Application version and app store

1.4.30

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by amywalkerdev** [comment]
I can't replicate this one
