### ISSUE TITLE
[Notifications] Not receiving push notifications

### ISSUE THREAD

**Issue by sudoman281** [vector-im/element-android#6675]
### Steps to reproduce

1. Join a private Matrix server
2. Start chatting with people/join groups
3. Close the app
4. Have someone text you

I checked, and I have the notifications enabled. I also tried to disable the battery optimization for the app, but the problem persisted.
When I try to Troubleshoot Notifications, everything is OK except for the push notifications. The push notifications keep spinning.
It works fine for most of my colleagues, so I don't think the problem is on the server.

#### What did you expect?
Receiving a notification when someone texted me.

#### What happened instead?
I didn't receive a notification.

### Your phone model

Google Pixel 4a (5G)

### Operating system version

12

### Application version and app store

1.4.27

### Homeserver

iguana.live Synapse

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by ouchadam** [comment]
let's consolidate the issue into https://github.com/vector-im/element-android/issues/6782
