### ISSUE TITLE
Backticks don't work on Android as expected

### ISSUE THREAD

**Issue by kristofmulier** [vector-im/element-android#6682]
### Steps to reproduce

In element, I often put a word between backticks, like so:
`foo`
such that the text is formatted different from usual text.

On the PC application, this works just fine. But on the android app, the backticks are escaped, such that they are printed as actual backticks in the message.

#### What did you expect?
Don't auto-escape characters.

#### What happened instead?
The element Android app auto-escapes some characters.

### Your phone model

Google Pixel 6

### Operating system version

Android 12

### Application version and app store

1.4.27 [40104272] (G-b9527)

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by bmarty** [comment]
Please ensure Markdown is enabled. In the `Settings/Preference/Message editor` check `Markdown formatting`

**Comment by kristofmulier** [comment]
Thank you @bmarty for the tip. That works.

I suggest to enable this `Markdown formatting` by default. That follows the UI principle of "least surprise". When a user enters backticks, 9 chances out of 10 he/she wants to format the enclosed text. It's the default behavior on the desktop App (which is great). So it should be default behavior on the other platforms as well (like Android), I think.

Kind regards

**Comment by bmarty** [comment]
This will be improve with the coming WYSIWIG editor.
