### ISSUE TITLE
Notification is not working when app is closed 

### ISSUE THREAD

**Issue by AnubhavReplyNow** [vector-im/element-android#6685]
### Steps to reproduce

Notifications is not working when the app is closed.
If the app is in the foreground or is in the background notifications are working fine, but if the app is closed then they are not working for any event.

#### What did you expect?

Receiving a notification when app is closed and someone texted me call me .

#### What happened instead?

I didn't receive a notification.

### Your phone model

Vivo 2011

### Operating system version

Android 12

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by DoM1niC** [comment]
Yes on some Device the energy Management have to set manual or disable the optimizations, I got the problem since the UnifiedPush implementations on some Device like Huawei.

**Comment by ouchadam** [comment]
let's consolidate the issue into https://github.com/vector-im/element-android/issues/6782
