### ISSUE TITLE
Space Switching: New Chat Bottom Sheet

### ISSUE THREAD

**Issue by ericdecanini** [vector-im/element-android#6717]
Previously we had two separate fragments for DMs and Rooms in the home screen. This meant that the "Create new chat" action would lead to a different screen based on which fragment was open.

With the new app layout and only one screen, we want to have a bottom sheet that offers these two options when clicking on the create new chat button.

The copies for the actions are as follows:
- Start chat
- Create room

A simple list bottom sheet modal will do.

**Comment by amshakal** [comment]
Updated designs based on issue raised in internal testing session
