### ISSUE TITLE
Users who have no access to matrix.org will NOT be able to  connect to other accessible HS.

### ISSUE THREAD

**Issue by lry127** [vector-im/element-android#6718]
### Steps to reproduce

1. Since the login and register flows have been change in v1.4.30, users now who don't have access to matrix.org (in case matrix.org is blocked due to a firewall but some others are not) will lose their access to other accessible HS because they will always get a message says that there was an error connecting to HS when trying to sign up (the 1st screenshot) and log in. (the 2nd screenshot)
![register](https://user-images.githubusercontent.com/101915599/182396337-bf2bba1e-4577-43bc-91a8-52e7a22de567.png)
![login](https://user-images.githubusercontent.com/101915599/182396057-fcf4ca6a-4944-4f97-89ad-4079c712f4e6.png)

2. But before v1.4.30, v1.4.28 for example, users will always be able to choose their preferred HS when signing up and logging in. (the 3rd screenshot, took in v1.4.28)
![OK](https://user-images.githubusercontent.com/101915599/182395841-65ed2029-7f37-4b9e-89d7-4241b20f825f.png)

3. So I think it will work perfectly that adding a button to both the register and login pages just like before (4th screenshot, button at bottom of the page) but keep the new flows, when they click that button, just redirect them to the new `Select your server` page (the last screenshot) without enforcing users to access matrix.org  and so that fix this problem.
![image](https://user-images.githubusercontent.com/101915599/182402540-b45ca6bc-de0d-41ae-bb09-02878f23aad0.png)
![image](https://user-images.githubusercontent.com/101915599/182400551-0cb2680f-a688-4f34-a785-d5497ffe832a.png)

#### What did you expect?
Being able to directly enter my HS address and receive no network IO exceptions when because of trying to access matrix.org.

#### What happened instead?
I have no way to directly enter my HS address and I *have to* connect to matrix.org, then as a result, running into network problems.

### Your phone model

Huawei Y9

### Operating system version

Android 9

### Application version and app store

Element v1.4.30

### Homeserver

matrix.org (problem HS), https://network.lan (my own HS in lan)

### Will you send logs?

Yes

### Are you willing to provide a PR?

Yes

**Comment by ouchadam** [comment]
after speaking with product, we've align with iOS https://github.com/vector-im/element-ios/pull/6540 by showing the edit server selection on error (prefilled with the failing url)

**Comment by huangyinhaow** [comment]
@ouchadam 

The workaround to the problem needs to be improved, as this causes users to wait for a very long time because matrix.org returns `ERR_CONNECTION_TIMED_OUT` in China.

![image](https://user-images.githubusercontent.com/64564727/193486928-4e756a96-807a-43a0-90a2-4f43fbb0b040.png)

**Comment by du64** [comment]
This is still a problem for many of my users that live in China

**Comment by hamedsbt** [comment]
Because the matrix.org has blocked in my country I unable to event reach the login screen. 
With a VPN connection I was able to reach the login screen then I disconnected the VPN connection and tried with several home-servers but I recieved "invalid user/pass" error message. 
As far as I know, I should be able to login with my account of matrix.org to a public home-server right?!
