### ISSUE TITLE
Reply to polls don't look like poll nor link to it

### ISSUE THREAD

**Issue by weeman1337** [vector-im/element-android#6719]
### Steps to reproduce

1. Create a poll
2. Reply to it

#### What did you expect?

- The poll visible in the reply
- A link to the poll message

![image](https://user-images.githubusercontent.com/6216686/182405495-5013e916-3b17-404a-a910-7914a23f58cc.png)

#### What happened instead?

The poll title as quote message

Compare to web

![image](https://user-images.githubusercontent.com/6216686/182405044-ced0c8c4-d5a0-4adf-bbd6-e4e71cb7d39d.png)

### Application version and app store

1.2.25

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by mnaturel** [comment]
Hi @weeman1337, thanks for raising this issue, we have just tested the link to the original poll message and it seems to work on the latest version.
For the content of the reply message, we may have to think about it so that we can have consistent UX accross platforms.

**Comment by Johennes** [comment]
@gaelledel and I spoke about this in DM last week and the quote section in replies being text-only is actually a general pattern we use on mobile due to the limited available space. We'd like to not change that at this time.

**Comment by weeman1337** [comment]
> @gaelledel and I spoke about this in DM last week and the quote section in replies being text-only is actually a general pattern we use on mobile due to the limited available space. We'd like to not change that at this time.

That is fine. But shouldn't it better display some information that you replied to a poll? It looks like a normal message but actually it was a poll. Eventually there could be a text link „go to poll“ in addition to that. Doesn't use much space, but makes things easier to understand.

**Comment by Johennes** [comment]
I'll let @gaelledel give the design perspective here but I think an explicit "go to poll" link might conflict / overlap with the existing idiom that tapping the quote section takes you the original message / event.

We could maybe consider calling out that it's a poll via the text, e.g.

```
> Poll: läuft?

Reply to läuft
```

?

**Comment by gaelledel** [comment]
Right now we have this pattern on mobile where the message that is replied to is not repeated. As this is a pattern that exists for all type of content: text, image, video, voice message - we cannot just change it for polls. So for now, let's keep the poll title as a summary in the reply. It is giving context to users as to what they are replying to. Changing the way replied messages are designed should be an effort done as a whole rather than for one element.
