### ISSUE TITLE
Space Switching: Space Bottom Sheet Empty States

### ISSUE THREAD

**Issue by ericdecanini** [vector-im/element-android#6754]
When there are no spaces at the root or children of the current space, we want to show an empty state to notify the user. Designs of this are TBD.

As per https://github.com/vector-im/element-android/issues/6771, we also want to make the toolbar non-collapsible in an empty state.

Figma design: https://www.figma.com/file/Hw4gjP3pknMZUir8jQqmWH/%5BMobile%5D-IA-early-proposals?node-id=2523%3A135211

Parent epic: https://github.com/vector-im/element-android/issues/6605

**Comment by daniellekirkwood** [comment]
Linked to this: https://github.com/vector-im/design/issues/24

**Comment by amshakal** [comment]
Figma link to empty state: https://www.figma.com/file/Hw4gjP3pknMZUir8jQqmWH/%5BMobile%5D-IA-early-proposals?node-id=3880%3A168810
