### ISSUE TITLE
Security options 

### ISSUE THREAD

**Issue by PassiHD2004** [vector-im/element-android#6811]
Feature request: Add seperate Buttons to turn, e.g. face recognition on/off or just use Fingerprint. (If possible)

**Comment by jmartinesp** [comment]
I don't think this is possible with the current Android APIs for biometric authentication. We can only ask for [3 levels of authentication](https://developer.android.com/reference/android/hardware/biometrics/BiometricManager.Authenticators#summary) but as can be seen on the docs, face or iris unlock can be both strong or weak authenticators, so choosing a concrete authentication method is not possible, it's up to the Android OS to decide which one should be used.
