### ISSUE TITLE
App Layout: Persistant Verification

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-android#6812]
### Steps to reproduce

@kittykat : "confused about the verification"

1. Log in
2. Try to verify device via Android app - don't get an option to verify against another session
3. Verify from a web session
4. See a "New login. Was this you?" prompt on Android for a verified session

### Application version and app store

App Layout APK

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by kittykat** [comment]
Also, the app kept showing my other sessions as unverified for some time after.

**Comment by ericdecanini** [comment]
The first thing we need to investigate is whether this issue is only happening with the new app layout or if it also happens with the feature flag disabled.

**Comment by kittykat** [comment]
Duplicate of #6460

**Comment by kittykat** [comment]
Duplicate of #4318
