### ISSUE TITLE
App Layout: Favourites do not appear and sometimes switching tabs takes more than 10s

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-android#6813]
### Steps to reproduce

Raised by @gsouquet in the internal testing session
Also raised by @kittykat

**Comment by gsouquet** [comment]
@kittykat have you experienced that recently? I have not, it's been super smooth for me!

**Comment by kittykat** [comment]
No, not seeing it in https://buildkite.com/matrix-dot-org/element-android/builds/10430

**Comment by gsouquet** [comment]
Can't repro anymore, closing
