### ISSUE TITLE
App Layout: Bottom sheet of Compose looks odd

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-android#6814]
### Your use case

The bottom sheet looks odd.

![Screenshot_20220811-201727_Element dbg](https://user-images.githubusercontent.com/89144281/184221478-3801ee1f-1626-4809-9c2f-79cbe425609e.jpg)

**Comment by daniellekirkwood** [comment]
@amshakal is this as expected?

**Comment by amshakal** [comment]
We wanted to use a default bottom sheet but I agree it doesn't look very nice. Ill work on this next.

**Comment by daniellekirkwood** [comment]
If it's as designed then I'll mark it as "not a blocker" and we can update it asap :)

**Comment by amshakal** [comment]
Updated the designs to match other bottom sheets in the app

<img width="239" alt="Screenshot 2022-08-15 at 1 51 41 pm" src="https://user-images.githubusercontent.com/85162587/184638307-0acf0e42-990d-4014-9606-ebce31935630.png">

[Figma Link](https://www.figma.com/file/Hw4gjP3pknMZUir8jQqmWH/%5BMobile%5D-IA-early-proposals?node-id=3781%3A168752)

**Comment by amshakal** [comment]
[Updated the designs](https://www.figma.com/file/Hw4gjP3pknMZUir8jQqmWH/%5BMobile%5D-IA-early-proposals?node-id=3781%3A168752) as promised, to match the current implementation of botoom sheet on android. Also broke down the options to match iOS. The buttons all link to existing screens, find below the screenshots for all of them.

<img width="324" alt="Screenshot 2022-08-15 at 1 55 07 pm" src="https://user-images.githubusercontent.com/85162587/184639616-e0dbdfb8-3d47-4fc1-beb1-eb1d16cc237f.png">

Start Chat -> Links to the start a DM screen
<img width="324" alt="Screenshot_20220815-135707" src="https://user-images.githubusercontent.com/85162587/184639671-7c8cfbf2-044e-4020-a671-a429bf15640f.png">

Create Room -> Links to create room flow
<img width="324" alt="Screenshot_20220815-135718" src="https://user-images.githubusercontent.com/85162587/184639703-cee034e7-7446-472a-a63d-c6d1c41aa5a9.png">

Explore Rooms -> Links to the explore room screen
<img width="324" alt="Screenshot_20220815-135655" src="https://user-images.githubusercontent.com/85162587/184639727-589e76c6-e8d0-4a4f-9665-c776f396a7d7.png">

**Comment by amshakal** [comment]
Link to similar issue: https://github.com/vector-im/element-android/issues/6717
