### ISSUE TITLE
Space Switching: Spaces Bottom Sheet Should Have Expandable Subspaces

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-android#6815]
Initially we aimed for an approach where clicking on a space closed the bottom sheet and you'd have to open the sheet again if you want to navigate even deeper.

Following internal and community feedback, we want to revert to the old style of having expandable subspaces.

<img width="500" src="https://user-images.githubusercontent.com/20701752/185088518-c65ee4fc-4516-4b9b-8728-125c253a5332.png" />

Figma link:
https://www.figma.com/file/Hw4gjP3pknMZUir8jQqmWH/%5BMobile%5D-IA-early-proposals

**Comment by daniellekirkwood** [comment]
can't access all chats from inside a space when that space has subspaces

**Comment by daniellekirkwood** [comment]
@amshakal @ericdecanini Let's chat about the behaviour of the space switching sheet :D

**Comment by ericdecanini** [comment]
I'm relabelling this issue as an enhancement. We have the other defects already written separately here
https://github.com/vector-im/element-android/issues/6605
