### ISSUE TITLE
App Layout: Dark Mode

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-android#6817]
### Your use case

The dark mode home page looks a little stripy - is that as designed?

| | | |
|---|---|---|
| ![darkmodeandroid](https://user-images.githubusercontent.com/89144281/184219912-9ed664cf-a818-4b46-a000-dc3ef5231d17.jpg) | | |

**Comment by daniellekirkwood** [comment]
@amshakal this is how the screen looks in dark mode - is it as designed?

**Comment by amshakal** [comment]
No this is not how it should look. I can create dark mode reference designs to make it clearer.

**Comment by gsouquet** [comment]
@amshakal would you be able to update this issue with the dark mode version? Looks like we're still waiting on a few UI pieces

**Comment by amshakal** [comment]
Here are a the dark mode screens covering most used components in the new proposal. [Link to figma](https://www.figma.com/file/Hw4gjP3pknMZUir8jQqmWH/%5BMobile%5D-IA-early-proposals?node-id=3986%3A172776)



![Image](https://user-images.githubusercontent.com/85162587/185436670-825e2698-ca5b-4496-8fde-aa63d37ab7f8.png)
