### ISSUE TITLE
App Layout: Dimmed screen when switching spaces

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-android#6818]
### Steps to reproduce

When switching back from a space (via back button), the bottom sheet is not shown but the screen is dimmed https://i.k8r.eu/8Da7Qg.png

### Application version and app store

App Layout APK

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by ericdecanini** [comment]
This will be fixed with https://github.com/vector-im/element-android/issues/6751
