### ISSUE TITLE
App Layout: Favourites tab appears as empty

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-android#6819]
### Steps to reproduce

Favourites tab is empty if favourites exist in a different than the current space.See https://i.k8r.eu/HVqXag.png vs https://i.k8r.eu/RbVeZQ.png

### Application version and app store

App Layout APK

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by fedrunov** [comment]
duplicates https://github.com/vector-im/element-android/issues/6770
