### ISSUE TITLE
Contacts showing as active when they are gone/idle

### ISSUE THREAD

**Issue by binarydad** [vector-im/element-android#6822]
### Steps to reproduce

Viewing a contact. In this case, my son uses Element and we are using a server that I host and manage. I've noticed recently that if he's not using his phone, even after hours, it still shows him as being active on my devices. I feel this is new behavior, as it would typically show him as not being active after he stopped using Element on his phone (or even when he uses the desktop app). 

Clearing the app cache (in Settings, General) fixes the issue. 

#### What did you expect?
That after several hours, he would not show as active

#### What happened instead?
He remained showing as active

### Your phone model

Galaxy S22 (mine), Galaxy A02s (his)

### Application version and app store

1.4.31 from GP

### Homeserver

Synapse 1.64

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by dreaddr** [comment]
Have observed this as well.

**Comment by ouchadam** [comment]
this may be related to the recent sync issues https://github.com/vector-im/element-android/issues/6782

if so, 1.4.34 may fix the inconsistencies
