### ISSUE TITLE
sent messages cannot be edited/deleted/replied to until after restarting the app

### ISSUE THREAD

**Issue by kylrth** [vector-im/element-android#6823]
### Steps to reproduce

1. send a message in a room
2. long-press on the sent message to see options

#### What did you expect?

Options to reply, edit, delete, etc. the message.

#### What happened instead?

(Often) I only see the option to cancel, even though the message has already reached the server.

<img src="https://user-images.githubusercontent.com/5044802/184445310-6a415b5a-9a19-4f53-9a83-4f3af86b3d13.png" width="300" alt="only the option to cancel shows up" />

### Your phone model

Google Pixel 3a

### Operating system version

12

### Application version and app store

Element 1.4.31, olm 3.2.12, GPlay

### Homeserver

matrix.kylrth.com

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by kylrth** [comment]
Sorry, I'll send logs when I see it happen again. It's hard to reproduce in isolation.

**Comment by immanuelfodor** [comment]
Same here with S22. Only fully closing the app then opening it again helps. The messages are sent to the server indeed, it seems only the app doesn't confirms it back to the user. 

I also have a bot in a room, and previously, it "saw" all messages that was sent there instantly, now the messages are marked as seen by the bot only after the app restart.

**Comment by nolimbsdotdev** [comment]
I have the same problem on the Pixel 4a. A force quit - reload is the only way to edit the messages.

**Comment by ouchadam** [comment]
thanks for raising, this sounds like the sync issue mentioned above https://github.com/vector-im/element-android/issues/6782

**Comment by Florian14** [comment]
This issue should be fixed according to the mentioned PR, also no updates have been given for a while, so I suppose I can close the issue.
