### ISSUE TITLE
App Layout: Empty States

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-android#6835]
### Your use case

There are several empty states needed for the app layout work: 

Here's the design issue for reference: https://github.com/vector-im/design/issues/24

There's already a space switching issue: https://github.com/vector-im/element-android/issues/6754

### Are you willing to provide a PR?

No

**Comment by daniellekirkwood** [comment]
@amshakal Please add the link to the figma :)

**Comment by amshakal** [comment]
There are four empty states that were discussed. I have two of them ready and two if them are pending final illustrations. If we can add a placeholder image that can be replaced later, we can work on all of them now.

1. All chats screen with no rooms yet - Content is finalised, Pending illustration
2. Space screen with no rooms added to the space - Content is finalised, Pending illustration
3. When there are no unreads in the tab - Ready
4. When there are no spaces (emoty space switcher bottom sheet) - Ready

[Link to Android empty states](https://www.figma.com/file/Hw4gjP3pknMZUir8jQqmWH/%5BMobile%5D-IA-early-proposals?node-id=3609%3A169367)
