### ISSUE TITLE
Space Switching: Creating A Room In A Subspace Didn't Put The Room In That Subspace

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-android#6848]
### Steps to reproduce

Found during testing today:
"Creating a room inside a space put the room correctly inside the same space.  Creating a room while inside subspace didn't put the room in either the space or the subspace."

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by ericdecanini** [comment]
Since we're changing the space sheet to be accordion-style, we won't need the ability to add subspaces with the "Create Space" button. Closing this for now
