### ISSUE TITLE
App Layout: New space shows as empty room from the All Chats list

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-android#6850]
### Steps to reproduce

found today in testing

If a space has just been created, it shows All Chats > Empty Room instead | 
Create a new space. Give it a name. When asked to add rooms, press "←". Screenshot: https://i.k8r.eu/ENnd7g.png

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by ericdecanini** [comment]
This is relevant to https://github.com/vector-im/element-android/issues/6751. While the mentioned issue is in progress, we should aim to fix this issue as well before submitting it as a PR
