### ISSUE TITLE
Private CA issue

### ISSUE THREAD

**Issue by iz4tow** [vector-im/element-android#6864]
### Steps to reproduce

1. It started with the last release, when the login interface changed on android. (until 1.4.27 was working)
2. When I choose  the server it appears the usual "Trust the certiicate?" I say Yes but I cannot go further
3. If you did not log out you can update Element with no issue

#### What did you expect?
When I choose  the server it appears the usual "Trust the certiicate?" I say Yes but I cannot go further
#### What happened instead?
I cannot go further and it keep asking "Trust Certificate?"

### Operating system version

Android 11

### Application version and app store

Element 1.4.32

### Homeserver

matrix-synapse last stable release with private CA

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by ouchadam** [comment]
am able to reproduce, will prepare a fix

**Comment by ouchadam** [comment]
a workaround is to deeplink into the app with `https://mobile.element.io/?hs_url=matrix.org&is_url=matrix.org` replacing matrix.org with your homeserver

**Comment by Modificator** [comment]
lastAction is EditHomeServer

![image](https://user-images.githubusercontent.com/3425930/185288250-848758cb-4c41-4ca6-b6a7-3bfd30df689a.png)
