### ISSUE TITLE
How to configure messages not to be encrypted?

### ISSUE THREAD

**Issue by YXyjt** [vector-im/element-android#6883]
How to configure the messages sent by the room to be unencrypted？

**Comment by ouchadam** [comment]
When creating a room, the encryption option can be disabled, it's not possible to disable once enabled.

![2022-08-19T11:11:47,855659071+01:00](https://user-images.githubusercontent.com/1848238/185597060-bbe132eb-5a4f-4234-8c63-b83fb74b9a3f.png)


It's technically supported by the spec to send unencrypted messages into an encrypted room but Element Android does not allow it for security reasons.

**Comment by YXyjt** [comment]
We have a scenario where we need to switch accounts to log in. If the message is encrypted, it will take too long to restore the password decryption. Is there a way to not encrypt it?

> 创建房间时，可以禁用加密选项，一旦启用就无法禁用。
> 
> ![2022-08-19T11:11:47,855659071+01:00](https://user-images.githubusercontent.com/1848238/185597060-bbe132eb-5a4f-4234-8c63-b83fb74b9a3f.png)
> 
> 该规范在技术上支持将未加密的消息发送到加密房间，但出于安全原因，Element Android 不允许这样做。
We have a scenario where we need to switch accounts to log in. If the message is encrypted, it will take too long to restore the password decryption. Is there a way to not encrypt it?
