### ISSUE TITLE
Make rooms and spaces accessible as a slideout

### ISSUE THREAD

**Issue by pbsds** [vector-im/element-android#6895]
#### What would you like to do?

I would like to slide out the rooms and spaces sidebar with a gesture /swipe from left to the right on touch screens in portrait mode.
Something like how the sidebar in thelounge behaves. (Relevant issue, description and solution: https://github.com/thelounge/thelounge/issues/393)

This is [rumoured to be somewhat of a feature](https://github.com/vector-im/element-android/issues/2996#issuecomment-799513858), but would on any recent android phone with default navigation settings be totally inaccessible.

#### Why would you like to do it?

Currently i find myself sliding my thumb from the left side, to the right, trying to get the rooms and spaces to come out, as i am used to in thelounge.
The current way to open the sidebar is to stretch my thumb to the upper left corner of the screen and hit the hamburger button, which is very poor UX on a large phone.

#### How would you like to achieve it?

Any left-to-right swipe while viewing a chat should open the rooms or spaces, as if the hamburger icon was hit.
This might conflict with other gesture (reply?), making this a feature that either is optional, or which changes the current default behavior.

### Have you considered any alternatives?

Doing nothing

### Additional context

Related? #1937
Similar request to cinny: https://github.com/cinnyapp/cinny/issues/761

### Are you willing to provide a PR?

No

**Comment by ambroisie** [comment]
Has this been removed recently?

I switched phones and reinstalled Element after not having it on there for a bit, and it looks like the sliding UI was removed in favor of a button?

That means that my orphaned rooms (which don't belong to any spaces) are harder to find now...
