### ISSUE TITLE
Push notification not working (Google Play variant)

### ISSUE THREAD

**Issue by rajil** [vector-im/element-android#6896]
### Steps to reproduce

Trouble shooting Notification is stuck on "Test Push". Self hosted synapse homeserver is on 1.65, and Android client is 1.4.32

![image](https://user-images.githubusercontent.com/379266/185794099-3986846d-2131-4ffb-9d82-7e73410321bc.png)

### Outcome

Push notification is not received.

### Your phone model

Samsung Note 9

### Operating system version

Android 10

### Application version and app store

Element Android 1.4.32

### Homeserver

1.65.0

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by bmarty** [comment]
This should be fixed in version 1.4.34.

**Comment by Notmarrco** [comment]
I have the same issue with 1.4.34

**Comment by tathougies** [comment]
I'm having this issue as well. I'm happy to debug or provide more information. I have access to my synapse logs and am happy to delve into code. I just don't know where to begin to look. I couldn't see anything obvious in the synapse logs.

**Comment by tathougies** [comment]
I managed to fix this by disabling notifications in my session and re-enabling them.

**Comment by Notmarrco** [comment]
Sadly disabling and re-enabling sessions notification in element doesn't work for me.

**Comment by Tropaion** [comment]
Doesn't work for me either, I hope this will be fixed soon.

**Comment by fedrunov** [comment]
#6572, #6975, #6379, #6283 might be related

**Comment by ggogel** [comment]
I'm also affected by this issue. I'm not sure if the issue started happening with `1.4.34` or `1.4.32`.

**Comment by Tropaion** [comment]
> Removing the app, including app data, and re-installing it fixed the issue for me.

Worked for me too.

**Comment by ouchadam** [comment]
thanks for letting us know :+1:  if the problem reappears it would give more weight to @ggogel 's theory that the push token is failing to refresh 

it might be worth us adding the ability to delete the current push token to force a refresh in the notification tester

**Comment by Notmarrco** [comment]
I did like @ggogel said, and it works again too. Thanks.

**Comment by Dominion0815** [comment]
Re-installation works !

**Comment by bahur142** [comment]
This is happens not only with Google FCM, but also with NTFY push provider. Until I manually remove the current pusher in "Notification Targets", all tests stucks and push not arriving.
When the pusher is deleted then new one appears automatically and push works again. No need to reinstall the app.

But this is hard work-around, only for advanced users. It is not easy to explain this to regular users.
I hope this will be fixed in the next release.

**Comment by bmarty** [comment]
The PR #7085 (based on #7068) fixes the issue for Google Play variant using Firebase. The fix is included in Element Android 1.4.36.

I am going to close the issue. @bahur142 feel free to open a dedicated issue related to the usage of NTFY. Thanks!
