### ISSUE TITLE
Bug: Crash when making calls in rooms using custom Jitsi server with authorization 

### ISSUE THREAD

**Issue by orange2008** [vector-im/element-android#6897]
### Steps to reproduce

Using Element Android to make a call in a room using my custom Jitsi server with authorization.
When making it, it crashed.
My Jitsi server is defined at [https://chat.frank-ruan.com/.well-known/matrix/client](https://chat.frank-ruan.com/.well-known/matrix/client) 
I don't know what's going on. 

#### What did you expect?
Jitsi widget pop up and ask me to authenticate, then make the call as usual. 
#### What happened instead?
It crashed 

### Your phone model

Vivo V1913A

### Operating system version

Android 9

### Application version and app store

Element version 1.4.32 [40104322] (G-b10318), olm 3.2.12

### Homeserver

matrix.frank-ruan.com

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by ouchadam** [comment]
thanks for raising and supplying logs, I can confirm you're encountering the same crash as #5745 

going to close this in favour of #5745
