### ISSUE TITLE
What's the anti-feature on f-droid release?

### ISSUE THREAD

**Issue by 4mohamedaliii** [vector-im/element-android#6898]
There's an anti-feture on your app by f-droid.
Could someone tell me about it.

**Comment by BigmenPixel0** [comment]
https://f-droid.org/en/docs/Anti-Features/#NonFreeNet

**Comment by ouchadam** [comment]
from the fdroid listing https://f-droid.org/en/packages/im.vector.app/

<img width="688" alt="Screenshot 2022-08-26 at 09 26 46" src="https://user-images.githubusercontent.com/1848238/186858368-13eab586-9cc6-4a40-9b50-33c895d2ab07.png">

**Comment by jmartinesp** [comment]
Since the question has been answered and there doesn't seem to be any other doubts I'm closing the issue, but please add any other comments if further clarification is needed.

**Comment by maurerle** [comment]
Hello,
I have the feeling, that this is not sufficiently answered here:

As the backend (synapse) and the identity server (sydent) is open source too, I was asking myself if this is still the case.
As far as I know, matrix's own identity server is suggested, but you can even configure it to use a different one.

https://github.com/matrix-org/synapse/issues/6183

On the other hand, the f-droid docs says:
> This antifeature would not apply, if there is a simple configuration option that allows pointing the app to a running instance of an alternative, publicly available, self-hostable, free software server solution.

So I have the question why does this still apply?

**Comment by jtrees** [comment]
I am also confused by this. Which non-free network is this label referring to?

**Comment by shuvashish76** [comment]
> This comes from Element's "Integration manager" implementation. Since this integration manager is currently hardcoded to https://scalar.vector.im, which is closed source and thus cannot be self-hosted right now, this leads to said anti-feature. ([source](https://github.com/SchildiChat/SchildiChat-android/issues/130#issuecomment-1166220018))

I'll through my same suggestion here again...

![SchildiChat](https://github.com/SchildiChat/SchildiChat-android/assets/48226312/ea4617f5-3702-43a7-bc99-31ff15535f18)

Please mention that "⚠️This service is proprietary." or something similar in the description for transparency because we don't expect users to search GH issue tracker for that.

One F-Droid maintainer said:
> If _Element_ were to make sure users cannot accidentally turn this on thinking it's FOSS, we'd be happy to remove the AF.

**Comment by obfusk** [comment]
> If _Element_ were to make sure users cannot accidentally turn this on thinking it's FOSS, we'd be happy to remove the AF.

I should have phrased that more carefully. I can't speak for the team, but I think we'd probably have agreement that the AF is no longer needed if there's a warning.
