### ISSUE TITLE
How to configure an unencrypted private chat room

### ISSUE THREAD

**Issue by YXyjt** [vector-im/element-android#6899]
We have a scenario where we need to switch accounts frequently to log in. If the message is encrypted, we need to verify the device with the key every time, which takes too long. Is there a solution to keep private chat messages from being encrypted?

**Comment by kittykat** [comment]
@YXyjt Hi, the best place to ask support questions about the Android app is in [the public Element Android room](https://matrix.to/#/#element-android:matrix.org). You can find other Element community rooms [in the space](https://develop.element.io/#/room/#community:element.io).

It is recommended to use encryption, but I believe the best way to achieve what you're looking for is to start an unencrypted room with one other person and then convert that room to a DM.
