### ISSUE TITLE
Plain text falsely identified as markdown

### ISSUE THREAD

**Issue by targodan** [vector-im/element-android#690]
RiotX seems a bit overzealous when it comes to what counts as markdown.

When the text contains a space at the end of a line (right in front of the LF) the message is interpreted as markdown and thus all newlines are effectively ignored (as the message is converted to HTML with `<p>`-tags only inserted when two newlines are present).

Because of my input method on android I can insert things like bangs (!) and so on via a gesture. This however leaves a space behind the bang. If I now add a line break, all my line breaks are effectively ignored, which is not the message I intended to send.

This does not happen in Riot Web/Desktop. I do not know if this does happen in RiotAndroid.

I'm running RiotX version `0.7.0 [20000700] (G-b1099)` from the Google Playstore, on Android 7.1.1 (I know, shame on me).

## How to reproduce

Go to any chat and type something like this. With `[SPACE]` replaced by an actual space.

```
test[SPACE]
some more test
```

**Comment by targodan** [comment]
Just updated to version 0.8.0 via google playstore. Still same behavior.

**Comment by bmarty** [comment]
I do not reproduce with Element Android 1.1.3. Feel free to re-open if you can reproduce
