### ISSUE TITLE
App Layout: Release Experience

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-android#6909]
### Your use case

https://github.com/vector-im/design/issues/25

We need for current users who update the app to be shown an in-app release experience that tells them what's different in this version. It should be shown once and not to new users. 

### Are you willing to provide a PR?

No

**Comment by niquewoodhouse** [comment]
Dark - https://www.figma.com/file/DQq9Qi8rRJ7cBPFt98uDAM/App-layout-release-xp?node-id=57%3A5918
Light - https://www.figma.com/file/DQq9Qi8rRJ7cBPFt98uDAM/App-layout-release-xp?node-id=57%3A5831

- [x] Same image used for light and dark
- [x] Static images
- [x] Copy content and button logic from iOS (but amend where necessary)
