### ISSUE TITLE
I want to add the "Use Proxy" feature to the settings of the software

### ISSUE THREAD

**Issue by Fhokud** [vector-im/element-android#6922]
### Your use case

I want to add the "Use Proxy" feature to the settings of the software.
This feature is important to help users access the network easily and quickly through a proxy.
Not only Android, but other clients should also add this feature.

The proxy agreement is socks or http or other

### Have you considered any alternatives?

Yes, I consider using vPNs and system proxies, but both handle traffic from other software

### Are you willing to provide a PR?

No

**Comment by jmartinesp** [comment]
Duplicate of #488.
