### ISSUE TITLE
FTUE: Make entering a custom Homeserver address faster

### ISSUE THREAD

**Issue by noantiq** [vector-im/element-android#6926]
#### What would you like to do?
Easily log in to a "custom" Homeserver that isn't matrix.org. 
#### Why would you like to do it?
Because I have a matrix account on that server. 
#### How would you like to achieve it?
Focus the input field and select it's text when navigating to the "Select your server" screen after pressing the "Edit" button on the login/registration screen.
This would make it possible to press the "Edit" button and simply start entering a Homeserver address that replaces the default address (which should usually be what you want when editing the server address). 

### Are you willing to provide a PR?

Yes

**Comment by ouchadam** [comment]
Included in 1.4.36
