### ISSUE TITLE
[FTUE] #2585 makes Chinese users unable to successfully log in or register

### ISSUE THREAD

**Issue by huangyinhaow** [vector-im/element-android#6944]
### Steps to reproduce

1. Go to China.
2. Install the latest version of Element.
3. Open Element.
4. ERROR.

#### What did you expect?

I want to use my own homeserver, beacuse matrix.org is blocked in China.

#### What happened instead?

Element will first try to connect to matrix.org, and if it can't, throw an error without first giving me an option to choose my own HS. In fact, I needed to connect to matrix.org via VPN first before Element gave me the option to choose my own HS in the second step. This obviously does not conform to the concept of decentralization.

### Your phone model

moto s20 pro

### Operating system version

a12

### Application version and app store

v1.4.30 and above (F-Droid)

### Homeserver

My own homeserver

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by huangyinhaow** [comment]
![image](https://user-images.githubusercontent.com/64564727/186800192-b1236eef-e0b9-4ad0-8b8d-59bf5b433f9e.png)

**Comment by ouchadam** [comment]
thanks for raising, this has been fixed in 1.4.32 by https://github.com/vector-im/element-android/issues/6735

**Comment by huangyinhaow** [comment]
> thanks for raising, this has been fixed in 1.4.32 by #6735

Seems unrelated. . .

**Comment by ouchadam** [comment]
I pasted the wrong link originally, the edit contains the correct links

**Comment by huangyinhaow** [comment]
Thanks!
