### ISSUE TITLE
my conversations became empty rooms

### ISSUE THREAD

**Issue by iopq** [vector-im/element-android#6954]
I may have tried the setting prohibiting sending unencrypted chats to encrypted rooms

But anyway, on the android client I have no one on one messages anymore, can't message the people I want to message or see the history

**Comment by jmartinesp** [comment]
I think we need more info, I can't reproduce the issue after enabling that setting. Could you maybe add some screenshots of what you see or a video and maybe rageshake referencing this issue (#6954)?

**Comment by iopq** [comment]
I think the issue is my room list on the front page doesn't match the list when I click the pyramid. I found my other conversations 😂

Not sure where the empty rooms came from
