### ISSUE TITLE
F-Droid can't build - non-FOSS compile time dependency firebase-appdistribution-gradle

### ISSUE THREAD

**Issue by licaon-kter** [vector-im/element-android#6963]
### Steps to reproduce

Since we started to scan classpaths too: `ERROR: Found usual suspect 'firebase' at build.gradle` -> https://github.com/vector-im/element-android/blob/v1.4.34/build.gradle#L27

Removing that and https://github.com/vector-im/element-android/blob/v1.4.34/vector/build.gradle#L4 yields this error: https://gitlab.com/TheLastProject/fdroiddata/-/jobs/2952428066#L481

Ref: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/11633/

Where's the source of that plugin? https://mvnrepository.com/artifact/com.google.firebase/firebase-appdistribution-gradle/3.0.3

If this https://github.com/firebase/firebase-android-sdk/blob/master/firebase-appdistribution/firebase-appdistribution.gradle#L60 then that's a non-FOSS dep, right?

fyi @TheLastProject 

### Outcome

Fails to build

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by bmarty** [comment]
This is a plugin that are not used if you do not invoke them, for instance by calling
```sh
./gradlew appDistributionUpload...
```

Are you sure this is blocking the release of the Element F-Droid app?

We already have (I think) non-FOSS plugin and this is not blocking (or not detected?), for instance [oss-licenses-plugin](https://github.com/vector-im/element-android/blob/v1.4.34/build.gradle#L30), applied [here](https://github.com/vector-im/element-android/blob/v1.4.34/vector/build.gradle#L5).

**Comment by ouchadam** [comment]
we could potentially dynamically apply the plugin only for gradle executions including "gplay", similar to the coverage generation https://github.com/vector-im/element-android/blob/develop/build.gradle#L173

**Comment by licaon-kter** [comment]
If I remove the line in build.gradle and (as you see) the build fails I'd call that "used" and "a blocker" :)

**Comment by ouchadam** [comment]
with the plugin commented out its configuration block will also need to commented/removed https://github.com/vector-im/element-android/blob/develop/vector/build.gradle#L281

```
firebaseAppDistribution { ... }
```

-----

I beliieve @bmarty meant the plugin isn't used to generate any sources, it's a wrapper around the google apis/firebase distribution apis, we could potentially create a separate wrapper like https://github.com/fastlane/fastlane-plugin-firebase_app_distribution although it's probably simpler to opt into the plugin for nightly/gplay variant tasks rather than apply by default

**Comment by licaon-kter** [comment]
Let me try to remove that section too.

**Comment by licaon-kter** [comment]
Yay, built fine: https://gitlab.com/TheLastProject/fdroiddata/-/jobs/2954399693#L3870
