### ISSUE TITLE
Add an option to hide image previews

### ISSUE THREAD

**Issue by tobiasdiez** [vector-im/element-android#6999]
#### What would you like to do?

Add an option to show/download an image after the user "accept" it. This exists already for the web version: https://github.com/matrix-org/matrix-react-sdk/pull/3492

#### Why would you like to do it?

This has the benefit of deciding which images you want to see and it can be easier on the data for mobile users.

### Are you willing to provide a PR?

No

**Comment by jmartinesp** [comment]
Duplicate of #6518, closing this one the referenced issue has more info and alternatives.
