### ISSUE TITLE
Presence Management - user status

### ISSUE THREAD

**Issue by bmarty** [vector-im/element-android#70]
### API and documentation

https://matrix.org/docs/spec/client_server/latest#id62

### Change SDK side

- [x] Create a PresenceService
- [x] Implement an API in PresenceService to set the status of the current user using https://matrix.org/docs/spec/client_server/latest#put-matrix-client-r0-presence-userid-status
- [x] Implement an API in PresenceService to retrieve the status of any user using https://matrix.org/docs/spec/client_server/latest#get-matrix-client-r0-presence-userid-status
- [x] Handle the presence update from the sync response (see https://matrix.org/docs/spec/client_server/latest#get-matrix-client-r0-sync):
```json
  "presence": {
    "events": [
      {
        "content": {
          "avatar_url": "mxc://localhost:wefuiwegh8742w",
          "last_active_ago": 2478593,
          "presence": "online",
          "currently_active": false,
          "status_msg": "Making cupcakes"
        },
        "type": "m.presence",
        "sender": "@example:localhost"
      }
    ]
  },
```
- [x] See how those data ^ can be stored in the session DB to be kept up to date. Probably a new Entity will have to be created (_to be discussed_)

#### Change application side

- [x] Integrate the design update regarding presence: _list of impacted screens to be defined_

### Presence supports by the homeserver

Note that matrix.org has disabled the presence management for performance reason.
We should avoid displaying (wrong) presence information if it's disabled on the homeserver, and we will be able to know that with https://github.com/matrix-org/matrix-doc/pull/1862

- [x] In the mean time, we can use the local config to disable presence locally, based on the user homeserver URL as per https://github.com/vector-im/element-web/blob/develop/element.io/app/config.json#L28. The config file on Element Android is [here](https://github.com/vector-im/element-android/blob/develop/vector/src/main/res/values/config.xml)

**Comment by BloodyIron** [comment]
Is this eventually going to enable things like "busy/DND/AFK" types of status? Would be nice to globally-mute alerts across my account and all devices logged into it, or equivalent.

**Comment by Sorunome** [comment]
The [presence module](https://matrix.org/docs/spec/client_server/latest#id62) also has a `status_msg` so that people could set a custom status.

Fluffychat supports this by now and it is really nice ^-^

**Comment by croulibri** [comment]
In my homeserver, presence management is activated.
In the new element Android App, I can't find anymore how to see presence of a specific user (is she/he online or not).
It would be really nice to have a "green dot" meaning the user is online, like on Element-desktop.

Is this function absent or have I missed something?

**Comment by ShadowJonathan** [comment]
@croulibri that function is definitely absent in Element/RiotX, imo it should replace the verified shield in the DM list, showing offline/online/etc, and having the E2EE shield be at the top of the conversation detail instead

**Comment by croulibri** [comment]
Thanks @ShadowJonathan for your detailed answer.
For the family usage we have, it is a step back as we use a lot the presence management to organise our calls.
I hope this feature will be back soon!
Congratulation for the excellent work done on Element and Matrix in general and good luck for implementing the missing features!

**Comment by BloodyIron** [comment]
Yeah I think it's coming time for presence to get revisited as a feature.

**Comment by BloodyIron** [comment]
So does closing this ticket mean Presence in Element is going to be coming back now or what? @ariskotsomitopoulos

**Comment by machisuji** [comment]
This is 2024 chiming in and presence would still be great to have. Right now people are changing their names to indicate status which is a very poor workaround creating a lot of noise.
