### ISSUE TITLE
App Layout: Spaces icon needs updating

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-android#7025]
### Your use case

We're using the wrong spaces icon 
in product and in the release experience images.

### Are you willing to provide a PR?

No

**Comment by ericdecanini** [comment]
I've looked at the figma and see that the icons match unless I'm misunderstanding. Can you explain more specifically what you're referring to and what it should be?

**Comment by daniellekirkwood** [comment]
@niquewoodhouse  I believe we changed the spaces icon (it's different in iOS at least) could you work with Eric here please.

**Comment by daniellekirkwood** [comment]
The image in the release experience will also need to be updated, @niquewoodhouse could you provide the link to that as well please?

**Comment by niquewoodhouse** [comment]
@ericdecanini https://www.figma.com/file/DQq9Qi8rRJ7cBPFt98uDAM/App-layout-release-xp?node-id=57%3A6092
