### ISSUE TITLE
Threads: Summaries in timeline are slow to load

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-android#7042]
### Steps to reproduce

1. Open a timeline with existing threads
2. Look for the thread summary below each root message

#### What did you expect?
Thread summary loads quickly

#### What happened instead?
Thread summary loads slowly

### Application version and app store

1.4.34

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by Johennes** [comment]
@kittykat could you quantify the delay compared to another platform, e.g. Element Web?

**Comment by kittykat** [comment]
It's there instantly now
