### ISSUE TITLE
No/slow system notification when receiving threaded message in the background

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-android#7047]
### Steps to reproduce

1. Start with a locked phone
2. Receive a threaded message while app is in the background

#### What did you expect?
Expect instant system notification

#### What happened instead?
Notification takes a long time to come through or doesn't come through at all

### Application version and app store

1.4.34

### Homeserver

matrix.org

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by daniellekirkwood** [comment]
Has this improved @kittykat ? 
@fedrunov do we know if threads notifications still take longer to arrive than other notifications?

**Comment by daniellekirkwood** [comment]
Are all notifications this slow, or is it specifically threads ones?

**Comment by kittykat** [comment]
I am seeing on screen notifications immediately now but my phone isn't buzzing for notifications both in threads or the main timeline at all when it should be… I'll let you decide @daniellekirkwood  if you want to close or not.

At the time when I filed the issue, it was specifically threads notifications.

**Comment by daniellekirkwood** [comment]
As this is Threads related, we'll close it out but if notifications aren't working on your devices we should raise that as an issue .
