### ISSUE TITLE
Threads: Long threads are slow to load with bubbles layout

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-android#7049]
### Steps to reproduce

1. Open a thread with 17+ threaded messages

#### What did you expect?
Can see messages instantly

#### What happened instead?
Messages are slow to load

### Application version and app store

1.4.34

### Homeserver

matrix.org

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by Johennes** [comment]
@kittykat could you quantify the delay compared to another layout?

**Comment by kittykat** [comment]
I can't reproduce this specifically about bubble layouts, but I do have issues with loading times for the threads overview which I filed as a new issue
