### ISSUE TITLE
"Room" revamp [Suggestion]

### ISSUE THREAD

**Issue by Flam3z** [vector-im/element-android#705]
Change the name "rooms" to "Houses" and let those "Houses" be able to create channels called "Rooms". Which could either be text based or VOIP based. With the channels having their own permissions set by proper moderation to however they want. e.g. (photos only, voice only, text only, emoji only etc.)

**Comment by MegaArthur** [comment]
We already have "communities" for that, but I'd certainly like to see communities getting a boost, if they were much more discord-like it would be great.

**Comment by Flam3z** [comment]
That's what I mean. Channels within the community but with different names.
