### ISSUE TITLE
Invite Button doesn't work

### ISSUE THREAD

**Issue by DoM1niC** [vector-im/element-android#7053]
e.g. Create a fresh Room or use a exist one, try to invite people over the Invite button or invite button as fab in the Member list activity

https://user-images.githubusercontent.com/1436958/188780004-8953f773-f393-49d0-bb64-8cf0d5e7a365.mp4

**Version:** develop 
**Server:** 1.67.0RC1

**Comment by jmartinesp** [comment]
I've tried to reproduce it myself with both an older version and the code in `develop` and it seems to work fine for me, both in an empty and a room that's already in use. Could you attach some logs so we can investigate them and try to reproduce your issue?

**Comment by bmarty** [comment]
@jmartinesp I can repro the bug when a Space is currently selected.

Rising the severity.

**Comment by bmarty** [comment]
(and working on a fix, I have found the root cause)

**Comment by bmarty** [comment]
In the mean time, from the room clicking on the top right menu / Invite works.
