### ISSUE TITLE
Add support for pinned messages

### ISSUE THREAD

**Issue by sarekv** [vector-im/element-android#7062]
### Your use case

Would be great to have an option to add multiple pinned messages in a given channel for easy reference. 

#### Why would you like to do it?
Important updates and information for users can be pinned on the channel header area.

#### How would you like to achieve it?
Press and hold a message / text and have the option to pin it to top.

### Are you willing to provide a PR?

No

**Comment by sarekv** [comment]
Would be great to have this on desktop as well. Should i open a separate feature request for that too?

**Comment by witchent** [comment]
Duplicate of https://github.com/vector-im/element-android/issues/357

Also, Web/Desktop has this feature in labs already

**Comment by sarekv** [comment]
Alright, thanks for the info. Guess this can be closed then.

**Comment by jmartinesp** [comment]
As mentioned, closing this as a duplicate of #357.
