### ISSUE TITLE
New App Layout | PagedList is buggy (long placeholders, jumpt to top)

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/element-android#7079]
When using the new layout (nighlty) I have several problems with the room list:
- Placeholders appearing fast and stay quite long (can be forever). It's not happening in production app
- When placehodlers are replaced the list sometimes jump to top

**Comment by daniellekirkwood** [comment]
I this a duplicate of this: https://github.com/vector-im/element-android/issues/7028

**Comment by fedrunov** [comment]
> I this a duplicate of this: #7028

No, it's not, it looks more like it's another symptom of slow list loading from this https://github.com/vector-im/element-android/issues/7030
