### ISSUE TITLE
Quickly double clicking the space button always crashes the app

### ISSUE THREAD

**Issue by bmarty** [vector-im/element-android#7087]
> Thread: main, Exception: java.lang.IllegalStateException: Fragment already added: SpaceListBottomSheet{c83880a} (1a201cc5-17ed-481c-8d34-4f5a958465c5 tag=SpacesBottomSheet)

I can repro.

https://github.com/matrix-org/element-android-rageshakes/issues/42645

**Comment by daniellekirkwood** [comment]
Is this specific to the app layout version?

**Comment by ericdecanini** [comment]
Given the error message, it would be yeah. I managed to reproduce this myself and I'm coming with a fix

> Is this specific to the app layout version?

**Comment by bmarty** [comment]
Fixed in 1.4.38
