### ISSUE TITLE
Inconsistent search/filter icon in new and default app layout

### ISSUE THREAD

**Issue by noantiq** [vector-im/element-android#7094]
### Steps to reproduce

1. Open Element Android, notice the filter or search button on the upper right.
![Screenshot_20220911-115807](https://user-images.githubusercontent.com/39308834/189522447-f147e55e-b91f-4d0c-ab4a-91fa2caa913e.png)
2. Go to Labs and switch to the new app layout.

#### What did you expect?
The filter or search button icons are the same since their functionality has not changed (correct me if I am wrong here). So I expected the icon I could see in the new app layout to be used in the default layout as well.
![Screenshot_20220911-115702_1](https://user-images.githubusercontent.com/39308834/189522605-591cc180-a57c-4209-883c-d4cbae19ff87.png)

#### What happened instead?
The icon was replaced only in the new app layout.

### Will you send logs?

No

### Are you willing to provide a PR?

Yes

**Comment by noantiq** [comment]
The icon left to the input when using the search should probably be changed as well and the hint should probably say something like "Search", see:
![Screenshot_20220911-140033](https://user-images.githubusercontent.com/39308834/189526548-e08ffb26-6ed5-4bbc-bbfb-4dd734328be8.png)
Same goes for the tooltip, see:
![Screenshot_20220911-135711](https://user-images.githubusercontent.com/39308834/189526568-5f13c0e4-c131-4cfd-b815-a5959378a205.png)

All of that would bring it in line with Web.

**Comment by daniellekirkwood** [comment]
@amshakal  

We've discussed this in the past but I can't remember where we landed. It may be best to keep the Search icon on the home screen - even though it's not technically search the filter icon might be too abstract? Search is easier and faster to grok... 

WDYT?

**Comment by amshakal** [comment]
Yes, after we de-labs the new layout on androird. This confusion would go away. We decided to stick to search because search as a feature doesn't exist and with this, we can build upon it over time.

**Comment by noantiq** [comment]
Hi @daniellekirkwood, if I read the comment correctly and you are sticking to search, there is still some inconsistency to be resolved. As wrote in [my comment](https://github.com/vector-im/element-android/issues/7094#issuecomment-1242950373), the search icon has a tooltip that says "filter" and when you tap it you are navigated to a screen that uses the old icon and has a hint that says "filter" again.

**Comment by daniellekirkwood** [comment]
Thanks, @noantiq. We're aware of the inconsistencies, unfortunately that's where we're choosing to stay for now. 

We've found in testing that the Search icon is much more recognisable than the filter icon (even though the action is a filter). As the action is a filter, not Search, we'll leave the ToolTips and the icon on the Filter page accurate. 

In our backlog & roadmap we have a project to enhance and improve the Search capabilities on our mobile clients - with this update your comments will be resolved :) 

Thanks so much for your time.

**Comment by noantiq** [comment]
Then I just misunderstood, thank you for the clarification!
