### ISSUE TITLE
App Layout: Current filter tab is reset when scrolling

### ISSUE THREAD

**Issue by noantiq** [vector-im/element-android#7096]
### Steps to reproduce

1. Open Element Android.
2. Go to Labs and activate the new app layout.
3. Activate the "Show filters" option in the layout preferences.
4. Navigate to the "People" tab.
5. Scroll down through the list to hide the filter tabs.
6. Scroll up again.

#### What did you expect?
The selected filter tab (People) is still selected
#### What happened instead?
The first filter tab (All) is selected, when pressing "All" you can not navigate to all chats but you have to select the "People" filter tab again to be able to navigate to all chats.

This might as well happen in every tab, but my "Unreads" and "Favourites" tab are not full enough for me to scroll and test it.

### Your phone model

Pixel 6

### Operating system version

Android 13

### Application version and app store

1.4.36 (GPlay Beta)

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by fedrunov** [comment]
duplicates https://github.com/vector-im/element-android/issues/6845
