### ISSUE TITLE
New App Layout: Favorites are not shown with filter deactivated

### ISSUE THREAD

**Issue by kojid0** [vector-im/element-android#7162]
### Steps to reproduce

When deactivating filters in layout settings, favorites are not shown anymore.

Solution:
1) Pin them to the top, or
2) Show them in the same way like 'recents' as icons (horizontal top bar)

#### What did you expect?
Favorite Chats are pinned to top
#### What happened instead?
Favorite Chats are not pinned to top

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by noantiq** [comment]
I think that should be #7095

**Comment by fedrunov** [comment]
Thank you for your report.

It seems like duplicate for #7095, so I'm going to close this issue now so we can focus on the older issue.
