### ISSUE TITLE
Room list keeps sending me back to the top

### ISSUE THREAD

**Issue by robintown** [vector-im/element-android#7164]
### Steps to reproduce

1. Use the new layout
2. Scroll down in the room list

#### What did you expect?

To stay where I am in the list

#### What happened instead?

After a few seconds, I'm sent back to the top:

https://user-images.githubusercontent.com/48614497/190874067-5eb8f36b-a739-45c5-959d-f151c3372606.mp4

For longer lists, such as my 'All chats' screen, this prevents me from scrolling all the way to the bottom.

### Your phone model

Google Pixel 3a

### Operating system version

LineageOS 19 (Android 12)

### Application version and app store

1.4.36 [40104360] (F-6cada8f6)

### Homeserver

Synapse 1.67

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by fedrunov** [comment]
Hi, thanks for rising this issue, this was fixed along with a placeholder height in this [PR](https://github.com/vector-im/element-android/pull/7145) and will be shipped in next release. Before that you can try to enable recents in layout preferences, this, most likely will, fix problem
