### ISSUE TITLE
Chat message timed destruction function

### ISSUE THREAD

**Issue by cz9** [vector-im/element-android#7167]
### Your use case

I suggest adding a timed destruction feature for chat messages as soon as possible. Allow users to set their own message destruction time, such as one day or seven days or something like that.

### Additional context

This feature is great for protecting users' privacy and keeping the space occupied by chat messages small. This feature is great for protecting user privacy and keeping the space occupied by chat messages small.

### Are you willing to provide a PR?

No

**Comment by jmartinesp** [comment]
Thanks for taking the time to request this enhancement. This feature has been requested several times and it's being discussed at https://github.com/vector-im/element-meta/issues/82.
