### ISSUE TITLE
Crash - App restarts in a loop

### ISSUE THREAD

**Issue by yostyle** [vector-im/element-android#7224]
### Steps to reproduce

1. Install the app
2. Launch the app

### Outcome

When the dialog to ask if the app can send notifications is displayed, app restarts in a loop on **Android 13** after a fresh install. From Android 13, permission is asked on the first run of the app.

I guess this issue is related to Strandhogg detection because we have this log in logcat in debug : `im.vector.app.debug E/VectorActivityLifecycleCallbacks$onActivityCreated: Application is potentially corrupted by an unknown activity`

The activity `com.android.permissioncontroller.permission.ui.GrantPermissionsActivity` launched by OS is detected as corrupted because it is not declared in the app manifest.

To avoid this problem we should add exposed activities by [PackageInstaller app](https://android.googlesource.com/platform/packages/apps/PackageInstaller/+/refs/heads/master/AndroidManifest.xml) in [activitiesInfo array](https://github.com/vector-im/element-android/blob/8d112a47d7ee9b2970d588a7f244aa5d2fd3f0c8/vector/src/main/java/im/vector/app/features/lifecycle/VectorActivityLifecycleCallbacks.kt#L102)

### Your phone model

Google Pixel 6A

### Operating system version

Android 13

### Application version and app store

Element version 1.4.36

### Homeserver

matrix.org

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by pacanukeha** [comment]
I'm getting the same on a Pixel 4a 5G

**Comment by dkasak** [comment]
Seeing the same on a Pixel 6 Pro with Android 12. Repro steps for me:

1. Kill all Element activities in the recent apps view.
1. Start Element normally, via the icon.
1. Background it by going back to the launcher.
1. Open Signal (or whatever).
1. Share something to Element. Notice there are now two Element activities in recent apps.
1. In the new activity, click + then the paperclip, to open the file manager.
1. Background this activity by going back to the launcher.
1. Tap on the Element icon.

Step 8 doesn't trigger it *every* time for some reason, but if it doesn't, try waiting a bit or switching back to the other activity, backgrounding it, then tapping the Element icon again.
