### ISSUE TITLE
redactions show up in notifications

### ISSUE THREAD

**Issue by NotAFile** [vector-im/element-android#723]
I receive notifications for redactions in rooms.

**Comment by bmarty** [comment]
Hi @NotAFile , could you be more specific please? Are you talking about notification in the notification panel?
Any screenshot will be appreciated :)

**Comment by NotAFile** [comment]
@bmarty it shows up in the android notifications, but not the riotx notifications panel.

![Screenshot_20191220-204130](https://user-images.githubusercontent.com/5447747/71287639-33740080-2369-11ea-9ab2-5ac57b06ded4.jpg)
![Screenshot_20191220-204109](https://user-images.githubusercontent.com/5447747/71287650-3b33a500-2369-11ea-8933-a62944babf63.jpg)

**Comment by NotAFile** [comment]
The same also applies for reactions

**Comment by bmarty** [comment]
ok, thanks for the screenshots

**Comment by ydnax** [comment]
this is still an issue. a good example is  Synapse Anouncements. I expect to only get notifications for new releases but instead 3-5 times a day i get a notification about a redact event in the room. This is very anoying and there doesn't seem to be a way to disable it except muting notifications for the room in general.

**Comment by ydnax** [comment]
While looking for the issue i found #1491 which can be merged into this issue i think

**Comment by Florian14** [comment]
Closed in favor of #1491
