### ISSUE TITLE
Please make an own F-Droid Repo

### ISSUE THREAD

**Issue by poltrian** [vector-im/element-android#7249]
### Your use case

Its take a long time for new Version for F-Doid users. We're waiting for the security fix from Today. Flatpack, Google and iOs User have the fixed version. F-Droid user have to wait days.

### Are you willing to provide a PR?

No

**Comment by bbhtt** [comment]
Duplicate https://github.com/vector-im/element-android/issues/1857

Related https://github.com/vector-im/element-android/issues/4913

**Comment by yostyle** [comment]
Duplicate of #1857
