### ISSUE TITLE
Filters sometimes don't work 

### ISSUE THREAD

**Issue by SimonBrandner** [vector-im/element-android#7253]
Sometimes I switch to Unreads or Favorites, am shown the correct rooms for a second or two and then all rooms are shown even though a filter is still selected 

App version: 1.5.2-dev-nightly [212577240] (G-0c451025)

**Comment by daniellekirkwood** [comment]
@ericdecanini & @fedrunov can you investigate?

**Comment by SimonBrandner** [comment]
Haven't seen this for a while - closing
