### ISSUE TITLE
Newline deletes text before

### ISSUE THREAD

**Issue by witchent** [vector-im/element-android#7357]
### Steps to reproduce

1. Be on newest develop version
2. Enter chat, write something, try to make a newline

#### What did you expect?
Newline to appear below the last written line

#### What happened instead?
The whole text before vanishes, instead leaving a weird looking newline

### Your phone model

Oneplus 6

### Operating system version

Android 12

### Application version and app store

1.5.4-dev 212713750

### Homeserver

Synapse

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by jmartinesp** [comment]
Just to confirm: is the rich text editor enabled?

Also, if it is: could you try to reproduce the issue and maybe record a video? Logs are welcome, but I don't think they'll have much info in this case, and I can't reproduce your issue with the steps you mentioned.

**Comment by witchent** [comment]
The rich text editor is disabled - if I enable it I don't have this problem anymore, but I don't like it so I would prefer it if it works without the rich text editor as well.

I am trying to attach a video recording but it fails right now, so I will try again later. Thanks for looking into it already.

**Comment by witchent** [comment]
There you go:

https://user-images.githubusercontent.com/13248566/196116311-6a195f94-9d2a-4a1c-ac65-58abbb0c114f.mp4

The body of the message also only has
"
hello"

**Comment by wo80** [comment]
Can confirm this issue. Absolutely annoying!

After Element update from v1.4.x to latest 1.5.4 on a Samsung Galaxy Tab A 2018, Android 10. Affects only the plain text editor, rich text editor works. But I'd like to disable it.

**Comment by j-maas** [comment]
I also have this issue with the Microsoft SwiftKey Keyboard. When I change to Gboard, enter works as expected.

So this might be an incompatibility issue between the keyboard and Element. I have not noticed this issue with the keyboard in any other app.

**Comment by wo80** [comment]
@jmartinesp As the new rich text editor has problems too (see https://github.com/vector-im/element-android/issues/7417, https://github.com/vector-im/element-android/issues/7420) - is it possible to downgrade to a previous version? Never tried this, so I thought I'd better ask. If it's possible, which version should I choose - is v1.5.2 ok?
Or will there be a release in the next days that includes a fix, so I can switch back to the plain text editor? The whole affair is really annoying!

**Comment by JokerGermany** [comment]
> I also have this issue with the Microsoft SwiftKey Keyboard. When I change to Gboard, enter works as expected.

@witchent shows the error wird Gboard.
Didn't look like it's related to SwiftKey like this one: #5597

**Comment by witchent** [comment]
> > I also have this issue with the Microsoft SwiftKey Keyboard. When I change to Gboard, enter works as expected.
> 
> @witchent shows the error wird Gboard. Didn't look like it's related to SwiftKey like this one: #5597

Actually, my keyboard is AnySoftKeyboard, so it might be related if they share any common behaviour
