### ISSUE TITLE
Android Wear OS / Pixel Watch compatibility

### ISSUE THREAD

**Issue by KeenMaron** [vector-im/element-android#7380]
Hi,

it would be nice if there will be an upgrade of the element android app to support messages on Wear OS / pixel watch device, like whatsapp.

This feature would be awesome :)!

Edit: Ok a friend of mine told me, he can answer element messages on his watch. Weird, maybe there it is a setting issue on my watch / phone...

**Comment by bbigras** [comment]
With wearos, when you get a notification, you can reply to it.

It could still be cool to be able to compose new messages and look at rooms.

I wonder if apps that need a phone are allowed. Not sure if I want my watch to fetch all my room data and kill my battery.

**Comment by KeenMaron** [comment]
I fixed it. You have to reset the notification settings in phone settings explicit for the element app. Not the notification setting in the app itself.
