### ISSUE TITLE
Encryption keys not shared in one of my DMs

### ISSUE THREAD

**Issue by babolivier** [vector-im/element-android#7403]
### Steps to reproduce

1. Open a DM
2. Send a message

#### What did you expect?

The message can be decrypted by the recipient.

#### What happened instead?

Here's the DM from the recipient (@Half-Shot)'s side:

![image](https://user-images.githubusercontent.com/5547783/196658493-b955cd5b-fc2a-4cf8-9f03-5302183d85a9.png)

The messages that were successfully decrypted were sent from Element Web, the ones which keys seem to be withheld were sent from Element Android.

This room (`!CxwbkNeawVzFvdXwza:half-shot.uk`) is the only one impacted that I've seen (I've been able to send encrypted messages in other rooms which Half-Shot has been able to see), but this issue happens consistently with every message that I send to this room with Element Android.

### Your phone model

Fairphone 3

### Operating system version

Android 11

### Application version and app store

Element version 1.5.2 [40105022] (G-b11679) - Matrix SDK version 1.5.2 (f6411d67) - Olm version 3.2.12 - From Play Store with beta channel joined

### Homeserver

abolivier.bzh

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by Hoeze** [comment]
Same problem here

**Comment by babolivier** [comment]
I have submitted one more rageshake in case it helps: https://github.com/matrix-org/element-android-rageshakes/issues/44662

Since this issue makes the DM completely unusable from Element Android, I've done a `/discardsession` to force it to create a new session (so I'm not reproducing the issue anymore, but I believe it's still a thing).

**Comment by G2G2G2G** [comment]
had this start happening last few days. From what I've seen over the past several years the "request new key" doesn't really do anything or devices ignore it.

I wonder if the new labs implementation with the "sharing keys for old history" has something to do with it. Hopefully that makes the requesting key work too

**Comment by BillCarsonFr** [comment]
We need the eventId and sessionId in order to investigate.
Will close if we can't have them

**Comment by babolivier** [comment]
> We need the eventId and sessionId in order to investigate.

Aren't they in the logs? The ID of one of the problematic events (the last one I'm sending in the screenshot above) is `$1666170470399vgBOt:abolivier.bzh`, I'm not sure how I'd get the session ID.

**Comment by robertmx** [comment]
I had the same problem and could fix that by deleting all "dead" sessions. I suspect (might be totally wrong here) that session A1 (my side) sent encrypted messages to session B2, that was stale / not accessible. Thus session B1 (the intended recipient) could not decrypt these messages because it could not get the required keys from session B2.
Anyway it is rather unfortunate for a decrypted DM to suddenly stop working. It did not recover for three weeks.

NB: I had another session A2 open, that could still communicate without problems with peer session B1. That was rather confusing. The nontechnical user owning session B1 was not particularly impressed :-/.

**Comment by richvdh** [comment]
> Aren't they in the logs? 

Not in a way that is easy to find, no. Thanks, will try to investigate `$1666170470399vgBOt:abolivier.bzh`

**Comment by richvdh** [comment]
Summary of my investigation so far:

At some point before 18th October, @babolivier's device created a megolm session `BFcWX863ZXpBNrigxDrfvHD14vS+/m3s8x8q8qFF0vo` and should have shared the keys for that session with @Half-Shot's device. That process appears to have failed for some reason, but we don't seem to have rageshake logs from either device going back far enough.

@Half-Shot's device sent room-key-requests to @babolivier's, but it's currently unclear to me if they were answered.

**Comment by richvdh** [comment]
> @Half-Shot's device sent room-key-requests to @babolivier's, but it's currently unclear to me if they were answered.

They weren't, because Element Android no longer responds to room-key-requests from other users.

Unfortunately I don't think we can do much more here, since we don't have the logs from when the room key should have been sent in the first place.
