### ISSUE TITLE
Sharing broken under v1.5.4

### ISSUE THREAD

**Issue by scottwallacesh** [vector-im/element-android#7410]
### Problem
Sharing links or images no longer works.

### To replicate
Visit a website in a browser, hit "share" and choose Element and then a room.  Nothing happens. Normally the text box is populated with the content from the share, ready to post to the room you selected.

### Notes
It worked on the previous version, v1.5.2, before the upgrade to v1.5.4.

### Versions
Element: 1.5.4 [40105042] (G-b12120)
Android: 13
Device: Pixel 4a

**Comment by scottwallacesh** [comment]
This could be a dupe of #7400.

**Comment by GeoBSI** [comment]
Same issue here, on Pixel 6 Pro (v1.5.4)

**Comment by bmarty** [comment]
Dup of #7400
