### ISSUE TITLE
Rich text editor: inexplicable and unusable area.

### ISSUE THREAD

**Issue by YamatoRyou** [vector-im/element-android#7411]
### Steps to reproduce

1. Enable "rich text editor" in the "Lab;
2. Go to a room without permissions.

#### What did you expect?
n/a

#### What happened instead?
A blank area appears at the bottom of the screen.
![{ACB19440-B3AC-B8DD-0281-2DE208796900}](https://user-images.githubusercontent.com/48104960/196806738-c8d84ecc-080b-43f0-a7df-c754a779c2be.png)

### Your phone model

Xiaomi Mi 9T; HMD Global TA-1054

### Operating system version

MIUI 12.5 by xiaomi.eu (based on Android 11); Android 8.1

### Application version and app store

Element Android 1.5.4 (Google Play)

### Homeserver

Synapse 1.69.0

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by jmartinesp** [comment]
This should have been fixed already since we fixed the margins several times and moved the 'user typing' view as part of the timeline.
