### ISSUE TITLE
Rich text editor: When entering the character, "Send" button flashes constantly.

### ISSUE THREAD

**Issue by YamatoRyou** [vector-im/element-android#7413]
### Steps to reproduce

1. Enable "rich text editor" in the "Lab";
2. Go to a room and type some text.

#### What did you expect?
n/a

#### What happened instead?
Each of a character, the button flickered once.

### Your phone model

Xiaomi Mi 9T; HMD Global TA-1054

### Operating system version

MIUI 12.5 by xiaomi.eu (based on Android 11); Android 8.1

### Application version and app store

Element Android 1.5.4 (Google Play)

### Homeserver

Synapse 1.69.0

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by jmartinesp** [comment]
This should have been fixed by #7572.
