### ISSUE TITLE
rich text editor breaks back button

### ISSUE THREAD

**Issue by lub** [vector-im/element-android#7420]
### Steps to reproduce

1. open a room room
2. tap on the rich text editor area (keyboard pops up, like it should)
3. press android back button (not the arrow within element itself) (keyboard disappears, like it should)
4. press android back button again

#### What did you expect?
To get back to the previous view, like it works without enabled richt text editor or if I don't tap on the rich text editor.

#### What happened instead?
Nothing happens. It just stays in the timeline view.

### Your phone model

Oneplus A5010

### Operating system version

Android 12/LienageOS 19-20221018-nightly-dumpling

### Application version and app store

1.5.6-dev [212772242] (F-b12134) develop

### Homeserver

imninja.net

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by jmartinesp** [comment]
It seems like the hardware keyboard listener that we use to intercept key presses actually intercepts the back key too by accident.

**Comment by jmartinesp** [comment]
This should have been fixed by #7572.
