### ISSUE TITLE
Resist to decryption errors in an edit chain.

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/element-android#7430]
Currently if an original message that was edited is in decryption error, the message will be displayed as a `unable to decrypt`/`waiting for that message` even if the edits are succesfully decrypted.

It's more visible recently due to this synapse bug https://github.com/matrix-org/synapse/issues/14252

I think it's reasonable to display the latest content if we can decrypt it?

**Comment by brandsimon** [comment]
Workaround: long-click the message and copying it will retrieve the last edit.

**Comment by BillCarsonFr** [comment]
Closing for now as [as per spec](https://spec.matrix.org/v1.4/client-server-api/#validity-of-replacement-events) initial event content is required for proper validation. Spec issue tracked here https://github.com/matrix-org/matrix-spec/issues/1299
The change causing the issue [has been reverted](https://github.com/matrix-org/synapse/pull/14283)
