### ISSUE TITLE
Element crashes my phone

### ISSUE THREAD

**Issue by koyuawsmbrtn** [vector-im/element-android#7433]
### Steps to reproduce

1. Use the app for a couple of minutes
2. Phone hangs (when music plays it bugs out) and shuts off

#### What did you expect?

My phone not crashing

#### What happened instead?

Phone crashes like a champ

### Your phone model

Nokia G21

### Operating system version

Android 12

### Application version and app store

Element version 1.5.2 [40105022] (G-b11679), olm version 3.2.12, Matrix SDK version 1.5.2 (f641d67) from Google Play

### Homeserver

chat.mozilla.org, hosted on EMS

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by tusooa** [comment]
Can confirm this. Element uses 1.4G ram on my phone.

**Comment by JaneValleyhasBtaken** [comment]
I can confirmed that, Tusooa own a Pixel 4 XL with 6 gig ram

**Comment by koyuawsmbrtn** [comment]
I can close this issue now. A couple of updates on my phone fixed it. It was probably because the Android 12 release was quite buggy when it came out.
