### ISSUE TITLE
[WYSIWYG] Turning off formatting and then tapping spacebar turns that formatting back on

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element-android#7465]
### Steps to reproduce

1. Enable the "Enable rich text editor" in labs settings
2. Type some text with some formatting enabled.
3. Disable some or all of the formatting with the WYSIWYG button
4. Hit space
5. See the space contain the formatting even though you tried to disable it.

You can see the behaviour in the video here:

https://user-images.githubusercontent.com/1342360/198070967-a7d34613-b48e-41a4-ab69-cebbe68833c0.mp4

It seems that the formatting only turns itself back on if there is a character preceding the space with that formatting. If there is a space preceding the space, the bug does not occur.

Possibly related: https://github.com/vector-im/element-android/issues/7464

#### What did you expect?

The formatting of my space to remain as what I chose when I disabled several formatting options. i.e. the options should not turn themselves back on after I hit space.

#### What happened instead?

What you see above.

### Your phone model

Google Pixel 4a 5G

### Operating system version

Android 13, GrapheneOS

### Application version and app store

1.5.4-dev [40105042] (F-b12018) tech/bump-wysiwyg-lib-to-0.2.1

### Homeserver

matrix.org

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by jmartinesp** [comment]
Could you try again with the latest nightly? It *should* be fixed now.

**Comment by anoadragon453** [comment]
I haven't had a chance to test this, so I'm just going to assume you fixed it :)
Feel free to re-open or make a new issue if that's not the case.
