### ISSUE TITLE
Ephemeral messages - Self destructing events feature?

### ISSUE THREAD

**Issue by Thatoo** [vector-im/element-android#747]
**Is your suggestion related to a problem? Please describe.**
Ephemeral messages or self destructing chat/salon is a requested feature by people for whom privacy is a matter of life

**Describe the solution you'd like**
As this synapse feature is coming, https://github.com/matrix-org/synapse/pull/6409, would it be possible to have such feature available on RiotX-android?

**Comment by Thatoo** [comment]
There is a proposal for synapse server to handle that feature, merged into develop now, here : https://github.com/matrix-org/synapse/pull/6409

So it could be possible soon now, right?

**Comment by trymeouteh** [comment]
matrix-org/synapse#6287

I created this issue in hopes that they will create a standard for self destructing messages within Matrix with many options.

I hope this can be developed and released for Matrix and then the clients such as Element can implement it.

**Comment by Gushtera** [comment]
Is supported by the Matrix server. Here is more info: 
https://github.com/matrix-org/synapse/pull/6409/commits/c9823807beb567b95766bd47f85db894308ef7d4

**Comment by kittykat** [comment]
Thank you, we appreciate that you took your time to file this enhancement request. I am going to close it for now in favour of a cross-platform issue to help us track the request more effectively. Please follow this issue for further updates: vector-im/element-meta/issues/82
