### ISSUE TITLE
voice broadcast：broadcasting event still on the screen after removing...

### ISSUE THREAD

**Issue by NewOcean11** [vector-im/element-android#7470]
### Steps to reproduce

1. when sending voice, no visualizer...
 2. fail to remove broadcasting even deleted on the desktop

### Outcome

just wonder why this happened on the mobile

### Operating system version

android 12

### Application version and app store

1.54

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by NewOcean11** [comment]
anyone can help?

**Comment by giomfo** [comment]
Should be fixed now  (see https://github.com/vector-im/element-android/pull/7629)
