### ISSUE TITLE
Image sharing from gallery no longer possible

### ISSUE THREAD

**Issue by neonknight** [vector-im/element-android#7471]
### Steps to reproduce

1. Open your Android image gallery app
2. Select random picture, click share button, select Element Messenger, select Chatroom to share image to

#### What did you expect?

I would expect the image to be shared (as it happened until yesterday before last update to 1.5.4)

#### What happened instead?

Nothing. No image is shared to chatroom. The only way to share images is by selecting them from within Element.

### Your phone model

various (Nokia, Oppo, Samsung, Huawei)

### Operating system version

various (Android 10, 11, 12)

### Application version and app store

Element 1.5.4 Olm 3.2.12 from Google Play

### Homeserver

synapse:v1.69.0

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by bmarty** [comment]
Thanks for reporting, this is #7400
