### ISSUE TITLE
Quick reply to thread message notification goes to main timeline

### ISSUE THREAD

**Issue by fedrunov** [vector-im/element-android#7475]
- receive push notification for message in a thread
- use "quick reply" to reply for this message

expected: reply message is sent to a thread
actual: reply message is sent to a thread and not relates to initial message/thread

**Comment by daniellekirkwood** [comment]
@fedrunov does this happen every time? I think so, so will mark as O-Frequent but please change that label if its only occasional

**Comment by amywalkerdev** [comment]
I get this consistently when testing
