### ISSUE TITLE
Convert voice to text

### ISSUE THREAD

**Issue by Nizami20052022** [vector-im/element-android#7483]
### Have you considered any alternatives?

Convert voice message to text. Telegram has this function.

### Are you willing to provide a PR?

No

**Comment by RayBB** [comment]
This would be great!
It's related to
https://github.com/vector-im/element-android/issues/4244

**Comment by mnaturel** [comment]
Hi @Nizami20052022, thanks for your suggestion. I am closing this issue in favor of keeping the existing #4244.
