### ISSUE TITLE
Migrate off BuildKite

### ISSUE THREAD

**Issue by benbz** [vector-im/element-android#7493]
We're ramping down our BuildKite usage and this project is one of the few left on it. How much work would it be to migrate to GH Actions/similar so that CI was under your span of control?

**Comment by bmarty** [comment]
Buildkite is used at the moment by this project to:
- build APKs on every pull requests. This is also done by GitHub action, and Buildkite is more used as a backup CI here. Ideally the existing GitHub action could provide an easy way to install the generated APK (by QR code, etc.), to replace the current script we have to download and install APK by providing a buildkite build number.
- build release (unsigned) APKs for the PlayStore. A new GitHub action has to be created to do this work, every time the `main` branch is pushed. The release script will need to be updated to.

I can work on this this week.
