### ISSUE TITLE
Sharing media (photos) from an external app to Element does not do anything

### ISSUE THREAD

**Issue by kylxbn** [vector-im/element-android#7525]
### Steps to reproduce

1. Where are you starting? What can you see?

I am viewing an image from an external app. In this case, the default Samsung Gallery app.
    
2. What do you click?

I choose the Share icon, and choose `Element` (or an Element user's name, or an Element chat room)

#### What did you expect?

I am expecting that the media (photo) I want to share gets either shared immediately with the person or with the chatroom, or previewed with a "Send" button visible before actually being shared.

#### What happened instead?

The person's chat history, or the chatroom's chat history just opens with nothing else happening.

### Your phone model

Samsung Note20 Ultra

### Operating system version

Android 12, One UI 4.1

### Application version and app store

Element version 1.5.4, olm version 3.2.12 from F-Droid (although another Android phone with Element installed from Play Store exhibits the same problem)

### Homeserver

matrix.org

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by JimboJoe** [comment]
Same symptoms since a few days on my Samsung Galaxy A32 EE 5G (Android 12) and Fairphone 3 (Android 11), both on version 1.5.4 from Play Store. I'm using my own synapse homeserver.

**Comment by v411e** [comment]
Duplicate of #7400? Should be fixed in 1.5.6

**Comment by kylxbn** [comment]
@v411e Hi, thanks for the reply and sorry for the duplicate. (I did search for duplicates but I didn't see that issue for some reason)

I hope that 7516 gets fixed soon! I'd help but I'm not really familiar with mobile app dev... Sorry!

Thanks again!
