### ISSUE TITLE
Play Store: Not availible in your region (Germany)

### ISSUE THREAD

**Issue by defini-tiv** [vector-im/element-android#7568]
Google play seems to not provide Element in Germany?
Whats the background of this?
Is there somethimg im missing?
Have you an influence on it, is it google or german law?

Getting issues before even installing the app is devastating for getting new (non-tecnical) useres.

**Comment by s-liwka** [comment]
You can download Element from F-Droid if you cannot find it in the Play store

**Comment by defini-tiv** [comment]
I use F-Droid and i love it.
But there are multiple reasons to not use it and it should not be the only way to install Element on Android.
Availability in the google play store is really crucial for distribution.

**Comment by bmarty** [comment]
In Germany you need to be 18 or more to be able to download the app, due to German laws. See https://github.com/vector-im/element-android/issues/1858 if you need more details.
