### ISSUE TITLE
Split abi for F-Droid release

### ISSUE THREAD

**Issue by linsui** [vector-im/element-android#7589]
#### What would you like to do?
I 'd like to publish 4 apks for every version instead of 1 universal apk.

#### Why would you like to do it?
The apk size is large. By splitting the abi we can reduce the size from 100M to 50M.

#### How would you like to achieve it?
We can patch the abiFilters or you can provide some api to set it.

### Additional context

https://gitlab.com/fdroid/fdroiddata/-/issues/2809

### Are you willing to provide a PR?

No

**Comment by bmarty** [comment]
I guess https://gitlab.com/fdroid/fdroiddata/-/issues/2809 have to be handled first.

@TheLastProject WDYT?

**Comment by linsui** [comment]
> I guess https://gitlab.com/fdroid/fdroiddata/-/issues/2809 have to be handled first.

It's a tracking issue.

We talked about this in https://gitlab.com/fdroid/fdroiddata/-/merge_requests/12068.

By the way, I guess the `Unable to strip the following libraries` warnings are unrelated.

**Comment by riverside6** [comment]
Maybe this issue might help? #4323

**Comment by linsui** [comment]
Yes, I'm here to solve that issue. I want something, e.g. project props to control the abiFilters. We can also patch it in the build metadata. Both are OK to me.

**Comment by TheLastProject** [comment]
I thought @linsui's reply was enough but seeing this has been silent for a week I'll reply to the WDYT:

I think linsui knows a lot more about Gradle details than me and it would be great to discuss what ABIs you want to (or already do for Google Play, if so, how?) split on and how you do the version codes so we can keep this in sync between Google Play and F-Droid to prevent possible confusion :)

**Comment by Bubu** [comment]
Aren't the play store builds already setup to do one APK per Abi by default? And we disable that in the metadata file somehow? (I haven't looked at the recipe in ages, so no idea if that's current information.)

I think it was also always possible to build split apks but annoying to work with within fdroid (you do 4x20 minute builds instead of one and the metadata file gets confusing and a few other oddities within fdroid). If *only* the possibility to auto update changed from fdroids side, then nothing changes for element. As auto update was never in use.

**Comment by Bubu** [comment]
@linsui Could you clarify this a bit?

> Yes, we still don't support split apks so it's disabled in F-Droid build.

F-Droid wants to publish split apks, but doesn't support them? That sounds a bit confusing currently.

> I also wonder why it's not split before. But now the apk size is much larger than before so it makes more sense to split it. The build time is not a problem anyway given we never release the update in 1 hour.

It was considered too much maintenance overhead for negligible benefit. But it certainly makes sense to re-evaluate that from time-to-time. (And I'm no longer maintaining the build, so the tradeoff might be different for someone else as well).

You can look for example at the metadata file of old app version on how it was done: https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/im.vector.alpha.yml

(That also used a confusing release versioncode scheme, which makes different abi versions not appear together in this file).

**Comment by linsui** [comment]
> F-Droid wants to publish split apks, but doesn't support them? That sounds a bit confusing currently.

We want to publish apks per abi but we can only build 1 apk every time.

> You can look for example at the metadata file of old app version on how it was done: https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/im.vector.alpha.yml

It builds multiple apks but only pick one. I'll patch the code to build only one apk since we also need to build native code for maplibre.

**Comment by Bubu** [comment]
> It builds multiple apks but only pick one.

Yes. At least at that point in time building one vs all Abi Versions of the APK took exactly the same amount of time.

**Comment by licaon-kter** [comment]
F-Droid users are confused about the size of the APK since F-Droid serves them one at ~100Mb when here its just ~50Mb.

@bmarty why is F-Droid limited and not able to split per ABI?
