### ISSUE TITLE
ANR on session start when sending client info is enabled 

### ISSUE THREAD

**Issue by mnaturel** [vector-im/element-android#7604]
### Steps to reproduce

When client info recording is enabled (see Settings -> Labs) and when there is a version update, the app may encounter ANR on session start.

This is due to the fact `ConfigureAndStartSessionUseCase` is declared as a suspend method. To avoid that, the use case implementation should be changed a little.

#### What did you expect?
No ANR.

#### What happened instead?
ANR when updating the app version on the start of the session and so when the application starts.

### Will you send logs?

No

### Are you willing to provide a PR?

Yes

**Comment by jmartinesp** [comment]
This is probably the same as https://github.com/vector-im/element-android/issues/7557.

**Comment by mnaturel** [comment]
> This is probably the same as #7557.

Perhaps it is related for some users but I think there may be different causes for other users. The `suspend` method was introduced in the version 1.5.4. The ANR should only be visible for next updates and only when the labs setting to send client info have been enabled manually (it is disabled by default).
