### ISSUE TITLE
How to change package name? (im.vactor.app)

### ISSUE THREAD

**Issue by nishitpatel7371** [vector-im/element-android#7631]
I want to change package name of app

**Comment by DoM1niC** [comment]
build.gradle in vector-app https://github.com/vector-im/element-android/blob/ae996ae197b3f55b59b08bbda575db9d5d7be465/vector-app/build.gradle#L136

**Comment by manyjuice** [comment]
> build.gradle in vector-app
> 
> https://github.com/vector-im/element-android/blob/ae996ae197b3f55b59b08bbda575db9d5d7be465/vector-app/build.gradle#L136

Could you please clarify if the regular project folders refactoring (renaming) is also needed here? After changing just the build.graddle it doesnt work I'm confused if both vector, bector-app etc threads should be renamed this way, or only a single thread, or the whole project entries.

All common ways to rename + the one mentioned here didn't help, so I'm sure that I'm doing somthing wrong.

**Comment by yostyle** [comment]
> > build.gradle in vector-app
> > https://github.com/vector-im/element-android/blob/ae996ae197b3f55b59b08bbda575db9d5d7be465/vector-app/build.gradle#L136
> 
> Could you please clarify if the regular project folders refactoring (renaming) is also needed here? After changing just the build.graddle it doesnt work I'm confused if both vector, bector-app etc threads should be renamed this way, or only a single thread, or the whole project entries.
> 
> All common ways to rename + the one mentioned here didn't help, so I'm sure that I'm doing somthing wrong.

If you want to rename the app package name you don't need to refactor the package name in project folders. It just necessary to [change the `applicationId`](https://developer.android.com/studio/build/configure-app-module#set-application-id) value in [build.gradle](https://github.com/vector-im/element-android/blob/main/vector-app/build.gradle#L127). 
To rename the app you have to change `app_name` string value in [build.gradle](https://github.com/vector-im/element-android/blob/main/vector-app/build.gradle#L240)
