### ISSUE TITLE
Left rooms are still displayed in breadcrumbs

### ISSUE THREAD

**Issue by bmarty** [vector-im/element-android#766]

**Comment by BillCarsonFr** [comment]
See https://github.com/vector-im/riot-web/issues/11644

**Comment by bmarty** [comment]
So it's a feature, because you can eventually re-join the left room :)

**Comment by steef435** [comment]
Currently, the breadcrumb items of left rooms also get a green "new notifications" bar. Even though a design decision has to be made on whether they should stick or not after leaving the room, could those highlights be removed in any case?

**Comment by bmarty** [comment]
Fixed in #1446
