### ISSUE TITLE
Notifications disappear on the lock screen

### ISSUE THREAD

**Issue by DCDevilschild** [vector-im/element-android#7701]
### Steps to reproduce

I start a chat. I stay in the chat window and lock the phone. The other person writes to me and a notification appears on the lock screen and disappears again.
The other person looks as if I have read the text.
When I leave the chat with the person and go to the overall view of all chats then the notification comes on the lock screen and stays. The text is also displayed to the other person as not read.

#### What did you expect?
The notification remains even when the chat window is open on the lock screen.

#### What happened instead?
Notification disappears from the lock screen.

### Your phone model

Google Pixel 6a

### Operating system version

Android 13

### Application version and app store

Element Version 1.5.8, OLM Version 3.2.12, Google PlayStore

### Homeserver

Matrix EMS Homeserver / Synapse 1.71.0 / Python 3.19.15

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by th0mcat** [comment]
Can confirm the same issue, Pixel 7 Pro, happening since the 1.5.10 update.  Not happening for every chat, but when it does happen my wife says it immediately marks her messages as read by me.

**Comment by bmarty** [comment]
Dup of https://github.com/vector-im/element-android/issues/7643
