### ISSUE TITLE
Android App does not work with https://github.com/matrix-org/prosody-mod-auth-matrix-user-verification

### ISSUE THREAD

**Issue by Takalele** [vector-im/element-android#7758]
### Steps to reproduce

1. Install a Jitis Meet instance with matrix login .well-known etc
https://github.com/matrix-org/prosody-mod-auth-matrix-user-verification https://github.com/matrix-org/matrix-user-verification-service
2. Create a Group Video Call inside of Element
3. Join the Call

#### What did you expect?

No Login Prompt because of the openidtoken-jwt. see 
![](https://raw.githubusercontent.com/matrix-org/prosody-mod-auth-matrix-user-verification/master/widget_load.png)

#### What happened instead?
Login Prompt - because its calling /config.js?room=efuvmr3mkjlhast2knzhmv2xlj2eo5z2nvqxi4tjpaxguylnoaxgs3q from the jiti-meet-web Instance

Element-Desktop, Elements-Web and Elements-IOS are working fine as expected.

### Your phone model

Samsung Note 9, Huawei P20, Acer T04

### Operating system version

Android 10, Android 10, Android 6

### Application version and app store

latest from Play Store

### Homeserver

Synapse:latest from dockerhub

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by petrutmanaila** [comment]
I have the exact same issue, did you manage to find a solution?

**Comment by Takalele** [comment]
@petrutmanaila
unfortunately not.
