### ISSUE TITLE
Message input field obscured when using Japanese keyboard

### ISSUE THREAD

**Issue by cyphar** [vector-im/element-android#7764]
### Steps to reproduce

1. Try to type in any room with a Japanese keyboard (I use gboard).
2. Note that the IME suggestions overlap the message input field.
3. If you are not entering text (and there are no IME suggestions) then the message input field is visible.

This broke in the previous update (1.5.10) and is still present in 1.5.11. I suspect the issue is that with GBoard, the keyboard gets taller when you start typing, but the input field is not being moved to accommodate it. I don't have the rich text editor enabled.

I suspect this issue also happens with Chinese keyboards (since they probably also use two rows for IME suggestions), but I don't speak Chinese so I can't test whether that is the case.

|No IME Suggestions|With IME Suggestions|
|:--:|:--:|
|![Screenshot_20221211-121910](https://user-images.githubusercontent.com/2888411/206882011-936eac63-a14e-4f12-96f4-ae2d06fe8aed.png)|![Screenshot_20221211-121926](https://user-images.githubusercontent.com/2888411/206882026-2011fe10-4317-4727-8bde-a3f6490f62cb.png)|

#### What did you expect?

The input field should move up if the keyboard becomes "taller".

#### What happened instead?

The input field is not visible.

### Your phone model

Pixel 4a

### Operating system version

Android 12

### Application version and app store

1.5.11 [40105110] (F-40bfffae), olm 3.2.12

### Homeserver

Synapse 1.72.0

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by razaar** [comment]
This is not only a problem with japanese input. Gboard's integrated emoji bar (and stickers) is rendered on top of the input field and the send button (see attached screenshots) aswell. 

(Android 12, Gboard 12.4.05 , Element 1.5.11)
<table>
<td>

![Screenshot_20221219_161431_Element](https://user-images.githubusercontent.com/53236951/208459737-3026b545-b2f1-49ae-93eb-90e2e34007e9.jpg)

</td><td>

![Screenshot_20221219_161443_Element](https://user-images.githubusercontent.com/53236951/208459749-8144bb4d-dd97-4a53-8092-dc7f059f9e9e.jpg)

</td><td>

![Screenshot_20221219_161529_Element](https://user-images.githubusercontent.com/53236951/208459758-15732ece-39df-449f-9bff-e7222d54f12d.jpg)

</td>
</table>

**Comment by tateisu** [comment]
it's also happen with S-Shoin IME (Sharp devices).

**Comment by razaar** [comment]
This seems to be fixed with the latest version (tested on 1.5.18).

**Comment by tateisu** [comment]
fixed!
I tried vector-gplay-arm64-v8a-release-signed.apk  on https://github.com/vector-im/element-android/releases/tag/v1.5.20 .

**Comment by cyphar** [comment]
Yeah, this is fixed in the latest update. Thanks!
