### ISSUE TITLE
Rich Text Editor: Cannot select text in certain cases.

### ISSUE THREAD

**Issue by YamatoRyou** [vector-im/element-android#7801]
### Steps to reproduce

1. Enable rich text editor in "Labs";
2. Go back to a certain room, type some text;
3. Click the "+" button, disable "Text formatting";

#### What did you expect?
n/a

#### What happened instead?
Unable to select text via "long press" or "double click" unless "Text formatting" is re-enabled.
If "Text formatting" is disabled while no text is being entered, the input box has difficulty accepting focus.

### Your phone model

Nokia 6.1 (TA-1054)

### Operating system version

Android 8.1

### Application version and app store

Element 1.5.12 (Google play)

### Homeserver

Synapse 1.73.0

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by onurays** [comment]
Here are some logcat logs:

```
Attempted to finish an input event but the input event receiver has already been disposed.
requestLayout() improperly called by android.widget.FrameLayout{39a199 VFE...C.. ......ID 0,2401-1220,2712 #7f0a01b7 app:id/composerContainer} during layout: running second layout pass
```
