### ISSUE TITLE
“Mark message as read” emits new notification

### ISSUE THREAD

**Issue by fbruetting** [vector-im/element-android#782]
v0.10.0

When I mark a message as read in the notification drawer of my OnePlus Android 9 device, the following notification, that I have “one unread message”, appears right away:

![Screenshot_20191218-230953__01](https://user-images.githubusercontent.com/10520767/71127783-fe8e6f00-21eb-11ea-8fef-cee6d7e8e7c7.jpg)

**Comment by steef435** [comment]
See also #348 (I still experience it as well).

**Comment by lub** [comment]
I guess this should be fixed by #1143 ?

**Comment by MatMaul** [comment]
It should indeed :)

**Comment by fbruetting** [comment]
Let's see hopefully later today. 😜

**Comment by onurays** [comment]
Cannot reproduce anymore. Fixed by #1143.
