### ISSUE TITLE
Ringing wouldn't stop when received missed call from iOS

### ISSUE THREAD

**Issue by zh-hl** [vector-im/element-android#7837]
### Steps to reproduce

**Element iOS to Element Android:**
1. Start voice calling from Element iOS to Element Android (different account)
2. Don't answer
3. iOS will stop the call after 60 secs, and goes back to home screen
4. Android will still ringing forever

===

And there's similar issue
**Element Android to Element Android**
1. Start voice calling from Element Android to Element Android
2. Don't answer, turn off internet
3. Caller phone will stop after 60 secs
4. Receiver phone will keep ringing indefinitely

#### What did you expect?
When receiving incoming call, ringing suppose to stop after 60 secs.
No matter I answered or not.
No matter what platform the call was coming from.
No matter I have internet or not.

#### What happened instead?
It keeps ringing.

#### Why do you think that happened?
Element Android only stops ringing when it receives event `m.call.hangup`.

#### What's the possible solution?
It supposed to have internal timer (the same mechanism as making Outgoing call which uses `INVITE_TIMEOUT`) to timeout the ringing.

### Your phone model

Samsung S20 FE

### Operating system version

Android 10, 11, 12

### Application version and app store

All version 1.5.11

### Homeserver

Any

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by krassle** [comment]
I'm experiencing the same issue. Here is my observation in addition to the cases @zh-hl described.

It really comes down to the following 2 cases: 

**(1)** If Element-Android (the receiver app) **is running in background**, then it rings _indefinitely_, no matter if 1) the caller stops ringing, OR 2) the call times out after X seconds, OR 3) the call is answered by me on another device(e.g. Element-Web).

**(2)** If Element-Android (the receiver app) **is running in foreground**,   then it stops ringing _immediately_ after 1) the caller stops ringing, OR 2) the call times out after X seconds, OR 3) the call is answered by me on another device(e.g. Element-Web).

So, the only difference appears to be how the call is handled in foreground versus background! I've also tested with locked and unlocked screen, but it did not make any difference.

**Comment by RinCat** [comment]
I'm experiencing the same issue for at least a few months. Incoming call ringing all my phones indefinitely until I decline them one by one.

**Comment by systemoperator** [comment]
I have the same problem. It's extremely annoying. If I'm not in the room or out of the flat, my Android smartphone rings/vibrates forever until the battery is empty, even though the caller hug up early. There is no workaround. :disappointed:

**Comment by adrfantini** [comment]
Can confirm the same.
If I reply to a call on the desktop app, the app on the phone will continue ringing indefinitely until I decline the call from there.

**Comment by bmarty** [comment]
Closed in favor of https://github.com/vector-im/element-android/issues/4066
