### ISSUE TITLE
Cannot connect to Jitpack

### ISSUE THREAD

**Issue by mfshiu** [vector-im/element-android#7839]
### Steps to reproduce

When I build the element android project, it was failed.

### Outcome

I've got one of the errors:
`Could not HEAD 'https://jitpack.io/com/github/hyuwah/DraggableView/1.0.0/DraggableView-1.0.0.aar'. Received status code 521 from server: `

**Comment by Florian14** [comment]
I close the issue as it looks like a temporary server issue, @mfshiu feel free to reopen it if you're still blocked.
