### ISSUE TITLE
I cant login from FtueAuthCombinedLoginFragment!

### ISSUE THREAD

**Issue by sealiasheq** [vector-im/element-android#7846]
### Steps to reproduce

I am changing this line `true -> FtueAuthSplashCarouselFragment::class.java` to `true -> FtueAuthCombinedLoginFragment::class.java` in `FtueAuthVariant class` but when I am using from app get me bellow error:

Invalid username or password

But I login from `FtueAuthSplashCarouselFragment` good and don't have any problem!

What can I do?

### Your phone model

Samsung S6

### Operating system version

Android Version 7.0

### Will you send logs?

Yes

### Are you willing to provide a PR?

Yes

**Comment by Florian14** [comment]
Hi @sealiasheq, you're changing the onboarding flow by opening a Fragment which is not expected at this step. The onboarding flow is very sensitive. Do not hesitate to ask for dev support in the [Element-Android room](https://matrix.to/#/#element-android:matrix.org)
