### ISSUE TITLE
[SDK] Display "left" rooms with messages 

### ISSUE THREAD

**Issue by ivan2311** [vector-im/element-android#7878]
### Description

Hello!

I would like to continue display rooms that user left, and once room screen is opened I would like to display all messages that were in the room while user was still there.

To get data needed to display list of rooms, I use this lines of code:
```
session.roomService().getRoomSummariesLive(
            queryParams = roomSummaryQueryParams {
                this.memberships = listOf(Membership.JOIN, Membership.INVITE, Membership.LEAVE)
            })
```
But, it doesn't return most of the needed data for left rooms. E.g. instead of room name, I just receive room id. Also, don't receive any data about participants, room image etc. Is my code incorrect? Am I missing some key step?

Also, to retrieve room messages here is used code:
```
        val timelineSettings = TimelineSettings(
            initialSize = 30
        )
        val timeline = getSession()
            ?.roomService()?.getRoom(roomId)
            ?.timelineService()
            ?.createTimeline(null, timelineSettings)

        val listener = object : Timeline.Listener {
            override fun onTimelineUpdated(snapshot: List<TimelineEvent>) {
                // snapshot is always empty for left rooms, and everything is ok for joined rooms
            }
        }

        if (timeline != null) {
            timeline.addListener(listener)
            timeline.start()
        }
```
Again, am I missing something when fetching left room messages? Is that even possible using Matrix Android SDK?

Thanks in advance!

**Comment by Florian14** [comment]
Hi @ivan2311, this is not the best place to ask for dev support. Do not hesitate to ask the community directly in the [Element Android Matrix room](https://matrix.to/#/#element-android:matrix.org)
