### ISSUE TITLE
Handle a connexion issue when we try to start a new voice broadcast

### ISSUE THREAD

**Issue by giomfo** [vector-im/element-android#7894]
### Your use case

When the first state event created to start a voice broadcast could not be sent (network issue, server unreachable ...), we display a dialog with the following:

Title: Connection error 

Body: Unfortunately we’re unable to start a recording right now. Please try again later.

Action: Ok

OnClick OK → Dismiss the modal

### Are you willing to provide a PR?

Yes

**Comment by Florian14** [comment]
We already display this error if there is no network:

<img width="537" alt="image" src="https://user-images.githubusercontent.com/11990514/213656024-03875a99-eb21-46d4-8578-0a47cc486366.png">

**Comment by giomfo** [comment]
Already handled
