### ISSUE TITLE
Read indicator shows up with multiple icons of the same person

### ISSUE THREAD

**Issue by KeenMaron** [vector-im/element-android#7910]
Since a few weeks element shows up with the following bug:
![image](https://user-images.githubusercontent.com/52194699/211191630-8351fc8e-0c56-4108-abf0-16b01ebffd63.png)

Sometimes you can see the icon of the user multiple times, that he / she has read the messages. Few months ago i never have seen this problem.

Any ideas how to slove this? and what does it cause?

**Comment by benedikt-bartscher** [comment]
same here!

**Comment by macmoritz** [comment]
Got a similar issue.
One user in a private chat does have two read indicators at different messages.
Appeared in an update a few weeks ago.

**Comment by RayBB** [comment]
I think this is a duplicate of https://github.com/vector-im/element-android/issues/7882

**Comment by jmartinesp** [comment]
As mentioned above, it seems like it's a duplicate of an existing issue, so I'm closing it so we can keep the discussion there.
