### ISSUE TITLE
Where do I export the logs for personal viewing/debugging?

### ISSUE THREAD

**Issue by mozzieongit** [vector-im/element-android#7933]
Hi,
I'm managing a homeserver and my clients have some problems which I would like to debug. But how do they (or myself) send me their element android logs? RageShake only sends the bug report to you, I guess.

**Comment by bmarty** [comment]
> RageShake only sends the bug report to you, I guess.

Yes. To see the log, you can build a debug version of the app with Android Studio, and you will get the log from there.

You can also rageshake by adding `#7933` to the bug description so that we could share some log here if it helps.

**Comment by mozzieongit** [comment]
Thanks, that would help. Is there any identifying information in the rageshakes that would deem it reasonable to send them privately?

**Comment by bmarty** [comment]
Yes, `userId`, `roomIds` can be present in the log. But the logs will not contain any private data such as messages content, keys or password.

**Comment by mozzieongit** [comment]
Hmm.. could you upload them to https://upload.disroot.org/ with a password that I'll add to the rageshake description and send the links here then? (My friend and I will then send the two rageshakes in about 2 hours: around 19:00 CET)

Thank you very much for your help.

**Comment by mozzieongit** [comment]
Sorry, my friend is late ^^

**Comment by mozzieongit** [comment]
Finally done with the second one.

**Comment by Florian14** [comment]
Hi @mozzieongit, sorry for the delay, I just uploaded the logs as requested, here are the links with the provided pwd:
[first](https://upload.disroot.org/r/9RU5RruH#xwCFFmvRkUweEogqnbZKcYpe/mb+8SgcsabCF7GEWKg=) / [second](https://upload.disroot.org/r/v4d7e9ez#3H/m2GGMq4yXL6AMJ3fr61m1vKQNKIoIsXK6M8WcwoQ=)

**Comment by mozzieongit** [comment]
Hi, no worries. Thank you very much.
