### ISSUE TITLE
Implement an Account Switcher for users with multiple accounts on Element

### ISSUE THREAD

**Issue by goliv04053** [vector-im/element-android#7935]
#### What would you like to do?
Have other accounts on the same app where I can switch without removing an account and entering in other
#### Why would you like to do it?
Make the process of accessing other accounts simplified.
#### How would you like to achieve it?
Like Discord, you login in your account and you can add other accounts to switch. How it's already logged, you can switch to other account.

### Are you willing to provide a PR?

No

**Comment by bmarty** [comment]
Dup of #26
