### ISSUE TITLE
Threads not available when offline

### ISSUE THREAD

**Issue by toby63** [vector-im/element-android#7952]
### Steps to reproduce

1. Sometimes I don't have internet (testcase: disable all internet connections)
2. I click on an existing thread that I have accessed before (so the content was also loaded at least once).
3. A strange green dot appears and flickers a bit.

#### What did you expect?

That the content in the thread would load, even though I am offline, because all other content seems to be stored locally and is accessable.

#### What happened instead?

Green dot and then no content (blank page).

### Operating system version

Android 11

### Application version and app store

Element version: 1.5.18 (F-Droid); OLM: 3.2.12

### Homeserver

Synapse v1.74.0

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by bmarty** [comment]
There is a no network error dialog now (1.5.22)

**Comment by toby63** [comment]
> There is a no network error dialog now (1.5.22)

Sry but do I understand it correctly, that Element does now only show an error message, instead of saving the content locally so it can be accessed later?

**Comment by toby63** [comment]
I just tried version 1.5.22 and the problems still exists, no dialog is shown etc.

@bmarty So reopen please.
