### ISSUE TITLE
Inline code formatted messages display with extra line breaks

### ISSUE THREAD

**Issue by jonnyandrew** [vector-im/element-android#7975]
### Steps to reproduce

1. Send the following formatted message:
````markdown
```
Code block
```
Followed by `inline code`
````

#### What did you expect?
The message is displayed correctly in the timeline e.g.
> ```
> Code block
> ```
> Followed by `inline code`

#### What happened instead?
The message is not displayed correctly in the timeline. Note the extra new line:

> ```
> Code block
> ```
> Followed by 
> `inline code`

Here's a comparison of how the same message looks in Element Web vs Element Android:

| Element Web | Element Android |
|-|-|
| <img src="https://user-images.githubusercontent.com/4940864/213407992-0ee7bdd1-fd1c-4764-bd72-a0d97191e2aa.png" width="1000px" /> | <img src="https://user-images.githubusercontent.com/4940864/213407802-5054c58f-9bef-490c-b834-cc1fd9d38e29.png" width="1000px" /> |

### Your phone model

Google Pixel 6a

### Operating system version

Android 13

### Application version and app store

1.5.20

### Homeserver

matrix.org

### Will you send logs?

No

### Are you willing to provide a PR?

Yes

**Comment by jonnyandrew** [comment]
I believe this is a bug with the underlying HTML parser from Markwon (see https://github.com/noties/Markwon/issues/423)

**Comment by jmartinesp** [comment]
On my device, it rendered fine for a second or so, then was re-rendered with the extra new lines. Maybe we're post-processing the contents at some point?
