### ISSUE TITLE
The app stops recieving new messages until I restart it

### ISSUE THREAD

**Issue by gianmarcogg03** [vector-im/element-android#8010]
### Steps to reproduce

1. I'm inside the app's main screen or in a chat
2. New messages don't come but I can still send messages
3. When I close and reopen the app the new messages appear

#### What did you expect?
The new messages should be already there.

#### What happened instead?
The new messages didn't appear until I restarted the app.

### Your phone model

Google Pixel 6a

### Operating system version

GrapheneOS (Android 13)

### Application version and app store

Element 1.5.18 from F-Droid

### Homeserver

gianmarco.gg (private) running Synapse 1.75.0

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by bmarty** [comment]
Thanks for reporting. I can repro when the app is resumed by the system after a crash, or after the system has decided to kill the process for any reason.

This is a demo of the issue:

![StoppedSyncBefore](https://user-images.githubusercontent.com/3940906/215092226-78a2a012-0d9c-4ef9-b871-c387662f22c3.gif)

Working on a fix / workaround.
