### ISSUE TITLE
Glitched image view resetting scroll position

### ISSUE THREAD

**Issue by thedidek** [vector-im/element-android#8021]
### Steps to reproduce

1. Where are you starting? What can you see?
2. What do you click?
3. More steps…

#### What did you expect?
Clicking in image on timeline should zoom in it smoothly and when going back scroll should be on the same position as before.

#### What happened instead?
While clicking on a photo in timeline, animation is glitching and when going back, scroll position is on the bottom.

### Your phone model

OnePlus 8T

### Operating system version

Android 13 (LineageOS 20)

### Application version and app store

Element 1.5.20 (also Element 1.5.18)

### Homeserver

Synapse

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by ganfra** [comment]
It happens as soon as the timeline goes to background.

**Comment by bagvand** [comment]
Hi,
This problem occurred after the following change
https://github.com/vector-im/element-android/pull/7734

**Comment by bmarty** [comment]
Yes, fixed by #8152, available in release 1.5.26 (2023-02-22)
