### ISSUE TITLE
Maunium sticker picker loads indefinitely on new update

### ISSUE THREAD

**Issue by catfromplan9** [vector-im/element-android#8026]
### Steps to reproduce

1. Where are you starting? What can you see?
Chat view
2. What do you click?
Sticker button
3. More steps…
N/A

#### What did you expect?
Sticker picker view loads and i can pick a sticker to send
#### What happened instead?
Indefinite loading of the sticker picker view. Works fine after downgrading to 1.5.11. Also, unrelated but I don't want to make another PR for this and it's technically not a bug: can you revert the image viewer to the pre-1.5.18 behaviour? What I mean is that when I open an image if I slide down on the image a little I used to be able to see the chat window and messages behind it but now it's blank and this means that whenever I view a video or photo file if I'm scrolled up in the chat after exiting the photo/video I'll immediately be jumped to the bottom and lose my position in the chat

### Your phone model

Pixel 5a

### Operating system version

Android 13.0

### Application version and app store

Element version 1.5.20, F-Droid

### Homeserver

Synapse 1.75.0

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by Trendyne** [comment]
Also happening to me and my friend on the latest FDroid version (1.5.20) and Synapse 1.75.0
* Xiaomi Redmi Note 10 Pro (sweet) Android 13
* Samsung A52 (LineageOS) Android 12

Restarting the app and trying to access stickers shows no entry in the NGINX log

**Comment by catfromplan9** [comment]
> Also happening to me and my friend on the latest FDroid version (1.5.20) and Synapse 1.75.0
> 
>     * Xiaomi Redmi Note 10 Pro (sweet) Android 13
> 
>     * Samsung A52 (LineageOS) Android 12
> 
> 
> Restarting the app and trying to access stickers shows no entry in the NGINX log

I downgraded the app and it works fine. Definitely a client-sided issue. Contributors could check the commits made between versions on related code to narrow down what broke it

**Comment by ramshackle-heather** [comment]
This issue is occurring for us, as well, on a Pixel 5 running Android 13 and the latest F-Droid release of Element (1.5.22). Maunium sticker packs still work fine on our self-hosted web client (Element 1.11.15), but not on mobile.

**Comment by whaever** [comment]
Same here - On a Oneplus 8 Pro (Android 13) and a Xiaomi Redmi Note 8 Pro (Android 12), the problem persists after updating Element to the newest fdroid version (1.5.22).

**Comment by Destroyer** [comment]
Still broken on 1.5.25

**Comment by Destroyer** [comment]
Can we also mark this as regression?

**Comment by sebix** [comment]
It worked prior to the mentioned version, so it's likely a regression I think

**Comment by yostyle** [comment]
The problem appeared after this PR #7917 included in 1.5.20 release.

**Comment by TomicekRosic** [comment]
> The problem appeared after this PR #7917 included in 1.5.20 release.

Thank you!
