### ISSUE TITLE
video call bug

### ISSUE THREAD

**Issue by perfectlisir** [vector-im/element-android#8079]
### Steps to reproduce

Click on the video call, and after connecting, the receiving party cannot see the screen of the video calling user.
For example: user A clicks on a video call to user B, and B cannot see A's picture after answering the call

### Your phone model

xiaomi 12S

### Operating system version

Android 11.0

### Application version and app store

Element APP version 1.5.6 - version 1.5.22

### Homeserver

https://matrix.moc.network

**Comment by rajil** [comment]
Duplicate of [#7169](https://github.com/vector-im/element-android/issues/7619)
