### ISSUE TITLE
Element Android always jumps to the bottom of the timeline

### ISSUE THREAD

**Issue by timokoesters** [vector-im/element-android#8090]
It seems like it is a design decision for leaving a room and opening it back up (although maybe that should be reconsidered), but opening an image, a profile, threads, the room settings and so on should not reset the position in the timeline.

Reproduce:
- scroll up
- open image
- close image
- you are at the bottom of the timeline again

**Comment by rabio** [comment]
It is not directly related to opening links from the app. Any focus' change, including opening app switcher or turning screen off for a slightest moment, results in full scroll down in opened room.

I think that automatic reset of position on timeline is problematic in general (not only on focus change), as action done on user's behalf, that is not easily reversible nor directly requested by a user, is always risky.

Maybe the whole thing could be reconsidered in favor of showing a position indicator that double as fast scroll down action button?

Solution of this kind was implemented in Signal UI f.e. and it seems to work well, giving quick access to the bottom of message feed, without disturbing user reading flow.

This would not only solve this issue but also would provide more predictable user experience in general, by putting user in control.

**Comment by bagvand** [comment]
Hi,
This problem occurred after the following change
https://github.com/vector-im/element-android/pull/7734

**Comment by bmarty** [comment]
Rising the severity as it's been reported a lot and I agree that it's a pain when we encounter this issue.
