### ISSUE TITLE
Show own location in map views

### ISSUE THREAD

**Issue by Johennes** [vector-im/element-android#8110]

**Comment by jonnyandrew** [comment]
@kittykat @Johennes should this issue be part of issue triage?

**Comment by kittykat** [comment]
> @kittykat @Johennes should this issue be part of issue triage?

Yes, the appropriate thing would be to add the needs info label and ask Johannes to fill in the issue :)

**Comment by Johennes** [comment]
The info is in the issue that tracks this one (linked in the header)
