### ISSUE TITLE
Add store metadata (summary/description/screenshots/whatsnew) to the repo

### ISSUE THREAD

**Issue by Bubu** [vector-im/element-android#812]
Copied over from https://github.com/vector-im/riot-android/issues/2298

F-Droid has had a feature for quite a while that allows controlling the description, summary and screenshots from the upstream repo: https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/

This would also allow for having localized descriptions. And generally It will help for the description not becoming outdated as it lives right here instead of the F-Droid repo.

You can also add a what's new section for every release which prominently displays a changelog on the app page in F-Droid.

I think nobody quite got around to documenting it but it should look like this here: https://github.com/lexica/lexica/tree/master/metadata/android/en-US/changelogs

**Comment by kojid0** [comment]
Didn't work for v1.0.8 update... No changelog on F-Droid

**Comment by Bubu** [comment]
Yes it's in the wrong folder unfortunately. @bmarty the fix for this is still outstanding.
