### ISSUE TITLE
One way video when video calling between android 13 to android 13 device

### ISSUE THREAD

**Issue by rajil** [vector-im/element-android#8145]
### Steps to reproduce

1. Where are you starting? What can you see?

Video call from Android (v1.5.25, Android 13, Samsung S22 Ultra) to Android (v1.5.25, Android 13, Samsung S23 Ultra)

2. What do you click?
Pick up call

#### What did you expect?
Video and audio work
#### What happened instead?
Caller can see self video and callee video, however callee cannot see caller video (can see self video)

Audio works both ways (no issues)

### Your phone model

Samsung S23

### Operating system version

Android 13

### Application version and app store

Element 1.5.25

### Homeserver

Synapse 1.77.0

### Will you send logs?

Rageshake sent with #8145

### Are you willing to provide a PR?

No

**Comment by mnaturel** [comment]
Thanks @rajil for raising this issue, I am closing this one in favor of the already existing issue: #7619.
