### ISSUE TITLE
[Timeline]: Editing a reply from iOS breaks the "in reply to" rendering

### ISSUE THREAD

**Issue by mnaturel** [vector-im/element-android#8150]
### Steps to reproduce

From iOS client:
- Reply to a message
- Edit the reply

#### What did you expect?
We should see the edited reply still rendering as a "in reply to" message.

#### What happened instead?
After the reply message has been edited, the "in reply to" message is considered as a simple text message and the "in reply to" context is lost.

### Will you send logs?

No

### Are you willing to provide a PR?

Yes

**Comment by HarHarLinks** [comment]
while you could patch that, what really needs to be done is #3731 (on iOS too)
