### ISSUE TITLE
Formatting creates extra newlines

### ISSUE THREAD

**Issue by WIPocket** [vector-im/element-android#8179]
### Steps to reproduce

Send texts containing formatting
![Screenshot_20230226-121654_1](https://user-images.githubusercontent.com/18397681/221407574-12e9b73c-dd32-453a-be73-fd6b5f8f9cfc.png)

#### What did you expect?
Same functionality as old version of Element Android and other clients.
Element Desktop 1.11.23:
![image](https://user-images.githubusercontent.com/18397681/221407776-d492d40e-2f2b-4876-bee6-029bd151fae9.png)

#### What happened instead?
Most formatting options start a new line.

This seems to only be the case when it is the first formatted text in a paragraph:
![Screenshot_20230226-125116_1](https://user-images.githubusercontent.com/18397681/221408789-0337d02f-c2ef-413e-8660-1182acfdb501.png)
With the markdown:
```
one _two_ three

four _five_ six
```

### Your phone model

Google Pixel 7

### Operating system version

GrapheneOS stable / Android 13

### Application version and app store

Version 1.5.25 [40105250] (F-f74a885a), Matrix SDK Version 1.5.25 (f74a885a), olm version 3.2.12, from F-Droid

### Homeserver

Synapse 1.77.0

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by WIPocket** [comment]
I was not using the new rich text editor. Toggling "Enable rich text editor" or "Enable LaTeX mathematics" does not change the rendering of these messages.

It renders wrong regardless of what client I send the message from, be it this new version of Element Android, Element Desktop or gomuks.

The event source looks like this:
```json
{
  "room_id": "<redacted>",
  "type": "m.room.message",
  "content": {
    "msgtype": "m.text",
    "body": "this _is_ underscores",
    "format": "org.matrix.custom.html",
    "formatted_body": "this <em>is</em> underscores"
  }
}
```

**Comment by jonnyandrew** [comment]
It could be caused by vector-im/element-android#8011 which attempted to workaround the following, seemingly related issue:
- https://github.com/vector-im/element-android/issues/7975
- https://github.com/noties/Markwon/issues/423
