### ISSUE TITLE
Saving App-Unlocking pin code as hashed value

### ISSUE THREAD

**Issue by yncyrydybyl** [vector-im/element-android#8186]
### Steps to reproduce

The pin code, used for app-unlocking, is stored as clear text and can be extracted on rooted devices. 

#### What did you expect?
The existing stored pin codes should be migrated to their hashed values.
### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by bmarty** [comment]
Tested on Element Android 1.5.26, the PIN code is stored in the SharedPreference in encoded version:

<img width="528" alt="image" src="https://user-images.githubusercontent.com/3940906/222154234-7024dc11-5951-40b8-9149-4383c09382ef.png">

- which version of the app are you using?
- where is stored the clear PIN code?

**Comment by artkoenig** [comment]
On rooted devices the Keystore API could be used to retrieve key references, then they could be used to initialize the Cipher object and decrypt the PIN. This issue can be mitigated by storing the hash of the PIN and not the PIN itself.

**Comment by dklimpel** [comment]
> * store a boolean in the SharedPref to remember that the migration has occurred, to avoid migrate several times.

It might be useful to specify the algorithm of the hash value instead of a boolean? This way the hash value can be updated without a new field in the future.

**Comment by bmarty** [comment]
@dklimpel thanks for your input. We could also store a `Int` to eventually handle further migration (like some DBs are working, using a schema version, to properly handle migration). But let's keep it simple for now use use a Boolean.

**Comment by yostyle** [comment]
Here is the patch : https://matrix.to/#/!eXrqdXvGMNVxzdCMvI:matrix.org/$C7Ypzt0tiMND-uu_NkuKtoEv9j2YfDqiXFlWEEczcGE?via=matrix.org&via=element.io
