### ISSUE TITLE
Date description should not depend on the time

### ISSUE THREAD

**Issue by fbruetting** [vector-im/element-android#822]
As you see below, the uppermost reader has read that message about 21 hours ago, which seems to be why RiotX displays that date as “the day before yesterday” (German: “vorgestern”). The others have read that message more than 24 hours ago (but on the same day), and there RiotX displays the timestamp via an exact date.

Would be nice if the threshold could be raised from “24 hours ago” to “24 hours ago + that whole day”, then the timestamps would be unified for every day.

![Screenshot_20200108-191733](https://user-images.githubusercontent.com/10520767/72004842-8e07ca80-324c-11ea-8a75-d0e1f7ded9dd.jpg)

**Comment by bmarty** [comment]
I'm not sure to undertand the problem. Could you precise the current date and time of the screenshot please?

**Comment by fbruetting** [comment]
The screen shot is of the day before yesterday and all persons have read the message at the same day (which is why it would be good to unify the timestamp, because currently, it looks like the first person read the message on another day than everybody else).

**Comment by bmarty** [comment]
Ok, so the screenshot has been taken the 8th of January at 19:17.

I see the pb now.
I'll see what we can do to improve this.
