### ISSUE TITLE
Failed to resolve: com.vanniktech:ui causes the app Graddle Sync failure

### ISSUE THREAD

**Issue by manyjuice** [vector-im/element-android#8280]
### Steps to reproduce

1. Where are you starting? What can you see?

Trying to run Graddle to sync via Android Studio (Java 11 or Java 20), even without any modifications to the project

#### What did you expect?

Graddle Sync previously worked good. It stopped working occasionally without any changes made to the project after the last succesfull build

#### What happened instead?

Failed to resolve: com.vanniktech:ui:0.5.0 alwas causes the Sync/Build failure. I'm out of ideas why

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by 337077418** [comment]
Please Did you solve it, I have the same problem

* What went wrong:
Execution failed for task ':vector-app:mergeGplayDebugNativeLibs'.
> Could not resolve all files for configuration ':vector-app:gplayDebugRuntimeClasspath'.
   > Could not resolve com.vanniktech:ui:0.5.0.
     Required by:
         project :vector-app > project :vector > com.vanniktech:emoji-material:0.16.0-SNAPSHOT:20230325.154257-107 > com.vanniktech:emoji-material-android:0.16.0-SNAPSHOT:20230325.154257-107 > com.vanniktech:emoji:0.16.0-SNAPSHOT:20230325.154257-107 > com.vanniktech:emoji-android:0.16.0-SNAPSHOT:20230325.154257-107
      > Could not resolve com.vanniktech:ui:0.5.0.
         > Could not get resource 'https://oss.sonatype.org/content/repositories/snapshots/com/vanniktech/ui/0.5.0/ui-0.5.0.pom'.
            > Could not GET 'https://oss.sonatype.org/content/repositories/snapshots/com/vanniktech/ui/0.5.0/ui-0.5.0.pom'.
               > oss.sonatype.org:443 failed to respond

**Comment by Graphicscore** [comment]
This is due to the following libs being updated, and they probably removed the snapshot build element was currently using.
```
com.vanniktech:emoji-material
 com.vanniktech:emoji-google
```

As a hotfix revert https://github.com/vector-im/element-android/pull/6929/commits/a1f4ffbf172315a5906c59ab821ab907d5cc2135 from https://github.com/vector-im/element-android/pull/6929 and set the `vanniktechEmoji` to `0.16.0` in `dependencies.gradle`

**Comment by Florian14** [comment]
Fixed by #8281
