### ISSUE TITLE
Room icon does not use emoji if there is just one person in a room

### ISSUE THREAD

**Issue by fbruetting** [vector-im/element-android#830]
v0.12

Minor issue, but RiotX changes the room icon not to the emoji, before other people are invited. As soon as the first person is invited, the emoji immediately gets used as the room icon.

![Screenshot_20200110-192622__01](https://user-images.githubusercontent.com/10520767/72177027-22eefd00-33e0-11ea-9cca-c6b6eba2b8a5.jpg)

**Comment by bmarty** [comment]
I do not understand what you mean. Feel free to clarify and re-open if it is still an issue
