### ISSUE TITLE
App crashing on opening access protection settings

### ISSUE THREAD

**Issue by manyjuice** [vector-im/element-android#8317]
### Steps to reproduce

1. Where are you starting? What can you see?

Trying to enable a screen PIN lock in Element 1.5.30 (main). Before the update it was all good.
3. What do you click?
Protect access within the Security settings section

5. More steps…

When trying to enter this Protect Access section, the app instantly crashes. Restarting the app or trying a different Android device doesn't resolve the issue

#### What did you expect?

To see PIN settings

#### What happened instead?

The app crashes and then offers me to share a report, but I can't do it know, as don't have my Rageshake available yet

### Your phone model

Samsung S21FE

### Operating system version

Android 13

### Application version and app store

1.5.30-main, customized

### Will you send logs?

No

### Are you willing to provide a PR?

Yes

**Comment by 8restcoop8** [comment]
Same issue on S22, android 13, Google Play store version 1.5.30

**Comment by scottwallacesh** [comment]
I'm seeing this too.

**Comment by manyjuice** [comment]
I can confirm the issue appears with the Market Element version 1.5.30 on any device I try. There is no such issue in 1.5.28.
It's a very useful option (screen protection), so I hope the issue will be resolved in the next release or at least clarified.

**Comment by scottwallacesh** [comment]
This, combined with the bug that occasionally removes the biometric option, means I'm now stuck entering a PIN every time I open the app.

**Comment by Twi1ightSparkle** [comment]
I can also reproduce. See my linked rageshake for details.

**Comment by manyjuice** [comment]
I see the issue was already submitted to Triage, but it looks like it's not prior for now and not fixed in the latest release. 
It's not affecting v1.5.28 and older, looks like we will use them until the issue is fixed, as @scottwallacesh mentioned the problem also affects those who already has the PIN enabled before the update

**Comment by scottwallacesh** [comment]
Even after upgrading to v1.5.32, the problem persists.

**Comment by farline99** [comment]
Same here. Google Play version. LineageOS 19.1

**Comment by shadow-identity** [comment]
Same here. Have no pin, but crashing. Google Pixel 6, everything updated.

**Comment by scottwallacesh** [comment]
Fixed for me in v1.6.0.

**Comment by manyjuice** [comment]
Thanks for the update, @scottwallacesh
