### ISSUE TITLE
When I return to my phone desktop, I won't receive any messages unless I return to the app again

### ISSUE THREAD

**Issue by 337077418** [vector-im/element-android#8318]
### Steps to reproduce

When I return to my phone desktop, I won't receive any messages unless I return to the app again

### Your phone model

huawei P40  samsung S21  xiaomi10Pro

### Operating system version

android12   harmonyOS 3.0

### Application version and app store

https://github.com/vector-im/element-android/releases/download/v1.5.30/vector-gplay-arm64-v8a-release-signed.apk

### Homeserver

matrix.org

### Will you send logs?

Yes

### Are you willing to provide a PR?

Yes

**Comment by kittykat** [comment]
@337077418 Can you please check your OS settings to make sure that the app can run in the background?

**Comment by 337077418** [comment]
> @337077418您能否检查您的操作系统设置以确保该应用程序可以在后台运行？

Resolved, thank you
