### ISSUE TITLE
Incorrect room icon in direct chats

### ISSUE THREAD

**Issue by Sorunome** [vector-im/element-android#832]
If your direct chat used to have three users but now only has two, the chat only has that auto-generated icon. It should, instead, use the others persons avatar

**Comment by bmarty** [comment]
Thanks for reporting. I assume that on Riot-Web the room avatar is the expected one?

**Comment by Sorunome** [comment]
That is correct

**Comment by onurays** [comment]
Tested on v1.0.10 and couldn't reproduce anymore. Kicked one of 3 users and the room avatar changed as the other user's avatar.
