### ISSUE TITLE
Uses phone speaker if headphone without mic is inserted

### ISSUE THREAD

**Issue by aelmahmoudy** [vector-im/element-android#8329]
I am using a Redmi Note 7 (M1901M7G) Android 10 phone. When a headphone without mic is inserted, and I attempt to start a video call using Element, Element uses phone speaker instead of the headphone. I would expect that Element would output voice through the headphone, and receive input voice from phones mic, just as the phone app does.

**Comment by kittykat** [comment]
Please provide the information requested in the [new bug template](https://github.com/vector-im/element-android/issues/new?assignees=&labels=T-Defect&template=bug.yml), we need some more details to look into your issue
