### ISSUE TITLE
Can not uninstall

### ISSUE THREAD

**Issue by Halilb1978** [vector-im/element-android#8336]
### Steps to reproduce

I can not uninstall the latest Element app( fdroid) from main profile also from secure folder. I could uninstall app in main profile via adb. But adb does not works in secure folder,and i could not uninstall the second one.

### Your phone model

Samsung galaxy a505f

### Operating system version

Android 11 one ui 3.1

### Application version and app store

Element Fdroid 1.5.30

### Will you send logs?

Yes

### Are you willing to provide a PR?

Yes

**Comment by yostyle** [comment]
@Halilb1978 Installing and uninstalling the app is handled by your device's operating system. We have no control over this.

If you use samsung secure folder feature maybe you could test this [how to](https://www.techbone.net/samsung/user-manual/remove-apps-from-secure-folder).
It would be possible to use adb too according [samsung forum](https://r2.community.samsung.com/t5/Tech-Talk/How-to-uninstall-app-from-secure-folder/td-p/4553554).

**Comment by Halilb1978** [comment]
All other apps can be uninstalled normally or via adb in main profile ( only vigilante app has this bug for everybody ).  No way to use adb in secure folder. I had to do factory reset for Element.
