### ISSUE TITLE
Got asked twice about verification

### ISSUE THREAD

**Issue by weeman1337** [vector-im/element-android#8353]
### Steps to reproduce

- Have the Android App open
- Sign in with Element Web to the same account
- Tap the verification banner on Android
- Verification starts, scan QR Code, finish verification

#### What did you expect?

Verification done

#### What happened instead?

Verification banner is displayed again

### Application version and app store

1.5.30

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by weeman1337** [comment]
Web Issue: https://github.com/vector-im/element-web/issues/25169

**Comment by BloodyIron** [comment]
Still happening on Android...

**Comment by BloodyIron** [comment]
When does this hit Google Play repos?
