### ISSUE TITLE
groups don't update

### ISSUE THREAD

**Issue by Sorunome** [vector-im/element-android#836]
If you join a new group via riot-web it doesn't show up in riot x. If you clear cache none show up anymore

**Comment by bmarty** [comment]
FTR, after a clear cache it works well on my account.

**Comment by Sorunome** [comment]
After quite some waiting they appeared (only noticed just now).....however only the old ones, not the new ones joined

**Comment by heyakyra** [comment]
Should this be marked as a duplicate of  #479 for simplicity?

**Comment by bmarty** [comment]
Group will be replaced by spaces very soon
