### ISSUE TITLE
Extract MatrixAndroidSdk

### ISSUE THREAD

**Issue by bmarty** [vector-im/element-android#85]
And move it in a new created repo in https://github.com/matrix-org

## Proposal

In order to simplify the management of the SDK repository, the idea is to keep managing the SDK code in [Element Android](https://github.com/vector-im/element-android) and regularly copy paste the SDK code from Element Android to the new SDK repository after each release of Element Android.

Opening Issues and PRs will not be possible on the SDK repository, it will have to be done on Element Android

Creating a dedicated repository will allow third party applications to add gradle dependency to the SDK.

## Repository name

We need a repo name.
Legacy name is `matrix-android-sdk`
Proposal: `matrix-android-sdk2`

Legacy way to add dependency to the SDK:
`implementation 'com.github.matrix-org:matrix-android-sdk:vA.B.C'`
So it will become:
`implementation 'com.github.matrix-org:matrix-android-sdk2:vA.B.C'`

## Package name

Also the package name could be updated in Element-Android before created the repository for the SDK.
Legacy package name is: `org.matrix.androidsdk`
Current package name of the SDK in Element Android is: `im.vector.matrix.android`
Proposal: `org.matrix.android.sdk` (so just add a point). Not sure that using `v2` here makes sense, because apps will not have dependency on the both SDKs

## Serialized objects

Serialized objects have to be robust following the package name change

## Copyright

SDK source files should have the Matrix copyright.
This line will be added in each file:
> Copyright 2020 The Matrix.org Foundation C.I.C.

**Comment by ara4n** [comment]
Would it make sense to call it matrix-kotlin-sdk rather than the clunky matrix-android-sdk-v2?  And then you can have org.matrix.kotlinsdk or something?

**Comment by ara4n** [comment]
Also, why would you not depend on it like a normal library (and so dogfood it like other app developers), rather than copy-pasting it from the main repo, which will lose git history?

**Comment by bmarty** [comment]
> Would it make sense to call it matrix-kotlin-sdk rather than the clunky matrix-android-sdk-v2? And then you can have org.matrix.kotlinsdk or something?

Kotlin is the language and not the platform. The SDK is only compatible with the Android plateform, as it depends on the Android SDK

> Also, why would you not depend on it like a normal library (and so dogfood it like other app developers), rather than copy-pasting it from the main repo, which will lose git history?

Several reasons:
- it's painful to develop new features across multiple GH repositories. Also the CI of Element Android get confused if Element Android depend on SDK changes that has not yet been released.
- the git history of the SDK part is already in the project Element Android
- we just want to provide a quick way for third party apps to set up a dependency on the Android Matrix SDK
- (for the moment) we want to avoid that a PR on Android Matrix SDK breaks compatibility with Element Android code

In the future, we may remove the Matrix SDK code from Element Android and get it through a regular gradle dependency.

**Comment by bmarty** [comment]
Also I've changed the proposal for GH repo name from `matrix-android-sdk-v2` to `matrix-android-sdk2` to avoid several `v` when adding the dependency.

**Comment by violoncelloCH** [comment]
just as a suggestion:
- regarding extraction of the SDK and git history: it's possible to extract specific subdirectories into their own git repo... I don't know command by heart because I've only used it once, but you'll find it if you search for it
- maybe git submodules could get around the ci build concerns, as you could easily include a specific commit of the dependency repo into a new feature branch
also git submodules seem to work for f-droid builds while they don't accept custom gradle dependencies

**Comment by BillCarsonFr** [comment]
As discussed and for the record, the package renaming will break deserialization of some classes (InboundGroupSession..).
Not sure how to mitigate this

**Comment by bmarty** [comment]
> As discussed and for the record, the package renaming will break deserialization of some classes (InboundGroupSession..).
> Not sure how to mitigate this

Tested ok with this commit: https://github.com/vector-im/element-android/pull/1911/commits/8f1adf6316a429689a5f11c0714690b162f6ff22

**Comment by ara4n** [comment]
one thought: how about matrix-androidx-sdk?

**Comment by bmarty** [comment]
Package has been renamed and https://github.com/matrix-org/matrix-android-sdk2/ has been created
