### ISSUE TITLE
Update of SAS strings is broken

### ISSUE THREAD

**Issue by bmarty** [vector-im/element-android#8525]
Reasons:
- [x] https://github.com/matrix-org/matrix-spec/issues/1372
- [x] `master` branch has been renamed to `main`, so the URL [in our script](https://github.com/vector-im/element-android/blob/develop/tools/import_sas_strings.py#L38) main be broken.

Once this is all fixed, we should get PR with the new or updated translations.

**Comment by Florian14** [comment]
Let's wait for the translations update PR before closing this issue

**Comment by bmarty** [comment]
(I have triggered the job: https://github.com/vector-im/element-android/actions/runs/5948269766)

**Comment by bmarty** [comment]
It works! https://github.com/vector-im/element-android/pull/8626 Thanks @turt2live !
