### ISSUE TITLE
Call doesn't end on the receiver

### ISSUE THREAD

**Issue by zh-hl** [vector-im/element-android#8531]
_Edit: fixing typos and rephrasing description_
### Steps to reproduce

Needs 2 devices, 1 for calling. The other is for receiving.

**Receiver**:
1. Clear task (make sure Element is not running on the background).
2. Turn off/lock the screen.
3. Don't do anything, let the screen wake up by itself from call notification.
4. Don't pick up the call.

**Caller**:
1. Start calling the other device
2. After ringing, hangup (end the call).

====

Another alternative:
Receiver may pickup the call on step 4, but the call should be ended (hangup) by the caller.

#### What did you expect?
- The ringing on the receiver should stop.
- or If the call was picked up, the call should also stop by itself.

#### What happened instead?
- It keeps ringing forever.
- or if the call was picked up, when the caller hang up, the receiver call status become _"call connecting..."_ forever.

### Your phone model

Samsung S20 FE

### Operating system version

Android 11

### Application version and app store

Google Play - Element v1.5.32

### Homeserver

matrix.org

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by bmarty** [comment]
Closed in favor of #4066
