### ISSUE TITLE
google captcha? 

### ISSUE THREAD

**Issue by A-7666** [vector-im/element-android#8586]
### Steps to reproduce

1. Try to create a new account

#### What did you expect?
No captcha. No malware/spyware/harmful services used.

I'm shocked. Really, are you serious?...
A secure and private messaging software using a malware/spyware service?
This is a very two-faced behavior, don't you think so?
Anti-private and anti-secure, harms the users, and donates data to one of the most powerful cyber-criminal coprorations on the planet!
This messenger cannot be called private and secure, as long as it has this nonsense.
Don't know what else to say, this is smth I absolutely didn't expect.
(Bonus: the program is unusable for those who have a hardened setup with google-booble IPs blocked system-wide)
(PS: isn't email verification enough? it is enough)

#### What happened instead?
Captcha provided by a malware/spyware service made by one of the biggest privacy/security enemies (google).

### Your phone model

N/A

### Operating system version

N/A

### Application version and app store

1.6.3 from F-Droid

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by ninja85a** [comment]
yeah servers you sign up on decide if they want to use captcha not element android itself

**Comment by bmarty** [comment]
Thanks @fd1f and @ninja85a for the answers!
