### ISSUE TITLE
The exciting launch of Element X, 

### ISSUE THREAD

**Issue by AnassDriate** [vector-im/element-android#8606]
### Steps to reproduce

Hello,

With the exciting launch of Element X, I'm curious about the support status for the original version of Element.io (this repo). Could you please clarify if the original version will continue to receive support, and if so, for how long?

Thank you for your time.

Best regards,

### Outcome

Support of Element IO

### Will you send logs?

Yes

### Are you willing to provide a PR?

Yes

**Comment by manuroe** [comment]
This repo and this version of the element app is in maintenance mode. We are only fixing security issues and high priority bugs.
We currently have the 2 apps in the store: `Element` and  `Element X`. When ready, the `Element` app will use the `Element X` code. `Element X` is a temporary app using a code name.

**Comment by Tecol87** [comment]
> When ready, the Element app will use the Element X code.

So when it is ready, the Element X app will be deleted from the playstore?
Will the Element app migrate its data when it uses Elemt X source code or will there be a re-login needed?

**Comment by manuroe** [comment]
> Is there like a rough guesstimate when it is going to happen?

We do not have a public date yet. Our product team is defining what production ready means for Element X. We are putting the bar in terms of UX and quality for Element X much more higher than for the previous Element apps. It takes time to define what should be the right scope of the new app before switching. But the sooner we can switch, the better for everyone (users and us).

> So when it is ready, the Element X app will be deleted from the playstore? I did not see a notice in the play store but think users should know.

Yes, Element X will be replaced at some point to avoid confusions. You are right we need to be more transparent about it in the store description (cc @nadonomy).
We will inform Element X users within the app in advance.

> Will the Element app migrate its data when it uses Element X source code or will there be a re-login needed?

The migration will be transparent for Element users. There will no need to re-login. 
There might be some crypto setup to do if the user is not using the default crypto behaviour advised in the current app. We want to make the crypto simpler to handle in EX for most users. It will start with less options before we extend them according to different persona levels.

**Comment by Tecol87** [comment]
@manuroe 
Sounds good, thank you very much for the clarification.

**Comment by Croydon** [comment]
> When ready, the Element app will use the Element X code. Element X is a temporary app using a code name.

@manuroe Is this still the case? AFAIK the plan changed and everyone has to migrate to Element X eventually, right?

**Comment by su-sd** [comment]
>  The migration will be transparent for Element users. There will no need to re-login.

Since on creating an account, Element users are instructed to use Element X, is this still up2date?

**Comment by manuroe** [comment]
> > The migration will be transparent for Element users. There will no need to re-login.
> 
> Since on creating an account, Element users are instructed to use Element X, is this still up2date?

We actually changed our plan. The migration in place would be too much work. It is not easy to migrate all data from one codebase to another, especially crypto data. It would be risky and stressful to make it.
Instead of a disruptive hard switch, users will be invited more and more to use EX.

**Comment by jakecornet** [comment]
Is there a git repo and issue tracker for Element X yet?  I would like to contribute to testing and reporting.

**Comment by manuroe** [comment]
it is https://github.com/element-hq/element-x-android/.
