### ISSUE TITLE
EA: Link to MAS for sign-out of other devices in MSC3824 OIDC-aware mode

### ISSUE THREAD

**Issue by hughns** [vector-im/element-android#8616]
Element Android was [previously](https://github.com/vector-im/element-android/pull/7920) made "OIDC-aware" (as described by [MSC3824](https://github.com/matrix-org/matrix-spec-proposals/pull/3824)).

In the case of OIDC-aware clients, you cannot sign out of _other_ sessions via the device manager in EA anymore. Instead, users will need to be guided towards the MAS UI to take this actions.

[MSC3824](https://github.com/matrix-org/matrix-spec-proposals/pull/3824) now describes this requirement including a format of a deep link structure to pass the device ID: `?action=session_end&device_id=<device_id>`

**Comment by pmaier1** [comment]
- We should add wording to let the user understand what's happening: "You will be redirected to your server's authentication provider to complete sign out."
- If the server doesn't advertise an account management URL, the client should show a message saying that the user should contact the administrator.

**Comment by pmaier1** [comment]
This is how iOS implements it https://github.com/vector-im/element-ios/pull/7658

**Comment by pmaier1** [comment]
@bmarty from testing, we've found that there is no prompt to let the user know what's actually happening, ref. https://github.com/vector-im/element-android/issues/8616#issuecomment-1693056095. Can you check?

**Comment by pmaier1** [comment]
@manuroe Can you link the PR that solves https://github.com/vector-im/element-android/issues/8616#issuecomment-1719282555, please?

**Comment by bmarty** [comment]
> @manuroe Can you link the PR that solves [#8616 (comment)](https://github.com/vector-im/element-android/issues/8616#issuecomment-1719282555), please?

This has not been done. I have created https://github.com/vector-im/element-android/issues/8647 to handle it.

**Comment by hughns** [comment]
I'm closing this issue as #8647 has the remaining work
