### ISSUE TITLE
Unable to connect to home server URL

### ISSUE THREAD

**Issue by beckend** [vector-im/element-android#8617]
### Steps to reproduce

1. Select your server, type in URL
2. Press Next
3. Red - Unrecongnized request

This works fine in app.element.io.

Server info:

<img width="471" alt="Screenshot 2023-08-20 134410" src="https://github.com/vector-im/element-android/assets/6056334/0656ebf3-7c65-4227-9975-161b83b0a9e5">

In the server logs, nothing is received, federation is not enabled, not willing to expose to public server.

#### What did you expect?
Should connect like app.element.io

#### What happened instead?
Unrecongnized Request when entering server URL, in the server logs, nothing is received.

### Your phone model

Google Pixel 7 Pro

### Operating system version

13

### Application version and app store

Not possible since you need to be connected to a server, latest from app store.

### Homeserver

dendrite 9a12420

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by mike-pisman** [comment]
Same issue, also running dendrite. iOS version of element connected without a problem, and a different android client(fluff chat) managed to connect. So it's really seems like the android version issue. I have checked the logs, but don't see anything related.

**Comment by randyg503** [comment]
for me, 'well_known_client_name:' dendrite config entry was missing/empty. Setting it resolved my 'unrecognized request' error on android element.

**Comment by beckend** [comment]
I can confirm setting it to my "subdomain.domain.tld" works.

**Comment by dopemike** [comment]
Confirm, had the same issue on android and running dendrite. Changing "well_known_client_name" to "https://subdomain.mydomain.net" worked!
