### ISSUE TITLE
EA: The app should hide account deactivation in OIDC-aware mode

### ISSUE THREAD

**Issue by pmaier1** [vector-im/element-android#8619]
In a native OIDC environment, account deactivation does not work anymore via `/account/deactivate`. For this reason, the feature should be hidden in the UI according to [MSC2964](https://github.com/sandhose/matrix-doc/blob/msc/sandhose/oauth2-profile/proposals/2964-oauth2-profile.md#removal-of-endpoints).

Screenshot from Web to make this more clear:

<img width="477" alt="image" src="https://github.com/vector-im/element-android/assets/21193500/9b248c7a-a0bc-42bb-bc50-9a8b20b7c87d">

@bmarty @hughns

**Comment by bmarty** [comment]
@pmaier1 should the UI be hidden, or should it opens the account manager on a specific page?

**Comment by pmaier1** [comment]
Hmm, we generally decided to hide it as there already is a way/button to "manage account" in OIDC-aware mode that would guide you to the MAS web UI. Not sure whether this is an issue for the Google policy.
