### ISSUE TITLE
RustCrypto breaks Sign in with QR feature

### ISSUE THREAD

**Issue by hughns** [vector-im/element-android#8653]
The `RustCrypto.setDeviceVerification()` function [does not have an implementation](https://github.com/vector-im/element-android/blob/1b3be240b3c67907672217a45225aec014a2a05c/matrix-sdk-android/src/rustCrypto/java/org/matrix/android/sdk/internal/crypto/RustCryptoService.kt#L539) which breaks the [Sign in with QR feature](https://github.com/vector-im/element-android/blob/5f185c51e7019b68613b23dc537d940f77dfe25c/matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/rendezvous/Rendezvous.kt#L213).

Can we get this implemented or is there an alternative function to use?

**Comment by BillCarsonFr** [comment]
I don't think you need to set local trust at all?
The other device is cross signed, and if you trust the master key now, you 'll trust it because it's signed by the now trusted SSK

**Comment by hughns** [comment]
> I don't think you need to set local trust at all? The other device is cross signed, and if you trust the master key now, you 'll trust it because it's signed by the now trusted SSK

As per offline conversation: it is intended that the Sign in with QR function works with a deployment that isn't using cross-signing. As such, this is the point in setting the existing device as locally trusted after the new device has signed in.

**Comment by BillCarsonFr** [comment]
It's not the only API not available in rust https://github.com/vector-im/element-android/blob/1b3be240b3c67907672217a45225aec014a2a05c/matrix-sdk-android/src/rustCrypto/java/org/matrix/android/sdk/internal/crypto/SecretShareManager.kt#L28

**Comment by BillCarsonFr** [comment]
> deployment that isn't using cross-signing

A lot of things expect cross signing nowadays. How can you disable it? there is a setting?

**Comment by hughns** [comment]
> A lot of things expect cross signing nowadays. How can you disable it? there is a setting?

Yes, you can make it so that the Element clients don't prompt to set up cross-signing (nor automatically set it up).
