### ISSUE TITLE
App crashes when inserting blank line after emoji in WYSIWYG composer

### ISSUE THREAD

**Issue by giomfo** [vector-im/element-android#8664]
### Steps to reproduce

1. Enable the new WYSIWYG composer
2. Writing a message
3. add an emoji to the message
4. after the emoji, press 2x Enter  -> insert blank line (ok)
5. continue writing text on the new line

#### What did you expect?
One can continue writing text in the expected line

#### What happened instead?
The app crashes
(sometimes the first message and the emoji are deleted)

### Application version and app store

v1.6.5

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by jonnyandrew** [comment]
This has been fixed in https://github.com/matrix-org/matrix-rich-text-editor/pull/824.

We'll need to update the rich text editor to v2.14.0 to get this in Element Android.

**Comment by giomfo** [comment]
fixed by https://github.com/vector-im/element-android/pull/8607
