### ISSUE TITLE
Inconsistent room joining behavior (in comparison with Element Web)

### ISSUE THREAD

**Issue by etkecc** [vector-im/element-android#8677]
### Steps to reproduce

1. Use `matrixrooms.info` as directory server
2. Try to join any room
3. Element Android sends `GET /_matrix/federation/v1/make_join/ROOM_ID/MATRIX_USER_ID?ver=1&ver=2&ver=3&ver=4&ver=5&ver=6&ver=7&ver=8&ver=9&ver=10&ver=11 HTTP/1.1` request to the directory server, ignoring the fact the `ROOM_ID` is from another server

#### What did you expect?

Identical behavior with Element Web, i.e. `make_join` is sent to the room's resident server

#### What happened instead?

Element Android sends `make_join` to the directory server, even when room is located on a different server.

### Your phone model

N/A

### Operating system version

N/A

### Application version and app store

Element 1.6.6.sc73 (F-Droid), Matrix SDK 1.6.6, Crypto Rust SDK 0.6.0, Crypto Vodozemac 0.4.0

### Homeserver

matrixrooms.info (MRS latest)

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by julioromano** [comment]
Does Element Android succeed in joining the room ?

**Comment by julioromano** [comment]
I've just succeeded joining a room from `matrixrooms.info` by both opening the directory server  from a web browser and clicking a room's matrix.to link and also by using matrixrooms.info as directory in element android.

Though I've used element from the Play Store.
Can you please double check with that as well to try to ascertain if it's an F-droid distro issue?

If you still see the issue then can you post a video that can show us the exact steps you take to repro?

**Comment by akdk7** [comment]
Just tried to join a room on frei.chat using my frei.chat account via the matrixrooms.info list. Unfortunately it didn't work. On Element Android it shows the little check mark, but the room does not appear in the list of joined rooms.

**Comment by akdk7** [comment]
Interesting, 4 days later it works now. Cannot tell why Element (Android 14) didn't want to join channels. Thanks though :)
