### ISSUE TITLE
Completely hide all non message events from conversation

### ISSUE THREAD

**Issue by EmmanuelMess** [vector-im/element-android#870]
It would be nice to have the option to hide everything that is not a message.
Hide things such as joins, exits, name changes, avatar changes, etc.

**Comment by BillCarsonFr** [comment]
We should probably align on web for filtering settings

<img width="589" alt="image" src="https://user-images.githubusercontent.com/9841565/89660248-61df2580-d8d1-11ea-945a-4e6050ea806b.png">

Also those events should not affect room ordering and unread message indicator 
(to avoid xxx changed their avatar making all room as unread and jump to top)

**Comment by bmarty** [comment]
I think this is handled by #3088.

**Comment by bmarty** [comment]
(availalbe in Element 1.1.4)
