### ISSUE TITLE
Tapping on an unloaded image stalls the UI

### ISSUE THREAD

**Issue by fbruetting** [vector-im/element-android#885]
`v0.13`

When I scroll up, sometimes images don’t get loaded immediately (even though I guess they are cached locally?). When I tap on such a placeholder which lacks its image, the UI freezes. I then have to either tap on Android’s “back” button, or wait until the image loads up, and then there is some chance that then tapping a second time on the image enlarges it and unfreezes the UI.

**Comment by bmarty** [comment]
Yes, I've seen that too, easier to reproduce under low bandwidth network connection

**Comment by onurays** [comment]
Couldn't reproduce anymore. `v1.0.14-dev`
