### ISSUE TITLE
Sharing a picture via Riot/X fails. It worked in Riot.im

### ISSUE THREAD

**Issue by the-moog** [vector-im/element-android#886]
If I take a photo, press share then select a room I get a red excamation mark rather than a picture.
In Riot.im this works ok, the picture is posted to the room.

You also used to get a prompt to decide what size picture to share.

**Comment by bmarty** [comment]
We will check that, thanks

**Comment by bmarty** [comment]
Please check with upcoming RiotX v0.17.0 if it works better

**Comment by the-moog** [comment]
I'll test it but won't use Riot/X until it supports configurable identity servers.  We use features of MA1SD/MXISD that we can't do without.

**Comment by LeoniePhiline** [comment]
I cannot send pictures any more since 0.17.

I get "Waiting..." and an indeterminate progress bar which will never resolve.
A long press shows a bottom sheet saying "Sending message".

![Screenshot_20200305_110325_im vector riotx](https://user-images.githubusercontent.com/22329650/75970794-2b8c1d00-5ed1-11ea-97d4-e431862c060e.jpg)

**Comment by dreamerchris** [comment]
Same here, I made a screenshot and pressed send from the phone gallery to riotx app then selected the room to send it and first time it timedout second time still waiting after more than 10 minutes

![Screenshot_2020-03-06-18-44-21-980_im vector riotx](https://user-images.githubusercontent.com/51272727/76103590-99703b80-5fda-11ea-86a2-6cc9b05bef0e.jpg)
![Screenshot_2020-03-06-18-44-41-520_im vector riotx](https://user-images.githubusercontent.com/51272727/76103609-9f661c80-5fda-11ea-8c16-ddc7931902d5.jpg)

**Comment by dreamerchris** [comment]
Same after clear cache

**Comment by LeoniePhiline** [comment]
I'm already waiting for two days.

It's pretty nasty having to scroll up by 14 pretending-to-be-sending images just to see the newest messages in the 1:1 chat.

If at least the pictures were sorted at their send dateTime rather than always appear at the bottom, that would make things better.

There's also no way to cancel sending of single items or clear the entire queue.

**Comment by Dragnucs** [comment]
I am also stuck with this. I tried sending some video from the gallery. This usually works without issue, but today, I had a network issue and the phone switched from the slow Wi-Fi to mobile data, thus interrupting the upload. The video is still sending for a few hours now.

**Comment by Dragnucs** [comment]
I got rid of the pending upload by deleting the file then clearing the cache from the application settings. I am not sure if the file deletion did help.

**Comment by LeoniePhiline** [comment]
I tried that, but it didn't work for me unfortunately. 

I have ~15 pics stalled at upload and clogging my conversation - and no way to remove them. :(

**Comment by Dragnucs** [comment]
@LeoniePhiline have you tried the option from Android or RiotX? The one that worked for me is RiotX > drawer > Account settings > General > Clear cache > restart the application.

**Comment by LeoniePhiline** [comment]
This worked! Fantastic. Yeah I had previously cleared the cache via the Android Apps Settings - that had not had any effect.

**Comment by LeoniePhiline** [comment]
So I tried sending a new photo, and it again got stalled right away.
Can I help with any log output etc. to see why they get stuck? I have already had success sending pics, so it's not a general problem, but a very very common one.

**Comment by Dragnucs** [comment]
It seems to happen a lot on slow or intermittent connexion. I send. A lot of pictures and most of the time it works. I have 4G.

**Comment by LeoniePhiline** [comment]
I also observed this happening when switching between 4G and wifi while pics were meant to be uploaded.

But it also happened to me at home in wlan where i did not observe any connection flakiness at that time.

**Comment by Bubu** [comment]
I just sent a rageshake for this.I could send a picture into one chat but couldn't upload any into another chat.

**Comment by bmarty** [comment]
Sending of attachment has been reworked, feel free to re-open the issue or to open a new one if you still have pb about that.
