### ISSUE TITLE
SSO useragent

### ISSUE THREAD

**Issue by tdaede** [vector-im/element-android#899]
auth0 has a useragent check on the Webauthn login flow. The webview used for SSO should use one of the useragents that auth0 recognizes.

**Comment by bmarty** [comment]
Which user agent (or format) is expected by auth0?

**Comment by tdaede** [comment]
I'm not sure, but at least using Firefox for Android's useragent seems to work. I could try looking in the JS.

**Comment by bmarty** [comment]
Now that we are using CustomChromeTab and not a webview anymore to display the SSO web page, I assume this issue is not relevant anymore. Feel free to re-open it if it is not case.
