### ISSUE TITLE
Automatic dark theme

### ISSUE THREAD

**Issue by Yajo** [vector-im/element-android#904]
Nowadays android devices have a night mode which autotriggers dark mode in supporting apps. Riot should support that. Given it has light and dark themes, it should just autoswitch it depending on the OS setting.

**Comment by igalic** [comment]
this would then only leave the choice of which light / dark theme one wants, and i think Tachiyomi does this pretty well:
![Screenshot of Tachiyomi Gebetskette settings, including the display and theme settings](https://user-images.githubusercontent.com/497249/83347140-1d5c6a00-a323-11ea-95c3-8b438991aca7.jpg)

**Comment by ShadowJonathan** [comment]
@bmarty can this be set on a project or milestone?

**Comment by bmarty** [comment]
We have other priorities, but any contribution will be appreciated :)

**Comment by 532910** [comment]
Is there a way to detect dark theme type: gray or pure black?

**Comment by proletarius101** [comment]
> Is there a way to detect dark theme type: gray or pure black?

The dark themes are not properly implemented. Actually light/dark variation should be implemented by https://material.io/develop/android/theming/dark. The gray/black varients should be implemented by different themes (with inheritance)
