### ISSUE TITLE
Iterate on typing UX

### ISSUE THREAD

**Issue by bmarty** [vector-im/element-android#947]
Riot-Web add this at the bottom of the timeline, which is pretty fine:

<img width="500" alt="image" src="https://user-images.githubusercontent.com/3940906/73677419-7d653b80-46b6-11ea-82b2-8ab3c1cb6081.png">

The first implementation of typing replace the toolbar subtitle, which is not efficient, but has the advantage of being visible if user scroll to the past, and to leave more space for the timeline messages

**Comment by violoncelloCH** [comment]
I'd argue the current approach to be nice because this way it doesn't take away additional space in the UI which is anyway very limited on small phone screens... I'd rather want to have that space for viewing the chat (esp while typing) than a bar like in old Riot-Android)

**Comment by bmarty** [comment]
Yes, I've updated the description.

**Comment by bmarty** [comment]
Nobody complains about that, let's close this issue then!
