### ISSUE TITLE
draft gets deleted when you start typing directly after sending a reply

### ISSUE THREAD

**Issue by lub** [vector-im/element-android#952]
Steps to reproduce:

1. send a messageA
2. swipe on messageA to go into reply mode
3. (the reply preview appears)
4. type some text and tap on submit to send messageB
5. (the input box is now cleared but the reply preview above the input box is still displayed)
6. type some text to compose messageC
7. (messageB gets local echoed, the reply preview is removed and messageC is deleted from the input box)

I think it makes sense to completely clear the composer including the reply preview at step 5, so you can start typing a new message right away.

**Comment by Skirmisher** [comment]
In my experience, this behavior appears right after sending *any* message, not just a reply.

**Comment by BillCarsonFr** [comment]
Reported in element android room:
> I'm regularly getting a nasty problem where I type a message, send it, then start typing the next one and a few seconds into typing it, Element just clears rhe text entry box and deletes everything I was typing
