### ISSUE TITLE
Room invites (friend requests) don’t emit notifications

### ISSUE THREAD

**Issue by fbruetting** [vector-im/element-android#960]
v0.14.3

My friend had to open the app for seeing my invitation, after we waited some time for a notification. It was a completely new account (but RiotX was opened some time before, so it was active).

**Comment by silvolivi** [comment]
i'm adding a comment to this (as i'm using element in a "experimental" server not administrated by me)

it seems that when an user is banned from a private room, and then unbanned and reinvited, invite only is notificated when the account from app is disconnected and reconnected again..

**Comment by daniellekirkwood** [comment]
I believe this is fixed so am marking this to be closed. If it's still not working as you'd expect, comment and we'll look into it for you!

**Comment by bmarty** [comment]
The notification for room invite could be improved, but they are displayed properly.
