### ISSUE TITLE
Restore linkification of room alias, userId, group id

### ISSUE THREAD

**Issue by bmarty** [vector-im/element-android#972]
They have been disabled after my work on pills because of a bug. I'll put here a link on the corresponding commit later.

The pb was that the linkification occurred after the pills treatment and so link was added twice (inside the of the pill content)

Expected behavior:

When user types

> #roomAlias:matrix.org

The link should be added to the whole string. Currently it's added only on the matrix.org text

**Comment by rubo77** [comment]
![Screenshot_20200722-002249_Element (Riotim)](https://user-images.githubusercontent.com/1591563/88113183-994f9180-cbb1-11ea-8a35-c55ff63c2b2d.jpg)


The same problem if you have a link to another room in the room description
